1. Данный ноутбук позволяет планировать ТО на ближайшие 100 м/ч
2. Контроль проведеного ТО

In [4]:
import os
import pandas as pd
import numpy as np 
import warnings
import re 
import glob
import datetime
pd.set_option("display.max_rows", 10)
pd.set_option("display.max_columns", 10)
pd.set_option("display.precision", 100)

warnings.filterwarnings('ignore', category=UserWarning, module='openpyxl')
current_dir=os.path.dirname(os.path.abspath("__file__"))
# df=pd.read_excel(r'\\192.168.91.92\maintenance\Агрегатный журнал сводный(Power Query).xlsx', "Реестр")
# df_agr=pd.read_excel(os.path.join(current_dir, 'Агрегатный журнал ОГМ 2024 (Эрел) (4).xlsx'), "Агрегатный журнал")

In [5]:
# df=df_agr.copy()
# дата с которой начинается планирование
t='2026-03-10'

In [6]:
directory = r'c:\Users\poisk-12\Documents\$Мониторинг\Агрегатный'
#directory = '/Users/alexei/Yandex.Disk.localized/Analisys/Excel/Агрегатный журнал'
file_pattern = '*.xlsx'
#files2 = [item for item in glob.glob(f'{directory}\\{file_pattern}')]
files2 = [item for item in glob.glob(f'{directory}/{file_pattern}')]
files2 = [item for item in files2 if 'Агрегатный журнал' in item]

In [7]:
df2 = pd.DataFrame()
for file in files2:
     file = pd.read_excel(file, sheet_name='Агрегатный журнал')                         
     df2 = pd.concat([df2, file])

In [8]:
df=df2.copy()

In [9]:
df['Дата начала обслуживания']=pd.to_datetime(df['Дата начала обслуживания'], errors='coerce')

In [10]:
df['Месяц_ном'] = df['Дата начала обслуживания'].dt.month
df['Год'] = df['Дата начала обслуживания'].dt.year
df=df.rename(columns={'Марка или обозначение техники':'Марка'})

In [11]:
df=df.loc[df['Год']>=2025]

In [12]:
df=df.rename(columns={'Наработка машины':'Наработка машины'})
df=df.rename(columns={'Показания прибора учета':'Фактическая наработка в момент проведения ТО'})

##### === нормализация столбца марка техники ===

In [13]:

targets = ['1288', '1289', '1290', '1310']
# матч как отдельное число, а не часть большего (например, 11288)
pat = re.compile(rf'(?<!\d)(?:{'|'.join(map(re.escape, targets))})(?!\d)')
mask = df['Инвентарный номер'].astype(str).str.contains(pat, na=False)
df.loc[mask, 'Марка'] = 'CLG975F'

targets=['1251', '1252']
pat = re.compile(rf'(?<!\d)(?:{'|'.join(map(re.escape, targets))})(?!\d)')
mask = df['Инвентарный номер'].astype(str).str.contains(pat, na=False)
df.loc[mask, 'Марка'] = "CLG942EHD"

targets=['1247', '1249']
pat = re.compile(rf'(?<!\d)(?:{'|'.join(map(re.escape, targets))})(?!\d)')
mask = df['Инвентарный номер'].astype(str).str.contains(pat, na=False)
df.loc[mask, 'Марка'] = "CLG877H"

targets=['1199']
pat = re.compile(rf'(?<!\d)(?:{'|'.join(map(re.escape, targets))})(?!\d)')
mask = df['Инвентарный номер'].astype(str).str.contains(pat, na=False)
df.loc[mask, 'Марка'] = "D55"

targets=['1183']
pat = re.compile(rf'(?<!\d)(?:{'|'.join(map(re.escape, targets))})(?!\d)')
mask = df['Инвентарный номер'].astype(str).str.contains(pat, na=False)
df.loc[mask, 'Марка'] = "SG21A_3"

targets=['1185', '1304']
pat = re.compile(rf'(?<!\d)(?:{'|'.join(map(re.escape, targets))})(?!\d)')
mask = df['Инвентарный номер'].astype(str).str.contains(pat, na=False)
df.loc[mask, 'Марка'] = "SD22"

targets=['702', '703', '704']
pat = re.compile(rf'(?<!\d)(?:{'|'.join(map(re.escape, targets))})(?!\d)')
mask = df['Инвентарный номер'].astype(str).str.contains(pat, na=False)
df.loc[mask, 'Марка'] = 'TM10.11 ГСТ10'

targets=['652', '653']
pat = re.compile(rf'(?<!\d)(?:{'|'.join(map(re.escape, targets))})(?!\d)')
mask = df['Инвентарный номер'].astype(str).str.contains(pat, na=False)
df.loc[mask, 'Марка'] = 'TM10.11 ГСТ12'

mask=df['Марка'].astype(str).isin(["SHANTUI SG21A-3",'Shantui '])
df.loc[mask, 'Марка'] = 'SG21A_3'

mask=df['Марка'].astype(str).isin(["SHANTUI SG21A-3",'Shantui '])
df.loc[mask, 'Марка'] = 'SG21A_3'


mask=df['Марка'].astype(str).isin(['Shantui SD22', 'Shantui SD23'])
df.loc[mask, 'Марка'] = "SD22"

In [14]:
df

,Подразделение,Тип машины,Марка,Модификация,Инвентарный номер,...,Замечания проверяющего,Отметка об утверждении акта (ФИО утвердившего),Дата утверждения,Месяц_ном,Год
21,Дымный,Бульдозер,TD-16,NaN,902.0,...,NaN,NaN,NaN,3.0,2025.0
22,Дымный,Бульдозер,TD-16,NaN,902.0,...,NaN,NaN,NaN,3.0,2025.0
23,Дымный,Бульдозер,TD-16,NaN,902.0,...,NaN,NaN,NaN,3.0,2025.0
24,Дымный,Бульдозер,TD-16,NaN,902.0,...,NaN,NaN,NaN,3.0,2025.0
25,Дымный,Экскаватор,PC-800,8,913.0,...,NaN,NaN,NaN,3.0,2025.0
...,...,...,...,...,...,...,...,...,...,...,...
446,Эрел,Буровой станок,Беркут,УБГ-С 30,931,...,NaN,NaN,NaN,3.0,2026.0
447,Эрел,Прочее,Платформа грузовая,ПГ-26,1020,...,NaN,NaN,NaN,3.0,2026.0
448,Эрел,Станция компрессорная,Компрессор,LUY100-12,1250,...,NaN,NaN,NaN,3.0,2026.0
449,Эрел,Бульдозер,D-65,EX-16,912,...,NaN,NaN,NaN,3.0,2026.0
450,Эрел,Автомойка,АВД ПОСЕЙДОН,NaN,1240,...,NaN,NaN,NaN,3.0,2026.0

In [15]:
s = pd.to_numeric(df['Инвентарный номер'], errors='coerce')
s = s.round()                                          # или .floor() / .ceil()
df['Инвентарный номер'] = s.astype('Int64')

In [16]:
s = (df['Инвентарный номер']
       .astype(str)
       .str.replace('\xa0', '', regex=False)   # убрать NBSP
       #.str.replace(',', '', regex=False)      # убрать разделители тысяч
       .str.strip()
       .str.replace(r'\D+', '', regex=True)    # убрать всё, что не цифры
       .replace('', pd.NA)                     # пустое -> NA
)

df['Инвентарный номер'] = pd.to_numeric(s, errors='coerce').astype('Int64')

In [17]:
df

,Подразделение,Тип машины,Марка,Модификация,Инвентарный номер,...,Замечания проверяющего,Отметка об утверждении акта (ФИО утвердившего),Дата утверждения,Месяц_ном,Год
21,Дымный,Бульдозер,TD-16,NaN,902,...,NaN,NaN,NaN,3.0,2025.0
22,Дымный,Бульдозер,TD-16,NaN,902,...,NaN,NaN,NaN,3.0,2025.0
23,Дымный,Бульдозер,TD-16,NaN,902,...,NaN,NaN,NaN,3.0,2025.0
24,Дымный,Бульдозер,TD-16,NaN,902,...,NaN,NaN,NaN,3.0,2025.0
25,Дымный,Экскаватор,PC-800,8,913,...,NaN,NaN,NaN,3.0,2025.0
...,...,...,...,...,...,...,...,...,...,...,...
446,Эрел,Буровой станок,Беркут,УБГ-С 30,931,...,NaN,NaN,NaN,3.0,2026.0
447,Эрел,Прочее,Платформа грузовая,ПГ-26,1020,...,NaN,NaN,NaN,3.0,2026.0
448,Эрел,Станция компрессорная,Компрессор,LUY100-12,1250,...,NaN,NaN,NaN,3.0,2026.0
449,Эрел,Бульдозер,D-65,EX-16,912,...,NaN,NaN,NaN,3.0,2026.0
450,Эрел,Автомойка,АВД ПОСЕЙДОН,NaN,1240,...,NaN,NaN,NaN,3.0,2026.0

In [18]:
df_narabotka=df.copy()

##### === считаем наработку ===

In [19]:
# создание сводной таблицы
pivot_table = pd.pivot_table(df,values=['Дата начала обслуживания'], 
                             index=['Подразделение','Марка','Модификация','Инвентарный номер','Фактическая наработка в момент проведения ТО', 'Наработка машины'], 
                             
                             aggfunc={'Дата начала обслуживания': 'last'})




pivot_table = pivot_table.round(2)
pivot_table = pivot_table.fillna(0)
pivot_table = pivot_table.reset_index()

In [20]:
keys = ['Подразделение','Марка', 'Модификация','Инвентарный номер']
vals = ['Фактическая наработка в момент проведения ТО','Наработка машины']

# выбираем, какая колонка дата есть в таблице
date_col = next(c for c in ['Дата','Дата планирования','Дата начала обслуживания'] if c in pivot_table.columns)

# df = pivot_table.copy()
df[date_col] = pd.to_datetime(df[date_col], errors='coerce')

# индексы строк с максимальной датой по каждой группе
idx = df.groupby(keys)[date_col].idxmax()

# берём нужные столбцы + дату
pivot_table = (df.loc[idx, keys + [date_col] + vals]
       .rename(columns={date_col: 'Дата начала обслуживания'})
       .sort_values(keys)
       .reset_index(drop=True))

# если нужно показывать только календарную дату без времени:
# t['Последняя дата'] = t['Последняя дата'].dt.date

In [21]:
pivot_table

,Подразделение,Марка,Модификация,Инвентарный номер,Дата начала обслуживания,Фактическая наработка в момент проведения ТО,Наработка машины
0,Дражный,CLG877H,LG G877H,1249,2025-10-17,2100,2100
1,Дражный,CLG877H,LG G877H,1249,2025-09-06,1489,1489
2,Дражный,CLG877H,LG G877H,1249,2025-09-23,1700,1700
3,Дражный,CLG877H,LG G877H,1249,2025-09-20,1680,1680
4,Дражный,CLG877H,LG G877H,1249,2025-09-27,1800,1800
...,...,...,...,...,...,...,...
844,Эрел,ЭД,400,476,2025-10-12,17458.0,17458.0
845,Эрел,ЭД,400,476,2026-03-08,17458.0,17458.0
846,Эрел,ЭД,400,596,2025-10-12,19927.0,19927.0
847,Эрел,ЭД,400,596,2026-03-05,19927.0,19927.0
848,Эрел,ЭД,400,596,2026-03-08,19927.0,19927.0

In [22]:
# 2) Индексы строк с последней датой по каждому инв. номеру
idx = df.groupby('Инвентарный номер')['Дата начала обслуживания'].idxmax()
# 3) Берём только «последние» строки
last_per_inv = df.loc[idx]

# 4) привести, если модификация равна пусто, то поставить 1
last_per_inv['Модификация'] = last_per_inv['Модификация'].fillna(1)

# 5) Сводная
pivot_table = (pd.pivot_table(
    last_per_inv,
    values=['Наработка машины','Дата начала обслуживания','Фактическая наработка в момент проведения ТО'],
    index=['Подразделение','Марка', 'Модификация','Инвентарный номер',],
    aggfunc='first'
).reset_index())

pivot_table = pivot_table.round(2).fillna(0)

In [23]:
pivot_table["Дата начала обслуживания"]=pd.to_datetime('2026-03-10', format='%Y-%m-%d', errors='coerce')

##### === определеяем когда какая техника запускается ===

In [24]:
# основание файл от Механиков и ПТО
targets=['701', '665', '1251', '1148', '1084','1156','661','658','1151','1152','903','1252','916', '789','790','1185','597','675','603','691','960','702','711','1288','678','688','1187','1082','660','664', '915','697',
         '1158', '1157','1159','600','1184',]
pat = re.compile(rf'(?<!\d)(?:{'|'.join(map(re.escape, targets))})(?!\d)')
mask = pivot_table['Инвентарный номер'].astype(str).str.contains(pat, na=False)
pivot_table.loc[mask, 'Дата начала обслуживания'] = pd.to_datetime('2026-04-01', format='%Y-%m-%d', errors='coerce')

targets=['676', '1078', '466','965','690','1312','1311','1153','1160','1161', '720','681','1247']
pat = re.compile(rf'(?<!\d)(?:{'|'.join(map(re.escape, targets))})(?!\d)')
mask = pivot_table['Инвентарный номер'].astype(str).str.contains(pat, na=False)
pivot_table.loc[mask, 'Дата начала обслуживания'] = pd.to_datetime('2026-05-01', format='%Y-%m-%d', errors='coerce')

targets=['1024', '1249', '719', '693',  ]
pat = re.compile(rf'(?<!\d)(?:{'|'.join(map(re.escape, targets))})(?!\d)')
mask = pivot_table['Инвентарный номер'].astype(str).str.contains(pat, na=False)
pivot_table.loc[mask, 'Дата начала обслуживания'] = pd.to_datetime('2026-06-01', format='%Y-%m-%d', errors='coerce')

##### === определить какая техника дублируется по подразделениям ===

In [25]:
pivot_table.groupby(['Марка', 'Модификация','Инвентарный номер' ]).count()

                                               Подразделение  \
Марка         Модификация   Инвентарный номер
BIGATV Falcon 1309          1309                           1
CASE          CX-800B       674                            1
CLG877H       877H          1247                           1
              LG G877H      1249                           1
CLG942EHD     CLG942EHD     1252                           1
...                                                      ...
Урал АТЗ      1             295                            1
Урал кран     КС-55713-3К-4 375                            1
ЭД            400           476                            1
                            596                            1
ЭКГ           5А            169                            1

                                               Дата начала обслуживания  \
Марка         Модификация   Инвентарный номер
BIGATV Falcon 1309          1309                                      1
CASE          CX-800B       674                                       1
CLG877H       877H          1247                                      1
              LG G877H      1249                                      1
CLG942EHD     CLG942EHD     1252                                      1
...                                                                 ...
Урал АТЗ      1             295                                       1
Урал кран     КС-55713-3К-4 375                                       1
ЭД            400           476                                       1
                            596                                       1
ЭКГ           5А            169                                       1

                                               Наработка машины  \
Марка         Модификация   Инвентарный номер
BIGATV Falcon 1309          1309                              1
CASE          CX-800B       674                               1
CLG877H       877H          1247                              1
              LG G877H      1249                              1
CLG942EHD     CLG942EHD     1252                              1
...                                                         ...
Урал АТЗ      1             295                               1
Урал кран     КС-55713-3К-4 375                               1
ЭД            400           476                               1
                            596                               1
ЭКГ           5А            169                               1

                                               Фактическая наработка в момент проведения ТО
Марка         Модификация   Инвентарный номер
BIGATV Falcon 1309          1309                                                          1
CASE          CX-800B       674                                                           1
CLG877H       877H          1247                                                          1
              LG G877H      1249                                                          1
CLG942EHD     CLG942EHD     1252                                                          1
...                                                                                     ...
Урал АТЗ      1             295                                                           1
Урал кран     КС-55713-3К-4 375                                                           1
ЭД            400           476                                                           1
                            596                                                           1
ЭКГ           5А            169                                                           1

[283 rows x 4 columns]

In [26]:
pivot_table

,Подразделение,Марка,Модификация,Инвентарный номер,Дата начала обслуживания,Наработка машины,Фактическая наработка в момент проведения ТО
0,Дражный,CLG877H,LG G877H,1249,2026-06-01,1700,1700
1,Дражный,CLG942EHD,LG-G942E,1251,2026-04-01,2800,2800
2,Дражный,CLG975F,LG-G975F,1310,2026-03-10,2450,2450
3,Дражный,D-375,6,818,2026-03-10,14241,14241
4,Дражный,D-375,5D,697,2026-04-01,38750,38750
...,...,...,...,...,...,...,...
294,Эрел,СБШ-250,МНА32,1105,2026-03-10,63615.0,63615.0
295,Эрел,ТАНКЕР-Л-330,1,1368,2026-03-10,0,0
296,Эрел,УАЗ,Хантер,962,2026-03-10,0,0
297,Эрел,ЭД,400,476,2026-03-10,17458.0,17458.0
298,Эрел,ЭД,400,596,2026-03-10,19927.0,19927.0

In [27]:

# установка формата вывода
pd.options.display.float_format = '{:,.0f}'.format
# Фильтрация по типу обслуживания "ТО-5000"
#pivot_table = pivot_table[pivot_table.index.get_level_values('Тип обслуживания') == 'ТО-5000']
#формулы к сводной таблице
pivot_table[('Дата планирования')] = (pivot_table[('Дата начала обслуживания')]+ pd.DateOffset(days=205))
# применение формата для всех чисел в таблице
pivot_table = pivot_table.applymap(lambda x: '{:,.0f}'.format(x) if isinstance(x, (int, float)) else x)


# print the updated pivot table
pivot_table

C:\Users\poisk-12\AppData\Local\Temp\ipykernel_61388\74498894.py:8: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  pivot_table = pivot_table.applymap(lambda x: '{:,.0f}'.format(x) if isinstance(x, (int, float)) else x)

,Подразделение,Марка,Модификация,Инвентарный номер,Дата начала обслуживания,Наработка машины,Фактическая наработка в момент проведения ТО,Дата планирования
0,Дражный,CLG877H,LG G877H,"1,249",2026-06-01,"1,700","1,700",2026-12-23
1,Дражный,CLG942EHD,LG-G942E,"1,251",2026-04-01,"2,800","2,800",2026-10-23
2,Дражный,CLG975F,LG-G975F,"1,310",2026-03-10,"2,450","2,450",2026-10-01
3,Дражный,D-375,6,818,2026-03-10,"14,241","14,241",2026-10-01
4,Дражный,D-375,5D,697,2026-04-01,"38,750","38,750",2026-10-23
...,...,...,...,...,...,...,...,...
294,Эрел,СБШ-250,МНА32,"1,105",2026-03-10,"63,615","63,615",2026-10-01
295,Эрел,ТАНКЕР-Л-330,1,"1,368",2026-03-10,0,0,2026-10-01
296,Эрел,УАЗ,Хантер,962,2026-03-10,0,0,2026-10-01
297,Эрел,ЭД,400,476,2026-03-10,"17,458","17,458",2026-10-01
298,Эрел,ЭД,400,596,2026-03-10,"19,927","19,927",2026-10-01

In [28]:
s = (pivot_table['Инвентарный номер']
       .astype(str)
       .str.replace('\xa0', '', regex=False)   # убрать NBSP
       .str.replace(',', '', regex=False)      # убрать разделители тысяч
       .str.strip()
       .str.replace(r'\D+', '', regex=True)    # убрать всё, что не цифры
       .replace('', pd.NA)                     # пустое -> NA
)

pivot_table['Инвентарный номер'] = pd.to_numeric(s, errors='coerce').astype('Int64')

In [29]:
df = pivot_table.copy()
for col in ['Дата начала обслуживания','Дата планирования']:
    df[col] = pd.to_datetime(df[col], errors='coerce')

df = df.dropna(subset=['Дата начала обслуживания','Дата планирования'])
df = df[df['Дата планирования'] >= df['Дата начала обслуживания']]

n = (df['Дата планирования'] - df['Дата начала обслуживания']).dt.days + 1
out = df.loc[df.index.repeat(n)].copy()
out['__i'] = out.groupby(level=0).cumcount()
out['Дата'] = out['Дата начала обслуживания'] + pd.to_timedelta(out['__i'], unit='D')
out = out.drop(columns='__i')
out

,Подразделение,Марка,Модификация,Инвентарный номер,Дата начала обслуживания,Наработка машины,Фактическая наработка в момент проведения ТО,Дата планирования,Дата
0,Дражный,CLG877H,LG G877H,1249,2026-06-01,"1,700","1,700",2026-12-23,2026-06-01
0,Дражный,CLG877H,LG G877H,1249,2026-06-01,"1,700","1,700",2026-12-23,2026-06-02
0,Дражный,CLG877H,LG G877H,1249,2026-06-01,"1,700","1,700",2026-12-23,2026-06-03
0,Дражный,CLG877H,LG G877H,1249,2026-06-01,"1,700","1,700",2026-12-23,2026-06-04
0,Дражный,CLG877H,LG G877H,1249,2026-06-01,"1,700","1,700",2026-12-23,2026-06-05
...,...,...,...,...,...,...,...,...,...
298,Эрел,ЭД,400,596,2026-03-10,"19,927","19,927",2026-10-01,2026-09-27
298,Эрел,ЭД,400,596,2026-03-10,"19,927","19,927",2026-10-01,2026-09-28
298,Эрел,ЭД,400,596,2026-03-10,"19,927","19,927",2026-10-01,2026-09-29
298,Эрел,ЭД,400,596,2026-03-10,"19,927","19,927",2026-10-01,2026-09-30
298,Эрел,ЭД,400,596,2026-03-10,"19,927","19,927",2026-10-01,2026-10-01

In [30]:
new_df=out.copy()

In [31]:
new_df['Наработка машины'] = new_df['Наработка машины'].str.replace(',', '')

In [32]:
mask=new_df["Марка"].eq('\xa0 LIUGONG ')
new_df = new_df.loc[~mask].copy()

In [33]:
new_df['Планируемая наработка в момент проведения ТО'] = new_df['Наработка машины']
new_df['Планируемая наработка в момент проведения ТО']=new_df['Планируемая наработка в момент проведения ТО'].astype(str).replace({',':''},regex=True)
new_df=new_df[~new_df['Планируемая наработка в момент проведения ТО'].isin(['н/д', "Отсутствие показаний", "н/р", "отсутствие показаний", "Н/Р"])]

In [34]:
##### === проверка как записана наработка в арегатном ===
uniq=new_df['Планируемая наработка в момент проведения ТО'].unique()
print("\n".join(map(str, sorted(uniq))))

0
100
1000
10041
10140
10190
10264
103956
104415
10485
10497
1050
10528
10691
1070
10936
1118
111863
11250
113150
11350
1145
114620
11500
11832
120000
12058
1250
12552
13183
13350
13361
13403
13410
13500
1365
13750
13806
13927
13936
14044
14050
14055
14074
14123
14241
14348
14624
1465
14772
14780
148
15
152245
15388
15530
15550
15560
15643
15730
15836
158460
15930
160000
16105
16200
1621
16275
16500
16790
16899
16927
1700
1710
17127
172802
17458
17741
17750
17870
17975
18010
18017
1838
18578
18750
18900
19090
1931
19630
19672
198029
19900
19927
19991
2025
20250
20300
20425
20546
20840
20848
20890
20964
21432
21500
21638
22160
22219
22250
22322
22380
22511
22520
22757
230
23225
23493
23723
23925
23990
24207
24340
2450
248
2486
250
2550
25545
25888
2595
2600
26677
26684
26822
27286
27428
2758
27600
2773
27793
2800
2853
29040
29215
29429
2965
29977
30590
30732
3076
30950
30994
310
3140
3147
32110
3274
3275
330
33000
33487
33700
33875
34100
34520
34750
34809
3489
34922
3595
36047
36625
3750
37650
38750
4000
40103
40750
4084
410
4125
4150
4160
41600
42
430
445130
45
4514
46979
4723
4750
50251
5205
52350
5250
5349
54
5418
5533
5561
56652
57270
57500
5752
5790
5830
5850
6258
6343
63615
6388
64753
6750
67542
6883
6890
71
72142
7389
7718
772
7825
7830
7845
7961
814
815
8200
8500
857
8750
87611
8840
8930
9151
9258
9487
950
960
9800

In [35]:
new_df['Планируемая наработка в момент проведения ТО'] = new_df['Планируемая наработка в момент проведения ТО'].fillna(0).astype(int)

In [36]:
new_df

,Подразделение,Марка,Модификация,Инвентарный номер,Дата начала обслуживания,Наработка машины,Фактическая наработка в момент проведения ТО,Дата планирования,Дата,Планируемая наработка в момент проведения ТО
0,Дражный,CLG877H,LG G877H,1249,2026-06-01,1700,"1,700",2026-12-23,2026-06-01,1700
0,Дражный,CLG877H,LG G877H,1249,2026-06-01,1700,"1,700",2026-12-23,2026-06-02,1700
0,Дражный,CLG877H,LG G877H,1249,2026-06-01,1700,"1,700",2026-12-23,2026-06-03,1700
0,Дражный,CLG877H,LG G877H,1249,2026-06-01,1700,"1,700",2026-12-23,2026-06-04,1700
0,Дражный,CLG877H,LG G877H,1249,2026-06-01,1700,"1,700",2026-12-23,2026-06-05,1700
...,...,...,...,...,...,...,...,...,...,...
298,Эрел,ЭД,400,596,2026-03-10,19927,"19,927",2026-10-01,2026-09-27,19927
298,Эрел,ЭД,400,596,2026-03-10,19927,"19,927",2026-10-01,2026-09-28,19927
298,Эрел,ЭД,400,596,2026-03-10,19927,"19,927",2026-10-01,2026-09-29,19927
298,Эрел,ЭД,400,596,2026-03-10,19927,"19,927",2026-10-01,2026-09-30,19927
298,Эрел,ЭД,400,596,2026-03-10,19927,"19,927",2026-10-01,2026-10-01,19927

In [37]:
bad_any = new_df[new_df.isna().any(axis=1)] #показать nan хотьв одном столбце
print(bad_any)

Empty DataFrame
Columns: [Подразделение, Марка, Модификация, Инвентарный номер, Дата начала обслуживания, Наработка машины, Фактическая наработка в момент проведения ТО, Дата планирования, Дата, Планируемая наработка в момент проведения ТО]
Index: []

In [38]:
df2 = new_df.replace({'': pd.NA, 'None': pd.NA, 'nan': pd.NA, 'NaN': pd.NA})
bad_any = df2[df2.isna().any(axis=1)]
bad_any

Empty DataFrame
Columns: [Подразделение, Марка, Модификация, Инвентарный номер, Дата начала обслуживания, Наработка машины, Фактическая наработка в момент проведения ТО, Дата планирования, Дата, Планируемая наработка в момент проведения ТО]
Index: []

In [39]:
# Рассчитываем планируемую наработку
new_df=new_df.reset_index()
STEP = 20  # сколько прибавлять в день

# убедимся, что дата — datetime
new_df['Дата'] = pd.to_datetime(new_df['Дата'], errors='coerce')

# сортируем по группам и дате
group_cols = ['Подразделение', 'Марка', 'Модификация','Инвентарный номер']  # добавь/убери поля по своей логике
new_df = new_df.sort_values(group_cols + ['Дата'])

# стартовое значение для каждой группы:
# берём первую (минимальную по дате) "планируемую наработку" в группе,
# если её нет — можно подставить фактическую/другой столбец как базу.
start = new_df.groupby(group_cols)['Планируемая наработка в момент проведения ТО'].transform('first')

# порядковый номер дня внутри группы: 0,1,2,3,...
day_idx = new_df.groupby(group_cols).cumcount()

# формула: старт + 20 * номер_дня
new_df['Планируемая наработка в момент проведения ТО'] = start + STEP * day_idx

##### === графики наработки ===

In [40]:
to_dict={
        50:	'',
    100:	'',
    150:	'',
    200:	'',
    250:	'ТО250',
    300:	'',
    350:	'',
    400:	'',
    450:	'',
    500:	'ТО500',
    550:	'',
    600:	'',
    650:	'',
    700:	'',
    750:	'ТО250',
    800:	'',
    850:	'',
    900:	'',
    950:	'',
    1000:	'ТО1000',
    1050:	'',
    1100:	'',
    1150:	'',
    1200:	'',
    1250:	'ТО250',
    1300:	'',
    1350:	'',
    1400:	'',
    1450:	'',
    1500:	'ТО500',
    1550:	'',
    1600:	'',
    1650:	'',
    1700:	'',
    1750:	'ТО250',
    1800:	'',
    1850:	'',
    1900:	'',
    1950:	'',
    2000:	'ТО2000',
    2050:	'',
    2100:	'',
    2150:	'',
    2200:	'',
    2250:	'ТО250',
    2300:	'',
    2350:	'',
    2400:	'',
    2450:	'',
    2500:	'ТО500',
    2550:	'',
    2600:	'',
    2650:	'',
    2700:	'',
    2750:	'ТО250',
    2800:	'',
    2850:	'',
    2900:	'',
    2950:	'',
    3000:	'ТО1000',
    3050:	'',
    3100:	'',
    3150:	'',
    3200:	'',
    3250:	'ТО250',
    3300:	'',
    3350:	'',
    3400:	'',
    3450:	'',
    3500:	'ТО500',
    3550:	'',
    3600:	'',
    3650:	'',
    3700:	'',
    3750:	'ТО250',
    3800:	'',
    3850:	'',
    3900:	'',
    3950:	'',
    4000:	'ТО4000',
    4050:	'',
    4100:	'',
    4150:	'',
    4200:	'',
    4250:	'ТО250',
    4300:	'',
    4350:	'',
    4400:	'',
    4450:	'',
    4500:	'ТО500',
    4550:	'',
    4600:	'',
    4650:	'',
    4700:	'',
    4750:	'ТО250',
    4800:	'',
    4850:	'',
    4900:	'',
    4950:	'',
    5000:	'ТО1000',
    5050:	'',
    5100:	'',
    5150:	'',
    5200:	'',
    5250:	'ТО250',
    5300:	'',
    5350:	'',
    5400:	'',
    5450:	'',
    5500:	'ТО500',
    5550:	'',
    5600:	'',
    5650:	'',
    5700:	'',
    5750:	'ТО250',
    5800:	'',
    5850:	'',
    5900:	'',
    5950:	'',
    6000:	'ТО2000',
    6050:	'',
    6100:	'',
    6150:	'',
    6200:	'',
    6250:	'ТО250',
    6300:	'',
    6350:	'',
    6400:	'',
    6450:	'',
    6500:	'ТО500',
    6550:	'',
    6600:	'',
    6650:	'',
    6700:	'',
    6750:	'ТО250',
    6800:	'',
    6850:	'',
    6900:	'',
    6950:	'',
    7000:	'ТО1000',
    7050:	'',
    7100:	'',
    7150:	'',
    7200:	'',
    7250:	'ТО250',
    7300:	'',
    7350:	'',
    7400:	'',
    7450:	'',
    7500:	'ТО500',
    7550:	'',
    7600:	'',
    7650:	'',
    7700:	'',
    7750:	'ТО250',
    7800:	'',
    7850:	'',
    7900:	'',
    7950:	'',
    8000:	'ТО4000',
    8050:	'',
    8100:	'',
    8150:	'',
    8200:	'',
    8250:	'ТО250',
    8300:	'',
    8350:	'',
    8400:	'',
    8450:	'',
    8500:	'ТО500',
    8550:	'',
    8600:	'',
    8650:	'',
    8700:	'',
    8750:	'ТО250',
    8800:	'',
    8850:	'',
    8900:	'',
    8950:	'',
    9000:	'ТО1000',
    9050:	'',
    9100:	'',
    9150:	'',
    9200:	'',
    9250:	'ТО250',
    9300:	'',
    9350:	'',
    9400:	'',
    9450:	'',
    9500:	'ТО500',
    9550:	'',
    9600:	'',
    9650:	'',
    9700:	'',
    9750:	'ТО250',
    9800:	'',
    9850:	'',
    9900:	'',
    9950:	'',
    10000:	'ТО2000',
    10050:	'',
    10100:	'',
    10150:	'',
    10200:	'',
    10250:	'ТО250',
    10300:	'',
    10350:	'',
    10400:	'',
    10450:	'',
    10500:	'ТО500',
    10550:	'',
    10600:	'',
    10650:	'',
    10700:	'',
    10750:	'ТО250',
    10800:	'',
    10850:	'',
    10900:	'',
    10950:	'',
    11000:	'ТО1000',
    11050:	'',
    11100:	'',
    11150:	'',
    11200:	'',
    11250:	'ТО250',
    11300:	'',
    11350:	'',
    11400:	'',
    11450:	'',
    11500:	'ТО500',
    11550:	'',
    11600:	'',
    11650:	'',
    11700:	'',
    11750:	'ТО250',
    11800:	'',
    11850:	'',
    11900:	'',
    11950:	'',
    12000:	'ТО4000',
    12050:	'',
    12100:	'',
    12150:	'',
    12200:	'',
    12250:	'ТО250',
    12300:	'',
    12350:	'',
    12400:	'',
    12450:	'',
    12500:	'ТО500',
    12550:	'',
    12600:	'',
    12650:	'',
    12700:	'',
    12750:	'ТО250',
    12800:	'',
    12850:	'',
    12900:	'',
    12950:	'',
    13000:	'ТО1000',
    13050:	'',
    13100:	'',
    13150:	'',
    13200:	'',
    13250:	'ТО250',
    13300:	'',
    13350:	'',
    13400:	'',
    13450:	'',
    13500:	'ТО500',
    13550:	'',
    13600:	'',
    13650:	'',
    13700:	'',
    13750:	'ТО250',
    13800:	'',
    13850:	'',
    13900:	'',
    13950:	'',
    14000:	'ТО2000',
    14050:	'',
    14100:	'',
    14150:	'',
    14200:	'',
    14250:	'ТО250',
    14300:	'',
    14350:	'',
    14400:	'',
    14450:	'',
    14500:	'ТО500',
    14550:	'',
    14600:	'',
    14650:	'',
    14700:	'',
    14750:	'ТО250',
    14800:	'',
    14850:	'',
    14900:	'',
    14950:	'',
    15000:	'ТО1000',
    15050:	'',
    15100:	'',
    15150:	'',
    15200:	'',
    15250:	'ТО250',
    15300:	'',
    15350:	'',
    15400:	'',
    15450:	'',
    15500:	'ТО500',
    15550:	'',
    15600:	'',
    15650:	'',
    15700:	'',
    15750:	'ТО250',
    15800:	'',
    15850:	'',
    15900:	'',
    15950:	'',
    16000:	'ТО4000',
    16050:	'',
    16100:	'',
    16150:	'',
    16200:	'',
    16250:	'ТО250',
    16300:	'',
    16350:	'',
    16400:	'',
    16450:	'',
    16500:	'ТО500',
    16550:	'',
    16600:	'',
    16650:	'',
    16700:	'',
    16750:	'ТО250',
    16800:	'',
    16850:	'',
    16900:	'',
    16950:	'',
    17000:	'ТО1000',
    17050:	'',
    17100:	'',
    17150:	'',
    17200:	'',
    17250:	'ТО250',
    17300:	'',
    17350:	'',
    17400:	'',
    17450:	'',
    17500:	'ТО500',
    17550:	'',
    17600:	'',
    17650:	'',
    17700:	'',
    17750:	'ТО250',
    17800:	'',
    17850:	'',
    17900:	'',
    17950:	'',
    18000:	'ТО2000',
    18050:	'',
    18100:	'',
    18150:	'',
    18200:	'',
    18250:	'ТО250',
    18300:	'',
    18350:	'',
    18400:	'',
    18450:	'',
    18500:	'ТО500',
    18550:	'',
    18600:	'',
    18650:	'',
    18700:	'',
    18750:	'ТО250',
    18800:	'',
    18850:	'',
    18900:	'',
    18950:	'',
    19000:	'ТО1000',
    19050:	'',
    19100:	'',
    19150:	'',
    19200:	'',
    19250:	'ТО250',
    19300:	'',
    19350:	'',
    19400:	'',
    19450:	'',
    19500:	'ТО500',
    19550:	'',
    19600:	'',
    19650:	'',
    19700:	'',
    19750:	'ТО250',
    19800:	'',
    19850:	'',
    19900:	'',
    19950:	'',
    20000:	'ТО4000',
    20050:	'',
    20100:	'',
    20150:	'',
    20200:	'',
    20250:	'ТО250',
    20300:	'',
    20350:	'',
    20400:	'',
    20450:	'',
    20500:	'ТО500',
    20550:	'',
    20600:	'',
    20650:	'',
    20700:	'',
    20750:	'ТО250',
    20800:	'',
    20850:	'',
    20900:	'',
    20950:	'',
    21000:	'ТО1000',
    21050:	'',
    21100:	'',
    21150:	'',
    21200:	'',
    21250:	'ТО250',
    21300:	'',
    21350:	'',
    21400:	'',
    21450:	'',
    21500:	'ТО500',
    21550:	'',
    21600:	'',
    21650:	'',
    21700:	'',
    21750:	'ТО250',
    21800:	'',
    21850:	'',
    21900:	'',
    21950:	'',
    22000:	'ТО2000',
    22050:	'',
    22100:	'',
    22150:	'',
    22200:	'',
    22250:	'ТО250',
    22300:	'',
    22350:	'',
    22400:	'',
    22450:	'',
    22500:	'ТО500',
    22550:	'',
    22600:	'',
    22650:	'',
    22700:	'',
    22750:	'ТО250',
    22800:	'',
    22850:	'',
    22900:	'',
    22950:	'',
    23000:	'ТО1000',
    23050:	'',
    23100:	'',
    23150:	'',
    23200:	'',
    23250:	'ТО250',
    23300:	'',
    23350:	'',
    23400:	'',
    23450:	'',
    23500:	'ТО500',
    23550:	'',
    23600:	'',
    23650:	'',
    23700:	'',
    23750:	'ТО250',
    23800:	'',
    23850:	'',
    23900:	'',
    23950:	'',
    24000:	'ТО4000',
    24050:	'',
    24100:	'',
    24150:	'',
    24200:	'',
    24250:	'ТО250',
    24300:	'',
    24350:	'',
    24400:	'',
    24450:	'',
    24500:	'ТО500',
    24550:	'',
    24600:	'',
    24650:	'',
    24700:	'',
    24750:	'ТО250',
    24800:	'',
    24850:	'',
    24900:	'',
    24950:	'',
    25000:	'ТО1000',
    25050:	'',
    25100:	'',
    25150:	'',
    25200:	'',
    25250:	'ТО250',
    25300:	'',
    25350:	'',
    25400:	'',
    25450:	'',
    25500:	'ТО500',
    25550:	'',
    25600:	'',
    25650:	'',
    25700:	'',
    25750:	'ТО250',
    25800:	'',
    25850:	'',
    25900:	'',
    25950:	'',
    26000:	'ТО2000',
    26050:	'',
    26100:	'',
    26150:	'',
    26200:	'',
    26250:	'ТО250',
    26300:	'',
    26350:	'',
    26400:	'',
    26450:	'',
    26500:	'ТО500',
    26550:	'',
    26600:	'',
    26650:	'',
    26700:	'',
    26750:	'ТО250',
    26800:	'',
    26850:	'',
    26900:	'',
    26950:	'',
    27000:	'ТО1000',
    27050:	'',
    27100:	'',
    27150:	'',
    27200:	'',
    27250:	'ТО250',
    27300:	'',
    27350:	'',
    27400:	'',
    27450:	'',
    27500:	'ТО500',
    27550:	'',
    27600:	'',
    27650:	'',
    27700:	'',
    27750:	'ТО250',
    27800:	'',
    27850:	'',
    27900:	'',
    27950:	'',
    28000:	'ТО4000',
    28050:	'',
    28100:	'',
    28150:	'',
    28200:	'',
    28250:	'ТО250',
    28300:	'',
    28350:	'',
    28400:	'',
    28450:	'',
    28500:	'ТО500',
    28550:	'',
    28600:	'',
    28650:	'',
    28700:	'',
    28750:	'ТО250',
    28800:	'',
    28850:	'',
    28900:	'',
    28950:	'',
    29000:	'ТО1000',
    29050:	'',
    29100:	'',
    29150:	'',
    29200:	'',
    29250:	'ТО250',
    29300:	'',
    29350:	'',
    29400:	'',
    29450:	'',
    29500:	'ТО500',
    29550:	'',
    29600:	'',
    29650:	'',
    29700:	'',
    29750:	'ТО250',
    29800:	'',
    29850:	'',
    29900:	'',
    29950:	'',
    30000:	'ТО2000',
    30050:	'',
    30100:	'',
    30150:	'',
    30200:	'',
    30250:	'ТО250',
    30300:	'',
    30350:	'',
    30400:	'',
    30450:	'',
    30500:	'ТО500',
    30550:	'',
    30600:	'',
    30650:	'',
    30700:	'',
    30750:	'ТО250',
    30800:	'',
    30850:	'',
    30900:	'',
    30950:	'',
    31000:	'ТО1000',
    31050:	'',
    31100:	'',
    31150:	'',
    31200:	'',
    31250:	'ТО250',
    31300:	'',
    31350:	'',
    31400:	'',
    31450:	'',
    31500:	'ТО500',
    31550:	'',
    31600:	'',
    31650:	'',
    31700:	'',
    31750:	'ТО250',
    31800:	'',
    31850:	'',
    31900:	'',
    31950:	'',
    32000:	'ТО4000',
    32050:	'',
    32100:	'',
    32150:	'',
    32200:	'',
    32250:	'ТО250',
    32300:	'',
    32350:	'',
    32400:	'',
    32450:	'',
    32500:	'ТО500',
    32550:	'',
    32600:	'',
    32650:	'',
    32700:	'',
    32750:	'ТО250',
    32800:	'',
    32850:	'',
    32900:	'',
    32950:	'',
    33000:	'ТО1000',
    33050:	'',
    33100:	'',
    33150:	'',
    33200:	'',
    33250:	'ТО250',
    33300:	'',
    33350:	'',
    33400:	'',
    33450:	'',
    33500:	'ТО500',
    33550:	'',
    33600:	'',
    33650:	'',
    33700:	'',
    33750:	'ТО250',
    33800:	'',
    33850:	'',
    33900:	'',
    33950:	'',
    34000:	'ТО2000',
    34050:	'',
    34100:	'',
    34150:	'',
    34200:	'',
    34250:	'ТО250',
    34300:	'',
    34350:	'',
    34400:	'',
    34450:	'',
    34500:	'ТО500',
    34550:	'',
    34600:	'',
    34650:	'',
    34700:	'',
    34750:	'ТО250',
    34800:	'',
    34850:	'',
    34900:	'',
    34950:	'',
    35000:	'ТО1000',
    35050:	'',
    35100:	'',
    35150:	'',
    35200:	'',
    35250:	'ТО250',
    35300:	'',
    35350:	'',
    35400:	'',
    35450:	'',
    35500:	'ТО500',
    35550:	'',
    35600:	'',
    35650:	'',
    35700:	'',
    35750:	'ТО250',
    35800:	'',
    35850:	'',
    35900:	'',
    35950:	'',
    36000:	'ТО4000',
    36050:	'',
    36100:	'',
    36150:	'',
    36200:	'',
    36250:	'ТО250',
    36300:	'',
    36350:	'',
    36400:	'',
    36450:	'',
    36500:	'ТО500',
    36550:	'',
    36600:	'',
    36650:	'',
    36700:	'',
    36750:	'ТО250',
    36800:	'',
    36850:	'',
    36900:	'',
    36950:	'',
    37000:	'ТО1000',
    37050:	'',
    37100:	'',
    37150:	'',
    37200:	'',
    37250:	'ТО250',
    37300:	'',
    37350:	'',
    37400:	'',
    37450:	'',
    37500:	'ТО500',
    37550:	'',
    37600:	'',
    37650:	'',
    37700:	'',
    37750:	'ТО250',
    37800:	'',
    37850:	'',
    37900:	'',
    37950:	'',
    38000:	'ТО2000',
    38050:	'',
    38100:	'',
    38150:	'',
    38200:	'',
    38250:	'ТО250',
    38300:	'',
    38350:	'',
    38400:	'',
    38450:	'',
    38500:	'ТО500',
    38550:	'',
    38600:	'',
    38650:	'',
    38700:	'',
    38750:	'ТО250',
    38800:	'',
    38850:	'',
    38900:	'',
    38950:	'',
    39000:	'ТО1000',
    39050:	'',
    39100:	'',
    39150:	'',
    39200:	'',
    39250:	'ТО250',
    39300:	'',
    39350:	'',
    39400:	'',
    39450:	'',
    39500:	'ТО500',
    39550:	'',
    39600:	'',
    39650:	'',
    39700:	'',
    39750:	'ТО250',
    39800:	'',
    39850:	'',
    39900:	'',
    39950:	'',
    40000:	'ТО4000',
    40050:	'',
    40100:	'',
    40150:	'',
    40200:	'',
    40250:	'ТО250',
    40300:	'',
    40350:	'',
    40400:	'',
    40450:	'',
    40500:	'ТО500',
    40550:	'',
    40600:	'',
    40650:	'',
    40700:	'',
    40750:	'ТО250',
    40800:	'',
    40850:	'',
    40900:	'',
    40950:	'',
    41000:	'ТО1000',
    41050:	'',
    41100:	'',
    41150:	'',
    41200:	'',
    41250:	'ТО250',
    41300:	'',
    41350:	'',
    41400:	'',
    41450:	'',
    41500:	'ТО500',
    41550:	'',
    41600:	'',
    41650:	'',
    41700:	'',
    41750:	'ТО250',
    41800:	'',
    41850:	'',
    41900:	'',
    41950:	'',
    42000:	'ТО2000',
    42050:	'',
    42100:	'',
    42150:	'',
    42200:	'',
    42250:	'ТО250',
    42300:	'',
    42350:	'',
    42400:	'',
    42450:	'',
    42500:	'ТО500',
    42550:	'',
    42600:	'',
    42650:	'',
    42700:	'',
    42750:	'ТО250',
    42800:	'',
    42850:	'',
    42900:	'',
    42950:	'',
    43000:	'ТО1000',
    43050:	'',
    43100:	'',
    43150:	'',
    43200:	'',
    43250:	'ТО250',
    43300:	'',
    43350:	'',
    43400:	'',
    43450:	'',
    43500:	'ТО500',
    43550:	'',
    43600:	'',
    43650:	'',
    43700:	'',
    43750:	'ТО250',
    43800:	'',
    43850:	'',
    43900:	'',
    43950:	'',
    44000:	'ТО4000',
    44050:	'',
    44100:	'',
    44150:	'',
    44200:	'',
    44250:	'ТО250',
    44300:	'',
    44350:	'',
    44400:	'',
    44450:	'',
    44500:	'ТО500',
    44550:	'',
    44600:	'',
    44650:	'',
    44700:	'',
    44750:	'ТО250',
    44800:	'',
    44850:	'',
    44900:	'',
    44950:	'',
    45000:	'ТО1000',
    45050:	'',
    45100:	'',
    45150:	'',
    45200:	'',
    45250:	'ТО250',
    45300:	'',
    45350:	'',
    45400:	'',
    45450:	'',
    45500:	'ТО500',
    45550:	'',
    45600:	'',
    45650:	'',
    45700:	'',
    45750:	'ТО250',
    45800:	'',
    45850:	'',
    45900:	'',
    45950:	'',
    46000:	'ТО2000',
    46050:	'',
    46100:	'',
    46150:	'',
    46200:	'',
    46250:	'ТО250',
    46300:	'',
    46350:	'',
    46400:	'',
    46450:	'',
    46500:	'ТО500',
    46550:	'',
    46600:	'',
    46650:	'',
    46700:	'',
    46750:	'ТО250',
    46800:	'',
    46850:	'',
    46900:	'',
    46950:	'',
    47000:	'ТО1000',
    47050:	'',
    47100:	'',
    47150:	'',
    47200:	'',
    47250:	'ТО250',
    47300:	'',
    47350:	'',
    47400:	'',
    47450:	'',
    47500:	'ТО500',
    47550:	'',
    47600:	'',
    47650:	'',
    47700:	'',
    47750:	'ТО250',
    47800:	'',
    47850:	'',
    47900:	'',
    47950:	'',
    48000:	'ТО4000'




}

In [41]:
to_dict475={
    50:	'',
100:	'',
150:	'',
200:	'',
250:	'ТО250',
300:	'',
350:	'',
400:	'',
450:	'',
500:	'ТО500',
550:	'',
600:	'',
650:	'',
700:	'',
750:	'ТО250',
800:	'',
850:	'',
900:	'',
950:	'',
1000:	'ТО1000',
1050:	'',
1100:	'',
1150:	'',
1200:	'',
1250:	'ТО250',
1300:	'',
1350:	'',
1400:	'',
1450:	'',
1500:	'ТО500',
1550:	'',
1600:	'',
1650:	'',
1700:	'',
1750:	'ТО250',
1800:	'',
1850:	'',
1900:	'',
1950:	'',
2000:	'ТО2000',
2050:	'',
2100:	'',
2150:	'',
2200:	'',
2250:	'ТО250',
2300:	'',
2350:	'',
2400:	'',
2450:	'',
2500:	'ТО500',
2550:	'',
2600:	'',
2650:	'',
2700:	'',
2750:	'ТО250',
2800:	'',
2850:	'',
2900:	'',
2950:	'',
3000:	'ТО1000',
3050:	'',
3100:	'',
3150:	'',
3200:	'',
3250:	'ТО250',
3300:	'',
3350:	'',
3400:	'',
3450:	'',
3500:	'ТО500',
3550:	'',
3600:	'',
3650:	'',
3700:	'',
3750:	'ТО250',
3800:	'',
3850:	'',
3900:	'',
3950:	'',
4000:	'ТО4000',
4050:	'',
4100:	'',
4150:	'',
4200:	'',
4250:	'ТО250',
4300:	'',
4350:	'',
4400:	'',
4450:	'',
4500:	'ТО500',
4550:	'',
4600:	'',
4650:	'',
4700:	'',
4750:	'ТО250',
4800:	'',
4850:	'',
4900:	'',
4950:	'',
5000:	'ТО1000',
5050:	'',
5100:	'',
5150:	'',
5200:	'',
5250:	'ТО250',
5300:	'',
5350:	'',
5400:	'',
5450:	'',
5500:	'ТО500',
5550:	'',
5600:	'',
5650:	'',
5700:	'',
5750:	'ТО250',
5800:	'',
5850:	'',
5900:	'',
5950:	'',
6000:	'ТО2000',
6050:	'',
6100:	'',
6150:	'',
6200:	'',
6250:	'ТО250',
6300:	'',
6350:	'',
6400:	'',
6450:	'',
6500:	'ТО500',
6550:	'',
6600:	'',
6650:	'',
6700:	'',
6750:	'ТО250',
6800:	'',
6850:	'',
6900:	'',
6950:	'',
7000:	'ТО1000',
7050:	'',
7100:	'',
7150:	'',
7200:	'',
7250:	'ТО250',
7300:	'',
7350:	'',
7400:	'',
7450:	'',
7500:	'ТО500',
7550:	'',
7600:	'',
7650:	'',
7700:	'',
7750:	'ТО250',
7800:	'',
7850:	'',
7900:	'',
7950:	'',
8000:	'ТО4000',
8050:	'',
8100:	'',
8150:	'',
8200:	'',
8250:	'ТО250',
8300:	'',
8350:	'',
8400:	'',
8450:	'',
8500:	'ТО500',
8550:	'',
8600:	'',
8650:	'',
8700:	'',
8750:	'ТО250',
8800:	'',
8850:	'',
8900:	'',
8950:	'',
9000:	'ТО1000',
9050:	'',
9100:	'',
9150:	'',
9200:	'',
9250:	'ТО250',
9300:	'',
9350:	'',
9400:	'',
9450:	'',
9500:	'ТО500',
9550:	'',
9600:	'',
9650:	'',
9700:	'',
9750:	'ТО250',
9800:	'',
9850:	'',
9900:	'',
9950:	'',
10000:	'ТО2000',
10050:	'',
10100:	'',
10150:	'',
10200:	'',
10250:	'ТО250',
10300:	'',
10350:	'',
10400:	'',
10450:	'',
10500:	'ТО500',
10550:	'',
10600:	'',
10650:	'',
10700:	'',
10750:	'ТО250',
10800:	'',
10850:	'',
10900:	'',
10950:	'',
11000:	'ТО1000',
11050:	'',
11100:	'',
11150:	'',
11200:	'',
11250:	'ТО250',
11300:	'',
11350:	'',
11400:	'',
11450:	'',
11500:	'ТО500',
11550:	'',
11600:	'',
11650:	'',
11700:	'',
11750:	'ТО250',
11800:	'',
11850:	'',
11900:	'',
11950:	'',
12000:	'ТО4000',
12050:	'',
12100:	'',
12150:	'',
12200:	'',
12250:	'ТО250',
12300:	'',
12350:	'',
12400:	'',
12450:	'',
12500:	'ТО500',
12550:	'',
12600:	'',
12650:	'',
12700:	'',
12750:	'ТО250',
12800:	'',
12850:	'',
12900:	'',
12950:	'',
13000:	'ТО1000',
13050:	'',
13100:	'',
13150:	'',
13200:	'',
13250:	'ТО250',
13300:	'',
13350:	'',
13400:	'',
13450:	'',
13500:	'ТО500',
13550:	'',
13600:	'',
13650:	'',
13700:	'',
13750:	'ТО250',
13800:	'',
13850:	'',
13900:	'',
13950:	'',
14000:	'ТО2000',
14050:	'',
14100:	'',
14150:	'',
14200:	'',
14250:	'ТО250',
14300:	'',
14350:	'',
14400:	'',
14450:	'',
14500:	'ТО500',
14550:	'',
14600:	'',
14650:	'',
14700:	'',
14750:	'ТО250',
14800:	'',
14850:	'',
14900:	'',
14950:	'',
15000:	'ТО1000',
15050:	'',
15100:	'',
15150:	'',
15200:	'',
15250:	'ТО250',
15300:	'',
15350:	'',
15400:	'',
15450:	'',
15500:	'ТО500',
15550:	'',
15600:	'',
15650:	'',
15700:	'',
15750:	'ТО250',
15800:	'',
15850:	'',
15900:	'',
15950:	'',
16000:	'ТО4000',
16050:	'',
16100:	'',
16150:	'',
16200:	'',
16250:	'ТО250',
16300:	'',
16350:	'',
16400:	'',
16450:	'',
16500:	'ТО500',
16550:	'',
16600:	'',
16650:	'',
16700:	'',
16750:	'ТО250',
16800:	'',
16850:	'',
16900:	'',
16950:	'',
17000:	'ТО1000',
17050:	'',
17100:	'',
17150:	'',
17200:	'',
17250:	'ТО250',
17300:	'',
17350:	'',
17400:	'',
17450:	'',
17500:	'ТО500',
17550:	'',
17600:	'',
17650:	'',
17700:	'',
17750:	'ТО250',
17800:	'',
17850:	'',
17900:	'',
17950:	'',
18000:	'ТО2000',
18050:	'',
18100:	'',
18150:	'',
18200:	'',
18250:	'ТО250',
18300:	'',
18350:	'',
18400:	'',
18450:	'',
18500:	'ТО500',
18550:	'',
18600:	'',
18650:	'',
18700:	'',
18750:	'ТО250',
18800:	'',
18850:	'',
18900:	'',
18950:	'',
19000:	'ТО1000',
19050:	'',
19100:	'',
19150:	'',
19200:	'',
19250:	'ТО250',
19300:	'',
19350:	'',
19400:	'',
19450:	'',
19500:	'ТО500',
19550:	'',
19600:	'',
19650:	'',
19700:	'',
19750:	'ТО250',
19800:	'',
19850:	'',
19900:	'',
19950:	'',
20000:	'ТО4000',
20050:	'',
20100:	'',
20150:	'',
20200:	'',
20250:	'ТО250',
20300:	'',
20350:	'',
20400:	'',
20450:	'',
20500:	'ТО500',
20550:	'',
20600:	'',
20650:	'',
20700:	'',
20750:	'ТО250',
20800:	'',
20850:	'',
20900:	'',
20950:	'',
21000:	'ТО1000',
21050:	'',
21100:	'',
21150:	'',
21200:	'',
21250:	'ТО250',
21300:	'',
21350:	'',
21400:	'',
21450:	'',
21500:	'ТО500',
21550:	'',
21600:	'',
21650:	'',
21700:	'',
21750:	'ТО250',
21800:	'',
21850:	'',
21900:	'',
21950:	'',
22000:	'ТО2000',
22050:	'',
22100:	'',
22150:	'',
22200:	'',
22250:	'ТО250',
22300:	'',
22350:	'',
22400:	'',
22450:	'',
22500:	'ТО500',
22550:	'',
22600:	'',
22650:	'',
22700:	'',
22750:	'ТО250',
22800:	'',
22850:	'',
22900:	'',
22950:	'',
23000:	'ТО1000',
23050:	'',
23100:	'',
23150:	'',
23200:	'',
23250:	'ТО250',
23300:	'',
23350:	'',
23400:	'',
23450:	'',
23500:	'ТО500',
23550:	'',
23600:	'',
23650:	'',
23700:	'',
23750:	'ТО250',
23800:	'',
23850:	'',
23900:	'',
23950:	'',
24000:	'ТО4000',
24050:	'',
24100:	'',
24150:	'',
24200:	'',
24250:	'ТО250',
24300:	'',
24350:	'',
24400:	'',
24450:	'',
24500:	'ТО500',
24550:	'',
24600:	'',
24650:	'',
24700:	'',
24750:	'ТО250',
24800:	'',
24850:	'',
24900:	'',
24950:	'',
25000:	'ТО1000',
25050:	'',
25100:	'',
25150:	'',
25200:	'',
25250:	'ТО250',
25300:	'',
25350:	'',
25400:	'',
25450:	'',
25500:	'ТО500',
25550:	'',
25600:	'',
25650:	'',
25700:	'',
25750:	'ТО250',
25800:	'',
25850:	'',
25900:	'',
25950:	'',
26000:	'ТО2000',
26050:	'',
26100:	'',
26150:	'',
26200:	'',
26250:	'ТО250',
26300:	'',
26350:	'',
26400:	'',
26450:	'',
26500:	'ТО500',
26550:	'',
26600:	'',
26650:	'',
26700:	'',
26750:	'ТО250',
26800:	'',
26850:	'',
26900:	'',
26950:	'',
27000:	'ТО1000',
27050:	'',
27100:	'',
27150:	'',
27200:	'',
27250:	'ТО250',
27300:	'',
27350:	'',
27400:	'',
27450:	'',
27500:	'ТО500',
27550:	'',
27600:	'',
27650:	'',
27700:	'',
27750:	'ТО250',
27800:	'',
27850:	'',
27900:	'',
27950:	'',
28000:	'ТО4000',
28050:	'',
28100:	'',
28150:	'',
28200:	'',
28250:	'ТО250',
28300:	'',
28350:	'',
28400:	'',
28450:	'',
28500:	'ТО500',
28550:	'',
28600:	'',
28650:	'',
28700:	'',
28750:	'ТО250',
28800:	'',
28850:	'',
28900:	'',
28950:	'',
29000:	'ТО1000',
29050:	'',
29100:	'',
29150:	'',
29200:	'',
29250:	'ТО250',
29300:	'',
29350:	'',
29400:	'',
29450:	'',
29500:	'ТО500',
29550:	'',
29600:	'',
29650:	'',
29700:	'',
29750:	'ТО250',
29800:	'',
29850:	'',
29900:	'',
29950:	'',
30000:	'ТО2000',
30050:	'',
30100:	'',
30150:	'',
30200:	'',
30250:	'ТО250',
30300:	'',
30350:	'',
30400:	'',
30450:	'',
30500:	'ТО500',
30550:	'',
30600:	'',
30650:	'',
30700:	'',
30750:	'ТО250',
30800:	'',
30850:	'',
30900:	'',
30950:	'',
31000:	'ТО1000',
31050:	'',
31100:	'',
31150:	'',
31200:	'',
31250:	'ТО250',
31300:	'',
31350:	'',
31400:	'',
31450:	'',
31500:	'ТО500',
31550:	'',
31600:	'',
31650:	'',
31700:	'',
31750:	'ТО250',
31800:	'',
31850:	'',
31900:	'',
31950:	'',
32000:	'ТО4000',
32050:	'',
32100:	'',
32150:	'',
32200:	'',
32250:	'ТО250',
32300:	'',
32350:	'',
32400:	'',
32450:	'',
32500:	'ТО500',
32550:	'',
32600:	'',
32650:	'',
32700:	'',
32750:	'ТО250',
32800:	'',
32850:	'',
32900:	'',
32950:	'',
33000:	'ТО1000',
33050:	'',
33100:	'',
33150:	'',
33200:	'',
33250:	'ТО250',
33300:	'',
33350:	'',
33400:	'',
33450:	'',
33500:	'ТО500',
33550:	'',
33600:	'',
33650:	'',
33700:	'',
33750:	'ТО250',
33800:	'',
33850:	'',
33900:	'',
33950:	'',
34000:	'ТО2000',
34050:	'',
34100:	'',
34150:	'',
34200:	'',
34250:	'ТО250',
34300:	'',
34350:	'',
34400:	'',
34450:	'',
34500:	'ТО500',
34550:	'',
34600:	'',
34650:	'',
34700:	'',
34750:	'ТО250',
34800:	'',
34850:	'',
34900:	'',
34950:	'',
35000:	'ТО1000',
35050:	'',
35100:	'',
35150:	'',
35200:	'',
35250:	'ТО250',
35300:	'',
35350:	'',
35400:	'',
35450:	'',
35500:	'ТО500',
35550:	'',
35600:	'',
35650:	'',
35700:	'',
35750:	'ТО250',
35800:	'',
35850:	'',
35900:	'',
35950:	'',
36000:	'ТО4000',
36050:	'',
36100:	'',
36150:	'',
36200:	'',
36250:	'ТО250',
36300:	'',
36350:	'',
36400:	'',
36450:	'',
36500:	'ТО500',
36550:	'',
36600:	'',
36650:	'',
36700:	'',
36750:	'ТО250',
36800:	'',
36850:	'',
36900:	'',
36950:	'',
37000:	'ТО1000',
37050:	'',
37100:	'',
37150:	'',
37200:	'',
37250:	'ТО250',
37300:	'',
37350:	'',
37400:	'',
37450:	'',
37500:	'ТО500',
37550:	'',
37600:	'',
37650:	'',
37700:	'',
37750:	'ТО250',
37800:	'',
37850:	'',
37900:	'',
37950:	'',
38000:	'ТО2000',
38050:	'',
38100:	'',
38150:	'',
38200:	'',
38250:	'ТО250',
38300:	'',
38350:	'',
38400:	'',
38450:	'',
38500:	'ТО500',
38550:	'',
38600:	'',
38650:	'',
38700:	'',
38750:	'ТО250',
38800:	'',
38850:	'',
38900:	'',
38950:	'',
39000:	'ТО1000',
39050:	'',
39100:	'',
39150:	'',
39200:	'',
39250:	'ТО250',
39300:	'',
39350:	'',
39400:	'',
39450:	'',
39500:	'ТО500',
39550:	'',
39600:	'',
39650:	'',
39700:	'',
39750:	'ТО250',
39800:	'',
39850:	'',
39900:	'',
39950:	'',
40000:	'ТО4000',
40050:	'',
40100:	'',
40150:	'',
40200:	'',
40250:	'ТО250',
40300:	'',
40350:	'',
40400:	'',
40450:	'',
40500:	'ТО500',
40550:	'',
40600:	'',
40650:	'',
40700:	'',
40750:	'ТО250',
40800:	'',
40850:	'',
40900:	'',
40950:	'',
41000:	'ТО1000',
41050:	'',
41100:	'',
41150:	'',
41200:	'',
41250:	'ТО250',
41300:	'',
41350:	'',
41400:	'',
41450:	'',
41500:	'ТО500',
41550:	'',
41600:	'',
41650:	'',
41700:	'',
41750:	'ТО250',
41800:	'',
41850:	'',
41900:	'',
41950:	'',
42000:	'ТО2000',
42050:	'',
42100:	'',
42150:	'',
42200:	'',
42250:	'ТО250',
42300:	'',
42350:	'',
42400:	'',
42450:	'',
42500:	'ТО500',
42550:	'',
42600:	'',
42650:	'',
42700:	'',
42750:	'ТО250',
42800:	'',
42850:	'',
42900:	'',
42950:	'',
43000:	'ТО1000',
43050:	'',
43100:	'',
43150:	'',
43200:	'',
43250:	'ТО250',
43300:	'',
43350:	'',
43400:	'',
43450:	'',
43500:	'ТО500',
43550:	'',
43600:	'',
43650:	'',
43700:	'',
43750:	'ТО250',
43800:	'',
43850:	'',
43900:	'',
43950:	'',
44000:	'ТО4000',
44050:	'',
44100:	'',
44150:	'',
44200:	'',
44250:	'ТО250',
44300:	'',
44350:	'',
44400:	'',
44450:	'',
44500:	'ТО500',
44550:	'',
44600:	'',
44650:	'',
44700:	'',
44750:	'ТО250',
44800:	'',
44850:	'',
44900:	'',
44950:	'',
45000:	'ТО1000',
45050:	'',
45100:	'',
45150:	'',
45200:	'',
45250:	'ТО250',
45300:	'',
45350:	'',
45400:	'',
45450:	'',
45500:	'ТО500',
45550:	'',
45600:	'',
45650:	'',
45700:	'',
45750:	'ТО250',
45800:	'',
45850:	'',
45900:	'',
45950:	'',
46000:	'ТО2000',
46050:	'',
46100:	'',
46150:	'',
46200:	'',
46250:	'ТО250',
46300:	'',
46350:	'',
46400:	'',
46450:	'',
46500:	'ТО500',
46550:	'',
46600:	'',
46650:	'',
46700:	'',
46750:	'ТО250',
46800:	'',
46850:	'',
46900:	'',
46950:	'',
47000:	'ТО1000',
47050:	'',
47100:	'',
47150:	'',
47200:	'',
47250:	'ТО250',
47300:	'',
47350:	'',
47400:	'',
47450:	'',
47500:	'ТО500',
47550:	'',
47600:	'',
47650:	'',
47700:	'',
47750:	'ТО250',
47800:	'',
47850:	'',
47900:	'',
47950:	'',
48000:	'ТО4000'

}

In [42]:
to_dict_PC={
    50:	'',
    100:	'ТО100',
    150:	'',
    200:	'ТО100',
    250:	'ТО250',
    300:	'ТО100',
    350:	'',
    400:	'ТО100',
    450:	'',
    500:	'ТО500',
    550:	'',
    600:	'ТО100',
    650:	'',
    700:	'ТО100',
    750:	'ТО250',
    800:	'ТО100',
    850:	'',
    900:	'ТО100',
    950:	'',
    1000:	'ТО1000',
    1050:	'',
    1100:	'ТО100',
    1150:	'',
    1200:	'ТО100',
    1250:	'ТО250',
    1300:	'ТО100',
    1350:	'',
    1400:	'ТО100',
    1450:	'',
    1500:	'ТО500',
    1550:	'',
    1600:	'ТО100',
    1650:	'',
    1700:	'ТО100',
    1750:	'ТО250',
    1800:	'ТО100',
    1850:	'',
    1900:	'ТО100',
    1950:	'',
    2000:	'ТО2000',
    2050:	'',
    2100:	'ТО100',
    2150:	'',
    2200:	'ТО100',
    2250:	'ТО250',
    2300:	'ТО100',
    2350:	'',
    2400:	'ТО100',
    2450:	'',
    2500:	'ТО500',
    2550:	'',
    2600:	'ТО100',
    2650:	'',
    2700:	'ТО100',
    2750:	'ТО250',
    2800:	'ТО100',
    2850:	'',
    2900:	'ТО100',
    2950:	'',
    3000:	'ТО1000',
    3050:	'',
    3100:	'ТО100',
    3150:	'',
    3200:	'ТО100',
    3250:	'ТО250',
    3300:	'ТО100',
    3350:	'',
    3400:	'ТО100',
    3450:	'',
    3500:	'ТО500',
    3550:	'',
    3600:	'ТО100',
    3650:	'',
    3700:	'ТО100',
    3750:	'ТО250',
    3800:	'ТО100',
    3850:	'',
    3900:	'ТО100',
    3950:	'',
    4000:	'ТО4000',
    4050:	'',
    4100:	'ТО100',
    4150:	'',
    4200:	'ТО100',
    4250:	'ТО250',
    4300:	'',
    4350:	'',
    4400:	'ТО100',
    4450:	'',
    4500:	'ТО500',
    4550:	'',
    4600:	'ТО100',
    4650:	'',
    4700:	'ТО100',
    4750:	'ТО250',
    4800:	'ТО100',
    4850:	'',
    4900:	'ТО100',
    4950:	'',
    5000:	'ТО5000',
    5050:	'',
    5100:	'ТО100',
    5150:	'',
    5200:	'ТО100',
    5250:	'ТО250',
    5300:	'ТО100',
    5350:	'',
    5400:	'ТО100',
    5450:	'',
    5500:	'ТО500',
    5550:	'',
    5600:	'ТО100',
    5650:	'',
    5700:	'ТО100',
    5750:	'ТО250',
    5800:	'ТО100',
    5850:	'',
    5900:	'ТО100',
    5950:	'',
    6000:	'ТО2000',
    6050:	'',
    6100:	'ТО100',
    6150:	'',
    6200:	'ТО100',
    6250:	'ТО250',
    6300:	'ТО100',
    6350:	'',
    6400:	'ТО100',
    6450:	'',
    6500:	'ТО500',
    6550:	'',
    6600:	'ТО100',
    6650:	'',
    6700:	'ТО100',
    6750:	'ТО250',
    6800:	'ТО100',
    6850:	'',
    6900:	'ТО100',
    6950:	'',
    7000:	'ТО1000',
    7050:	'',
    7100:	'ТО100',
    7150:	'',
    7200:	'ТО100',
    7250:	'ТО250',
    7300:	'ТО100',
    7350:	'',
    7400:	'ТО100',
    7450:	'',
    7500:	'ТО500',
    7550:	'',
    7600:	'ТО100',
    7650:	'',
    7700:	'ТО100',
    7750:	'ТО250',
    7800:	'ТО100',
    7850:	'',
    7900:	'ТО100',
    7950:	'',
    8000:	'ТО8000',
    8050:	'',
    8100:	'ТО100',
    8150:	'',
    8200:	'ТО100',
    8250:	'ТО250',
    8300:	'ТО100',
    8350:	'',
    8400:	'ТО100',
    8450:	'',
    8500:	'ТО500',
    8550:	'',
    8600:	'ТО100',
    8650:	'',
    8700:	'ТО100',
    8750:	'ТО250',
    8800:	'ТО100',
    8850:	'',
    8900:	'ТО100',
    8950:	'',
    9000:	'ТО1000',
    9050:	'',
    9100:	'ТО100',
    9150:	'',
    9200:	'ТО100',
    9250:	'ТО250',
    9300:	'ТО100',
    9350:	'',
    9400:	'ТО100',
    9450:	'',
    9500:	'ТО500',
    9550:	'',
    9600:	'ТО100',
    9650:	'',
    9700:	'ТО100',
    9750:	'ТО250',
    9800:	'ТО100',
    9850:	'',
    9900:	'ТО100',
    9950:	'',
    10000:	'ТО2000/5000',
    10050:	'',
    10100:	'ТО100',
    10150:	'',
    10200:	'ТО100',
    10250:	'ТО250',
    10300:	'ТО100',
    10350:	'',
    10400:	'ТО100',
    10450:	'',
    10500:	'ТО500',
    10550:	'',
    10600:	'ТО100',
    10650:	'',
    10700:	'',
    10750:	'ТО250',
    10800:	'ТО100',
    10850:	'',
    10900:	'ТО100',
    10950:	'',
    11000:	'ТО1000',
    11050:	'',
    11100:	'ТО100',
    11150:	'',
    11200:	'ТО100',
    11250:	'ТО250',
    11300:	'ТО100',
    11350:	'',
    11400:	'ТО100',
    11450:	'',
    11500:	'ТО500',
    11550:	'',
    11600:	'ТО100',
    11650:	'',
    11700:	'ТО100',
    11750:	'ТО250',
    11800:	'ТО100',
    11850:	'',
    11900:	'ТО100',
    11950:	'',
    12000:	'ТО4000',
    12050:	'',
    12100:	'ТО100',
    12150:	'',
    12200:	'ТО100',
    12250:	'ТО250',
    12300:	'ТО100',
    12350:	'',
    12400:	'ТО100',
    12450:	'',
    12500:	'ТО500',
    12550:	'',
    12600:	'ТО100',
    12650:	'',
    12700:	'ТО100',
    12750:	'ТО250',
    12800:	'ТО100',
    12850:	'',
    12900:	'ТО100',
    12950:	'',
    13000:	'ТО1000',
    13050:	'',
    13100:	'ТО100',
    13150:	'',
    13200:	'ТО100',
    13250:	'ТО250',
    13300:	'ТО100',
    13350:	'',
    13400:	'ТО100',
    13450:	'',
    13500:	'ТО500',
    13550:	'',
    13600:	'ТО100',
    13650:	'',
    13700:	'ТО100',
    13750:	'ТО250',
    13800:	'ТО100',
    13850:	'',
    13900:	'ТО100',
    13950:	'',
    14000:	'ТО2000',
    14050:	'',
    14100:	'ТО100',
    14150:	'',
    14200:	'ТО100',
    14250:	'ТО250',
    14300:	'ТО100',
    14350:	'',
    14400:	'ТО100',
    14450:	'',
    14500:	'ТО500',
    14550:	'',
    14600:	'ТО100',
    14650:	'',
    14700:	'ТО100',
    14750:	'ТО250',
    14800:	'ТО100',
    14850:	'',
    14900:	'ТО100',
    14950:	'',
    15000:	'ТО5000',
    15050:	'',
    15100:	'ТО100',
    15150:	'',
    15200:	'ТО100',
    15250:	'ТО250',
    15300:	'ТО100',
    15350:	'',
    15400:	'ТО100',
    15450:	'',
    15500:	'ТО500',
    15550:	'',
    15600:	'ТО100',
    15650:	'',
    15700:	'ТО100',
    15750:	'ТО250',
    15800:	'ТО100',
    15850:	'',
    15900:	'ТО100',
    15950:	'',
    16000:	'ТО8000',
    16050:	'',
    16100:	'ТО100',
    16150:	'',
    16200:	'ТО100',
    16250:	'ТО250',
    16300:	'ТО100',
    16350:	'',
    16400:	'ТО100',
    16450:	'',
    16500:	'ТО500',
    16550:	'',
    16600:	'ТО100',
    16650:	'',
    16700:	'ТО100',
    16750:	'ТО250',
    16800:	'ТО100',
    16850:	'',
    16900:	'ТО100',
    16950:	'',
    17000:	'ТО1000',
    17050:	'',
    17100:	'ТО100',
    17150:	'',
    17200:	'ТО100',
    17250:	'ТО250',
    17300:	'ТО100',
    17350:	'',
    17400:	'ТО100',
    17450:	'',
    17500:	'ТО500',
    17550:	'',
    17600:	'ТО100',
    17650:	'',
    17700:	'ТО100',
    17750:	'ТО250',
    17800:	'ТО100',
    17850:	'',
    17900:	'ТО100',
    17950:	'',
    18000:	'ТО2000',
    18050:	'',
    18100:	'ТО100',
    18150:	'',
    18200:	'ТО100',
    18250:	'ТО250',
    18300:	'ТО100',
    18350:	'',
    18400:	'ТО100',
    18450:	'',
    18500:	'ТО500',
    18550:	'',
    18600:	'ТО100',
    18650:	'',
    18700:	'ТО100',
    18750:	'ТО250',
    18800:	'ТО100',
    18850:	'',
    18900:	'ТО100',
    18950:	'',
    19000:	'ТО1000',
    19050:	'',
    19100:	'ТО100',
    19150:	'',
    19200:	'ТО100',
    19250:	'ТО250',
    19300:	'ТО100',
    19350:	'',
    19400:	'ТО100',
    19450:	'',
    19500:	'ТО500',
    19550:	'',
    19600:	'ТО100',
    19650:	'',
    19700:	'ТО100',
    19750:	'ТО250',
    19800:	'ТО100',
    19850:	'',
    19900:	'ТО100',
    19950:	'',
    20000:	'ТО4000/5000',
    20050:	'',
    20100:	'ТО100',
    20150:	'',
    20200:	'ТО100',
    20250:	'ТО250',
    20300:	'ТО100',
    20350:	'',
    20400:	'ТО100',
    20450:	'',
    20500:	'ТО500',
    20550:	'',
    20600:	'ТО100',
    20650:	'',
    20700:	'ТО100',
    20750:	'ТО250',
    20800:	'ТО100',
    20850:	'',
    20900:	'ТО100',
    20950:	'',
    21000:	'ТО1000',
    21050:	'',
    21100:	'ТО100',
    21150:	'',
    21200:	'ТО100',
    21250:	'ТО250',
    21300:	'ТО100',
    21350:	'',
    21400:	'ТО100',
    21450:	'',
    21500:	'ТО500',
    21550:	'',
    21600:	'ТО100',
    21650:	'',
    21700:	'ТО100',
    21750:	'ТО250',
    21800:	'ТО100',
    21850:	'',
    21900:	'ТО100',
    21950:	'',
    22000:	'ТО2000',
    22050:	'',
    22100:	'ТО100',
    22150:	'',
    22200:	'ТО100',
    22250:	'ТО250',
    22300:	'ТО100',
    22350:	'',
    22400:	'ТО100',
    22450:	'',
    22500:	'ТО500',
    22550:	'',
    22600:	'ТО100',
    22650:	'',
    22700:	'ТО100',
    22750:	'ТО250',
    22800:	'ТО100',
    22850:	'',
    22900:	'ТО100',
    22950:	'',
    23000:	'ТО1000',
    23050:	'',
    23100:	'ТО100',
    23150:	'',
    23200:	'ТО100',
    23250:	'ТО250',
    23300:	'ТО100',
    23350:	'',
    23400:	'ТО100',
    23450:	'',
    23500:	'ТО500',
    23550:	'',
    23600:	'ТО100',
    23650:	'',
    23700:	'ТО100',
    23750:	'ТО250',
    23800:	'ТО100',
    23850:	'',
    23900:	'ТО100',
    23950:	'',
    24000:	'ТО8000',
    24050:	'',
    24100:	'ТО100',
        24150:	'',
        24200:	'ТО100',
        24250:	'ТО250',
        24300:	'ТО100',
        24350:	'',
        24400:	'ТО100',
        24450:	'',
        24500:	'ТО500',
        24550:	'',
        24600:	'ТО100',
        24650:	'',
        24700:	'ТО100',
        24750:	'ТО250',
        24800:	'ТО100',
        24850:	'',
        24900:	'ТО100',
        24950:	'',
        25000:	'ТО5000',
        25050:	'',
        25100:	'ТО100',
        25150:	'',
        25200:	'ТО100',
        25250:	'ТО250',
        25300:	'ТО100',
        25350:	'',
        25400:	'ТО100',
        25450:	'',
        25500:	'ТО500',
        25550:	'',
        25600:	'ТО100',
        25650:	'',
        25700:	'ТО100',
        25750:	'ТО250',
        25800:	'ТО100',
        25850:	'',
        25900:	'ТО100',
        25950:	'',
        26000:	'ТО2000',
        26050:	'',
        26100:	'ТО100',
        26150:	'',
        26200:	'ТО100',
        26250:	'ТО250',
        26300:	'ТО100',
        26350:	'',
        26400:	'ТО100',
        26450:	'',
        26500:	'ТО500',
        26550:	'',
        26600:	'ТО100',
        26650:	'',
        26700:	'ТО100',
        26750:	'ТО250',
        26800:	'ТО100',
        26850:	'',
        26900:	'ТО100',
        26950:	'',
        27000:	'ТО1000',
        27050:	'',
        27100:	'ТО100',
        27150:	'',
        27200:	'ТО100',
        27250:	'ТО250',
        27300:	'ТО100',
        27350:	'',
        27400:	'ТО100',
        27450:	'',
        27500:	'ТО500',
        27550:	'',
        27600:	'ТО100',
        27650:	'',
        27700:	'ТО100',
        27750:	'ТО250',
        27800:	'ТО100',
        27850:	'',
        27900:	'ТО100',
        27950:	'',
        28000:	'ТО4000',
        28050:	'',
        28100:	'ТО100',
        28150:	'',
        28200:	'ТО100',
        28250:	'ТО250',
        28300:	'ТО100',
        28350:	'',
        28400:	'ТО100',
        28450:	'',
        28500:	'ТО500',
        28550:	'',
        28600:	'ТО100',
        28650:	'',
        28700:	'ТО100',
        28750:	'ТО250',
        28800:	'ТО100',
        28850:	'',
        28900:	'ТО100',
        28950:	'',
        29000:	'ТО1000',
        29050:	'',
        29100:	'ТО100',
        29150:	'',
        29200:	'ТО100',
        29250:	'ТО250',
        29300:	'ТО100',
        29350:	'',
        29400:	'ТО100',
        29450:	'',
        29500:	'ТО500',
        29550:	'',
        29600:	'ТО100',
        29650:	'',
        29700:	'ТО100',
        29750:	'ТО250',
        29800:	'ТО100',
        29850:	'',
        29900:	'ТО100',
        29950:	'',
        30000:	'ТО2000/5000',
        30050:	'',
        30100:	'ТО100',
        30150:	'',
        30200:	'ТО100',
        30250:	'ТО250',
        30300:	'ТО100',
        30350:	'',
        30400:	'ТО100',
        30450:	'',
        30500:	'ТО500',
        30550:	'',
        30600:	'ТО100',
        30650:	'',
        30700:	'ТО100',
        30750:	'ТО250',
        30800:	'ТО100',
        30850:	'',
        30900:	'ТО100',
        30950:	'',
        31000:	'ТО1000',
        31050:	'',
        31100:	'ТО100',
        31150:	'',
        31200:	'ТО100',
        31250:	'ТО250',
        31300:	'ТО100',
        31350:	'',
        31400:	'ТО100',
        31450:	'',
        31500:	'ТО500',
        31550:	'',
        31600:	'ТО100',
        31650:	'',
        31700:	'ТО100',
        31750:	'ТО250',
        31800:	'ТО100',
        31850:	'',
        31900:	'ТО100',
        31950:	'',
        32000:	'ТО8000',
        32050:	'',
        32100:	'ТО100',
        32150:	'',
        32200:	'ТО100',
        32250:	'ТО250',
        32300:	'ТО100',
        32350:	'',
        32400:	'ТО100',
        32450:	'',
        32500:	'ТО500',
        32550:	'',
        32600:	'ТО100',
        32650:	'',
        32700:	'ТО100',
        32750:	'ТО250',
        32800:	'ТО100',
        32850:	'',
        32900:	'ТО100',
        32950:	'',
        33000:	'ТО1000',
        33050:	'',
        33100:	'ТО100',
        33150:	'',
        33200:	'ТО100',
        33250:	'ТО250',
        33300:	'ТО100',
        33350:	'',
        33400:	'ТО100',
        33450:	'',
        33500:	'ТО500',
        33550:	'',
        33600:	'ТО100',
        33650:	'',
        33700:	'ТО100',
        33750:	'ТО250',
        33800:	'ТО100',
        33850:	'',
        33900:	'ТО100',
        33950:	'',
        34000:	'ТО2000',
        34050:	'',
        34100:	'ТО100',
        34150:	'',
        34200:	'ТО100',
        34250:	'ТО250',
        34300:	'ТО100',
        34350:	'',
        34400:	'ТО100',
        34450:	'',
        34500:	'ТО500',
        34550:	'',
        34600:	'ТО100',
        34650:	'',
        34700:	'ТО100',
        34750:	'ТО250',
        34800:	'ТО100',
        34850:	'',
        34900:	'ТО100',
        34950:	'',
        35000:	'ТО5000',
        35050:	'',
        35100:	'ТО100',
        35150:	'',
        35200:	'ТО100',
        35250:	'ТО250',
        35300:	'ТО100',
        35350:	'',
        35400:	'ТО100',
        35450:	'',
        35500:	'ТО500',
        35550:	'',
        35600:	'ТО100',
        35650:	'',
        35700:	'ТО100',
        35750:	'ТО250',
        35800:	'ТО100',
        35850:	'',
        35900:	'ТО100',
        35950:	'',
        36000:	'ТО4000',
        36050:	'',
        36100:	'ТО100',
        36150:	'',
        36200:	'ТО100',
        36250:	'ТО250',
        36300:	'ТО100',
        36350:	'',
        36400:	'ТО100',
        36450:	'',
        36500:	'ТО500',
        36550:	'',
        36600:	'ТО100',
        36650:	'',
        36700:	'ТО100',
        36750:	'ТО250',
        36800:	'ТО100',
        36850:	'',
        36900:	'ТО100',
        36950:	'',
        37000:	'ТО1000',
        37050:	'',
        37100:	'ТО100',
        37150:	'',
        37200:	'ТО100',
        37250:	'ТО250',
        37300:	'ТО100',
        37350:	'',
        37400:	'ТО100',
        37450:	'',
        37500:	'ТО500',
        37550:	'',
        37600:	'ТО100',
        37650:	'',
        37700:	'ТО100',
        37750:	'ТО250',
        37800:	'ТО100',
        37850:	'',
        37900:	'ТО100',
        37950:	'',
        38000:	'ТО2000',
        38050:	'',
        38100:	'ТО100',
        38150:	'',
        38200:	'ТО100',
        38250:	'ТО250',
        38300:	'ТО100',
        38350:	'',
        38400:	'ТО100',
        38450:	'',
        38500:	'ТО500',
        38550:	'',
        38600:	'ТО100',
        38650:	'',
        38700:	'ТО100',
        38750:	'ТО250',
        38800:	'ТО100',
        38850:	'',
        38900:	'ТО100',
        38950:	'',
        39000:	'ТО1000',
        39050:	'',
        39100:	'ТО100',
        39150:	'',
        39200:	'ТО100',
        39250:	'ТО250',
        39300:	'ТО100',
        39350:	'',
        39400:	'ТО100',
        39450:	'',
        39500:	'ТО500',
        39550:	'',
        39600:	'ТО100',
        39650:	'',
        39700:	'ТО100',
        39750:	'ТО250',
        39800:	'ТО100',
        39850:	'',
        39900:	'ТО100',
        39950:	'',
        40000:	'ТО5000/8000',
        40050:	'',
        40100:	'ТО100',
        40150:	'',
        40200:	'ТО100',
        40250:	'ТО250',
        40300:	'ТО100',
        40350:	'',
        40400:	'ТО100',
        40450:	'',
        40500:	'ТО500',
        40550:	'',
        40600:	'ТО100',
        40650:	'',
        40700:	'ТО100',
        40750:	'ТО250',
        40800:	'ТО100',
        40850:	'',
        40900:	'ТО100',
        40950:	'',
        41000:	'ТО1000',
        41050:	'',
        41100:	'ТО100',
        41150:	'',
        41200:	'ТО100',
        41250:	'ТО250',
        41300:	'ТО100',
        41350:	'',
        41400:	'ТО100',
        41450:	'',
        41500:	'ТО500',
        41550:	'',
        41600:	'ТО100',
        41650:	'',
        41700:	'ТО100',
        41750:	'ТО250',
        41800:	'ТО100',
        41850:	'',
        41900:	'ТО100',
        41950:	'',
        42000:	'ТО2000',
        42050:	'',
        42100:	'ТО100',
        42150:	'',
        42200:	'ТО100',
        42250:	'ТО250',
        42300:	'ТО100',
        42350:	'',
        42400:	'ТО100',
        42450:	'',
        42500:	'ТО500',
        42550:	'',
        42600:	'ТО100',
        42650:	'',
        42700:	'ТО100',
        42750:	'ТО250',
        42800:	'ТО100',
        42850:	'',
        42900:	'ТО100',
        42950:	'',
        43000:	'ТО1000',
        43050:	'',
        43100:	'ТО100',
        43150:	'',
        43200:	'ТО100',
        43250:	'ТО250',
        43300:	'ТО100',
        43350:	'',
        43400:	'ТО100',
        43450:	'',
        43500:	'ТО500',
        43550:	'',
        43600:	'ТО100',
        43650:	'',
        43700:	'ТО100',
        43750:	'ТО250',
        43800:	'ТО100',
        43850:	'',
        43900:	'ТО100',
        43950:	'',
        44000:	'ТО4000',
        44050:	'',
        44100:	'ТО100',
        44150:	'',
        44200:	'ТО100',
        44250:	'ТО250',
        44300:	'ТО100',
        44350:	'',
        44400:	'ТО100',
        44450:	'',
        44500:	'ТО500',
        44550:	'',
        44600:	'ТО100',
        44650:	'',
        44700:	'ТО100',
        44750:	'ТО250',
        44800:	'ТО100',
        44850:	'',
        44900:	'ТО100',
        44950:	'',
        45000:	'ТО5000',
        45050:	'',
        45100:	'ТО100',
        45150:	'',
        45200:	'ТО100',
        45250:	'ТО250',
        45300:	'ТО100',
        45350:	'',
        45400:	'ТО100',
        45450:	'',
        45500:	'ТО500',
        45550:	'',
        45600:	'ТО100',
        45650:	'',
        45700:	'ТО100',
        45750:	'ТО250',
        45800:	'ТО100',
        45850:	'',
        45900:	'ТО100',
        45950:	'',
        46000:	'ТО2000',
        46050:	'',
        46100:	'ТО100',
        46150:	'',
        46200:	'ТО100',
        46250:	'ТО250',
        46300:	'ТО100',
        46350:	'',
        46400:	'ТО100',
        46450:	'',
        46500:	'ТО500',
        46550:	'',
        46600:	'ТО100',
        46650:	'',
        46700:	'ТО100',
        46750:	'ТО250',
        46800:	'ТО100',
        46850:	'',
        46900:	'ТО100',
        46950:	'',
        47000:	'ТО1000',
        47050:	'',
        47100:	'ТО100',
        47150:	'',
        47200:	'ТО100',
        47250:	'ТО250',
        47300:	'ТО100',
        47350:	'',
        47400:	'ТО100',
        47450:	'',
        47500:	'ТО500',
        47550:	'',
        47600:	'ТО100',
        47650:	'',
        47700:	'ТО100',
        47750:	'ТО250',
        47800:	'ТО100',
        47850:	'',
        47900:	'ТО100',
        47950:	'',
        48000:	'ТО8000'



}

In [43]:
to_dict_PC400={
    50:	'',
    100:	'',
    150:	'',
    200:	'',
    250:	'ТО250',
    300:	'',
    350:	'',
    400:	'',
    450:	'',
    500:	'ТО500',
    550:	'',
    600:	'',
    650:	'',
    700:	'',
    750:	'ТО250',
    800:	'',
    850:	'',
    900:	'',
    950:	'',
    1000:	'ТО1000',
    1050:	'',
    1100:	'',
    1150:	'',
    1200:	'',
    1250:	'ТО250',
    1300:	'',
    1350:	'',
    1400:	'',
    1450:	'',
    1500:	'ТО500',
    1550:	'',
    1600:	'',
    1650:	'',
    1700:	'',
    1750:	'ТО250',
    1800:	'',
    1850:	'',
    1900:	'',
    1950:	'',
    2000:	'ТО2000',
    2050:	'',
    2100:	'',
    2150:	'',
    2200:	'',
    2250:	'ТО250',
    2300:	'',
    2350:	'',
    2400:	'',
    2450:	'',
    2500:	'ТО500',
    2550:	'',
    2600:	'',
    2650:	'',
    2700:	'',
    2750:	'ТО250',
    2800:	'',
    2850:	'',
    2900:	'',
    2950:	'',
    3000:	'ТО1000',
    3050:	'',
    3100:	'',
    3150:	'',
    3200:	'',
    3250:	'ТО250',
    3300:	'',
    3350:	'',
    3400:	'',
    3450:	'',
    3500:	'ТО500',
    3550:	'',
    3600:	'',
    3650:	'',
    3700:	'',
    3750:	'ТО250',
    3800:	'',
    3850:	'',
    3900:	'',
    3950:	'',
    4000:	'ТО4000',
    4050:	'',
    4100:	'',
    4150:	'',
    4200:	'',
    4250:	'ТО250',
    4300:	'',
    4350:	'',
    4400:	'',
    4450:	'',
    4500:	'ТО500',
    4550:	'',
    4600:	'',
    4650:	'',
    4700:	'',
    4750:	'ТО250',
    4800:	'',
    4850:	'',
    4900:	'',
    4950:	'',
    5000:	'ТО5000',
    5050:	'',
    5100:	'',
    5150:	'',
    5200:	'',
    5250:	'ТО250',
    5300:	'',
    5350:	'',
    5400:	'',
    5450:	'',
    5500:	'ТО500',
    5550:	'',
    5600:	'',
    5650:	'',
    5700:	'',
    5750:	'ТО250',
    5800:	'',
    5850:	'',
    5900:	'',
    5950:	'',
    6000:	'ТО2000',
    6050:	'',
    6100:	'',
    6150:	'',
    6200:	'',
    6250:	'ТО250',
    6300:	'',
    6350:	'',
    6400:	'',
    6450:	'',
    6500:	'ТО500',
    6550:	'',
    6600:	'',
    6650:	'',
    6700:	'',
    6750:	'ТО250',
    6800:	'',
    6850:	'',
    6900:	'',
    6950:	'',
    7000:	'ТО1000',
    7050:	'',
    7100:	'',
    7150:	'',
    7200:	'',
    7250:	'ТО250',
    7300:	'',
    7350:	'',
    7400:	'',
    7450:	'',
    7500:	'ТО500',
    7550:	'',
    7600:	'',
    7650:	'',
    7700:	'',
    7750:	'ТО250',
    7800:	'',
    7850:	'',
    7900:	'',
    7950:	'',
    8000:	'ТО8000',
    8050:	'',
    8100:	'',
    8150:	'',
    8200:	'',
    8250:	'ТО250',
    8300:	'',
    8350:	'',
    8400:	'',
    8450:	'',
    8500:	'ТО500',
    8550:	'',
    8600:	'',
    8650:	'',
    8700:	'',
    8750:	'ТО250',
    8800:	'',
    8850:	'',
    8900:	'',
    8950:	'',
    9000:	'ТО1000',
    9050:	'',
    9100:	'',
    9150:	'',
    9200:	'',
    9250:	'ТО250',
    9300:	'',
    9350:	'',
    9400:	'',
    9450:	'',
    9500:	'ТО500',
    9550:	'',
    9600:	'',
    9650:	'',
    9700:	'',
    9750:	'ТО250',
    9800:	'',
    9850:	'',
    9900:	'',
    9950:	'',
    10000:	'ТО2000/5000',
    10050:	'',
    10100:	'',
    10150:	'',
    10200:	'',
    10250:	'ТО250',
    10300:	'',
    10350:	'',
    10400:	'',
    10450:	'',
    10500:	'ТО500',
    10550:	'',
    10600:	'',
    10650:	'',
    10700:	'',
    10750:	'ТО250',
    10800:	'',
    10850:	'',
    10900:	'',
    10950:	'',
    11000:	'ТО1000',
    11050:	'',
    11100:	'',
    11150:	'',
    11200:	'',
    11250:	'ТО250',
    11300:	'',
    11350:	'',
    11400:	'',
    11450:	'',
    11500:	'ТО500',
    11550:	'',
    11600:	'',
    11650:	'',
    11700:	'',
    11750:	'ТО250',
    11800:	'',
    11850:	'',
    11900:	'',
    11950:	'',
    12000:	'ТО4000',
    12050:	'',
    12100:	'',
    12150:	'',
    12200:	'',
    12250:	'ТО250',
    12300:	'',
    12350:	'',
    12400:	'',
    12450:	'',
    12500:	'ТО500',
    12550:	'',
    12600:	'',
    12650:	'',
    12700:	'',
    12750:	'ТО250',
    12800:	'',
    12850:	'',
    12900:	'',
    12950:	'',
    13000:	'ТО1000',
    13050:	'',
    13100:	'',
    13150:	'',
    13200:	'',
    13250:	'ТО250',
    13300:	'',
    13350:	'',
    13400:	'',
    13450:	'',
    13500:	'ТО500',
    13550:	'',
    13600:	'',
    13650:	'',
    13700:	'',
    13750:	'ТО250',
    13800:	'',
    13850:	'',
    13900:	'',
    13950:	'',
    14000:	'ТО2000',
    14050:	'',
    14100:	'',
    14150:	'',
    14200:	'',
    14250:	'ТО250',
    14300:	'',
    14350:	'',
    14400:	'',
    14450:	'',
    14500:	'ТО500',
    14550:	'',
    14600:	'',
    14650:	'',
    14700:	'',
    14750:	'ТО250',
    14800:	'',
    14850:	'',
    14900:	'',
    14950:	'',
    15000:	'ТО5000',
    15050:	'',
    15100:	'',
    15150:	'',
    15200:	'',
    15250:	'ТО250',
    15300:	'',
    15350:	'',
    15400:	'',
    15450:	'',
    15500:	'ТО500',
    15550:	'',
    15600:	'',
    15650:	'',
    15700:	'',
    15750:	'ТО250',
    15800:	'',
    15850:	'',
    15900:	'',
    15950:	'',
    16000:	'ТО8000',
    16050:	'',
    16100:	'',
    16150:	'',
    16200:	'',
    16250:	'ТО250',
    16300:	'',
    16350:	'',
    16400:	'',
    16450:	'',
    16500:	'ТО500',
    16550:	'',
    16600:	'',
    16650:	'',
    16700:	'',
    16750:	'ТО250',
    16800:	'',
    16850:	'',
    16900:	'',
    16950:	'',
    17000:	'ТО1000',
    17050:	'',
    17100:	'',
    17150:	'',
    17200:	'',
    17250:	'ТО250',
    17300:	'',
    17350:	'',
    17400:	'',
    17450:	'',
    17500:	'ТО500',
    17550:	'',
    17600:	'',
    17650:	'',
    17700:	'',
    17750:	'ТО250',
    17800:	'',
    17850:	'',
    17900:	'',
    17950:	'',
    18000:	'ТО2000',
    18050:	'',
    18100:	'',
    18150:	'',
    18200:	'',
    18250:	'ТО250',
    18300:	'',
    18350:	'',
    18400:	'',
    18450:	'',
    18500:	'ТО500',
    18550:	'',
    18600:	'',
    18650:	'',
    18700:	'',
    18750:	'ТО250',
    18800:	'',
    18850:	'',
    18900:	'',
    18950:	'',
    19000:	'ТО1000',
    19050:	'',
    19100:	'',
    19150:	'',
    19200:	'',
    19250:	'ТО250',
    19300:	'',
    19350:	'',
    19400:	'',
    19450:	'',
    19500:	'ТО500',
    19550:	'',
    19600:	'',
    19650:	'',
    19700:	'',
    19750:	'ТО250',
    19800:	'',
    19850:	'',
    19900:	'',
    19950:	'',
    20000:	'ТО4000/5000',
    20050:	'',
    20100:	'',
    20150:	'',
    20200:	'',
    20250:	'ТО250',
    20300:	'',
    20350:	'',
    20400:	'',
    20450:	'',
    20500:	'ТО500',
    20550:	'',
    20600:	'',
    20650:	'',
    20700:	'',
    20750:	'ТО250',
    20800:	'',
    20850:	'',
    20900:	'',
    20950:	'',
    21000:	'ТО1000',
    21050:	'',
    21100:	'',
    21150:	'',
    21200:	'',
    21250:	'ТО250',
    21300:	'',
    21350:	'',
    21400:	'',
    21450:	'',
    21500:	'ТО500',
    21550:	'',
    21600:	'',
    21650:	'',
    21700:	'',
    21750:	'ТО250',
    21800:	'',
    21850:	'',
    21900:	'',
    21950:	'',
    22000:	'ТО2000',
    22050:	'',
    22100:	'',
    22150:	'',
    22200:	'',
    22250:	'ТО250',
    22300:	'',
    22350:	'',
    22400:	'',
    22450:	'',
    22500:	'ТО500',
    22550:	'',
    22600:	'',
    22650:	'',
    22700:	'',
    22750:	'ТО250',
    22800:	'',
    22850:	'',
    22900:	'',
    22950:	'',
    23000:	'ТО1000',
    23050:	'',
    23100:	'',
    23150:	'',
    23200:	'',
    23250:	'ТО250',
    23300:	'',
    23350:	'',
    23400:	'',
    23450:	'',
    23500:	'ТО500',
    23550:	'',
    23600:	'',
    23650:	'',
    23700:	'',
    23750:	'ТО250',
    23800:	'',
    23850:	'',
    23900:	'',
    23950:	'',
    24000:	'ТО8000',
    24050:	'',
    24100:	'',
    24150:	'',
    24200:	'',
    24250:	'ТО250',
    24300:	'',
    24350:	'',
    24400:	'',
    24450:	'',
    24500:	'ТО500',
    24550:	'',
    24600:	'',
    24650:	'',
    24700:	'',
    24750:	'ТО250',
    24800:	'',
    24850:	'',
    24900:	'',
    24950:	'',
    25000:	'ТО5000',
    25050:	'',
    25100:	'',
    25150:	'',
    25200:	'',
    25250:	'ТО250',
    25300:	'',
    25350:	'',
    25400:	'',
    25450:	'',
    25500:	'ТО500',
    25550:	'',
    25600:	'',
    25650:	'',
    25700:	'',
    25750:	'ТО250',
    25800:	'',
    25850:	'',
    25900:	'',
    25950:	'',
    26000:	'ТО2000',
    26050:	'',
    26100:	'',
    26150:	'',
    26200:	'',
    26250:	'ТО250',
    26300:	'',
    26350:	'',
    26400:	'',
    26450:	'',
    26500:	'ТО500',
    26550:	'',
    26600:	'',
    26650:	'',
    26700:	'',
    26750:	'ТО250',
    26800:	'',
    26850:	'',
    26900:	'',
    26950:	'',
    27000:	'ТО1000',
    27050:	'',
    27100:	'',
    27150:	'',
    27200:	'',
    27250:	'ТО250',
    27300:	'',
    27350:	'',
    27400:	'',
    27450:	'',
    27500:	'ТО500',
    27550:	'',
    27600:	'',
    27650:	'',
    27700:	'',
    27750:	'ТО250',
    27800:	'',
    27850:	'',
    27900:	'',
    27950:	'',
    28000:	'ТО4000',
    28050:	'',
    28100:	'',
    28150:	'',
    28200:	'',
    28250:	'ТО250',
    28300:	'',
    28350:	'',
    28400:	'',
    28450:	'',
    28500:	'ТО500',
    28550:	'',
    28600:	'',
    28650:	'',
    28700:	'',
    28750:	'ТО250',
    28800:	'',
    28850:	'',
    28900:	'',
    28950:	'',
    29000:	'ТО1000',
    29050:	'',
    29100:	'',
    29150:	'',
    29200:	'',
    29250:	'ТО250',
    29300:	'',
    29350:	'',
    29400:	'',
    29450:	'',
    29500:	'ТО500',
    29550:	'',
    29600:	'',
    29650:	'',
    29700:	'',
    29750:	'ТО250',
    29800:	'',
    29850:	'',
    29900:	'',
    29950:	'',
    30000:	'ТО2000/5000',
    30050:	'',
    30100:	'',
    30150:	'',
    30200:	'',
    30250:	'ТО250',
    30300:	'',
    30350:	'',
    30400:	'',
    30450:	'',
    30500:	'ТО500',
    30550:	'',
    30600:	'',
    30650:	'',
    30700:	'',
    30750:	'ТО250',
    30800:	'',
    30850:	'',
    30900:	'',
    30950:	'',
    31000:	'ТО1000',
    31050:	'',
    31100:	'',
    31150:	'',
    31200:	'',
    31250:	'ТО250',
    31300:	'',
    31350:	'',
    31400:	'',
    31450:	'',
    31500:	'ТО500',
    31550:	'',
    31600:	'',
    31650:	'',
    31700:	'',
    31750:	'ТО250',
    31800:	'',
    31850:	'',
    31900:	'',
    31950:	'',
    32000:	'ТО8000',
    32050:	'',
    32100:	'',
    32150:	'',
    32200:	'',
    32250:	'ТО250',
    32300:	'',
    32350:	'',
    32400:	'',
    32450:	'',
    32500:	'ТО500',
    32550:	'',
    32600:	'',
    32650:	'',
    32700:	'',
    32750:	'ТО250',
    32800:	'',
    32850:	'',
    32900:	'',
    32950:	'',
    33000:	'ТО1000',
    33050:	'',
    33100:	'',
    33150:	'',
    33200:	'',
    33250:	'ТО250',
    33300:	'',
    33350:	'',
    33400:	'',
    33450:	'',
    33500:	'ТО500',
    33550:	'',
    33600:	'',
    33650:	'',
    33700:	'',
    33750:	'ТО250',
    33800:	'',
    33850:	'',
    33900:	'',
    33950:	'',
    34000:	'ТО2000',
    34050:	'',
    34100:	'',
    34150:	'',
    34200:	'',
    34250:	'ТО250',
    34300:	'',
    34350:	'',
    34400:	'',
    34450:	'',
    34500:	'ТО500',
    34550:	'',
    34600:	'',
    34650:	'',
    34700:	'',
    34750:	'ТО250',
    34800:	'',
    34850:	'',
    34900:	'',
    34950:	'',
    35000:	'ТО5000',
    35050:	'',
    35100:	'',
    35150:	'',
    35200:	'',
    35250:	'ТО250',
    35300:	'',
    35350:	'',
    35400:	'',
    35450:	'',
    35500:	'ТО500',
    35550:	'',
    35600:	'',
    35650:	'',
    35700:	'',
    35750:	'ТО250',
    35800:	'',
    35850:	'',
    35900:	'',
    35950:	'',
    36000:	'ТО4000',
    36050:	'',
    36100:	'',
    36150:	'',
    36200:	'',
    36250:	'ТО250',
    36300:	'',
    36350:	'',
    36400:	'',
    36450:	'',
    36500:	'ТО500',
    36550:	'',
    36600:	'',
    36650:	'',
    36700:	'',
    36750:	'ТО250',
    36800:	'',
    36850:	'',
    36900:	'',
    36950:	'',
    37000:	'ТО1000',
    37050:	'',
    37100:	'',
    37150:	'',
    37200:	'',
    37250:	'ТО250',
    37300:	'',
    37350:	'',
    37400:	'',
    37450:	'',
    37500:	'ТО500',
    37550:	'',
    37600:	'',
    37650:	'',
    37700:	'',
    37750:	'ТО250',
    37800:	'',
    37850:	'',
    37900:	'',
    37950:	'',
    38000:	'ТО2000',
    38050:	'',
    38100:	'',
    38150:	'',
    38200:	'',
    38250:	'ТО250',
    38300:	'',
    38350:	'',
    38400:	'',
    38450:	'',
    38500:	'ТО500',
    38550:	'',
    38600:	'',
    38650:	'',
    38700:	'',
    38750:	'ТО250',
    38800:	'',
    38850:	'',
    38900:	'',
    38950:	'',
    39000:	'ТО1000',
    39050:	'',
    39100:	'',
    39150:	'',
    39200:	'',
    39250:	'ТО250',
    39300:	'',
    39350:	'',
    39400:	'',
    39450:	'',
    39500:	'ТО500',
    39550:	'',
    39600:	'',
    39650:	'',
    39700:	'',
    39750:	'ТО250',
    39800:	'',
    39850:	'',
    39900:	'',
    39950:	'',
    40000:	'ТО5000/8000',
    40050:	'',
    40100:	'',
    40150:	'',
    40200:	'',
    40250:	'ТО250',
    40300:	'',
    40350:	'',
    40400:	'',
    40450:	'',
    40500:	'ТО500',
    40550:	'',
    40600:	'',
    40650:	'',
    40700:	'',
    40750:	'ТО250',
    40800:	'',
    40850:	'',
    40900:	'',
    40950:	'',
    41000:	'ТО1000',
    41050:	'',
    41100:	'',
    41150:	'',
    41200:	'',
    41250:	'ТО250',
    41300:	'',
    41350:	'',
    41400:	'',
    41450:	'',
    41500:	'ТО500',
    41550:	'',
    41600:	'',
    41650:	'',
    41700:	'',
    41750:	'ТО250',
    41800:	'',
    41850:	'',
    41900:	'',
    41950:	'',
    42000:	'ТО2000',
    42050:	'',
    42100:	'',
    42150:	'',
    42200:	'',
    42250:	'ТО250',
    42300:	'',
    42350:	'',
    42400:	'',
    42450:	'',
    42500:	'ТО500',
    42550:	'',
    42600:	'',
    42650:	'',
    42700:	'',
    42750:	'ТО250',
    42800:	'',
    42850:	'',
    42900:	'',
    42950:	'',
    43000:	'ТО1000',
    43050:	'',
    43100:	'',
    43150:	'',
    43200:	'',
    43250:	'ТО250',
    43300:	'',
    43350:	'',
    43400:	'',
    43450:	'',
    43500:	'ТО500',
    43550:	'',
    43600:	'',
    43650:	'',
    43700:	'',
    43750:	'ТО250',
    43800:	'',
    43850:	'',
    43900:	'',
    43950:	'',
    44000:	'ТО4000',
    44050:	'',
    44100:	'',
    44150:	'',
    44200:	'',
    44250:	'ТО250',
    44300:	'',
    44350:	'',
    44400:	'',
    44450:	'',
    44500:	'ТО500',
    44550:	'',
    44600:	'',
    44650:	'',
    44700:	'',
    44750:	'ТО250',
    44800:	'',
    44850:	'',
    44900:	'',
    44950:	'',
    45000:	'ТО5000',
    45050:	'',
    45100:	'',
    45150:	'',
    45200:	'',
    45250:	'ТО250',
    45300:	'',
    45350:	'',
    45400:	'',
    45450:	'',
    45500:	'ТО500',
    45550:	'',
    45600:	'',
    45650:	'',
    45700:	'',
    45750:	'ТО250',
    45800:	'',
    45850:	'',
    45900:	'',
    45950:	'',
    46000:	'ТО1000',
    46050:	'',
    46100:	'',
    46150:	'',
    46200:	'',
    46250:	'ТО250',
    46300:	'',
    46350:	'',
    46400:	'',
    46450:	'',
    46500:	'ТО500',
    46550:	'',
    46600:	'',
    46650:	'',
    46700:	'',
    46750:	'ТО250',
    46800:	'',
    46850:	'',
    46900:	'',
    46950:	'',
    47000:	'ТО2000',
    47050:	'',
    47100:	'',
    47150:	'',
    47200:	'',
    47250:	'ТО250',
    47300:	'',
    47350:	'',
    47400:	'',
    47450:	'',
    47500:	'ТО500',
    47550:	'',
    47600:	'',
    47650:	'',
    47700:	'',
    47750:	'ТО250',
    47800:	'',
    47850:	'',
    47900:	'',
    47950:	'',
    48000:	'ТО8000'

}

In [44]:
to_dict_ZX={
    50:	'ТО50',
    100:	'ТО50',
    150:	'ТО50',
    200:	'ТО50',
    250:	'ТО250',
    300:	'ТО50',
    350:	'ТО50',
    400:	'ТО50',
    450:	'ТО50',
    500:	'ТО500',
    550:	'ТО50',
    600:	'ТО50',
    650:	'ТО50',
    700:	'ТО50',
    750:	'ТО250',
    800:	'ТО50',
    850:	'ТО50',
    900:	'ТО50',
    950:	'ТО50',
    1000:	'ТО1000',
    1050:	'ТО50',
    1100:	'ТО50',
    1150:	'ТО50',
    1200:	'ТО50',
    1250:	'ТО250',
    1300:	'ТО50',
    1350:	'ТО50',
    1400:	'ТО50',
    1450:	'ТО50',
    1500:	'ТО500',
    1550:	'ТО50',
    1600:	'ТО50',
    1650:	'ТО50',
    1700:	'ТО50',
    1750:	'ТО250',
    1800:	'ТО50',
    1850:	'ТО50',
    1900:	'ТО50',
    1950:	'ТО50',
    2000:	'ТО2000',
    2050:	'ТО50',
    2100:	'ТО50',
    2150:	'ТО50',
    2200:	'ТО50',
    2250:	'ТО250',
    2300:	'ТО50',
    2350:	'ТО50',
    2400:	'ТО50',
    2450:	'ТО50',
    2500:	'ТО500',
    2550:	'ТО50',
    2600:	'ТО50',
    2650:	'ТО50',
    2700:	'ТО50',
    2750:	'ТО250',
    2800:	'ТО50',
    2850:	'ТО50',
    2900:	'ТО50',
    2950:	'ТО50',
    3000:	'ТО1000',
    3050:	'ТО50',
    3100:	'ТО50',
    3150:	'ТО50',
    3200:	'ТО50',
    3250:	'ТО250',
    3300:	'ТО50',
    3350:	'ТО50',
    3400:	'ТО50',
    3450:	'ТО50',
    3500:	'ТО500',
    3550:	'ТО50',
    3600:	'ТО50',
    3650:	'ТО50',
    3700:	'ТО50',
    3750:	'ТО250',
    3800:	'ТО50',
    3850:	'ТО50',
    3900:	'ТО50',
    3950:	'ТО50',
    4000:	'ТО4000',
    4050:	'ТО50',
    4100:	'ТО50',
    4150:	'ТО50',
    4200:	'ТО50',
    4250:	'ТО250',
    4300:	'ТО50',
    4350:	'ТО50',
    4400:	'ТО50',
    4450:	'ТО50',
    4500:	'ТО500',
    4550:	'ТО50',
    4600:	'ТО50',
    4650:	'ТО50',
    4700:	'ТО50',
    4750:	'ТО250',
    4800:	'ТО50',
    4850:	'ТО50',
    4900:	'ТО50',
    4950:	'ТО50',
    5000:	'ТО1000',
    5050:	'ТО50',
    5100:	'ТО50',
    5150:	'ТО50',
    5200:	'ТО50',
    5250:	'ТО250',
    5300:	'ТО50',
    5350:	'ТО50',
    5400:	'ТО50',
    5450:	'ТО50',
    5500:	'ТО500',
    5550:	'ТО50',
    5600:	'ТО50',
    5650:	'ТО50',
    5700:	'ТО50',
    5750:	'ТО250',
    5800:	'ТО50',
    5850:	'ТО50',
    5900:	'ТО50',
    5950:	'ТО50',
    6000:	'ТО2000',
    6050:	'ТО50',
    6100:	'ТО50',
    6150:	'ТО50',
    6200:	'ТО50',
    6250:	'ТО250',
    6300:	'ТО50',
    6350:	'ТО50',
    6400:	'ТО50',
    6450:	'ТО50',
    6500:	'ТО500',
    6550:	'ТО50',
    6600:	'ТО50',
    6650:	'ТО50',
    6700:	'ТО50',
    6750:	'ТО250',
    6800:	'ТО50',
    6850:	'ТО50',
    6900:	'ТО50',
    6950:	'ТО50',
    7000:	'ТО1000',
    7050:	'ТО50',
    7100:	'ТО50',
    7150:	'ТО50',
    7200:	'ТО50',
    7250:	'ТО250',
    7300:	'ТО50',
    7350:	'ТО50',
    7400:	'ТО50',
    7450:	'ТО50',
    7500:	'ТО500',
    7550:	'ТО50',
    7600:	'ТО50',
    7650:	'ТО50',
    7700:	'ТО50',
    7750:	'ТО250',
    7800:	'ТО50',
    7850:	'ТО50',
    7900:	'ТО50',
    7950:	'ТО50',
    8000:	'ТО4000',
    8050:	'ТО50',
    8100:	'ТО50',
    8150:	'ТО50',
    8200:	'ТО50',
    8250:	'ТО250',
    8300:	'ТО50',
    8350:	'ТО50',
    8400:	'ТО50',
    8450:	'ТО50',
    8500:	'ТО500',
    8550:	'ТО50',
    8600:	'ТО50',
    8650:	'ТО50',
    8700:	'ТО50',
    8750:	'ТО250',
    8800:	'ТО50',
    8850:	'ТО50',
    8900:	'ТО50',
    8950:	'ТО50',
    9000:	'ТО1000',
    9050:	'ТО50',
    9100:	'ТО50',
    9150:	'ТО50',
    9200:	'ТО50',
    9250:	'ТО250',
    9300:	'ТО50',
    9350:	'ТО50',
    9400:	'ТО50',
    9450:	'ТО50',
    9500:	'ТО500',
    9550:	'ТО50',
    9600:	'ТО50',
    9650:	'ТО50',
    9700:	'ТО50',
    9750:	'ТО250',
    9800:	'ТО50',
    9850:	'ТО50',
    9900:	'ТО50',
    9950:	'ТО50',
    10000:	'ТО2000',
    10050:	'ТО50',
    10100:	'ТО50',
    10150:	'ТО50',
    10200:	'ТО50',
    10250:	'ТО250',
    10300:	'ТО50',
    10350:	'ТО50',
    10400:	'ТО50',
    10450:	'ТО50',
    10500:	'ТО500',
    10550:	'ТО50',
    10600:	'ТО50',
    10650:	'ТО50',
    10700:	'ТО50',
    10750:	'ТО250',
    10800:	'ТО50',
    10850:	'ТО50',
    10900:	'ТО50',
    10950:	'ТО50',
    11000:	'ТО1000',
    11050:	'ТО50',
    11100:	'ТО50',
    11150:	'ТО50',
    11200:	'ТО50',
    11250:	'ТО250',
    11300:	'ТО50',
    11350:	'ТО50',
    11400:	'ТО50',
    11450:	'ТО50',
    11500:	'ТО500',
    11550:	'ТО50',
    11600:	'ТО50',
    11650:	'ТО50',
    11700:	'ТО50',
    11750:	'ТО250',
    11800:	'ТО50',
    11850:	'ТО50',
    11900:	'ТО50',
    11950:	'ТО50',
    12000:	'ТО4000',
    12050:	'ТО50',
    12100:	'ТО50',
    12150:	'ТО50',
    12200:	'ТО50',
    12250:	'ТО250',
    12300:	'ТО50',
    12350:	'ТО50',
    12400:	'ТО50',
    12450:	'ТО50',
    12500:	'ТО500',
    12550:	'ТО50',
    12600:	'ТО50',
    12650:	'ТО50',
    12700:	'ТО50',
    12750:	'ТО250',
    12800:	'ТО50',
    12850:	'ТО50',
    12900:	'ТО50',
    12950:	'ТО50',
    13000:	'ТО1000',
    13050:	'ТО50',
    13100:	'ТО50',
    13150:	'ТО50',
    13200:	'ТО50',
    13250:	'ТО250',
    13300:	'ТО50',
    13350:	'ТО50',
    13400:	'ТО50',
    13450:	'ТО50',
    13500:	'ТО500',
    13550:	'ТО50',
    13600:	'ТО50',
    13650:	'ТО50',
    13700:	'ТО50',
    13750:	'ТО250',
    13800:	'ТО50',
    13850:	'ТО50',
    13900:	'ТО50',
    13950:	'ТО50',
    14000:	'ТО2000',
    14050:	'ТО50',
    14100:	'ТО50',
    14150:	'ТО50',
    14200:	'ТО50',
    14250:	'ТО250',
    14300:	'ТО50',
    14350:	'ТО50',
    14400:	'ТО50',
    14450:	'ТО50',
    14500:	'ТО500',
    14550:	'ТО50',
    14600:	'ТО50',
    14650:	'ТО50',
    14700:	'ТО50',
    14750:	'ТО250',
    14800:	'ТО50',
    14850:	'ТО50',
    14900:	'ТО50',
    14950:	'ТО50',
    15000:	'ТО1000',
    15050:	'ТО50',
    15100:	'ТО50',
    15150:	'ТО50',
    15200:	'ТО50',
    15250:	'ТО250',
    15300:	'ТО50',
    15350:	'ТО50',
    15400:	'ТО50',
    15450:	'ТО50',
    15500:	'ТО500',
    15550:	'ТО50',
    15600:	'ТО50',
    15650:	'ТО50',
    15700:	'ТО50',
    15750:	'ТО250',
    15800:	'ТО50',
    15850:	'ТО50',
    15900:	'ТО50',
    15950:	'ТО50',
    16000:	'ТО4000',
    16050:	'ТО50',
    16100:	'ТО50',
    16150:	'ТО50',
    16200:	'ТО50',
    16250:	'ТО250',
    16300:	'ТО50',
    16350:	'ТО50',
    16400:	'ТО50',
    16450:	'ТО50',
    16500:	'ТО500',
    16550:	'ТО50',
    16600:	'ТО50',
    16650:	'ТО50',
    16700:	'ТО50',
    16750:	'ТО250',
    16800:	'ТО50',
    16850:	'ТО50',
    16900:	'ТО50',
    16950:	'ТО50',
    17000:	'ТО1000',
    17050:	'ТО50',
    17100:	'ТО50',
    17150:	'ТО50',
    17200:	'ТО50',
    17250:	'ТО250',
    17300:	'ТО50',
    17350:	'ТО50',
    17400:	'ТО50',
    17450:	'ТО50',
    17500:	'ТО500',
    17550:	'ТО50',
    17600:	'ТО50',
    17650:	'ТО50',
    17700:	'ТО50',
    17750:	'ТО250',
    17800:	'ТО50',
    17850:	'ТО50',
    17900:	'ТО50',
    17950:	'ТО50',
    18000:	'ТО2000',
    18050:	'ТО50',
    18100:	'ТО50',
    18150:	'ТО50',
    18200:	'ТО50',
    18250:	'ТО250',
    18300:	'ТО50',
    18350:	'ТО50',
    18400:	'ТО50',
    18450:	'ТО50',
    18500:	'ТО500',
    18550:	'ТО50',
    18600:	'ТО50',
    18650:	'ТО50',
    18700:	'ТО50',
    18750:	'ТО250',
    18800:	'ТО50',
    18850:	'ТО50',
    18900:	'ТО50',
    18950:	'ТО50',
    19000:	'ТО1000',
    19050:	'ТО50',
    19100:	'ТО50',
    19150:	'ТО50',
    19200:	'ТО50',
    19250:	'ТО250',
    19300:	'ТО50',
    19350:	'ТО50',
    19400:	'ТО50',
    19450:	'ТО50',
    19500:	'ТО500',
    19550:	'ТО50',
    19600:	'ТО50',
    19650:	'ТО50',
    19700:	'ТО50',
    19750:	'ТО250',
    19800:	'ТО50',
    19850:	'ТО50',
    19900:	'ТО50',
    19950:	'ТО50',
    20000:	'ТО4000',
    20050:	'ТО50',
    20100:	'ТО50',
    20150:	'ТО50',
    20200:	'ТО50',
    20250:	'ТО250',
    20300:	'ТО50',
    20350:	'ТО50',
    20400:	'ТО50',
    20450:	'ТО50',
    20500:	'ТО500',
    20550:	'ТО50',
    20600:	'ТО50',
    20650:	'ТО50',
    20700:	'ТО50',
    20750:	'ТО250',
    20800:	'ТО50',
    20850:	'ТО50',
    20900:	'ТО50',
    20950:	'ТО50',
    21000:	'ТО1000',
    21050:	'ТО50',
    21100:	'ТО50',
    21150:	'ТО50',
    21200:	'ТО50',
    21250:	'ТО250',
    21300:	'ТО50',
    21350:	'ТО50',
    21400:	'ТО50',
    21450:	'ТО50',
    21500:	'ТО500',
    21550:	'ТО50',
    21600:	'ТО50',
    21650:	'ТО50',
    21700:	'ТО50',
    21750:	'ТО250',
    21800:	'ТО50',
    21850:	'ТО50',
    21900:	'ТО50',
    21950:	'ТО50',
    22000:	'ТО2000',
    22050:	'ТО50',
    22100:	'ТО50',
    22150:	'ТО50',
    22200:	'ТО50',
    22250:	'ТО250',
    22300:	'ТО50',
    22350:	'ТО50',
    22400:	'ТО50',
    22450:	'ТО50',
    22500:	'ТО500',
    22550:	'ТО50',
    22600:	'ТО50',
    22650:	'ТО50',
    22700:	'ТО50',
    22750:	'ТО250',
    22800:	'ТО50',
    22850:	'ТО50',
    22900:	'ТО50',
    22950:	'ТО50',
    23000:	'ТО1000',
    23050:	'ТО50',
    23100:	'ТО50',
    23150:	'ТО50',
    23200:	'ТО50',
    23250:	'ТО250',
    23300:	'ТО50',
    23350:	'ТО50',
    23400:	'ТО50',
    23450:	'ТО50',
    23500:	'ТО500',
    23550:	'ТО50',
    23600:	'ТО50',
    23650:	'ТО50',
    23700:	'ТО50',
    23750:	'ТО250',
    23800:	'ТО50',
    23850:	'ТО50',
    23900:	'ТО50',
    23950:	'ТО50',
    24000:	'ТО4000',
    24050:	'ТО50',
    24100:	'ТО50',
    24150:	'ТО50',
    24200:	'ТО50',
    24250:	'ТО250',
    24300:	'ТО50',
    24350:	'ТО50',
    24400:	'ТО50',
    24450:	'ТО50',
    24500:	'ТО500',
    24550:	'ТО50',
    24600:	'ТО50',
    24650:	'ТО50',
    24700:	'ТО50',
    24750:	'ТО250',
    24800:	'ТО50',
    24850:	'ТО50',
    24900:	'ТО50',
    24950:	'ТО50',
    25000:	'ТО1000',
    25050:	'ТО50',
    25100:	'ТО50',
    25150:	'ТО50',
    25200:	'ТО50',
    25250:	'ТО250',
    25300:	'ТО50',
    25350:	'ТО50',
    25400:	'ТО50',
    25450:	'ТО50',
    25500:	'ТО500',
    25550:	'ТО50',
    25600:	'ТО50',
    25650:	'ТО50',
    25700:	'ТО50',
    25750:	'ТО250',
    25800:	'ТО50',
    25850:	'ТО50',
    25900:	'ТО50',
    25950:	'ТО50',
    26000:	'ТО2000',
    26050:	'ТО50',
    26100:	'ТО50',
    26150:	'ТО50',
    26200:	'ТО50',
    26250:	'ТО250',
    26300:	'ТО50',
    26350:	'ТО50',
    26400:	'ТО50',
    26450:	'ТО50',
    26500:	'ТО500',
    26550:	'ТО50',
    26600:	'ТО50',
    26650:	'ТО50',
    26700:	'ТО50',
    26750:	'ТО250',
    26800:	'ТО50',
    26850:	'ТО50',
    26900:	'ТО50',
    26950:	'ТО50',
    27000:	'ТО1000',
    27050:	'ТО50',
    27100:	'ТО50',
    27150:	'ТО50',
    27200:	'ТО50',
    27250:	'ТО250',
    27300:	'ТО50',
    27350:	'ТО50',
    27400:	'ТО50',
    27450:	'ТО50',
    27500:	'ТО500',
    27550:	'ТО50',
    27600:	'ТО50',
    27650:	'ТО50',
    27700:	'ТО50',
    27750:	'ТО250',
    27800:	'ТО50',
    27850:	'ТО50',
    27900:	'ТО50',
    27950:	'ТО50',
    28000:	'ТО4000',
    28050:	'ТО50',
    28100:	'ТО50',
    28150:	'ТО50',
    28200:	'ТО50',
    28250:	'ТО250',
    28300:	'ТО50',
    28350:	'ТО50',
    28400:	'ТО50',
    28450:	'ТО50',
    28500:	'ТО500',
    28550:	'ТО50',
    28600:	'ТО50',
    28650:	'ТО50',
    28700:	'ТО50',
    28750:	'ТО250',
    28800:	'ТО50',
    28850:	'ТО50',
    28900:	'ТО50',
    28950:	'ТО50',
    29000:	'ТО1000',
    29050:	'ТО50',
    29100:	'ТО50',
    29150:	'ТО50',
    29200:	'ТО50',
    29250:	'ТО250',
    29300:	'ТО50',
    29350:	'ТО50',
    29400:	'ТО50',
    29450:	'ТО50',
    29500:	'ТО500',
    29550:	'ТО50',
    29600:	'ТО50',
    29650:	'ТО50',
    29700:	'ТО50',
    29750:	'ТО250',
    29800:	'ТО50',
    29850:	'ТО50',
    29900:	'ТО50',
    29950:	'ТО50',
    30000:	'ТО2000',
    30050:	'ТО50',
    30100:	'ТО50',
    30150:	'ТО50',
    30200:	'ТО50',
    30250:	'ТО250',
    30300:	'ТО50',
    30350:	'ТО50',
    30400:	'ТО50',
    30450:	'ТО50',
    30500:	'ТО500',
    30550:	'ТО50',
    30600:	'ТО50',
    30650:	'ТО50',
    30700:	'ТО50',
    30750:	'ТО250',
    30800:	'ТО50',
    30850:	'ТО50',
    30900:	'ТО50',
    30950:	'ТО50',
    31000:	'ТО1000',
    31050:	'ТО50',
    31100:	'ТО50',
    31150:	'ТО50',
    31200:	'ТО50',
    31250:	'ТО250',
    31300:	'ТО50',
    31350:	'ТО50',
    31400:	'ТО50',
    31450:	'ТО50',
    31500:	'ТО500',
    31550:	'ТО50',
    31600:	'ТО50',
    31650:	'ТО50',
    31700:	'ТО50',
    31750:	'ТО250',
    31800:	'ТО50',
    31850:	'ТО50',
    31900:	'ТО50',
    31950:	'ТО50',
    32000:	'ТО4000',
    32050:	'ТО50',
    32100:	'ТО50',
    32150:	'ТО50',
    32200:	'ТО50',
    32250:	'ТО250',
    32300:	'ТО50',
    32350:	'ТО50',
    32400:	'ТО50',
    32450:	'ТО50',
    32500:	'ТО500',
    32550:	'ТО50',
    32600:	'ТО50',
    32650:	'ТО50',
    32700:	'ТО50',
    32750:	'ТО250',
    32800:	'ТО50',
    32850:	'ТО50',
    32900:	'ТО50',
    32950:	'ТО50',
    33000:	'ТО1000',
    33050:	'ТО50',
    33100:	'ТО50',
    33150:	'ТО50',
    33200:	'ТО50',
    33250:	'ТО250',
    33300:	'ТО50',
    33350:	'ТО50',
    33400:	'ТО50',
    33450:	'ТО50',
    33500:	'ТО500',
    33550:	'ТО50',
    33600:	'ТО50',
    33650:	'ТО50',
    33700:	'ТО50',
    33750:	'ТО250',
    33800:	'ТО50',
    33850:	'ТО50',
    33900:	'ТО50',
    33950:	'ТО50',
    34000:	'ТО2000',
    34050:	'ТО50',
    34100:	'ТО50',
    34150:	'ТО50',
    34200:	'ТО50',
    34250:	'ТО250',
    34300:	'ТО50',
    34350:	'ТО50',
    34400:	'ТО50',
    34450:	'ТО50',
    34500:	'ТО500',
    34550:	'ТО50',
    34600:	'ТО50',
    34650:	'ТО50',
    34700:	'ТО50',
    34750:	'ТО250',
    34800:	'ТО50',
    34850:	'ТО50',
    34900:	'ТО50',
    34950:	'ТО50',
    35000:	'ТО1000',
    35050:	'ТО50',
    35100:	'ТО50',
    35150:	'ТО50',
    35200:	'ТО50',
    35250:	'ТО250',
    35300:	'ТО50',
    35350:	'ТО50',
    35400:	'ТО50',
    35450:	'ТО50',
    35500:	'ТО500',
    35550:	'ТО50',
    35600:	'ТО50',
    35650:	'ТО50',
    35700:	'ТО50',
    35750:	'ТО250',
    35800:	'ТО50',
    35850:	'ТО50',
    35900:	'ТО50',
    35950:	'ТО50',
    36000:	'ТО4000',
    36050:	'ТО50',
    36100:	'ТО50',
    36150:	'ТО50',
    36200:	'ТО50',
    36250:	'ТО250',
    36300:	'ТО50',
    36350:	'ТО50',
    36400:	'ТО50',
    36450:	'ТО50',
    36500:	'ТО500',
    36550:	'ТО50',
    36600:	'ТО50',
    36650:	'ТО50',
    36700:	'ТО50',
    36750:	'ТО250',
    36800:	'ТО50',
    36850:	'ТО50',
    36900:	'ТО50',
    36950:	'ТО50',
    37000:	'ТО1000',
    37050:	'ТО50',
    37100:	'ТО50',
    37150:	'ТО50',
    37200:	'ТО50',
    37250:	'ТО250',
    37300:	'ТО50',
    37350:	'ТО50',
    37400:	'ТО50',
    37450:	'ТО50',
    37500:	'ТО500',
    37550:	'ТО50',
    37600:	'ТО50',
    37650:	'ТО50',
    37700:	'ТО50',
    37750:	'ТО250',
    37800:	'ТО50',
    37850:	'ТО50',
    37900:	'ТО50',
    37950:	'ТО50',
    38000:	'ТО2000',
    38050:	'ТО50',
    38100:	'ТО50',
    38150:	'ТО50',
    38200:	'ТО50',
    38250:	'ТО250',
    38300:	'ТО50',
    38350:	'ТО50',
    38400:	'ТО50',
    38450:	'ТО50',
    38500:	'ТО500',
    38550:	'ТО50',
    38600:	'ТО50',
    38650:	'ТО50',
    38700:	'ТО50',
    38750:	'ТО250',
    38800:	'ТО50',
    38850:	'ТО50',
    38900:	'ТО50',
    38950:	'ТО50',
    39000:	'ТО1000',
    39050:	'ТО50',
    39100:	'ТО50',
    39150:	'ТО50',
    39200:	'ТО50',
    39250:	'ТО250',
    39300:	'ТО50',
    39350:	'ТО50',
    39400:	'ТО50',
    39450:	'ТО50',
    39500:	'ТО500',
    39550:	'ТО50',
    39600:	'ТО50',
    39650:	'ТО50',
    39700:	'ТО50',
    39750:	'ТО250',
    39800:	'ТО50',
    39850:	'ТО50',
    39900:	'ТО50',
    39950:	'ТО50',
    40000:	'ТО4000',
    40050:	'ТО50',
    40100:	'ТО50',
    40150:	'ТО50',
    40200:	'ТО50',
    40250:	'ТО250',
    40300:	'ТО50',
    40350:	'ТО50',
    40400:	'ТО50',
    40450:	'ТО50',
    40500:	'ТО500',
    40550:	'ТО50',
    40600:	'ТО50',
    40650:	'ТО50',
    40700:	'ТО50',
    40750:	'ТО250',
    40800:	'ТО50',
    40850:	'ТО50',
    40900:	'ТО50',
    40950:	'ТО50',
    41000:	'ТО1000',
    41050:	'ТО50',
    41100:	'ТО50',
    41150:	'ТО50',
    41200:	'ТО50',
    41250:	'ТО250',
    41300:	'ТО50',
    41350:	'ТО50',
    41400:	'ТО50',
    41450:	'ТО50',
    41500:	'ТО500',
    41550:	'ТО50',
    41600:	'ТО50',
    41650:	'ТО50',
    41700:	'ТО50',
    41750:	'ТО250',
    41800:	'ТО50',
    41850:	'ТО50',
    41900:	'ТО50',
    41950:	'ТО50',
    42000:	'ТО2000',
    42050:	'ТО50',
    42100:	'ТО50',
    42150:	'ТО50',
    42200:	'ТО50',
    42250:	'ТО250',
    42300:	'ТО50',
    42350:	'ТО50',
    42400:	'ТО50',
    42450:	'ТО50',
    42500:	'ТО500',
    42550:	'ТО50',
    42600:	'ТО50',
    42650:	'ТО50',
    42700:	'ТО50',
    42750:	'ТО250',
    42800:	'ТО50',
    42850:	'ТО50',
    42900:	'ТО50',
    42950:	'ТО50',
    43000:	'ТО1000',
    43050:	'ТО50',
    43100:	'ТО50',
    43150:	'ТО50',
    43200:	'ТО50',
    43250:	'ТО250',
    43300:	'ТО50',
    43350:	'ТО50',
    43400:	'ТО50',
    43450:	'ТО50',
    43500:	'ТО500',
    43550:	'ТО50',
    43600:	'ТО50',
    43650:	'ТО50',
    43700:	'ТО50',
    43750:	'ТО250',
    43800:	'ТО50',
    43850:	'ТО50',
    43900:	'ТО50',
    43950:	'ТО50',
    44000:	'ТО4000',
    44050:	'ТО50',
    44100:	'ТО50',
    44150:	'ТО50',
    44200:	'ТО50',
    44250:	'ТО250',
    44300:	'ТО50',
    44350:	'ТО50',
    44400:	'ТО50',
    44450:	'ТО50',
    44500:	'ТО500',
    44550:	'ТО50',
    44600:	'ТО50',
    44650:	'ТО50',
    44700:	'ТО50',
    44750:	'ТО250',
    44800:	'ТО50',
    44850:	'ТО50',
    44900:	'ТО50',
    44950:	'ТО50',
    45000:	'ТО1000',
    45050:	'ТО50',
    45100:	'ТО50',
    45150:	'ТО50',
    45200:	'ТО50',
    45250:	'ТО250',
    45300:	'ТО50',
    45350:	'ТО50',
    45400:	'ТО50',
    45450:	'ТО50',
    45500:	'ТО500',
    45550:	'ТО50',
    45600:	'ТО50',
    45650:	'ТО50',
    45700:	'ТО50',
    45750:	'ТО250',
    45800:	'ТО50',
    45850:	'ТО50',
    45900:	'ТО50',
    45950:	'ТО50',
    46000:	'ТО2000',
    46050:	'ТО50',
    46100:	'ТО50',
    46150:	'ТО50',
    46200:	'ТО50',
    46250:	'ТО250',
    46300:	'ТО50',
    46350:	'ТО50',
    46400:	'ТО50',
    46450:	'ТО50',
    46500:	'ТО500',
    46550:	'ТО50',
    46600:	'ТО50',
    46650:	'ТО50',
    46700:	'ТО50',
    46750:	'ТО250',
    46800:	'ТО50',
    46850:	'ТО50',
    46900:	'ТО50',
    46950:	'ТО50',
    47000:	'ТО1000',
    47050:	'ТО50',
    47100:	'ТО50',
    47150:	'ТО50',
    47200:	'ТО50',
    47250:	'ТО250',
    47300:	'ТО50',
    47350:	'ТО50',
    47400:	'ТО50',
    47450:	'ТО50',
    47500:	'ТО500',
    47550:	'ТО50',
    47600:	'ТО50',
    47650:	'ТО50',
    47700:	'ТО50',
    47750:	'ТО250',
    47800:	'ТО50',
    47850:	'ТО50',
    47900:	'ТО50',
    47950:	'ТО50',
    48000:	'ТО4000'



}

In [45]:
to_dict_HD={
    50:	'',
    100:	'',
    150:	'',
    200:	'',
    250:	'ТО250',
    300:	'',
    350:	'',
    400:	'',
    450:	'',
    500:	'ТО500',
    550:	'',
    600:	'',
    650:	'',
    700:	'',
    750:	'ТО250',
    800:	'',
    850:	'',
    900:	'',
    950:	'',
    1000:	'ТО1000',
    1050:	'',
    1100:	'',
    1150:	'',
    1200:	'',
    1250:	'ТО250',
    1300:	'',
    1350:	'',
    1400:	'',
    1450:	'',
    1500:	'ТО500',
    1550:	'',
    1600:	'',
    1650:	'',
    1700:	'',
    1750:	'ТО250',
    1800:	'',
    1850:	'',
    1900:	'',
    1950:	'',
    2000:	'ТО2000',
    2050:	'',
    2100:	'',
    2150:	'',
    2200:	'',
    2250:	'ТО250',
    2300:	'',
    2350:	'',
    2400:	'',
    2450:	'',
    2500:	'ТО500',
    2550:	'',
    2600:	'',
    2650:	'',
    2700:	'',
    2750:	'ТО250',
    2800:	'',
    2850:	'',
    2900:	'',
    2950:	'',
    3000:	'ТО1000',
    3050:	'',
    3100:	'',
    3150:	'',
    3200:	'',
    3250:	'ТО250',
    3300:	'',
    3350:	'',
    3400:	'',
    3450:	'',
    3500:	'ТО500',
    3550:	'',
    3600:	'',
    3650:	'',
    3700:	'',
    3750:	'ТО250',
    3800:	'',
    3850:	'',
    3900:	'',
    3950:	'',
    4000:	'ТО4000',
    4050:	'',
    4100:	'',
    4150:	'',
    4200:	'',
    4250:	'ТО250',
    4300:	'',
    4350:	'',
    4400:	'',
    4450:	'',
    4500:	'ТО500',
    4550:	'',
    4600:	'',
    4650:	'',
    4700:	'',
    4750:	'ТО250',
    4800:	'',
    4850:	'',
    4900:	'',
    4950:	'',
    5000:	'ТО1000',
    5050:	'',
    5100:	'',
    5150:	'',
    5200:	'',
    5250:	'ТО250',
    5300:	'',
    5350:	'',
    5400:	'',
    5450:	'',
    5500:	'ТО500',
    5550:	'',
    5600:	'',
    5650:	'',
    5700:	'',
    5750:	'ТО250',
    5800:	'',
    5850:	'',
    5900:	'',
    5950:	'',
    6000:	'ТО2000',
    6050:	'',
    6100:	'',
    6150:	'',
    6200:	'',
    6250:	'ТО250',
    6300:	'',
    6350:	'',
    6400:	'',
    6450:	'',
    6500:	'ТО500',
    6550:	'',
    6600:	'',
    6650:	'',
    6700:	'',
    6750:	'ТО250',
    6800:	'',
    6850:	'',
    6900:	'',
    6950:	'',
    7000:	'ТО1000',
    7050:	'',
    7100:	'',
    7150:	'',
    7200:	'',
    7250:	'ТО250',
    7300:	'',
    7350:	'',
    7400:	'',
    7450:	'',
    7500:	'ТО500',
    7550:	'',
    7600:	'',
    7650:	'',
    7700:	'',
    7750:	'ТО250',
    7800:	'',
    7850:	'',
    7900:	'',
    7950:	'',
    8000:	'ТО4000',
    8050:	'',
    8100:	'',
    8150:	'',
    8200:	'',
    8250:	'ТО250',
    8300:	'',
    8350:	'',
    8400:	'',
    8450:	'',
    8500:	'ТО500',
    8550:	'',
    8600:	'',
    8650:	'',
    8700:	'',
    8750:	'ТО250',
    8800:	'',
    8850:	'',
    8900:	'',
    8950:	'',
    9000:	'ТО1000',
    9050:	'',
    9100:	'',
    9150:	'',
    9200:	'',
    9250:	'ТО250',
    9300:	'',
    9350:	'',
    9400:	'',
    9450:	'',
    9500:	'ТО500',
    9550:	'',
    9600:	'',
    9650:	'',
    9700:	'',
    9750:	'ТО250',
    9800:	'',
    9850:	'',
    9900:	'',
    9950:	'',
    10000:	'ТО2000',
    10050:	'',
    10100:	'',
    10150:	'',
    10200:	'',
    10250:	'ТО250',
    10300:	'',
    10350:	'',
    10400:	'',
    10450:	'',
    10500:	'ТО500',
    10550:	'',
    10600:	'',
    10650:	'',
    10700:	'',
    10750:	'ТО250',
    10800:	'',
    10850:	'',
    10900:	'',
    10950:	'',
    11000:	'ТО1000',
    11050:	'',
    11100:	'',
    11150:	'',
    11200:	'',
    11250:	'ТО250',
    11300:	'',
    11350:	'',
    11400:	'',
    11450:	'',
    11500:	'ТО500',
    11550:	'',
    11600:	'',
    11650:	'',
    11700:	'',
    11750:	'ТО250',
    11800:	'',
    11850:	'',
    11900:	'',
    11950:	'',
    12000:	'ТО4000',
    12050:	'',
    12100:	'',
    12150:	'',
    12200:	'',
    12250:	'ТО250',
    12300:	'',
    12350:	'',
    12400:	'',
    12450:	'',
    12500:	'ТО500',
    12550:	'',
    12600:	'',
    12650:	'',
    12700:	'',
    12750:	'ТО250',
    12800:	'',
    12850:	'',
    12900:	'',
    12950:	'',
    13000:	'ТО1000',
    13050:	'',
    13100:	'',
    13150:	'',
    13200:	'',
    13250:	'ТО250',
    13300:	'',
    13350:	'',
    13400:	'',
    13450:	'',
    13500:	'ТО500',
    13550:	'',
    13600:	'',
    13650:	'',
    13700:	'',
    13750:	'ТО250',
    13800:	'',
    13850:	'',
    13900:	'',
    13950:	'',
    14000:	'ТО2000',
    14050:	'',
    14100:	'',
    14150:	'',
    14200:	'',
    14250:	'ТО250',
    14300:	'',
    14350:	'',
    14400:	'',
    14450:	'',
    14500:	'ТО500',
    14550:	'',
    14600:	'',
    14650:	'',
    14700:	'',
    14750:	'ТО250',
    14800:	'',
    14850:	'',
    14900:	'',
    14950:	'',
    15000:	'ТО1000',
    15050:	'',
    15100:	'',
    15150:	'',
    15200:	'',
    15250:	'ТО250',
    15300:	'',
    15350:	'',
    15400:	'',
    15450:	'',
    15500:	'ТО500',
    15550:	'',
    15600:	'',
    15650:	'',
    15700:	'',
    15750:	'ТО250',
    15800:	'',
    15850:	'',
    15900:	'',
    15950:	'',
    16000:	'ТО4000',
    16050:	'',
    16100:	'',
    16150:	'',
    16200:	'',
    16250:	'ТО250',
    16300:	'',
    16350:	'',
    16400:	'',
    16450:	'',
    16500:	'ТО500',
    16550:	'',
    16600:	'',
    16650:	'',
    16700:	'',
    16750:	'ТО250',
    16800:	'',
    16850:	'',
    16900:	'',
    16950:	'',
    17000:	'ТО1000',
    17050:	'',
    17100:	'',
    17150:	'',
    17200:	'',
    17250:	'ТО250',
    17300:	'',
    17350:	'',
    17400:	'',
    17450:	'',
    17500:	'ТО500',
    17550:	'',
    17600:	'',
    17650:	'',
    17700:	'',
    17750:	'ТО250',
    17800:	'',
    17850:	'',
    17900:	'',
    17950:	'',
    18000:	'ТО2000',
    18050:	'',
    18100:	'',
    18150:	'',
    18200:	'',
    18250:	'ТО250',
    18300:	'',
    18350:	'',
    18400:	'',
    18450:	'',
    18500:	'ТО500',
    18550:	'',
    18600:	'',
    18650:	'',
    18700:	'',
    18750:	'ТО250',
    18800:	'',
    18850:	'',
    18900:	'',
    18950:	'',
    19000:	'ТО1000',
    19050:	'',
    19100:	'',
    19150:	'',
    19200:	'',
    19250:	'ТО250',
    19300:	'',
    19350:	'',
    19400:	'',
    19450:	'',
    19500:	'ТО500',
    19550:	'',
    19600:	'',
    19650:	'',
    19700:	'',
    19750:	'ТО250',
    19800:	'',
    19850:	'',
    19900:	'',
    19950:	'',
    20000:	'ТО4000',
    20050:	'',
    20100:	'',
    20150:	'',
    20200:	'',
    20250:	'ТО250',
    20300:	'',
    20350:	'',
    20400:	'',
    20450:	'',
    20500:	'ТО500',
    20550:	'',
    20600:	'',
    20650:	'',
    20700:	'',
    20750:	'ТО250',
    20800:	'',
    20850:	'',
    20900:	'',
    20950:	'',
    21000:	'ТО1000',
    21050:	'',
    21100:	'',
    21150:	'',
    21200:	'',
    21250:	'ТО250',
    21300:	'',
    21350:	'',
    21400:	'',
    21450:	'',
    21500:	'ТО500',
    21550:	'',
    21600:	'',
    21650:	'',
    21700:	'',
    21750:	'ТО250',
    21800:	'',
    21850:	'',
    21900:	'',
    21950:	'',
    22000:	'ТО2000',
    22050:	'',
    22100:	'',
    22150:	'',
    22200:	'',
    22250:	'ТО250',
    22300:	'',
    22350:	'',
    22400:	'',
    22450:	'',
    22500:	'ТО500',
    22550:	'',
    22600:	'',
    22650:	'',
    22700:	'',
    22750:	'ТО250',
    22800:	'',
    22850:	'',
    22900:	'',
    22950:	'',
    23000:	'ТО1000',
    23050:	'',
    23100:	'',
    23150:	'',
    23200:	'',
    23250:	'ТО250',
    23300:	'',
    23350:	'',
    23400:	'',
    23450:	'',
    23500:	'ТО500',
    23550:	'',
    23600:	'',
    23650:	'',
    23700:	'',
    23750:	'ТО250',
    23800:	'',
    23850:	'',
    23900:	'',
    23950:	'',
    24000:	'ТО4000',
    24050:	'',
    24100:	'',
    24150:	'',
    24200:	'',
    24250:	'ТО250',
    24300:	'',
    24350:	'',
    24400:	'',
    24450:	'',
    24500:	'ТО500',
    24550:	'',
    24600:	'',
    24650:	'',
    24700:	'',
    24750:	'ТО250',
    24800:	'',
    24850:	'',
    24900:	'',
    24950:	'',
    25000:	'ТО1000',
    25050:	'',
    25100:	'',
    25150:	'',
    25200:	'',
    25250:	'ТО250',
    25300:	'',
    25350:	'',
    25400:	'',
    25450:	'',
    25500:	'ТО500',
    25550:	'',
    25600:	'',
    25650:	'',
    25700:	'',
    25750:	'ТО250',
    25800:	'',
    25850:	'',
    25900:	'',
    25950:	'',
    26000:	'ТО2000',
    26050:	'',
    26100:	'',
    26150:	'',
    26200:	'',
    26250:	'ТО250',
    26300:	'',
    26350:	'',
    26400:	'',
    26450:	'',
    26500:	'ТО500',
    26550:	'',
    26600:	'',
    26650:	'',
    26700:	'',
    26750:	'ТО250',
    26800:	'',
    26850:	'',
    26900:	'',
    26950:	'',
    27000:	'ТО1000',
    27050:	'',
    27100:	'',
    27150:	'',
    27200:	'',
    27250:	'ТО250',
    27300:	'',
    27350:	'',
    27400:	'',
    27450:	'',
    27500:	'ТО500',
    27550:	'',
    27600:	'',
    27650:	'',
    27700:	'',
    27750:	'ТО250',
    27800:	'',
    27850:	'',
    27900:	'',
    27950:	'',
    28000:	'ТО4000',
    28050:	'',
    28100:	'',
    28150:	'',
    28200:	'',
    28250:	'ТО250',
    28300:	'',
    28350:	'',
    28400:	'',
    28450:	'',
    28500:	'ТО500',
    28550:	'',
    28600:	'',
    28650:	'',
    28700:	'',
    28750:	'ТО250',
    28800:	'',
    28850:	'',
    28900:	'',
    28950:	'',
    29000:	'ТО1000',
    29050:	'',
    29100:	'',
    29150:	'',
    29200:	'',
    29250:	'ТО250',
    29300:	'',
    29350:	'',
    29400:	'',
    29450:	'',
    29500:	'ТО500',
    29550:	'',
    29600:	'',
    29650:	'',
    29700:	'',
    29750:	'ТО250',
    29800:	'',
    29850:	'',
    29900:	'',
    29950:	'',
    30000:	'ТО2000',
    30050:	'',
    30100:	'',
    30150:	'',
    30200:	'',
    30250:	'ТО250',
    30300:	'',
    30350:	'',
    30400:	'',
    30450:	'',
    30500:	'ТО500',
    30550:	'',
    30600:	'',
    30650:	'',
    30700:	'',
    30750:	'ТО250',
    30800:	'',
    30850:	'',
    30900:	'',
    30950:	'',
    31000:	'ТО1000',
    31050:	'',
    31100:	'',
    31150:	'',
    31200:	'',
    31250:	'ТО250',
    31300:	'',
    31350:	'',
    31400:	'',
    31450:	'',
    31500:	'ТО500',
    31550:	'',
    31600:	'',
    31650:	'',
    31700:	'',
    31750:	'ТО250',
    31800:	'',
    31850:	'',
    31900:	'',
    31950:	'',
    32000:	'ТО4000',
    32050:	'',
    32100:	'',
    32150:	'',
    32200:	'',
    32250:	'ТО250',
    32300:	'',
    32350:	'',
    32400:	'',
    32450:	'',
    32500:	'ТО500',
    32550:	'',
    32600:	'',
    32650:	'',
    32700:	'',
    32750:	'ТО250',
    32800:	'',
    32850:	'',
    32900:	'',
    32950:	'',
    33000:	'ТО1000',
    33050:	'',
    33100:	'',
    33150:	'',
    33200:	'',
    33250:	'ТО250',
    33300:	'',
    33350:	'',
    33400:	'',
    33450:	'',
    33500:	'ТО500',
    33550:	'',
    33600:	'',
    33650:	'',
    33700:	'',
    33750:	'ТО250',
    33800:	'',
    33850:	'',
    33900:	'',
    33950:	'',
    34000:	'ТО2000',
    34050:	'',
    34100:	'',
    34150:	'',
    34200:	'',
    34250:	'ТО250',
    34300:	'',
    34350:	'',
    34400:	'',
    34450:	'',
    34500:	'ТО500',
    34550:	'',
    34600:	'',
    34650:	'',
    34700:	'',
    34750:	'ТО250',
    34800:	'',
    34850:	'',
    34900:	'',
    34950:	'',
    35000:	'ТО1000',
    35050:	'',
    35100:	'',
    35150:	'',
    35200:	'',
    35250:	'ТО250',
    35300:	'',
    35350:	'',
    35400:	'',
    35450:	'',
    35500:	'ТО500',
    35550:	'',
    35600:	'',
    35650:	'',
    35700:	'',
    35750:	'ТО250',
    35800:	'',
    35850:	'',
    35900:	'',
    35950:	'',
    36000:	'ТО4000',
    36050:	'',
    36100:	'',
    36150:	'',
    36200:	'',
    36250:	'ТО250',
    36300:	'',
    36350:	'',
    36400:	'',
    36450:	'',
    36500:	'ТО500',
    36550:	'',
    36600:	'',
    36650:	'',
    36700:	'',
    36750:	'ТО250',
    36800:	'',
    36850:	'',
    36900:	'',
    36950:	'',
    37000:	'ТО1000',
    37050:	'',
    37100:	'',
    37150:	'',
    37200:	'',
    37250:	'ТО250',
    37300:	'',
    37350:	'',
    37400:	'',
    37450:	'',
    37500:	'ТО500',
    37550:	'',
    37600:	'',
    37650:	'',
    37700:	'',
    37750:	'ТО250',
    37800:	'',
    37850:	'',
    37900:	'',
    37950:	'',
    38000:	'ТО2000',
    38050:	'',
    38100:	'',
    38150:	'',
    38200:	'',
    38250:	'ТО250',
    38300:	'',
    38350:	'',
    38400:	'',
    38450:	'',
    38500:	'ТО500',
    38550:	'',
    38600:	'',
    38650:	'',
    38700:	'',
    38750:	'ТО250',
    38800:	'',
    38850:	'',
    38900:	'',
    38950:	'',
    39000:	'ТО1000',
    39050:	'',
    39100:	'',
    39150:	'',
    39200:	'',
    39250:	'ТО250',
    39300:	'',
    39350:	'',
    39400:	'',
    39450:	'',
    39500:	'ТО500',
    39550:	'',
    39600:	'',
    39650:	'',
    39700:	'',
    39750:	'ТО250',
    39800:	'',
    39850:	'',
    39900:	'',
    39950:	'',
    40000:	'ТО4000',
    40050:	'',
    40100:	'',
    40150:	'',
    40200:	'',
    40250:	'ТО250',
    40300:	'',
    40350:	'',
    40400:	'',
    40450:	'',
    40500:	'ТО500',
    40550:	'',
    40600:	'',
    40650:	'',
    40700:	'',
    40750:	'ТО250',
    40800:	'',
    40850:	'',
    40900:	'',
    40950:	'',
    41000:	'ТО1000',
    41050:	'',
    41100:	'',
    41150:	'',
    41200:	'',
    41250:	'ТО250',
    41300:	'',
    41350:	'',
    41400:	'',
    41450:	'',
    41500:	'ТО500',
    41550:	'',
    41600:	'',
    41650:	'',
    41700:	'',
    41750:	'ТО250',
    41800:	'',
    41850:	'',
    41900:	'',
    41950:	'',
    42000:	'ТО2000',
    42050:	'',
    42100:	'',
    42150:	'',
    42200:	'',
    42250:	'ТО250',
    42300:	'',
    42350:	'',
    42400:	'',
    42450:	'',
    42500:	'ТО500',
    42550:	'',
    42600:	'',
    42650:	'',
    42700:	'',
    42750:	'ТО250',
    42800:	'',
    42850:	'',
    42900:	'',
    42950:	'',
    43000:	'ТО1000',
    43050:	'',
    43100:	'',
    43150:	'',
    43200:	'',
    43250:	'ТО250',
    43300:	'',
    43350:	'',
    43400:	'',
    43450:	'',
    43500:	'ТО500',
    43550:	'',
    43600:	'',
    43650:	'',
    43700:	'',
    43750:	'ТО250',
    43800:	'',
    43850:	'',
    43900:	'',
    43950:	'',
    44000:	'ТО4000',
    44050:	'',
    44100:	'',
    44150:	'',
    44200:	'',
    44250:	'ТО250',
    44300:	'',
    44350:	'',
    44400:	'',
    44450:	'',
    44500:	'ТО500',
    44550:	'',
    44600:	'',
    44650:	'',
    44700:	'',
    44750:	'ТО250',
    44800:	'',
    44850:	'',
    44900:	'',
    44950:	'',
    45000:	'ТО1000',
    45050:	'',
    45100:	'',
    45150:	'',
    45200:	'',
    45250:	'ТО250',
    45300:	'',
    45350:	'',
    45400:	'',
    45450:	'',
    45500:	'ТО500',
    45550:	'',
    45600:	'',
    45650:	'',
    45700:	'',
    45750:	'ТО250',
    45800:	'',
    45850:	'',
    45900:	'',
    45950:	'',
    46000:	'ТО2000',
    46050:	'',
    46100:	'',
    46150:	'',
    46200:	'',
    46250:	'ТО250',
    46300:	'',
    46350:	'',
    46400:	'',
    46450:	'',
    46500:	'ТО500',
    46550:	'',
    46600:	'',
    46650:	'',
    46700:	'',
    46750:	'ТО250',
    46800:	'',
    46850:	'',
    46900:	'',
    46950:	'',
    47000:	'ТО1000',
    47050:	'',
    47100:	'',
    47150:	'',
    47200:	'',
    47250:	'ТО250',
    47300:	'',
    47350:	'',
    47400:	'',
    47450:	'',
    47500:	'ТО500',
    47550:	'',
    47600:	'',
    47650:	'',
    47700:	'',
    47750:	'ТО250',
    47800:	'',
    47850:	'',
    47900:	'',
    47950:	'',
    48000:	'ТО4000'

}

In [46]:
to_dict_7555={
        50:	'',
        100:	'',
        150:	'',
        200:	'',
        250:	'ТО250',
        300:	'',
        350:	'',
        400:	'',
        450:	'',
        500:	'ТО500',
        550:	'',
        600:	'',
        650:	'',
        700:	'',
        750:	'ТО250',
        800:	'',
        850:	'',
        900:	'',
        950:	'',
        1000:	'ТО1000',
        1050:	'',
        1100:	'',
        1150:	'',
        1200:	'',
        1250:	'ТО250',
        1300:	'',
        1350:	'',
        1400:	'',
        1450:	'',
        1500:	'ТО1500',
        1550:	'',
        1600:	'',
        1650:	'',
        1700:	'',
        1750:	'ТО250',
        1800:	'',
        1850:	'',
        1900:	'',
        1950:	'',
        2000:	'ТО2000',
        2050:	'',
        2100:	'',
        2150:	'',
        2200:	'',
        2250:	'ТО250',
        2300:	'',
        2350:	'',
        2400:	'',
        2450:	'',
        2500:	'ТО500',
        2550:	'',
        2600:	'',
        2650:	'',
        2700:	'',
        2750:	'ТО250',
        2800:	'',
        2850:	'',
        2900:	'',
        2950:	'',
        3000:	'ТО3000',
        3050:	'',
        3100:	'',
        3150:	'',
        3200:	'',
        3250:	'ТО250',
        3300:	'',
        3350:	'',
        3400:	'',
        3450:	'',
        3500:	'ТО500',
        3550:	'',
        3600:	'',
        3650:	'',
        3700:	'',
        3750:	'ТО250',
        3800:	'',
        3850:	'',
        3900:	'',
        3950:	'',
        4000:	'ТО4000',
        4050:	'',
        4100:	'',
        4150:	'',
        4200:	'',
        4250:	'ТО250',
        4300:	'',
        4350:	'',
        4400:	'',
        4450:	'',
        4500:	'ТО1500',
        4550:	'',
        4600:	'',
        4650:	'',
        4700:	'',
        4750:	'ТО250',
        4800:	'',
        4850:	'',
        4900:	'',
        4950:	'',
        5000:	'ТО1000',
        5050:	'',
        5100:	'',
        5150:	'',
        5200:	'',
        5250:	'ТО250',
        5300:	'',
        5350:	'',
        5400:	'',
        5450:	'',
        5500:	'ТО500',
        5550:	'',
        5600:	'',
        5650:	'',
        5700:	'',
        5750:	'ТО250',
        5800:	'',
        5850:	'',
        5900:	'',
        5950:	'',
        6000:	'ТО6000',
        6050:	'',
        6100:	'',
        6150:	'',
        6200:	'',
        6250:	'ТО250',
        6300:	'',
        6350:	'',
        6400:	'',
        6450:	'',
        6500:	'ТО500',
        6550:	'',
        6600:	'',
        6650:	'',
        6700:	'',
        6750:	'ТО250',
        6800:	'',
        6850:	'',
        6900:	'',
        6950:	'',
        7000:	'ТО1000',
        7050:	'',
        7100:	'',
        7150:	'',
        7200:	'',
        7250:	'ТО250',
        7300:	'',
        7350:	'',
        7400:	'',
        7450:	'',
        7500:	'ТО1500',
        7550:	'',
        7600:	'',
        7650:	'',
        7700:	'',
        7750:	'ТО250',
        7800:	'',
        7850:	'',
        7900:	'',
        7950:	'',
        8000:	'ТО4000',
        8050:	'',
        8100:	'',
        8150:	'',
        8200:	'',
        8250:	'ТО250',
        8300:	'',
        8350:	'',
        8400:	'',
        8450:	'',
        8500:	'ТО500',
        8550:	'',
        8600:	'',
        8650:	'',
        8700:	'',
        8750:	'ТО250',
        8800:	'',
        8850:	'',
        8900:	'',
        8950:	'',
        9000:	'ТО3000',
        9050:	'',
        9100:	'',
        9150:	'',
        9200:	'',
        9250:	'ТО250',
        9300:	'',
        9350:	'',
        9400:	'',
        9450:	'',
        9500:	'ТО500',
        9550:	'',
        9600:	'',
        9650:	'',
        9700:	'',
        9750:	'ТО250',
        9800:	'',
        9850:	'',
        9900:	'',
        9950:	'',
        10000:	'ТО2000',
        10050:	'',
        10100:	'',
        10150:	'',
        10200:	'',
        10250:	'ТО250',
        10300:	'',
        10350:	'',
        10400:	'',
        10450:	'',
        10500:	'ТО1500',
        10550:	'',
        10600:	'',
        10650:	'',
        10700:	'',
        10750:	'ТО250',
        10800:	'',
        10850:	'',
        10900:	'',
        10950:	'',
        11000:	'ТО1000',
        11050:	'',
        11100:	'',
        11150:	'',
        11200:	'',
        11250:	'ТО250',
        11300:	'',
        11350:	'',
        11400:	'',
        11450:	'',
        11500:	'ТО500',
        11550:	'',
        11600:	'',
        11650:	'',
        11700:	'',
        11750:	'ТО250',
        11800:	'',
        11850:	'',
        11900:	'',
        11950:	'',
        12000:	'ТО4000/6000',
        12050:	'',
        12100:	'',
        12150:	'',
        12200:	'',
        12250:	'ТО250',
        12300:	'',
        12350:	'',
        12400:	'',
        12450:	'',
        12500:	'ТО500',
        12550:	'',
        12600:	'',
        12650:	'',
        12700:	'',
        12750:	'ТО250',
        12800:	'',
        12850:	'',
        12900:	'',
        12950:	'',
        13000:	'ТО1000',
        13050:	'',
        13100:	'',
        13150:	'',
        13200:	'',
        13250:	'ТО250',
        13300:	'',
        13350:	'',
        13400:	'',
        13450:	'',
        13500:	'ТО1500',
        13550:	'',
        13600:	'',
        13650:	'',
        13700:	'',
        13750:	'ТО250',
        13800:	'',
        13850:	'',
        13900:	'',
        13950:	'',
        14000:	'ТО2000',
        14050:	'',
        14100:	'',
        14150:	'',
        14200:	'',
        14250:	'ТО250',
        14300:	'',
        14350:	'',
        14400:	'',
        14450:	'',
        14500:	'ТО500',
        14550:	'',
        14600:	'',
        14650:	'',
        14700:	'',
        14750:	'ТО250',
        14800:	'',
        14850:	'',
        14900:	'',
        14950:	'',
        15000:	'ТО3000',
        15050:	'',
        15100:	'',
        15150:	'',
        15200:	'',
        15250:	'ТО250',
        15300:	'',
        15350:	'',
        15400:	'',
        15450:	'',
        15500:	'ТО500',
        15550:	'',
        15600:	'',
        15650:	'',
        15700:	'',
        15750:	'ТО250',
        15800:	'',
        15850:	'',
        15900:	'',
        15950:	'',
        16000:	'ТО4000',
        16050:	'',
        16100:	'',
        16150:	'',
        16200:	'',
        16250:	'ТО250',
        16300:	'',
        16350:	'',
        16400:	'',
        16450:	'',
        16500:	'ТО1500',
        16550:	'',
        16600:	'',
        16650:	'',
        16700:	'',
        16750:	'ТО250',
        16800:	'',
        16850:	'',
        16900:	'',
        16950:	'',
        17000:	'ТО1000',
        17050:	'',
        17100:	'',
        17150:	'',
        17200:	'',
        17250:	'ТО250',
        17300:	'',
        17350:	'',
        17400:	'',
        17450:	'',
        17500:	'ТО500',
        17550:	'',
        17600:	'',
        17650:	'',
        17700:	'',
        17750:	'ТО250',
        17800:	'',
        17850:	'',
        17900:	'',
        17950:	'',
        18000:	'ТО6000',
        18050:	'',
        18100:	'',
        18150:	'',
        18200:	'',
        18250:	'ТО250',
        18300:	'',
        18350:	'',
        18400:	'',
        18450:	'',
        18500:	'ТО500',
        18550:	'',
        18600:	'',
        18650:	'',
        18700:	'',
        18750:	'ТО250',
        18800:	'',
        18850:	'',
        18900:	'',
        18950:	'',
        19000:	'ТО1000',
        19050:	'',
        19100:	'',
        19150:	'',
        19200:	'',
        19250:	'ТО250',
        19300:	'',
        19350:	'',
        19400:	'',
        19450:	'',
        19500:	'ТО1500',
        19550:	'',
        19600:	'',
        19650:	'',
        19700:	'',
        19750:	'ТО250',
        19800:	'',
        19850:	'',
        19900:	'',
        19950:	'',
        20000:	'ТО4000',
        20050:	'',
        20100:	'',
        20150:	'',
        20200:	'',
        20250:	'ТО250',
        20300:	'',
        20350:	'',
        20400:	'',
        20450:	'',
        20500:	'ТО500',
        20550:	'',
        20600:	'',
        20650:	'',
        20700:	'',
        20750:	'ТО250',
        20800:	'',
        20850:	'',
        20900:	'',
        20950:	'',
        21000:	'ТО3000',
        21050:	'',
        21100:	'',
        21150:	'',
        21200:	'',
        21250:	'ТО250',
        21300:	'',
        21350:	'',
        21400:	'',
        21450:	'',
        21500:	'ТО500',
        21550:	'',
        21600:	'',
        21650:	'',
        21700:	'',
        21750:	'ТО250',
        21800:	'',
        21850:	'',
        21900:	'',
        21950:	'',
        22000:	'ТО2000',
        22050:	'',
        22100:	'',
        22150:	'',
        22200:	'',
        22250:	'ТО250',
        22300:	'',
        22350:	'',
        22400:	'',
        22450:	'',
        22500:	'ТО1500',
        22550:	'',
        22600:	'',
        22650:	'',
        22700:	'',
        22750:	'ТО250',
        22800:	'',
        22850:	'',
        22900:	'',
        22950:	'',
        23000:	'ТО1000',
        23050:	'',
        23100:	'',
        23150:	'',
        23200:	'',
        23250:	'ТО250',
        23300:	'',
        23350:	'',
        23400:	'',
        23450:	'',
        23500:	'ТО500',
        23550:	'',
        23600:	'',
        23650:	'',
        23700:	'',
        23750:	'ТО250',
        23800:	'',
        23850:	'',
        23900:	'',
        23950:	'',
        24000:	'ТО4000/6000',
        24050:	'',
        24100:	'',
        24150:	'',
        24200:	'',
        24250:	'ТО250',
        24300:	'',
        24350:	'',
        24400:	'',
        24450:	'',
        24500:	'ТО500',
        24550:	'',
        24600:	'',
        24650:	'',
        24700:	'',
        24750:	'ТО250',
        24800:	'',
        24850:	'',
        24900:	'',
        24950:	'',
        25000:	'ТО1000',
        25050:	'',
        25100:	'',
        25150:	'',
        25200:	'',
        25250:	'ТО250',
        25300:	'',
        25350:	'',
        25400:	'',
        25450:	'',
        25500:	'ТО1500',
        25550:	'',
        25600:	'',
        25650:	'',
        25700:	'',
        25750:	'ТО250',
        25800:	'',
        25850:	'',
        25900:	'',
        25950:	'',
        26000:	'ТО2000',
        26050:	'',
        26100:	'',
        26150:	'',
        26200:	'',
        26250:	'ТО250',
        26300:	'',
        26350:	'',
        26400:	'',
        26450:	'',
        26500:	'ТО500',
        26550:	'',
        26600:	'',
        26650:	'',
        26700:	'',
        26750:	'ТО250',
        26800:	'',
        26850:	'',
        26900:	'',
        26950:	'',
        27000:	'ТО3000',
        27050:	'',
        27100:	'',
        27150:	'',
        27200:	'',
        27250:	'ТО250',
        27300:	'',
        27350:	'',
        27400:	'',
        27450:	'',
        27500:	'ТО500',
        27550:	'',
        27600:	'',
        27650:	'',
        27700:	'',
        27750:	'ТО250',
        27800:	'',
        27850:	'',
        27900:	'',
        27950:	'',
        28000:	'ТО4000',
        28050:	'',
        28100:	'',
        28150:	'',
        28200:	'',
        28250:	'ТО250',
        28300:	'',
        28350:	'',
        28400:	'',
        28450:	'',
        28500:	'ТО1500',
        28550:	'',
        28600:	'',
        28650:	'',
        28700:	'',
        28750:	'ТО250',
        28800:	'',
        28850:	'',
        28900:	'',
        28950:	'',
        29000:	'ТО1000',
        29050:	'',
        29100:	'',
        29150:	'',
        29200:	'',
        29250:	'ТО250',
        29300:	'',
        29350:	'',
        29400:	'',
        29450:	'',
        29500:	'ТО500',
        29550:	'',
        29600:	'',
        29650:	'',
        29700:	'',
        29750:	'ТО250',
        29800:	'',
        29850:	'',
        29900:	'',
        29950:	'',
        30000:	'ТО6000',
        30050:	'',
        30100:	'',
        30150:	'',
        30200:	'',
        30250:	'ТО250',
        30300:	'',
        30350:	'',
        30400:	'',
        30450:	'',
        30500:	'ТО500',
        30550:	'',
        30600:	'',
        30650:	'',
        30700:	'',
        30750:	'ТО250',
        30800:	'',
        30850:	'',
        30900:	'',
        30950:	'',
        31000:	'ТО1000',
        31050:	'',
        31100:	'',
        31150:	'',
        31200:	'',
        31250:	'ТО250',
        31300:	'',
        31350:	'',
        31400:	'',
        31450:	'',
        31500:	'ТО1500',
        31550:	'',
        31600:	'',
        31650:	'',
        31700:	'',
        31750:	'ТО250',
        31800:	'',
        31850:	'',
        31900:	'',
        31950:	'',
        32000:	'ТО4000',
        32050:	'',
        32100:	'',
        32150:	'',
        32200:	'',
        32250:	'ТО250',
        32300:	'',
        32350:	'',
        32400:	'',
        32450:	'',
        32500:	'ТО500',
        32550:	'',
        32600:	'',
        32650:	'',
        32700:	'',
        32750:	'ТО250',
        32800:	'',
        32850:	'',
        32900:	'',
        32950:	'',
        33000:	'ТО3000',
        33050:	'',
        33100:	'',
        33150:	'',
        33200:	'',
        33250:	'ТО250',
        33300:	'',
        33350:	'',
        33400:	'',
        33450:	'',
        33500:	'ТО500',
        33550:	'',
        33600:	'',
        33650:	'',
        33700:	'',
        33750:	'ТО250',
        33800:	'',
        33850:	'',
        33900:	'',
        33950:	'',
        34000:	'ТО2000',
        34050:	'',
        34100:	'',
        34150:	'',
        34200:	'',
        34250:	'ТО250',
        34300:	'',
        34350:	'',
        34400:	'',
        34450:	'',
        34500:	'ТО1500',
        34550:	'',
        34600:	'',
        34650:	'',
        34700:	'',
        34750:	'ТО250',
        34800:	'',
        34850:	'',
        34900:	'',
        34950:	'',
        35000:	'ТО1000',
        35050:	'',
        35100:	'',
        35150:	'',
        35200:	'',
        35250:	'ТО250',
        35300:	'',
        35350:	'',
        35400:	'',
        35450:	'',
        35500:	'ТО500',
        35550:	'',
        35600:	'',
        35650:	'',
        35700:	'',
        35750:	'ТО250',
        35800:	'',
        35850:	'',
        35900:	'',
        35950:	'',
        36000:	'ТО4000/6000',
        36050:	'',
        36100:	'',
        36150:	'',
        36200:	'',
        36250:	'ТО250',
        36300:	'',
        36350:	'',
        36400:	'',
        36450:	'',
        36500:	'ТО500',
        36550:	'',
        36600:	'',
        36650:	'',
        36700:	'',
        36750:	'ТО250',
        36800:	'',
        36850:	'',
        36900:	'',
        36950:	'',
        37000:	'ТО1000',
        37050:	'',
        37100:	'',
        37150:	'',
        37200:	'',
        37250:	'ТО250',
        37300:	'',
        37350:	'',
        37400:	'',
        37450:	'',
        37500:	'ТО1500',
        37550:	'',
        37600:	'',
        37650:	'',
        37700:	'',
        37750:	'ТО250',
        37800:	'',
        37850:	'',
        37900:	'',
        37950:	'',
        38000:	'ТО2000',
        38050:	'',
        38100:	'',
        38150:	'',
        38200:	'',
        38250:	'ТО250',
        38300:	'',
        38350:	'',
        38400:	'',
        38450:	'',
        38500:	'ТО500',
        38550:	'',
        38600:	'',
        38650:	'',
        38700:	'',
        38750:	'ТО250',
        38800:	'',
        38850:	'',
        38900:	'',
        38950:	'',
        39000:	'ТО3000',
        39050:	'',
        39100:	'',
        39150:	'',
        39200:	'',
        39250:	'ТО250',
        39300:	'',
        39350:	'',
        39400:	'',
        39450:	'',
        39500:	'ТО500',
        39550:	'',
        39600:	'',
        39650:	'',
        39700:	'',
        39750:	'ТО250',
        39800:	'',
        39850:	'',
        39900:	'',
        39950:	'',
        40000:	'ТО4000',
        40050:	'',
        40100:	'',
        40150:	'',
        40200:	'',
        40250:	'ТО250',
        40300:	'',
        40350:	'',
        40400:	'',
        40450:	'',
        40500:	'ТО1500',
        40550:	'',
        40600:	'',
        40650:	'',
        40700:	'',
        40750:	'ТО250',
        40800:	'',
        40850:	'',
        40900:	'',
        40950:	'',
        41000:	'ТО1000',
        41050:	'',
        41100:	'',
        41150:	'',
        41200:	'',
        41250:	'ТО250',
        41300:	'',
        41350:	'',
        41400:	'',
        41450:	'',
        41500:	'ТО500',
        41550:	'',
        41600:	'',
        41650:	'',
        41700:	'',
        41750:	'ТО250',
        41800:	'',
        41850:	'',
        41900:	'',
        41950:	'',
        42000:	'ТО6000',
        42050:	'',
        42100:	'',
        42150:	'',
        42200:	'',
        42250:	'ТО250',
        42300:	'',
        42350:	'',
        42400:	'',
        42450:	'',
        42500:	'ТО500',
        42550:	'',
        42600:	'',
        42650:	'',
        42700:	'',
        42750:	'ТО250',
        42800:	'',
        42850:	'',
        42900:	'',
        42950:	'',
        43000:	'ТО1000',
        43050:	'',
        43100:	'',
        43150:	'',
        43200:	'',
        43250:	'ТО250',
        43300:	'',
        43350:	'',
        43400:	'',
        43450:	'',
        43500:	'ТО1500',
        43550:	'',
        43600:	'',
        43650:	'',
        43700:	'',
        43750:	'ТО250',
        43800:	'',
        43850:	'',
        43900:	'',
        43950:	'',
        44000:	'ТО4000',
        44050:	'',
        44100:	'',
        44150:	'',
        44200:	'',
        44250:	'ТО250',
        44300:	'',
        44350:	'',
        44400:	'',
        44450:	'',
        44500:	'ТО500',
        44550:	'',
        44600:	'',
        44650:	'',
        44700:	'',
        44750:	'ТО250',
        44800:	'',
        44850:	'',
        44900:	'',
        44950:	'',
        45000:	'ТО3000',
        45050:	'',
        45100:	'',
        45150:	'',
        45200:	'',
        45250:	'ТО250',
        45300:	'',
        45350:	'',
        45400:	'',
        45450:	'',
        45500:	'ТО500',
        45550:	'',
        45600:	'',
        45650:	'',
        45700:	'',
        45750:	'ТО250',
        45800:	'',
        45850:	'',
        45900:	'',
        45950:	'',
        46000:	'ТО2000',
        46050:	'',
        46100:	'',
        46150:	'',
        46200:	'',
        46250:	'ТО250',
        46300:	'',
        46350:	'',
        46400:	'',
        46450:	'',
        46500:	'ТО1500',
        46550:	'',
        46600:	'',
        46650:	'',
        46700:	'',
        46750:	'ТО250',
        46800:	'',
        46850:	'',
        46900:	'',
        46950:	'',
        47000:	'ТО1000',
        47050:	'',
        47100:	'',
        47150:	'',
        47200:	'',
        47250:	'ТО250',
        47300:	'',
        47350:	'',
        47400:	'',
        47450:	'',
        47500:	'ТО500',
        47550:	'',
        47600:	'',
        47650:	'',
        47700:	'',
        47750:	'ТО250',
        47800:	'',
        47850:	'',
        47900:	'',
        47950:	'',
        48000:	'ТО4000/6000'


}

In [47]:
to_dict_DM={
50:"ТО50",
100:"ТО50",
150:"ТО50",
200:"ТО50",
250:"ТО250",
300:"ТО50",
350:"ТО50",
400:"ТО50",
450:"ТО50",
500:"ТО500",
550:"ТО50",
600:"ТО50",
650:"ТО50",
700:"ТО50",
750:"ТО250",
800:"ТО50",
850:"ТО50",
900:"ТО50",
950:"ТО50",
1000:"ТО1000",
1050:"ТО50",
1100:"ТО50",
1150:"ТО50",
1200:"ТО50",
1250:"ТО250",
1300:"ТО50",
1350:"ТО50",
1400:"ТО50",
1450:"ТО50",
1500:"ТО500",
1550:"ТО50",
1600:"ТО50",
1650:"ТО50",
1700:"ТО50",
1750:"ТО250",
1800:"ТО50",
1850:"ТО50",
1900:"ТО50",
1950:"ТО50",
2000:"ТО2000",
2050:"ТО50",
2100:"ТО50",
2150:"ТО50",
2200:"ТО50",
2250:"ТО250",
2300:"ТО50",
2350:"ТО50",
2400:"ТО50",
2450:"ТО50",
2500:"ТО500",
2550:"ТО50",
2600:"ТО50",
2650:"ТО50",
2700:"ТО50",
2750:"ТО250",
2800:"ТО50",
2850:"ТО50",
2900:"ТО50",
2950:"ТО50",
3000:"ТО3000",
3050:"ТО50",
3100:"ТО50",
3150:"ТО50",
3200:"ТО50",
3250:"ТО250",
3300:"ТО50",
3350:"ТО50",
3400:"ТО50",
3450:"ТО50",
3500:"ТО500",
3550:"ТО50",
3600:"ТО50",
3650:"ТО50",
3700:"ТО50",
3750:"ТО250",
3800:"ТО50",
3850:"ТО50",
3900:"ТО50",
3950:"ТО50",
4000:"ТО2000",
4050:"ТО50",
4100:"ТО50",
4150:"ТО50",
4200:"ТО50",
4250:"ТО250",
4300:"ТО50",
4350:"ТО50",
4400:"ТО50",
4450:"ТО50",
4500:"ТО500",
4550:"ТО50",
4600:"ТО50",
4650:"ТО50",
4700:"ТО50",
4750:"ТО250",
4800:"ТО50",
4850:"ТО50",
4900:"ТО50",
4950:"ТО50",
5000:"ТО5000",
5050:"ТО50",
5100:"ТО50",
5150:"ТО50",
5200:"ТО50",
5250:"ТО250",
5300:"ТО50",
5350:"ТО50",
5400:"ТО50",
5450:"ТО50",
5500:"ТО500",
5550:"ТО50",
5600:"ТО50",
5650:"ТО50",
5700:"ТО50",
5750:"ТО250",
5800:"ТО50",
5850:"ТО50",
5900:"ТО50",
5950:"ТО50",
6000:"ТО6000",
6050:"ТО50",
6100:"ТО50",
6150:"ТО50",
6200:"ТО50",
6250:"ТО250",
6300:"ТО50",
6350:"ТО50",
6400:"ТО50",
6450:"ТО50",
6500:"ТО500",
6550:"ТО50",
6600:"ТО50",
6650:"ТО50",
6700:"ТО50",
6750:"ТО250",
6800:"ТО50",
6850:"ТО50",
6900:"ТО50",
6950:"ТО50",
7000:"ТО1000",
7050:"ТО50",
7100:"ТО50",
7150:"ТО50",
7200:"ТО50",
7250:"ТО250",
7300:"ТО50",
7350:"ТО50",
7400:"ТО50",
7450:"ТО50",
7500:"ТО500",
7550:"ТО50",
7600:"ТО50",
7650:"ТО50",
7700:"ТО50",
7750:"ТО250",
7800:"ТО50",
7850:"ТО50",
7900:"ТО50",
7950:"ТО50",
8000:"ТО2000",
8050:"ТО50",
8100:"ТО50",
8150:"ТО50",
8200:"ТО50",
8250:"ТО250",
8300:"ТО50",
8350:"ТО50",
8400:"ТО50",
8450:"ТО50",
8500:"ТО500",
8550:"ТО50",
8600:"ТО50",
8650:"ТО50",
8700:"ТО50",
8750:"ТО250",
8800:"ТО50",
8850:"ТО50",
8900:"ТО50",
8950:"ТО50",
9000:"ТО3000",
9050:"ТО50",
9100:"ТО50",
9150:"ТО50",
9200:"ТО50",
9250:"ТО250",
9300:"ТО50",
9350:"ТО50",
9400:"ТО50",
9450:"ТО50",
9500:"ТО500",
9550:"ТО50",
9600:"ТО50",
9650:"ТО50",
9700:"ТО50",
9750:"ТО250",
9800:"ТО50",
9850:"ТО50",
9900:"ТО50",
9950:"ТО50",
10000:"ТО5000",
10050:"ТО50",
10100:"ТО50",
10150:"ТО50",
10200:"ТО50",
10250:"ТО250",
10300:"ТО50",
10350:"ТО50",
10400:"ТО50",
10450:"ТО50",
10500:"ТО500",
10550:"ТО50",
10600:"ТО50",
10650:"ТО50",
10700:"ТО50",
10750:"ТО250",
10800:"ТО50",
10850:"ТО50",
10900:"ТО50",
10950:"ТО50",
11000:"ТО1000",
11050:"ТО50",
11100:"ТО50",
11150:"ТО50",
11200:"ТО50",
11250:"ТО250",
11300:"ТО50",
11350:"ТО50",
11400:"ТО50",
11450:"ТО50",
11500:"ТО500",
11550:"ТО50",
11600:"ТО50",
11650:"ТО50",
11700:"ТО50",
11750:"ТО250",
11800:"ТО50",
11850:"ТО50",
11900:"ТО50",
11950:"ТО50",
12000:"ТО6000",
12050:"ТО50",
12100:"ТО50",
12150:"ТО50",
12200:"ТО50",
12250:"ТО250",
12300:"ТО50",
12350:"ТО50",
12400:"ТО50",
12450:"ТО50",
12500:"ТО500",
12550:"ТО50",
12600:"ТО50",
12650:"ТО50",
12700:"ТО50",
12750:"ТО250",
12800:"ТО50",
12850:"ТО50",
12900:"ТО50",
12950:"ТО50",
13000:"ТО1000",
13050:"ТО50",
13100:"ТО50",
13150:"ТО50",
13200:"ТО50",
13250:"ТО250",
13300:"ТО50",
13350:"ТО50",
13400:"ТО50",
13450:"ТО50",
13500:"ТО500",
13550:"ТО50",
13600:"ТО50",
13650:"ТО50",
13700:"ТО50",
13750:"ТО250",
13800:"ТО50",
13850:"ТО50",
13900:"ТО50",
13950:"ТО50",
14000:"ТО2000",
14050:"ТО50",
14100:"ТО50",
14150:"ТО50",
14200:"ТО50",
14250:"ТО250",
14300:"ТО50",
14350:"ТО50",
14400:"ТО50",
14450:"ТО50",
14500:"ТО500",
14550:"ТО50",
14600:"ТО50",
14650:"ТО50",
14700:"ТО50",
14750:"ТО250",
14800:"ТО50",
14850:"ТО50",
14900:"ТО50",
14950:"ТО50",
15000:"ТО3000/5000",
15050:"ТО50",
15100:"ТО50",
15150:"ТО50",
15200:"ТО50",
15250:"ТО250",
15300:"ТО50",
15350:"ТО50",
15400:"ТО50",
15450:"ТО50",
15500:"ТО500",
15550:"ТО50",
15600:"ТО50",
15650:"ТО50",
15700:"ТО50",
15750:"ТО250",
15800:"ТО50",
15850:"ТО50",
15900:"ТО50",
15950:"ТО50",
16000:"ТО2000",
16050:"ТО50",
16100:"ТО50",
16150:"ТО50",
16200:"ТО50",
16250:"ТО250",
16300:"ТО50",
16350:"ТО50",
16400:"ТО50",
16450:"ТО50",
16500:"ТО500",
16550:"ТО50",
16600:"ТО50",
16650:"ТО50",
16700:"ТО50",
16750:"ТО250",
16800:"ТО50",
16850:"ТО50",
16900:"ТО50",
16950:"ТО50",
17000:"ТО1000",
17050:"ТО50",
17100:"ТО50",
17150:"ТО50",
17200:"ТО50",
17250:"ТО250",
17300:"ТО50",
17350:"ТО50",
17400:"ТО50",
17450:"ТО50",
17500:"ТО500",
17550:"ТО50",
17600:"ТО50",
17650:"ТО50",
17700:"ТО50",
17750:"ТО250",
17800:"ТО50",
17850:"ТО50",
17900:"ТО50",
17950:"ТО50",
18000:"ТО6000",
18050:"ТО50",
18100:"ТО50",
18150:"ТО50",
18200:"ТО50",
18250:"ТО250",
18300:"ТО50",
18350:"ТО50",
18400:"ТО50",
18450:"ТО50",
18500:"ТО500",
18550:"ТО50",
18600:"ТО50",
18650:"ТО50",
18700:"ТО50",
18750:"ТО250",
18800:"ТО50",
18850:"ТО50",
18900:"ТО50",
18950:"ТО50",
19000:"ТО1000",
19050:"ТО50",
19100:"ТО50",
19150:"ТО50",
19200:"ТО50",
19250:"ТО250",
19300:"ТО50",
19350:"ТО50",
19400:"ТО50",
19450:"ТО50",
19500:"ТО500",
19550:"ТО50",
19600:"ТО50",
19650:"ТО50",
19700:"ТО50",
19750:"ТО250",
19800:"ТО50",
19850:"ТО50",
19900:"ТО50",
19950:"ТО50",
20000:"ТО5000",
20050:"ТО50",
20100:"ТО50",
20150:"ТО50",
20200:"ТО50",
20250:"ТО250",
20300:"ТО50",
20350:"ТО50",
20400:"ТО50",
20450:"ТО50",
20500:"ТО500",
20550:"ТО50",
20600:"ТО50",
20650:"ТО50",
20700:"ТО50",
20750:"ТО250",
20800:"ТО50",
20850:"ТО50",
20900:"ТО50",
20950:"ТО50",
21000:"ТО3000",
21050:"ТО50",
21100:"ТО50",
21150:"ТО50",
21200:"ТО50",
21250:"ТО250",
21300:"ТО50",
21350:"ТО50",
21400:"ТО50",
21450:"ТО50",
21500:"ТО500",
21550:"ТО50",
21600:"ТО50",
21650:"ТО50",
21700:"ТО50",
21750:"ТО250",
21800:"ТО50",
21850:"ТО50",
21900:"ТО50",
21950:"ТО50",
22000:"ТО2000",
22050:"ТО50",
22100:"ТО50",
22150:"ТО50",
22200:"ТО50",
22250:"ТО250",
22300:"ТО50",
22350:"ТО50",
22400:"ТО50",
22450:"ТО50",
22500:"ТО500",
22550:"ТО50",
22600:"ТО50",
22650:"ТО50",
22700:"ТО50",
22750:"ТО250",
22800:"ТО50",
22850:"ТО50",
22900:"ТО50",
22950:"ТО50",
23000:"ТО1000",
23050:"ТО50",
23100:"ТО50",
23150:"ТО50",
23200:"ТО50",
23250:"ТО250",
23300:"ТО50",
23350:"ТО50",
23400:"ТО50",
23450:"ТО50",
23500:"ТО500",
23550:"ТО50",
23600:"ТО50",
23650:"ТО50",
23700:"ТО50",
23750:"ТО250",
23800:"ТО50",
23850:"ТО50",
23900:"ТО50",
23950:"ТО50",
24000:"ТО6000",
24050:"ТО50",
24100:"ТО50",
24150:"ТО50",
24200:"ТО50",
24250:"ТО250",
24300:"ТО50",
24350:"ТО50",
24400:"ТО50",
24450:"ТО50",
24500:"ТО500",
24550:"ТО50",
24600:"ТО50",
24650:"ТО50",
24700:"ТО50",
24750:"ТО250",
24800:"ТО50",
24850:"ТО50",
24900:"ТО50",
24950:"ТО50",
25000:"ТО5000",
25050:"ТО50",
25100:"ТО50",
25150:"ТО50",
25200:"ТО50",
25250:"ТО250",
25300:"ТО50",
25350:"ТО50",
25400:"ТО50",
25450:"ТО50",
25500:"ТО500",
25550:"ТО50",
25600:"ТО50",
25650:"ТО50",
25700:"ТО50",
25750:"ТО250",
25800:"ТО50",
25850:"ТО50",
25900:"ТО50",
25950:"ТО50",
26000:"ТО2000",
26050:"ТО50",
26100:"ТО50",
26150:"ТО50",
26200:"ТО50",
26250:"ТО250",
26300:"ТО50",
26350:"ТО50",
26400:"ТО50",
26450:"ТО50",
26500:"ТО500",
26550:"ТО50",
26600:"ТО50",
26650:"ТО50",
26700:"ТО50",
26750:"ТО250",
26800:"ТО50",
26850:"ТО50",
26900:"ТО50",
26950:"ТО50",
27000:"ТО3000",
27050:"ТО50",
27100:"ТО50",
27150:"ТО50",
27200:"ТО50",
27250:"ТО250",
27300:"ТО50",
27350:"ТО50",
27400:"ТО50",
27450:"ТО50",
27500:"ТО500",
27550:"ТО50",
27600:"ТО50",
27650:"ТО50",
27700:"ТО50",
27750:"ТО250",
27800:"ТО50",
27850:"ТО50",
27900:"ТО50",
27950:"ТО50",
28000:"ТО2000",
28050:"ТО50",
28100:"ТО50",
28150:"ТО50",
28200:"ТО50",
28250:"ТО250",
28300:"ТО50",
28350:"ТО50",
28400:"ТО50",
28450:"ТО50",
28500:"ТО500",
28550:"ТО50",
28600:"ТО50",
28650:"ТО50",
28700:"ТО50",
28750:"ТО250",
28800:"ТО50",
28850:"ТО50",
28900:"ТО50",
28950:"ТО50",
29000:"ТО1000",
29050:"ТО50",
29100:"ТО50",
29150:"ТО50",
29200:"ТО50",
29250:"ТО250",
29300:"ТО50",
29350:"ТО50",
29400:"ТО50",
29450:"ТО50",
29500:"ТО500",
29550:"ТО50",
29600:"ТО50",
29650:"ТО50",
29700:"ТО50",
29750:"ТО250",
29800:"ТО50",
29850:"ТО50",
29900:"ТО50",
29950:"ТО50",
30000:"ТО6000",
30050:"ТО50",
30100:"ТО50",
30150:"ТО50",
30200:"ТО50",
30250:"ТО250",
30300:"ТО50",
30350:"ТО50",
30400:"ТО50",
30450:"ТО50",
30500:"ТО500",
30550:"ТО50",
30600:"ТО50",
30650:"ТО50",
30700:"ТО50",
30750:"ТО250",
30800:"ТО50",
30850:"ТО50",
30900:"ТО50",
30950:"ТО50",
31000:"ТО1000",
31050:"ТО50",
31100:"ТО50",
31150:"ТО50",
31200:"ТО50",
31250:"ТО250",
31300:"ТО50",
31350:"ТО50",
31400:"ТО50",
31450:"ТО50",
31500:"ТО500",
31550:"ТО50",
31600:"ТО50",
31650:"ТО50",
31700:"ТО50",
31750:"ТО250",
31800:"ТО50",
31850:"ТО50",
31900:"ТО50",
31950:"ТО50",
32000:"ТО2000",
32050:"ТО50",
32100:"ТО50",
32150:"ТО50",
32200:"ТО50",
32250:"ТО250",
32300:"ТО50",
32350:"ТО50",
32400:"ТО50",
32450:"ТО50",
32500:"ТО500",
32550:"ТО50",
32600:"ТО50",
32650:"ТО50",
32700:"ТО50",
32750:"ТО250",
32800:"ТО50",
32850:"ТО50",
32900:"ТО50",
32950:"ТО50",
33000:"ТО3000",
33050:"ТО50",
33100:"ТО50",
33150:"ТО50",
33200:"ТО50",
33250:"ТО250",
33300:"ТО50",
33350:"ТО50",
33400:"ТО50",
33450:"ТО50",
33500:"ТО500",
33550:"ТО50",
33600:"ТО50",
33650:"ТО50",
33700:"ТО50",
33750:"ТО250",
33800:"ТО50",
33850:"ТО50",
33900:"ТО50",
33950:"ТО50",
34000:"ТО2000",
34050:"ТО50",
34100:"ТО50",
34150:"ТО50",
34200:"ТО50",
34250:"ТО250",
34300:"ТО50",
34350:"ТО50",
34400:"ТО50",
34450:"ТО50",
34500:"ТО500",
34550:"ТО50",
34600:"ТО50",
34650:"ТО50",
34700:"ТО50",
34750:"ТО250",
34800:"ТО50",
34850:"ТО50",
34900:"ТО50",
34950:"ТО50",
35000:"ТО5000",
35050:"ТО50",
35100:"ТО50",
35150:"ТО50",
35200:"ТО50",
35250:"ТО250",
35300:"ТО50",
35350:"ТО50",
35400:"ТО50",
35450:"ТО50",
35500:"ТО500",
35550:"ТО50",
35600:"ТО50",
35650:"ТО50",
35700:"ТО50",
35750:"ТО250",
35800:"ТО50",
35850:"ТО50",
35900:"ТО50",
35950:"ТО50",
36000:"ТО6000",
36050:"ТО50",
36100:"ТО50",
36150:"ТО50",
36200:"ТО50",
36250:"ТО250",
36300:"ТО50",
36350:"ТО50",
36400:"ТО50",
36450:"ТО50",
36500:"ТО500",
36550:"ТО50",
36600:"ТО50",
36650:"ТО50",
36700:"ТО50",
36750:"ТО250",
36800:"ТО50",
36850:"ТО50",
36900:"ТО50",
36950:"ТО50",
37000:"ТО1000",
37050:"ТО50",
37100:"ТО50",
37150:"ТО50",
37200:"ТО50",
37250:"ТО250",
37300:"ТО50",
37350:"ТО50",
37400:"ТО50",
37450:"ТО50",
37500:"ТО500",
37550:"ТО50",
37600:"ТО50",
37650:"ТО50",
37700:"ТО50",
37750:"ТО250",
37800:"ТО50",
37850:"ТО50",
37900:"ТО50",
37950:"ТО50",
38000:"ТО2000",
38050:"ТО50",
38100:"ТО50",
38150:"ТО50",
38200:"ТО50",
38250:"ТО250",
38300:"ТО50",
38350:"ТО50",
38400:"ТО50",
38450:"ТО50",
38500:"ТО500",
38550:"ТО50",
38600:"ТО50",
38650:"ТО50",
38700:"ТО50",
38750:"ТО250",
38800:"ТО50",
38850:"ТО50",
38900:"ТО50",
38950:"ТО50",
39000:"ТО3000",
39050:"ТО50",
39100:"ТО50",
39150:"ТО50",
39200:"ТО50",
39250:"ТО250",
39300:"ТО50",
39350:"ТО50",
39400:"ТО50",
39450:"ТО50",
39500:"ТО500",
39550:"ТО50",
39600:"ТО50",
39650:"ТО50",
39700:"ТО50",
39750:"ТО250",
39800:"ТО50",
39850:"ТО50",
39900:"ТО50",
39950:"ТО50",
40000:"ТО5000",
40050:"ТО50",
40100:"ТО50",
40150:"ТО50",
40200:"ТО50",
40250:"ТО250",
40300:"ТО50",
40350:"ТО50",
40400:"ТО50",
40450:"ТО50",
40500:"ТО500",
40550:"ТО50",
40600:"ТО50",
40650:"ТО50",
40700:"ТО50",
40750:"ТО250",
40800:"ТО50",
40850:"ТО50",
40900:"ТО50",
40950:"ТО50",
41000:"ТО1000",
41050:"ТО50",
41100:"ТО50",
41150:"ТО50",
41200:"ТО50",
41250:"ТО250",
41300:"ТО50",
41350:"ТО50",
41400:"ТО50",
41450:"ТО50",
41500:"ТО500",
41550:"ТО50",
41600:"ТО50",
41650:"ТО50",
41700:"ТО50",
41750:"ТО250",
41800:"ТО50",
41850:"ТО50",
41900:"ТО50",
41950:"ТО50",
42000:"ТО6000",
42050:"ТО50",
42100:"ТО50",
42150:"ТО50",
42200:"ТО50",
42250:"ТО250",
42300:"ТО50",
42350:"ТО50",
42400:"ТО50",
42450:"ТО50",
42500:"ТО500",
42550:"ТО50",
42600:"ТО50",
42650:"ТО50",
42700:"ТО50",
42750:"ТО250",
42800:"ТО50",
42850:"ТО50",
42900:"ТО50",
42950:"ТО50",
43000:"ТО1000",
43050:"ТО50",
43100:"ТО50",
43150:"ТО50",
43200:"ТО50",
43250:"ТО250",
43300:"ТО50",
43350:"ТО50",
43400:"ТО50",
43450:"ТО50",
43500:"ТО500",
43550:"ТО50",
43600:"ТО50",
43650:"ТО50",
43700:"ТО50",
43750:"ТО250",
43800:"ТО50",
43850:"ТО50",
43900:"ТО50",
43950:"ТО50",
44000:"ТО2000",
44050:"ТО50",
44100:"ТО50",
44150:"ТО50",
44200:"ТО50",
44250:"ТО250",
44300:"ТО50",
44350:"ТО50",
44400:"ТО50",
44450:"ТО50",
44500:"ТО500",
44550:"ТО50",
44600:"ТО50",
44650:"ТО50",
44700:"ТО50",
44750:"ТО250",
44800:"ТО50",
44850:"ТО50",
44900:"ТО50",
44950:"ТО50",
45000:"ТО3000/5000",
45050:"ТО50",
45100:"ТО50",
45150:"ТО50",
45200:"ТО50",
45250:"ТО250",
45300:"ТО50",
45350:"ТО50",
45400:"ТО50",
45450:"ТО50",
45500:"ТО500",
45550:"ТО50",
45600:"ТО50",
45650:"ТО50",
45700:"ТО50",
45750:"ТО250",
45800:"ТО50",
45850:"ТО50",
45900:"ТО50",
45950:"ТО50",
46000:"ТО2000",
46050:"ТО50",
46100:"ТО50",
46150:"ТО50",
46200:"ТО50",
46250:"ТО250",
46300:"ТО50",
46350:"ТО50",
46400:"ТО50",
46450:"ТО50",
46500:"ТО500",
46550:"ТО50",
46600:"ТО50",
46650:"ТО50",
46700:"ТО50",
46750:"ТО250",
46800:"ТО50",
46850:"ТО50",
46900:"ТО50",
46950:"ТО50",
47000:"ТО1000",
47050:"ТО50",
47100:"ТО50",
47150:"ТО50",
47200:"ТО50",
47250:"ТО250",
47300:"ТО50",
47350:"ТО50",
47400:"ТО50",
47450:"ТО50",
47500:"ТО500",
47550:"ТО50",
47600:"ТО50",
47650:"ТО50",
47700:"ТО50",
47750:"ТО250",
47800:"ТО50",
47850:"ТО50",
47900:"ТО50",
47950:"ТО50",
48000:"ТО6000"

}

In [48]:
to_dict_JD={
    50:	'ТО50',
100:	'ТО50',
150:	'ТО50',
200:	'ТО50',
250:	'ТО250',
300:	'ТО50',
350:	'ТО50',
400:	'ТО50',
450:	'ТО50',
500:	'ТО500',
550:	'ТО50',
600:	'ТО50',
650:	'ТО50',
700:	'ТО50',
750:	'ТО250',
800:	'ТО50',
850:	'ТО50',
900:	'ТО50',
950:	'ТО50',
1000:	'ТО1000',
1050:	'ТО50',
1100:	'ТО50',
1150:	'ТО50',
1200:	'ТО50',
1250:	'ТО250',
1300:	'ТО50',
1350:	'ТО50',
1400:	'ТО50',
1450:	'ТО50',
1500:	'ТО1500',
1550:	'ТО50',
1600:	'ТО50',
1650:	'ТО50',
1700:	'ТО50',
1750:	'ТО250',
1800:	'ТО50',
1850:	'ТО50',
1900:	'ТО50',
1950:	'ТО50',
2000:	'ТО2000',
2050:	'ТО50',
2100:	'ТО50',
2150:	'ТО50',
2200:	'ТО50',
2250:	'ТО250',
2300:	'ТО50',
2350:	'ТО50',
2400:	'ТО50',
2450:	'ТО50',
2500:	'ТО500',
2550:	'ТО50',
2600:	'ТО50',
2650:	'ТО50',
2700:	'ТО50',
2750:	'ТО250',
2800:	'ТО50',
2850:	'ТО50',
2900:	'ТО50',
2950:	'ТО50',
3000:	'ТО3000',
3050:	'ТО50',
3100:	'ТО50',
3150:	'ТО50',
3200:	'ТО50',
3250:	'ТО250',
3300:	'ТО50',
3350:	'ТО50',
3400:	'ТО50',
3450:	'ТО50',
3500:	'ТО500',
3550:	'ТО50',
3600:	'ТО50',
3650:	'ТО50',
3700:	'ТО50',
3750:	'ТО250',
3800:	'ТО50',
3850:	'ТО50',
3900:	'ТО50',
3950:	'ТО50',
4000:	'ТО2000',
4050:	'ТО50',
4100:	'ТО50',
4150:	'ТО50',
4200:	'ТО50',
4250:	'ТО250',
4300:	'ТО50',
4350:	'ТО50',
4400:	'ТО50',
4450:	'ТО50',
4500:	'ТО1500',
4550:	'ТО50',
4600:	'ТО50',
4650:	'ТО50',
4700:	'ТО50',
4750:	'ТО250',
4800:	'ТО50',
4850:	'ТО50',
4900:	'ТО50',
4950:	'ТО50',
5000:	'ТО1000',
5050:	'ТО50',
5100:	'ТО50',
5150:	'ТО50',
5200:	'ТО50',
5250:	'ТО250',
5300:	'ТО50',
5350:	'ТО50',
5400:	'ТО50',
5450:	'ТО50',
5500:	'ТО500',
5550:	'ТО50',
5600:	'ТО50',
5650:	'ТО50',
5700:	'ТО50',
5750:	'ТО250',
5800:	'ТО50',
5850:	'ТО50',
5900:	'ТО50',
5950:	'ТО50',
6000:	'ТО2000/3000',
6050:	'ТО50',
6100:	'ТО50',
6150:	'ТО50',
6200:	'ТО50',
6250:	'ТО250',
6300:	'ТО50',
6350:	'ТО50',
6400:	'ТО50',
6450:	'ТО50',
6500:	'ТО500',
6550:	'ТО50',
6600:	'ТО50',
6650:	'ТО50',
6700:	'ТО50',
6750:	'ТО250',
6800:	'ТО50',
6850:	'ТО50',
6900:	'ТО50',
6950:	'ТО50',
7000:	'ТО1000',
7050:	'ТО50',
7100:	'ТО50',
7150:	'ТО50',
7200:	'ТО50',
7250:	'ТО250',
7300:	'ТО50',
7350:	'ТО50',
7400:	'ТО50',
7450:	'ТО50',
7500:	'ТО1500',
7550:	'ТО50',
7600:	'ТО50',
7650:	'ТО50',
7700:	'ТО50',
7750:	'ТО250',
7800:	'ТО50',
7850:	'ТО50',
7900:	'ТО50',
7950:	'ТО50',
8000:	'ТО2000',
8050:	'ТО50',
8100:	'ТО50',
8150:	'ТО50',
8200:	'ТО50',
8250:	'ТО250',
8300:	'ТО50',
8350:	'ТО50',
8400:	'ТО50',
8450:	'ТО50',
8500:	'ТО500',
8550:	'ТО50',
8600:	'ТО50',
8650:	'ТО50',
8700:	'ТО50',
8750:	'ТО250',
8800:	'ТО50',
8850:	'ТО50',
8900:	'ТО50',
8950:	'ТО50',
9000:	'ТО3000',
9050:	'ТО50',
9100:	'ТО50',
9150:	'ТО50',
9200:	'ТО50',
9250:	'ТО250',
9300:	'ТО50',
9350:	'ТО50',
9400:	'ТО50',
9450:	'ТО50',
9500:	'ТО500',
9550:	'ТО50',
9600:	'ТО50',
9650:	'ТО50',
9700:	'ТО50',
9750:	'ТО250',
9800:	'ТО50',
9850:	'ТО50',
9900:	'ТО50',
9950:	'ТО50',
10000:	'ТО2000',
10050:	'ТО50',
10100:	'ТО50',
10150:	'ТО50',
10200:	'ТО50',
10250:	'ТО250',
10300:	'ТО50',
10350:	'ТО50',
10400:	'ТО50',
10450:	'ТО50',
10500:	'ТО1500',
10550:	'ТО50',
10600:	'ТО50',
10650:	'ТО50',
10700:	'ТО50',
10750:	'ТО250',
10800:	'ТО50',
10850:	'ТО50',
10900:	'ТО50',
10950:	'ТО50',
11000:	'ТО1000',
11050:	'ТО50',
11100:	'ТО50',
11150:	'ТО50',
11200:	'ТО50',
11250:	'ТО250',
11300:	'ТО50',
11350:	'ТО50',
11400:	'ТО50',
11450:	'ТО50',
11500:	'ТО500',
11550:	'ТО50',
11600:	'ТО50',
11650:	'ТО50',
11700:	'ТО50',
11750:	'ТО250',
11800:	'ТО50',
11850:	'ТО50',
11900:	'ТО50',
11950:	'ТО50',
12000:	'ТО2000/3000',
12050:	'ТО50',
12100:	'ТО50',
12150:	'ТО50',
12200:	'ТО50',
12250:	'ТО250',
12300:	'ТО50',
12350:	'ТО50',
12400:	'ТО50',
12450:	'ТО50',
12500:	'ТО500',
12550:	'ТО50',
12600:	'ТО50',
12650:	'ТО50',
12700:	'ТО50',
12750:	'ТО250',
12800:	'ТО50',
12850:	'ТО50',
12900:	'ТО50',
12950:	'ТО50',
13000:	'ТО1000',
13050:	'ТО50',
13100:	'ТО50',
13150:	'ТО50',
13200:	'ТО50',
13250:	'ТО250',
13300:	'ТО50',
13350:	'ТО50',
13400:	'ТО50',
13450:	'ТО50',
13500:	'ТО1500',
13550:	'ТО50',
13600:	'ТО50',
13650:	'ТО50',
13700:	'ТО50',
13750:	'ТО250',
13800:	'ТО50',
13850:	'ТО50',
13900:	'ТО50',
13950:	'ТО50',
14000:	'ТО2000',
14050:	'ТО50',
14100:	'ТО50',
14150:	'ТО50',
14200:	'ТО50',
14250:	'ТО250',
14300:	'ТО50',
14350:	'ТО50',
14400:	'ТО50',
14450:	'ТО50',
14500:	'ТО500',
14550:	'ТО50',
14600:	'ТО50',
14650:	'ТО50',
14700:	'ТО50',
14750:	'ТО250',
14800:	'ТО50',
14850:	'ТО50',
14900:	'ТО50',
14950:	'ТО50',
15000:	'ТО3000',
15050:	'ТО50',
15100:	'ТО50',
15150:	'ТО50',
15200:	'ТО50',
15250:	'ТО250',
15300:	'ТО50',
15350:	'ТО50',
15400:	'ТО50',
15450:	'ТО50',
15500:	'ТО500',
15550:	'ТО50',
15600:	'ТО50',
15650:	'ТО50',
15700:	'ТО50',
15750:	'ТО250',
15800:	'ТО50',
15850:	'ТО50',
15900:	'ТО50',
15950:	'ТО50',
16000:	'ТО2000',
16050:	'ТО50',
16100:	'ТО50',
16150:	'ТО50',
16200:	'ТО50',
16250:	'ТО250',
16300:	'ТО50',
16350:	'ТО50',
16400:	'ТО50',
16450:	'ТО50',
16500:	'ТО1500',
16550:	'ТО50',
16600:	'ТО50',
16650:	'ТО50',
16700:	'ТО50',
16750:	'ТО250',
16800:	'ТО50',
16850:	'ТО50',
16900:	'ТО50',
16950:	'ТО50',
17000:	'ТО1000',
17050:	'ТО50',
17100:	'ТО50',
17150:	'ТО50',
17200:	'ТО50',
17250:	'ТО250',
17300:	'ТО50',
17350:	'ТО50',
17400:	'ТО50',
17450:	'ТО50',
17500:	'ТО500',
17550:	'ТО50',
17600:	'ТО50',
17650:	'ТО50',
17700:	'ТО50',
17750:	'ТО250',
17800:	'ТО50',
17850:	'ТО50',
17900:	'ТО50',
17950:	'ТО50',
18000:	'ТО2000/3000',
18050:	'ТО50',
18100:	'ТО50',
18150:	'ТО50',
18200:	'ТО50',
18250:	'ТО250',
18300:	'ТО50',
18350:	'ТО50',
18400:	'ТО50',
18450:	'ТО50',
18500:	'ТО500',
18550:	'ТО50',
18600:	'ТО50',
18650:	'ТО50',
18700:	'ТО50',
18750:	'ТО250',
18800:	'ТО50',
18850:	'ТО50',
18900:	'ТО50',
18950:	'ТО50',
19000:	'ТО1000',
19050:	'ТО50',
19100:	'ТО50',
19150:	'ТО50',
19200:	'ТО50',
19250:	'ТО250',
19300:	'ТО50',
19350:	'ТО50',
19400:	'ТО50',
19450:	'ТО50',
19500:	'ТО1500',
19550:	'ТО50',
19600:	'ТО50',
19650:	'ТО50',
19700:	'ТО50',
19750:	'ТО250',
19800:	'ТО50',
19850:	'ТО50',
19900:	'ТО50',
19950:	'ТО50',
20000:	'ТО2000',
20050:	'ТО50',
20100:	'ТО50',
20150:	'ТО50',
20200:	'ТО50',
20250:	'ТО250',
20300:	'ТО50',
20350:	'ТО50',
20400:	'ТО50',
20450:	'ТО50',
20500:	'ТО500',
20550:	'ТО50',
20600:	'ТО50',
20650:	'ТО50',
20700:	'ТО50',
20750:	'ТО250',
20800:	'ТО50',
20850:	'ТО50',
20900:	'ТО50',
20950:	'ТО50',
21000:	'ТО3000',
21050:	'ТО50',
21100:	'ТО50',
21150:	'ТО50',
21200:	'ТО50',
21250:	'ТО250',
21300:	'ТО50',
21350:	'ТО50',
21400:	'ТО50',
21450:	'ТО50',
21500:	'ТО500',
21550:	'ТО50',
21600:	'ТО50',
21650:	'ТО50',
21700:	'ТО50',
21750:	'ТО250',
21800:	'ТО50',
21850:	'ТО50',
21900:	'ТО50',
21950:	'ТО50',
22000:	'ТО2000',
22050:	'ТО50',
22100:	'ТО50',
22150:	'ТО50',
22200:	'ТО50',
22250:	'ТО250',
22300:	'ТО50',
22350:	'ТО50',
22400:	'ТО50',
22450:	'ТО50',
22500:	'ТО1500',
22550:	'ТО50',
22600:	'ТО50',
22650:	'ТО50',
22700:	'ТО50',
22750:	'ТО250',
22800:	'ТО50',
22850:	'ТО50',
22900:	'ТО50',
22950:	'ТО50',
23000:	'ТО1000',
23050:	'ТО50',
23100:	'ТО50',
23150:	'ТО50',
23200:	'ТО50',
23250:	'ТО250',
23300:	'ТО50',
23350:	'ТО50',
23400:	'ТО50',
23450:	'ТО50',
23500:	'ТО500',
23550:	'ТО50',
23600:	'ТО50',
23650:	'ТО50',
23700:	'ТО50',
23750:	'ТО250',
23800:	'ТО50',
23850:	'ТО50',
23900:	'ТО50',
23950:	'ТО50',
24000:	'ТО2000/3000',
24050:	'ТО50',
24100:	'ТО50',
24150:	'ТО50',
24200:	'ТО50',
24250:	'ТО250',
24300:	'ТО50',
24350:	'ТО50',
24400:	'ТО50',
24450:	'ТО50',
24500:	'ТО500',
24550:	'ТО50',
24600:	'ТО50',
24650:	'ТО50',
24700:	'ТО50',
24750:	'ТО250',
24800:	'ТО50',
24850:	'ТО50',
24900:	'ТО50',
24950:	'ТО50',
25000:	'ТО500',
25050:	'ТО50',
25100:	'ТО50',
25150:	'ТО50',
25200:	'ТО50',
25250:	'ТО50',
25300:	'ТО50',
25350:	'ТО50',
25400:	'ТО50',
25450:	'ТО50',
25500:	'ТО1500',
25550:	'ТО50',
25600:	'ТО50',
25650:	'ТО50',
25700:	'ТО50',
25750:	'ТО250',
25800:	'ТО50',
25850:	'ТО50',
25900:	'ТО50',
25950:	'ТО50',
26000:	'ТО2000',
26050:	'ТО50',
26100:	'ТО50',
26150:	'ТО50',
26200:	'ТО50',
26250:	'ТО250',
26300:	'ТО50',
26350:	'ТО50',
26400:	'ТО50',
26450:	'ТО50',
26500:	'ТО500',
26550:	'ТО50',
26600:	'ТО50',
26650:	'ТО50',
26700:	'ТО50',
26750:	'ТО250',
26800:	'ТО50',
26850:	'ТО50',
26900:	'ТО50',
26950:	'ТО50',
27000:	'ТО3000',
27050:	'ТО50',
27100:	'ТО50',
27150:	'ТО50',
27200:	'ТО50',
27250:	'ТО250',
27300:	'ТО50',
27350:	'ТО50',
27400:	'ТО50',
27450:	'ТО50',
27500:	'ТО500',
27550:	'ТО50',
27600:	'ТО50',
27650:	'ТО50',
27700:	'ТО50',
27750:	'ТО250',
27800:	'ТО50',
27850:	'ТО50',
27900:	'ТО50',
27950:	'ТО50',
28000:	'ТО2000',
28050:	'ТО50',
28100:	'ТО50',
28150:	'ТО50',
28200:	'ТО50',
28250:	'ТО250',
28300:	'ТО50',
28350:	'ТО50',
28400:	'ТО50',
28450:	'ТО50',
28500:	'ТО1500',
28550:	'ТО50',
28600:	'ТО50',
28650:	'ТО50',
28700:	'ТО50',
28750:	'ТО250',
28800:	'ТО50',
28850:	'ТО50',
28900:	'ТО50',
28950:	'ТО50',
29000:	'ТО1000',
29050:	'ТО50',
29100:	'ТО50',
29150:	'ТО50',
29200:	'ТО50',
29250:	'ТО250',
29300:	'ТО50',
29350:	'ТО50',
29400:	'ТО50',
29450:	'ТО50',
29500:	'ТО500',
29550:	'ТО50',
29600:	'ТО50',
29650:	'ТО50',
29700:	'ТО50',
29750:	'ТО250',
29800:	'ТО50',
29850:	'ТО50',
29900:	'ТО50',
29950:	'ТО50',
30000:	'ТО2000/3000',
30050:	'ТО50',
30100:	'ТО50',
30150:	'ТО50',
30200:	'ТО50',
30250:	'ТО250',
30300:	'ТО50',
30350:	'ТО50',
30400:	'ТО50',
30450:	'ТО50',
30500:	'ТО500',
30550:	'ТО50',
30600:	'ТО50',
30650:	'ТО50',
30700:	'ТО50',
30750:	'ТО250',
30800:	'ТО50',
30850:	'ТО50',
30900:	'ТО50',
30950:	'ТО50',
31000:	'ТО1000',
31050:	'ТО50',
31100:	'ТО50',
31150:	'ТО50',
31200:	'ТО50',
31250:	'ТО250',
31300:	'ТО50',
31350:	'ТО50',
31400:	'ТО50',
31450:	'ТО50',
31500:	'ТО1500',
31550:	'ТО50',
31600:	'ТО50',
31650:	'ТО50',
31700:	'ТО50',
31750:	'ТО250',
31800:	'ТО50',
31850:	'ТО50',
31900:	'ТО50',
31950:	'ТО50',
32000:	'ТО2000',
32050:	'ТО50',
32100:	'ТО50',
32150:	'ТО50',
32200:	'ТО50',
32250:	'ТО250',
32300:	'ТО50',
32350:	'ТО50',
32400:	'ТО50',
32450:	'ТО50',
32500:	'ТО500',
32550:	'ТО50',
32600:	'ТО50',
32650:	'ТО50',
32700:	'ТО50',
32750:	'ТО250',
32800:	'ТО50',
32850:	'ТО50',
32900:	'ТО50',
32950:	'ТО50',
33000:	'ТО3000',
33050:	'ТО50',
33100:	'ТО50',
33150:	'ТО50',
33200:	'ТО50',
33250:	'ТО250',
33300:	'ТО50',
33350:	'ТО50',
33400:	'ТО50',
33450:	'ТО50',
33500:	'ТО500',
33550:	'ТО50',
33600:	'ТО50',
33650:	'ТО50',
33700:	'ТО50',
33750:	'ТО250',
33800:	'ТО50',
33850:	'ТО50',
33900:	'ТО50',
33950:	'ТО50',
34000:	'ТО2000',
34050:	'ТО50',
34100:	'ТО50',
34150:	'ТО50',
34200:	'ТО50',
34250:	'ТО250',
34300:	'ТО50',
34350:	'ТО50',
34400:	'ТО50',
34450:	'ТО50',
34500:	'ТО1500',
34550:	'ТО50',
34600:	'ТО50',
34650:	'ТО50',
34700:	'ТО50',
34750:	'ТО250',
34800:	'ТО50',
34850:	'ТО50',
34900:	'ТО50',
34950:	'ТО50',
35000:	'ТО1000',
35050:	'ТО50',
35100:	'ТО50',
35150:	'ТО50',
35200:	'ТО50',
35250:	'ТО250',
35300:	'ТО50',
35350:	'ТО50',
35400:	'ТО50',
35450:	'ТО50',
35500:	'ТО500',
35550:	'ТО50',
35600:	'ТО50',
35650:	'ТО50',
35700:	'ТО50',
35750:	'ТО250',
35800:	'ТО50',
35850:	'ТО50',
35900:	'ТО50',
35950:	'ТО50',
36000:	'ТО2000/3000',
36050:	'ТО50',
36100:	'ТО50',
36150:	'ТО50',
36200:	'ТО50',
36250:	'ТО250',
36300:	'ТО50',
36350:	'ТО50',
36400:	'ТО50',
36450:	'ТО50',
36500:	'ТО500',
36550:	'ТО50',
36600:	'ТО50',
36650:	'ТО50',
36700:	'ТО50',
36750:	'ТО250',
36800:	'ТО50',
36850:	'ТО50',
36900:	'ТО50',
36950:	'ТО50',
37000:	'ТО1000',
37050:	'ТО50',
37100:	'ТО50',
37150:	'ТО50',
37200:	'ТО50',
37250:	'ТО250',
37300:	'ТО50',
37350:	'ТО50',
37400:	'ТО50',
37450:	'ТО50',
37500:	'ТО1500',
37550:	'ТО50',
37600:	'ТО50',
37650:	'ТО50',
37700:	'ТО50',
37750:	'ТО250',
37800:	'ТО50',
37850:	'ТО50',
37900:	'ТО50',
37950:	'ТО50',
38000:	'ТО2000',
38050:	'ТО50',
38100:	'ТО50',
38150:	'ТО50',
38200:	'ТО50',
38250:	'ТО250',
38300:	'ТО50',
38350:	'ТО50',
38400:	'ТО50',
38450:	'ТО50',
38500:	'ТО500',
38550:	'ТО50',
38600:	'ТО50',
38650:	'ТО50',
38700:	'ТО50',
38750:	'ТО250',
38800:	'ТО50',
38850:	'ТО50',
38900:	'ТО50',
38950:	'ТО50',
39000:	'ТО3000',
39050:	'ТО50',
39100:	'ТО50',
39150:	'ТО50',
39200:	'ТО50',
39250:	'ТО250',
39300:	'ТО50',
39350:	'ТО50',
39400:	'ТО50',
39450:	'ТО50',
39500:	'ТО500',
39550:	'ТО50',
39600:	'ТО50',
39650:	'ТО50',
39700:	'ТО50',
39750:	'ТО250',
39800:	'ТО50',
39850:	'ТО50',
39900:	'ТО50',
39950:	'ТО50',
40000:	'ТО2000',
40050:	'ТО50',
40100:	'ТО50',
40150:	'ТО50',
40200:	'ТО50',
40250:	'ТО250',
40300:	'ТО50',
40350:	'ТО50',
40400:	'ТО50',
40450:	'ТО50',
40500:	'ТО1500',
40550:	'ТО50',
40600:	'ТО50',
40650:	'ТО50',
40700:	'ТО50',
40750:	'ТО250',
40800:	'ТО50',
40850:	'ТО50',
40900:	'ТО50',
40950:	'ТО50',
41000:	'ТО1000',
41050:	'ТО50',
41100:	'ТО50',
41150:	'ТО50',
41200:	'ТО50',
41250:	'ТО250',
41300:	'ТО50',
41350:	'ТО50',
41400:	'ТО50',
41450:	'ТО50',
41500:	'ТО500',
41550:	'ТО50',
41600:	'ТО50',
41650:	'ТО50',
41700:	'ТО50',
41750:	'ТО250',
41800:	'ТО50',
41850:	'ТО50',
41900:	'ТО50',
41950:	'ТО50',
42000:	'ТО2000/3000',
42050:	'ТО50',
42100:	'ТО50',
42150:	'ТО50',
42200:	'ТО50',
42250:	'ТО250',
42300:	'ТО50',
42350:	'ТО50',
42400:	'ТО50',
42450:	'ТО50',
42500:	'ТО500',
42550:	'ТО50',
42600:	'ТО50',
42650:	'ТО50',
42700:	'ТО50',
42750:	'ТО250',
42800:	'ТО50',
42850:	'ТО50',
42900:	'ТО50',
42950:	'ТО50',
43000:	'ТО1000',
43050:	'ТО50',
43100:	'ТО50',
43150:	'ТО50',
43200:	'ТО50',
43250:	'ТО250',
43300:	'ТО50',
43350:	'ТО50',
43400:	'ТО50',
43450:	'ТО50',
43500:	'ТО1500',
43550:	'ТО50',
43600:	'ТО50',
43650:	'ТО50',
43700:	'ТО50',
43750:	'ТО250',
43800:	'ТО50',
43850:	'ТО50',
43900:	'ТО50',
43950:	'ТО50',
44000:	'ТО2000',
44050:	'ТО50',
44100:	'ТО50',
44150:	'ТО50',
44200:	'ТО50',
44250:	'ТО250',
44300:	'ТО50',
44350:	'ТО50',
44400:	'ТО50',
44450:	'ТО50',
44500:	'ТО500',
44550:	'ТО50',
44600:	'ТО50',
44650:	'ТО50',
44700:	'ТО50',
44750:	'ТО250',
44800:	'ТО50',
44850:	'ТО50',
44900:	'ТО50',
44950:	'ТО50',
45000:	'ТО3000',
45050:	'ТО50',
45100:	'ТО50',
45150:	'ТО50',
45200:	'ТО50',
45250:	'ТО250',
45300:	'ТО50',
45350:	'ТО50',
45400:	'ТО50',
45450:	'ТО50',
45500:	'ТО500',
45550:	'ТО50',
45600:	'ТО50',
45650:	'ТО50',
45700:	'ТО50',
45750:	'ТО250',
45800:	'ТО50',
45850:	'ТО50',
45900:	'ТО50',
45950:	'ТО50',
46000:	'ТО2000',
46050:	'ТО50',
46100:	'ТО50',
46150:	'ТО50',
46200:	'ТО50',
46250:	'ТО250',
46300:	'ТО50',
46350:	'ТО50',
46400:	'ТО50',
46450:	'ТО50',
46500:	'ТО1500',
46550:	'ТО50',
46600:	'ТО50',
46650:	'ТО50',
46700:	'ТО50',
46750:	'ТО250',
46800:	'ТО50',
46850:	'ТО50',
46900:	'ТО50',
46950:	'ТО50',
47000:	'ТО1000',
47050:	'ТО50',
47100:	'ТО50',
47150:	'ТО50',
47200:	'ТО50',
47250:	'ТО250',
47300:	'ТО50',
47350:	'ТО50',
47400:	'ТО50',
47450:	'ТО50',
47500:	'ТО500',
47550:	'ТО50',
47600:	'ТО50',
47650:	'ТО50',
47700:	'ТО50',
47750:	'ТО250',
47800:	'ТО50',
47850:	'ТО50',
47900:	'ТО50',
47950:	'ТО50',
48000:	'ТО2000/3000'

}

In [49]:
to_dict_WA470={
50:	'ТО50',
100:	'ТО100',
150:	'ТО50',
200:	'ТО100',
250:	'ТО250',
300:	'ТО100',
350:	'ТО50',
400:	'ТО100',
450:	'ТО50',
500:	'ТО500',
550:	'ТО50',
600:	'ТО100',
650:	'ТО50',
700:	'ТО100',
750:	'ТО250',
800:	'ТО100',
850:	'ТО50',
900:	'ТО100',
950:	'ТО50',
1000:	'ТО1000',
1050:	'ТО50',
1100:	'ТО100',
1150:	'ТО50',
1200:	'ТО100',
1250:	'ТО250',
1300:	'ТО100',
1350:	'ТО50',
1400:	'ТО100',
1450:	'ТО50',
1500:	'ТО500',
1550:	'ТО50',
1600:	'ТО100',
1650:	'ТО50',
1700:	'ТО100',
1750:	'ТО250',
1800:	'ТО100',
1850:	'ТО50',
1900:	'ТО100',
1950:	'ТО50',
2000:	'ТО2000',
2050:	'ТО50',
2100:	'ТО100',
2150:	'ТО50',
2200:	'ТО100',
2250:	'ТО250',
2300:	'ТО100',
2350:	'ТО50',
2400:	'ТО100',
2450:	'ТО50',
2500:	'ТО500',
2550:	'ТО50',
2600:	'ТО100',
2650:	'ТО50',
2700:	'ТО100',
2750:	'ТО250',
2800:	'ТО100',
2850:	'ТО50',
2900:	'ТО100',
2950:	'ТО50',
3000:	'ТО1000',
3050:	'ТО50',
3100:	'ТО100',
3150:	'ТО50',
3200:	'ТО100',
3250:	'ТО250',
3300:	'ТО100',
3350:	'ТО50',
3400:	'ТО100',
3450:	'ТО50',
3500:	'ТО500',
3550:	'ТО50',
3600:	'ТО100',
3650:	'ТО50',
3700:	'ТО100',
3750:	'ТО250',
3800:	'ТО100',
3850:	'ТО50',
3900:	'ТО100',
3950:	'ТО50',
4000:	'ТО4000',
4050:	'ТО50',
4100:	'ТО100',
4150:	'ТО50',
4200:	'ТО100',
4250:	'ТО250',
4300:	'ТО100',
4350:	'ТО50',
4400:	'ТО100',
4450:	'ТО50',
4500:	'ТО500',
4550:	'ТО50',
4600:	'ТО100',
4650:	'ТО50',
4700:	'ТО100',
4750:	'ТО250',
4800:	'ТО100',
4850:	'ТО50',
4900:	'ТО100',
4950:	'ТО50',
5000:	'ТО1000',
5050:	'ТО50',
5100:	'ТО100',
5150:	'ТО50',
5200:	'ТО100',
5250:	'ТО250',
5300:	'ТО100',
5350:	'ТО50',
5400:	'ТО100',
5450:	'ТО50',
5500:	'ТО500',
5550:	'ТО50',
5600:	'ТО100',
5650:	'ТО50',
5700:	'ТО100',
5750:	'ТО250',
5800:	'ТО100',
5850:	'ТО50',
5900:	'ТО100',
5950:	'ТО50',
6000:	'ТО2000',
6050:	'ТО50',
6100:	'ТО100',
6150:	'ТО50',
6200:	'ТО100',
6250:	'ТО250',
6300:	'ТО100',
6350:	'ТО50',
6400:	'ТО100',
6450:	'ТО50',
6500:	'ТО500',
6550:	'ТО50',
6600:	'ТО100',
6650:	'ТО50',
6700:	'ТО100',
6750:	'ТО250',
6800:	'ТО100',
6850:	'ТО50',
6900:	'ТО100',
6950:	'ТО50',
7000:	'ТО1000',
7050:	'ТО50',
7100:	'ТО100',
7150:	'ТО50',
7200:	'ТО100',
7250:	'ТО250',
7300:	'ТО100',
7350:	'ТО50',
7400:	'ТО100',
7450:	'ТО50',
7500:	'ТО500',
7550:	'ТО50',
7600:	'ТО100',
7650:	'ТО50',
7700:	'ТО100',
7750:	'ТО250',
7800:	'ТО100',
7850:	'ТО50',
7900:	'ТО100',
7950:	'ТО50',
8000:	'ТО4000',
8050:	'ТО50',
8100:	'ТО100',
8150:	'ТО50',
8200:	'ТО100',
8250:	'ТО250',
8300:	'ТО100',
8350:	'ТО50',
8400:	'ТО100',
8450:	'ТО50',
8500:	'ТО500',
8550:	'ТО50',
8600:	'ТО100',
8650:	'ТО50',
8700:	'ТО100',
8750:	'ТО250',
8800:	'ТО100',
8850:	'ТО50',
8900:	'ТО100',
8950:	'ТО50',
9000:	'ТО1000',
9050:	'ТО50',
9100:	'ТО100',
9150:	'ТО50',
9200:	'ТО100',
9250:	'ТО250',
9300:	'ТО100',
9350:	'ТО50',
9400:	'ТО100',
9450:	'ТО50',
9500:	'ТО500',
9550:	'ТО50',
9600:	'ТО100',
9650:	'ТО50',
9700:	'ТО100',
9750:	'ТО250',
9800:	'ТО100',
9850:	'ТО50',
9900:	'ТО100',
9950:	'ТО50',
10000:	'ТО2000',
10050:	'ТО50',
10100:	'ТО100',
10150:	'ТО50',
10200:	'ТО100',
10250:	'ТО250',
10300:	'ТО100',
10350:	'ТО50',
10400:	'ТО100',
10450:	'ТО50',
10500:	'ТО500',
10550:	'ТО50',
10600:	'ТО100',
10650:	'ТО50',
10700:	'ТО100',
10750:	'ТО250',
10800:	'ТО100',
10850:	'ТО50',
10900:	'ТО100',
10950:	'ТО50',
11000:	'ТО1000',
11050:	'ТО50',
11100:	'ТО100',
11150:	'ТО50',
11200:	'ТО100',
11250:	'ТО250',
11300:	'ТО100',
11350:	'ТО50',
11400:	'ТО100',
11450:	'ТО50',
11500:	'ТО500',
11550:	'ТО50',
11600:	'ТО100',
11650:	'ТО50',
11700:	'ТО100',
11750:	'ТО250',
11800:	'ТО100',
11850:	'ТО50',
11900:	'ТО100',
11950:	'ТО50',
12000:	'ТО4000',
12050:	'ТО50',
12100:	'ТО100',
12150:	'ТО50',
12200:	'ТО100',
12250:	'ТО250',
12300:	'ТО100',
12350:	'ТО50',
12400:	'ТО100',
12450:	'ТО50',
12500:	'ТО500',
12550:	'ТО50',
12600:	'ТО100',
12650:	'ТО50',
12700:	'ТО100',
12750:	'ТО250',
12800:	'ТО100',
12850:	'ТО50',
12900:	'ТО100',
12950:	'ТО50',
13000:	'ТО1000',
13050:	'ТО50',
13100:	'ТО100',
13150:	'ТО50',
13200:	'ТО100',
13250:	'ТО250',
13300:	'ТО100',
13350:	'ТО50',
13400:	'ТО100',
13450:	'ТО50',
13500:	'ТО500',
13550:	'ТО50',
13600:	'ТО100',
13650:	'ТО50',
13700:	'ТО100',
13750:	'ТО250',
13800:	'ТО100',
13850:	'ТО50',
13900:	'ТО100',
13950:	'ТО50',
14000:	'ТО2000',
14050:	'ТО50',
14100:	'ТО100',
14150:	'ТО50',
14200:	'ТО100',
14250:	'ТО250',
14300:	'ТО100',
14350:	'ТО50',
14400:	'ТО100',
14450:	'ТО50',
14500:	'ТО500',
14550:	'ТО50',
14600:	'ТО100',
14650:	'ТО50',
14700:	'ТО100',
14750:	'ТО250',
14800:	'ТО100',
14850:	'ТО50',
14900:	'ТО100',
14950:	'ТО50',
15000:	'ТО1000',
15050:	'ТО50',
15100:	'ТО100',
15150:	'ТО50',
15200:	'ТО100',
15250:	'ТО250',
15300:	'ТО100',
15350:	'ТО50',
15400:	'ТО100',
15450:	'ТО50',
15500:	'ТО500',
15550:	'ТО50',
15600:	'ТО100',
15650:	'ТО50',
15700:	'ТО100',
15750:	'ТО250',
15800:	'ТО100',
15850:	'ТО50',
15900:	'ТО100',
15950:	'ТО50',
16000:	'ТО4000',
16050:	'ТО50',
16100:	'ТО100',
16150:	'ТО50',
16200:	'ТО100',
16250:	'ТО250',
16300:	'ТО100',
16350:	'ТО50',
16400:	'ТО100',
16450:	'ТО50',
16500:	'ТО500',
16550:	'ТО50',
16600:	'ТО100',
16650:	'ТО50',
16700:	'ТО100',
16750:	'ТО250',
16800:	'ТО100',
16850:	'ТО50',
16900:	'ТО100',
16950:	'ТО50',
17000:	'ТО1000',
17050:	'ТО50',
17100:	'ТО100',
17150:	'ТО50',
17200:	'ТО100',
17250:	'ТО250',
17300:	'ТО100',
17350:	'ТО50',
17400:	'ТО100',
17450:	'ТО50',
17500:	'ТО500',
17550:	'ТО50',
17600:	'ТО100',
17650:	'ТО50',
17700:	'ТО100',
17750:	'ТО250',
17800:	'ТО100',
17850:	'ТО50',
17900:	'ТО100',
17950:	'ТО50',
18000:	'ТО2000',
18050:	'ТО50',
18100:	'ТО100',
18150:	'ТО50',
18200:	'ТО100',
18250:	'ТО250',
18300:	'ТО100',
18350:	'ТО50',
18400:	'ТО100',
18450:	'ТО50',
18500:	'ТО500',
18550:	'ТО50',
18600:	'ТО100',
18650:	'ТО50',
18700:	'ТО100',
18750:	'ТО250',
18800:	'ТО100',
18850:	'ТО50',
18900:	'ТО100',
18950:	'ТО50',
19000:	'ТО1000',
19050:	'ТО50',
19100:	'ТО100',
19150:	'ТО50',
19200:	'ТО100',
19250:	'ТО250',
19300:	'ТО100',
19350:	'ТО50',
19400:	'ТО100',
19450:	'ТО50',
19500:	'ТО500',
19550:	'ТО50',
19600:	'ТО100',
19650:	'ТО50',
19700:	'ТО100',
19750:	'ТО250',
19800:	'ТО100',
19850:	'ТО50',
19900:	'ТО100',
19950:	'ТО50',
20000:	'ТО4000',
20050:	'ТО50',
20100:	'ТО100',
20150:	'ТО50',
20200:	'ТО100',
20250:	'ТО250',
20300:	'ТО100',
20350:	'ТО50',
20400:	'ТО100',
20450:	'ТО50',
20500:	'ТО500',
20550:	'ТО50',
20600:	'ТО100',
20650:	'ТО50',
20700:	'ТО100',
20750:	'ТО250',
20800:	'ТО100',
20850:	'ТО50',
20900:	'ТО100',
20950:	'ТО50',
21000:	'ТО1000',
21050:	'ТО50',
21100:	'ТО100',
21150:	'ТО50',
21200:	'ТО100',
21250:	'ТО250',
21300:	'ТО100',
21350:	'ТО50',
21400:	'ТО100',
21450:	'ТО50',
21500:	'ТО500',
21550:	'ТО50',
21600:	'ТО100',
21650:	'ТО50',
21700:	'ТО100',
21750:	'ТО250',
21800:	'ТО100',
21850:	'ТО50',
21900:	'ТО100',
21950:	'ТО50',
22000:	'ТО2000',
22050:	'ТО50',
22100:	'ТО100',
22150:	'ТО50',
22200:	'ТО100',
22250:	'ТО250',
22300:	'ТО100',
22350:	'ТО50',
22400:	'ТО100',
22450:	'ТО50',
22500:	'ТО500',
22550:	'ТО50',
22600:	'ТО100',
22650:	'ТО50',
22700:	'ТО100',
22750:	'ТО250',
22800:	'ТО100',
22850:	'ТО50',
22900:	'ТО100',
22950:	'ТО50',
23000:	'ТО1000',
23050:	'ТО50',
23100:	'ТО100',
23150:	'ТО50',
23200:	'ТО100',
23250:	'ТО250',
23300:	'ТО100',
23350:	'ТО50',
23400:	'ТО100',
23450:	'ТО50',
23500:	'ТО500',
23550:	'ТО50',
23600:	'ТО100',
23650:	'ТО50',
23700:	'ТО100',
23750:	'ТО250',
23800:	'ТО100',
23850:	'ТО50',
23900:	'ТО100',
23950:	'ТО50',
24000:	'ТО4000',
24050:	'ТО50',
24100:	'ТО100',
24150:	'ТО50',
24200:	'ТО100',
24250:	'ТО250',
24300:	'ТО100',
24350:	'ТО50',
24400:	'ТО100',
24450:	'ТО50',
24500:	'ТО500',
24550:	'ТО50',
24600:	'ТО100',
24650:	'ТО50',
24700:	'ТО100',
24750:	'ТО250',
24800:	'ТО100',
24850:	'ТО50',
24900:	'ТО100',
24950:	'ТО50',
25000:	'ТО1000',
25050:	'ТО50',
25100:	'ТО100',
25150:	'ТО50',
25200:	'ТО100',
25250:	'ТО250',
25300:	'ТО100',
25350:	'ТО50',
25400:	'ТО100',
25450:	'ТО50',
25500:	'ТО500',
25550:	'ТО50',
25600:	'ТО100',
25650:	'ТО50',
25700:	'ТО100',
25750:	'ТО250',
25800:	'ТО100',
25850:	'ТО50',
25900:	'ТО100',
25950:	'ТО50',
26000:	'ТО2000',
26050:	'ТО50',
26100:	'ТО100',
26150:	'ТО50',
26200:	'ТО100',
26250:	'ТО250',
26300:	'ТО100',
26350:	'ТО50',
26400:	'ТО100',
26450:	'ТО50',
26500:	'ТО500',
26550:	'ТО50',
26600:	'ТО100',
26650:	'ТО50',
26700:	'ТО100',
26750:	'ТО250',
26800:	'ТО100',
26850:	'ТО50',
26900:	'ТО100',
26950:	'ТО50',
27000:	'ТО1000',
27050:	'ТО50',
27100:	'ТО100',
27150:	'ТО50',
27200:	'ТО100',
27250:	'ТО250',
27300:	'ТО100',
27350:	'ТО50',
27400:	'ТО100',
27450:	'ТО50',
27500:	'ТО500',
27550:	'ТО50',
27600:	'ТО100',
27650:	'ТО50',
27700:	'ТО100',
27750:	'ТО250',
27800:	'ТО100',
27850:	'ТО50',
27900:	'ТО100',
27950:	'ТО50',
28000:	'ТО4000',
28050:	'ТО50',
28100:	'ТО100',
28150:	'ТО50',
28200:	'ТО100',
28250:	'ТО250',
28300:	'ТО100',
28350:	'ТО50',
28400:	'ТО100',
28450:	'ТО50',
28500:	'ТО500',
28550:	'ТО50',
28600:	'ТО100',
28650:	'ТО50',
28700:	'ТО100',
28750:	'ТО250',
28800:	'ТО100',
28850:	'ТО50',
28900:	'ТО100',
28950:	'ТО50',
29000:	'ТО1000',
29050:	'ТО50',
29100:	'ТО100',
29150:	'ТО50',
29200:	'ТО100',
29250:	'ТО250',
29300:	'ТО100',
29350:	'ТО50',
29400:	'ТО100',
29450:	'ТО50',
29500:	'ТО500',
29550:	'ТО50',
29600:	'ТО100',
29650:	'ТО50',
29700:	'ТО100',
29750:	'ТО250',
29800:	'ТО100',
29850:	'ТО50',
29900:	'ТО100',
29950:	'ТО50',
30000:	'ТО2000',
30050:	'ТО50',
30100:	'ТО100',
30150:	'ТО50',
30200:	'ТО100',
30250:	'ТО250',
30300:	'ТО100',
30350:	'ТО50',
30400:	'ТО100',
30450:	'ТО50',
30500:	'ТО500',
30550:	'ТО50',
30600:	'ТО100',
30650:	'ТО50',
30700:	'ТО100',
30750:	'ТО250',
30800:	'ТО100',
30850:	'ТО50',
30900:	'ТО100',
30950:	'ТО50',
31000:	'ТО1000',
31050:	'ТО50',
31100:	'ТО100',
31150:	'ТО50',
31200:	'ТО100',
31250:	'ТО250',
31300:	'ТО100',
31350:	'ТО50',
31400:	'ТО100',
31450:	'ТО50',
31500:	'ТО500',
31550:	'ТО50',
31600:	'ТО100',
31650:	'ТО50',
31700:	'ТО100',
31750:	'ТО250',
31800:	'ТО100',
31850:	'ТО50',
31900:	'ТО100',
31950:	'ТО50',
32000:	'ТО4000',
32050:	'ТО50',
32100:	'ТО100',
32150:	'ТО50',
32200:	'ТО100',
32250:	'ТО250',
32300:	'ТО100',
32350:	'ТО50',
32400:	'ТО100',
32450:	'ТО50',
32500:	'ТО500',
32550:	'ТО50',
32600:	'ТО100',
32650:	'ТО50',
32700:	'ТО100',
32750:	'ТО250',
32800:	'ТО100',
32850:	'ТО50',
32900:	'ТО100',
32950:	'ТО50',
33000:	'ТО1000',
33050:	'ТО50',
33100:	'ТО100',
33150:	'ТО50',
33200:	'ТО100',
33250:	'ТО250',
33300:	'ТО100',
33350:	'ТО50',
33400:	'ТО100',
33450:	'ТО50',
33500:	'ТО500',
33550:	'ТО50',
33600:	'ТО100',
33650:	'ТО50',
33700:	'ТО100',
33750:	'ТО250',
33800:	'ТО100',
33850:	'ТО50',
33900:	'ТО100',
33950:	'ТО50',
34000:	'ТО2000',
34050:	'ТО50',
34100:	'ТО100',
34150:	'ТО50',
34200:	'ТО100',
34250:	'ТО250',
34300:	'ТО100',
34350:	'ТО50',
34400:	'ТО100',
34450:	'ТО50',
34500:	'ТО500',
34550:	'ТО50',
34600:	'ТО100',
34650:	'ТО50',
34700:	'ТО100',
34750:	'ТО250',
34800:	'ТО100',
34850:	'ТО50',
34900:	'ТО100',
34950:	'ТО50',
35000:	'ТО1000',
35050:	'ТО50',
35100:	'ТО100',
35150:	'ТО50',
35200:	'ТО100',
35250:	'ТО250',
35300:	'ТО100',
35350:	'ТО50',
35400:	'ТО100',
35450:	'ТО50',
35500:	'ТО500',
35550:	'ТО50',
35600:	'ТО100',
35650:	'ТО50',
35700:	'ТО100',
35750:	'ТО250',
35800:	'ТО100',
35850:	'ТО50',
35900:	'ТО100',
35950:	'ТО50',
36000:	'ТО4000',
36050:	'ТО50',
36100:	'ТО100',
36150:	'ТО50',
36200:	'ТО100',
36250:	'ТО250',
36300:	'ТО100',
36350:	'ТО50',
36400:	'ТО100',
36450:	'ТО50',
36500:	'ТО500',
36550:	'ТО50',
36600:	'ТО100',
36650:	'ТО50',
36700:	'ТО100',
36750:	'ТО250',
36800:	'ТО100',
36850:	'ТО50',
36900:	'ТО100',
36950:	'ТО50',
37000:	'ТО1000',
37050:	'ТО50',
37100:	'ТО100',
37150:	'ТО50',
37200:	'ТО100',
37250:	'ТО250',
37300:	'ТО100',
37350:	'ТО50',
37400:	'ТО100',
37450:	'ТО50',
37500:	'ТО500',
37550:	'ТО50',
37600:	'ТО100',
37650:	'ТО50',
37700:	'ТО100',
37750:	'ТО250',
37800:	'ТО100',
37850:	'ТО50',
37900:	'ТО100',
37950:	'ТО50',
38000:	'ТО2000',
38050:	'ТО50',
38100:	'ТО100',
38150:	'ТО50',
38200:	'ТО100',
38250:	'ТО250',
38300:	'ТО100',
38350:	'ТО50',
38400:	'ТО100',
38450:	'ТО50',
38500:	'ТО500',
38550:	'ТО50',
38600:	'ТО100',
38650:	'ТО50',
38700:	'ТО100',
38750:	'ТО250',
38800:	'ТО100',
38850:	'ТО50',
38900:	'ТО100',
38950:	'ТО50',
39000:	'ТО1000',
39050:	'ТО50',
39100:	'ТО100',
39150:	'ТО50',
39200:	'ТО100',
39250:	'ТО250',
39300:	'ТО100',
39350:	'ТО50',
39400:	'ТО100',
39450:	'ТО50',
39500:	'ТО500',
39550:	'ТО50',
39600:	'ТО100',
39650:	'ТО50',
39700:	'ТО100',
39750:	'ТО250',
39800:	'ТО100',
39850:	'ТО50',
39900:	'ТО100',
39950:	'ТО50',
40000:	'ТО4000',
40050:	'ТО50',
40100:	'ТО100',
40150:	'ТО50',
40200:	'ТО100',
40250:	'ТО250',
40300:	'ТО100',
40350:	'ТО50',
40400:	'ТО100',
40450:	'ТО50',
40500:	'ТО500',
40550:	'ТО50',
40600:	'ТО100',
40650:	'ТО50',
40700:	'ТО100',
40750:	'ТО250',
40800:	'ТО100',
40850:	'ТО50',
40900:	'ТО100',
40950:	'ТО50',
41000:	'ТО1000',
41050:	'ТО50',
41100:	'ТО100',
41150:	'ТО50',
41200:	'ТО100',
41250:	'ТО250',
41300:	'ТО100',
41350:	'ТО50',
41400:	'ТО100',
41450:	'ТО50',
41500:	'ТО500',
41550:	'ТО50',
41600:	'ТО100',
41650:	'ТО50',
41700:	'ТО100',
41750:	'ТО250',
41800:	'ТО100',
41850:	'ТО50',
41900:	'ТО100',
41950:	'ТО50',
42000:	'ТО2000',
42050:	'ТО50',
42100:	'ТО100',
42150:	'ТО50',
42200:	'ТО100',
42250:	'ТО250',
42300:	'ТО100',
42350:	'ТО50',
42400:	'ТО100',
42450:	'ТО50',
42500:	'ТО500',
42550:	'ТО50',
42600:	'ТО100',
42650:	'ТО50',
42700:	'ТО100',
42750:	'ТО250',
42800:	'ТО100',
42850:	'ТО50',
42900:	'ТО100',
42950:	'ТО50',
43000:	'ТО1000',
43050:	'ТО50',
43100:	'ТО100',
43150:	'ТО50',
43200:	'ТО100',
43250:	'ТО250',
43300:	'ТО100',
43350:	'ТО50',
43400:	'ТО100',
43450:	'ТО50',
43500:	'ТО500',
43550:	'ТО50',
43600:	'ТО100',
43650:	'ТО50',
43700:	'ТО100',
43750:	'ТО250',
43800:	'ТО100',
43850:	'ТО50',
43900:	'ТО100',
43950:	'ТО50',
44000:	'ТО4000',
44050:	'ТО50',
44100:	'ТО100',
44150:	'ТО50',
44200:	'ТО100',
44250:	'ТО250',
44300:	'ТО100',
44350:	'ТО50',
44400:	'ТО100',
44450:	'ТО50',
44500:	'ТО500',
44550:	'ТО50',
44600:	'ТО100',
44650:	'ТО50',
44700:	'ТО100',
44750:	'ТО250',
44800:	'ТО100',
44850:	'ТО50',
44900:	'ТО100',
44950:	'ТО50',
45000:	'ТО1000',
45050:	'ТО50',
45100:	'ТО100',
45150:	'ТО50',
45200:	'ТО100',
45250:	'ТО250',
45300:	'ТО100',
45350:	'ТО50',
45400:	'ТО100',
45450:	'ТО50',
45500:	'ТО500',
45550:	'ТО50',
45600:	'ТО100',
45650:	'ТО50',
45700:	'ТО100',
45750:	'ТО250',
45800:	'ТО100',
45850:	'ТО50',
45900:	'ТО100',
45950:	'ТО50',
46000:	'ТО2000',
46050:	'ТО50',
46100:	'ТО100',
46150:	'ТО50',
46200:	'ТО100',
46250:	'ТО250',
46300:	'ТО100',
46350:	'ТО50',
46400:	'ТО100',
46450:	'ТО50',
46500:	'ТО500',
46550:	'ТО50',
46600:	'ТО100',
46650:	'ТО50',
46700:	'ТО100',
46750:	'ТО250',
46800:	'ТО100',
46850:	'ТО50',
46900:	'ТО100',
46950:	'ТО50',
47000:	'ТО1000',
47050:	'ТО50',
47100:	'ТО100',
47150:	'ТО50',
47200:	'ТО100',
47250:	'ТО250',
47300:	'ТО100',
47350:	'ТО50',
47400:	'ТО100',
47450:	'ТО50',
47500:	'ТО500',
47550:	'ТО50',
47600:	'ТО100',
47650:	'ТО50',
47700:	'ТО100',
47750:	'ТО250',
47800:	'ТО100',
47850:	'ТО50',
47900:	'ТО100',
47950:	'ТО50',
48000:	'ТО4000'

}

In [50]:
to_dict_TM={
    50:	'ТО50',
100:	'ТО50',
150:	'ТО50',
200:	'ТО50',
250:	'ТО250',
300:	'ТО50',
350:	'ТО50',
400:	'ТО50',
450:	'ТО50',
500:	'ТО500',
550:	'ТО50',
600:	'ТО50',
650:	'ТО50',
700:	'ТО50',
750:	'ТО250',
800:	'ТО50',
850:	'ТО50',
900:	'ТО50',
950:	'ТО50',
1000:	'ТО1000',
1050:	'ТО50',
1100:	'ТО50',
1150:	'ТО50',
1200:	'ТО50',
1250:	'ТО250',
1300:	'ТО50',
1350:	'ТО50',
1400:	'ТО50',
1450:	'ТО50',
1500:	'ТО500',
1550:	'ТО50',
1600:	'ТО50',
1650:	'ТО50',
1700:	'ТО50',
1750:	'ТО250',
1800:	'ТО50',
1850:	'ТО50',
1900:	'ТО50',
1950:	'ТО50',
2000:	'ТО2000',
2050:	'ТО50',
2100:	'ТО50',
2150:	'ТО50',
2200:	'ТО50',
2250:	'ТО250',
2300:	'ТО50',
2350:	'ТО50',
2400:	'ТО50',
2450:	'ТО50',
2500:	'ТО500',
2550:	'ТО50',
2600:	'ТО50',
2650:	'ТО50',
2700:	'ТО50',
2750:	'ТО250',
2800:	'ТО50',
2850:	'ТО50',
2900:	'ТО50',
2950:	'ТО50',
3000:	'ТО1000',
3050:	'ТО50',
3100:	'ТО50',
3150:	'ТО50',
3200:	'ТО50',
3250:	'ТО250',
3300:	'ТО50',
3350:	'ТО50',
3400:	'ТО50',
3450:	'ТО50',
3500:	'ТО500',
3550:	'ТО50',
3600:	'ТО50',
3650:	'ТО50',
3700:	'ТО50',
3750:	'ТО250',
3800:	'ТО50',
3850:	'ТО50',
3900:	'ТО50',
3950:	'ТО50',
4000:	'ТО4000',
4050:	'ТО50',
4100:	'ТО50',
4150:	'ТО50',
4200:	'ТО50',
4250:	'ТО250',
4300:	'ТО50',
4350:	'ТО50',
4400:	'ТО50',
4450:	'ТО50',
4500:	'ТО500',
4550:	'ТО50',
4600:	'ТО50',
4650:	'ТО50',
4700:	'ТО50',
4750:	'ТО250',
4800:	'ТО50',
4850:	'ТО50',
4900:	'ТО50',
4950:	'ТО50',
5000:	'ТО1000',
5050:	'ТО50',
5100:	'ТО50',
5150:	'ТО50',
5200:	'ТО50',
5250:	'ТО250',
5300:	'ТО50',
5350:	'ТО50',
5400:	'ТО50',
5450:	'ТО50',
5500:	'ТО500',
5550:	'ТО50',
5600:	'ТО50',
5650:	'ТО50',
5700:	'ТО50',
5750:	'ТО250',
5800:	'ТО50',
5850:	'ТО50',
5900:	'ТО50',
5950:	'ТО50',
6000:	'ТО2000',
6050:	'ТО50',
6100:	'ТО50',
6150:	'ТО50',
6200:	'ТО50',
6250:	'ТО250',
6300:	'ТО50',
6350:	'ТО50',
6400:	'ТО50',
6450:	'ТО50',
6500:	'ТО500',
6550:	'ТО50',
6600:	'ТО50',
6650:	'ТО50',
6700:	'ТО50',
6750:	'ТО250',
6800:	'ТО50',
6850:	'ТО50',
6900:	'ТО50',
6950:	'ТО50',
7000:	'ТО1000',
7050:	'ТО50',
7100:	'ТО50',
7150:	'ТО50',
7200:	'ТО50',
7250:	'ТО250',
7300:	'ТО50',
7350:	'ТО50',
7400:	'ТО50',
7450:	'ТО50',
7500:	'ТО500',
7550:	'ТО50',
7600:	'ТО50',
7650:	'ТО50',
7700:	'ТО50',
7750:	'ТО250',
7800:	'ТО50',
7850:	'ТО50',
7900:	'ТО50',
7950:	'ТО50',
8000:	'ТО4000',
8050:	'ТО50',
8100:	'ТО50',
8150:	'ТО50',
8200:	'ТО50',
8250:	'ТО250',
8300:	'ТО50',
8350:	'ТО50',
8400:	'ТО50',
8450:	'ТО50',
8500:	'ТО500',
8550:	'ТО50',
8600:	'ТО50',
8650:	'ТО50',
8700:	'ТО50',
8750:	'ТО250',
8800:	'ТО50',
8850:	'ТО50',
8900:	'ТО50',
8950:	'ТО50',
9000:	'ТО1000',
9050:	'ТО50',
9100:	'ТО50',
9150:	'ТО50',
9200:	'ТО50',
9250:	'ТО250',
9300:	'ТО50',
9350:	'ТО50',
9400:	'ТО50',
9450:	'ТО50',
9500:	'ТО500',
9550:	'ТО50',
9600:	'ТО50',
9650:	'ТО50',
9700:	'ТО50',
9750:	'ТО250',
9800:	'ТО50',
9850:	'ТО50',
9900:	'ТО50',
9950:	'ТО50',
10000:	'ТО2000',
10050:	'ТО50',
10100:	'ТО50',
10150:	'ТО50',
10200:	'ТО50',
10250:	'ТО250',
10300:	'ТО50',
10350:	'ТО50',
10400:	'ТО50',
10450:	'ТО50',
10500:	'ТО500',
10550:	'ТО50',
10600:	'ТО50',
10650:	'ТО50',
10700:	'ТО50',
10750:	'ТО250',
10800:	'ТО50',
10850:	'ТО50',
10900:	'ТО50',
10950:	'ТО50',
11000:	'ТО1000',
11050:	'ТО50',
11100:	'ТО50',
11150:	'ТО50',
11200:	'ТО50',
11250:	'ТО250',
11300:	'ТО50',
11350:	'ТО50',
11400:	'ТО50',
11450:	'ТО50',
11500:	'ТО500',
11550:	'ТО50',
11600:	'ТО50',
11650:	'ТО50',
11700:	'ТО50',
11750:	'ТО250',
11800:	'ТО50',
11850:	'ТО50',
11900:	'ТО50',
11950:	'ТО50',
12000:	'ТО4000',
12050:	'ТО50',
12100:	'ТО50',
12150:	'ТО50',
12200:	'ТО50',
12250:	'ТО250',
12300:	'ТО50',
12350:	'ТО50',
12400:	'ТО50',
12450:	'ТО50',
12500:	'ТО500',
12550:	'ТО50',
12600:	'ТО50',
12650:	'ТО50',
12700:	'ТО50',
12750:	'ТО250',
12800:	'ТО50',
12850:	'ТО50',
12900:	'ТО50',
12950:	'ТО50',
13000:	'ТО1000',
13050:	'ТО50',
13100:	'ТО50',
13150:	'ТО50',
13200:	'ТО50',
13250:	'ТО250',
13300:	'ТО50',
13350:	'ТО50',
13400:	'ТО50',
13450:	'ТО50',
13500:	'ТО500',
13550:	'ТО50',
13600:	'ТО50',
13650:	'ТО50',
13700:	'ТО50',
13750:	'ТО250',
13800:	'ТО50',
13850:	'ТО50',
13900:	'ТО50',
13950:	'ТО50',
14000:	'ТО2000',
14050:	'ТО50',
14100:	'ТО50',
14150:	'ТО50',
14200:	'ТО50',
14250:	'ТО250',
14300:	'ТО50',
14350:	'ТО50',
14400:	'ТО50',
14450:	'ТО50',
14500:	'ТО500',
14550:	'ТО50',
14600:	'ТО50',
14650:	'ТО50',
14700:	'ТО50',
14750:	'ТО250',
14800:	'ТО50',
14850:	'ТО50',
14900:	'ТО50',
14950:	'ТО50',
15000:	'ТО1000',
15050:	'ТО50',
15100:	'ТО50',
15150:	'ТО50',
15200:	'ТО50',
15250:	'ТО250',
15300:	'ТО50',
15350:	'ТО50',
15400:	'ТО50',
15450:	'ТО50',
15500:	'ТО500',
15550:	'ТО50',
15600:	'ТО50',
15650:	'ТО50',
15700:	'ТО50',
15750:	'ТО250',
15800:	'ТО50',
15850:	'ТО50',
15900:	'ТО50',
15950:	'ТО50',
16000:	'ТО4000',
16050:	'ТО50',
16100:	'ТО50',
16150:	'ТО50',
16200:	'ТО50',
16250:	'ТО250',
16300:	'ТО50',
16350:	'ТО50',
16400:	'ТО50',
16450:	'ТО50',
16500:	'ТО500',
16550:	'ТО50',
16600:	'ТО50',
16650:	'ТО50',
16700:	'ТО50',
16750:	'ТО250',
16800:	'ТО50',
16850:	'ТО50',
16900:	'ТО50',
16950:	'ТО50',
17000:	'ТО1000',
17050:	'ТО50',
17100:	'ТО50',
17150:	'ТО50',
17200:	'ТО50',
17250:	'ТО250',
17300:	'ТО50',
17350:	'ТО50',
17400:	'ТО50',
17450:	'ТО50',
17500:	'ТО500',
17550:	'ТО50',
17600:	'ТО50',
17650:	'ТО50',
17700:	'ТО50',
17750:	'ТО250',
17800:	'ТО50',
17850:	'ТО50',
17900:	'ТО50',
17950:	'ТО50',
18000:	'ТО2000',
18050:	'ТО50',
18100:	'ТО50',
18150:	'ТО50',
18200:	'ТО50',
18250:	'ТО250',
18300:	'ТО50',
18350:	'ТО50',
18400:	'ТО50',
18450:	'ТО50',
18500:	'ТО500',
18550:	'ТО50',
18600:	'ТО50',
18650:	'ТО50',
18700:	'ТО50',
18750:	'ТО250',
18800:	'ТО50',
18850:	'ТО50',
18900:	'ТО50',
18950:	'ТО50',
19000:	'ТО1000',
19050:	'ТО50',
19100:	'ТО50',
19150:	'ТО50',
19200:	'ТО50',
19250:	'ТО250',
19300:	'ТО50',
19350:	'ТО50',
19400:	'ТО50',
19450:	'ТО50',
19500:	'ТО500',
19550:	'ТО50',
19600:	'ТО50',
19650:	'ТО50',
19700:	'ТО50',
19750:	'ТО250',
19800:	'ТО50',
19850:	'ТО50',
19900:	'ТО50',
19950:	'ТО50',
20000:	'ТО4000',
20050:	'ТО50',
20100:	'ТО50',
20150:	'ТО50',
20200:	'ТО50',
20250:	'ТО250',
20300:	'ТО50',
20350:	'ТО50',
20400:	'ТО50',
20450:	'ТО50',
20500:	'ТО500',
20550:	'ТО50',
20600:	'ТО50',
20650:	'ТО50',
20700:	'ТО50',
20750:	'ТО250',
20800:	'ТО50',
20850:	'ТО50',
20900:	'ТО50',
20950:	'ТО50',
21000:	'ТО1000',
21050:	'ТО50',
21100:	'ТО50',
21150:	'ТО50',
21200:	'ТО50',
21250:	'ТО250',
21300:	'ТО50',
21350:	'ТО50',
21400:	'ТО50',
21450:	'ТО50',
21500:	'ТО500',
21550:	'ТО50',
21600:	'ТО50',
21650:	'ТО50',
21700:	'ТО50',
21750:	'ТО250',
21800:	'ТО50',
21850:	'ТО50',
21900:	'ТО50',
21950:	'ТО50',
22000:	'ТО2000',
22050:	'ТО50',
22100:	'ТО50',
22150:	'ТО50',
22200:	'ТО50',
22250:	'ТО250',
22300:	'ТО50',
22350:	'ТО50',
22400:	'ТО50',
22450:	'ТО50',
22500:	'ТО500',
22550:	'ТО50',
22600:	'ТО50',
22650:	'ТО50',
22700:	'ТО50',
22750:	'ТО250',
22800:	'ТО50',
22850:	'ТО50',
22900:	'ТО50',
22950:	'ТО50',
23000:	'ТО1000',
23050:	'ТО50',
23100:	'ТО50',
23150:	'ТО50',
23200:	'ТО50',
23250:	'ТО250',
23300:	'ТО50',
23350:	'ТО50',
23400:	'ТО50',
23450:	'ТО50',
23500:	'ТО500',
23550:	'ТО50',
23600:	'ТО50',
23650:	'ТО50',
23700:	'ТО50',
23750:	'ТО250',
23800:	'ТО50',
23850:	'ТО50',
23900:	'ТО50',
23950:	'ТО50',
24000:	'ТО4000',
24050:	'ТО50',
24100:	'ТО50',
24150:	'ТО50',
24200:	'ТО50',
24250:	'ТО250',
24300:	'ТО50',
24350:	'ТО50',
24400:	'ТО50',
24450:	'ТО50',
24500:	'ТО500',
24550:	'ТО50',
24600:	'ТО50',
24650:	'ТО50',
24700:	'ТО50',
24750:	'ТО250',
24800:	'ТО50',
24850:	'ТО50',
24900:	'ТО50',
24950:	'ТО50',
25000:	'ТО1000',
25050:	'ТО50',
25100:	'ТО50',
25150:	'ТО50',
25200:	'ТО50',
25250:	'ТО250',
25300:	'ТО50',
25350:	'ТО50',
25400:	'ТО50',
25450:	'ТО50',
25500:	'ТО500',
25550:	'ТО50',
25600:	'ТО50',
25650:	'ТО50',
25700:	'ТО50',
25750:	'ТО250',
25800:	'ТО50',
25850:	'ТО50',
25900:	'ТО50',
25950:	'ТО50',
26000:	'ТО2000',
26050:	'ТО50',
26100:	'ТО50',
26150:	'ТО50',
26200:	'ТО50',
26250:	'ТО250',
26300:	'ТО50',
26350:	'ТО50',
26400:	'ТО50',
26450:	'ТО50',
26500:	'ТО500',
26550:	'ТО50',
26600:	'ТО50',
26650:	'ТО50',
26700:	'ТО50',
26750:	'ТО250',
26800:	'ТО50',
26850:	'ТО50',
26900:	'ТО50',
26950:	'ТО50',
27000:	'ТО1000',
27050:	'ТО50',
27100:	'ТО50',
27150:	'ТО50',
27200:	'ТО50',
27250:	'ТО250',
27300:	'ТО50',
27350:	'ТО50',
27400:	'ТО50',
27450:	'ТО50',
27500:	'ТО500',
27550:	'ТО50',
27600:	'ТО50',
27650:	'ТО50',
27700:	'ТО50',
27750:	'ТО250',
27800:	'ТО50',
27850:	'ТО50',
27900:	'ТО50',
27950:	'ТО50',
28000:	'ТО4000',
28050:	'ТО50',
28100:	'ТО50',
28150:	'ТО50',
28200:	'ТО50',
28250:	'ТО250',
28300:	'ТО50',
28350:	'ТО50',
28400:	'ТО50',
28450:	'ТО50',
28500:	'ТО500',
28550:	'ТО50',
28600:	'ТО50',
28650:	'ТО50',
28700:	'ТО50',
28750:	'ТО250',
28800:	'ТО50',
28850:	'ТО50',
28900:	'ТО50',
28950:	'ТО50',
29000:	'ТО1000',
29050:	'ТО50',
29100:	'ТО50',
29150:	'ТО50',
29200:	'ТО50',
29250:	'ТО250',
29300:	'ТО50',
29350:	'ТО50',
29400:	'ТО50',
29450:	'ТО50',
29500:	'ТО500',
29550:	'ТО50',
29600:	'ТО50',
29650:	'ТО50',
29700:	'ТО50',
29750:	'ТО250',
29800:	'ТО50',
29850:	'ТО50',
29900:	'ТО50',
29950:	'ТО50',
30000:	'ТО2000',
30050:	'ТО50',
30100:	'ТО50',
30150:	'ТО50',
30200:	'ТО50',
30250:	'ТО250',
30300:	'ТО50',
30350:	'ТО50',
30400:	'ТО50',
30450:	'ТО50',
30500:	'ТО500',
30550:	'ТО50',
30600:	'ТО50',
30650:	'ТО50',
30700:	'ТО50',
30750:	'ТО250',
30800:	'ТО50',
30850:	'ТО50',
30900:	'ТО50',
30950:	'ТО50',
31000:	'ТО1000',
31050:	'ТО50',
31100:	'ТО50',
31150:	'ТО50',
31200:	'ТО50',
31250:	'ТО250',
31300:	'ТО50',
31350:	'ТО50',
31400:	'ТО50',
31450:	'ТО50',
31500:	'ТО500',
31550:	'ТО50',
31600:	'ТО50',
31650:	'ТО50',
31700:	'ТО50',
31750:	'ТО250',
31800:	'ТО50',
31850:	'ТО50',
31900:	'ТО50',
31950:	'ТО50',
32000:	'ТО4000',
32050:	'ТО50',
32100:	'ТО50',
32150:	'ТО50',
32200:	'ТО50',
32250:	'ТО250',
32300:	'ТО50',
32350:	'ТО50',
32400:	'ТО50',
32450:	'ТО50',
32500:	'ТО500',
32550:	'ТО50',
32600:	'ТО50',
32650:	'ТО50',
32700:	'ТО50',
32750:	'ТО250',
32800:	'ТО50',
32850:	'ТО50',
32900:	'ТО50',
32950:	'ТО50',
33000:	'ТО1000',
33050:	'ТО50',
33100:	'ТО50',
33150:	'ТО50',
33200:	'ТО50',
33250:	'ТО250',
33300:	'ТО50',
33350:	'ТО50',
33400:	'ТО50',
33450:	'ТО50',
33500:	'ТО500',
33550:	'ТО50',
33600:	'ТО50',
33650:	'ТО50',
33700:	'ТО50',
33750:	'ТО250',
33800:	'ТО50',
33850:	'ТО50',
33900:	'ТО50',
33950:	'ТО50',
34000:	'ТО2000',
34050:	'ТО50',
34100:	'ТО50',
34150:	'ТО50',
34200:	'ТО50',
34250:	'ТО250',
34300:	'ТО50',
34350:	'ТО50',
34400:	'ТО50',
34450:	'ТО50',
34500:	'ТО500',
34550:	'ТО50',
34600:	'ТО50',
34650:	'ТО50',
34700:	'ТО50',
34750:	'ТО250',
34800:	'ТО50',
34850:	'ТО50',
34900:	'ТО50',
34950:	'ТО50',
35000:	'ТО1000',
35050:	'ТО50',
35100:	'ТО50',
35150:	'ТО50',
35200:	'ТО50',
35250:	'ТО250',
35300:	'ТО50',
35350:	'ТО50',
35400:	'ТО50',
35450:	'ТО50',
35500:	'ТО500',
35550:	'ТО50',
35600:	'ТО50',
35650:	'ТО50',
35700:	'ТО50',
35750:	'ТО250',
35800:	'ТО50',
35850:	'ТО50',
35900:	'ТО50',
35950:	'ТО50',
36000:	'ТО4000',
36050:	'ТО50',
36100:	'ТО50',
36150:	'ТО50',
36200:	'ТО50',
36250:	'ТО250',
36300:	'ТО50',
36350:	'ТО50',
36400:	'ТО50',
36450:	'ТО50',
36500:	'ТО500',
36550:	'ТО50',
36600:	'ТО50',
36650:	'ТО50',
36700:	'ТО50',
36750:	'ТО250',
36800:	'ТО50',
36850:	'ТО50',
36900:	'ТО50',
36950:	'ТО50',
37000:	'ТО1000',
37050:	'ТО50',
37100:	'ТО50',
37150:	'ТО50',
37200:	'ТО50',
37250:	'ТО250',
37300:	'ТО50',
37350:	'ТО50',
37400:	'ТО50',
37450:	'ТО50',
37500:	'ТО500',
37550:	'ТО50',
37600:	'ТО50',
37650:	'ТО50',
37700:	'ТО50',
37750:	'ТО250',
37800:	'ТО50',
37850:	'ТО50',
37900:	'ТО50',
37950:	'ТО50',
38000:	'ТО2000',
38050:	'ТО50',
38100:	'ТО50',
38150:	'ТО50',
38200:	'ТО50',
38250:	'ТО250',
38300:	'ТО50',
38350:	'ТО50',
38400:	'ТО50',
38450:	'ТО50',
38500:	'ТО500',
38550:	'ТО50',
38600:	'ТО50',
38650:	'ТО50',
38700:	'ТО50',
38750:	'ТО250',
38800:	'ТО50',
38850:	'ТО50',
38900:	'ТО50',
38950:	'ТО50',
39000:	'ТО1000',
39050:	'ТО50',
39100:	'ТО50',
39150:	'ТО50',
39200:	'ТО50',
39250:	'ТО250',
39300:	'ТО50',
39350:	'ТО50',
39400:	'ТО50',
39450:	'ТО50',
39500:	'ТО500',
39550:	'ТО50',
39600:	'ТО50',
39650:	'ТО50',
39700:	'ТО50',
39750:	'ТО250',
39800:	'ТО50',
39850:	'ТО50',
39900:	'ТО50',
39950:	'ТО50',
40000:	'ТО4000',
40050:	'ТО50',
40100:	'ТО50',
40150:	'ТО50',
40200:	'ТО50',
40250:	'ТО250',
40300:	'ТО50',
40350:	'ТО50',
40400:	'ТО50',
40450:	'ТО50',
40500:	'ТО500',
40550:	'ТО50',
40600:	'ТО50',
40650:	'ТО50',
40700:	'ТО50',
40750:	'ТО250',
40800:	'ТО50',
40850:	'ТО50',
40900:	'ТО50',
40950:	'ТО50',
41000:	'ТО1000',
41050:	'ТО50',
41100:	'ТО50',
41150:	'ТО50',
41200:	'ТО50',
41250:	'ТО250',
41300:	'ТО50',
41350:	'ТО50',
41400:	'ТО50',
41450:	'ТО50',
41500:	'ТО500',
41550:	'ТО50',
41600:	'ТО50',
41650:	'ТО50',
41700:	'ТО50',
41750:	'ТО250',
41800:	'ТО50',
41850:	'ТО50',
41900:	'ТО50',
41950:	'ТО50',
42000:	'ТО2000',
42050:	'ТО50',
42100:	'ТО50',
42150:	'ТО50',
42200:	'ТО50',
42250:	'ТО250',
42300:	'ТО50',
42350:	'ТО50',
42400:	'ТО50',
42450:	'ТО50',
42500:	'ТО500',
42550:	'ТО50',
42600:	'ТО50',
42650:	'ТО50',
42700:	'ТО50',
42750:	'ТО250',
42800:	'ТО50',
42850:	'ТО50',
42900:	'ТО50',
42950:	'ТО50',
43000:	'ТО1000',
43050:	'ТО50',
43100:	'ТО50',
43150:	'ТО50',
43200:	'ТО50',
43250:	'ТО250',
43300:	'ТО50',
43350:	'ТО50',
43400:	'ТО50',
43450:	'ТО50',
43500:	'ТО500',
43550:	'ТО50',
43600:	'ТО50',
43650:	'ТО50',
43700:	'ТО50',
43750:	'ТО250',
43800:	'ТО50',
43850:	'ТО50',
43900:	'ТО50',
43950:	'ТО50',
44000:	'ТО4000',
44050:	'ТО50',
44100:	'ТО50',
44150:	'ТО50',
44200:	'ТО50',
44250:	'ТО250',
44300:	'ТО50',
44350:	'ТО50',
44400:	'ТО50',
44450:	'ТО50',
44500:	'ТО500',
44550:	'ТО50',
44600:	'ТО50',
44650:	'ТО50',
44700:	'ТО50',
44750:	'ТО250',
44800:	'ТО50',
44850:	'ТО50',
44900:	'ТО50',
44950:	'ТО50',
45000:	'ТО1000',
45050:	'ТО50',
45100:	'ТО50',
45150:	'ТО50',
45200:	'ТО50',
45250:	'ТО250',
45300:	'ТО50',
45350:	'ТО50',
45400:	'ТО50',
45450:	'ТО50',
45500:	'ТО500',
45550:	'ТО50',
45600:	'ТО50',
45650:	'ТО50',
45700:	'ТО50',
45750:	'ТО250',
45800:	'ТО50',
45850:	'ТО50',
45900:	'ТО50',
45950:	'ТО50',
46000:	'ТО2000',
46050:	'ТО50',
46100:	'ТО50',
46150:	'ТО50',
46200:	'ТО50',
46250:	'ТО250',
46300:	'ТО50',
46350:	'ТО50',
46400:	'ТО50',
46450:	'ТО50',
46500:	'ТО500',
46550:	'ТО50',
46600:	'ТО50',
46650:	'ТО50',
46700:	'ТО50',
46750:	'ТО250',
46800:	'ТО50',
46850:	'ТО50',
46900:	'ТО50',
46950:	'ТО50',
47000:	'ТО1000',
47050:	'ТО50',
47100:	'ТО50',
47150:	'ТО50',
47200:	'ТО50',
47250:	'ТО250',
47300:	'ТО50',
47350:	'ТО50',
47400:	'ТО50',
47450:	'ТО50',
47500:	'ТО500',
47550:	'ТО50',
47600:	'ТО50',
47650:	'ТО50',
47700:	'ТО50',
47750:	'ТО250',
47800:	'ТО50',
47850:	'ТО50',
47900:	'ТО50',
47950:	'ТО50',
48000:	'ТО4000'

}

In [51]:
to_dict_ECD50E={
 50:"ТО50",
100:"ТО100",
150:"ТО50",
200:"ТО200",
250:"ТО50",
300:"ТО100",
350:"ТО50",
400:"ТО200",
450:"ТО50",
500:"ТО100",
550:"ТО50",
600:"ТО200",
650:"ТО50",
700:"ТО100",
750:"ТО50",
800:"ТО200",
850:"ТО50",
900:"ТО100",
950:"ТО50",
1000:"ТО1000",
1050:"ТО50",
1100:"ТО100",
1150:"ТО50",
1200:"ТО200",
1250:"ТО50",
1300:"ТО100",
1350:"ТО50",
1400:"ТО200",
1450:"ТО50",
1500:"ТО1500",
1550:"ТО50",
1600:"ТО200",
1650:"ТО50",
1700:"ТО100",
1750:"ТО50",
1800:"ТО200",
1850:"ТО50",
1900:"ТО100",
1950:"ТО50",
2000:"ТО2000",
2050:"ТО50",
2100:"ТО100",
2150:"ТО50",
2200:"ТО200",
2250:"ТО50",
2300:"ТО100",
2350:"ТО50",
2400:"ТО200",
2450:"ТО50",
2500:"ТО100",
2550:"ТО50",
2600:"ТО200",
2650:"ТО50",
2700:"ТО100",
2750:"ТО50",
2800:"ТО200",
2850:"ТО50",
2900:"ТО100",
2950:"ТО50",
3000:"ТО3000",
3050:"ТО50",
3100:"ТО100",
3150:"ТО50",
3200:"ТО200",
3250:"ТО50",
3300:"ТО100",
3350:"ТО50",
3400:"ТО200",
3450:"ТО50",
3500:"ТО100",
3550:"ТО50",
3600:"ТО200",
3650:"ТО50",
3700:"ТО100",
3750:"ТО50",
3800:"ТО200",
3850:"ТО50",
3900:"ТО100",
3950:"ТО50",
4000:"ТО2000",
4050:"ТО50",
4100:"ТО100",
4150:"ТО50",
4200:"ТО200",
4250:"ТО50",
4300:"ТО100",
4350:"ТО50",
4400:"ТО200",
4450:"ТО50",
4500:"ТО1500",
4550:"ТО50",
4600:"ТО200",
4650:"ТО50",
4700:"ТО100",
4750:"ТО50",
4800:"ТО200",
4850:"ТО50",
4900:"ТО100",
4950:"ТО50",
5000:"ТО1000",
5050:"ТО50",
5100:"ТО100",
5150:"ТО50",
5200:"ТО200",
5250:"ТО50",
5300:"ТО100",
5350:"ТО50",
5400:"ТО200",
5450:"ТО50",
5500:"ТО100",
5550:"ТО50",
5600:"ТО200",
5650:"ТО50",
5700:"ТО100",
5750:"ТО50",
5800:"ТО200",
5850:"ТО50",
5900:"ТО100",
5950:"ТО50",
6000:"ТО2000/3000",
6050:"ТО50",
6100:"ТО100",
6150:"ТО50",
6200:"ТО200",
6250:"ТО50",
6300:"ТО100",
6350:"ТО50",
6400:"ТО200",
6450:"ТО50",
6500:"ТО100",
6550:"ТО50",
6600:"ТО200",
6650:"ТО50",
6700:"ТО100",
6750:"ТО50",
6800:"ТО200",
6850:"ТО50",
6900:"ТО100",
6950:"ТО50",
7000:"ТО1000",
7050:"ТО50",
7100:"ТО100",
7150:"ТО50",
7200:"ТО200",
7250:"ТО50",
7300:"ТО100",
7350:"ТО50",
7400:"ТО200",
7450:"ТО50",
7500:"ТО1500",
7550:"ТО50",
7600:"ТО200",
7650:"ТО50",
7700:"ТО100",
7750:"ТО50",
7800:"ТО200",
7850:"ТО50",
7900:"ТО100",
7950:"ТО50",
8000:"ТО2000",
8050:"ТО50",
8100:"ТО100",
8150:"ТО50",
8200:"ТО200",
8250:"ТО50",
8300:"ТО100",
8350:"ТО50",
8400:"ТО200",
8450:"ТО50",
8500:"ТО100",
8550:"ТО50",
8600:"ТО200",
8650:"ТО50",
8700:"ТО100",
8750:"ТО50",
8800:"ТО200",
8850:"ТО50",
8900:"ТО100",
8950:"ТО50",
9000:"ТО3000",
9050:"ТО50",
9100:"ТО100",
9150:"ТО50",
9200:"ТО200",
9250:"ТО50",
9300:"ТО100",
9350:"ТО50",
9400:"ТО200",
9450:"ТО50",
9500:"ТО100",
9550:"ТО50",
9600:"ТО200",
9650:"ТО50",
9700:"ТО100",
9750:"ТО50",
9800:"ТО200",
9850:"ТО50",
9900:"ТО100",
9950:"ТО50",
10000:"ТО2000",
10050:"ТО50",
10100:"ТО100",
10150:"ТО50",
10200:"ТО200",
10250:"ТО50",
10300:"ТО100",
10350:"ТО50",
10400:"ТО200",
10450:"ТО50",
10500:"ТО1500",
10550:"ТО50",
10600:"ТО200",
10650:"ТО50",
10700:"ТО100",
10750:"ТО50",
10800:"ТО200",
10850:"ТО50",
10900:"ТО100",
10950:"ТО50",
11000:"ТО1000",
11050:"ТО50",
11100:"ТО100",
11150:"ТО50",
11200:"ТО200",
11250:"ТО50",
11300:"ТО100",
11350:"ТО50",
11400:"ТО200",
11450:"ТО50",
11500:"ТО100",
11550:"ТО50",
11600:"ТО200",
11650:"ТО50",
11700:"ТО100",
11750:"ТО50",
11800:"ТО200",
11850:"ТО50",
11900:"ТО100",
11950:"ТО50",
12000:"ТО2000/3000",
12050:"ТО50",
12100:"ТО100",
12150:"ТО50",
12200:"ТО200",
12250:"ТО50",
12300:"ТО100",
12350:"ТО50",
12400:"ТО200",
12450:"ТО50",
12500:"ТО100",
12550:"ТО50",
12600:"ТО200",
12650:"ТО50",
12700:"ТО100",
12750:"ТО50",
12800:"ТО200",
12850:"ТО50",
12900:"ТО100",
12950:"ТО50",
13000:"ТО1000",
13050:"ТО50",
13100:"ТО100",
13150:"ТО50",
13200:"ТО200",
13250:"ТО50",
13300:"ТО100",
13350:"ТО50",
13400:"ТО200",
13450:"ТО50",
13500:"ТО1500",
13550:"ТО50",
13600:"ТО200",
13650:"ТО50",
13700:"ТО100",
13750:"ТО50",
13800:"ТО200",
13850:"ТО50",
13900:"ТО100",
13950:"ТО50",
14000:"ТО2000",
14050:"ТО50",
14100:"ТО100",
14150:"ТО50",
14200:"ТО200",
14250:"ТО50",
14300:"ТО100",
14350:"ТО50",
14400:"ТО200",
14450:"ТО50",
14500:"ТО100",
14550:"ТО50",
14600:"ТО200",
14650:"ТО50",
14700:"ТО100",
14750:"ТО50",
14800:"ТО200",
14850:"ТО50",
14900:"ТО100",
14950:"ТО50",
15000:"ТО3000",
15050:"ТО50",
15100:"ТО100",
15150:"ТО50",
15200:"ТО200",
15250:"ТО50",
15300:"ТО100",
15350:"ТО50",
15400:"ТО200",
15450:"ТО50",
15500:"ТО100",
15550:"ТО50",
15600:"ТО200",
15650:"ТО50",
15700:"ТО100",
15750:"ТО50",
15800:"ТО200",
15850:"ТО50",
15900:"ТО100",
15950:"ТО50",
16000:"ТО2000",
16050:"ТО50",
16100:"ТО100",
16150:"ТО50",
16200:"ТО200",
16250:"ТО50",
16300:"ТО100",
16350:"ТО50",
16400:"ТО200",
16450:"ТО50",
16500:"ТО1500",
16550:"ТО50",
16600:"ТО200",
16650:"ТО50",
16700:"ТО100",
16750:"ТО50",
16800:"ТО200",
16850:"ТО50",
16900:"ТО100",
16950:"ТО50",
17000:"ТО1000",
17050:"ТО50",
17100:"ТО100",
17150:"ТО50",
17200:"ТО200",
17250:"ТО50",
17300:"ТО100",
17350:"ТО50",
17400:"ТО200",
17450:"ТО50",
17500:"ТО100",
17550:"ТО50",
17600:"ТО200",
17650:"ТО50",
17700:"ТО100",
17750:"ТО50",
17800:"ТО200",
17850:"ТО50",
17900:"ТО100",
17950:"ТО50",
18000:"ТО2000/3000",
18050:"ТО50",
18100:"ТО100",
18150:"ТО50",
18200:"ТО200",
18250:"ТО50",
18300:"ТО100",
18350:"ТО50",
18400:"ТО200",
18450:"ТО50",
18500:"ТО100",
18550:"ТО50",
18600:"ТО200",
18650:"ТО50",
18700:"ТО100",
18750:"ТО50",
18800:"ТО200",
18850:"ТО50",
18900:"ТО100",
18950:"ТО50",
19000:"ТО1000",
19050:"ТО50",
19100:"ТО100",
19150:"ТО50",
19200:"ТО200",
19250:"ТО50",
19300:"ТО100",
19350:"ТО50",
19400:"ТО200",
19450:"ТО50",
19500:"ТО1500",
19550:"ТО50",
19600:"ТО200",
19650:"ТО50",
19700:"ТО100",
19750:"ТО50",
19800:"ТО200",
19850:"ТО50",
19900:"ТО100",
19950:"ТО50",
20000:"ТО2000",
20050:"ТО50",
20100:"ТО100",
20150:"ТО50",
20200:"ТО200",
20250:"ТО50",
20300:"ТО100",
20350:"ТО50",
20400:"ТО200",
20450:"ТО50",
20500:"ТО100",
20550:"ТО50",
20600:"ТО200",
20650:"ТО50",
20700:"ТО100",
20750:"ТО50",
20800:"ТО200",
20850:"ТО50",
20900:"ТО100",
20950:"ТО50",
21000:"ТО3000",
21050:"ТО50",
21100:"ТО100",
21150:"ТО50",
21200:"ТО200",
21250:"ТО50",
21300:"ТО100",
21350:"ТО50",
21400:"ТО200",
21450:"ТО50",
21500:"ТО100",
21550:"ТО50",
21600:"ТО200",
21650:"ТО50",
21700:"ТО100",
21750:"ТО50",
21800:"ТО200",
21850:"ТО50",
21900:"ТО100",
21950:"ТО50",
22000:"ТО2000",
22050:"ТО50",
22100:"ТО100",
22150:"ТО50",
22200:"ТО200",
22250:"ТО50",
22300:"ТО100",
22350:"ТО50",
22400:"ТО200",
22450:"ТО50",
22500:"ТО1500",
22550:"ТО50",
22600:"ТО200",
22650:"ТО50",
22700:"ТО100",
22750:"ТО50",
22800:"ТО200",
22850:"ТО50",
22900:"ТО100",
22950:"ТО50",
23000:"ТО1000",
23050:"ТО50",
23100:"ТО100",
23150:"ТО50",
23200:"ТО200",
23250:"ТО50",
23300:"ТО100",
23350:"ТО50",
23400:"ТО200",
23450:"ТО50",
23500:"ТО100",
23550:"ТО50",
23600:"ТО200",
23650:"ТО50",
23700:"ТО100",
23750:"ТО50",
23800:"ТО200",
23850:"ТО50",
23900:"ТО100",
23950:"ТО50",
24000:"ТО2000/3000",
24050:"ТО50",
24100:"ТО100",
24150:"ТО50",
24200:"ТО200",
24250:"ТО50",
24300:"ТО100",
24350:"ТО50",
24400:"ТО200",
24450:"ТО50",
24500:"ТО100",
24550:"ТО50",
24600:"ТО200",
24650:"ТО50",
24700:"ТО100",
24750:"ТО50",
24800:"ТО200",
24850:"ТО50",
24900:"ТО100",
24950:"ТО50",
25000:"ТО1000",
25050:"ТО50",
25100:"ТО100",
25150:"ТО50",
25200:"ТО200",
25250:"ТО50",
25300:"ТО100",
25350:"ТО50",
25400:"ТО200",
25450:"ТО50",
25500:"ТО1500",
25550:"ТО50",
25600:"ТО200",
25650:"ТО50",
25700:"ТО100",
25750:"ТО50",
25800:"ТО200",
25850:"ТО50",
25900:"ТО100",
25950:"ТО50",
26000:"ТО2000",
26050:"ТО50",
26100:"ТО100",
26150:"ТО50",
26200:"ТО200",
26250:"ТО50",
26300:"ТО100",
26350:"ТО50",
26400:"ТО200",
26450:"ТО50",
26500:"ТО100",
26550:"ТО50",
26600:"ТО200",
26650:"ТО50",
26700:"ТО100",
26750:"ТО50",
26800:"ТО200",
26850:"ТО50",
26900:"ТО100",
26950:"ТО50",
27000:"ТО3000",
27050:"ТО50",
27100:"ТО100",
27150:"ТО50",
27200:"ТО200",
27250:"ТО50",
27300:"ТО100",
27350:"ТО50",
27400:"ТО200",
27450:"ТО50",
27500:"ТО100",
27550:"ТО50",
27600:"ТО200",
27650:"ТО50",
27700:"ТО100",
27750:"ТО50",
27800:"ТО200",
27850:"ТО50",
27900:"ТО100",
27950:"ТО50",
28000:"ТО2000",
28050:"ТО50",
28100:"ТО100",
28150:"ТО50",
28200:"ТО200",
28250:"ТО50",
28300:"ТО100",
28350:"ТО50",
28400:"ТО200",
28450:"ТО50",
28500:"ТО1500",
28550:"ТО50",
28600:"ТО200",
28650:"ТО50",
28700:"ТО100",
28750:"ТО50",
28800:"ТО200",
28850:"ТО50",
28900:"ТО100",
28950:"ТО50",
29000:"ТО1000",
29050:"ТО50",
29100:"ТО100",
29150:"ТО50",
29200:"ТО200",
29250:"ТО50",
29300:"ТО100",
29350:"ТО50",
29400:"ТО200",
29450:"ТО50",
29500:"ТО100",
29550:"ТО50",
29600:"ТО200",
29650:"ТО50",
29700:"ТО100",
29750:"ТО50",
29800:"ТО200",
29850:"ТО50",
29900:"ТО100",
29950:"ТО50",
30000:"ТО2000/3000",
30050:"ТО50",
30100:"ТО100",
30150:"ТО50",
30200:"ТО200",
30250:"ТО50",
30300:"ТО100",
30350:"ТО50",
30400:"ТО200",
30450:"ТО50",
30500:"ТО100",
30550:"ТО50",
30600:"ТО200",
30650:"ТО50",
30700:"ТО100",
30750:"ТО50",
30800:"ТО200",
30850:"ТО50",
30900:"ТО100",
30950:"ТО50",
31000:"ТО1000",
31050:"ТО50",
31100:"ТО100",
31150:"ТО50",
31200:"ТО200",
31250:"ТО50",
31300:"ТО100",
31350:"ТО50",
31400:"ТО200",
31450:"ТО50",
31500:"ТО1500",
31550:"ТО50",
31600:"ТО200",
31650:"ТО50",
31700:"ТО100",
31750:"ТО50",
31800:"ТО200",
31850:"ТО50",
31900:"ТО100",
31950:"ТО50",
32000:"ТО2000",
32050:"ТО50",
32100:"ТО100",
32150:"ТО50",
32200:"ТО200",
32250:"ТО50",
32300:"ТО100",
32350:"ТО50",
32400:"ТО200",
32450:"ТО50",
32500:"ТО100",
32550:"ТО50",
32600:"ТО200",
32650:"ТО50",
32700:"ТО100",
32750:"ТО50",
32800:"ТО200",
32850:"ТО50",
32900:"ТО100",
32950:"ТО50",
33000:"ТО3000",
33050:"ТО50",
33100:"ТО100",
33150:"ТО50",
33200:"ТО200",
33250:"ТО50",
33300:"ТО100",
33350:"ТО50",
33400:"ТО200",
33450:"ТО50",
33500:"ТО100",
33550:"ТО50",
33600:"ТО200",
33650:"ТО50",
33700:"ТО100",
33750:"ТО50",
33800:"ТО200",
33850:"ТО50",
33900:"ТО100",
33950:"ТО50",
34000:"ТО2000",
34050:"ТО50",
34100:"ТО100",
34150:"ТО50",
34200:"ТО200",
34250:"ТО50",
34300:"ТО100",
34350:"ТО50",
34400:"ТО200",
34450:"ТО50",
34500:"ТО1500",
34550:"ТО50",
34600:"ТО200",
34650:"ТО50",
34700:"ТО100",
34750:"ТО50",
34800:"ТО200",
34850:"ТО50",
34900:"ТО100",
34950:"ТО50",
35000:"ТО1000",
35050:"ТО50",
35100:"ТО100",
35150:"ТО50",
35200:"ТО200",
35250:"ТО50",
35300:"ТО100",
35350:"ТО50",
35400:"ТО200",
35450:"ТО50",
35500:"ТО100",
35550:"ТО50",
35600:"ТО200",
35650:"ТО50",
35700:"ТО100",
35750:"ТО50",
35800:"ТО200",
35850:"ТО50",
35900:"ТО100",
35950:"ТО50",
36000:"ТО2000/3000",
36050:"ТО50",
36100:"ТО100",
36150:"ТО50",
36200:"ТО200",
36250:"ТО50",
36300:"ТО100",
36350:"ТО50",
36400:"ТО200",
36450:"ТО50",
36500:"ТО100",
36550:"ТО50",
36600:"ТО200",
36650:"ТО50",
36700:"ТО100",
36750:"ТО50",
36800:"ТО200",
36850:"ТО50",
36900:"ТО100",
36950:"ТО50",
37000:"ТО1000",
37050:"ТО50",
37100:"ТО100",
37150:"ТО50",
37200:"ТО200",
37250:"ТО50",
37300:"ТО100",
37350:"ТО50",
37400:"ТО200",
37450:"ТО50",
37500:"ТО1500",
37550:"ТО50",
37600:"ТО200",
37650:"ТО50",
37700:"ТО100",
37750:"ТО50",
37800:"ТО200",
37850:"ТО50",
37900:"ТО100",
37950:"ТО50",
38000:"ТО2000",
38050:"ТО50",
38100:"ТО100",
38150:"ТО50",
38200:"ТО200",
38250:"ТО50",
38300:"ТО100",
38350:"ТО50",
38400:"ТО200",
38450:"ТО50",
38500:"ТО100",
38550:"ТО50",
38600:"ТО200",
38650:"ТО50",
38700:"ТО100",
38750:"ТО50",
38800:"ТО200",
38850:"ТО50",
38900:"ТО100",
38950:"ТО50",
39000:"ТО3000",
39050:"ТО50",
39100:"ТО100",
39150:"ТО50",
39200:"ТО200",
39250:"ТО50",
39300:"ТО100",
39350:"ТО50",
39400:"ТО200",
39450:"ТО50",
39500:"ТО100",
39550:"ТО50",
39600:"ТО200",
39650:"ТО50",
39700:"ТО100",
39750:"ТО50",
39800:"ТО200",
39850:"ТО50",
39900:"ТО100",
39950:"ТО50",
40000:"ТО2000",
40050:"ТО50",
40100:"ТО100",
40150:"ТО50",
40200:"ТО200",
40250:"ТО50",
40300:"ТО100",
40350:"ТО50",
40400:"ТО200",
40450:"ТО50",
40500:"ТО1500",
40550:"ТО50",
40600:"ТО200",
40650:"ТО50",
40700:"ТО100",
40750:"ТО50",
40800:"ТО200",
40850:"ТО50",
40900:"ТО100",
40950:"ТО50",
41000:"ТО1000",
41050:"ТО50",
41100:"ТО100",
41150:"ТО50",
41200:"ТО200",
41250:"ТО50",
41300:"ТО100",
41350:"ТО50",
41400:"ТО200",
41450:"ТО50",
41500:"ТО100",
41550:"ТО50",
41600:"ТО200",
41650:"ТО50",
41700:"ТО100",
41750:"ТО50",
41800:"ТО200",
41850:"ТО50",
41900:"ТО100",
41950:"ТО50",
42000:"ТО2000/3000",
42050:"ТО50",
42100:"ТО100",
42150:"ТО50",
42200:"ТО200",
42250:"ТО50",
42300:"ТО100",
42350:"ТО50",
42400:"ТО200",
42450:"ТО50",
42500:"ТО100",
42550:"ТО50",
42600:"ТО200",
42650:"ТО50",
42700:"ТО100",
42750:"ТО50",
42800:"ТО200",
42850:"ТО50",
42900:"ТО100",
42950:"ТО50",
43000:"ТО1000",
43050:"ТО50",
43100:"ТО100",
43150:"ТО50",
43200:"ТО200",
43250:"ТО50",
43300:"ТО100",
43350:"ТО50",
43400:"ТО200",
43450:"ТО50",
43500:"ТО1500",
43550:"ТО50",
43600:"ТО200",
43650:"ТО50",
43700:"ТО100",
43750:"ТО50",
43800:"ТО200",
43850:"ТО50",
43900:"ТО100",
43950:"ТО50",
44000:"ТО2000",
44050:"ТО50",
44100:"ТО100",
44150:"ТО50",
44200:"ТО200",
44250:"ТО50",
44300:"ТО100",
44350:"ТО50",
44400:"ТО200",
44450:"ТО50",
44500:"ТО100",
44550:"ТО50",
44600:"ТО200",
44650:"ТО50",
44700:"ТО100",
44750:"ТО50",
44800:"ТО200",
44850:"ТО50",
44900:"ТО100",
44950:"ТО50",
45000:"ТО3000",
45050:"ТО50",
45100:"ТО100",
45150:"ТО50",
45200:"ТО200",
45250:"ТО50",
45300:"ТО100",
45350:"ТО50",
45400:"ТО200",
45450:"ТО50",
45500:"ТО100",
45550:"ТО50",
45600:"ТО200",
45650:"ТО50",
45700:"ТО100",
45750:"ТО50",
45800:"ТО200",
45850:"ТО50",
45900:"ТО100",
45950:"ТО50",
46000:"ТО2000",
46050:"ТО50",
46100:"ТО100",
46150:"ТО50",
46200:"ТО200",
46250:"ТО50",
46300:"ТО100",
46350:"ТО50",
46400:"ТО200",
46450:"ТО50",
46500:"ТО1500",
46550:"ТО50",
46600:"ТО200",
46650:"ТО50",
46700:"ТО100",
46750:"ТО50",
46800:"ТО200",
46850:"ТО50",
46900:"ТО100",
46950:"ТО50",
47000:"ТО1000",
47050:"ТО50",
47100:"ТО100",
47150:"ТО50",
47200:"ТО200",
47250:"ТО50",
47300:"ТО100",
47350:"ТО50",
47400:"ТО200",
47450:"ТО50",
47500:"ТО100",
47550:"ТО50",
47600:"ТО200",
47650:"ТО50",
47700:"ТО100",
47750:"ТО50",
47800:"ТО200",
47850:"ТО50",
47900:"ТО100",
47950:"ТО50",
48000:"ТО2000/3000"


}

In [52]:
to_dict_7547={
    50:	'',
    100:	'',
    150:	'',
    200:	'',
    250:	'ТО250',
    300:	'',
    350:	'',
    400:	'',
    450:	'',
    500:	'ТО500',
    550:	'',
    600:	'',
    650:	'',
    700:	'',
    750:	'ТО250',
    800:	'',
    850:	'',
    900:	'',
    950:	'',
    1000:	'ТО1000',
    1050:	'',
    1100:	'',
    1150:	'',
    1200:	'',
    1250:	'ТО250',
    1300:	'',
    1350:	'',
    1400:	'',
    1450:	'',
    1500:	'ТО1500',
    1550:	'',
    1600:	'',
    1650:	'',
    1700:	'',
    1750:	'ТО250',
    1800:	'',
    1850:	'',
    1900:	'',
    1950:	'',
    2000:	'ТО2000',
    2050:	'',
    2100:	'',
    2150:	'',
    2200:	'',
    2250:	'ТО250',
    2300:	'',
    2350:	'',
    2400:	'',
    2450:	'',
    2500:	'ТО500',
    2550:	'',
    2600:	'',
    2650:	'',
    2700:	'',
    2750:	'ТО250',
    2800:	'',
    2850:	'',
    2900:	'',
    2950:	'',
    3000:	'ТО3000',
    3050:	'',
    3100:	'',
    3150:	'',
    3200:	'',
    3250:	'ТО250',
    3300:	'',
    3350:	'',
    3400:	'',
    3450:	'',
    3500:	'ТО500',
    3550:	'',
    3600:	'',
    3650:	'',
    3700:	'',
    3750:	'ТО250',
    3800:	'',
    3850:	'',
    3900:	'',
    3950:	'',
    4000:	'ТО4000',
    4050:	'',
    4100:	'',
    4150:	'',
    4200:	'',
    4250:	'ТО250',
    4300:	'',
    4350:	'',
    4400:	'',
    4450:	'',
    4500:	'ТО1500',
    4550:	'',
    4600:	'',
    4650:	'',
    4700:	'',
    4750:	'ТО250',
    4800:	'',
    4850:	'',
    4900:	'',
    4950:	'',
    5000:	'ТО1000',
    5050:	'',
    5100:	'',
    5150:	'',
    5200:	'',
    5250:	'ТО250',
    5300:	'',
    5350:	'',
    5400:	'',
    5450:	'',
    5500:	'ТО500',
    5550:	'',
    5600:	'',
    5650:	'',
    5700:	'',
    5750:	'ТО250',
    5800:	'',
    5850:	'',
    5900:	'',
    5950:	'',
    6000:	'ТО2000/3000',
    6050:	'',
    6100:	'',
    6150:	'',
    6200:	'',
    6250:	'ТО250',
    6300:	'',
    6350:	'',
    6400:	'',
    6450:	'',
    6500:	'ТО500',
    6550:	'',
    6600:	'',
    6650:	'',
    6700:	'',
    6750:	'ТО250',
    6800:	'',
    6850:	'',
    6900:	'',
    6950:	'',
    7000:	'ТО1000',
    7050:	'',
    7100:	'',
    7150:	'',
    7200:	'',
    7250:	'ТО250',
    7300:	'',
    7350:	'',
    7400:	'',
    7450:	'',
    7500:	'ТО1500',
    7550:	'',
    7600:	'',
    7650:	'',
    7700:	'',
    7750:	'ТО250',
    7800:	'',
    7850:	'',
    7900:	'',
    7950:	'',
    8000:	'ТО4000',
    8050:	'',
    8100:	'',
    8150:	'',
    8200:	'',
    8250:	'ТО250',
    8300:	'',
    8350:	'',
    8400:	'',
    8450:	'',
    8500:	'ТО500',
    8550:	'',
    8600:	'',
    8650:	'',
    8700:	'',
    8750:	'ТО250',
    8800:	'',
    8850:	'',
    8900:	'',
    8950:	'',
    9000:	'ТО3000',
    9050:	'',
    9100:	'',
    9150:	'',
    9200:	'',
    9250:	'ТО250',
    9300:	'',
    9350:	'',
    9400:	'',
    9450:	'',
    9500:	'ТО500',
    9550:	'',
    9600:	'',
    9650:	'',
    9700:	'',
    9750:	'ТО250',
    9800:	'',
    9850:	'',
    9900:	'',
    9950:	'',
    10000:	'ТО2000',
    10050:	'',
    10100:	'',
    10150:	'',
    10200:	'',
    10250:	'ТО250',
    10300:	'',
    10350:	'',
    10400:	'',
    10450:	'',
    10500:	'ТО1500',
    10550:	'',
    10600:	'',
    10650:	'',
    10700:	'',
    10750:	'ТО250',
    10800:	'',
    10850:	'',
    10900:	'',
    10950:	'',
    11000:	'ТО1000',
    11050:	'',
    11100:	'',
    11150:	'',
    11200:	'',
    11250:	'ТО250',
    11300:	'',
    11350:	'',
    11400:	'',
    11450:	'',
    11500:	'ТО500',
    11550:	'',
    11600:	'',
    11650:	'',
    11700:	'',
    11750:	'ТО250',
    11800:	'',
    11850:	'',
    11900:	'',
    11950:	'',
    12000:	'ТО1500/4000',
    12050:	'',
    12100:	'',
    12150:	'',
    12200:	'',
    12250:	'ТО250',
    12300:	'',
    12350:	'',
    12400:	'',
    12450:	'',
    12500:	'ТО500',
    12550:	'',
    12600:	'',
    12650:	'',
    12700:	'',
    12750:	'ТО250',
    12800:	'',
    12850:	'',
    12900:	'',
    12950:	'',
    13000:	'ТО1000',
    13050:	'',
    13100:	'',
    13150:	'',
    13200:	'',
    13250:	'ТО250',
    13300:	'',
    13350:	'',
    13400:	'',
    13450:	'',
    13500:	'ТО1500',
    13550:	'',
    13600:	'',
    13650:	'',
    13700:	'',
    13750:	'ТО250',
    13800:	'',
    13850:	'',
    13900:	'',
    13950:	'',
    14000:	'ТО2000',
    14050:	'',
    14100:	'',
    14150:	'',
    14200:	'',
    14250:	'ТО250',
    14300:	'',
    14350:	'',
    14400:	'',
    14450:	'',
    14500:	'ТО500',
    14550:	'',
    14600:	'',
    14650:	'',
    14700:	'',
    14750:	'ТО250',
    14800:	'',
    14850:	'',
    14900:	'',
    14950:	'',
    15000:	'ТО3000',
    15050:	'',
    15100:	'',
    15150:	'',
    15200:	'',
    15250:	'ТО250',
    15300:	'',
    15350:	'',
    15400:	'',
    15450:	'',
    15500:	'ТО500',
    15550:	'',
    15600:	'',
    15650:	'',
    15700:	'',
    15750:	'ТО250',
    15800:	'',
    15850:	'',
    15900:	'',
    15950:	'',
    16000:	'ТО4000',
    16050:	'',
    16100:	'',
    16150:	'',
    16200:	'',
    16250:	'ТО250',
    16300:	'',
    16350:	'',
    16400:	'',
    16450:	'',
    16500:	'ТО1500',
    16550:	'',
    16600:	'',
    16650:	'',
    16700:	'',
    16750:	'ТО250',
    16800:	'',
    16850:	'',
    16900:	'',
    16950:	'',
    17000:	'ТО1000',
    17050:	'',
    17100:	'',
    17150:	'',
    17200:	'',
    17250:	'ТО250',
    17300:	'',
    17350:	'',
    17400:	'',
    17450:	'',
    17500:	'ТО500',
    17550:	'',
    17600:	'',
    17650:	'',
    17700:	'',
    17750:	'ТО250',
    17800:	'',
    17850:	'',
    17900:	'',
    17950:	'',
    18000:	'ТО2000/3000',
    18050:	'',
    18100:	'',
    18150:	'',
    18200:	'',
    18250:	'ТО250',
    18300:	'',
    18350:	'',
    18400:	'',
    18450:	'',
    18500:	'ТО500',
    18550:	'',
    18600:	'',
    18650:	'',
    18700:	'',
    18750:	'ТО250',
    18800:	'',
    18850:	'',
    18900:	'',
    18950:	'',
    19000:	'ТО1000',
    19050:	'',
    19100:	'',
    19150:	'',
    19200:	'',
    19250:	'ТО250',
    19300:	'',
    19350:	'',
    19400:	'',
    19450:	'',
    19500:	'ТО1500',
    19550:	'',
    19600:	'',
    19650:	'',
    19700:	'',
    19750:	'ТО250',
    19800:	'',
    19850:	'',
    19900:	'',
    19950:	'',
    20000:	'ТО4000',
    20050:	'',
    20100:	'',
    20150:	'',
    20200:	'',
    20250:	'ТО250',
    20300:	'',
    20350:	'',
    20400:	'',
    20450:	'',
    20500:	'ТО500',
    20550:	'',
    20600:	'',
    20650:	'',
    20700:	'',
    20750:	'ТО250',
    20800:	'',
    20850:	'',
    20900:	'',
    20950:	'',
    21000:	'ТО3000',
    21050:	'',
    21100:	'',
    21150:	'',
    21200:	'',
    21250:	'ТО250',
    21300:	'',
    21350:	'',
    21400:	'',
    21450:	'',
    21500:	'ТО500',
    21550:	'',
    21600:	'',
    21650:	'',
    21700:	'',
    21750:	'ТО250',
    21800:	'',
    21850:	'',
    21900:	'',
    21950:	'',
    22000:	'ТО2000',
    22050:	'',
    22100:	'',
    22150:	'',
    22200:	'',
    22250:	'ТО250',
    22300:	'',
    22350:	'',
    22400:	'',
    22450:	'',
    22500:	'ТО1500',
    22550:	'',
    22600:	'',
    22650:	'',
    22700:	'',
    22750:	'ТО250',
    22800:	'',
    22850:	'',
    22900:	'',
    22950:	'',
    23000:	'ТО1000',
    23050:	'',
    23100:	'',
    23150:	'',
    23200:	'',
    23250:	'ТО250',
    23300:	'',
    23350:	'',
    23400:	'',
    23450:	'',
    23500:	'ТО500',
    23550:	'',
    23600:	'',
    23650:	'',
    23700:	'',
    23750:	'ТО250',
    23800:	'',
    23850:	'',
    23900:	'',
    23950:	'',
    24000:	'ТО1500/4000',
    24050:	'',
    24100:	'',
    24150:	'',
    24200:	'',
    24250:	'ТО250',
    24300:	'',
    24350:	'',
    24400:	'',
    24450:	'',
    24500:	'ТО500',
    24550:	'',
    24600:	'',
    24650:	'',
    24700:	'',
    24750:	'ТО250',
    24800:	'',
    24850:	'',
    24900:	'',
    24950:	'',
    25000:	'ТО1000',
    25050:	'',
    25100:	'',
    25150:	'',
    25200:	'',
    25250:	'ТО250',
    25300:	'',
    25350:	'',
    25400:	'',
    25450:	'',
    25500:	'ТО1500',
    25550:	'',
    25600:	'',
    25650:	'',
    25700:	'',
    25750:	'ТО250',
    25800:	'',
    25850:	'',
    25900:	'',
    25950:	'',
    26000:	'ТО2000',
    26050:	'',
    26100:	'',
    26150:	'',
    26200:	'',
    26250:	'ТО250',
    26300:	'',
    26350:	'',
    26400:	'',
    26450:	'',
    26500:	'ТО500',
    26550:	'',
    26600:	'',
    26650:	'',
    26700:	'',
    26750:	'ТО250',
    26800:	'',
    26850:	'',
    26900:	'',
    26950:	'',
    27000:	'ТО3000',
    27050:	'',
    27100:	'',
    27150:	'',
    27200:	'',
    27250:	'ТО250',
    27300:	'',
    27350:	'',
    27400:	'',
    27450:	'',
    27500:	'ТО500',
    27550:	'',
    27600:	'',
    27650:	'',
    27700:	'',
    27750:	'ТО250',
    27800:	'',
    27850:	'',
    27900:	'',
    27950:	'',
    28000:	'ТО4000',
    28050:	'',
    28100:	'',
    28150:	'',
    28200:	'',
    28250:	'ТО250',
    28300:	'',
    28350:	'',
    28400:	'',
    28450:	'',
    28500:	'ТО1500',
    28550:	'',
    28600:	'',
    28650:	'',
    28700:	'',
    28750:	'ТО250',
    28800:	'',
    28850:	'',
    28900:	'',
    28950:	'',
    29000:	'ТО1000',
    29050:	'',
    29100:	'',
    29150:	'',
    29200:	'',
    29250:	'ТО250',
    29300:	'',
    29350:	'',
    29400:	'',
    29450:	'',
    29500:	'ТО500',
    29550:	'',
    29600:	'',
    29650:	'',
    29700:	'',
    29750:	'ТО250',
    29800:	'',
    29850:	'',
    29900:	'',
    29950:	'',
    30000:	'ТО2000/3000',
    30050:	'',
    30100:	'',
    30150:	'',
    30200:	'',
    30250:	'ТО250',
    30300:	'',
    30350:	'',
    30400:	'',
    30450:	'',
    30500:	'ТО500',
    30550:	'',
    30600:	'',
    30650:	'',
    30700:	'',
    30750:	'ТО250',
    30800:	'',
    30850:	'',
    30900:	'',
    30950:	'',
    31000:	'ТО1000',
    31050:	'',
    31100:	'',
    31150:	'',
    31200:	'',
    31250:	'ТО250',
    31300:	'',
    31350:	'',
    31400:	'',
    31450:	'',
    31500:	'ТО1500',
    31550:	'',
    31600:	'',
    31650:	'',
    31700:	'',
    31750:	'ТО250',
    31800:	'',
    31850:	'',
    31900:	'',
    31950:	'',
    32000:	'ТО4000',
    32050:	'',
    32100:	'',
    32150:	'',
    32200:	'',
    32250:	'ТО250',
    32300:	'',
    32350:	'',
    32400:	'',
    32450:	'',
    32500:	'ТО500',
    32550:	'',
    32600:	'',
    32650:	'',
    32700:	'',
    32750:	'ТО250',
    32800:	'',
    32850:	'',
    32900:	'',
    32950:	'',
    33000:	'ТО3000',
    33050:	'',
    33100:	'',
    33150:	'',
    33200:	'',
    33250:	'ТО250',
    33300:	'',
    33350:	'',
    33400:	'',
    33450:	'',
    33500:	'ТО500',
    33550:	'',
    33600:	'',
    33650:	'',
    33700:	'',
    33750:	'ТО250',
    33800:	'',
    33850:	'',
    33900:	'',
    33950:	'',
    34000:	'ТО2000',
    34050:	'',
    34100:	'',
    34150:	'',
    34200:	'',
    34250:	'ТО250',
    34300:	'',
    34350:	'',
    34400:	'',
    34450:	'',
    34500:	'ТО1500',
    34550:	'',
    34600:	'',
    34650:	'',
    34700:	'',
    34750:	'ТО250',
    34800:	'',
    34850:	'',
    34900:	'',
    34950:	'',
    35000:	'ТО1000',
    35050:	'',
    35100:	'',
    35150:	'',
    35200:	'',
    35250:	'ТО250',
    35300:	'',
    35350:	'',
    35400:	'',
    35450:	'',
    35500:	'ТО500',
    35550:	'',
    35600:	'',
    35650:	'',
    35700:	'',
    35750:	'ТО250',
    35800:	'',
    35850:	'',
    35900:	'',
    35950:	'',
    36000:	'ТО1500/4000',
    36050:	'',
    36100:	'',
    36150:	'',
    36200:	'',
    36250:	'ТО250',
    36300:	'',
    36350:	'',
    36400:	'',
    36450:	'',
    36500:	'ТО500',
    36550:	'',
    36600:	'',
    36650:	'',
    36700:	'',
    36750:	'ТО250',
    36800:	'',
    36850:	'',
    36900:	'',
    36950:	'',
    37000:	'ТО1000',
    37050:	'',
    37100:	'',
    37150:	'',
    37200:	'',
    37250:	'ТО250',
    37300:	'',
    37350:	'',
    37400:	'',
    37450:	'',
    37500:	'ТО1500',
    37550:	'',
    37600:	'',
    37650:	'',
    37700:	'',
    37750:	'ТО250',
    37800:	'',
    37850:	'',
    37900:	'',
    37950:	'',
    38000:	'ТО2000',
    38050:	'',
    38100:	'',
    38150:	'',
    38200:	'',
    38250:	'ТО250',
    38300:	'',
    38350:	'',
    38400:	'',
    38450:	'',
    38500:	'ТО500',
    38550:	'',
    38600:	'',
    38650:	'',
    38700:	'',
    38750:	'ТО250',
    38800:	'',
    38850:	'',
    38900:	'',
    38950:	'',
    39000:	'ТО3000',
    39050:	'',
    39100:	'',
    39150:	'',
    39200:	'',
    39250:	'ТО250',
    39300:	'',
    39350:	'',
    39400:	'',
    39450:	'',
    39500:	'ТО500',
    39550:	'',
    39600:	'',
    39650:	'',
    39700:	'',
    39750:	'ТО250',
    39800:	'',
    39850:	'',
    39900:	'',
    39950:	'',
    40000:	'ТО4000',
    40050:	'',
    40100:	'',
    40150:	'',
    40200:	'',
    40250:	'ТО250',
    40300:	'',
    40350:	'',
    40400:	'',
    40450:	'',
    40500:	'ТО1500',
    40550:	'',
    40600:	'',
    40650:	'',
    40700:	'',
    40750:	'ТО250',
    40800:	'',
    40850:	'',
    40900:	'',
    40950:	'',
    41000:	'ТО1000',
    41050:	'',
    41100:	'',
    41150:	'',
    41200:	'',
    41250:	'ТО250',
    41300:	'',
    41350:	'',
    41400:	'',
    41450:	'',
    41500:	'ТО500',
    41550:	'',
    41600:	'',
    41650:	'',
    41700:	'',
    41750:	'ТО250',
    41800:	'',
    41850:	'',
    41900:	'',
    41950:	'',
    42000:	'ТО2000/3000',
    42050:	'',
    42100:	'',
    42150:	'',
    42200:	'',
    42250:	'ТО250',
    42300:	'',
    42350:	'',
    42400:	'',
    42450:	'',
    42500:	'ТО500',
    42550:	'',
    42600:	'',
    42650:	'',
    42700:	'',
    42750:	'ТО250',
    42800:	'',
    42850:	'',
    42900:	'',
    42950:	'',
    43000:	'ТО1000',
    43050:	'',
    43100:	'',
    43150:	'',
    43200:	'',
    43250:	'ТО250',
    43300:	'',
    43350:	'',
    43400:	'',
    43450:	'',
    43500:	'ТО1500',
    43550:	'',
    43600:	'',
    43650:	'',
    43700:	'',
    43750:	'ТО250',
    43800:	'',
    43850:	'',
    43900:	'',
    43950:	'',
    44000:	'ТО4000',
    44050:	'',
    44100:	'',
    44150:	'',
    44200:	'',
    44250:	'ТО250',
    44300:	'',
    44350:	'',
    44400:	'',
    44450:	'',
    44500:	'ТО500',
    44550:	'',
    44600:	'',
    44650:	'',
    44700:	'',
    44750:	'ТО250',
    44800:	'',
    44850:	'',
    44900:	'',
    44950:	'',
    45000:	'ТО3000',
    45050:	'',
    45100:	'',
    45150:	'',
    45200:	'',
    45250:	'ТО250',
    45300:	'',
    45350:	'',
    45400:	'',
    45450:	'',
    45500:	'ТО500',
    45550:	'',
    45600:	'',
    45650:	'',
    45700:	'',
    45750:	'ТО250',
    45800:	'',
    45850:	'',
    45900:	'',
    45950:	'',
    46000:	'ТО2000',
    46050:	'',
    46100:	'',
    46150:	'',
    46200:	'',
    46250:	'ТО250',
    46300:	'',
    46350:	'',
    46400:	'',
    46450:	'',
    46500:	'ТО1500',
    46550:	'',
    46600:	'',
    46650:	'',
    46700:	'',
    46750:	'ТО250',
    46800:	'',
    46850:	'',
    46900:	'',
    46950:	'',
    47000:	'ТО1000',
    47050:	'',
    47100:	'',
    47150:	'',
    47200:	'',
    47250:	'ТО250',
    47300:	'',
    47350:	'',
    47400:	'',
    47450:	'',
    47500:	'То500',
    47550:	'',
    47600:	'',
    47650:	'',
    47700:	'',
    47750:	'ТО250',
    47800:	'',
    47850:	'',
    47900:	'',
    47950:	'',
    48000:	'ТО1500/4000'




}

In [53]:
to_dict_WD={
    50:	'ТО50',
100:	'ТО100',
150:	'ТО50',
200:	'ТО100',
250:	'ТО250',
300:	'ТО100',
350:	'ТО100',
400:	'ТО100',
450:	'ТО50',
500:	'ТО500',
550:	'ТО50',
600:	'ТО100',
650:	'ТО50',
700:	'ТО100',
750:	'ТО250',
800:	'ТО100',
850:	'ТО100',
900:	'ТО100',
950:	'ТО50',
1000:	'ТО1000',
1050:	'ТО50',
1100:	'ТО100',
1150:	'ТО50',
1200:	'ТО100',
1250:	'ТО250',
1300:	'ТО100',
1350:	'ТО100',
1400:	'ТО100',
1450:	'ТО50',
1500:	'ТО500',
1550:	'ТО50',
1600:	'ТО100',
1650:	'ТО50',
1700:	'ТО100',
1750:	'ТО250',
1800:	'ТО100',
1850:	'ТО100',
1900:	'ТО100',
1950:	'ТО50',
2000:	'ТО2000',
2050:	'ТО50',
2100:	'ТО100',
2150:	'ТО50',
2200:	'ТО100',
2250:	'ТО250',
2300:	'ТО100',
2350:	'ТО100',
2400:	'ТО100',
2450:	'ТО50',
2500:	'ТО500',
2550:	'ТО50',
2600:	'ТО100',
2650:	'ТО50',
2700:	'ТО100',
2750:	'ТО250',
2800:	'ТО100',
2850:	'ТО100',
2900:	'ТО100',
2950:	'ТО50',
3000:	'ТО1000',
3050:	'ТО50',
3100:	'ТО100',
3150:	'ТО50',
3200:	'ТО100',
3250:	'ТО250',
3300:	'ТО100',
3350:	'ТО100',
3400:	'ТО100',
3450:	'ТО50',
3500:	'ТО500',
3550:	'ТО50',
3600:	'ТО100',
3650:	'ТО50',
3700:	'ТО100',
3750:	'ТО250',
3800:	'ТО100',
3850:	'ТО100',
3900:	'ТО100',
3950:	'ТО50',
4000:	'ТО4000',
4050:	'ТО50',
4100:	'ТО100',
4150:	'ТО50',
4200:	'ТО100',
4250:	'ТО250',
4300:	'ТО100',
4350:	'ТО100',
4400:	'ТО100',
4450:	'ТО50',
4500:	'ТО500',
4550:	'ТО50',
4600:	'ТО100',
4650:	'ТО50',
4700:	'ТО100',
4750:	'ТО250',
4800:	'ТО100',
4850:	'ТО100',
4900:	'ТО100',
4950:	'ТО50',
5000:	'ТО1000',
5050:	'ТО50',
5100:	'ТО100',
5150:	'ТО50',
5200:	'ТО100',
5250:	'ТО250',
5300:	'ТО100',
5350:	'ТО100',
5400:	'ТО100',
5450:	'ТО50',
5500:	'ТО500',
5550:	'ТО50',
5600:	'ТО100',
5650:	'ТО50',
5700:	'ТО100',
5750:	'ТО250',
5800:	'ТО100',
5850:	'ТО100',
5900:	'ТО100',
5950:	'ТО50',
6000:	'ТО2000',
6050:	'ТО50',
6100:	'ТО100',
6150:	'ТО50',
6200:	'ТО100',
6250:	'ТО250',
6300:	'ТО100',
6350:	'ТО100',
6400:	'ТО100',
6450:	'ТО50',
6500:	'ТО500',
6550:	'ТО50',
6600:	'ТО100',
6650:	'ТО50',
6700:	'ТО100',
6750:	'ТО250',
6800:	'ТО100',
6850:	'ТО100',
6900:	'ТО100',
6950:	'ТО50',
7000:	'ТО1000',
7050:	'ТО50',
7100:	'ТО100',
7150:	'ТО50',
7200:	'ТО100',
7250:	'ТО250',
7300:	'ТО100',
7350:	'ТО100',
7400:	'ТО100',
7450:	'ТО50',
7500:	'ТО500',
7550:	'ТО50',
7600:	'ТО100',
7650:	'ТО50',
7700:	'ТО100',
7750:	'ТО250',
7800:	'ТО100',
7850:	'ТО100',
7900:	'ТО100',
7950:	'ТО50',
8000:	'ТО8000',
8050:	'ТО50',
8100:	'ТО100',
8150:	'ТО50',
8200:	'ТО100',
8250:	'ТО250',
8300:	'ТО100',
8350:	'ТО100',
8400:	'ТО100',
8450:	'ТО50',
8500:	'ТО500',
8550:	'ТО50',
8600:	'ТО100',
8650:	'ТО50',
8700:	'ТО100',
8750:	'ТО250',
8800:	'ТО100',
8850:	'ТО100',
8900:	'ТО100',
8950:	'ТО50',
9000:	'ТО1000',
9050:	'ТО50',
9100:	'ТО100',
9150:	'ТО50',
9200:	'ТО100',
9250:	'ТО250',
9300:	'ТО100',
9350:	'ТО100',
9400:	'ТО100',
9450:	'ТО50',
9500:	'ТО500',
9550:	'ТО50',
9600:	'ТО100',
9650:	'ТО50',
9700:	'ТО100',
9750:	'ТО250',
9800:	'ТО100',
9850:	'ТО100',
9900:	'ТО100',
9950:	'ТО50',
10000:	'ТО2000',
10050:	'ТО50',
10100:	'ТО100',
10150:	'ТО50',
10200:	'ТО100',
10250:	'ТО250',
10300:	'ТО100',
10350:	'ТО100',
10400:	'ТО100',
10450:	'ТО50',
10500:	'ТО500',
10550:	'ТО50',
10600:	'ТО100',
10650:	'ТО50',
10700:	'ТО100',
10750:	'ТО250',
10800:	'ТО100',
10850:	'ТО100',
10900:	'ТО100',
10950:	'ТО50',
11000:	'ТО1000',
11050:	'ТО50',
11100:	'ТО100',
11150:	'ТО50',
11200:	'ТО100',
11250:	'ТО250',
11300:	'ТО100',
11350:	'ТО100',
11400:	'ТО100',
11450:	'ТО50',
11500:	'ТО500',
11550:	'ТО50',
11600:	'ТО100',
11650:	'ТО50',
11700:	'ТО100',
11750:	'ТО250',
11800:	'ТО100',
11850:	'ТО100',
11900:	'ТО100',
11950:	'ТО50',
12000:	'ТО4000',
12050:	'ТО50',
12100:	'ТО100',
12150:	'ТО50',
12200:	'ТО100',
12250:	'ТО250',
12300:	'ТО100',
12350:	'ТО100',
12400:	'ТО100',
12450:	'ТО50',
12500:	'ТО500',
12550:	'ТО50',
12600:	'ТО100',
12650:	'ТО50',
12700:	'ТО100',
12750:	'ТО250',
12800:	'ТО100',
12850:	'ТО100',
12900:	'ТО100',
12950:	'ТО50',
13000:	'ТО1000',
13050:	'ТО50',
13100:	'ТО100',
13150:	'ТО50',
13200:	'ТО100',
13250:	'ТО250',
13300:	'ТО100',
13350:	'ТО100',
13400:	'ТО100',
13450:	'ТО50',
13500:	'ТО500',
13550:	'ТО50',
13600:	'ТО100',
13650:	'ТО50',
13700:	'ТО100',
13750:	'ТО250',
13800:	'ТО100',
13850:	'ТО100',
13900:	'ТО100',
13950:	'ТО50',
14000:	'ТО2000',
14050:	'ТО50',
14100:	'ТО100',
14150:	'ТО50',
14200:	'ТО100',
14250:	'ТО250',
14300:	'ТО100',
14350:	'ТО100',
14400:	'ТО100',
14450:	'ТО50',
14500:	'ТО500',
14550:	'ТО50',
14600:	'ТО100',
14650:	'ТО50',
14700:	'ТО100',
14750:	'ТО250',
14800:	'ТО100',
14850:	'ТО100',
14900:	'ТО100',
14950:	'ТО50',
15000:	'ТО1000',
15050:	'ТО50',
15100:	'ТО100',
15150:	'ТО50',
15200:	'ТО100',
15250:	'ТО250',
15300:	'ТО100',
15350:	'ТО100',
15400:	'ТО100',
15450:	'ТО50',
15500:	'ТО500',
15550:	'ТО50',
15600:	'ТО100',
15650:	'ТО50',
15700:	'ТО100',
15750:	'ТО250',
15800:	'ТО100',
15850:	'ТО100',
15900:	'ТО100',
15950:	'ТО50',
16000:	'ТО8000',
16050:	'ТО50',
16100:	'ТО100',
16150:	'ТО50',
16200:	'ТО100',
16250:	'ТО250',
16300:	'ТО100',
16350:	'ТО100',
16400:	'ТО100',
16450:	'ТО50',
16500:	'ТО500',
16550:	'ТО50',
16600:	'ТО100',
16650:	'ТО50',
16700:	'ТО100',
16750:	'ТО250',
16800:	'ТО100',
16850:	'ТО100',
16900:	'ТО100',
16950:	'ТО50',
17000:	'ТО1000',
17050:	'ТО50',
17100:	'ТО100',
17150:	'ТО50',
17200:	'ТО100',
17250:	'ТО250',
17300:	'ТО100',
17350:	'ТО100',
17400:	'ТО100',
17450:	'ТО50',
17500:	'ТО500',
17550:	'ТО50',
17600:	'ТО100',
17650:	'ТО50',
17700:	'ТО100',
17750:	'ТО250',
17800:	'ТО100',
17850:	'ТО100',
17900:	'ТО100',
17950:	'ТО50',
18000:	'ТО2000',
18050:	'ТО50',
18100:	'ТО100',
18150:	'ТО50',
18200:	'ТО100',
18250:	'ТО250',
18300:	'ТО100',
18350:	'ТО100',
18400:	'ТО100',
18450:	'ТО50',
18500:	'ТО500',
18550:	'ТО50',
18600:	'ТО100',
18650:	'ТО50',
18700:	'ТО100',
18750:	'ТО250',
18800:	'ТО100',
18850:	'ТО100',
18900:	'ТО100',
18950:	'ТО50',
19000:	'ТО1000',
19050:	'ТО50',
19100:	'ТО100',
19150:	'ТО50',
19200:	'ТО100',
19250:	'ТО250',
19300:	'ТО100',
19350:	'ТО100',
19400:	'ТО100',
19450:	'ТО50',
19500:	'ТО500',
19550:	'ТО50',
19600:	'ТО100',
19650:	'ТО50',
19700:	'ТО100',
19750:	'ТО250',
19800:	'ТО100',
19850:	'ТО100',
19900:	'ТО100',
19950:	'ТО50',
20000:	'ТО4000',
20050:	'ТО50',
20100:	'ТО100',
20150:	'ТО50',
20200:	'ТО100',
20250:	'ТО250',
20300:	'ТО100',
20350:	'ТО100',
20400:	'ТО100',
20450:	'ТО50',
20500:	'ТО500',
20550:	'ТО50',
20600:	'ТО100',
20650:	'ТО50',
20700:	'ТО100',
20750:	'ТО250',
20800:	'ТО100',
20850:	'ТО100',
20900:	'ТО100',
20950:	'ТО50',
21000:	'ТО1000',
21050:	'ТО50',
21100:	'ТО100',
21150:	'ТО50',
21200:	'ТО100',
21250:	'ТО250',
21300:	'ТО100',
21350:	'ТО100',
21400:	'ТО100',
21450:	'ТО50',
21500:	'ТО500',
21550:	'ТО50',
21600:	'ТО100',
21650:	'ТО50',
21700:	'ТО100',
21750:	'ТО250',
21800:	'ТО100',
21850:	'ТО100',
21900:	'ТО100',
21950:	'ТО50',
22000:	'ТО2000',
22050:	'ТО50',
22100:	'ТО100',
22150:	'ТО50',
22200:	'ТО100',
22250:	'ТО250',
22300:	'ТО100',
22350:	'ТО100',
22400:	'ТО100',
22450:	'ТО50',
22500:	'ТО500',
22550:	'ТО50',
22600:	'ТО100',
22650:	'ТО50',
22700:	'ТО100',
22750:	'ТО250',
22800:	'ТО100',
22850:	'ТО100',
22900:	'ТО100',
22950:	'ТО50',
23000:	'ТО1000',
23050:	'ТО50',
23100:	'ТО100',
23150:	'ТО50',
23200:	'ТО100',
23250:	'ТО250',
23300:	'ТО100',
23350:	'ТО100',
23400:	'ТО100',
23450:	'ТО50',
23500:	'ТО500',
23550:	'ТО50',
23600:	'ТО100',
23650:	'ТО50',
23700:	'ТО100',
23750:	'ТО250',
23800:	'ТО100',
23850:	'ТО100',
23900:	'ТО100',
23950:	'ТО50',
24000:	'ТО8000',
24050:	'ТО50',
24100:	'ТО100',
24150:	'ТО50',
24200:	'ТО100',
24250:	'ТО250',
24300:	'ТО100',
24350:	'ТО100',
24400:	'ТО100',
24450:	'ТО50',
24500:	'ТО500',
24550:	'ТО50',
24600:	'ТО100',
24650:	'ТО50',
24700:	'ТО100',
24750:	'ТО250',
24800:	'ТО100',
24850:	'ТО100',
24900:	'ТО100',
24950:	'ТО50',
25000:	'ТО1000',
25050:	'ТО50',
25100:	'ТО100',
25150:	'ТО50',
25200:	'ТО100',
25250:	'ТО250',
25300:	'ТО100',
25350:	'ТО100',
25400:	'ТО100',
25450:	'ТО50',
25500:	'ТО500',
25550:	'ТО50',
25600:	'ТО100',
25650:	'ТО50',
25700:	'ТО100',
25750:	'ТО250',
25800:	'ТО100',
25850:	'ТО100',
25900:	'ТО100',
25950:	'ТО50',
26000:	'ТО2000',
26050:	'ТО50',
26100:	'ТО100',
26150:	'ТО50',
26200:	'ТО100',
26250:	'ТО250',
26300:	'ТО100',
26350:	'ТО100',
26400:	'ТО100',
26450:	'ТО50',
26500:	'ТО500',
26550:	'ТО50',
26600:	'ТО100',
26650:	'ТО50',
26700:	'ТО100',
26750:	'ТО250',
26800:	'ТО100',
26850:	'ТО100',
26900:	'ТО100',
26950:	'ТО50',
27000:	'ТО1000',
27050:	'ТО50',
27100:	'ТО100',
27150:	'ТО50',
27200:	'ТО100',
27250:	'ТО250',
27300:	'ТО100',
27350:	'ТО100',
27400:	'ТО100',
27450:	'ТО50',
27500:	'ТО500',
27550:	'ТО50',
27600:	'ТО100',
27650:	'ТО50',
27700:	'ТО100',
27750:	'ТО250',
27800:	'ТО100',
27850:	'ТО100',
27900:	'ТО100',
27950:	'ТО50',
28000:	'ТО8000',
28050:	'ТО50',
28100:	'ТО100',
28150:	'ТО50',
28200:	'ТО100',
28250:	'ТО250',
28300:	'ТО100',
28350:	'ТО100',
28400:	'ТО100',
28450:	'ТО50',
28500:	'ТО500',
28550:	'ТО50',
28600:	'ТО100',
28650:	'ТО50',
28700:	'ТО100',
28750:	'ТО250',
28800:	'ТО100',
28850:	'ТО100',
28900:	'ТО100',
28950:	'ТО50',
29000:	'ТО1000',
29050:	'ТО50',
29100:	'ТО100',
29150:	'ТО50',
29200:	'ТО100',
29250:	'ТО250',
29300:	'ТО100',
29350:	'ТО100',
29400:	'ТО100',
29450:	'ТО50',
29500:	'ТО500',
29550:	'ТО50',
29600:	'ТО100',
29650:	'ТО50',
29700:	'ТО100',
29750:	'ТО250',
29800:	'ТО100',
29850:	'ТО100',
29900:	'ТО100',
29950:	'ТО50',
30000:	'ТО2000',
30050:	'ТО50',
30100:	'ТО100',
30150:	'ТО50',
30200:	'ТО100',
30250:	'ТО250',
30300:	'ТО100',
30350:	'ТО100',
30400:	'ТО100',
30450:	'ТО50',
30500:	'ТО500',
30550:	'ТО50',
30600:	'ТО100',
30650:	'ТО50',
30700:	'ТО100',
30750:	'ТО250',
30800:	'ТО100',
30850:	'ТО100',
30900:	'ТО100',
30950:	'ТО50',
31000:	'ТО1000',
31050:	'ТО50',
31100:	'ТО100',
31150:	'ТО50',
31200:	'ТО100',
31250:	'ТО250',
31300:	'ТО100',
31350:	'ТО100',
31400:	'ТО100',
31450:	'ТО50',
31500:	'ТО500',
31550:	'ТО50',
31600:	'ТО100',
31650:	'ТО50',
31700:	'ТО100',
31750:	'ТО250',
31800:	'ТО100',
31850:	'ТО100',
31900:	'ТО100',
31950:	'ТО50',
32000:	'ТО4000',
32050:	'ТО50',
32100:	'ТО100',
32150:	'ТО50',
32200:	'ТО100',
32250:	'ТО250',
32300:	'ТО100',
32350:	'ТО100',
32400:	'ТО100',
32450:	'ТО50',
32500:	'ТО500',
32550:	'ТО50',
32600:	'ТО100',
32650:	'ТО50',
32700:	'ТО100',
32750:	'ТО250',
32800:	'ТО100',
32850:	'ТО100',
32900:	'ТО100',
32950:	'ТО50',
33000:	'ТО1000',
33050:	'ТО50',
33100:	'ТО100',
33150:	'ТО50',
33200:	'ТО100',
33250:	'ТО250',
33300:	'ТО100',
33350:	'ТО100',
33400:	'ТО100',
33450:	'ТО50',
33500:	'ТО500',
33550:	'ТО50',
33600:	'ТО100',
33650:	'ТО50',
33700:	'ТО100',
33750:	'ТО250',
33800:	'ТО100',
33850:	'ТО100',
33900:	'ТО100',
33950:	'ТО50',
34000:	'ТО2000',
34050:	'ТО50',
34100:	'ТО100',
34150:	'ТО50',
34200:	'ТО100',
34250:	'ТО250',
34300:	'ТО100',
34350:	'ТО100',
34400:	'ТО100',
34450:	'ТО50',
34500:	'ТО500',
34550:	'ТО50',
34600:	'ТО100',
34650:	'ТО50',
34700:	'ТО100',
34750:	'ТО250',
34800:	'ТО100',
34850:	'ТО100',
34900:	'ТО100',
34950:	'ТО50',
35000:	'ТО1000',
35050:	'ТО50',
35100:	'ТО100',
35150:	'ТО50',
35200:	'ТО100',
35250:	'ТО250',
35300:	'ТО100',
35350:	'ТО100',
35400:	'ТО100',
35450:	'ТО50',
35500:	'ТО500',
35550:	'ТО50',
35600:	'ТО100',
35650:	'ТО50',
35700:	'ТО100',
35750:	'ТО250',
35800:	'ТО100',
35850:	'ТО100',
35900:	'ТО100',
35950:	'ТО50',
36000:	'ТО8000',
36050:	'ТО50',
36100:	'ТО100',
36150:	'ТО50',
36200:	'ТО100',
36250:	'ТО250',
36300:	'ТО100',
36350:	'ТО100',
36400:	'ТО100',
36450:	'ТО50',
36500:	'ТО500',
36550:	'ТО50',
36600:	'ТО100',
36650:	'ТО50',
36700:	'ТО100',
36750:	'ТО250',
36800:	'ТО100',
36850:	'ТО100',
36900:	'ТО100',
36950:	'ТО50',
37000:	'ТО1000',
37050:	'ТО50',
37100:	'ТО100',
37150:	'ТО50',
37200:	'ТО100',
37250:	'ТО250',
37300:	'ТО100',
37350:	'ТО100',
37400:	'ТО100',
37450:	'ТО50',
37500:	'ТО500',
37550:	'ТО50',
37600:	'ТО100',
37650:	'ТО50',
37700:	'ТО100',
37750:	'ТО250',
37800:	'ТО100',
37850:	'ТО100',
37900:	'ТО100',
37950:	'ТО50',
38000:	'ТО2000',
38050:	'ТО50',
38100:	'ТО100',
38150:	'ТО50',
38200:	'ТО100',
38250:	'ТО250',
38300:	'ТО100',
38350:	'ТО100',
38400:	'ТО100',
38450:	'ТО50',
38500:	'ТО500',
38550:	'ТО50',
38600:	'ТО100',
38650:	'ТО50',
38700:	'ТО100',
38750:	'ТО250',
38800:	'ТО100',
38850:	'ТО100',
38900:	'ТО100',
38950:	'ТО50',
39000:	'ТО1000',
39050:	'ТО50',
39100:	'ТО100',
39150:	'ТО50',
39200:	'ТО100',
39250:	'ТО250',
39300:	'ТО100',
39350:	'ТО100',
39400:	'ТО100',
39450:	'ТО50',
39500:	'ТО500',
39550:	'ТО50',
39600:	'ТО100',
39650:	'ТО50',
39700:	'ТО100',
39750:	'ТО250',
39800:	'ТО100',
39850:	'ТО100',
39900:	'ТО100',
39950:	'ТО50',
40000:	'ТО4000',
40050:	'ТО50',
40100:	'ТО100',
40150:	'ТО50',
40200:	'ТО100',
40250:	'ТО250',
40300:	'ТО100',
40350:	'ТО100',
40400:	'ТО100',
40450:	'ТО50',
40500:	'ТО500',
40550:	'ТО50',
40600:	'ТО100',
40650:	'ТО50',
40700:	'ТО100',
40750:	'ТО250',
40800:	'ТО100',
40850:	'ТО100',
40900:	'ТО100',
40950:	'ТО50',
41000:	'ТО1000',
41050:	'ТО50',
41100:	'ТО100',
41150:	'ТО50',
41200:	'ТО100',
41250:	'ТО250',
41300:	'ТО100',
41350:	'ТО100',
41400:	'ТО100',
41450:	'ТО50',
41500:	'ТО500',
41550:	'ТО50',
41600:	'ТО100',
41650:	'ТО50',
41700:	'ТО100',
41750:	'ТО250',
41800:	'ТО100',
41850:	'ТО100',
41900:	'ТО100',
41950:	'ТО50',
42000:	'ТО2000',
42050:	'ТО50',
42100:	'ТО100',
42150:	'ТО50',
42200:	'ТО100',
42250:	'ТО250',
42300:	'ТО100',
42350:	'ТО100',
42400:	'ТО100',
42450:	'ТО50',
42500:	'ТО500',
42550:	'ТО50',
42600:	'ТО100',
42650:	'ТО50',
42700:	'ТО100',
42750:	'ТО250',
42800:	'ТО100',
42850:	'ТО100',
42900:	'ТО100',
42950:	'ТО50',
43000:	'ТО1000',
43050:	'ТО50',
43100:	'ТО100',
43150:	'ТО50',
43200:	'ТО100',
43250:	'ТО250',
43300:	'ТО100',
43350:	'ТО100',
43400:	'ТО100',
43450:	'ТО50',
43500:	'ТО500',
43550:	'ТО50',
43600:	'ТО100',
43650:	'ТО50',
43700:	'ТО100',
43750:	'ТО250',
43800:	'ТО100',
43850:	'ТО100',
43900:	'ТО100',
43950:	'ТО50',
44000:	'ТО8000',
44050:	'ТО50',
44100:	'ТО100',
44150:	'ТО50',
44200:	'ТО100',
44250:	'ТО250',
44300:	'ТО100',
44350:	'ТО100',
44400:	'ТО100',
44450:	'ТО50',
44500:	'ТО500',
44550:	'ТО50',
44600:	'ТО100',
44650:	'ТО50',
44700:	'ТО100',
44750:	'ТО250',
44800:	'ТО100',
44850:	'ТО100',
44900:	'ТО100',
44950:	'ТО50',
45000:	'ТО1000',
45050:	'ТО50',
45100:	'ТО100',
45150:	'ТО50',
45200:	'ТО100',
45250:	'ТО250',
45300:	'ТО100',
45350:	'ТО100',
45400:	'ТО100',
45450:	'ТО50',
45500:	'ТО500',
45550:	'ТО50',
45600:	'ТО100',
45650:	'ТО50',
45700:	'ТО100',
45750:	'ТО250',
45800:	'ТО100',
45850:	'ТО100',
45900:	'ТО100',
45950:	'ТО50',
46000:	'ТО2000',
46050:	'ТО50',
46100:	'ТО100',
46150:	'ТО50',
46200:	'ТО100',
46250:	'ТО250',
46300:	'ТО100',
46350:	'ТО100',
46400:	'ТО100',
46450:	'ТО50',
46500:	'ТО500',
46550:	'ТО50',
46600:	'ТО100',
46650:	'ТО50',
46700:	'ТО100',
46750:	'ТО250',
46800:	'ТО100',
46850:	'ТО100',
46900:	'ТО100',
46950:	'ТО50',
47000:	'ТО1000',
47050:	'ТО50',
47100:	'ТО100',
47150:	'ТО50',
47200:	'ТО100',
47250:	'ТО250',
47300:	'ТО100',
47350:	'ТО100',
47400:	'ТО100',
47450:	'ТО50',
47500:	'ТО500',
47550:	'ТО50',
47600:	'ТО100',
47650:	'ТО50',
47700:	'ТО100',
47750:	'ТО250',
47800:	'ТО100',
47850:	'ТО100',
47900:	'ТО100',
47950:	'ТО50',
48000:	'ТО8000'

}

In [54]:
to_dict_TD16={
    50:	'ТО50',
100:	'ТО50',
150:	'ТО50',
200:	'ТО50',
250:	'ТО250',
300:	'ТО50',
350:	'ТО50',
400:	'ТО50',
450:	'ТО50',
500:	'ТО500',
550:	'ТО50',
600:	'ТО50',
650:	'ТО50',
700:	'ТО50',
750:	'ТО250',
800:	'ТО50',
850:	'ТО50',
900:	'ТО50',
950:	'ТО50',
1000:	'ТО1000',
1050:	'ТО50',
1100:	'ТО50',
1150:	'ТО50',
1200:	'ТО50',
1250:	'ТО250',
1300:	'ТО50',
1350:	'ТО50',
1400:	'ТО50',
1450:	'ТО50',
1500:	'ТО500',
1550:	'ТО50',
1600:	'ТО50',
1650:	'ТО50',
1700:	'ТО50',
1750:	'ТО250',
1800:	'ТО50',
1850:	'ТО50',
1900:	'ТО50',
1950:	'ТО50',
2000:	'ТО2000',
2050:	'ТО50',
2100:	'ТО50',
2150:	'ТО50',
2200:	'ТО50',
2250:	'ТО250',
2300:	'ТО50',
2350:	'ТО50',
2400:	'ТО50',
2450:	'ТО50',
2500:	'ТО500',
2550:	'ТО50',
2600:	'ТО50',
2650:	'ТО50',
2700:	'ТО50',
2750:	'ТО250',
2800:	'ТО50',
2850:	'ТО50',
2900:	'ТО50',
2950:	'ТО50',
3000:	'ТО1000',
3050:	'ТО50',
3100:	'ТО50',
3150:	'ТО50',
3200:	'ТО50',
3250:	'ТО250',
3300:	'ТО50',
3350:	'ТО50',
3400:	'ТО50',
3450:	'ТО50',
3500:	'ТО500',
3550:	'ТО50',
3600:	'ТО50',
3650:	'ТО50',
3700:	'ТО50',
3750:	'ТО250',
3800:	'ТО50',
3850:	'ТО50',
3900:	'ТО50',
3950:	'ТО50',
4000:	'ТО4000',
4050:	'ТО50',
4100:	'ТО50',
4150:	'ТО50',
4200:	'ТО50',
4250:	'ТО250',
4300:	'ТО50',
4350:	'ТО50',
4400:	'ТО50',
4450:	'ТО50',
4500:	'ТО500',
4550:	'ТО50',
4600:	'ТО50',
4650:	'ТО50',
4700:	'ТО50',
4750:	'ТО250',
4800:	'ТО50',
4850:	'ТО50',
4900:	'ТО50',
4950:	'ТО50',
5000:	'ТО1000',
5050:	'ТО50',
5100:	'ТО50',
5150:	'ТО50',
5200:	'ТО50',
5250:	'ТО250',
5300:	'ТО50',
5350:	'ТО50',
5400:	'ТО50',
5450:	'ТО50',
5500:	'ТО500',
5550:	'ТО50',
5600:	'ТО50',
5650:	'ТО50',
5700:	'ТО50',
5750:	'ТО250',
5800:	'ТО50',
5850:	'ТО50',
5900:	'ТО50',
5950:	'ТО50',
6000:	'ТО2000',
6050:	'ТО50',
6100:	'ТО50',
6150:	'ТО50',
6200:	'ТО50',
6250:	'ТО250',
6300:	'ТО50',
6350:	'ТО50',
6400:	'ТО50',
6450:	'ТО50',
6500:	'ТО500',
6550:	'ТО50',
6600:	'ТО50',
6650:	'ТО50',
6700:	'ТО50',
6750:	'ТО250',
6800:	'ТО50',
6850:	'ТО50',
6900:	'ТО50',
6950:	'ТО50',
7000:	'ТО1000',
7050:	'ТО50',
7100:	'ТО50',
7150:	'ТО50',
7200:	'ТО50',
7250:	'ТО250',
7300:	'ТО50',
7350:	'ТО50',
7400:	'ТО50',
7450:	'ТО50',
7500:	'ТО500',
7550:	'ТО50',
7600:	'ТО50',
7650:	'ТО50',
7700:	'ТО50',
7750:	'ТО250',
7800:	'ТО50',
7850:	'ТО50',
7900:	'ТО50',
7950:	'ТО50',
8000:	'ТО4000',
8050:	'ТО50',
8100:	'ТО50',
8150:	'ТО50',
8200:	'ТО50',
8250:	'ТО250',
8300:	'ТО50',
8350:	'ТО50',
8400:	'ТО50',
8450:	'ТО50',
8500:	'ТО500',
8550:	'ТО50',
8600:	'ТО50',
8650:	'ТО50',
8700:	'ТО50',
8750:	'ТО250',
8800:	'ТО50',
8850:	'ТО50',
8900:	'ТО50',
8950:	'ТО50',
9000:	'ТО1000',
9050:	'ТО50',
9100:	'ТО50',
9150:	'ТО50',
9200:	'ТО50',
9250:	'ТО250',
9300:	'ТО50',
9350:	'ТО50',
9400:	'ТО50',
9450:	'ТО50',
9500:	'ТО500',
9550:	'ТО50',
9600:	'ТО50',
9650:	'ТО50',
9700:	'ТО50',
9750:	'ТО250',
9800:	'ТО50',
9850:	'ТО50',
9900:	'ТО50',
9950:	'ТО50',
10000:	'ТО2000',
10050:	'ТО50',
10100:	'ТО50',
10150:	'ТО50',
10200:	'ТО50',
10250:	'ТО250',
10300:	'ТО50',
10350:	'ТО50',
10400:	'ТО50',
10450:	'ТО50',
10500:	'ТО500',
10550:	'ТО50',
10600:	'ТО50',
10650:	'ТО50',
10700:	'ТО50',
10750:	'ТО250',
10800:	'ТО50',
10850:	'ТО50',
10900:	'ТО50',
10950:	'ТО50',
11000:	'ТО1000',
11050:	'ТО50',
11100:	'ТО50',
11150:	'ТО50',
11200:	'ТО50',
11250:	'ТО250',
11300:	'ТО50',
11350:	'ТО50',
11400:	'ТО50',
11450:	'ТО50',
11500:	'ТО500',
11550:	'ТО50',
11600:	'ТО50',
11650:	'ТО50',
11700:	'ТО50',
11750:	'ТО250',
11800:	'ТО50',
11850:	'ТО50',
11900:	'ТО50',
11950:	'ТО50',
12000:	'ТО4000',
12050:	'ТО50',
12100:	'ТО50',
12150:	'ТО50',
12200:	'ТО50',
12250:	'ТО250',
12300:	'ТО50',
12350:	'ТО50',
12400:	'ТО50',
12450:	'ТО50',
12500:	'ТО500',
12550:	'ТО50',
12600:	'ТО50',
12650:	'ТО50',
12700:	'ТО50',
12750:	'ТО250',
12800:	'ТО50',
12850:	'ТО50',
12900:	'ТО50',
12950:	'ТО50',
13000:	'ТО1000',
13050:	'ТО50',
13100:	'ТО50',
13150:	'ТО50',
13200:	'ТО50',
13250:	'ТО250',
13300:	'ТО50',
13350:	'ТО50',
13400:	'ТО50',
13450:	'ТО50',
13500:	'ТО500',
13550:	'ТО50',
13600:	'ТО50',
13650:	'ТО50',
13700:	'ТО50',
13750:	'ТО250',
13800:	'ТО50',
13850:	'ТО50',
13900:	'ТО50',
13950:	'ТО50',
14000:	'ТО2000',
14050:	'ТО50',
14100:	'ТО50',
14150:	'ТО50',
14200:	'ТО50',
14250:	'ТО250',
14300:	'ТО50',
14350:	'ТО50',
14400:	'ТО50',
14450:	'ТО50',
14500:	'ТО500',
14550:	'ТО50',
14600:	'ТО50',
14650:	'ТО50',
14700:	'ТО50',
14750:	'ТО250',
14800:	'ТО50',
14850:	'ТО50',
14900:	'ТО50',
14950:	'ТО50',
15000:	'ТО1000',
15050:	'ТО50',
15100:	'ТО50',
15150:	'ТО50',
15200:	'ТО50',
15250:	'ТО250',
15300:	'ТО50',
15350:	'ТО50',
15400:	'ТО50',
15450:	'ТО50',
15500:	'ТО500',
15550:	'ТО50',
15600:	'ТО50',
15650:	'ТО50',
15700:	'ТО50',
15750:	'ТО250',
15800:	'ТО50',
15850:	'ТО50',
15900:	'ТО50',
15950:	'ТО50',
16000:	'ТО4000',
16050:	'ТО50',
16100:	'ТО50',
16150:	'ТО50',
16200:	'ТО50',
16250:	'ТО250',
16300:	'ТО50',
16350:	'ТО50',
16400:	'ТО50',
16450:	'ТО50',
16500:	'ТО500',
16550:	'ТО50',
16600:	'ТО50',
16650:	'ТО50',
16700:	'ТО50',
16750:	'ТО250',
16800:	'ТО50',
16850:	'ТО50',
16900:	'ТО50',
16950:	'ТО50',
17000:	'ТО1000',
17050:	'ТО50',
17100:	'ТО50',
17150:	'ТО50',
17200:	'ТО50',
17250:	'ТО250',
17300:	'ТО50',
17350:	'ТО50',
17400:	'ТО50',
17450:	'ТО50',
17500:	'ТО500',
17550:	'ТО50',
17600:	'ТО50',
17650:	'ТО50',
17700:	'ТО50',
17750:	'ТО250',
17800:	'ТО50',
17850:	'ТО50',
17900:	'ТО50',
17950:	'ТО50',
18000:	'ТО2000',
18050:	'ТО50',
18100:	'ТО50',
18150:	'ТО50',
18200:	'ТО50',
18250:	'ТО250',
18300:	'ТО50',
18350:	'ТО50',
18400:	'ТО50',
18450:	'ТО50',
18500:	'ТО500',
18550:	'ТО50',
18600:	'ТО50',
18650:	'ТО50',
18700:	'ТО50',
18750:	'ТО250',
18800:	'ТО50',
18850:	'ТО50',
18900:	'ТО50',
18950:	'ТО50',
19000:	'ТО1000',
19050:	'ТО50',
19100:	'ТО50',
19150:	'ТО50',
19200:	'ТО50',
19250:	'ТО250',
19300:	'ТО50',
19350:	'ТО50',
19400:	'ТО50',
19450:	'ТО50',
19500:	'ТО500',
19550:	'ТО50',
19600:	'ТО50',
19650:	'ТО50',
19700:	'ТО50',
19750:	'ТО250',
19800:	'ТО50',
19850:	'ТО50',
19900:	'ТО50',
19950:	'ТО50',
20000:	'ТО4000',
20050:	'ТО50',
20100:	'ТО50',
20150:	'ТО50',
20200:	'ТО50',
20250:	'ТО250',
20300:	'ТО50',
20350:	'ТО50',
20400:	'ТО50',
20450:	'ТО50',
20500:	'ТО500',
20550:	'ТО50',
20600:	'ТО50',
20650:	'ТО50',
20700:	'ТО50',
20750:	'ТО250',
20800:	'ТО50',
20850:	'ТО50',
20900:	'ТО50',
20950:	'ТО50',
21000:	'ТО1000',
21050:	'ТО50',
21100:	'ТО50',
21150:	'ТО50',
21200:	'ТО50',
21250:	'ТО250',
21300:	'ТО50',
21350:	'ТО50',
21400:	'ТО50',
21450:	'ТО50',
21500:	'ТО500',
21550:	'ТО50',
21600:	'ТО50',
21650:	'ТО50',
21700:	'ТО50',
21750:	'ТО250',
21800:	'ТО50',
21850:	'ТО50',
21900:	'ТО50',
21950:	'ТО50',
22000:	'ТО2000',
22050:	'ТО50',
22100:	'ТО50',
22150:	'ТО50',
22200:	'ТО50',
22250:	'ТО250',
22300:	'ТО50',
22350:	'ТО50',
22400:	'ТО50',
22450:	'ТО50',
22500:	'ТО500',
22550:	'ТО50',
22600:	'ТО50',
22650:	'ТО50',
22700:	'ТО50',
22750:	'ТО250',
22800:	'ТО50',
22850:	'ТО50',
22900:	'ТО50',
22950:	'ТО50',
23000:	'ТО1000',
23050:	'ТО50',
23100:	'ТО50',
23150:	'ТО50',
23200:	'ТО50',
23250:	'ТО250',
23300:	'ТО50',
23350:	'ТО50',
23400:	'ТО50',
23450:	'ТО50',
23500:	'ТО500',
23550:	'ТО50',
23600:	'ТО50',
23650:	'ТО50',
23700:	'ТО50',
23750:	'ТО250',
23800:	'ТО50',
23850:	'ТО50',
23900:	'ТО50',
23950:	'ТО50',
24000:	'ТО4000',
24050:	'ТО50',
24100:	'ТО50',
24150:	'ТО50',
24200:	'ТО50',
24250:	'ТО250',
24300:	'ТО50',
24350:	'ТО50',
24400:	'ТО50',
24450:	'ТО50',
24500:	'ТО500',
24550:	'ТО50',
24600:	'ТО50',
24650:	'ТО50',
24700:	'ТО50',
24750:	'ТО250',
24800:	'ТО50',
24850:	'ТО50',
24900:	'ТО50',
24950:	'ТО50',
25000:	'ТО1000',
25050:	'ТО50',
25100:	'ТО50',
25150:	'ТО50',
25200:	'ТО50',
25250:	'ТО250',
25300:	'ТО50',
25350:	'ТО50',
25400:	'ТО50',
25450:	'ТО50',
25500:	'ТО500',
25550:	'ТО50',
25600:	'ТО50',
25650:	'ТО50',
25700:	'ТО50',
25750:	'ТО250',
25800:	'ТО50',
25850:	'ТО50',
25900:	'ТО50',
25950:	'ТО50',
26000:	'ТО2000',
26050:	'ТО50',
26100:	'ТО50',
26150:	'ТО50',
26200:	'ТО50',
26250:	'ТО250',
26300:	'ТО50',
26350:	'ТО50',
26400:	'ТО50',
26450:	'ТО50',
26500:	'ТО500',
26550:	'ТО50',
26600:	'ТО50',
26650:	'ТО50',
26700:	'ТО50',
26750:	'ТО250',
26800:	'ТО50',
26850:	'ТО50',
26900:	'ТО50',
26950:	'ТО50',
27000:	'ТО1000',
27050:	'ТО50',
27100:	'ТО50',
27150:	'ТО50',
27200:	'ТО50',
27250:	'ТО250',
27300:	'ТО50',
27350:	'ТО50',
27400:	'ТО50',
27450:	'ТО50',
27500:	'ТО500',
27550:	'ТО50',
27600:	'ТО50',
27650:	'ТО50',
27700:	'ТО50',
27750:	'ТО250',
27800:	'ТО50',
27850:	'ТО50',
27900:	'ТО50',
27950:	'ТО50',
28000:	'ТО4000',
28050:	'ТО50',
28100:	'ТО50',
28150:	'ТО50',
28200:	'ТО50',
28250:	'ТО250',
28300:	'ТО50',
28350:	'ТО50',
28400:	'ТО50',
28450:	'ТО50',
28500:	'ТО500',
28550:	'ТО50',
28600:	'ТО50',
28650:	'ТО50',
28700:	'ТО50',
28750:	'ТО250',
28800:	'ТО50',
28850:	'ТО50',
28900:	'ТО50',
28950:	'ТО50',
29000:	'ТО1000',
29050:	'ТО50',
29100:	'ТО50',
29150:	'ТО50',
29200:	'ТО50',
29250:	'ТО250',
29300:	'ТО50',
29350:	'ТО50',
29400:	'ТО50',
29450:	'ТО50',
29500:	'ТО500',
29550:	'ТО50',
29600:	'ТО50',
29650:	'ТО50',
29700:	'ТО50',
29750:	'ТО250',
29800:	'ТО50',
29850:	'ТО50',
29900:	'ТО50',
29950:	'ТО50',
30000:	'ТО2000',
30050:	'ТО50',
30100:	'ТО50',
30150:	'ТО50',
30200:	'ТО50',
30250:	'ТО250',
30300:	'ТО50',
30350:	'ТО50',
30400:	'ТО50',
30450:	'ТО50',
30500:	'ТО500',
30550:	'ТО50',
30600:	'ТО50',
30650:	'ТО50',
30700:	'ТО50',
30750:	'ТО250',
30800:	'ТО50',
30850:	'ТО50',
30900:	'ТО50',
30950:	'ТО50',
31000:	'ТО1000',
31050:	'ТО50',
31100:	'ТО50',
31150:	'ТО50',
31200:	'ТО50',
31250:	'ТО250',
31300:	'ТО50',
31350:	'ТО50',
31400:	'ТО50',
31450:	'ТО50',
31500:	'ТО500',
31550:	'ТО50',
31600:	'ТО50',
31650:	'ТО50',
31700:	'ТО50',
31750:	'ТО250',
31800:	'ТО50',
31850:	'ТО50',
31900:	'ТО50',
31950:	'ТО50',
32000:	'ТО4000',
32050:	'ТО50',
32100:	'ТО50',
32150:	'ТО50',
32200:	'ТО50',
32250:	'ТО250',
32300:	'ТО50',
32350:	'ТО50',
32400:	'ТО50',
32450:	'ТО50',
32500:	'ТО500',
32550:	'ТО50',
32600:	'ТО50',
32650:	'ТО50',
32700:	'ТО50',
32750:	'ТО250',
32800:	'ТО50',
32850:	'ТО50',
32900:	'ТО50',
32950:	'ТО50',
33000:	'ТО1000',
33050:	'ТО50',
33100:	'ТО50',
33150:	'ТО50',
33200:	'ТО50',
33250:	'ТО250',
33300:	'ТО50',
33350:	'ТО50',
33400:	'ТО50',
33450:	'ТО50',
33500:	'ТО500',
33550:	'ТО50',
33600:	'ТО50',
33650:	'ТО50',
33700:	'ТО50',
33750:	'ТО250',
33800:	'ТО50',
33850:	'ТО50',
33900:	'ТО50',
33950:	'ТО50',
34000:	'ТО2000',
34050:	'ТО50',
34100:	'ТО50',
34150:	'ТО50',
34200:	'ТО50',
34250:	'ТО250',
34300:	'ТО50',
34350:	'ТО50',
34400:	'ТО50',
34450:	'ТО50',
34500:	'ТО500',
34550:	'ТО50',
34600:	'ТО50',
34650:	'ТО50',
34700:	'ТО50',
34750:	'ТО250',
34800:	'ТО50',
34850:	'ТО50',
34900:	'ТО50',
34950:	'ТО50',
35000:	'ТО1000',
35050:	'ТО50',
35100:	'ТО50',
35150:	'ТО50',
35200:	'ТО50',
35250:	'ТО250',
35300:	'ТО50',
35350:	'ТО50',
35400:	'ТО50',
35450:	'ТО50',
35500:	'ТО500',
35550:	'ТО50',
35600:	'ТО50',
35650:	'ТО50',
35700:	'ТО50',
35750:	'ТО250',
35800:	'ТО50',
35850:	'ТО50',
35900:	'ТО50',
35950:	'ТО50',
36000:	'ТО4000',
36050:	'ТО50',
36100:	'ТО50',
36150:	'ТО50',
36200:	'ТО50',
36250:	'ТО250',
36300:	'ТО50',
36350:	'ТО50',
36400:	'ТО50',
36450:	'ТО50',
36500:	'ТО500',
36550:	'ТО50',
36600:	'ТО50',
36650:	'ТО50',
36700:	'ТО50',
36750:	'ТО250',
36800:	'ТО50',
36850:	'ТО50',
36900:	'ТО50',
36950:	'ТО50',
37000:	'ТО1000',
37050:	'ТО50',
37100:	'ТО50',
37150:	'ТО50',
37200:	'ТО50',
37250:	'ТО250',
37300:	'ТО50',
37350:	'ТО50',
37400:	'ТО50',
37450:	'ТО50',
37500:	'ТО500',
37550:	'ТО50',
37600:	'ТО50',
37650:	'ТО50',
37700:	'ТО50',
37750:	'ТО250',
37800:	'ТО50',
37850:	'ТО50',
37900:	'ТО50',
37950:	'ТО50',
38000:	'ТО2000',
38050:	'ТО50',
38100:	'ТО50',
38150:	'ТО50',
38200:	'ТО50',
38250:	'ТО250',
38300:	'ТО50',
38350:	'ТО50',
38400:	'ТО50',
38450:	'ТО50',
38500:	'ТО500',
38550:	'ТО50',
38600:	'ТО50',
38650:	'ТО50',
38700:	'ТО50',
38750:	'ТО250',
38800:	'ТО50',
38850:	'ТО50',
38900:	'ТО50',
38950:	'ТО50',
39000:	'ТО1000',
39050:	'ТО50',
39100:	'ТО50',
39150:	'ТО50',
39200:	'ТО50',
39250:	'ТО250',
39300:	'ТО50',
39350:	'ТО50',
39400:	'ТО50',
39450:	'ТО50',
39500:	'ТО500',
39550:	'ТО50',
39600:	'ТО50',
39650:	'ТО50',
39700:	'ТО50',
39750:	'ТО250',
39800:	'ТО50',
39850:	'ТО50',
39900:	'ТО50',
39950:	'ТО50',
40000:	'ТО4000',
40050:	'ТО50',
40100:	'ТО50',
40150:	'ТО50',
40200:	'ТО50',
40250:	'ТО250',
40300:	'ТО50',
40350:	'ТО50',
40400:	'ТО50',
40450:	'ТО50',
40500:	'ТО500',
40550:	'ТО50',
40600:	'ТО50',
40650:	'ТО50',
40700:	'ТО50',
40750:	'ТО250',
40800:	'ТО50',
40850:	'ТО50',
40900:	'ТО50',
40950:	'ТО50',
41000:	'ТО1000',
41050:	'ТО50',
41100:	'ТО50',
41150:	'ТО50',
41200:	'ТО50',
41250:	'ТО250',
41300:	'ТО50',
41350:	'ТО50',
41400:	'ТО50',
41450:	'ТО50',
41500:	'ТО500',
41550:	'ТО50',
41600:	'ТО50',
41650:	'ТО50',
41700:	'ТО50',
41750:	'ТО250',
41800:	'ТО50',
41850:	'ТО50',
41900:	'ТО50',
41950:	'ТО50',
42000:	'ТО2000',
42050:	'ТО50',
42100:	'ТО50',
42150:	'ТО50',
42200:	'ТО50',
42250:	'ТО250',
42300:	'ТО50',
42350:	'ТО50',
42400:	'ТО50',
42450:	'ТО50',
42500:	'ТО500',
42550:	'ТО50',
42600:	'ТО50',
42650:	'ТО50',
42700:	'ТО50',
42750:	'ТО250',
42800:	'ТО50',
42850:	'ТО50',
42900:	'ТО50',
42950:	'ТО50',
43000:	'ТО1000',
43050:	'ТО50',
43100:	'ТО50',
43150:	'ТО50',
43200:	'ТО50',
43250:	'ТО250',
43300:	'ТО50',
43350:	'ТО50',
43400:	'ТО50',
43450:	'ТО50',
43500:	'ТО500',
43550:	'ТО50',
43600:	'ТО50',
43650:	'ТО50',
43700:	'ТО50',
43750:	'ТО250',
43800:	'ТО50',
43850:	'ТО50',
43900:	'ТО50',
43950:	'ТО50',
44000:	'ТО4000',
44050:	'ТО50',
44100:	'ТО50',
44150:	'ТО50',
44200:	'ТО50',
44250:	'ТО250',
44300:	'ТО50',
44350:	'ТО50',
44400:	'ТО50',
44450:	'ТО50',
44500:	'ТО500',
44550:	'ТО50',
44600:	'ТО50',
44650:	'ТО50',
44700:	'ТО50',
44750:	'ТО250',
44800:	'ТО50',
44850:	'ТО50',
44900:	'ТО50',
44950:	'ТО50',
45000:	'ТО1000',
45050:	'ТО50',
45100:	'ТО50',
45150:	'ТО50',
45200:	'ТО50',
45250:	'ТО250',
45300:	'ТО50',
45350:	'ТО50',
45400:	'ТО50',
45450:	'ТО50',
45500:	'ТО500',
45550:	'ТО50',
45600:	'ТО50',
45650:	'ТО50',
45700:	'ТО50',
45750:	'ТО250',
45800:	'ТО50',
45850:	'ТО50',
45900:	'ТО50',
45950:	'ТО50',
46000:	'ТО2000',
46050:	'ТО50',
46100:	'ТО50',
46150:	'ТО50',
46200:	'ТО50',
46250:	'ТО250',
46300:	'ТО50',
46350:	'ТО50',
46400:	'ТО50',
46450:	'ТО50',
46500:	'ТО500',
46550:	'ТО50',
46600:	'ТО50',
46650:	'ТО50',
46700:	'ТО50',
46750:	'ТО250',
46800:	'ТО50',
46850:	'ТО50',
46900:	'ТО50',
46950:	'ТО50',
47000:	'ТО1000',
47050:	'ТО50',
47100:	'ТО50',
47150:	'ТО50',
47200:	'ТО50',
47250:	'ТО250',
47300:	'ТО50',
47350:	'ТО50',
47400:	'ТО50',
47450:	'ТО50',
47500:	'ТО500',
47550:	'ТО50',
47600:	'ТО50',
47650:	'ТО50',
47700:	'ТО50',
47750:	'ТО250',
47800:	'ТО50',
47850:	'ТО50',
47900:	'ТО50',
47950:	'ТО50',
48000:	'ТО4000'

}

In [55]:
to_dict_D65={
    50:	'ТО50',
100:	'ТО50',
150:	'ТО50',
200:	'ТО50',
250:	'ТО250',
300:	'ТО50',
350:	'ТО50',
400:	'ТО50',
450:	'ТО50',
500:	'ТО500',
550:	'ТО50',
600:	'ТО50',
650:	'ТО50',
700:	'ТО50',
750:	'ТО250',
800:	'ТО50',
850:	'ТО50',
900:	'ТО50',
950:	'ТО50',
1000:	'ТО1000',
1050:	'ТО50',
1100:	'ТО50',
1150:	'ТО50',
1200:	'ТО50',
1250:	'ТО250',
1300:	'ТО50',
1350:	'ТО50',
1400:	'ТО50',
1450:	'ТО50',
1500:	'ТО500',
1550:	'ТО50',
1600:	'ТО50',
1650:	'ТО50',
1700:	'ТО50',
1750:	'ТО250',
1800:	'ТО50',
1850:	'ТО50',
1900:	'ТО50',
1950:	'ТО50',
2000:	'ТО2000',
2050:	'ТО50',
2100:	'ТО50',
2150:	'ТО50',
2200:	'ТО50',
2250:	'ТО250',
2300:	'ТО50',
2350:	'ТО50',
2400:	'ТО50',
2450:	'ТО50',
2500:	'ТО500',
2550:	'ТО50',
2600:	'ТО50',
2650:	'ТО50',
2700:	'ТО50',
2750:	'ТО250',
2800:	'ТО50',
2850:	'ТО50',
2900:	'ТО50',
2950:	'ТО50',
3000:	'ТО1000',
3050:	'ТО50',
3100:	'ТО50',
3150:	'ТО50',
3200:	'ТО50',
3250:	'ТО250',
3300:	'ТО50',
3350:	'ТО50',
3400:	'ТО50',
3450:	'ТО50',
3500:	'ТО500',
3550:	'ТО50',
3600:	'ТО50',
3650:	'ТО50',
3700:	'ТО50',
3750:	'ТО250',
3800:	'ТО50',
3850:	'ТО50',
3900:	'ТО50',
3950:	'ТО50',
4000:	'ТО4000',
4050:	'ТО50',
4100:	'ТО50',
4150:	'ТО50',
4200:	'ТО50',
4250:	'ТО250',
4300:	'ТО50',
4350:	'ТО50',
4400:	'ТО50',
4450:	'ТО50',
4500:	'ТО500',
4550:	'ТО50',
4600:	'ТО50',
4650:	'ТО50',
4700:	'ТО50',
4750:	'ТО250',
4800:	'ТО50',
4850:	'ТО50',
4900:	'ТО50',
4950:	'ТО50',
5000:	'ТО1000',
5050:	'ТО50',
5100:	'ТО50',
5150:	'ТО50',
5200:	'ТО50',
5250:	'ТО250',
5300:	'ТО50',
5350:	'ТО50',
5400:	'ТО50',
5450:	'ТО50',
5500:	'ТО500',
5550:	'ТО50',
5600:	'ТО50',
5650:	'ТО50',
5700:	'ТО50',
5750:	'ТО250',
5800:	'ТО50',
5850:	'ТО50',
5900:	'ТО50',
5950:	'ТО50',
6000:	'ТО2000',
6050:	'ТО50',
6100:	'ТО50',
6150:	'ТО50',
6200:	'ТО50',
6250:	'ТО250',
6300:	'ТО50',
6350:	'ТО50',
6400:	'ТО50',
6450:	'ТО50',
6500:	'ТО500',
6550:	'ТО50',
6600:	'ТО50',
6650:	'ТО50',
6700:	'ТО50',
6750:	'ТО250',
6800:	'ТО50',
6850:	'ТО50',
6900:	'ТО50',
6950:	'ТО50',
7000:	'ТО1000',
7050:	'ТО50',
7100:	'ТО50',
7150:	'ТО50',
7200:	'ТО50',
7250:	'ТО250',
7300:	'ТО50',
7350:	'ТО50',
7400:	'ТО50',
7450:	'ТО50',
7500:	'ТО500',
7550:	'ТО50',
7600:	'ТО50',
7650:	'ТО50',
7700:	'ТО50',
7750:	'ТО250',
7800:	'ТО50',
7850:	'ТО50',
7900:	'ТО50',
7950:	'ТО50',
8000:	'ТО8000',
8050:	'ТО50',
8100:	'ТО50',
8150:	'ТО50',
8200:	'ТО50',
8250:	'ТО250',
8300:	'ТО50',
8350:	'ТО50',
8400:	'ТО50',
8450:	'ТО50',
8500:	'ТО500',
8550:	'ТО50',
8600:	'ТО50',
8650:	'ТО50',
8700:	'ТО50',
8750:	'ТО250',
8800:	'ТО50',
8850:	'ТО50',
8900:	'ТО50',
8950:	'ТО50',
9000:	'ТО1000',
9050:	'ТО50',
9100:	'ТО50',
9150:	'ТО50',
9200:	'ТО50',
9250:	'ТО250',
9300:	'ТО50',
9350:	'ТО50',
9400:	'ТО50',
9450:	'ТО50',
9500:	'ТО500',
9550:	'ТО50',
9600:	'ТО50',
9650:	'ТО50',
9700:	'ТО50',
9750:	'ТО250',
9800:	'ТО50',
9850:	'ТО50',
9900:	'ТО50',
9950:	'ТО50',
10000:	'ТО2000',
10050:	'ТО50',
10100:	'ТО50',
10150:	'ТО50',
10200:	'ТО50',
10250:	'ТО250',
10300:	'ТО50',
10350:	'ТО50',
10400:	'ТО50',
10450:	'ТО50',
10500:	'ТО500',
10550:	'ТО50',
10600:	'ТО50',
10650:	'ТО50',
10700:	'ТО50',
10750:	'ТО250',
10800:	'ТО50',
10850:	'ТО50',
10900:	'ТО50',
10950:	'ТО50',
11000:	'ТО1000',
11050:	'ТО50',
11100:	'ТО50',
11150:	'ТО50',
11200:	'ТО50',
11250:	'ТО250',
11300:	'ТО50',
11350:	'ТО50',
11400:	'ТО50',
11450:	'ТО50',
11500:	'ТО500',
11550:	'ТО50',
11600:	'ТО50',
11650:	'ТО50',
11700:	'ТО50',
11750:	'ТО250',
11800:	'ТО50',
11850:	'ТО50',
11900:	'ТО50',
11950:	'ТО50',
12000:	'ТО4000',
12050:	'ТО50',
12100:	'ТО50',
12150:	'ТО50',
12200:	'ТО50',
12250:	'ТО250',
12300:	'ТО50',
12350:	'ТО50',
12400:	'ТО50',
12450:	'ТО50',
12500:	'ТО500',
12550:	'ТО50',
12600:	'ТО50',
12650:	'ТО50',
12700:	'ТО50',
12750:	'ТО250',
12800:	'ТО50',
12850:	'ТО50',
12900:	'ТО50',
12950:	'ТО50',
13000:	'ТО1000',
13050:	'ТО50',
13100:	'ТО50',
13150:	'ТО50',
13200:	'ТО50',
13250:	'ТО250',
13300:	'ТО50',
13350:	'ТО50',
13400:	'ТО50',
13450:	'ТО50',
13500:	'ТО500',
13550:	'ТО50',
13600:	'ТО50',
13650:	'ТО50',
13700:	'ТО50',
13750:	'ТО250',
13800:	'ТО50',
13850:	'ТО50',
13900:	'ТО50',
13950:	'ТО50',
14000:	'ТО2000',
14050:	'ТО50',
14100:	'ТО50',
14150:	'ТО50',
14200:	'ТО50',
14250:	'ТО250',
14300:	'ТО50',
14350:	'ТО50',
14400:	'ТО50',
14450:	'ТО50',
14500:	'ТО500',
14550:	'ТО50',
14600:	'ТО50',
14650:	'ТО50',
14700:	'ТО50',
14750:	'ТО250',
14800:	'ТО50',
14850:	'ТО50',
14900:	'ТО50',
14950:	'ТО50',
15000:	'ТО1000',
15050:	'ТО50',
15100:	'ТО50',
15150:	'ТО50',
15200:	'ТО50',
15250:	'ТО250',
15300:	'ТО50',
15350:	'ТО50',
15400:	'ТО50',
15450:	'ТО50',
15500:	'ТО500',
15550:	'ТО50',
15600:	'ТО50',
15650:	'ТО50',
15700:	'ТО50',
15750:	'ТО250',
15800:	'ТО50',
15850:	'ТО50',
15900:	'ТО50',
15950:	'ТО50',
16000:	'ТО8000',
16050:	'ТО50',
16100:	'ТО50',
16150:	'ТО50',
16200:	'ТО50',
16250:	'ТО250',
16300:	'ТО50',
16350:	'ТО50',
16400:	'ТО50',
16450:	'ТО50',
16500:	'ТО500',
16550:	'ТО50',
16600:	'ТО50',
16650:	'ТО50',
16700:	'ТО50',
16750:	'ТО250',
16800:	'ТО50',
16850:	'ТО50',
16900:	'ТО50',
16950:	'ТО50',
17000:	'ТО1000',
17050:	'ТО50',
17100:	'ТО50',
17150:	'ТО50',
17200:	'ТО50',
17250:	'ТО250',
17300:	'ТО50',
17350:	'ТО50',
17400:	'ТО50',
17450:	'ТО50',
17500:	'ТО500',
17550:	'ТО50',
17600:	'ТО50',
17650:	'ТО50',
17700:	'ТО50',
17750:	'ТО250',
17800:	'ТО50',
17850:	'ТО50',
17900:	'ТО50',
17950:	'ТО50',
18000:	'ТО2000',
18050:	'ТО50',
18100:	'ТО50',
18150:	'ТО50',
18200:	'ТО50',
18250:	'ТО250',
18300:	'ТО50',
18350:	'ТО50',
18400:	'ТО50',
18450:	'ТО50',
18500:	'ТО500',
18550:	'ТО50',
18600:	'ТО50',
18650:	'ТО50',
18700:	'ТО50',
18750:	'ТО250',
18800:	'ТО50',
18850:	'ТО50',
18900:	'ТО50',
18950:	'ТО50',
19000:	'ТО1000',
19050:	'ТО50',
19100:	'ТО50',
19150:	'ТО50',
19200:	'ТО50',
19250:	'ТО250',
19300:	'ТО50',
19350:	'ТО50',
19400:	'ТО50',
19450:	'ТО50',
19500:	'ТО500',
19550:	'ТО50',
19600:	'ТО50',
19650:	'ТО50',
19700:	'ТО50',
19750:	'ТО250',
19800:	'ТО50',
19850:	'ТО50',
19900:	'ТО50',
19950:	'ТО50',
20000:	'ТО4000',
20050:	'ТО50',
20100:	'ТО50',
20150:	'ТО50',
20200:	'ТО50',
20250:	'ТО250',
20300:	'ТО50',
20350:	'ТО50',
20400:	'ТО50',
20450:	'ТО50',
20500:	'ТО500',
20550:	'ТО50',
20600:	'ТО50',
20650:	'ТО50',
20700:	'ТО50',
20750:	'ТО250',
20800:	'ТО50',
20850:	'ТО50',
20900:	'ТО50',
20950:	'ТО50',
21000:	'ТО1000',
21050:	'ТО50',
21100:	'ТО50',
21150:	'ТО50',
21200:	'ТО50',
21250:	'ТО250',
21300:	'ТО50',
21350:	'ТО50',
21400:	'ТО50',
21450:	'ТО50',
21500:	'ТО500',
21550:	'ТО50',
21600:	'ТО50',
21650:	'ТО50',
21700:	'ТО50',
21750:	'ТО250',
21800:	'ТО50',
21850:	'ТО50',
21900:	'ТО50',
21950:	'ТО50',
22000:	'ТО2000',
22050:	'ТО50',
22100:	'ТО50',
22150:	'ТО50',
22200:	'ТО50',
22250:	'ТО250',
22300:	'ТО50',
22350:	'ТО50',
22400:	'ТО50',
22450:	'ТО50',
22500:	'ТО500',
22550:	'ТО50',
22600:	'ТО50',
22650:	'ТО50',
22700:	'ТО50',
22750:	'ТО250',
22800:	'ТО50',
22850:	'ТО50',
22900:	'ТО50',
22950:	'ТО50',
23000:	'ТО1000',
23050:	'ТО50',
23100:	'ТО50',
23150:	'ТО50',
23200:	'ТО50',
23250:	'ТО250',
23300:	'ТО50',
23350:	'ТО50',
23400:	'ТО50',
23450:	'ТО50',
23500:	'ТО500',
23550:	'ТО50',
23600:	'ТО50',
23650:	'ТО50',
23700:	'ТО50',
23750:	'ТО250',
23800:	'ТО50',
23850:	'ТО50',
23900:	'ТО50',
23950:	'ТО50',
24000:	'ТО8000',
24050:	'ТО50',
24100:	'ТО50',
24150:	'ТО50',
24200:	'ТО50',
24250:	'ТО250',
24300:	'ТО50',
24350:	'ТО50',
24400:	'ТО50',
24450:	'ТО50',
24500:	'ТО500',
24550:	'ТО50',
24600:	'ТО50',
24650:	'ТО50',
24700:	'ТО50',
24750:	'ТО250',
24800:	'ТО50',
24850:	'ТО50',
24900:	'ТО50',
24950:	'ТО50',
25000:	'ТО1000',
25050:	'ТО50',
25100:	'ТО50',
25150:	'ТО50',
25200:	'ТО50',
25250:	'ТО250',
25300:	'ТО50',
25350:	'ТО50',
25400:	'ТО50',
25450:	'ТО50',
25500:	'ТО500',
25550:	'ТО50',
25600:	'ТО50',
25650:	'ТО50',
25700:	'ТО50',
25750:	'ТО250',
25800:	'ТО50',
25850:	'ТО50',
25900:	'ТО50',
25950:	'ТО50',
26000:	'ТО2000',
26050:	'ТО50',
26100:	'ТО50',
26150:	'ТО50',
26200:	'ТО50',
26250:	'ТО250',
26300:	'ТО50',
26350:	'ТО50',
26400:	'ТО50',
26450:	'ТО50',
26500:	'ТО500',
26550:	'ТО50',
26600:	'ТО50',
26650:	'ТО50',
26700:	'ТО50',
26750:	'ТО250',
26800:	'ТО50',
26850:	'ТО50',
26900:	'ТО50',
26950:	'ТО50',
27000:	'ТО1000',
27050:	'ТО50',
27100:	'ТО50',
27150:	'ТО50',
27200:	'ТО50',
27250:	'ТО250',
27300:	'ТО50',
27350:	'ТО50',
27400:	'ТО50',
27450:	'ТО50',
27500:	'ТО500',
27550:	'ТО50',
27600:	'ТО50',
27650:	'ТО50',
27700:	'ТО50',
27750:	'ТО250',
27800:	'ТО50',
27850:	'ТО50',
27900:	'ТО50',
27950:	'ТО50',
28000:	'ТО8000',
28050:	'ТО50',
28100:	'ТО50',
28150:	'ТО50',
28200:	'ТО50',
28250:	'ТО250',
28300:	'ТО50',
28350:	'ТО50',
28400:	'ТО50',
28450:	'ТО50',
28500:	'ТО500',
28550:	'ТО50',
28600:	'ТО50',
28650:	'ТО50',
28700:	'ТО50',
28750:	'ТО250',
28800:	'ТО50',
28850:	'ТО50',
28900:	'ТО50',
28950:	'ТО50',
29000:	'ТО1000',
29050:	'ТО50',
29100:	'ТО50',
29150:	'ТО50',
29200:	'ТО50',
29250:	'ТО250',
29300:	'ТО50',
29350:	'ТО50',
29400:	'ТО50',
29450:	'ТО50',
29500:	'ТО500',
29550:	'ТО50',
29600:	'ТО50',
29650:	'ТО50',
29700:	'ТО50',
29750:	'ТО250',
29800:	'ТО50',
29850:	'ТО50',
29900:	'ТО50',
29950:	'ТО50',
30000:	'ТО2000',
30050:	'ТО50',
30100:	'ТО50',
30150:	'ТО50',
30200:	'ТО50',
30250:	'ТО250',
30300:	'ТО50',
30350:	'ТО50',
30400:	'ТО50',
30450:	'ТО50',
30500:	'ТО500',
30550:	'ТО50',
30600:	'ТО50',
30650:	'ТО50',
30700:	'ТО50',
30750:	'ТО250',
30800:	'ТО50',
30850:	'ТО50',
30900:	'ТО50',
30950:	'ТО50',
31000:	'ТО1000',
31050:	'ТО50',
31100:	'ТО50',
31150:	'ТО50',
31200:	'ТО50',
31250:	'ТО250',
31300:	'ТО50',
31350:	'ТО50',
31400:	'ТО50',
31450:	'ТО50',
31500:	'ТО500',
31550:	'ТО50',
31600:	'ТО50',
31650:	'ТО50',
31700:	'ТО50',
31750:	'ТО250',
31800:	'ТО50',
31850:	'ТО50',
31900:	'ТО50',
31950:	'ТО50',
32000:	'ТО4000',
32050:	'ТО50',
32100:	'ТО50',
32150:	'ТО50',
32200:	'ТО50',
32250:	'ТО250',
32300:	'ТО50',
32350:	'ТО50',
32400:	'ТО50',
32450:	'ТО50',
32500:	'ТО500',
32550:	'ТО50',
32600:	'ТО50',
32650:	'ТО50',
32700:	'ТО50',
32750:	'ТО250',
32800:	'ТО50',
32850:	'ТО50',
32900:	'ТО50',
32950:	'ТО50',
33000:	'ТО1000',
33050:	'ТО50',
33100:	'ТО50',
33150:	'ТО50',
33200:	'ТО50',
33250:	'ТО250',
33300:	'ТО50',
33350:	'ТО50',
33400:	'ТО50',
33450:	'ТО50',
33500:	'ТО500',
33550:	'ТО50',
33600:	'ТО50',
33650:	'ТО50',
33700:	'ТО50',
33750:	'ТО250',
33800:	'ТО50',
33850:	'ТО50',
33900:	'ТО50',
33950:	'ТО50',
34000:	'ТО2000',
34050:	'ТО50',
34100:	'ТО50',
34150:	'ТО50',
34200:	'ТО50',
34250:	'ТО250',
34300:	'ТО50',
34350:	'ТО50',
34400:	'ТО50',
34450:	'ТО50',
34500:	'ТО500',
34550:	'ТО50',
34600:	'ТО50',
34650:	'ТО50',
34700:	'ТО50',
34750:	'ТО250',
34800:	'ТО50',
34850:	'ТО50',
34900:	'ТО50',
34950:	'ТО50',
35000:	'ТО1000',
35050:	'ТО50',
35100:	'ТО50',
35150:	'ТО50',
35200:	'ТО50',
35250:	'ТО250',
35300:	'ТО50',
35350:	'ТО50',
35400:	'ТО50',
35450:	'ТО50',
35500:	'ТО500',
35550:	'ТО50',
35600:	'ТО50',
35650:	'ТО50',
35700:	'ТО50',
35750:	'ТО250',
35800:	'ТО50',
35850:	'ТО50',
35900:	'ТО50',
35950:	'ТО50',
36000:	'ТО8000',
36050:	'ТО50',
36100:	'ТО50',
36150:	'ТО50',
36200:	'ТО50',
36250:	'ТО250',
36300:	'ТО50',
36350:	'ТО50',
36400:	'ТО50',
36450:	'ТО50',
36500:	'ТО500',
36550:	'ТО50',
36600:	'ТО50',
36650:	'ТО50',
36700:	'ТО50',
36750:	'ТО250',
36800:	'ТО50',
36850:	'ТО50',
36900:	'ТО50',
36950:	'ТО50',
37000:	'ТО1000',
37050:	'ТО50',
37100:	'ТО50',
37150:	'ТО50',
37200:	'ТО50',
37250:	'ТО250',
37300:	'ТО50',
37350:	'ТО50',
37400:	'ТО50',
37450:	'ТО50',
37500:	'ТО500',
37550:	'ТО50',
37600:	'ТО50',
37650:	'ТО50',
37700:	'ТО50',
37750:	'ТО250',
37800:	'ТО50',
37850:	'ТО50',
37900:	'ТО50',
37950:	'ТО50',
38000:	'ТО2000',
38050:	'ТО50',
38100:	'ТО50',
38150:	'ТО50',
38200:	'ТО50',
38250:	'ТО250',
38300:	'ТО50',
38350:	'ТО50',
38400:	'ТО50',
38450:	'ТО50',
38500:	'ТО500',
38550:	'ТО50',
38600:	'ТО50',
38650:	'ТО50',
38700:	'ТО50',
38750:	'ТО250',
38800:	'ТО50',
38850:	'ТО50',
38900:	'ТО50',
38950:	'ТО50',
39000:	'ТО1000',
39050:	'ТО50',
39100:	'ТО50',
39150:	'ТО50',
39200:	'ТО50',
39250:	'ТО250',
39300:	'ТО50',
39350:	'ТО50',
39400:	'ТО50',
39450:	'ТО50',
39500:	'ТО500',
39550:	'ТО50',
39600:	'ТО50',
39650:	'ТО50',
39700:	'ТО50',
39750:	'ТО250',
39800:	'ТО50',
39850:	'ТО50',
39900:	'ТО50',
39950:	'ТО50',
40000:	'ТО4000',
40050:	'ТО50',
40100:	'ТО50',
40150:	'ТО50',
40200:	'ТО50',
40250:	'ТО250',
40300:	'ТО50',
40350:	'ТО50',
40400:	'ТО50',
40450:	'ТО50',
40500:	'ТО500',
40550:	'ТО50',
40600:	'ТО50',
40650:	'ТО50',
40700:	'ТО50',
40750:	'ТО250',
40800:	'ТО50',
40850:	'ТО50',
40900:	'ТО50',
40950:	'ТО50',
41000:	'ТО1000',
41050:	'ТО50',
41100:	'ТО50',
41150:	'ТО50',
41200:	'ТО50',
41250:	'ТО250',
41300:	'ТО50',
41350:	'ТО50',
41400:	'ТО50',
41450:	'ТО50',
41500:	'ТО500',
41550:	'ТО50',
41600:	'ТО50',
41650:	'ТО50',
41700:	'ТО50',
41750:	'ТО250',
41800:	'ТО50',
41850:	'ТО50',
41900:	'ТО50',
41950:	'ТО50',
42000:	'ТО2000',
42050:	'ТО50',
42100:	'ТО50',
42150:	'ТО50',
42200:	'ТО50',
42250:	'ТО250',
42300:	'ТО50',
42350:	'ТО50',
42400:	'ТО50',
42450:	'ТО50',
42500:	'ТО500',
42550:	'ТО50',
42600:	'ТО50',
42650:	'ТО50',
42700:	'ТО50',
42750:	'ТО250',
42800:	'ТО50',
42850:	'ТО50',
42900:	'ТО50',
42950:	'ТО50',
43000:	'ТО1000',
43050:	'ТО50',
43100:	'ТО50',
43150:	'ТО50',
43200:	'ТО50',
43250:	'ТО250',
43300:	'ТО50',
43350:	'ТО50',
43400:	'ТО50',
43450:	'ТО50',
43500:	'ТО500',
43550:	'ТО50',
43600:	'ТО50',
43650:	'ТО50',
43700:	'ТО50',
43750:	'ТО250',
43800:	'ТО50',
43850:	'ТО50',
43900:	'ТО50',
43950:	'ТО50',
44000:	'ТО8000',
44050:	'ТО50',
44100:	'ТО50',
44150:	'ТО50',
44200:	'ТО50',
44250:	'ТО250',
44300:	'ТО50',
44350:	'ТО50',
44400:	'ТО50',
44450:	'ТО50',
44500:	'ТО500',
44550:	'ТО50',
44600:	'ТО50',
44650:	'ТО50',
44700:	'ТО50',
44750:	'ТО250',
44800:	'ТО50',
44850:	'ТО50',
44900:	'ТО50',
44950:	'ТО50',
45000:	'ТО1000',
45050:	'ТО50',
45100:	'ТО50',
45150:	'ТО50',
45200:	'ТО50',
45250:	'ТО250',
45300:	'ТО50',
45350:	'ТО50',
45400:	'ТО50',
45450:	'ТО50',
45500:	'ТО500',
45550:	'ТО50',
45600:	'ТО50',
45650:	'ТО50',
45700:	'ТО50',
45750:	'ТО250',
45800:	'ТО50',
45850:	'ТО50',
45900:	'ТО50',
45950:	'ТО50',
46000:	'ТО2000',
46050:	'ТО50',
46100:	'ТО50',
46150:	'ТО50',
46200:	'ТО50',
46250:	'ТО250',
46300:	'ТО50',
46350:	'ТО50',
46400:	'ТО50',
46450:	'ТО50',
46500:	'ТО500',
46550:	'ТО50',
46600:	'ТО50',
46650:	'ТО50',
46700:	'ТО50',
46750:	'ТО250',
46800:	'ТО50',
46850:	'ТО50',
46900:	'ТО50',
46950:	'ТО50',
47000:	'ТО1000',
47050:	'ТО50',
47100:	'ТО50',
47150:	'ТО50',
47200:	'ТО50',
47250:	'ТО250',
47300:	'ТО50',
47350:	'ТО50',
47400:	'ТО50',
47450:	'ТО50',
47500:	'ТО500',
47550:	'ТО50',
47600:	'ТО50',
47650:	'ТО50',
47700:	'ТО50',
47750:	'ТО250',
47800:	'ТО50',
47850:	'ТО50',
47900:	'ТО50',
47950:	'ТО50',
48000:	'ТО8000'



}

In [56]:
to_dict_case={
    50: "ТО50",
100: "ТО50",
150: "ТО50",
200: "ТО50",
250: "ТО250",
300: "ТО50",
350: "ТО50",
400: "ТО50",
450: "ТО50",
500: "ТО500",
550: "ТО50",
600: "ТО50",
650: "ТО50",
700: "ТО50",
750: "ТО250",
800: "ТО50",
850: "ТО50",
900: "ТО50",
950: "ТО50",
1000: "ТО1000",
1050: "ТО50",
1100: "ТО50",
1150: "ТО50",
1200: "ТО50",
1250: "ТО250",
1300: "ТО50",
1350: "ТО50",
1400: "ТО50",
1450: "ТО50",
1500: "ТО500",
1550: "ТО50",
1600: "ТО50",
1650: "ТО50",
1700: "ТО50",
1750: "ТО250",
1800: "ТО50",
1850: "ТО50",
1900: "ТО50",
1950: "ТО50",
2000: "ТО2000",
2050: "ТО50",
2100: "ТО50",
2150: "ТО50",
2200: "ТО50",
2250: "ТО250",
2300: "ТО50",
2350: "ТО50",
2400: "ТО50",
2450: "ТО50",
2500: "ТО500",
2550: "ТО50",
2600: "ТО50",
2650: "ТО50",
2700: "ТО50",
2750: "ТО250",
2800: "ТО50",
2850: "ТО50",
2900: "ТО50",
2950: "ТО50",
3000: "ТО3000",
3050: "ТО50",
3100: "ТО50",
3150: "ТО50",
3200: "ТО50",
3250: "ТО250",
3300: "ТО50",
3350: "ТО50",
3400: "ТО50",
3450: "ТО50",
3500: "ТО500",
3550: "ТО50",
3600: "ТО50",
3650: "ТО50",
3700: "ТО50",
3750: "ТО250",
3800: "ТО50",
3850: "ТО50",
3900: "ТО50",
3950: "ТО50",
4000: "ТО4000",
4050: "ТО50",
4100: "ТО50",
4150: "ТО50",
4200: "ТО50",
4250: "ТО250",
4300: "ТО50",
4350: "ТО50",
4400: "ТО50",
4450: "ТО50",
4500: "ТО500",
4550: "ТО50",
4600: "ТО50",
4650: "ТО50",
4700: "ТО50",
4750: "ТО250",
4800: "ТО50",
4850: "ТО50",
4900: "ТО50",
4950: "ТО50",
5000: "ТО5000",
5050: "ТО50",
5100: "ТО50",
5150: "ТО50",
5200: "ТО50",
5250: "ТО250",
5300: "ТО50",
5350: "ТО50",
5400:"ТО50",
5450:"ТО50",
5500:"ТО500",
5550:"ТО50",
5600:"ТО50",
5650:"ТО50",
5700:"ТО50",
5750:"ТО250",
5800:"ТО50",
5850:"ТО50",
5900:"ТО50",
5950:"ТО50",
6000:"ТО3000",
6050:"ТО50",
6100:"ТО50",
6150:"ТО50",
6200:"ТО50",
6250:"ТО250",
6300:"ТО50",
6350:"ТО50",
6400:"ТО50",
6450:"ТО50",
6500:"ТО500",
6550:"ТО50",
6600:"ТО50",
6650:"ТО50",
6700:"ТО50",
6750:"ТО250",
6800:"ТО50",
6850:"ТО50",
6900:"ТО50",
6950:"ТО50",
7000:"ТО1000",
7050:"ТО50",
7100:"ТО50",
7150:"ТО50",
7200:"ТО50",
7250:"ТО250",
7300:"ТО50",
7350:"ТО50",
7400:"ТО50",
7450:"ТО50",
7500:"ТО500",
7550:"ТО50",
7600:"ТО50",
7650:"ТО50",
7700:"ТО50",
7750:"ТО250",
7800:"ТО50",
7850:"ТО50",
7900:"ТО50",
7950:"ТО50",
8000:"ТО4000",
8050:"ТО50",
8100:"ТО50",
8150:"ТО50",
8200:"ТО50",
8250:"ТО250",
8300:"ТО50",
8350:"ТО50",
8400:"ТО50",
8450:"ТО50",
8500:"ТО500",
8550:"ТО50",
8600:"ТО50",
8650:"ТО50",
8700:"ТО50",
8750:"ТО250",
8800:"ТО50",
8850:"ТО50",
8900:"ТО50",
8950:"ТО50",
9000:"ТО3000",
9050:"ТО50",
9100:"ТО50",
9150:"ТО50",
9200:"ТО50",
9250:"ТО250",
9300:"ТО50",
9350:"ТО50",
9400:"ТО50",
9450:"ТО50",
9500:"ТО500",
9550:"ТО50",
9600:"ТО50",
9650:"ТО50",
9700:"ТО50",
9750:"ТО250",
9800:"ТО50",
9850:"ТО50",
9900:"ТО50",
9950:"ТО50",
10000:"ТО2000/5000",
10050:"ТО50",
10100:"ТО50",
10150:"ТО50",
10200:"ТО50",
10250:"ТО250",
10300:"ТО50",
10350:"ТО50",
10400:"ТО50",
10450:"ТО50",
10500:"ТО500",
10550:"ТО50",
10600:"ТО50",
10650:"ТО50",
10700:"ТО50",
10750:"ТО250",
10800:"ТО50",
10850:"ТО50",
10900:"ТО50",
10950:"ТО50",
11000:"ТО1000",
11050:"ТО50",
11100:"ТО50",
11150:"ТО50",
11200:"ТО50",
11250:"ТО250",
11300:"ТО50",
11350:"ТО50",
11400:"ТО50",
11450:"ТО50",
11500:"ТО500",
11550:"ТО50",
11600:"ТО50",
11650:"ТО50",
11700:"ТО50",
11750:"ТО250",
11800:"ТО50",
11850:"ТО50",
11900:"ТО50",
11950:"ТО50",
12000:"ТО3000/4000",
12050:"ТО50",
12100:"ТО50",
12150:"ТО50",
12200:"ТО50",
12250:"ТО250",
12300:"ТО50",
12350:"ТО50",
12400:"ТО50",
12450:"ТО50",
12500:"ТО500",
12550:"ТО50",
12600:"ТО50",
12650:"ТО50",
12700:"ТО50",
12750:"ТО250",
12800:"ТО50",
12850:"ТО50",
12900:"ТО50",
12950:"ТО50",
13000:"ТО1000",
13050:"ТО50",
13100:"ТО50",
13150:"ТО50",
13200:"ТО50",
13250:"ТО250",
13300:"ТО50",
13350:"ТО50",
13400:"ТО50",
13450:"ТО50",
13500:"ТО500",
13550:"ТО50",
13600:"ТО50",
13650:"ТО50",
13700:"ТО50",
13750:"ТО250",
13800:"ТО50",
13850:"ТО50",
13900:"ТО50",
13950:"ТО50",
14000:"ТО2000",
14050:"ТО50",
14100:"ТО50",
14150:"ТО50",
14200:"ТО50",
14250:"ТО250",
14300:"ТО50",
14350:"ТО50",
14400:"ТО50",
14450:"ТО50",
14500:"ТО500",
14550:"ТО50",
14600:"ТО50",
14650:"ТО50",
14700:"ТО50",
14750:"ТО250",
14800:"ТО50",
14850:"ТО50",
14900:"ТО50",
14950:"ТО50",
15000:"ТО3000/5000",
15050:"ТО50",
15100:"ТО50",
15150:"ТО50",
15200:"ТО50",
15250:"ТО250",
15300:"ТО50",
15350:"ТО50",
15400:"ТО50",
15450:"ТО50",
15500:"ТО500",
15550:"ТО50",
15600:"ТО50",
15650:"ТО50",
15700:"ТО50",
15750:"ТО250",
15800:"ТО50",
15850:"ТО50",
15900:"ТО50",
15950:"ТО50",
16000:"ТО4000",
16050:"ТО50",
16100:"ТО50",
16150:"ТО50",
16200:"ТО50",
16250:"ТО250",
16300:"ТО50",
16350:"ТО50",
16400:"ТО50",
16450:"ТО50",
16500:"ТО500",
16550:"ТО50",
16600:"ТО50",
16650:"ТО50",
16700:"ТО50",
16750:"ТО250",
16800:"ТО50",
16850:"ТО50",
16900:"ТО50",
16950:"ТО50",
17000:"ТО1000",
17050:"ТО50",
17100:"ТО50",
17150:"ТО50",
17200:"ТО50",
17250:"ТО250",
17300:"ТО50",
17350:"ТО50",
17400:"ТО50",
17450:"ТО50",
17500:"ТО500",
17550:"ТО50",
17600:"ТО50",
17650:"ТО50",
17700:"ТО50",
17750:"ТО250",
17800:"ТО50",
17850:"ТО50",
17900:"ТО50",
17950:"ТО50",
18000:"ТО3000",
18050:"ТО50",
18100:"ТО50",
18150:"ТО50",
18200:"ТО50",
18250:"ТО250",
18300:"ТО50",
18350:"ТО50",
18400:"ТО50",
18450:"ТО50",
18500:"ТО500",
18550:"ТО50",
18600:"ТО50",
18650:"ТО50",
18700:"ТО50",
18750:"ТО250",
18800:"ТО50",
18850:"ТО50",
18900:"ТО50",
18950:"ТО50",
19000:"ТО1000",
19050:"ТО50",
19100:"ТО50",
19150:"ТО50",
19200:"ТО50",
19250:"ТО250",
19300:"ТО50",
19350:"ТО50",
19400:"ТО50",
19450:"ТО50",
19500:"ТО500",
19550:"ТО50",
19600:"ТО50",
19650:"ТО50",
19700:"ТО50",
19750:"ТО250",
19800:"ТО50",
19850:"ТО50",
19900:"ТО50",
19950:"ТО50",
20000:"ТО4000/5000",
20050:"ТО50",
20100:"ТО50",
20150:"ТО50",
20200:"ТО50",
20250:"ТО250",
20300:"ТО50",
20350:"ТО50",
20400:"ТО50",
20450:"ТО50",
20500:"ТО500",
20550:"ТО50",
20600:"ТО50",
20650:"ТО50",
20700:"ТО50",
20750:"ТО250",
20800:"ТО50",
20850:"ТО50",
20900:"ТО50",
20950:"ТО50",
21000:"ТО3000",
21050:"ТО50",
21100:"ТО50",
21150:"ТО50",
21200:"ТО50",
21250:"ТО250",
21300:"ТО50",
21350:"ТО50",
21400:"ТО50",
21450:"ТО50",
21500:"ТО500",
21550:"ТО50",
21600:"ТО50",
21650:"ТО50",
21700:"ТО50",
21750:"ТО250",
21800:"ТО50",
21850:"ТО50",
21900:"ТО50",
21950:"ТО50",
22000:"ТО2000",
22050:"ТО50",
22100:"ТО50",
22150:"ТО50",
22200:"ТО50",
22250:"ТО250",
22300:"ТО50",
22350:"ТО50",
22400:"ТО50",
22450:"ТО50",
22500:"ТО500",
22550:"ТО50",
22600:"ТО50",
22650:"ТО50",
22700:"ТО50",
22750:"ТО250",
22800:"ТО50",
22850:"ТО50",
22900:"ТО50",
22950:"ТО50",
23000:"ТО1000",
23050:"ТО50",
23100:"ТО50",
23150:"ТО50",
23200:"ТО50",
23250:"ТО250",
23300:"ТО50",
23350:"ТО50",
23400:"ТО50",
23450:"ТО50",
23500:"ТО500",
23550:"ТО50",
23600:"ТО50",
23650:"ТО50",
23700:"ТО50",
23750:"ТО250",
23800:"ТО50",
23850:"ТО50",
23900:"ТО50",
23950:"ТО50",
24000:"ТО3000/4000",
24050:"ТО50",
24100:"ТО50",
24150:"ТО50",
24200:"ТО50",
24250:"ТО250",
24300:"ТО50",
24350:"ТО50",
24400:"ТО50",
24450:"ТО50",
24500:"ТО500",
24550:"ТО50",
24600:"ТО50",
24650:"ТО50",
24700:"ТО50",
24750:"ТО250",
24800:"ТО50",
24850:"ТО50",
24900:"ТО50",
24950:"ТО50",
25000:"ТО5000",
25050:"ТО50",
25100:"ТО50",
25150:"ТО50",
25200:"ТО50",
25250:"ТО250",
25300:"ТО50",
25350:"ТО50",
25400:"ТО50",
25450:"ТО50",
25500:"ТО500",
25550:"ТО50",
25600:"ТО50",
25650:"ТО50",
25700:"ТО50",
25750:"ТО250",
25800:"ТО50",
25850:"ТО50",
25900:"ТО50",
25950:"ТО50",
26000:"ТО2000",
26050:"ТО50",
26100:"ТО50",
26150:"ТО50",
26200:"ТО50",
26250:"ТО250",
26300:"ТО50",
26350:"ТО50",
26400:"ТО50",
26450:"ТО50",
26500:"ТО500",
26550:"ТО50",
26600:"ТО50",
26650:"ТО50",
26700:"ТО50",
26750:"ТО250",
26800:"ТО50",
26850:"ТО50",
26900:"ТО50",
26950:"ТО50",
27000:"ТО3000",
27050:"ТО50",
27100:"ТО50",
27150:"ТО50",
27200:"ТО50",
27250:"ТО250",
27300:"ТО50",
27350:"ТО50",
27400:"ТО50",
27450:"ТО50",
27500:"ТО500",
27550:"ТО50",
27600:"ТО50",
27650:"ТО50",
27700:"ТО50",
27750:"ТО250",
27800:"ТО50",
27850:"ТО50",
27900:"ТО50",
27950:"ТО50",
28000:"ТО4000",
28050:"ТО50",
28100:"ТО50",
28150:"ТО50",
28200:"ТО50",
28250:"ТО250",
28300:"ТО50",
28350:"ТО50",
28400:"ТО50",
28450:"ТО50",
28500:"ТО500",
28550:"ТО50",
28600:"ТО50",
28650:"ТО50",
28700:"ТО50",
28750:"ТО250",
28800:"ТО50",
28850:"ТО50",
28900:"ТО50",
28950:"ТО50",
29000:"ТО1000",
29050:"ТО50",
29100:"ТО50",
29150:"ТО50",
29200:"ТО50",
29250:"ТО250",
29300:"ТО50",
29350:"ТО50",
29400:"ТО50",
29450:"ТО50",
29500:"ТО500",
29550:"ТО50",
29600:"ТО50",
29650:"ТО50",
29700:"ТО50",
29750:"ТО250",
29800:"ТО50",
29850:"ТО50",
29900:"ТО50",
29950:"ТО50",
30000:"ТО3000/5000",
30050:"ТО50",
30100:"ТО50",
30150:"ТО50",
30200:"ТО50",
30250:"ТО250",
30300:"ТО50",
30350:"ТО50",
30400:"ТО50",
30450:"ТО50",
30500:"ТО500",
30550:"ТО50",
30600:"ТО50",
30650:"ТО50",
30700:"ТО50",
30750:"ТО250",
30800:"ТО50",
30850:"ТО50",
30900:"ТО50",
30950:"ТО50",
31000:"ТО1000",
31050:"ТО50",
31100:"ТО50",
31150:"ТО50",
31200:"ТО50",
31250:"ТО250",
31300:"ТО50",
31350:"ТО50",
31400:"ТО50",
31450:"ТО50",
31500:"ТО500",
31550:"ТО50",
31600:"ТО50",
31650:"ТО50",
31700:"ТО50",
31750:"ТО250",
31800:"ТО50",
31850:"ТО50",
31900:"ТО50",
31950:"ТО50",
32000:"ТО4000",
32050:"ТО50",
32100:"ТО50",
32150:"ТО50",
32200:"ТО50",
32250:"ТО250",
32300:"ТО50",
32350:"ТО50",
32400:"ТО50",
32450:"ТО50",
32500:"ТО500",
32550:"ТО50",
32600:"ТО50",
32650:"ТО50",
32700:"ТО50",
32750:"ТО250",
32800:"ТО50",
32850:"ТО50",
32900:"ТО50",
32950:"ТО50",
33000:"ТО3000",
33050:"ТО50",
33100:"ТО50",
33150:"ТО50",
33200:"ТО50",
33250:"ТО250",
33300:"ТО50",
33350:"ТО50",
33400:"ТО50",
33450:"ТО50",
33500:"ТО500",
33550:"ТО50",
33600:"ТО50",
33650:"ТО50",
33700:"ТО50",
33750:"ТО250",
33800:"ТО50",
33850:"ТО50",
33900:"ТО50",
33950:"ТО50",
34000:"ТО2000",
34050:"ТО50",
34100:"ТО50",
34150:"ТО50",
34200:"ТО50",
34250:"ТО250",
34300:"ТО50",
34350:"ТО50",
34400:"ТО50",
34450:"ТО50",
34500:"ТО500",
34550:"ТО50",
34600:"ТО50",
34650:"ТО50",
34700:"ТО50",
34750:"ТО250",
34800:"ТО50",
34850:"ТО50",
34900:"ТО50",
34950:"ТО50",
35000:"ТО5000",
35050:"ТО50",
35100:"ТО50",
35150:"ТО50",
35200:"ТО50",
35250:"ТО250",
35300:"ТО50",
35350:"ТО50",
35400:"ТО50",
35450:"ТО50",
35500:"ТО500",
35550:"ТО50",
35600:"ТО50",
35650:"ТО50",
35700:"ТО50",
35750:"ТО250",
35800:"ТО50",
35850:"ТО50",
35900:"ТО50",
35950:"ТО50",
36000:"ТО3000/4000",
36050:"ТО50",
36100:"ТО50",
36150:"ТО50",
36200:"ТО50",
36250:"ТО250",
36300:"ТО50",
36350:"ТО50",
36400:"ТО50",
36450:"ТО50",
36500:"ТО500",
36550:"ТО50",
36600:"ТО50",
36650:"ТО50",
36700:"ТО50",
36750:"ТО250",
36800:"ТО50",
36850:"ТО50",
36900:"ТО50",
36950:"ТО50",
37000:"ТО1000",
37050:"ТО50",
37100:"ТО50",
37150:"ТО50",
37200:"ТО50",
37250:"ТО250",
37300:"ТО50",
37350:"ТО50",
37400:"ТО50",
37450:"ТО50",
37500:"ТО500",
37550:"ТО50",
37600:"ТО50",
37650:"ТО50",
37700:"ТО50",
37750:"ТО250",
37800:"ТО50",
37850:"ТО50",
37900:"ТО50",
37950:"ТО50",
38000:"ТО2000",
38050:"ТО50",
38100:"ТО50",
38150:"ТО50",
38200:"ТО50",
38250:"ТО250",
38300:"ТО50",
38350:"ТО50",
38400:"ТО50",
38450:"ТО50",
38500:"ТО500",
38550:"ТО50",
38600:"ТО50",
38650:"ТО50",
38700:"ТО50",
38750:"ТО250",
38800:"ТО50",
38850:"ТО50",
38900:"ТО50",
38950:"ТО50",
39000:"ТО3000",
39050:"ТО50",
39100:"ТО50",
39150:"ТО50",
39200:"ТО50",
39250:"ТО250",
39300:"ТО50",
39350:"ТО50",
39400:"ТО50",
39450:"ТО50",
39500:"ТО500",
39550:"ТО50",
39600:"ТО50",
39650:"ТО50",
39700:"ТО50",
39750:"ТО250",
39800:"ТО50",
39850:"ТО50",
39900:"ТО50",
39950:"ТО50",
40000:"ТО4000/5000",
40050:"ТО50",
40100:"ТО50",
40150:"ТО50",
40200:"ТО50",
40250:"ТО250",
40300:"ТО50",
40350:"ТО50",
40400:"ТО50",
40450:"ТО50",
40500:"ТО500",
40550:"ТО50",
40600:"ТО50",
40650:"ТО50",
40700:"ТО50",
40750:"ТО250",
40800:"ТО50",
40850:"ТО50",
40900:"ТО50",
40950:"ТО50",
41000:"ТО1000",
41050:"ТО50",
41100:"ТО50",
41150:"ТО50",
41200:"ТО50",
41250:"ТО250",
41300:"ТО50",
41350:"ТО50",
41400:"ТО50",
41450:"ТО50",
41500:"ТО500",
41550:"ТО50",
41600:"ТО50",
41650:"ТО50",
41700:"ТО50",
41750:"ТО250",
41800:"ТО50",
41850:"ТО50",
41900:"ТО50",
41950:"ТО50",
42000:"ТО3000",
42050:"ТО50",
42100:"ТО50",
42150:"ТО50",
42200:"ТО50",
42250:"ТО250",
42300:"ТО50",
42350:"ТО50",
42400:"ТО50",
42450:"ТО50",
42500:"ТО500",
42550:"ТО50",
42600:"ТО50",
42650:"ТО50",
42700:"ТО50",
42750:"ТО250",
42800:"ТО50",
42850:"ТО50",
42900:"ТО50",
42950:"ТО50",
43000:"ТО1000",
43050:"ТО50",
43100:"ТО50",
43150:"ТО50",
43200:"ТО50",
43250:"ТО250",
43300:"ТО50",
43350:"ТО50",
43400:"ТО50",
43450:"ТО50",
43500:"ТО500",
43550:"ТО50",
43600:"ТО50",
43650:"ТО50",
43700:"ТО50",
43750:"ТО250",
43800:"ТО50",
43850:"ТО50",
43900:"ТО50",
43950:"ТО50",
44000:"ТО4000",
44050:"ТО50",
44100:"ТО50",
44150:"ТО50",
44200:"ТО50",
44250:"ТО250",
44300:"ТО50",
44350:"ТО50",
44400:"ТО50",
44450:"ТО50",
44500:"ТО500",
44550:"ТО50",
44600:"ТО50",
44650:"ТО50",
44700:"ТО50",
44750:"ТО250",
44800:"ТО50",
44850:"ТО50",
44900:"ТО50",
44950:"ТО50",
45000:"ТО3000/5000",
45050:"ТО50",
45100:"ТО50",
45150:"ТО50",
45200:"ТО50",
45250:"ТО250",
45300:"ТО50",
45350:"ТО50",
45400:"ТО50",
45450:"ТО50",
45500:"ТО500",
45550:"ТО50",
45600:"ТО50",
45650:"ТО50",
45700:"ТО50",
45750:"ТО250",
45800:"ТО50",
45850:"ТО50",
45900:"ТО50",
45950:"ТО50",
46000:"ТО2000",
46050:"ТО50",
46100:"ТО50",
46150:"ТО50",
46200:"ТО50",
46250:"ТО250",
46300:"ТО50",
46350:"ТО50",
46400:"ТО50",
46450:"ТО50",
46500:"ТО500",
46550:"ТО50",
46600:"ТО50",
46650:"ТО50",
46700:"ТО50",
46750:"ТО250",
46800:"ТО50",
46850:"ТО50",
46900:"ТО50",
46950:"ТО50",
47000:"ТО1000",
47050:"ТО50",
47100:"ТО50",
47150:"ТО50",
47200:"ТО50",
47250:"ТО250",
47300:"ТО50",
47350:"ТО50",
47400:"ТО50",
47450:"ТО50",
47500:"ТО500",
47550:"ТО50",
47600:"ТО50",
47650:"ТО50",
47700:"ТО50",
47750:"ТО250",
47800:"ТО50",
47850:"ТО50",
47900:"ТО50",
47950:"ТО50",
48000:"ТО3000/4000"

    
}

In [57]:
to_dict_sl={
    50:"",
100:"",
150:"",
200:"",
250:"ТО250",
300:"",
350:"",
400:"",
450:"",
500:"ТО500",
550:"",
600:"",
650:"",
700:"",
750:"ТО250",
800:"",
850:"",
900:"",
950:"",
1000:"ТО1000",
1050:"",
1100:"",
1150:"",
1200:"",
1250:"ТО250",
1300:"",
1350:"",
1400:"",
1450:"",
1500:"ТО500",
1550:"",
1600:"",
1650:"",
1700:"",
1750:"ТО250",
1800:"",
1850:"",
1900:"",
1950:"",
2000:"ТО2000",
2050:"",
2100:"",
2150:"",
2200:"",
2250:"ТО250",
2300:"",
2350:"",
2400:"",
2450:"",
2500:"ТО2500",
2550:"",
2600:"",
2650:"",
2700:"",
2750:"ТО250",
2800:"",
2850:"",
2900:"",
2950:"",
3000:"ТО1000",
3050:"",
3100:"",
3150:"",
3200:"",
3250:"ТО250",
3300:"",
3350:"",
3400:"",
3450:"",
3500:"ТО500",
3550:"",
3600:"",
3650:"",
3700:"",
3750:"ТО250",
3800:"",
3850:"",
3900:"",
3950:"",
4000:"ТО4000",
4050:"",
4100:"",
4150:"",
4200:"",
4250:"ТО250",
4300:"",
4350:"",
4400:"",
4450:"",
4500:"ТО500",
4550:"",
4600:"",
4650:"",
4700:"",
4750:"ТО250",
4800:"",
4850:"",
4900:"",
4950:"",
5000:"ТО1000/2500",
5050:"",
5100:"",
5150:"",
5200:"",
5250:"ТО250",
5300:"",
5350:"",
5400:"",
5450:"",
5500:"ТО500",
5550:"",
5600:"",
5650:"",
5700:"",
5750:"ТО250",
5800:"",
5850:"",
5900:"",
5950:"",
6000:"ТО2000",
6050:"",
6100:"",
6150:"",
6200:"",
6250:"ТО250",
6300:"",
6350:"",
6400:"",
6450:"",
6500:"ТО500",
6550:"",
6600:"",
6650:"",
6700:"",
6750:"ТО250",
6800:"",
6850:"",
6900:"",
6950:"",
7000:"ТО1000",
7050:"",
7100:"",
7150:"",
7200:"",
7250:"ТО250",
7300:"",
7350:"",
7400:"",
7450:"",
7500:"ТО2500",
7550:"",
7600:"",
7650:"",
7700:"",
7750:"ТО250",
7800:"",
7850:"",
7900:"",
7950:"",
8000:"ТО4000",
8050:"",
8100:"",
8150:"",
8200:"",
8250:"ТО250",
8300:"",
8350:"",
8400:"",
8450:"",
8500:"ТО500",
8550:"",
8600:"",
8650:"",
8700:"",
8750:"ТО250",
8800:"",
8850:"",
8900:"",
8950:"",
9000:"ТО1000",
9050:"",
9100:"",
9150:"",
9200:"",
9250:"ТО250",
9300:"",
9350:"",
9400:"",
9450:"",
9500:"ТО500",
9550:"",
9600:"",
9650:"",
9700:"",
9750:"ТО250",
9800:"",
9850:"",
9900:"",
9950:"",
10000:"ТО2500",
10050:"",
10100:"",
10150:"",
10200:"",
10250:"ТО250",
10300:"",
10350:"",
10400:"",
10450:"",
10500:"ТО500",
10550:"",
10600:"",
10650:"",
10700:"",
10750:"ТО250",
10800:"",
10850:"",
10900:"",
10950:"",
11000:"ТО1000",
11050:"",
11100:"",
11150:"",
11200:"",
11250:"ТО250",
11300:"",
11350:"",
11400:"",
11450:"",
11500:"ТО500",
11550:"",
11600:"",
11650:"",
11700:"",
11750:"ТО250",
11800:"",
11850:"",
11900:"",
11950:"",
12000:"ТО4000",
12050:"",
12100:"",
12150:"",
12200:"",
12250:"ТО250",
12300:"",
12350:"",
12400:"",
12450:"",
12500:"ТО2500",
12550:"",
12600:"",
12650:"",
12700:"",
12750:"ТО250",
12800:"",
12850:"",
12900:"",
12950:"",
13000:"ТО1000",
13050:"",
13100:"",
13150:"",
13200:"",
13250:"ТО250",
13300:"",
13350:"",
13400:"",
13450:"",
13500:"ТО500",
13550:"",
13600:"",
13650:"",
13700:"",
13750:"ТО250",
13800:"",
13850:"",
13900:"",
13950:"",
14000:"ТО2000",
14050:"",
14100:"",
14150:"",
14200:"",
14250:"ТО250",
14300:"",
14350:"",
14400:"",
14450:"",
14500:"ТО500",
14550:"",
14600:"",
14650:"",
14700:"",
14750:"ТО250",
14800:"",
14850:"",
14900:"",
14950:"",
15000:"ТО1000/2500",
15050:"",
15100:"",
15150:"",
15200:"",
15250:"ТО250",
15300:"",
15350:"",
15400:"",
15450:"",
15500:"ТО500",
15550:"",
15600:"",
15650:"",
15700:"",
15750:"ТО250",
15800:"",
15850:"",
15900:"",
15950:"",
16000:"ТО4000",
16050:"",
16100:"",
16150:"",
16200:"",
16250:"ТО250",
16300:"",
16350:"",
16400:"",
16450:"",
16500:"ТО500",
16550:"",
16600:"",
16650:"",
16700:"",
16750:"ТО250",
16800:"",
16850:"",
16900:"",
16950:"",
17000:"ТО1000",
17050:"",
17100:"",
17150:"",
17200:"",
17250:"ТО250",
17300:"",
17350:"",
17400:"",
17450:"",
17500:"ТО2500",
17550:"",
17600:"",
17650:"",
17700:"",
17750:"ТО250",
17800:"",
17850:"",
17900:"",
17950:"",
18000:"ТО2000",
18050:"",
18100:"",
18150:"",
18200:"",
18250:"ТО250",
18300:"",
18350:"",
18400:"",
18450:"",
18500:"ТО500",
18550:"",
18600:"",
18650:"",
18700:"",
18750:"ТО250",
18800:"",
18850:"",
18900:"",
18950:"",
19000:"ТО1000",
19050:"",
19100:"",
19150:"",
19200:"",
19250:"ТО250",
19300:"",
19350:"",
19400:"",
19450:"",
19500:"ТО500",
19550:"",
19600:"",
19650:"",
19700:"",
19750:"ТО250",
19800:"",
19850:"",
19900:"",
19950:"",
20000:"ТО2500/4000",
20050:"",
20100:"",
20150:"",
20200:"",
20250:"ТО250",
20300:"",
20350:"",
20400:"",
20450:"",
20500:"ТО500",
20550:"",
20600:"",
20650:"",
20700:"",
20750:"ТО250",
20800:"",
20850:"",
20900:"",
20950:"",
21000:"ТО1000",
21050:"",
21100:"",
21150:"",
21200:"",
21250:"ТО250",
21300:"",
21350:"",
21400:"",
21450:"",
21500:"ТО500",
21550:"",
21600:"",
21650:"",
21700:"",
21750:"ТО250",
21800:"",
21850:"",
21900:"",
21950:"",
22000:"ТО2000",
22050:"",
22100:"",
22150:"",
22200:"",
22250:"ТО250",
22300:"",
22350:"",
22400:"",
22450:"",
22500:"ТО2500",
22550:"",
22600:"",
22650:"",
22700:"",
22750:"ТО250",
22800:"",
22850:"",
22900:"",
22950:"",
23000:"ТО1000",
23050:"",
23100:"",
23150:"",
23200:"",
23250:"ТО250",
23300:"",
23350:"",
23400:"",
23450:"",
23500:"ТО500",
23550:"",
23600:"",
23650:"",
23700:"",
23750:"ТО250",
23800:"",
23850:"",
23900:"",
23950:"",
24000:"ТО4000",
24050:"",
24100:"",
24150:"",
24200:"",
24250:"ТО250",
24300:"",
24350:"",
24400:"",
24450:"",
24500:"ТО500",
24550:"",
24600:"",
24650:"",
24700:"",
24750:"ТО250",
24800:"",
24850:"",
24900:"",
24950:"",
25000:"ТО1000/2500",
25050:"",
25100:"",
25150:"",
25200:"",
25250:"ТО250",
25300:"",
25350:"",
25400:"",
25450:"",
25500:"ТО500",
25550:"",
25600:"",
25650:"",
25700:"",
25750:"ТО250",
25800:"",
25850:"",
25900:"",
25950:"",
26000:"ТО2000",
26050:"",
26100:"",
26150:"",
26200:"",
26250:"ТО250",
26300:"",
26350:"",
26400:"",
26450:"",
26500:"ТО500",
26550:"",
26600:"",
26650:"",
26700:"",
26750:"ТО250",
26800:"",
26850:"",
26900:"",
26950:"",
27000:"ТО1000",
27050:"",
27100:"",
27150:"",
27200:"",
27250:"ТО250",
27300:"",
27350:"",
27400:"",
27450:"",
27500:"ТО2500",
27550:"",
27600:"",
27650:"",
27700:"",
27750:"ТО250",
27800:"",
27850:"",
27900:"",
27950:"",
28000:"ТО4000",
28050:"",
28100:"",
28150:"",
28200:"",
28250:"ТО250",
28300:"",
28350:"",
28400:"",
28450:"",
28500:"ТО500",
28550:"",
28600:"",
28650:"",
28700:"",
28750:"ТО250",
28800:"",
28850:"",
28900:"",
28950:"",
29000:"ТО1000",
29050:"",
29100:"",
29150:"",
29200:"",
29250:"ТО250",
29300:"",
29350:"",
29400:"",
29450:"",
29500:"ТО500",
29550:"",
29600:"",
29650:"",
29700:"",
29750:"ТО250",
29800:"",
29850:"",
29900:"",
29950:"",
30000:"ТО2000/2500",
30050:"",
30100:"",
30150:"",
30200:"",
30250:"ТО250",
30300:"",
30350:"",
30400:"",
30450:"",
30500:"ТО500",
30550:"",
30600:"",
30650:"",
30700:"",
30750:"ТО250",
30800:"",
30850:"",
30900:"",
30950:"",
31000:"ТО1000",
31050:"",
31100:"",
31150:"",
31200:"",
31250:"ТО250",
31300:"",
31350:"",
31400:"",
31450:"",
31500:"ТО500",
31550:"",
31600:"",
31650:"",
31700:"",
31750:"ТО250",
31800:"",
31850:"",
31900:"",
31950:"",
32000:"ТО4000",
32050:"",
32100:"",
32150:"",
32200:"",
32250:"ТО250",
32300:"",
32350:"",
32400:"",
32450:"",
32500:"ТО2500",
32550:"",
32600:"",
32650:"",
32700:"",
32750:"ТО250",
32800:"",
32850:"",
32900:"",
32950:"",
33000:"ТО1000",
33050:"",
33100:"",
33150:"",
33200:"",
33250:"ТО250",
33300:"",
33350:"",
33400:"",
33450:"",
33500:"ТО500",
33550:"",
33600:"",
33650:"",
33700:"",
33750:"ТО250",
33800:"",
33850:"",
33900:"",
33950:"",
34000:"ТО2000",
34050:"",
34100:"",
34150:"",
34200:"",
34250:"ТО250",
34300:"",
34350:"",
34400:"",
34450:"",
34500:"ТО500",
34550:"",
34600:"",
34650:"",
34700:"",
34750:"ТО250",
34800:"",
34850:"",
34900:"",
34950:"",
35000:"ТО1000/2500",
35050:"",
35100:"",
35150:"",
35200:"",
35250:"ТО250",
35300:"",
35350:"",
35400:"",
35450:"",
35500:"ТО500",
35550:"",
35600:"",
35650:"",
35700:"",
35750:"ТО250",
35800:"",
35850:"",
35900:"",
35950:"",
36000:"ТО4000",
36050:"",
36100:"",
36150:"",
36200:"",
36250:"ТО250",
36300:"",
36350:"",
36400:"",
36450:"",
36500:"ТО500",
36550:"",
36600:"",
36650:"",
36700:"",
36750:"ТО250",
36800:"",
36850:"",
36900:"",
36950:"",
37000:"ТО1000",
37050:"",
37100:"",
37150:"",
37200:"",
37250:"ТО250",
37300:"",
37350:"",
37400:"",
37450:"",
37500:"ТО2500",
37550:"",
37600:"",
37650:"",
37700:"",
37750:"ТО250",
37800:"",
37850:"",
37900:"",
37950:"",
38000:"ТО2000",
38050:"",
38100:"",
38150:"",
38200:"",
38250:"ТО250",
38300:"",
38350:"",
38400:"",
38450:"",
38500:"ТО500",
38550:"",
38600:"",
38650:"",
38700:"",
38750:"ТО250",
38800:"",
38850:"",
38900:"",
38950:"",
39000:"ТО1000",
39050:"",
39100:"",
39150:"",
39200:"",
39250:"ТО250",
39300:"",
39350:"",
39400:"",
39450:"",
39500:"ТО500",
39550:"",
39600:"",
39650:"",
39700:"",
39750:"ТО250",
39800:"",
39850:"",
39900:"",
39950:"",
40000:"ТО2500/4000",
40050:"",
40100:"",
40150:"",
40200:"",
40250:"ТО250",
40300:"",
40350:"",
40400:"",
40450:"",
40500:"ТО500",
40550:"",
40600:"",
40650:"",
40700:"",
40750:"ТО250",
40800:"",
40850:"",
40900:"",
40950:"",
41000:"ТО1000",
41050:"",
41100:"",
41150:"",
41200:"",
41250:"ТО250",
41300:"",
41350:"",
41400:"",
41450:"",
41500:"ТО500",
41550:"",
41600:"",
41650:"",
41700:"",
41750:"ТО250",
41800:"",
41850:"",
41900:"",
41950:"",
42000:"ТО2000",
42050:"",
42100:"",
42150:"",
42200:"",
42250:"ТО250",
42300:"",
42350:"",
42400:"",
42450:"",
42500:"ТО2500",
42550:"",
42600:"",
42650:"",
42700:"",
42750:"ТО250",
42800:"",
42850:"",
42900:"",
42950:"",
43000:"ТО1000",
43050:"",
43100:"",
43150:"",
43200:"",
43250:"ТО250",
43300:"",
43350:"",
43400:"",
43450:"",
43500:"ТО500",
43550:"",
43600:"",
43650:"",
43700:"",
43750:"ТО250",
43800:"",
43850:"",
43900:"",
43950:"",
44000:"ТО4000",
44050:"",
44100:"",
44150:"",
44200:"",
44250:"ТО250",
44300:"",
44350:"",
44400:"",
44450:"",
44500:"ТО500",
44550:"",
44600:"",
44650:"",
44700:"",
44750:"ТО250",
44800:"",
44850:"",
44900:"",
44950:"",
45000:"ТО1000/2500",
45050:"",
45100:"",
45150:"",
45200:"",
45250:"ТО250",
45300:"",
45350:"",
45400:"",
45450:"",
45500:"ТО500",
45550:"",
45600:"",
45650:"",
45700:"",
45750:"ТО250",
45800:"",
45850:"",
45900:"",
45950:"",
46000:"ТО2000",
46050:"",
46100:"",
46150:"",
46200:"",
46250:"ТО250",
46300:"",
46350:"",
46400:"",
46450:"",
46500:"ТО500",
46550:"",
46600:"",
46650:"",
46700:"",
46750:"ТО250",
46800:"",
46850:"",
46900:"",
46950:"",
47000:"ТО1000",
47050:"",
47100:"",
47150:"",
47200:"",
47250:"ТО250",
47300:"",
47350:"",
47400:"",
47450:"",
47500:"ТО2500",
47550:"",
47600:"",
47650:"",
47700:"",
47750:"ТО250",
47800:"",
47850:"",
47900:"",
47950:"",
48000:"ТО4000"

    
}

In [58]:
to_dict_b11={
    50:"",
100:"",
150:"",
200:"",
250:"ТО250",
300:"",
350:"",
400:"",
450:"",
500:"ТО500",
550:"",
600:"",
650:"",
700:"",
750:"ТО250",
800:"",
850:"",
900:"",
950:"",
1000:"ТО1000",
1050:"",
1100:"",
1150:"",
1200:"",
1250:"ТО250",
1300:"",
1350:"",
1400:"",
1450:"",
1500:"ТО500",
1550:"",
1600:"",
1650:"",
1700:"",
1750:"ТО250",
1800:"",
1850:"",
1900:"",
1950:"",
2000:"ТО2000",
2050:"",
2100:"",
2150:"",
2200:"",
2250:"ТО250",
2300:"",
2350:"",
2400:"",
2450:"",
2500:"ТО500",
2550:"",
2600:"",
2650:"",
2700:"",
2750:"ТО250",
2800:"",
2850:"",
2900:"",
2950:"",
3000:"ТО1000",
3050:"",
3100:"",
3150:"",
3200:"",
3250:"ТО250",
3300:"",
3350:"",
3400:"",
3450:"",
3500:"ТО500",
3550:"",
3600:"",
3650:"",
3700:"",
3750:"ТО250",
3800:"",
3850:"",
3900:"",
3950:"",
4000:"ТО4000",
4050:"",
4100:"",
4150:"",
4200:"",
4250:"ТО250",
4300:"",
4350:"",
4400:"",
4450:"",
4500:"ТО500",
4550:"",
4600:"",
4650:"",
4700:"",
4750:"ТО250",
4800:"",
4850:"",
4900:"",
4950:"",
5000:"ТО1000",
5050:"",
5100:"",
5150:"",
5200:"",
5250:"ТО250",
5300:"",
5350:"",
5400:"",
5450:"",
5500:"ТО500",
5550:"",
5600:"",
5650:"",
5700:"",
5750:"ТО250",
5800:"",
5850:"",
5900:"",
5950:"",
6000:"ТО2000",
6050:"",
6100:"",
6150:"",
6200:"",
6250:"ТО250",
6300:"",
6350:"",
6400:"",
6450:"",
6500:"ТО500",
6550:"",
6600:"",
6650:"",
6700:"",
6750:"ТО250",
6800:"",
6850:"",
6900:"",
6950:"",
7000:"ТО1000",
7050:"",
7100:"",
7150:"",
7200:"",
7250:"ТО250",
7300:"",
7350:"",
7400:"",
7450:"",
7500:"ТО500",
7550:"",
7600:"",
7650:"",
7700:"",
7750:"ТО250",
7800:"",
7850:"",
7900:"",
7950:"",
8000:"ТО4000",
8050:"",
8100:"",
8150:"",
8200:"",
8250:"ТО250",
8300:"",
8350:"",
8400:"",
8450:"",
8500:"ТО500",
8550:"",
8600:"",
8650:"",
8700:"",
8750:"ТО250",
8800:"",
8850:"",
8900:"",
8950:"",
9000:"ТО1000",
9050:"",
9100:"",
9150:"",
9200:"",
9250:"ТО250",
9300:"",
9350:"",
9400:"",
9450:"",
9500:"ТО500",
9550:"",
9600:"",
9650:"",
9700:"",
9750:"ТО250",
9800:"",
9850:"",
9900:"",
9950:"",
10000:"ТО2000",
10050:"",
10100:"",
10150:"",
10200:"",
10250:"ТО250",
10300:"",
10350:"",
10400:"",
10450:"",
10500:"ТО500",
10550:"",
10600:"",
10650:"",
10700:"",
10750:"ТО250",
10800:"",
10850:"",
10900:"",
10950:"",
11000:"ТО1000",
11050:"",
11100:"",
11150:"",
11200:"",
11250:"ТО250",
11300:"",
11350:"",
11400:"",
11450:"",
11500:"ТО500",
11550:"",
11600:"",
11650:"",
11700:"",
11750:"ТО250",
11800:"",
11850:"",
11900:"",
11950:"",
12000:"ТО4000",
12050:"",
12100:"",
12150:"",
12200:"",
12250:"ТО250",
12300:"",
12350:"",
12400:"",
12450:"",
12500:"ТО500",
12550:"",
12600:"",
12650:"",
12700:"",
12750:"ТО250",
12800:"",
12850:"",
12900:"",
12950:"",
13000:"ТО1000",
13050:"",
13100:"",
13150:"",
13200:"",
13250:"ТО250",
13300:"",
13350:"",
13400:"",
13450:"",
13500:"ТО500",
13550:"",
13600:"",
13650:"",
13700:"",
13750:"ТО250",
13800:"",
13850:"",
13900:"",
13950:"",
14000:"ТО2000",
14050:"",
14100:"",
14150:"",
14200:"",
14250:"ТО250",
14300:"",
14350:"",
14400:"",
14450:"",
14500:"ТО500",
14550:"",
14600:"",
14650:"",
14700:"",
14750:"ТО250",
14800:"",
14850:"",
14900:"",
14950:"",
15000:"ТО1000",
15050:"",
15100:"",
15150:"",
15200:"",
15250:"ТО250",
15300:"",
15350:"",
15400:"",
15450:"",
15500:"ТО500",
15550:"",
15600:"",
15650:"",
15700:"",
15750:"ТО250",
15800:"",
15850:"",
15900:"",
15950:"",
16000:"ТО4000",
16050:"",
16100:"",
16150:"",
16200:"",
16250:"ТО250",
16300:"",
16350:"",
16400:"",
16450:"",
16500:"ТО500",
16550:"",
16600:"",
16650:"",
16700:"",
16750:"ТО250",
16800:"",
16850:"",
16900:"",
16950:"",
17000:"ТО1000",
17050:"",
17100:"",
17150:"",
17200:"",
17250:"ТО250",
17300:"",
17350:"",
17400:"",
17450:"",
17500:"ТО500",
17550:"",
17600:"",
17650:"",
17700:"",
17750:"ТО250",
17800:"",
17850:"",
17900:"",
17950:"",
18000:"ТО2000",
18050:"",
18100:"",
18150:"",
18200:"",
18250:"ТО250",
18300:"",
18350:"",
18400:"",
18450:"",
18500:"ТО500",
18550:"",
18600:"",
18650:"",
18700:"",
18750:"ТО250",
18800:"",
18850:"",
18900:"",
18950:"",
19000:"ТО1000",
19050:"",
19100:"",
19150:"",
19200:"",
19250:"ТО250",
19300:"",
19350:"",
19400:"",
19450:"",
19500:"ТО500",
19550:"",
19600:"",
19650:"",
19700:"",
19750:"ТО250",
19800:"",
19850:"",
19900:"",
19950:"",
20000:"ТО4000",
20050:"",
20100:"",
20150:"",
20200:"",
20250:"ТО250",
20300:"",
20350:"",
20400:"",
20450:"",
20500:"ТО500",
20550:"",
20600:"",
20650:"",
20700:"",
20750:"ТО250",
20800:"",
20850:"",
20900:"",
20950:"",
21000:"ТО1000",
21050:"",
21100:"",
21150:"",
21200:"",
21250:"ТО250",
21300:"",
21350:"",
21400:"",
21450:"",
21500:"ТО500",
21550:"",
21600:"",
21650:"",
21700:"",
21750:"ТО250",
21800:"",
21850:"",
21900:"",
21950:"",
22000:"ТО2000",
22050:"",
22100:"",
22150:"",
22200:"",
22250:"ТО250",
22300:"",
22350:"",
22400:"",
22450:"",
22500:"ТО500",
22550:"",
22600:"",
22650:"",
22700:"",
22750:"ТО250",
22800:"",
22850:"",
22900:"",
22950:"",
23000:"ТО1000",
23050:"",
23100:"",
23150:"",
23200:"",
23250:"ТО250",
23300:"",
23350:"",
23400:"",
23450:"",
23500:"ТО500",
23550:"",
23600:"",
23650:"",
23700:"",
23750:"ТО250",
23800:"",
23850:"",
23900:"",
23950:"",
24000:"ТО4000",
24050:"",
24100:"",
24150:"",
24200:"",
24250:"ТО250",
24300:"",
24350:"",
24400:"",
24450:"",
24500:"ТО500",
24550:"",
24600:"",
24650:"",
24700:"",
24750:"ТО250",
24800:"",
24850:"",
24900:"",
24950:"",
25000:"ТО1000",
25050:"",
25100:"",
25150:"",
25200:"",
25250:"ТО250",
25300:"",
25350:"",
25400:"",
25450:"",
25500:"ТО500",
25550:"",
25600:"",
25650:"",
25700:"",
25750:"ТО250",
25800:"",
25850:"",
25900:"",
25950:"",
26000:"ТО2000",
26050:"",
26100:"",
26150:"",
26200:"",
26250:"ТО250",
26300:"",
26350:"",
26400:"",
26450:"",
26500:"ТО500",
26550:"",
26600:"",
26650:"",
26700:"",
26750:"ТО250",
26800:"",
26850:"",
26900:"",
26950:"",
27000:"ТО1000",
27050:"",
27100:"",
27150:"",
27200:"",
27250:"ТО250",
27300:"",
27350:"",
27400:"",
27450:"",
27500:"ТО500",
27550:"",
27600:"",
27650:"",
27700:"",
27750:"ТО250",
27800:"",
27850:"",
27900:"",
27950:"",
28000:"ТО4000",
28050:"",
28100:"",
28150:"",
28200:"",
28250:"ТО250",
28300:"",
28350:"",
28400:"",
28450:"",
28500:"ТО500",
28550:"",
28600:"",
28650:"",
28700:"",
28750:"ТО250",
28800:"",
28850:"",
28900:"",
28950:"",
29000:"ТО1000",
29050:"",
29100:"",
29150:"",
29200:"",
29250:"ТО250",
29300:"",
29350:"",
29400:"",
29450:"",
29500:"ТО500",
29550:"",
29600:"",
29650:"",
29700:"",
29750:"ТО250",
29800:"",
29850:"",
29900:"",
29950:"",
30000:"ТО2000",
30050:"",
30100:"",
30150:"",
30200:"",
30250:"ТО250",
30300:"",
30350:"",
30400:"",
30450:"",
30500:"ТО500",
30550:"",
30600:"",
30650:"",
30700:"",
30750:"ТО250",
30800:"",
30850:"",
30900:"",
30950:"",
31000:"ТО1000",
31050:"",
31100:"",
31150:"",
31200:"",
31250:"ТО250",
31300:"",
31350:"",
31400:"",
31450:"",
31500:"ТО500",
31550:"",
31600:"",
31650:"",
31700:"",
31750:"ТО250",
31800:"",
31850:"",
31900:"",
31950:"",
32000:"ТО4000",
32050:"",
32100:"",
32150:"",
32200:"",
32250:"ТО250",
32300:"",
32350:"",
32400:"",
32450:"",
32500:"ТО500",
32550:"",
32600:"",
32650:"",
32700:"",
32750:"ТО250",
32800:"",
32850:"",
32900:"",
32950:"",
33000:"ТО1000",
33050:"",
33100:"",
33150:"",
33200:"",
33250:"ТО250",
33300:"",
33350:"",
33400:"",
33450:"",
33500:"ТО500",
33550:"",
33600:"",
33650:"",
33700:"",
33750:"ТО250",
33800:"",
33850:"",
33900:"",
33950:"",
34000:"ТО2000",
34050:"",
34100:"",
34150:"",
34200:"",
34250:"ТО250",
34300:"",
34350:"",
34400:"",
34450:"",
34500:"ТО500",
34550:"",
34600:"",
34650:"",
34700:"",
34750:"ТО250",
34800:"",
34850:"",
34900:"",
34950:"",
35000:"ТО1000",
35050:"",
35100:"",
35150:"",
35200:"",
35250:"ТО250",
35300:"",
35350:"",
35400:"",
35450:"",
35500:"ТО500",
35550:"",
35600:"",
35650:"",
35700:"",
35750:"ТО250",
35800:"",
35850:"",
35900:"",
35950:"",
36000:"ТО4000",
36050:"",
36100:"",
36150:"",
36200:"",
36250:"ТО250",
36300:"",
36350:"",
36400:"",
36450:"",
36500:"ТО500",
36550:"",
36600:"",
36650:"",
36700:"",
36750:"ТО250",
36800:"",
36850:"",
36900:"",
36950:"",
37000:"ТО1000",
37050:"",
37100:"",
37150:"",
37200:"",
37250:"ТО250",
37300:"",
37350:"",
37400:"",
37450:"",
37500:"ТО500",
37550:"",
37600:"",
37650:"",
37700:"",
37750:"ТО250",
37800:"",
37850:"",
37900:"",
37950:"",
38000:"ТО2000",
38050:"",
38100:"",
38150:"",
38200:"",
38250:"ТО250",
38300:"",
38350:"",
38400:"",
38450:"",
38500:"ТО500",
38550:"",
38600:"",
38650:"",
38700:"",
38750:"ТО250",
38800:"",
38850:"",
38900:"",
38950:"",
39000:"ТО1000",
39050:"",
39100:"",
39150:"",
39200:"",
39250:"ТО250",
39300:"",
39350:"",
39400:"",
39450:"",
39500:"ТО500",
39550:"",
39600:"",
39650:"",
39700:"",
39750:"ТО250",
39800:"",
39850:"",
39900:"",
39950:"",
40000:"ТО4000",
40050:"",
40100:"",
40150:"",
40200:"",
40250:"ТО250",
40300:"",
40350:"",
40400:"",
40450:"",
40500:"ТО500",
40550:"",
40600:"",
40650:"",
40700:"",
40750:"ТО250",
40800:"",
40850:"",
40900:"",
40950:"",
41000:"ТО1000",
41050:"",
41100:"",
41150:"",
41200:"",
41250:"ТО250",
41300:"",
41350:"",
41400:"",
41450:"",
41500:"ТО500",
41550:"",
41600:"",
41650:"",
41700:"",
41750:"ТО250",
41800:"",
41850:"",
41900:"",
41950:"",
42000:"ТО2000",
42050:"",
42100:"",
42150:"",
42200:"",
42250:"ТО250",
42300:"",
42350:"",
42400:"",
42450:"",
42500:"ТО500",
42550:"",
42600:"",
42650:"",
42700:"",
42750:"ТО250",
42800:"",
42850:"",
42900:"",
42950:"",
43000:"ТО1000",
43050:"",
43100:"",
43150:"",
43200:"",
43250:"ТО250",
43300:"",
43350:"",
43400:"",
43450:"",
43500:"ТО500",
43550:"",
43600:"",
43650:"",
43700:"",
43750:"ТО250",
43800:"",
43850:"",
43900:"",
43950:"",
44000:"ТО4000",
44050:"",
44100:"",
44150:"",
44200:"",
44250:"ТО250",
44300:"",
44350:"",
44400:"",
44450:"",
44500:"ТО500",
44550:"",
44600:"",
44650:"",
44700:"",
44750:"ТО250",
44800:"",
44850:"",
44900:"",
44950:"",
45000:"ТО1000",
45050:"",
45100:"",
45150:"",
45200:"",
45250:"ТО250",
45300:"",
45350:"",
45400:"",
45450:"",
45500:"ТО500",
45550:"",
45600:"",
45650:"",
45700:"",
45750:"ТО250",
45800:"",
45850:"",
45900:"",
45950:"",
46000:"ТО2000",
46050:"",
46100:"",
46150:"",
46200:"",
46250:"ТО250",
46300:"",
46350:"",
46400:"",
46450:"",
46500:"ТО500",
46550:"",
46600:"",
46650:"",
46700:"",
46750:"ТО250",
46800:"",
46850:"",
46900:"",
46950:"",
47000:"ТО1000",
47050:"",
47100:"",
47150:"",
47200:"",
47250:"ТО250",
47300:"",
47350:"",
47400:"",
47450:"",
47500:"ТО500",
47550:"",
47600:"",
47650:"",
47700:"",
47750:"ТО250",
47800:"",
47850:"",
47900:"",
47950:"",
48000:"ТО4000"

    
}

In [59]:
to_dict_sbh={
    50:"ТО50",
100:"ТО50",
150:"ТО50",
200:"ТО50",
250:"ТО250",
300:"ТО50",
350:"ТО50",
400:"ТО50",
450:"ТО50",
500:"ТО250",
550:"ТО50",
600:"ТО50",
650:"ТО50",
700:"ТО50",
750:"ТО250",
800:"ТО50",
850:"ТО50",
900:"ТО50",
950:"ТО50",
1000:"ТО1000",
1050:"ТО50",
1100:"ТО50",
1150:"ТО50",
1200:"ТО50",
1250:"ТО250",
1300:"ТО50",
1350:"ТО50",
1400:"ТО50",
1450:"ТО50",
1500:"ТО250",
1550:"ТО50",
1600:"ТО50",
1650:"ТО50",
1700:"ТО50",
1750:"ТО250",
1800:"ТО50",
1850:"ТО50",
1900:"ТО50",
1950:"ТО50",
2000:"ТО2000",
2050:"ТО50",
2100:"ТО50",
2150:"ТО50",
2200:"ТО50",
2250:"ТО250",
2300:"ТО50",
2350:"ТО50",
2400:"ТО50",
2450:"ТО50",
2500:"ТО250",
2550:"ТО50",
2600:"ТО50",
2650:"ТО50",
2700:"ТО50",
2750:"ТО250",
2800:"ТО50",
2850:"ТО50",
2900:"ТО50",
2950:"ТО50",
3000:"ТО1000",
3050:"ТО50",
3100:"ТО50",
3150:"ТО50",
3200:"ТО50",
3250:"ТО250",
3300:"ТО50",
3350:"ТО50",
3400:"ТО50",
3450:"ТО50",
3500:"ТО250",
3550:"ТО50",
3600:"ТО50",
3650:"ТО50",
3700:"ТО50",
3750:"ТО250",
3800:"ТО50",
3850:"ТО50",
3900:"ТО50",
3950:"ТО50",
4000:"ТО2000",
4050:"ТО50",
4100:"ТО50",
4150:"ТО50",
4200:"ТО50",
4250:"ТО250",
4300:"ТО50",
4350:"ТО50",
4400:"ТО50",
4450:"ТО50",
4500:"ТО250",
4550:"ТО50",
4600:"ТО50",
4650:"ТО50",
4700:"ТО50",
4750:"ТО250",
4800:"ТО50",
4850:"ТО50",
4900:"ТО50",
4950:"ТО50",
5000:"ТО1000",
5050:"ТО50",
5100:"ТО50",
5150:"ТО50",
5200:"ТО50",
5250:"ТО250",
5300:"ТО50",
5350:"ТО50",
5400:"ТО50",
5450:"ТО50",
5500:"ТО250",
5550:"ТО50",
5600:"ТО50",
5650:"ТО50",
5700:"ТО50",
5750:"ТО250",
5800:"ТО50",
5850:"ТО50",
5900:"ТО50",
5950:"ТО50",
6000:"ТО2000",
6050:"ТО50",
6100:"ТО50",
6150:"ТО50",
6200:"ТО50",
6250:"ТО250",
6300:"ТО50",
6350:"ТО50",
6400:"ТО50",
6450:"ТО50",
6500:"ТО250",
6550:"ТО50",
6600:"ТО50",
6650:"ТО50",
6700:"ТО50",
6750:"ТО250",
6800:"ТО50",
6850:"ТО50",
6900:"ТО50",
6950:"ТО50",
7000:"ТО1000",
7050:"ТО50",
7100:"ТО50",
7150:"ТО50",
7200:"ТО50",
7250:"ТО250",
7300:"ТО50",
7350:"ТО50",
7400:"ТО50",
7450:"ТО50",
7500:"ТО250",
7550:"ТО50",
7600:"ТО50",
7650:"ТО50",
7700:"ТО50",
7750:"ТО250",
7800:"ТО50",
7850:"ТО50",
7900:"ТО50",
7950:"ТО50",
8000:"ТО2000",
8050:"ТО50",
8100:"ТО50",
8150:"ТО50",
8200:"ТО50",
8250:"ТО250",
8300:"ТО50",
8350:"ТО50",
8400:"ТО50",
8450:"ТО50",
8500:"ТО250",
8550:"ТО50",
8600:"ТО50",
8650:"ТО50",
8700:"ТО50",
8750:"ТО250",
8800:"ТО50",
8850:"ТО50",
8900:"ТО50",
8950:"ТО50",
9000:"ТО1000",
9050:"ТО50",
9100:"ТО50",
9150:"ТО50",
9200:"ТО50",
9250:"ТО250",
9300:"ТО50",
9350:"ТО50",
9400:"ТО50",
9450:"ТО50",
9500:"ТО250",
9550:"ТО50",
9600:"ТО50",
9650:"ТО50",
9700:"ТО50",
9750:"ТО250",
9800:"ТО50",
9850:"ТО50",
9900:"ТО50",
9950:"ТО50",
10000:"ТО2000",
10050:"ТО50",
10100:"ТО50",
10150:"ТО50",
10200:"ТО50",
10250:"ТО250",
10300:"ТО50",
10350:"ТО50",
10400:"ТО50",
10450:"ТО50",
10500:"ТО250",
10550:"ТО50",
10600:"ТО50",
10650:"ТО50",
10700:"ТО50",
10750:"ТО250",
10800:"ТО50",
10850:"ТО50",
10900:"ТО50",
10950:"ТО50",
11000:"ТО1000",
11050:"ТО50",
11100:"ТО50",
11150:"ТО50",
11200:"ТО50",
11250:"ТО250",
11300:"ТО50",
11350:"ТО50",
11400:"ТО50",
11450:"ТО50",
11500:"ТО250",
11550:"ТО50",
11600:"ТО50",
11650:"ТО50",
11700:"ТО50",
11750:"ТО250",
11800:"ТО50",
11850:"ТО50",
11900:"ТО50",
11950:"ТО50",
12000:"ТО2000",
12050:"ТО50",
12100:"ТО50",
12150:"ТО50",
12200:"ТО50",
12250:"ТО250",
12300:"ТО50",
12350:"ТО50",
12400:"ТО50",
12450:"ТО50",
12500:"ТО250",
12550:"ТО50",
12600:"ТО50",
12650:"ТО50",
12700:"ТО50",
12750:"ТО250",
12800:"ТО50",
12850:"ТО50",
12900:"ТО50",
12950:"ТО50",
13000:"ТО1000",
13050:"ТО50",
13100:"ТО50",
13150:"ТО50",
13200:"ТО50",
13250:"ТО250",
13300:"ТО50",
13350:"ТО50",
13400:"ТО50",
13450:"ТО50",
13500:"ТО250",
13550:"ТО50",
13600:"ТО50",
13650:"ТО50",
13700:"ТО50",
13750:"ТО250",
13800:"ТО50",
13850:"ТО50",
13900:"ТО50",
13950:"ТО50",
14000:"ТО2000",
14050:"ТО50",
14100:"ТО50",
14150:"ТО50",
14200:"ТО50",
14250:"ТО250",
14300:"ТО50",
14350:"ТО50",
14400:"ТО50",
14450:"ТО50",
14500:"ТО250",
14550:"ТО50",
14600:"ТО50",
14650:"ТО50",
14700:"ТО50",
14750:"ТО250",
14800:"ТО50",
14850:"ТО50",
14900:"ТО50",
14950:"ТО50",
15000:"ТО1000",
15050:"ТО50",
15100:"ТО50",
15150:"ТО50",
15200:"ТО50",
15250:"ТО250",
15300:"ТО50",
15350:"ТО50",
15400:"ТО50",
15450:"ТО50",
15500:"ТО250",
15550:"ТО50",
15600:"ТО50",
15650:"ТО50",
15700:"ТО50",
15750:"ТО250",
15800:"ТО50",
15850:"ТО50",
15900:"ТО50",
15950:"ТО50",
16000:"ТО2000",
16050:"ТО50",
16100:"ТО50",
16150:"ТО50",
16200:"ТО50",
16250:"ТО250",
16300:"ТО50",
16350:"ТО50",
16400:"ТО50",
16450:"ТО50",
16500:"ТО250",
16550:"ТО50",
16600:"ТО50",
16650:"ТО50",
16700:"ТО50",
16750:"ТО250",
16800:"ТО50",
16850:"ТО50",
16900:"ТО50",
16950:"ТО50",
17000:"ТО1000",
17050:"ТО50",
17100:"ТО50",
17150:"ТО50",
17200:"ТО50",
17250:"ТО250",
17300:"ТО50",
17350:"ТО50",
17400:"ТО50",
17450:"ТО50",
17500:"ТО250",
17550:"ТО50",
17600:"ТО50",
17650:"ТО50",
17700:"ТО50",
17750:"ТО250",
17800:"ТО50",
17850:"ТО50",
17900:"ТО50",
17950:"ТО50",
18000:"ТО2000",
18050:"ТО50",
18100:"ТО50",
18150:"ТО50",
18200:"ТО50",
18250:"ТО250",
18300:"ТО50",
18350:"ТО50",
18400:"ТО50",
18450:"ТО50",
18500:"ТО250",
18550:"ТО50",
18600:"ТО50",
18650:"ТО50",
18700:"ТО50",
18750:"ТО250",
18800:"ТО50",
18850:"ТО50",
18900:"ТО50",
18950:"ТО50",
19000:"ТО1000",
19050:"ТО50",
19100:"ТО50",
19150:"ТО50",
19200:"ТО50",
19250:"ТО250",
19300:"ТО50",
19350:"ТО50",
19400:"ТО50",
19450:"ТО50",
19500:"ТО250",
19550:"ТО50",
19600:"ТО50",
19650:"ТО50",
19700:"ТО50",
19750:"ТО250",
19800:"ТО50",
19850:"ТО50",
19900:"ТО50",
19950:"ТО50",
20000:"ТО2000",
20050:"ТО50",
20100:"ТО50",
20150:"ТО50",
20200:"ТО50",
20250:"ТО250",
20300:"ТО50",
20350:"ТО50",
20400:"ТО50",
20450:"ТО50",
20500:"ТО250",
20550:"ТО50",
20600:"ТО50",
20650:"ТО50",
20700:"ТО50",
20750:"ТО250",
20800:"ТО50",
20850:"ТО50",
20900:"ТО50",
20950:"ТО50",
21000:"ТО1000",
21050:"ТО50",
21100:"ТО50",
21150:"ТО50",
21200:"ТО50",
21250:"ТО250",
21300:"ТО50",
21350:"ТО50",
21400:"ТО50",
21450:"ТО50",
21500:"ТО250",
21550:"ТО50",
21600:"ТО50",
21650:"ТО50",
21700:"ТО50",
21750:"ТО250",
21800:"ТО50",
21850:"ТО50",
21900:"ТО50",
21950:"ТО50",
22000:"ТО2000",
22050:"ТО50",
22100:"ТО50",
22150:"ТО50",
22200:"ТО50",
22250:"ТО250",
22300:"ТО50",
22350:"ТО50",
22400:"ТО50",
22450:"ТО50",
22500:"ТО250",
22550:"ТО50",
22600:"ТО50",
22650:"ТО50",
22700:"ТО50",
22750:"ТО250",
22800:"ТО50",
22850:"ТО50",
22900:"ТО50",
22950:"ТО50",
23000:"ТО1000",
23050:"ТО50",
23100:"ТО50",
23150:"ТО50",
23200:"ТО50",
23250:"ТО250",
23300:"ТО50",
23350:"ТО50",
23400:"ТО50",
23450:"ТО50",
23500:"ТО250",
23550:"ТО50",
23600:"ТО50",
23650:"ТО50",
23700:"ТО50",
23750:"ТО250",
23800:"ТО50",
23850:"ТО50",
23900:"ТО50",
23950:"ТО50",
24000:"ТО2000",
24050:"ТО50",
24100:"ТО50",
24150:"ТО50",
24200:"ТО50",
24250:"ТО250",
24300:"ТО50",
24350:"ТО50",
24400:"ТО50",
24450:"ТО50",
24500:"ТО250",
24550:"ТО50",
24600:"ТО50",
24650:"ТО50",
24700:"ТО50",
24750:"ТО250",
24800:"ТО50",
24850:"ТО50",
24900:"ТО50",
24950:"ТО50",
25000:"ТО1000",
25050:"ТО50",
25100:"ТО50",
25150:"ТО50",
25200:"ТО50",
25250:"ТО250",
25300:"ТО50",
25350:"ТО50",
25400:"ТО50",
25450:"ТО50",
25500:"ТО250",
25550:"ТО50",
25600:"ТО50",
25650:"ТО50",
25700:"ТО50",
25750:"ТО250",
25800:"ТО50",
25850:"ТО50",
25900:"ТО50",
25950:"ТО50",
26000:"ТО2000",
26050:"ТО50",
26100:"ТО50",
26150:"ТО50",
26200:"ТО50",
26250:"ТО250",
26300:"ТО50",
26350:"ТО50",
26400:"ТО50",
26450:"ТО50",
26500:"ТО250",
26550:"ТО50",
26600:"ТО50",
26650:"ТО50",
26700:"ТО50",
26750:"ТО250",
26800:"ТО50",
26850:"ТО50",
26900:"ТО50",
26950:"ТО50",
27000:"ТО1000",
27050:"ТО50",
27100:"ТО50",
27150:"ТО50",
27200:"ТО50",
27250:"ТО250",
27300:"ТО50",
27350:"ТО50",
27400:"ТО50",
27450:"ТО50",
27500:"ТО250",
27550:"ТО50",
27600:"ТО50",
27650:"ТО50",
27700:"ТО50",
27750:"ТО250",
27800:"ТО50",
27850:"ТО50",
27900:"ТО50",
27950:"ТО50",
28000:"ТО2000",
28050:"ТО50",
28100:"ТО50",
28150:"ТО50",
28200:"ТО50",
28250:"ТО250",
28300:"ТО50",
28350:"ТО50",
28400:"ТО50",
28450:"ТО50",
28500:"ТО250",
28550:"ТО50",
28600:"ТО50",
28650:"ТО50",
28700:"ТО50",
28750:"ТО250",
28800:"ТО50",
28850:"ТО50",
28900:"ТО50",
28950:"ТО50",
29000:"ТО1000",
29050:"ТО50",
29100:"ТО50",
29150:"ТО50",
29200:"ТО50",
29250:"ТО250",
29300:"ТО50",
29350:"ТО50",
29400:"ТО50",
29450:"ТО50",
29500:"ТО250",
29550:"ТО50",
29600:"ТО50",
29650:"ТО50",
29700:"ТО50",
29750:"ТО250",
29800:"ТО50",
29850:"ТО50",
29900:"ТО50",
29950:"ТО50",
30000:"ТО2000",
30050:"ТО50",
30100:"ТО50",
30150:"ТО50",
30200:"ТО50",
30250:"ТО250",
30300:"ТО50",
30350:"ТО50",
30400:"ТО50",
30450:"ТО50",
30500:"ТО250",
30550:"ТО50",
30600:"ТО50",
30650:"ТО50",
30700:"ТО50",
30750:"ТО250",
30800:"ТО50",
30850:"ТО50",
30900:"ТО50",
30950:"ТО50",
31000:"ТО1000",
31050:"ТО50",
31100:"ТО50",
31150:"ТО50",
31200:"ТО50",
31250:"ТО250",
31300:"ТО50",
31350:"ТО50",
31400:"ТО50",
31450:"ТО50",
31500:"ТО250",
31550:"ТО50",
31600:"ТО50",
31650:"ТО50",
31700:"ТО50",
31750:"ТО250",
31800:"ТО50",
31850:"ТО50",
31900:"ТО50",
31950:"ТО50",
32000:"ТО2000",
32050:"ТО50",
32100:"ТО50",
32150:"ТО50",
32200:"ТО50",
32250:"ТО250",
32300:"ТО50",
32350:"ТО50",
32400:"ТО50",
32450:"ТО50",
32500:"ТО250",
32550:"ТО50",
32600:"ТО50",
32650:"ТО50",
32700:"ТО50",
32750:"ТО250",
32800:"ТО50",
32850:"ТО50",
32900:"ТО50",
32950:"ТО50",
33000:"ТО1000",
33050:"ТО50",
33100:"ТО50",
33150:"ТО50",
33200:"ТО50",
33250:"ТО250",
33300:"ТО50",
33350:"ТО50",
33400:"ТО50",
33450:"ТО50",
33500:"ТО250",
33550:"ТО50",
33600:"ТО50",
33650:"ТО50",
33700:"ТО50",
33750:"ТО250",
33800:"ТО50",
33850:"ТО50",
33900:"ТО50",
33950:"ТО50",
34000:"ТО2000",
34050:"ТО50",
34100:"ТО50",
34150:"ТО50",
34200:"ТО50",
34250:"ТО250",
34300:"ТО50",
34350:"ТО50",
34400:"ТО50",
34450:"ТО50",
34500:"ТО250",
34550:"ТО50",
34600:"ТО50",
34650:"ТО50",
34700:"ТО50",
34750:"ТО250",
34800:"ТО50",
34850:"ТО50",
34900:"ТО50",
34950:"ТО50",
35000:"ТО1000",
35050:"ТО50",
35100:"ТО50",
35150:"ТО50",
35200:"ТО50",
35250:"ТО250",
35300:"ТО50",
35350:"ТО50",
35400:"ТО50",
35450:"ТО50",
35500:"ТО250",
35550:"ТО50",
35600:"ТО50",
35650:"ТО50",
35700:"ТО50",
35750:"ТО250",
35800:"ТО50",
35850:"ТО50",
35900:"ТО50",
35950:"ТО50",
36000:"ТО2000",
36050:"ТО50",
36100:"ТО50",
36150:"ТО50",
36200:"ТО50",
36250:"ТО250",
36300:"ТО50",
36350:"ТО50",
36400:"ТО50",
36450:"ТО50",
36500:"ТО250",
36550:"ТО50",
36600:"ТО50",
36650:"ТО50",
36700:"ТО50",
36750:"ТО250",
36800:"ТО50",
36850:"ТО50",
36900:"ТО50",
36950:"ТО50",
37000:"ТО1000",
37050:"ТО50",
37100:"ТО50",
37150:"ТО50",
37200:"ТО50",
37250:"ТО250",
37300:"ТО50",
37350:"ТО50",
37400:"ТО50",
37450:"ТО50",
37500:"ТО250",
37550:"ТО50",
37600:"ТО50",
37650:"ТО50",
37700:"ТО50",
37750:"ТО250",
37800:"ТО50",
37850:"ТО50",
37900:"ТО50",
37950:"ТО50",
38000:"ТО2000",
38050:"ТО50",
38100:"ТО50",
38150:"ТО50",
38200:"ТО50",
38250:"ТО250",
38300:"ТО50",
38350:"ТО50",
38400:"ТО50",
38450:"ТО50",
38500:"ТО250",
38550:"ТО50",
38600:"ТО50",
38650:"ТО50",
38700:"ТО50",
38750:"ТО250",
38800:"ТО50",
38850:"ТО50",
38900:"ТО50",
38950:"ТО50",
39000:"ТО1000",
39050:"ТО50",
39100:"ТО50",
39150:"ТО50",
39200:"ТО50",
39250:"ТО250",
39300:"ТО50",
39350:"ТО50",
39400:"ТО50",
39450:"ТО50",
39500:"ТО250",
39550:"ТО50",
39600:"ТО50",
39650:"ТО50",
39700:"ТО50",
39750:"ТО250",
39800:"ТО50",
39850:"ТО50",
39900:"ТО50",
39950:"ТО50",
40000:"ТО2000",
40050:"ТО50",
40100:"ТО50",
40150:"ТО50",
40200:"ТО50",
40250:"ТО250",
40300:"ТО50",
40350:"ТО50",
40400:"ТО50",
40450:"ТО50",
40500:"ТО250",
40550:"ТО50",
40600:"ТО50",
40650:"ТО50",
40700:"ТО50",
40750:"ТО250",
40800:"ТО50",
40850:"ТО50",
40900:"ТО50",
40950:"ТО50",
41000:"ТО1000",
41050:"ТО50",
41100:"ТО50",
41150:"ТО50",
41200:"ТО50",
41250:"ТО250",
41300:"ТО50",
41350:"ТО50",
41400:"ТО50",
41450:"ТО50",
41500:"ТО250",
41550:"ТО50",
41600:"ТО50",
41650:"ТО50",
41700:"ТО50",
41750:"ТО250",
41800:"ТО50",
41850:"ТО50",
41900:"ТО50",
41950:"ТО50",
42000:"ТО2000",
42050:"ТО50",
42100:"ТО50",
42150:"ТО50",
42200:"ТО50",
42250:"ТО250",
42300:"ТО50",
42350:"ТО50",
42400:"ТО50",
42450:"ТО50",
42500:"ТО250",
42550:"ТО50",
42600:"ТО50",
42650:"ТО50",
42700:"ТО50",
42750:"ТО250",
42800:"ТО50",
42850:"ТО50",
42900:"ТО50",
42950:"ТО50",
43000:"ТО1000",
43050:"ТО50",
43100:"ТО50",
43150:"ТО50",
43200:"ТО50",
43250:"ТО250",
43300:"ТО50",
43350:"ТО50",
43400:"ТО50",
43450:"ТО50",
43500:"ТО250",
43550:"ТО50",
43600:"ТО50",
43650:"ТО50",
43700:"ТО50",
43750:"ТО250",
43800:"ТО50",
43850:"ТО50",
43900:"ТО50",
43950:"ТО50",
44000:"ТО2000",
44050:"ТО50",
44100:"ТО50",
44150:"ТО50",
44200:"ТО50",
44250:"ТО250",
44300:"ТО50",
44350:"ТО50",
44400:"ТО50",
44450:"ТО50",
44500:"ТО250",
44550:"ТО50",
44600:"ТО50",
44650:"ТО50",
44700:"ТО50",
44750:"ТО250",
44800:"ТО50",
44850:"ТО50",
44900:"ТО50",
44950:"ТО50",
45000:"ТО1000",
45050:"ТО50",
45100:"ТО50",
45150:"ТО50",
45200:"ТО50",
45250:"ТО250",
45300:"ТО50",
45350:"ТО50",
45400:"ТО50",
45450:"ТО50",
45500:"ТО250",
45550:"ТО50",
45600:"ТО50",
45650:"ТО50",
45700:"ТО50",
45750:"ТО250",
45800:"ТО50",
45850:"ТО50",
45900:"ТО50",
45950:"ТО50",
46000:"ТО2000",
46050:"ТО50",
46100:"ТО50",
46150:"ТО50",
46200:"ТО50",
46250:"ТО250",
46300:"ТО50",
46350:"ТО50",
46400:"ТО50",
46450:"ТО50",
46500:"ТО250",
46550:"ТО50",
46600:"ТО50",
46650:"ТО50",
46700:"ТО50",
46750:"ТО250",
46800:"ТО50",
46850:"ТО50",
46900:"ТО50",
46950:"ТО50",
47000:"ТО1000",
47050:"ТО50",
47100:"ТО50",
47150:"ТО50",
47200:"ТО50",
47250:"ТО250",
47300:"ТО50",
47350:"ТО50",
47400:"ТО50",
47450:"ТО50",
47500:"ТО250",
47550:"ТО50",
47600:"ТО50",
47650:"ТО50",
47700:"ТО50",
47750:"ТО250",
47800:"ТО50",
47850:"ТО50",
47900:"ТО50",
47950:"ТО50",
48000:"ТО2000"

    
}

In [60]:
to_dict_DNU={
    50:"",
100:"",
150:"",
200:"",
250:"ТО250",
300:"",
350:"",
400:"",
450:"",
500:"ТО500",
550:"",
600:"",
650:"",
700:"",
750:"ТО250",
800:"",
850:"",
900:"",
950:"",
1000:"ТО1000",
1050:"",
1100:"",
1150:"",
1200:"",
1250:"ТО250",
1300:"",
1350:"",
1400:"",
1450:"",
1500:"ТО500",
1550:"",
1600:"",
1650:"",
1700:"",
1750:"ТО250",
1800:"",
1850:"",
1900:"",
1950:"",
2000:"ТО1000",
2050:"",
2100:"",
2150:"",
2200:"",
2250:"ТО250",
2300:"",
2350:"",
2400:"",
2450:"",
2500:"ТО500",
2550:"",
2600:"",
2650:"",
2700:"",
2750:"ТО250",
2800:"",
2850:"",
2900:"",
2950:"",
3000:"ТО1000",
3050:"",
3100:"",
3150:"",
3200:"",
3250:"ТО250",
3300:"",
3350:"",
3400:"",
3450:"",
3500:"ТО500",
3550:"",
3600:"",
3650:"",
3700:"",
3750:"ТО250",
3800:"",
3850:"",
3900:"",
3950:"",
4000:"ТО4000",
4050:"",
4100:"",
4150:"",
4200:"",
4250:"ТО250",
4300:"",
4350:"",
4400:"",
4450:"",
4500:"ТО500",
4550:"",
4600:"",
4650:"",
4700:"",
4750:"ТО250",
4800:"",
4850:"",
4900:"",
4950:"",
5000:"ТО1000",
5050:"",
5100:"",
5150:"",
5200:"",
5250:"ТО250",
5300:"",
5350:"",
5400:"",
5450:"",
5500:"ТО500",
5550:"",
5600:"",
5650:"",
5700:"",
5750:"ТО250",
5800:"",
5850:"",
5900:"",
5950:"",
6000:"ТО1000",
6050:"",
6100:"",
6150:"",
6200:"",
6250:"ТО250",
6300:"",
6350:"",
6400:"",
6450:"",
6500:"ТО500",
6550:"",
6600:"",
6650:"",
6700:"",
6750:"ТО250",
6800:"",
6850:"",
6900:"",
6950:"",
7000:"ТО1000",
7050:"",
7100:"",
7150:"",
7200:"",
7250:"ТО250",
7300:"",
7350:"",
7400:"",
7450:"",
7500:"ТО500",
7550:"",
7600:"",
7650:"",
7700:"",
7750:"ТО250",
7800:"",
7850:"",
7900:"",
7950:"",
8000:"ТО4000",
8050:"",
8100:"",
8150:"",
8200:"",
8250:"ТО250",
8300:"",
8350:"",
8400:"",
8450:"",
8500:"ТО500",
8550:"",
8600:"",
8650:"",
8700:"",
8750:"ТО250",
8800:"",
8850:"",
8900:"",
8950:"",
9000:"ТО1000",
9050:"",
9100:"",
9150:"",
9200:"",
9250:"ТО250",
9300:"",
9350:"",
9400:"",
9450:"",
9500:"ТО500",
9550:"",
9600:"",
9650:"",
9700:"",
9750:"ТО250",
9800:"",
9850:"",
9900:"",
9950:"",
10000:"ТО1000",
10050:"",
10100:"",
10150:"",
10200:"",
10250:"ТО250",
10300:"",
10350:"",
10400:"",
10450:"",
10500:"ТО500",
10550:"",
10600:"",
10650:"",
10700:"",
10750:"ТО250",
10800:"",
10850:"",
10900:"",
10950:"",
11000:"ТО1000",
11050:"",
11100:"",
11150:"",
11200:"",
11250:"ТО250",
11300:"",
11350:"",
11400:"",
11450:"",
11500:"ТО500",
11550:"",
11600:"",
11650:"",
11700:"",
11750:"ТО250",
11800:"",
11850:"",
11900:"",
11950:"",
12000:"ТО4000",
12050:"",
12100:"",
12150:"",
12200:"",
12250:"ТО250",
12300:"",
12350:"",
12400:"",
12450:"",
12500:"ТО500",
12550:"",
12600:"",
12650:"",
12700:"",
12750:"ТО250",
12800:"",
12850:"",
12900:"",
12950:"",
13000:"ТО1000",
13050:"",
13100:"",
13150:"",
13200:"",
13250:"ТО250",
13300:"",
13350:"",
13400:"",
13450:"",
13500:"ТО500",
13550:"",
13600:"",
13650:"",
13700:"",
13750:"ТО250",
13800:"",
13850:"",
13900:"",
13950:"",
14000:"ТО1000",
14050:"",
14100:"",
14150:"",
14200:"",
14250:"ТО250",
14300:"",
14350:"",
14400:"",
14450:"",
14500:"ТО500",
14550:"",
14600:"",
14650:"",
14700:"",
14750:"ТО250",
14800:"",
14850:"",
14900:"",
14950:"",
15000:"ТО1000",
15050:"",
15100:"",
15150:"",
15200:"",
15250:"ТО250",
15300:"",
15350:"",
15400:"",
15450:"",
15500:"ТО500",
15550:"",
15600:"",
15650:"",
15700:"",
15750:"ТО250",
15800:"",
15850:"",
15900:"",
15950:"",
16000:"ТО4000",
16050:"",
16100:"",
16150:"",
16200:"",
16250:"ТО250",
16300:"",
16350:"",
16400:"",
16450:"",
16500:"ТО500",
16550:"",
16600:"",
16650:"",
16700:"",
16750:"ТО250",
16800:"",
16850:"",
16900:"",
16950:"",
17000:"ТО1000",
17050:"",
17100:"",
17150:"",
17200:"",
17250:"ТО250",
17300:"",
17350:"",
17400:"",
17450:"",
17500:"ТО500",
17550:"",
17600:"",
17650:"",
17700:"",
17750:"ТО250",
17800:"",
17850:"",
17900:"",
17950:"",
18000:"ТО1000",
18050:"",
18100:"",
18150:"",
18200:"",
18250:"ТО250",
18300:"",
18350:"",
18400:"",
18450:"",
18500:"ТО500",
18550:"",
18600:"",
18650:"",
18700:"",
18750:"ТО250",
18800:"",
18850:"",
18900:"",
18950:"",
19000:"ТО1000",
19050:"",
19100:"",
19150:"",
19200:"",
19250:"ТО250",
19300:"",
19350:"",
19400:"",
19450:"",
19500:"ТО500",
19550:"",
19600:"",
19650:"",
19700:"",
19750:"ТО250",
19800:"",
19850:"",
19900:"",
19950:"",
20000:"ТО4000",
20050:"",
20100:"",
20150:"",
20200:"",
20250:"ТО250",
20300:"",
20350:"",
20400:"",
20450:"",
20500:"ТО500",
20550:"",
20600:"",
20650:"",
20700:"",
20750:"ТО250",
20800:"",
20850:"",
20900:"",
20950:"",
21000:"ТО1000",
21050:"",
21100:"",
21150:"",
21200:"",
21250:"ТО250",
21300:"",
21350:"",
21400:"",
21450:"",
21500:"ТО500",
21550:"",
21600:"",
21650:"",
21700:"",
21750:"ТО250",
21800:"",
21850:"",
21900:"",
21950:"",
22000:"ТО1000",
22050:"",
22100:"",
22150:"",
22200:"",
22250:"ТО250",
22300:"",
22350:"",
22400:"",
22450:"",
22500:"ТО500",
22550:"",
22600:"",
22650:"",
22700:"",
22750:"ТО250",
22800:"",
22850:"",
22900:"",
22950:"",
23000:"ТО1000",
23050:"",
23100:"",
23150:"",
23200:"",
23250:"ТО250",
23300:"",
23350:"",
23400:"",
23450:"",
23500:"ТО500",
23550:"",
23600:"",
23650:"",
23700:"",
23750:"ТО250",
23800:"",
23850:"",
23900:"",
23950:"",
24000:"ТО4000",
24050:"",
24100:"",
24150:"",
24200:"",
24250:"ТО250",
24300:"",
24350:"",
24400:"",
24450:"",
24500:"ТО500",
24550:"",
24600:"",
24650:"",
24700:"",
24750:"ТО250",
24800:"",
24850:"",
24900:"",
24950:"",
25000:"ТО1000",
25050:"",
25100:"",
25150:"",
25200:"",
25250:"ТО250",
25300:"",
25350:"",
25400:"",
25450:"",
25500:"ТО500",
25550:"",
25600:"",
25650:"",
25700:"",
25750:"ТО250",
25800:"",
25850:"",
25900:"",
25950:"",
26000:"ТО1000",
26050:"",
26100:"",
26150:"",
26200:"",
26250:"ТО250",
26300:"",
26350:"",
26400:"",
26450:"",
26500:"ТО500",
26550:"",
26600:"",
26650:"",
26700:"",
26750:"ТО250",
26800:"",
26850:"",
26900:"",
26950:"",
27000:"ТО1000",
27050:"",
27100:"",
27150:"",
27200:"",
27250:"ТО250",
27300:"",
27350:"",
27400:"",
27450:"",
27500:"ТО500",
27550:"",
27600:"",
27650:"",
27700:"",
27750:"ТО250",
27800:"",
27850:"",
27900:"",
27950:"",
28000:"ТО4000",
28050:"",
28100:"",
28150:"",
28200:"",
28250:"ТО250",
28300:"",
28350:"",
28400:"",
28450:"",
28500:"ТО500",
28550:"",
28600:"",
28650:"",
28700:"",
28750:"ТО250",
28800:"",
28850:"",
28900:"",
28950:"",
29000:"ТО1000",
29050:"",
29100:"",
29150:"",
29200:"",
29250:"ТО250",
29300:"",
29350:"",
29400:"",
29450:"",
29500:"ТО500",
29550:"",
29600:"",
29650:"",
29700:"",
29750:"ТО250",
29800:"",
29850:"",
29900:"",
29950:"",
30000:"ТО1000",
30050:"",
30100:"",
30150:"",
30200:"",
30250:"ТО250",
30300:"",
30350:"",
30400:"",
30450:"",
30500:"ТО500",
30550:"",
30600:"",
30650:"",
30700:"",
30750:"ТО250",
30800:"",
30850:"",
30900:"",
30950:"",
31000:"ТО1000",
31050:"",
31100:"",
31150:"",
31200:"",
31250:"ТО250",
31300:"",
31350:"",
31400:"",
31450:"",
31500:"ТО500",
31550:"",
31600:"",
31650:"",
31700:"",
31750:"ТО250",
31800:"",
31850:"",
31900:"",
31950:"",
32000:"ТО4000",
32050:"",
32100:"",
32150:"",
32200:"",
32250:"ТО250",
32300:"",
32350:"",
32400:"",
32450:"",
32500:"ТО500",
32550:"",
32600:"",
32650:"",
32700:"",
32750:"ТО250",
32800:"",
32850:"",
32900:"",
32950:"",
33000:"ТО1000",
33050:"",
33100:"",
33150:"",
33200:"",
33250:"ТО250",
33300:"",
33350:"",
33400:"",
33450:"",
33500:"ТО500",
33550:"",
33600:"",
33650:"",
33700:"",
33750:"ТО250",
33800:"",
33850:"",
33900:"",
33950:"",
34000:"ТО1000",
34050:"",
34100:"",
34150:"",
34200:"",
34250:"ТО250",
34300:"",
34350:"",
34400:"",
34450:"",
34500:"ТО500",
34550:"",
34600:"",
34650:"",
34700:"",
34750:"ТО250",
34800:"",
34850:"",
34900:"",
34950:"",
35000:"ТО1000",
35050:"",
35100:"",
35150:"",
35200:"",
35250:"ТО250",
35300:"",
35350:"",
35400:"",
35450:"",
35500:"ТО500",
35550:"",
35600:"",
35650:"",
35700:"",
35750:"ТО250",
35800:"",
35850:"",
35900:"",
35950:"",
36000:"ТО4000",
36050:"",
36100:"",
36150:"",
36200:"",
36250:"ТО250",
36300:"",
36350:"",
36400:"",
36450:"",
36500:"ТО500",
36550:"",
36600:"",
36650:"",
36700:"",
36750:"ТО250",
36800:"",
36850:"",
36900:"",
36950:"",
37000:"ТО1000",
37050:"",
37100:"",
37150:"",
37200:"",
37250:"ТО250",
37300:"",
37350:"",
37400:"",
37450:"",
37500:"ТО500",
37550:"",
37600:"",
37650:"",
37700:"",
37750:"ТО250",
37800:"",
37850:"",
37900:"",
37950:"",
38000:"ТО1000",
38050:"",
38100:"",
38150:"",
38200:"",
38250:"ТО250",
38300:"",
38350:"",
38400:"",
38450:"",
38500:"ТО500",
38550:"",
38600:"",
38650:"",
38700:"",
38750:"ТО250",
38800:"",
38850:"",
38900:"",
38950:"",
39000:"ТО1000",
39050:"",
39100:"",
39150:"",
39200:"",
39250:"ТО250",
39300:"",
39350:"",
39400:"",
39450:"",
39500:"ТО500",
39550:"",
39600:"",
39650:"",
39700:"",
39750:"ТО250",
39800:"",
39850:"",
39900:"",
39950:"",
40000:"ТО4000",
40050:"",
40100:"",
40150:"",
40200:"",
40250:"ТО250",
40300:"",
40350:"",
40400:"",
40450:"",
40500:"ТО500",
40550:"",
40600:"",
40650:"",
40700:"",
40750:"ТО250",
40800:"",
40850:"",
40900:"",
40950:"",
41000:"ТО1000",
41050:"",
41100:"",
41150:"",
41200:"",
41250:"ТО250",
41300:"",
41350:"",
41400:"",
41450:"",
41500:"ТО500",
41550:"",
41600:"",
41650:"",
41700:"",
41750:"ТО250",
41800:"",
41850:"",
41900:"",
41950:"",
42000:"ТО1000",
42050:"",
42100:"",
42150:"",
42200:"",
42250:"ТО250",
42300:"",
42350:"",
42400:"",
42450:"",
42500:"ТО500",
42550:"",
42600:"",
42650:"",
42700:"",
42750:"ТО250",
42800:"",
42850:"",
42900:"",
42950:"",
43000:"ТО1000",
43050:"",
43100:"",
43150:"",
43200:"",
43250:"ТО250",
43300:"",
43350:"",
43400:"",
43450:"",
43500:"ТО500",
43550:"",
43600:"",
43650:"",
43700:"",
43750:"ТО250",
43800:"",
43850:"",
43900:"",
43950:"",
44000:"ТО4000",
44050:"",
44100:"",
44150:"",
44200:"",
44250:"ТО250",
44300:"",
44350:"",
44400:"",
44450:"",
44500:"ТО500",
44550:"",
44600:"",
44650:"",
44700:"",
44750:"ТО250",
44800:"",
44850:"",
44900:"",
44950:"",
45000:"ТО1000",
45050:"",
45100:"",
45150:"",
45200:"",
45250:"ТО250",
45300:"",
45350:"",
45400:"",
45450:"",
45500:"ТО500",
45550:"",
45600:"",
45650:"",
45700:"",
45750:"ТО250",
45800:"",
45850:"",
45900:"",
45950:"",
46000:"ТО1000",
46050:"",
46100:"",
46150:"",
46200:"",
46250:"ТО250",
46300:"",
46350:"",
46400:"",
46450:"",
46500:"ТО500",
46550:"",
46600:"",
46650:"",
46700:"",
46750:"ТО250",
46800:"",
46850:"",
46900:"",
46950:"",
47000:"ТО1000",
47050:"",
47100:"",
47150:"",
47200:"",
47250:"ТО250",
47300:"",
47350:"",
47400:"",
47450:"",
47500:"ТО500",
47550:"",
47600:"",
47650:"",
47700:"",
47750:"ТО250",
47800:"",
47850:"",
47900:"",
47950:"",
48000:"ТО4000"

       
}

In [61]:
to_dict_DNU_1600={
    50:"",
100:"",
150:"",
200:"ТО200",
250:"",
300:"",
350:"",
400:"ТО400",
450:"",
500:"",
550:"",
600:"ТО200",
650:"",
700:"",
750:"",
800:"ТО400",
850:"",
900:"",
950:"",
1000:"ТО200",
1050:"",
1100:"",
1150:"",
1200:"ТО400",
1250:"",
1300:"",
1350:"",
1400:"ТО200",
1450:"",
1500:"",
1550:"",
1600:"ТО1600",
1650:"",
1700:"",
1750:"",
1800:"ТО200",
1850:"",
1900:"",
1950:"",
2000:"ТО400",
2050:"",
2100:"",
2150:"",
2200:"ТО200",
2250:"",
2300:"",
2350:"",
2400:"ТО400",
2450:"",
2500:"",
2550:"",
2600:"ТО200",
2650:"",
2700:"",
2750:"",
2800:"ТО400",
2850:"",
2900:"",
2950:"",
3000:"ТО200",
3050:"",
3100:"",
3150:"",
3200:"ТО3200",
3250:"",
3300:"",
3350:"",
3400:"ТО200",
3450:"",
3500:"",
3550:"",
3600:"ТО400",
3650:"",
3700:"",
3750:"",
3800:"ТО200",
3850:"",
3900:"",
3950:"",
4000:"ТО4000",
4050:"",
4100:"",
4150:"",
4200:"ТО200",
4250:"",
4300:"",
4350:"",
4400:"ТО400",
4450:"",
4500:"",
4550:"",
4600:"ТО200",
4650:"",
4700:"",
4750:"",
4800:"ТО1600",
4850:"",
4900:"",
4950:"",
5000:"ТО200",
5050:"",
5100:"",
5150:"",
5200:"ТО400",
5250:"",
5300:"",
5350:"",
5400:"ТО200",
5450:"",
5500:"",
5550:"",
5600:"ТО400",
5650:"",
5700:"",
5750:"",
5800:"ТО200",
5850:"",
5900:"",
5950:"",
6000:"ТО400",
6050:"",
6100:"",
6150:"",
6200:"ТО200",
6250:"",
6300:"",
6350:"",
6400:"ТО3200",
6450:"",
6500:"",
6550:"",
6600:"ТО200",
6650:"",
6700:"",
6750:"",
6800:"ТО400",
6850:"",
6900:"",
6950:"",
7000:"ТО200",
7050:"",
7100:"",
7150:"",
7200:"ТО400",
7250:"",
7300:"",
7350:"",
7400:"ТО200",
7450:"",
7500:"",
7550:"",
7600:"ТО400",
7650:"",
7700:"",
7750:"",
7800:"ТО200",
7850:"",
7900:"",
7950:"",
8000:"ТО4000",
8050:"",
8100:"",
8150:"",
8200:"ТО200",
8250:"",
8300:"",
8350:"",
8400:"ТО400",
8450:"",
8500:"",
8550:"",
8600:"ТО200",
8650:"",
8700:"",
8750:"",
8800:"ТО400",
8850:"",
8900:"",
8950:"",
9000:"ТО200",
9050:"",
9100:"",
9150:"",
9200:"ТО400",
9250:"",
9300:"",
9350:"",
9400:"ТО200",
9450:"",
9500:"",
9550:"",
9600:"ТО3200",
9650:"",
9700:"",
9750:"",
9800:"ТО200",
9850:"",
9900:"",
9950:"",
10000:"ТО400",
10050:"",
10100:"",
10150:"",
10200:"ТО200",
10250:"",
10300:"",
10350:"",
10400:"ТО400",
10450:"",
10500:"",
10550:"",
10600:"ТО200",
10650:"",
10700:"",
10750:"",
10800:"ТО400",
10850:"",
10900:"",
10950:"",
11000:"ТО200",
11050:"",
11100:"",
11150:"",
11200:"ТО1600",
11250:"",
11300:"",
11350:"",
11400:"ТО200",
11450:"",
11500:"",
11550:"",
11600:"ТО400",
11650:"",
11700:"",
11750:"",
11800:"ТО200",
11850:"",
11900:"",
11950:"",
12000:"ТО4000",
12050:"",
12100:"",
12150:"",
12200:"ТО200",
12250:"",
12300:"",
12350:"",
12400:"ТО400",
12450:"",
12500:"",
12550:"",
12600:"ТО200",
12650:"",
12700:"",
12750:"",
12800:"ТО3200",
12850:"",
12900:"",
12950:"",
13000:"ТО200",
13050:"",
13100:"",
13150:"",
13200:"ТО400",
13250:"",
13300:"",
13350:"",
13400:"ТО200",
13450:"",
13500:"",
13550:"",
13600:"ТО400",
13650:"",
13700:"",
13750:"",
13800:"ТО200",
13850:"",
13900:"",
13950:"",
14000:"ТО400",
14050:"",
14100:"",
14150:"",
14200:"ТО200",
14250:"",
14300:"",
14350:"",
14400:"ТО1600",
14450:"",
14500:"",
14550:"",
14600:"ТО200",
14650:"",
14700:"",
14750:"",
14800:"ТО400",
14850:"",
14900:"",
14950:"",
15000:"ТО200",
15050:"",
15100:"",
15150:"",
15200:"ТО400",
15250:"",
15300:"",
15350:"",
15400:"ТО200",
15450:"",
15500:"",
15550:"",
15600:"ТО400",
15650:"",
15700:"",
15750:"",
15800:"ТО200",
15850:"",
15900:"",
15950:"",
16000:"ТО4000",
16050:"",
16100:"",
16150:"",
16200:"ТО200",
16250:"",
16300:"",
16350:"",
16400:"ТО400",
16450:"",
16500:"",
16550:"",
16600:"ТО200",
16650:"",
16700:"",
16750:"",
16800:"ТО400",
16850:"",
16900:"",
16950:"",
17000:"ТО200",
17050:"",
17100:"",
17150:"",
17200:"ТО400",
17250:"",
17300:"",
17350:"",
17400:"ТО200",
17450:"",
17500:"",
17550:"",
17600:"ТО1600",
17650:"",
17700:"",
17750:"",
17800:"ТО200",
17850:"",
17900:"",
17950:"",
18000:"ТО400",
18050:"",
18100:"",
18150:"",
18200:"ТО200",
18250:"",
18300:"",
18350:"",
18400:"ТО400",
18450:"",
18500:"",
18550:"",
18600:"ТО200",
18650:"",
18700:"",
18750:"",
18800:"ТО400",
18850:"",
18900:"",
18950:"",
19000:"ТО200",
19050:"",
19100:"",
19150:"",
19200:"ТО3200",
19250:"",
19300:"",
19350:"",
19400:"ТО200",
19450:"",
19500:"",
19550:"",
19600:"ТО400",
19650:"",
19700:"",
19750:"",
19800:"ТО200",
19850:"",
19900:"",
19950:"",
20000:"ТО4000",
20050:"",
20100:"",
20150:"",
20200:"ТО200",
20250:"",
20300:"",
20350:"",
20400:"ТО400",
20450:"",
20500:"",
20550:"",
20600:"ТО200",
20650:"",
20700:"",
20750:"",
20800:"ТО1600",
20850:"",
20900:"",
20950:"",
21000:"ТО200",
21050:"",
21100:"",
21150:"",
21200:"ТО400",
21250:"",
21300:"",
21350:"",
21400:"ТО200",
21450:"",
21500:"",
21550:"",
21600:"ТО400",
21650:"",
21700:"",
21750:"",
21800:"ТО200",
21850:"",
21900:"",
21950:"",
22000:"ТО400",
22050:"",
22100:"",
22150:"",
22200:"ТО200",
22250:"",
22300:"",
22350:"",
22400:"ТО3200",
22450:"",
22500:"",
22550:"",
22600:"ТО200",
22650:"",
22700:"",
22750:"",
22800:"ТО400",
22850:"",
22900:"",
22950:"",
23000:"ТО200",
23050:"",
23100:"",
23150:"",
23200:"ТО400",
23250:"",
23300:"",
23350:"",
23400:"ТО200",
23450:"",
23500:"",
23550:"",
23600:"ТО400",
23650:"",
23700:"",
23750:"",
23800:"ТО200",
23850:"",
23900:"",
23950:"",
24000:"ТО4000",
24050:"",
24100:"",
24150:"",
24200:"ТО200",
24250:"",
24300:"",
24350:"",
24400:"ТО400",
24450:"",
24500:"",
24550:"",
24600:"ТО200",
24650:"",
24700:"",
24750:"",
24800:"ТО400",
24850:"",
24900:"",
24950:"",
25000:"ТО200",
25050:"",
25100:"",
25150:"",
25200:"ТО400",
25250:"",
25300:"",
25350:"",
25400:"ТО200",
25450:"",
25500:"",
25550:"",
25600:"ТО3200",
25650:"",
25700:"",
25750:"",
25800:"ТО200",
25850:"",
25900:"",
25950:"",
26000:"ТО400",
26050:"",
26100:"",
26150:"",
26200:"ТО200",
26250:"",
26300:"",
26350:"",
26400:"ТО400",
26450:"",
26500:"",
26550:"",
26600:"ТО200",
26650:"",
26700:"",
26750:"",
26800:"ТО400",
26850:"",
26900:"",
26950:"",
27000:"ТО200",
27050:"",
27100:"",
27150:"",
27200:"ТО1600",
27250:"",
27300:"",
27350:"",
27400:"ТО200",
27450:"",
27500:"",
27550:"",
27600:"ТО400",
27650:"",
27700:"",
27750:"",
27800:"ТО200",
27850:"",
27900:"",
27950:"",
28000:"ТО4000",
28050:"",
28100:"",
28150:"",
28200:"ТО200",
28250:"",
28300:"",
28350:"",
28400:"ТО400",
28450:"",
28500:"",
28550:"",
28600:"ТО200",
28650:"",
28700:"",
28750:"",
28800:"ТО3200",
28850:"",
28900:"",
28950:"",
29000:"ТО200",
29050:"",
29100:"",
29150:"",
29200:"ТО400",
29250:"",
29300:"",
29350:"",
29400:"ТО200",
29450:"",
29500:"",
29550:"",
29600:"ТО400",
29650:"",
29700:"",
29750:"",
29800:"ТО200",
29850:"",
29900:"",
29950:"",
30000:"ТО400",
30050:"",
30100:"",
30150:"",
30200:"ТО200",
30250:"",
30300:"",
30350:"",
30400:"ТО1600",
30450:"",
30500:"",
30550:"",
30600:"ТО200",
30650:"",
30700:"",
30750:"",
30800:"ТО400",
30850:"",
30900:"",
30950:"",
31000:"ТО200",
31050:"",
31100:"",
31150:"",
31200:"ТО400",
31250:"",
31300:"",
31350:"",
31400:"ТО200",
31450:"",
31500:"",
31550:"",
31600:"ТО400",
31650:"",
31700:"",
31750:"",
31800:"ТО200",
31850:"",
31900:"",
31950:"",
32000:"ТО4000",
32050:"",
32100:"",
32150:"",
32200:"ТО200",
32250:"",
32300:"",
32350:"",
32400:"ТО400",
32450:"",
32500:"",
32550:"",
32600:"ТО200",
32650:"",
32700:"",
32750:"",
32800:"ТО400",
32850:"",
32900:"",
32950:"",
33000:"ТО200",
33050:"",
33100:"",
33150:"",
33200:"ТО400",
33250:"",
33300:"",
33350:"",
33400:"ТО200",
33450:"",
33500:"",
33550:"",
33600:"ТО1600",
33650:"",
33700:"",
33750:"",
33800:"ТО200",
33850:"",
33900:"",
33950:"",
34000:"ТО400",
34050:"",
34100:"",
34150:"",
34200:"ТО200",
34250:"",
34300:"",
34350:"",
34400:"ТО400",
34450:"",
34500:"",
34550:"",
34600:"ТО200",
34650:"",
34700:"",
34750:"",
34800:"ТО400",
34850:"",
34900:"",
34950:"",
35000:"ТО200",
35050:"",
35100:"",
35150:"",
35200:"ТО3200",
35250:"",
35300:"",
35350:"",
35400:"ТО200",
35450:"",
35500:"",
35550:"",
35600:"ТО400",
35650:"",
35700:"",
35750:"",
35800:"ТО200",
35850:"",
35900:"",
35950:"",
36000:"ТО4000",
36050:"",
36100:"",
36150:"",
36200:"ТО200",
36250:"",
36300:"",
36350:"",
36400:"ТО400",
36450:"",
36500:"",
36550:"",
36600:"ТО200",
36650:"",
36700:"",
36750:"",
36800:"ТО1600",
36850:"",
36900:"",
36950:"",
37000:"ТО200",
37050:"",
37100:"",
37150:"",
37200:"ТО400",
37250:"",
37300:"",
37350:"",
37400:"ТО200",
37450:"",
37500:"",
37550:"",
37600:"ТО400",
37650:"",
37700:"",
37750:"",
37800:"ТО200",
37850:"",
37900:"",
37950:"",
38000:"ТО400",
38050:"",
38100:"",
38150:"",
38200:"ТО200",
38250:"",
38300:"",
38350:"",
38400:"ТО3200",
38450:"",
38500:"",
38550:"",
38600:"ТО200",
38650:"",
38700:"",
38750:"",
38800:"ТО400",
38850:"",
38900:"",
38950:"",
39000:"ТО200",
39050:"",
39100:"",
39150:"",
39200:"ТО400",
39250:"",
39300:"",
39350:"",
39400:"ТО200",
39450:"",
39500:"",
39550:"",
39600:"ТО400",
39650:"",
39700:"",
39750:"",
39800:"ТО200",
39850:"",
39900:"",
39950:"",
40000:"ТО4000",
40050:"",
40100:"",
40150:"",
40200:"ТО200",
40250:"",
40300:"",
40350:"",
40400:"ТО400",
40450:"",
40500:"",
40550:"",
40600:"ТО200",
40650:"",
40700:"",
40750:"",
40800:"ТО400",
40850:"",
40900:"",
40950:"",
41000:"ТО200",
41050:"",
41100:"",
41150:"",
41200:"ТО400",
41250:"",
41300:"",
41350:"",
41400:"ТО200",
41450:"",
41500:"",
41550:"",
41600:"ТО3200",
41650:"",
41700:"",
41750:"",
41800:"ТО200",
41850:"",
41900:"",
41950:"",
42000:"ТО400",
42050:"",
42100:"",
42150:"",
42200:"ТО200",
42250:"",
42300:"",
42350:"",
42400:"ТО400",
42450:"",
42500:"",
42550:"",
42600:"ТО200",
42650:"",
42700:"",
42750:"",
42800:"ТО400",
42850:"",
42900:"",
42950:"",
43000:"ТО200",
43050:"",
43100:"",
43150:"",
43200:"ТО1600",
43250:"",
43300:"",
43350:"",
43400:"ТО200",
43450:"",
43500:"",
43550:"",
43600:"ТО400",
43650:"",
43700:"",
43750:"",
43800:"ТО200",
43850:"",
43900:"",
43950:"",
44000:"ТО4000",
44050:"",
44100:"",
44150:"",
44200:"ТО200",
44250:"",
44300:"",
44350:"",
44400:"ТО400",
44450:"",
44500:"",
44550:"",
44600:"ТО200",
44650:"",
44700:"",
44750:"",
44800:"ТО3200",
44850:"",
44900:"",
44950:"",
45000:"ТО200",
45050:"",
45100:"",
45150:"",
45200:"ТО400",
45250:"",
45300:"",
45350:"",
45400:"ТО200",
45450:"",
45500:"",
45550:"",
45600:"ТО400",
45650:"",
45700:"",
45750:"",
45800:"ТО200",
45850:"",
45900:"",
45950:"",
46000:"ТО400",
46050:"",
46100:"",
46150:"",
46200:"ТО200",
46250:"",
46300:"",
46350:"",
46400:"ТО1600",
46450:"",
46500:"",
46550:"",
46600:"ТО200",
46650:"",
46700:"",
46750:"",
46800:"ТО400",
46850:"",
46900:"",
46950:"",
47000:"ТО200",
47050:"",
47100:"",
47150:"",
47200:"ТО400",
47250:"",
47300:"",
47350:"",
47400:"ТО200",
47450:"",
47500:"",
47550:"",
47600:"ТО400",
47650:"",
47700:"",
47750:"",
47800:"ТО200",
47850:"",
47900:"",
47950:"",
48000:"ТО4000"
      
}

In [62]:
to_dict_DCA={
    50:"",
100:"",
150:"",
200:"",
250:"ТО250",
300:"",
350:"",
400:"",
450:"",
500:"ТО500",
550:"",
600:"",
650:"",
700:"",
750:"ТО250",
800:"",
850:"",
900:"",
950:"",
1000:"ТО1000",
1050:"",
1100:"",
1150:"",
1200:"",
1250:"ТО250",
1300:"",
1350:"",
1400:"",
1450:"",
1500:"ТО500",
1550:"",
1600:"",
1650:"",
1700:"",
1750:"ТО250",
1800:"",
1850:"",
1900:"",
1950:"",
2000:"ТО2000",
2050:"",
2100:"",
2150:"",
2200:"",
2250:"ТО250",
2300:"",
2350:"",
2400:"",
2450:"",
2500:"ТО500",
2550:"",
2600:"",
2650:"",
2700:"",
2750:"ТО250",
2800:"",
2850:"",
2900:"",
2950:"",
3000:"ТО1000",
3050:"",
3100:"",
3150:"",
3200:"",
3250:"ТО250",
3300:"",
3350:"",
3400:"",
3450:"",
3500:"ТО500",
3550:"",
3600:"",
3650:"",
3700:"",
3750:"ТО250",
3800:"",
3850:"",
3900:"",
3950:"",
4000:"ТО4000",
4050:"",
4100:"",
4150:"",
4200:"",
4250:"ТО250",
4300:"",
4350:"",
4400:"",
4450:"",
4500:"ТО500",
4550:"",
4600:"",
4650:"",
4700:"",
4750:"ТО250",
4800:"",
4850:"",
4900:"",
4950:"",
5000:"ТО1000",
5050:"",
5100:"",
5150:"",
5200:"",
5250:"ТО250",
5300:"",
5350:"",
5400:"",
5450:"",
5500:"ТО500",
5550:"",
5600:"",
5650:"",
5700:"",
5750:"ТО250",
5800:"",
5850:"",
5900:"",
5950:"",
6000:"ТО2000",
6050:"",
6100:"",
6150:"",
6200:"",
6250:"ТО250",
6300:"",
6350:"",
6400:"",
6450:"",
6500:"ТО500",
6550:"",
6600:"",
6650:"",
6700:"",
6750:"ТО250",
6800:"",
6850:"",
6900:"",
6950:"",
7000:"ТО1000",
7050:"",
7100:"",
7150:"",
7200:"",
7250:"ТО250",
7300:"",
7350:"",
7400:"",
7450:"",
7500:"ТО500",
7550:"",
7600:"",
7650:"",
7700:"",
7750:"ТО250",
7800:"",
7850:"",
7900:"",
7950:"",
8000:"ТО4000",
8050:"",
8100:"",
8150:"",
8200:"",
8250:"ТО250",
8300:"",
8350:"",
8400:"",
8450:"",
8500:"ТО500",
8550:"",
8600:"",
8650:"",
8700:"",
8750:"ТО250",
8800:"",
8850:"",
8900:"",
8950:"",
9000:"ТО1000",
9050:"",
9100:"",
9150:"",
9200:"",
9250:"ТО250",
9300:"",
9350:"",
9400:"",
9450:"",
9500:"ТО500",
9550:"",
9600:"",
9650:"",
9700:"",
9750:"ТО250",
9800:"",
9850:"",
9900:"",
9950:"",
10000:"ТО2000",
10050:"",
10100:"",
10150:"",
10200:"",
10250:"ТО250",
10300:"",
10350:"",
10400:"",
10450:"",
10500:"ТО500",
10550:"",
10600:"",
10650:"",
10700:"",
10750:"ТО250",
10800:"",
10850:"",
10900:"",
10950:"",
11000:"ТО1000",
11050:"",
11100:"",
11150:"",
11200:"",
11250:"ТО250",
11300:"",
11350:"",
11400:"",
11450:"",
11500:"ТО500",
11550:"",
11600:"",
11650:"",
11700:"",
11750:"ТО250",
11800:"",
11850:"",
11900:"",
11950:"",
12000:"ТО4000",
12050:"",
12100:"",
12150:"",
12200:"",
12250:"ТО250",
12300:"",
12350:"",
12400:"",
12450:"",
12500:"ТО500",
12550:"",
12600:"",
12650:"",
12700:"",
12750:"ТО250",
12800:"",
12850:"",
12900:"",
12950:"",
13000:"ТО1000",
13050:"",
13100:"",
13150:"",
13200:"",
13250:"ТО250",
13300:"",
13350:"",
13400:"",
13450:"",
13500:"ТО500",
13550:"",
13600:"",
13650:"",
13700:"",
13750:"ТО250",
13800:"",
13850:"",
13900:"",
13950:"",
14000:"ТО2000",
14050:"",
14100:"",
14150:"",
14200:"",
14250:"ТО250",
14300:"",
14350:"",
14400:"",
14450:"",
14500:"ТО500",
14550:"",
14600:"",
14650:"",
14700:"",
14750:"ТО250",
14800:"",
14850:"",
14900:"",
14950:"",
15000:"ТО1000",
15050:"",
15100:"",
15150:"",
15200:"",
15250:"ТО250",
15300:"",
15350:"",
15400:"",
15450:"",
15500:"ТО500",
15550:"",
15600:"",
15650:"",
15700:"",
15750:"ТО250",
15800:"",
15850:"",
15900:"",
15950:"",
16000:"ТО4000",
16050:"",
16100:"",
16150:"",
16200:"",
16250:"ТО250",
16300:"",
16350:"",
16400:"",
16450:"",
16500:"ТО500",
16550:"",
16600:"",
16650:"",
16700:"",
16750:"ТО250",
16800:"",
16850:"",
16900:"",
16950:"",
17000:"ТО1000",
17050:"",
17100:"",
17150:"",
17200:"",
17250:"ТО250",
17300:"",
17350:"",
17400:"",
17450:"",
17500:"ТО500",
17550:"",
17600:"",
17650:"",
17700:"",
17750:"ТО250",
17800:"",
17850:"",
17900:"",
17950:"",
18000:"ТО2000",
18050:"",
18100:"",
18150:"",
18200:"",
18250:"ТО250",
18300:"",
18350:"",
18400:"",
18450:"",
18500:"ТО500",
18550:"",
18600:"",
18650:"",
18700:"",
18750:"ТО250",
18800:"",
18850:"",
18900:"",
18950:"",
19000:"ТО1000",
19050:"",
19100:"",
19150:"",
19200:"",
19250:"ТО250",
19300:"",
19350:"",
19400:"",
19450:"",
19500:"ТО500",
19550:"",
19600:"",
19650:"",
19700:"",
19750:"ТО250",
19800:"",
19850:"",
19900:"",
19950:"",
20000:"ТО4000",
20050:"",
20100:"",
20150:"",
20200:"",
20250:"ТО250",
20300:"",
20350:"",
20400:"",
20450:"",
20500:"ТО500",
20550:"",
20600:"",
20650:"",
20700:"",
20750:"ТО250",
20800:"",
20850:"",
20900:"",
20950:"",
21000:"ТО1000",
21050:"",
21100:"",
21150:"",
21200:"",
21250:"ТО250",
21300:"",
21350:"",
21400:"",
21450:"",
21500:"ТО500",
21550:"",
21600:"",
21650:"",
21700:"",
21750:"ТО250",
21800:"",
21850:"",
21900:"",
21950:"",
22000:"ТО2000",
22050:"",
22100:"",
22150:"",
22200:"",
22250:"ТО250",
22300:"",
22350:"",
22400:"",
22450:"",
22500:"ТО500",
22550:"",
22600:"",
22650:"",
22700:"",
22750:"ТО250",
22800:"",
22850:"",
22900:"",
22950:"",
23000:"ТО1000",
23050:"",
23100:"",
23150:"",
23200:"",
23250:"ТО250",
23300:"",
23350:"",
23400:"",
23450:"",
23500:"ТО500",
23550:"",
23600:"",
23650:"",
23700:"",
23750:"ТО250",
23800:"",
23850:"",
23900:"",
23950:"",
24000:"ТО4000",
24050:"",
24100:"",
24150:"",
24200:"",
24250:"ТО250",
24300:"",
24350:"",
24400:"",
24450:"",
24500:"ТО500",
24550:"",
24600:"",
24650:"",
24700:"",
24750:"ТО250",
24800:"",
24850:"",
24900:"",
24950:"",
25000:"ТО1000",
25050:"",
25100:"",
25150:"",
25200:"",
25250:"ТО250",
25300:"",
25350:"",
25400:"",
25450:"",
25500:"ТО500",
25550:"",
25600:"",
25650:"",
25700:"",
25750:"ТО250",
25800:"",
25850:"",
25900:"",
25950:"",
26000:"ТО2000",
26050:"",
26100:"",
26150:"",
26200:"",
26250:"ТО250",
26300:"",
26350:"",
26400:"",
26450:"",
26500:"ТО500",
26550:"",
26600:"",
26650:"",
26700:"",
26750:"ТО250",
26800:"",
26850:"",
26900:"",
26950:"",
27000:"ТО1000",
27050:"",
27100:"",
27150:"",
27200:"",
27250:"ТО250",
27300:"",
27350:"",
27400:"",
27450:"",
27500:"ТО500",
27550:"",
27600:"",
27650:"",
27700:"",
27750:"ТО250",
27800:"",
27850:"",
27900:"",
27950:"",
28000:"ТО4000",
28050:"",
28100:"",
28150:"",
28200:"",
28250:"ТО250",
28300:"",
28350:"",
28400:"",
28450:"",
28500:"ТО500",
28550:"",
28600:"",
28650:"",
28700:"",
28750:"ТО250",
28800:"",
28850:"",
28900:"",
28950:"",
29000:"ТО1000",
29050:"",
29100:"",
29150:"",
29200:"",
29250:"ТО250",
29300:"",
29350:"",
29400:"",
29450:"",
29500:"ТО500",
29550:"",
29600:"",
29650:"",
29700:"",
29750:"ТО250",
29800:"",
29850:"",
29900:"",
29950:"",
30000:"ТО2000",
30050:"",
30100:"",
30150:"",
30200:"",
30250:"ТО250",
30300:"",
30350:"",
30400:"",
30450:"",
30500:"ТО500",
30550:"",
30600:"",
30650:"",
30700:"",
30750:"ТО250",
30800:"",
30850:"",
30900:"",
30950:"",
31000:"ТО1000",
31050:"",
31100:"",
31150:"",
31200:"",
31250:"ТО250",
31300:"",
31350:"",
31400:"",
31450:"",
31500:"ТО500",
31550:"",
31600:"",
31650:"",
31700:"",
31750:"ТО250",
31800:"",
31850:"",
31900:"",
31950:"",
32000:"ТО4000",
32050:"",
32100:"",
32150:"",
32200:"",
32250:"ТО250",
32300:"",
32350:"",
32400:"",
32450:"",
32500:"ТО500",
32550:"",
32600:"",
32650:"",
32700:"",
32750:"ТО250",
32800:"",
32850:"",
32900:"",
32950:"",
33000:"ТО1000",
33050:"",
33100:"",
33150:"",
33200:"",
33250:"ТО250",
33300:"",
33350:"",
33400:"",
33450:"",
33500:"ТО500",
33550:"",
33600:"",
33650:"",
33700:"",
33750:"ТО250",
33800:"",
33850:"",
33900:"",
33950:"",
34000:"ТО2000",
34050:"",
34100:"",
34150:"",
34200:"",
34250:"ТО250",
34300:"",
34350:"",
34400:"",
34450:"",
34500:"ТО500",
34550:"",
34600:"",
34650:"",
34700:"",
34750:"ТО250",
34800:"",
34850:"",
34900:"",
34950:"",
35000:"ТО1000",
35050:"",
35100:"",
35150:"",
35200:"",
35250:"ТО250",
35300:"",
35350:"",
35400:"",
35450:"",
35500:"ТО500",
35550:"",
35600:"",
35650:"",
35700:"",
35750:"ТО250",
35800:"",
35850:"",
35900:"",
35950:"",
36000:"ТО4000",
36050:"",
36100:"",
36150:"",
36200:"",
36250:"ТО250",
36300:"",
36350:"",
36400:"",
36450:"",
36500:"ТО500",
36550:"",
36600:"",
36650:"",
36700:"",
36750:"ТО250",
36800:"",
36850:"",
36900:"",
36950:"",
37000:"ТО1000",
37050:"",
37100:"",
37150:"",
37200:"",
37250:"ТО250",
37300:"",
37350:"",
37400:"",
37450:"",
37500:"ТО500",
37550:"",
37600:"",
37650:"",
37700:"",
37750:"ТО250",
37800:"",
37850:"",
37900:"",
37950:"",
38000:"ТО2000",
38050:"",
38100:"",
38150:"",
38200:"",
38250:"ТО250",
38300:"",
38350:"",
38400:"",
38450:"",
38500:"ТО500",
38550:"",
38600:"",
38650:"",
38700:"",
38750:"ТО250",
38800:"",
38850:"",
38900:"",
38950:"",
39000:"ТО1000",
39050:"",
39100:"",
39150:"",
39200:"",
39250:"ТО250",
39300:"",
39350:"",
39400:"",
39450:"",
39500:"ТО500",
39550:"",
39600:"",
39650:"",
39700:"",
39750:"ТО250",
39800:"",
39850:"",
39900:"",
39950:"",
40000:"ТО4000",
40050:"",
40100:"",
40150:"",
40200:"",
40250:"ТО250",
40300:"",
40350:"",
40400:"",
40450:"",
40500:"ТО500",
40550:"",
40600:"",
40650:"",
40700:"",
40750:"ТО250",
40800:"",
40850:"",
40900:"",
40950:"",
41000:"ТО1000",
41050:"",
41100:"",
41150:"",
41200:"",
41250:"ТО250",
41300:"",
41350:"",
41400:"",
41450:"",
41500:"ТО500",
41550:"",
41600:"",
41650:"",
41700:"",
41750:"ТО250",
41800:"",
41850:"",
41900:"",
41950:"",
42000:"ТО2000",
42050:"",
42100:"",
42150:"",
42200:"",
42250:"ТО250",
42300:"",
42350:"",
42400:"",
42450:"",
42500:"ТО500",
42550:"",
42600:"",
42650:"",
42700:"",
42750:"ТО250",
42800:"",
42850:"",
42900:"",
42950:"",
43000:"ТО1000",
43050:"",
43100:"",
43150:"",
43200:"",
43250:"ТО250",
43300:"",
43350:"",
43400:"",
43450:"",
43500:"ТО500",
43550:"",
43600:"",
43650:"",
43700:"",
43750:"ТО250",
43800:"",
43850:"",
43900:"",
43950:"",
44000:"ТО4000",
44050:"",
44100:"",
44150:"",
44200:"",
44250:"ТО250",
44300:"",
44350:"",
44400:"",
44450:"",
44500:"ТО500",
44550:"",
44600:"",
44650:"",
44700:"",
44750:"ТО250",
44800:"",
44850:"",
44900:"",
44950:"",
45000:"ТО1000",
45050:"",
45100:"",
45150:"",
45200:"",
45250:"ТО250",
45300:"",
45350:"",
45400:"",
45450:"",
45500:"ТО500",
45550:"",
45600:"",
45650:"",
45700:"",
45750:"ТО250",
45800:"",
45850:"",
45900:"",
45950:"",
46000:"ТО2000",
46050:"",
46100:"",
46150:"",
46200:"",
46250:"ТО250",
46300:"",
46350:"",
46400:"",
46450:"",
46500:"ТО500",
46550:"",
46600:"",
46650:"",
46700:"",
46750:"ТО250",
46800:"",
46850:"",
46900:"",
46950:"",
47000:"ТО1000",
47050:"",
47100:"",
47150:"",
47200:"",
47250:"ТО250",
47300:"",
47350:"",
47400:"",
47450:"",
47500:"ТО500",
47550:"",
47600:"",
47650:"",
47700:"",
47750:"ТО250",
47800:"",
47850:"",
47900:"",
47950:"",
48000:"ТО4000"
     
}

In [63]:
to_dict_DCA_AD200={
    50:"",
100:"",
150:"",
200:"",
250:"",
300:"",
350:"",
400:"",
450:"",
500:"ТО500",
550:"",
600:"",
650:"",
700:"",
750:"",
800:"",
850:"",
900:"",
950:"",
1000:"ТО1000",
1050:"",
1100:"",
1150:"",
1200:"",
1250:"",
1300:"",
1350:"",
1400:"",
1450:"",
1500:"ТО500",
1550:"",
1600:"",
1650:"",
1700:"",
1750:"",
1800:"",
1850:"",
1900:"",
1950:"",
2000:"ТО2000",
2050:"",
2100:"",
2150:"",
2200:"",
2250:"",
2300:"",
2350:"",
2400:"",
2450:"",
2500:"ТО500",
2550:"",
2600:"",
2650:"",
2700:"",
2750:"",
2800:"",
2850:"",
2900:"",
2950:"",
3000:"ТО1000",
3050:"",
3100:"",
3150:"",
3200:"",
3250:"",
3300:"",
3350:"",
3400:"",
3450:"",
3500:"ТО500",
3550:"",
3600:"",
3650:"",
3700:"",
3750:"",
3800:"",
3850:"",
3900:"",
3950:"",
4000:"ТО4000",
4050:"",
4100:"",
4150:"",
4200:"",
4250:"",
4300:"",
4350:"",
4400:"",
4450:"",
4500:"ТО500",
4550:"",
4600:"",
4650:"",
4700:"",
4750:"",
4800:"",
4850:"",
4900:"",
4950:"",
5000:"ТО1000",
5050:"",
5100:"",
5150:"",
5200:"",
5250:"",
5300:"",
5350:"",
5400:"",
5450:"",
5500:"ТО500",
5550:"",
5600:"",
5650:"",
5700:"",
5750:"",
5800:"",
5850:"",
5900:"",
5950:"",
6000:"ТО2000",
6050:"",
6100:"",
6150:"",
6200:"",
6250:"",
6300:"",
6350:"",
6400:"",
6450:"",
6500:"ТО500",
6550:"",
6600:"",
6650:"",
6700:"",
6750:"",
6800:"",
6850:"",
6900:"",
6950:"",
7000:"ТО1000",
7050:"",
7100:"",
7150:"",
7200:"",
7250:"",
7300:"",
7350:"",
7400:"",
7450:"",
7500:"ТО500",
7550:"",
7600:"",
7650:"",
7700:"",
7750:"",
7800:"",
7850:"",
7900:"",
7950:"",
8000:"ТО4000",
8050:"",
8100:"",
8150:"",
8200:"",
8250:"",
8300:"",
8350:"",
8400:"",
8450:"",
8500:"ТО500",
8550:"",
8600:"",
8650:"",
8700:"",
8750:"",
8800:"",
8850:"",
8900:"",
8950:"",
9000:"ТО1000",
9050:"",
9100:"",
9150:"",
9200:"",
9250:"",
9300:"",
9350:"",
9400:"",
9450:"",
9500:"ТО500",
9550:"",
9600:"",
9650:"",
9700:"",
9750:"",
9800:"",
9850:"",
9900:"",
9950:"",
10000:"ТО2000",
10050:"",
10100:"",
10150:"",
10200:"",
10250:"",
10300:"",
10350:"",
10400:"",
10450:"",
10500:"ТО500",
10550:"",
10600:"",
10650:"",
10700:"",
10750:"",
10800:"",
10850:"",
10900:"",
10950:"",
11000:"ТО1000",
11050:"",
11100:"",
11150:"",
11200:"",
11250:"",
11300:"",
11350:"",
11400:"",
11450:"",
11500:"ТО500",
11550:"",
11600:"",
11650:"",
11700:"",
11750:"",
11800:"",
11850:"",
11900:"",
11950:"",
12000:"ТО4000",
12050:"",
12100:"",
12150:"",
12200:"",
12250:"",
12300:"",
12350:"",
12400:"",
12450:"",
12500:"ТО500",
12550:"",
12600:"",
12650:"",
12700:"",
12750:"",
12800:"",
12850:"",
12900:"",
12950:"",
13000:"ТО1000",
13050:"",
13100:"",
13150:"",
13200:"",
13250:"",
13300:"",
13350:"",
13400:"",
13450:"",
13500:"ТО500",
13550:"",
13600:"",
13650:"",
13700:"",
13750:"",
13800:"",
13850:"",
13900:"",
13950:"",
14000:"ТО2000",
14050:"",
14100:"",
14150:"",
14200:"",
14250:"",
14300:"",
14350:"",
14400:"",
14450:"",
14500:"ТО500",
14550:"",
14600:"",
14650:"",
14700:"",
14750:"",
14800:"",
14850:"",
14900:"",
14950:"",
15000:"ТО1000",
15050:"",
15100:"",
15150:"",
15200:"",
15250:"",
15300:"",
15350:"",
15400:"",
15450:"",
15500:"ТО500",
15550:"",
15600:"",
15650:"",
15700:"",
15750:"",
15800:"",
15850:"",
15900:"",
15950:"",
16000:"ТО4000",
16050:"",
16100:"",
16150:"",
16200:"",
16250:"",
16300:"",
16350:"",
16400:"",
16450:"",
16500:"ТО500",
16550:"",
16600:"",
16650:"",
16700:"",
16750:"",
16800:"",
16850:"",
16900:"",
16950:"",
17000:"ТО1000",
17050:"",
17100:"",
17150:"",
17200:"",
17250:"",
17300:"",
17350:"",
17400:"",
17450:"",
17500:"ТО500",
17550:"",
17600:"",
17650:"",
17700:"",
17750:"",
17800:"",
17850:"",
17900:"",
17950:"",
18000:"ТО2000",
18050:"",
18100:"",
18150:"",
18200:"",
18250:"",
18300:"",
18350:"",
18400:"",
18450:"",
18500:"ТО500",
18550:"",
18600:"",
18650:"",
18700:"",
18750:"",
18800:"",
18850:"",
18900:"",
18950:"",
19000:"ТО1000",
19050:"",
19100:"",
19150:"",
19200:"",
19250:"",
19300:"",
19350:"",
19400:"",
19450:"",
19500:"ТО500",
19550:"",
19600:"",
19650:"",
19700:"",
19750:"",
19800:"",
19850:"",
19900:"",
19950:"",
20000:"ТО4000",
20050:"",
20100:"",
20150:"",
20200:"",
20250:"",
20300:"",
20350:"",
20400:"",
20450:"",
20500:"ТО500",
20550:"",
20600:"",
20650:"",
20700:"",
20750:"",
20800:"",
20850:"",
20900:"",
20950:"",
21000:"ТО1000",
21050:"",
21100:"",
21150:"",
21200:"",
21250:"",
21300:"",
21350:"",
21400:"",
21450:"",
21500:"ТО500",
21550:"",
21600:"",
21650:"",
21700:"",
21750:"",
21800:"",
21850:"",
21900:"",
21950:"",
22000:"ТО2000",
22050:"",
22100:"",
22150:"",
22200:"",
22250:"",
22300:"",
22350:"",
22400:"",
22450:"",
22500:"ТО500",
22550:"",
22600:"",
22650:"",
22700:"",
22750:"",
22800:"",
22850:"",
22900:"",
22950:"",
23000:"ТО1000",
23050:"",
23100:"",
23150:"",
23200:"",
23250:"",
23300:"",
23350:"",
23400:"",
23450:"",
23500:"ТО500",
23550:"",
23600:"",
23650:"",
23700:"",
23750:"",
23800:"",
23850:"",
23900:"",
23950:"",
24000:"ТО4000",
24050:"",
24100:"",
24150:"",
24200:"",
24250:"",
24300:"",
24350:"",
24400:"",
24450:"",
24500:"ТО500",
24550:"",
24600:"",
24650:"",
24700:"",
24750:"",
24800:"",
24850:"",
24900:"",
24950:"",
25000:"ТО1000",
25050:"",
25100:"",
25150:"",
25200:"",
25250:"",
25300:"",
25350:"",
25400:"",
25450:"",
25500:"ТО500",
25550:"",
25600:"",
25650:"",
25700:"",
25750:"",
25800:"",
25850:"",
25900:"",
25950:"",
26000:"ТО2000",
26050:"",
26100:"",
26150:"",
26200:"",
26250:"",
26300:"",
26350:"",
26400:"",
26450:"",
26500:"ТО500",
26550:"",
26600:"",
26650:"",
26700:"",
26750:"",
26800:"",
26850:"",
26900:"",
26950:"",
27000:"ТО1000",
27050:"",
27100:"",
27150:"",
27200:"",
27250:"",
27300:"",
27350:"",
27400:"",
27450:"",
27500:"ТО500",
27550:"",
27600:"",
27650:"",
27700:"",
27750:"",
27800:"",
27850:"",
27900:"",
27950:"",
28000:"ТО4000",
28050:"",
28100:"",
28150:"",
28200:"",
28250:"",
28300:"",
28350:"",
28400:"",
28450:"",
28500:"ТО500",
28550:"",
28600:"",
28650:"",
28700:"",
28750:"",
28800:"",
28850:"",
28900:"",
28950:"",
29000:"ТО1000",
29050:"",
29100:"",
29150:"",
29200:"",
29250:"",
29300:"",
29350:"",
29400:"",
29450:"",
29500:"ТО500",
29550:"",
29600:"",
29650:"",
29700:"",
29750:"",
29800:"",
29850:"",
29900:"",
29950:"",
30000:"ТО2000",
30050:"",
30100:"",
30150:"",
30200:"",
30250:"",
30300:"",
30350:"",
30400:"",
30450:"",
30500:"ТО500",
30550:"",
30600:"",
30650:"",
30700:"",
30750:"",
30800:"",
30850:"",
30900:"",
30950:"",
31000:"ТО1000",
31050:"",
31100:"",
31150:"",
31200:"",
31250:"",
31300:"",
31350:"",
31400:"",
31450:"",
31500:"ТО500",
31550:"",
31600:"",
31650:"",
31700:"",
31750:"",
31800:"",
31850:"",
31900:"",
31950:"",
32000:"ТО4000",
32050:"",
32100:"",
32150:"",
32200:"",
32250:"",
32300:"",
32350:"",
32400:"",
32450:"",
32500:"ТО500",
32550:"",
32600:"",
32650:"",
32700:"",
32750:"",
32800:"",
32850:"",
32900:"",
32950:"",
33000:"ТО1000",
33050:"",
33100:"",
33150:"",
33200:"",
33250:"",
33300:"",
33350:"",
33400:"",
33450:"",
33500:"ТО500",
33550:"",
33600:"",
33650:"",
33700:"",
33750:"",
33800:"",
33850:"",
33900:"",
33950:"",
34000:"ТО2000",
34050:"",
34100:"",
34150:"",
34200:"",
34250:"",
34300:"",
34350:"",
34400:"",
34450:"",
34500:"ТО500",
34550:"",
34600:"",
34650:"",
34700:"",
34750:"",
34800:"",
34850:"",
34900:"",
34950:"",
35000:"ТО1000",
35050:"",
35100:"",
35150:"",
35200:"",
35250:"",
35300:"",
35350:"",
35400:"",
35450:"",
35500:"ТО500",
35550:"",
35600:"",
35650:"",
35700:"",
35750:"",
35800:"",
35850:"",
35900:"",
35950:"",
36000:"ТО4000",
36050:"",
36100:"",
36150:"",
36200:"",
36250:"",
36300:"",
36350:"",
36400:"",
36450:"",
36500:"ТО500",
36550:"",
36600:"",
36650:"",
36700:"",
36750:"",
36800:"",
36850:"",
36900:"",
36950:"",
37000:"ТО1000",
37050:"",
37100:"",
37150:"",
37200:"",
37250:"",
37300:"",
37350:"",
37400:"",
37450:"",
37500:"ТО500",
37550:"",
37600:"",
37650:"",
37700:"",
37750:"",
37800:"",
37850:"",
37900:"",
37950:"",
38000:"ТО2000",
38050:"",
38100:"",
38150:"",
38200:"",
38250:"",
38300:"",
38350:"",
38400:"",
38450:"",
38500:"ТО500",
38550:"",
38600:"",
38650:"",
38700:"",
38750:"",
38800:"",
38850:"",
38900:"",
38950:"",
39000:"ТО1000",
39050:"",
39100:"",
39150:"",
39200:"",
39250:"",
39300:"",
39350:"",
39400:"",
39450:"",
39500:"ТО500",
39550:"",
39600:"",
39650:"",
39700:"",
39750:"",
39800:"",
39850:"",
39900:"",
39950:"",
40000:"ТО4000",
40050:"",
40100:"",
40150:"",
40200:"",
40250:"",
40300:"",
40350:"",
40400:"",
40450:"",
40500:"ТО500",
40550:"",
40600:"",
40650:"",
40700:"",
40750:"",
40800:"",
40850:"",
40900:"",
40950:"",
41000:"ТО1000",
41050:"",
41100:"",
41150:"",
41200:"",
41250:"",
41300:"",
41350:"",
41400:"",
41450:"",
41500:"ТО500",
41550:"",
41600:"",
41650:"",
41700:"",
41750:"",
41800:"",
41850:"",
41900:"",
41950:"",
42000:"ТО2000",
42050:"",
42100:"",
42150:"",
42200:"",
42250:"",
42300:"",
42350:"",
42400:"",
42450:"",
42500:"ТО500",
42550:"",
42600:"",
42650:"",
42700:"",
42750:"",
42800:"",
42850:"",
42900:"",
42950:"",
43000:"ТО1000",
43050:"",
43100:"",
43150:"",
43200:"",
43250:"",
43300:"",
43350:"",
43400:"",
43450:"",
43500:"ТО500",
43550:"",
43600:"",
43650:"",
43700:"",
43750:"",
43800:"",
43850:"",
43900:"",
43950:"",
44000:"ТО4000",
44050:"",
44100:"",
44150:"",
44200:"",
44250:"",
44300:"",
44350:"",
44400:"",
44450:"",
44500:"ТО500",
44550:"",
44600:"",
44650:"",
44700:"",
44750:"",
44800:"",
44850:"",
44900:"",
44950:"",
45000:"ТО1000",
45050:"",
45100:"",
45150:"",
45200:"",
45250:"",
45300:"",
45350:"",
45400:"",
45450:"",
45500:"ТО500",
45550:"",
45600:"",
45650:"",
45700:"",
45750:"",
45800:"",
45850:"",
45900:"",
45950:"",
46000:"ТО2000",
46050:"",
46100:"",
46150:"",
46200:"",
46250:"",
46300:"",
46350:"",
46400:"",
46450:"",
46500:"ТО500",
46550:"",
46600:"",
46650:"",
46700:"",
46750:"",
46800:"",
46850:"",
46900:"",
46950:"",
47000:"ТО1000",
47050:"",
47100:"",
47150:"",
47200:"",
47250:"",
47300:"",
47350:"",
47400:"",
47450:"",
47500:"ТО500",
47550:"",
47600:"",
47650:"",
47700:"",
47750:"",
47800:"",
47850:"",
47900:"",
47950:"",
48000:"ТО4000"
    
}

In [64]:
to_dict_DCA_ED30={
    50:"",
100:"",
150:"",
200:"",
250:"ТО250",
300:"",
350:"",
400:"",
450:"",
500:"ТО500",
550:"",
600:"",
650:"",
700:"",
750:"ТО250",
800:"",
850:"",
900:"",
950:"",
1000:"ТО500",
1050:"",
1100:"",
1150:"",
1200:"",
1250:"ТО250",
1300:"",
1350:"",
1400:"",
1450:"",
1500:"ТО1500",
1550:"",
1600:"",
1650:"",
1700:"",
1750:"ТО250",
1800:"",
1850:"",
1900:"",
1950:"",
2000:"ТО500",
2050:"",
2100:"",
2150:"",
2200:"",
2250:"ТО250",
2300:"",
2350:"",
2400:"",
2450:"",
2500:"ТО500",
2550:"",
2600:"",
2650:"",
2700:"",
2750:"ТО250",
2800:"",
2850:"",
2900:"",
2950:"",
3000:"ТО3000",
3050:"",
3100:"",
3150:"",
3200:"",
3250:"ТО250",
3300:"",
3350:"",
3400:"",
3450:"",
3500:"ТО500",
3550:"",
3600:"",
3650:"",
3700:"",
3750:"ТО250",
3800:"",
3850:"",
3900:"",
3950:"",
4000:"ТО500",
4050:"",
4100:"",
4150:"",
4200:"",
4250:"ТО250",
4300:"",
4350:"",
4400:"",
4450:"",
4500:"ТО1500",
4550:"",
4600:"",
4650:"",
4700:"",
4750:"ТО250",
4800:"",
4850:"",
4900:"",
4950:"",
5000:"ТО500",
5050:"",
5100:"",
5150:"",
5200:"",
5250:"ТО250",
5300:"",
5350:"",
5400:"",
5450:"",
5500:"ТО500",
5550:"",
5600:"",
5650:"",
5700:"",
5750:"ТО250",
5800:"",
5850:"",
5900:"",
5950:"",
6000:"ТО3000",
6050:"",
6100:"",
6150:"",
6200:"",
6250:"ТО250",
6300:"",
6350:"",
6400:"",
6450:"",
6500:"ТО500",
6550:"",
6600:"",
6650:"",
6700:"",
6750:"ТО250",
6800:"",
6850:"",
6900:"",
6950:"",
7000:"ТО500",
7050:"",
7100:"",
7150:"",
7200:"",
7250:"ТО250",
7300:"",
7350:"",
7400:"",
7450:"",
7500:"ТО1500",
7550:"",
7600:"",
7650:"",
7700:"",
7750:"ТО250",
7800:"",
7850:"",
7900:"",
7950:"",
8000:"ТО500",
8050:"",
8100:"",
8150:"",
8200:"",
8250:"ТО250",
8300:"",
8350:"",
8400:"",
8450:"",
8500:"ТО500",
8550:"",
8600:"",
8650:"",
8700:"",
8750:"ТО250",
8800:"",
8850:"",
8900:"",
8950:"",
9000:"ТО3000",
9050:"",
9100:"",
9150:"",
9200:"",
9250:"ТО250",
9300:"",
9350:"",
9400:"",
9450:"",
9500:"ТО500",
9550:"",
9600:"",
9650:"",
9700:"",
9750:"ТО250",
9800:"",
9850:"",
9900:"",
9950:"",
10000:"ТО500",
10050:"",
10100:"",
10150:"",
10200:"",
10250:"ТО250",
10300:"",
10350:"",
10400:"",
10450:"",
10500:"ТО1500",
10550:"",
10600:"",
10650:"",
10700:"",
10750:"ТО250",
10800:"",
10850:"",
10900:"",
10950:"",
11000:"ТО500",
11050:"",
11100:"",
11150:"",
11200:"",
11250:"ТО250",
11300:"",
11350:"",
11400:"",
11450:"",
11500:"ТО500",
11550:"",
11600:"",
11650:"",
11700:"",
11750:"ТО250",
11800:"",
11850:"",
11900:"",
11950:"",
12000:"ТО3000",
12050:"",
12100:"",
12150:"",
12200:"",
12250:"ТО250",
12300:"",
12350:"",
12400:"",
12450:"",
12500:"ТО500",
12550:"",
12600:"",
12650:"",
12700:"",
12750:"ТО250",
12800:"",
12850:"",
12900:"",
12950:"",
13000:"ТО500",
13050:"",
13100:"",
13150:"",
13200:"",
13250:"ТО250",
13300:"",
13350:"",
13400:"",
13450:"",
13500:"ТО1500",
13550:"",
13600:"",
13650:"",
13700:"",
13750:"ТО250",
13800:"",
13850:"",
13900:"",
13950:"",
14000:"ТО500",
14050:"",
14100:"",
14150:"",
14200:"",
14250:"ТО250",
14300:"",
14350:"",
14400:"",
14450:"",
14500:"ТО500",
14550:"",
14600:"",
14650:"",
14700:"",
14750:"ТО250",
14800:"",
14850:"",
14900:"",
14950:"",
15000:"ТО3000",
15050:"",
15100:"",
15150:"",
15200:"",
15250:"ТО250",
15300:"",
15350:"",
15400:"",
15450:"",
15500:"ТО500",
15550:"",
15600:"",
15650:"",
15700:"",
15750:"ТО250",
15800:"",
15850:"",
15900:"",
15950:"",
16000:"ТО500",
16050:"",
16100:"",
16150:"",
16200:"",
16250:"ТО250",
16300:"",
16350:"",
16400:"",
16450:"",
16500:"ТО1500",
16550:"",
16600:"",
16650:"",
16700:"",
16750:"ТО250",
16800:"",
16850:"",
16900:"",
16950:"",
17000:"ТО500",
17050:"",
17100:"",
17150:"",
17200:"",
17250:"ТО250",
17300:"",
17350:"",
17400:"",
17450:"",
17500:"ТО500",
17550:"",
17600:"",
17650:"",
17700:"",
17750:"ТО250",
17800:"",
17850:"",
17900:"",
17950:"",
18000:"ТО3000",
18050:"",
18100:"",
18150:"",
18200:"",
18250:"ТО250",
18300:"",
18350:"",
18400:"",
18450:"",
18500:"ТО500",
18550:"",
18600:"",
18650:"",
18700:"",
18750:"ТО250",
18800:"",
18850:"",
18900:"",
18950:"",
19000:"ТО500",
19050:"",
19100:"",
19150:"",
19200:"",
19250:"ТО250",
19300:"",
19350:"",
19400:"",
19450:"",
19500:"ТО1500",
19550:"",
19600:"",
19650:"",
19700:"",
19750:"ТО250",
19800:"",
19850:"",
19900:"",
19950:"",
20000:"ТО500",
20050:"",
20100:"",
20150:"",
20200:"",
20250:"ТО250",
20300:"",
20350:"",
20400:"",
20450:"",
20500:"ТО500",
20550:"",
20600:"",
20650:"",
20700:"",
20750:"ТО250",
20800:"",
20850:"",
20900:"",
20950:"",
21000:"ТО3000",
21050:"",
21100:"",
21150:"",
21200:"",
21250:"ТО250",
21300:"",
21350:"",
21400:"",
21450:"",
21500:"ТО500",
21550:"",
21600:"",
21650:"",
21700:"",
21750:"ТО250",
21800:"",
21850:"",
21900:"",
21950:"",
22000:"ТО500",
22050:"",
22100:"",
22150:"",
22200:"",
22250:"ТО250",
22300:"",
22350:"",
22400:"",
22450:"",
22500:"ТО1500",
22550:"",
22600:"",
22650:"",
22700:"",
22750:"ТО250",
22800:"",
22850:"",
22900:"",
22950:"",
23000:"ТО500",
23050:"",
23100:"",
23150:"",
23200:"",
23250:"ТО250",
23300:"",
23350:"",
23400:"",
23450:"",
23500:"ТО500",
23550:"",
23600:"",
23650:"",
23700:"",
23750:"ТО250",
23800:"",
23850:"",
23900:"",
23950:"",
24000:"ТО3000",
24050:"",
24100:"",
24150:"",
24200:"",
24250:"ТО250",
24300:"",
24350:"",
24400:"",
24450:"",
24500:"ТО500",
24550:"",
24600:"",
24650:"",
24700:"",
24750:"ТО250",
24800:"",
24850:"",
24900:"",
24950:"",
25000:"ТО500",
25050:"",
25100:"",
25150:"",
25200:"",
25250:"ТО250",
25300:"",
25350:"",
25400:"",
25450:"",
25500:"ТО1500",
25550:"",
25600:"",
25650:"",
25700:"",
25750:"ТО250",
25800:"",
25850:"",
25900:"",
25950:"",
26000:"ТО500",
26050:"",
26100:"",
26150:"",
26200:"",
26250:"ТО250",
26300:"",
26350:"",
26400:"",
26450:"",
26500:"ТО500",
26550:"",
26600:"",
26650:"",
26700:"",
26750:"ТО250",
26800:"",
26850:"",
26900:"",
26950:"",
27000:"ТО3000",
27050:"",
27100:"",
27150:"",
27200:"",
27250:"ТО250",
27300:"",
27350:"",
27400:"",
27450:"",
27500:"ТО500",
27550:"",
27600:"",
27650:"",
27700:"",
27750:"ТО250",
27800:"",
27850:"",
27900:"",
27950:"",
28000:"ТО500",
28050:"",
28100:"",
28150:"",
28200:"",
28250:"ТО250",
28300:"",
28350:"",
28400:"",
28450:"",
28500:"ТО1500",
28550:"",
28600:"",
28650:"",
28700:"",
28750:"ТО250",
28800:"",
28850:"",
28900:"",
28950:"",
29000:"ТО500",
29050:"",
29100:"",
29150:"",
29200:"",
29250:"ТО250",
29300:"",
29350:"",
29400:"",
29450:"",
29500:"ТО500",
29550:"",
29600:"",
29650:"",
29700:"",
29750:"ТО250",
29800:"",
29850:"",
29900:"",
29950:"",
30000:"ТО3000",
30050:"",
30100:"",
30150:"",
30200:"",
30250:"0",
30300:"",
30350:"",
30400:"",
30450:"",
30500:"0",
30550:"",
30600:"",
30650:"",
30700:"",
30750:"0",
30800:"",
30850:"",
30900:"",
30950:"",
31000:"0",
31050:"",
31100:"",
31150:"",
31200:"",
31250:"0",
31300:"",
31350:"",
31400:"",
31450:"",
31500:"ТО1500",
31550:"",
31600:"",
31650:"",
31700:"",
31750:"0",
31800:"",
31850:"",
31900:"",
31950:"",
32000:"0",
32050:"",
32100:"",
32150:"",
32200:"",
32250:"0",
32300:"",
32350:"",
32400:"",
32450:"",
32500:"0",
32550:"",
32600:"",
32650:"",
32700:"",
32750:"0",
32800:"",
32850:"",
32900:"",
32950:"",
33000:"ТО1500",
33050:"",
33100:"",
33150:"",
33200:"",
33250:"0",
33300:"",
33350:"",
33400:"",
33450:"",
33500:"0",
33550:"",
33600:"",
33650:"",
33700:"",
33750:"0",
33800:"",
33850:"",
33900:"",
33950:"",
34000:"0",
34050:"",
34100:"",
34150:"",
34200:"",
34250:"0",
34300:"",
34350:"",
34400:"",
34450:"",
34500:"ТО1500",
34550:"",
34600:"",
34650:"",
34700:"",
34750:"0",
34800:"",
34850:"",
34900:"",
34950:"",
35000:"0",
35050:"",
35100:"",
35150:"",
35200:"",
35250:"0",
35300:"",
35350:"",
35400:"",
35450:"",
35500:"0",
35550:"",
35600:"",
35650:"",
35700:"",
35750:"0",
35800:"",
35850:"",
35900:"",
35950:"",
36000:"ТО3000",
36050:"",
36100:"",
36150:"",
36200:"",
36250:"0",
36300:"",
36350:"",
36400:"",
36450:"",
36500:"0",
36550:"",
36600:"",
36650:"",
36700:"",
36750:"0",
36800:"",
36850:"",
36900:"",
36950:"",
37000:"0",
37050:"",
37100:"",
37150:"",
37200:"",
37250:"0",
37300:"",
37350:"",
37400:"",
37450:"",
37500:"ТО1500",
37550:"",
37600:"",
37650:"",
37700:"",
37750:"0",
37800:"",
37850:"",
37900:"",
37950:"",
38000:"0",
38050:"",
38100:"",
38150:"",
38200:"",
38250:"0",
38300:"",
38350:"",
38400:"",
38450:"",
38500:"0",
38550:"",
38600:"",
38650:"",
38700:"",
38750:"0",
38800:"",
38850:"",
38900:"",
38950:"",
39000:"ТО1500",
39050:"",
39100:"",
39150:"",
39200:"",
39250:"0",
39300:"",
39350:"",
39400:"",
39450:"",
39500:"0",
39550:"",
39600:"",
39650:"",
39700:"",
39750:"0",
39800:"",
39850:"",
39900:"",
39950:"",
40000:"0",
40050:"",
40100:"",
40150:"",
40200:"",
40250:"0",
40300:"",
40350:"",
40400:"",
40450:"",
40500:"ТО1500",
40550:"",
40600:"",
40650:"",
40700:"",
40750:"0",
40800:"",
40850:"",
40900:"",
40950:"",
41000:"0",
41050:"",
41100:"",
41150:"",
41200:"",
41250:"0",
41300:"",
41350:"",
41400:"",
41450:"",
41500:"0",
41550:"",
41600:"",
41650:"",
41700:"",
41750:"0",
41800:"",
41850:"",
41900:"",
41950:"",
42000:"ТО3000",
42050:"",
42100:"",
42150:"",
42200:"",
42250:"0",
42300:"",
42350:"",
42400:"",
42450:"",
42500:"0",
42550:"",
42600:"",
42650:"",
42700:"",
42750:"0",
42800:"",
42850:"",
42900:"",
42950:"",
43000:"0",
43050:"",
43100:"",
43150:"",
43200:"",
43250:"0",
43300:"",
43350:"",
43400:"",
43450:"",
43500:"ТО1500",
43550:"",
43600:"",
43650:"",
43700:"",
43750:"0",
43800:"",
43850:"",
43900:"",
43950:"",
44000:"0",
44050:"",
44100:"",
44150:"",
44200:"",
44250:"0",
44300:"",
44350:"",
44400:"",
44450:"",
44500:"0",
44550:"",
44600:"",
44650:"",
44700:"",
44750:"0",
44800:"",
44850:"",
44900:"",
44950:"",
45000:"ТО1500",
45050:"",
45100:"",
45150:"",
45200:"",
45250:"0",
45300:"",
45350:"",
45400:"",
45450:"",
45500:"0",
45550:"",
45600:"",
45650:"",
45700:"",
45750:"0",
45800:"",
45850:"",
45900:"",
45950:"",
46000:"0",
46050:"",
46100:"",
46150:"",
46200:"",
46250:"0",
46300:"",
46350:"",
46400:"",
46450:"",
46500:"ТО1500",
46550:"",
46600:"",
46650:"",
46700:"",
46750:"0",
46800:"",
46850:"",
46900:"",
46950:"",
47000:"0",
47050:"",
47100:"",
47150:"",
47200:"",
47250:"0",
47300:"",
47350:"",
47400:"",
47450:"",
47500:"0",
47550:"",
47600:"",
47650:"",
47700:"",
47750:"0",
47800:"",
47850:"",
47900:"",
47950:"",
48000:"ТО3000"
   
}

In [65]:
to_dict_DCA_ED200={
    50:"",
100:"",
150:"",
200:"",
250:"",
300:"",
350:"",
400:"",
450:"",
500:"ТО500",
550:"",
600:"",
650:"",
700:"",
750:"",
800:"",
850:"",
900:"",
950:"",
1000:"ТО1000",
1050:"",
1100:"",
1150:"",
1200:"",
1250:"",
1300:"",
1350:"",
1400:"",
1450:"",
1500:"ТО500",
1550:"",
1600:"",
1650:"",
1700:"",
1750:"",
1800:"",
1850:"",
1900:"",
1950:"",
2000:"ТО2000",
2050:"",
2100:"",
2150:"",
2200:"",
2250:"",
2300:"",
2350:"",
2400:"",
2450:"",
2500:"ТО500",
2550:"",
2600:"",
2650:"",
2700:"",
2750:"",
2800:"",
2850:"",
2900:"",
2950:"",
3000:"ТО1000",
3050:"",
3100:"",
3150:"",
3200:"",
3250:"",
3300:"",
3350:"",
3400:"",
3450:"",
3500:"ТО500",
3550:"",
3600:"",
3650:"",
3700:"",
3750:"",
3800:"",
3850:"",
3900:"",
3950:"",
4000:"ТО4000",
4050:"",
4100:"",
4150:"",
4200:"",
4250:"",
4300:"",
4350:"",
4400:"",
4450:"",
4500:"ТО500",
4550:"",
4600:"",
4650:"",
4700:"",
4750:"",
4800:"",
4850:"",
4900:"",
4950:"",
5000:"ТО1000",
5050:"",
5100:"",
5150:"",
5200:"",
5250:"",
5300:"",
5350:"",
5400:"",
5450:"",
5500:"ТО500",
5550:"",
5600:"",
5650:"",
5700:"",
5750:"",
5800:"",
5850:"",
5900:"",
5950:"",
6000:"ТО2000",
6050:"",
6100:"",
6150:"",
6200:"",
6250:"",
6300:"",
6350:"",
6400:"",
6450:"",
6500:"ТО500",
6550:"",
6600:"",
6650:"",
6700:"",
6750:"",
6800:"",
6850:"",
6900:"",
6950:"",
7000:"ТО1000",
7050:"",
7100:"",
7150:"",
7200:"",
7250:"",
7300:"",
7350:"",
7400:"",
7450:"",
7500:"ТО500",
7550:"",
7600:"",
7650:"",
7700:"",
7750:"",
7800:"",
7850:"",
7900:"",
7950:"",
8000:"ТО4000",
8050:"",
8100:"",
8150:"",
8200:"",
8250:"",
8300:"",
8350:"",
8400:"",
8450:"",
8500:"ТО500",
8550:"",
8600:"",
8650:"",
8700:"",
8750:"",
8800:"",
8850:"",
8900:"",
8950:"",
9000:"ТО1000",
9050:"",
9100:"",
9150:"",
9200:"",
9250:"",
9300:"",
9350:"",
9400:"",
9450:"",
9500:"ТО500",
9550:"",
9600:"",
9650:"",
9700:"",
9750:"",
9800:"",
9850:"",
9900:"",
9950:"",
10000:"ТО2000",
10050:"",
10100:"",
10150:"",
10200:"",
10250:"",
10300:"",
10350:"",
10400:"",
10450:"",
10500:"ТО500",
10550:"",
10600:"",
10650:"",
10700:"",
10750:"",
10800:"",
10850:"",
10900:"",
10950:"",
11000:"ТО1000",
11050:"",
11100:"",
11150:"",
11200:"",
11250:"",
11300:"",
11350:"",
11400:"",
11450:"",
11500:"ТО500",
11550:"",
11600:"",
11650:"",
11700:"",
11750:"",
11800:"",
11850:"",
11900:"",
11950:"",
12000:"ТО4000",
12050:"",
12100:"",
12150:"",
12200:"",
12250:"",
12300:"",
12350:"",
12400:"",
12450:"",
12500:"ТО500",
12550:"",
12600:"",
12650:"",
12700:"",
12750:"",
12800:"",
12850:"",
12900:"",
12950:"",
13000:"ТО1000",
13050:"",
13100:"",
13150:"",
13200:"",
13250:"",
13300:"",
13350:"",
13400:"",
13450:"",
13500:"ТО500",
13550:"",
13600:"",
13650:"",
13700:"",
13750:"",
13800:"",
13850:"",
13900:"",
13950:"",
14000:"ТО2000",
14050:"",
14100:"",
14150:"",
14200:"",
14250:"",
14300:"",
14350:"",
14400:"",
14450:"",
14500:"ТО500",
14550:"",
14600:"",
14650:"",
14700:"",
14750:"",
14800:"",
14850:"",
14900:"",
14950:"",
15000:"ТО1000",
15050:"",
15100:"",
15150:"",
15200:"",
15250:"",
15300:"",
15350:"",
15400:"",
15450:"",
15500:"ТО500",
15550:"",
15600:"",
15650:"",
15700:"",
15750:"",
15800:"",
15850:"",
15900:"",
15950:"",
16000:"ТО4000",
16050:"",
16100:"",
16150:"",
16200:"",
16250:"",
16300:"",
16350:"",
16400:"",
16450:"",
16500:"ТО500",
16550:"",
16600:"",
16650:"",
16700:"",
16750:"",
16800:"",
16850:"",
16900:"",
16950:"",
17000:"ТО1000",
17050:"",
17100:"",
17150:"",
17200:"",
17250:"",
17300:"",
17350:"",
17400:"",
17450:"",
17500:"ТО500",
17550:"",
17600:"",
17650:"",
17700:"",
17750:"",
17800:"",
17850:"",
17900:"",
17950:"",
18000:"ТО2000",
18050:"",
18100:"",
18150:"",
18200:"",
18250:"",
18300:"",
18350:"",
18400:"",
18450:"",
18500:"ТО500",
18550:"",
18600:"",
18650:"",
18700:"",
18750:"",
18800:"",
18850:"",
18900:"",
18950:"",
19000:"ТО1000",
19050:"",
19100:"",
19150:"",
19200:"",
19250:"",
19300:"",
19350:"",
19400:"",
19450:"",
19500:"ТО500",
19550:"",
19600:"",
19650:"",
19700:"",
19750:"",
19800:"",
19850:"",
19900:"",
19950:"",
20000:"ТО4000",
20050:"",
20100:"",
20150:"",
20200:"",
20250:"",
20300:"",
20350:"",
20400:"",
20450:"",
20500:"ТО500",
20550:"",
20600:"",
20650:"",
20700:"",
20750:"",
20800:"",
20850:"",
20900:"",
20950:"",
21000:"ТО1000",
21050:"",
21100:"",
21150:"",
21200:"",
21250:"",
21300:"",
21350:"",
21400:"",
21450:"",
21500:"ТО500",
21550:"",
21600:"",
21650:"",
21700:"",
21750:"",
21800:"",
21850:"",
21900:"",
21950:"",
22000:"ТО2000",
22050:"",
22100:"",
22150:"",
22200:"",
22250:"",
22300:"",
22350:"",
22400:"",
22450:"",
22500:"ТО500",
22550:"",
22600:"",
22650:"",
22700:"",
22750:"",
22800:"",
22850:"",
22900:"",
22950:"",
23000:"ТО1000",
23050:"",
23100:"",
23150:"",
23200:"",
23250:"",
23300:"",
23350:"",
23400:"",
23450:"",
23500:"ТО500",
23550:"",
23600:"",
23650:"",
23700:"",
23750:"",
23800:"",
23850:"",
23900:"",
23950:"",
24000:"ТО4000",
24050:"",
24100:"",
24150:"",
24200:"",
24250:"",
24300:"",
24350:"",
24400:"",
24450:"",
24500:"ТО500",
24550:"",
24600:"",
24650:"",
24700:"",
24750:"",
24800:"",
24850:"",
24900:"",
24950:"",
25000:"ТО1000",
25050:"",
25100:"",
25150:"",
25200:"",
25250:"",
25300:"",
25350:"",
25400:"",
25450:"",
25500:"ТО500",
25550:"",
25600:"",
25650:"",
25700:"",
25750:"",
25800:"",
25850:"",
25900:"",
25950:"",
26000:"ТО2000",
26050:"",
26100:"",
26150:"",
26200:"",
26250:"",
26300:"",
26350:"",
26400:"",
26450:"",
26500:"ТО500",
26550:"",
26600:"",
26650:"",
26700:"",
26750:"",
26800:"",
26850:"",
26900:"",
26950:"",
27000:"ТО1000",
27050:"",
27100:"",
27150:"",
27200:"",
27250:"",
27300:"",
27350:"",
27400:"",
27450:"",
27500:"ТО500",
27550:"",
27600:"",
27650:"",
27700:"",
27750:"",
27800:"",
27850:"",
27900:"",
27950:"",
28000:"ТО4000",
28050:"",
28100:"",
28150:"",
28200:"",
28250:"",
28300:"",
28350:"",
28400:"",
28450:"",
28500:"ТО500",
28550:"",
28600:"",
28650:"",
28700:"",
28750:"",
28800:"",
28850:"",
28900:"",
28950:"",
29000:"ТО1000",
29050:"",
29100:"",
29150:"",
29200:"",
29250:"",
29300:"",
29350:"",
29400:"",
29450:"",
29500:"ТО500",
29550:"",
29600:"",
29650:"",
29700:"",
29750:"",
29800:"",
29850:"",
29900:"",
29950:"",
30000:"ТО2000",
30050:"",
30100:"",
30150:"",
30200:"",
30250:"",
30300:"",
30350:"",
30400:"",
30450:"",
30500:"ТО500",
30550:"",
30600:"",
30650:"",
30700:"",
30750:"",
30800:"",
30850:"",
30900:"",
30950:"",
31000:"ТО1000",
31050:"",
31100:"",
31150:"",
31200:"",
31250:"",
31300:"",
31350:"",
31400:"",
31450:"",
31500:"ТО500",
31550:"",
31600:"",
31650:"",
31700:"",
31750:"",
31800:"",
31850:"",
31900:"",
31950:"",
32000:"ТО4000",
32050:"",
32100:"",
32150:"",
32200:"",
32250:"",
32300:"",
32350:"",
32400:"",
32450:"",
32500:"ТО500",
32550:"",
32600:"",
32650:"",
32700:"",
32750:"",
32800:"",
32850:"",
32900:"",
32950:"",
33000:"ТО1000",
33050:"",
33100:"",
33150:"",
33200:"",
33250:"",
33300:"",
33350:"",
33400:"",
33450:"",
33500:"ТО500",
33550:"",
33600:"",
33650:"",
33700:"",
33750:"",
33800:"",
33850:"",
33900:"",
33950:"",
34000:"ТО2000",
34050:"",
34100:"",
34150:"",
34200:"",
34250:"",
34300:"",
34350:"",
34400:"",
34450:"",
34500:"ТО500",
34550:"",
34600:"",
34650:"",
34700:"",
34750:"",
34800:"",
34850:"",
34900:"",
34950:"",
35000:"ТО1000",
35050:"",
35100:"",
35150:"",
35200:"",
35250:"",
35300:"",
35350:"",
35400:"",
35450:"",
35500:"ТО500",
35550:"",
35600:"",
35650:"",
35700:"",
35750:"",
35800:"",
35850:"",
35900:"",
35950:"",
36000:"ТО4000",
36050:"",
36100:"",
36150:"",
36200:"",
36250:"",
36300:"",
36350:"",
36400:"",
36450:"",
36500:"ТО500",
36550:"",
36600:"",
36650:"",
36700:"",
36750:"",
36800:"",
36850:"",
36900:"",
36950:"",
37000:"ТО1000",
37050:"",
37100:"",
37150:"",
37200:"",
37250:"",
37300:"",
37350:"",
37400:"",
37450:"",
37500:"ТО500",
37550:"",
37600:"",
37650:"",
37700:"",
37750:"",
37800:"",
37850:"",
37900:"",
37950:"",
38000:"ТО2000",
38050:"",
38100:"",
38150:"",
38200:"",
38250:"",
38300:"",
38350:"",
38400:"",
38450:"",
38500:"ТО500",
38550:"",
38600:"",
38650:"",
38700:"",
38750:"",
38800:"",
38850:"",
38900:"",
38950:"",
39000:"ТО1000",
39050:"",
39100:"",
39150:"",
39200:"",
39250:"",
39300:"",
39350:"",
39400:"",
39450:"",
39500:"ТО500",
39550:"",
39600:"",
39650:"",
39700:"",
39750:"",
39800:"",
39850:"",
39900:"",
39950:"",
40000:"ТО4000",
40050:"",
40100:"",
40150:"",
40200:"",
40250:"",
40300:"",
40350:"",
40400:"",
40450:"",
40500:"ТО500",
40550:"",
40600:"",
40650:"",
40700:"",
40750:"",
40800:"",
40850:"",
40900:"",
40950:"",
41000:"ТО1000",
41050:"",
41100:"",
41150:"",
41200:"",
41250:"",
41300:"",
41350:"",
41400:"",
41450:"",
41500:"ТО500",
41550:"",
41600:"",
41650:"",
41700:"",
41750:"",
41800:"",
41850:"",
41900:"",
41950:"",
42000:"ТО2000",
42050:"",
42100:"",
42150:"",
42200:"",
42250:"",
42300:"",
42350:"",
42400:"",
42450:"",
42500:"ТО500",
42550:"",
42600:"",
42650:"",
42700:"",
42750:"",
42800:"",
42850:"",
42900:"",
42950:"",
43000:"ТО1000",
43050:"",
43100:"",
43150:"",
43200:"",
43250:"",
43300:"",
43350:"",
43400:"",
43450:"",
43500:"ТО500",
43550:"",
43600:"",
43650:"",
43700:"",
43750:"",
43800:"",
43850:"",
43900:"",
43950:"",
44000:"ТО4000",
44050:"",
44100:"",
44150:"",
44200:"",
44250:"",
44300:"",
44350:"",
44400:"",
44450:"",
44500:"ТО500",
44550:"",
44600:"",
44650:"",
44700:"",
44750:"",
44800:"",
44850:"",
44900:"",
44950:"",
45000:"ТО1000",
45050:"",
45100:"",
45150:"",
45200:"",
45250:"",
45300:"",
45350:"",
45400:"",
45450:"",
45500:"ТО500",
45550:"",
45600:"",
45650:"",
45700:"",
45750:"",
45800:"",
45850:"",
45900:"",
45950:"",
46000:"ТО2000",
46050:"",
46100:"",
46150:"",
46200:"",
46250:"",
46300:"",
46350:"",
46400:"",
46450:"",
46500:"ТО500",
46550:"",
46600:"",
46650:"",
46700:"",
46750:"",
46800:"",
46850:"",
46900:"",
46950:"",
47000:"ТО1000",
47050:"",
47100:"",
47150:"",
47200:"",
47250:"",
47300:"",
47350:"",
47400:"",
47450:"",
47500:"ТО500",
47550:"",
47600:"",
47650:"",
47700:"",
47750:"",
47800:"",
47850:"",
47900:"",
47950:"",
48000:"ТО4000"
  
}

In [66]:
to_dict_D55={
50:"ТО50",
100:"ТО50",
150:"ТО50",
200:"ТО50",
250:"ТО250",
300:"ТО50",
350:"ТО50",
400:"ТО50",
450:"ТО50",
500:"ТО500",
550:"ТО50",
600:"ТО50",
650:"ТО50",
700:"ТО50",
750:"ТО250",
800:"ТО50",
850:"ТО50",
900:"ТО50",
950:"ТО50",
1000:"ТО1000",
1050:"ТО50",
1100:"ТО50",
1150:"ТО50",
1200:"ТО50",
1250:"ТО250",
1300:"ТО50",
1350:"ТО50",
1400:"ТО50",
1450:"ТО50",
1500:"ТО1500",
1550:"ТО50",
1600:"ТО50",
1650:"ТО50",
1700:"ТО50",
1750:"ТО250",
1800:"ТО50",
1850:"ТО50",
1900:"ТО50",
1950:"ТО50",
2000:"ТО2000",
2050:"ТО50",
2100:"ТО50",
2150:"ТО50",
2200:"ТО50",
2250:"ТО250",
2300:"ТО50",
2350:"ТО50",
2400:"ТО50",
2450:"ТО50",
2500:"ТО500",
2550:"ТО50",
2600:"ТО50",
2650:"ТО50",
2700:"ТО50",
2750:"ТО250",
2800:"ТО50",
2850:"ТО50",
2900:"ТО50",
2950:"ТО50",
3000:"ТО3000",
3050:"ТО50",
3100:"ТО50",
3150:"ТО50",
3200:"ТО50",
3250:"ТО250",
3300:"ТО50",
3350:"ТО50",
3400:"ТО50",
3450:"ТО50",
3500:"ТО500",
3550:"ТО50",
3600:"ТО50",
3650:"ТО50",
3700:"ТО50",
3750:"ТО250",
3800:"ТО50",
3850:"ТО50",
3900:"ТО50",
3950:"ТО50",
4000:"ТО1000",
4050:"ТО50",
4100:"ТО50",
4150:"ТО50",
4200:"ТО50",
4250:"ТО250",
4300:"ТО50",
4350:"ТО50",
4400:"ТО50",
4450:"ТО50",
4500:"ТО1500",
4550:"ТО50",
4600:"ТО50",
4650:"ТО50",
4700:"ТО50",
4750:"ТО250",
4800:"ТО50",
4850:"ТО50",
4900:"ТО50",
4950:"ТО50",
5000:"ТО5000",
5050:"ТО50",
5100:"ТО50",
5150:"ТО50",
5200:"ТО50",
5250:"ТО250",
5300:"ТО50",
5350:"ТО50",
5400:"ТО50",
5450:"ТО50",
5500:"ТО500",
5550:"ТО50",
5600:"ТО50",
5650:"ТО50",
5700:"ТО50",
5750:"ТО250",
5800:"ТО50",
5850:"ТО50",
5900:"ТО50",
5950:"ТО50",
6000:"ТО6000",
6050:"ТО50",
6100:"ТО50",
6150:"ТО50",
6200:"ТО50",
6250:"ТО250",
6300:"ТО50",
6350:"ТО50",
6400:"ТО50",
6450:"ТО50",
6500:"ТО500",
6550:"ТО50",
6600:"ТО50",
6650:"ТО50",
6700:"ТО50",
6750:"ТО250",
6800:"ТО50",
6850:"ТО50",
6900:"ТО50",
6950:"ТО50",
7000:"ТО1000",
7050:"ТО50",
7100:"ТО50",
7150:"ТО50",
7200:"ТО50",
7250:"ТО250",
7300:"ТО50",
7350:"ТО50",
7400:"ТО50",
7450:"ТО50",
7500:"ТО1500",
7550:"ТО50",
7600:"ТО50",
7650:"ТО50",
7700:"ТО50",
7750:"ТО250",
7800:"ТО50",
7850:"ТО50",
7900:"ТО50",
7950:"ТО50",
8000:"ТО8000",
8050:"ТО50",
8100:"ТО50",
8150:"ТО50",
8200:"ТО50",
8250:"ТО250",
8300:"ТО50",
8350:"ТО50",
8400:"ТО50",
8450:"ТО50",
8500:"ТО500",
8550:"ТО50",
8600:"ТО50",
8650:"ТО50",
8700:"ТО50",
8750:"ТО250",
8800:"ТО50",
8850:"ТО50",
8900:"ТО50",
8950:"ТО50",
9000:"ТО3000",
9050:"ТО50",
9100:"ТО50",
9150:"ТО50",
9200:"ТО50",
9250:"ТО250",
9300:"ТО50",
9350:"ТО50",
9400:"ТО50",
9450:"ТО50",
9500:"ТО500",
9550:"ТО50",
9600:"ТО50",
9650:"ТО50",
9700:"ТО50",
9750:"ТО250",
9800:"ТО50",
9850:"ТО50",
9900:"ТО50",
9950:"ТО50",
10000:"ТО5000",
10050:"ТО50",
10100:"ТО50",
10150:"ТО50",
10200:"ТО50",
10250:"ТО250",
10300:"ТО50",
10350:"ТО50",
10400:"ТО50",
10450:"ТО50",
10500:"ТО1500",
10550:"ТО50",
10600:"ТО50",
10650:"ТО50",
10700:"ТО50",
10750:"ТО250",
10800:"ТО50",
10850:"ТО50",
10900:"ТО50",
10950:"ТО50",
11000:"ТО1000",
11050:"ТО50",
11100:"ТО50",
11150:"ТО50",
11200:"ТО50",
11250:"ТО250",
11300:"ТО50",
11350:"ТО50",
11400:"ТО50",
11450:"ТО50",
11500:"ТО500",
11550:"ТО50",
11600:"ТО50",
11650:"ТО50",
11700:"ТО50",
11750:"ТО250",
11800:"ТО50",
11850:"ТО50",
11900:"ТО50",
11950:"ТО50",
12000:"ТО12000",
12050:"ТО50",
12100:"ТО50",
12150:"ТО50",
12200:"ТО50",
12250:"ТО250",
12300:"ТО50",
12350:"ТО50",
12400:"ТО50",
12450:"ТО50",
12500:"ТО500",
12550:"ТО50",
12600:"ТО50",
12650:"ТО50",
12700:"ТО50",
12750:"ТО250",
12800:"ТО50",
12850:"ТО50",
12900:"ТО50",
12950:"ТО50",
13000:"ТО1000",
13050:"ТО50",
13100:"ТО50",
13150:"ТО50",
13200:"ТО50",
13250:"ТО250",
13300:"ТО50",
13350:"ТО50",
13400:"ТО50",
13450:"ТО50",
13500:"ТО1500",
13550:"ТО50",
13600:"ТО50",
13650:"ТО50",
13700:"ТО50",
13750:"ТО250",
13800:"ТО50",
13850:"ТО50",
13900:"ТО50",
13950:"ТО50",
14000:"ТО1000",
14050:"ТО50",
14100:"ТО50",
14150:"ТО50",
14200:"ТО50",
14250:"ТО250",
14300:"ТО50",
14350:"ТО50",
14400:"ТО50",
14450:"ТО50",
14500:"ТО500",
14550:"ТО50",
14600:"ТО50",
14650:"ТО50",
14700:"ТО50",
14750:"ТО250",
14800:"ТО50",
14850:"ТО50",
14900:"ТО50",
14950:"ТО50",
15000:"ТО3000/ТО5000",
15050:"ТО50",
15100:"ТО50",
15150:"ТО50",
15200:"ТО50",
15250:"ТО250",
15300:"ТО50",
15350:"ТО50",
15400:"ТО50",
15450:"ТО50",
15500:"ТО500",
15550:"ТО50",
15600:"ТО50",
15650:"ТО50",
15700:"ТО50",
15750:"ТО250",
15800:"ТО50",
15850:"ТО50",
15900:"ТО50",
15950:"ТО50",
16000:"ТО8000",
16050:"ТО50",
16100:"ТО50",
16150:"ТО50",
16200:"ТО50",
16250:"ТО250",
16300:"ТО50",
16350:"ТО50",
16400:"ТО50",
16450:"ТО50",
16500:"ТО1500",
16550:"ТО50",
16600:"ТО50",
16650:"ТО50",
16700:"ТО50",
16750:"ТО250",
16800:"ТО50",
16850:"ТО50",
16900:"ТО50",
16950:"ТО50",
17000:"ТО1000",
17050:"ТО50",
17100:"ТО50",
17150:"ТО50",
17200:"ТО50",
17250:"ТО250",
17300:"ТО50",
17350:"ТО50",
17400:"ТО50",
17450:"ТО50",
17500:"ТО500",
17550:"ТО50",
17600:"ТО50",
17650:"ТО50",
17700:"ТО50",
17750:"ТО250",
17800:"ТО50",
17850:"ТО50",
17900:"ТО50",
17950:"ТО50",
18000:"ТО6000",
18050:"ТО50",
18100:"ТО50",
18150:"ТО50",
18200:"ТО50",
18250:"ТО250",
18300:"ТО50",
18350:"ТО50",
18400:"ТО50",
18450:"ТО50",
18500:"ТО500",
18550:"ТО50",
18600:"ТО50",
18650:"ТО50",
18700:"ТО50",
18750:"ТО250",
18800:"ТО50",
18850:"ТО50",
18900:"ТО50",
18950:"ТО50",
19000:"ТО1000",
19050:"ТО50",
19100:"ТО50",
19150:"ТО50",
19200:"ТО50",
19250:"ТО250",
19300:"ТО50",
19350:"ТО50",
19400:"ТО50",
19450:"ТО50",
19500:"ТО1500",
19550:"ТО50",
19600:"ТО50",
19650:"ТО50",
19700:"ТО50",
19750:"ТО250",
19800:"ТО50",
19850:"ТО50",
19900:"ТО50",
19950:"ТО50",
20000:"ТО5000",
20050:"ТО50",
20100:"ТО50",
20150:"ТО50",
20200:"ТО50",
20250:"ТО250",
20300:"ТО50",
20350:"ТО50",
20400:"ТО50",
20450:"ТО50",
20500:"ТО500",
20550:"ТО50",
20600:"ТО50",
20650:"ТО50",
20700:"ТО50",
20750:"ТО250",
20800:"ТО50",
20850:"ТО50",
20900:"ТО50",
20950:"ТО50",
21000:"ТО3000",
21050:"ТО50",
21100:"ТО50",
21150:"ТО50",
21200:"ТО50",
21250:"ТО250",
21300:"ТО50",
21350:"ТО50",
21400:"ТО50",
21450:"ТО50",
21500:"ТО500",
21550:"ТО50",
21600:"ТО50",
21650:"ТО50",
21700:"ТО50",
21750:"ТО250",
21800:"ТО50",
21850:"ТО50",
21900:"ТО50",
21950:"ТО50",
22000:"ТО1000",
22050:"ТО50",
22100:"ТО50",
22150:"ТО50",
22200:"ТО50",
22250:"ТО250",
22300:"ТО50",
22350:"ТО50",
22400:"ТО50",
22450:"ТО50",
22500:"ТО1500",
22550:"ТО50",
22600:"ТО50",
22650:"ТО50",
22700:"ТО50",
22750:"ТО250",
22800:"ТО50",
22850:"ТО50",
22900:"ТО50",
22950:"ТО50",
23000:"ТО1000",
23050:"ТО50",
23100:"ТО50",
23150:"ТО50",
23200:"ТО50",
23250:"ТО250",
23300:"ТО50",
23350:"ТО50",
23400:"ТО50",
23450:"ТО50",
23500:"ТО500",
23550:"ТО50",
23600:"ТО50",
23650:"ТО50",
23700:"ТО50",
23750:"ТО250",
23800:"ТО50",
23850:"ТО50",
23900:"ТО50",
23950:"ТО50",
24000:"ТО8000/12000",
24050:"ТО50",
24100:"ТО50",
24150:"ТО50",
24200:"ТО50",
24250:"ТО250",
24300:"ТО50",
24350:"ТО50",
24400:"ТО50",
24450:"ТО50",
24500:"ТО500",
24550:"ТО50",
24600:"ТО50",
24650:"ТО50",
24700:"ТО50",
24750:"ТО250",
24800:"ТО50",
24850:"ТО50",
24900:"ТО50",
24950:"ТО50",
25000:"ТО1000",
25050:"ТО50",
25100:"ТО50",
25150:"ТО50",
25200:"ТО50",
25250:"ТО250",
25300:"ТО50",
25350:"ТО50",
25400:"ТО50",
25450:"ТО50",
25500:"ТО1500",
25550:"ТО50",
25600:"ТО50",
25650:"ТО50",
25700:"ТО50",
25750:"ТО50",
25800:"ТО50",
25850:"ТО50",
25900:"ТО50",
25950:"ТО50",
26000:"ТО1000",
26050:"ТО50",
26100:"ТО50",
26150:"ТО50",
26200:"ТО50",
26250:"ТО250",
26300:"ТО50",
26350:"ТО50",
26400:"ТО50",
26450:"ТО50",
26500:"ТО500",
26550:"ТО50",
26600:"ТО50",
26650:"ТО50",
26700:"ТО50",
26750:"ТО250",
26800:"ТО50",
26850:"ТО50",
26900:"ТО50",
26950:"ТО50",
27000:"ТО3000",
27050:"ТО50",
27100:"ТО50",
27150:"ТО50",
27200:"ТО50",
27250:"ТО250",
27300:"ТО50",
27350:"ТО50",
27400:"ТО50",
27450:"ТО50",
27500:"ТО500",
27550:"ТО50",
27600:"ТО50",
27650:"ТО50",
27700:"ТО50",
27750:"ТО250",
27800:"ТО50",
27850:"ТО50",
27900:"ТО50",
27950:"ТО50",
28000:"ТО1000",
28050:"ТО50",
28100:"ТО50",
28150:"ТО50",
28200:"ТО50",
28250:"ТО250",
28300:"ТО50",
28350:"ТО50",
28400:"ТО50",
28450:"ТО50",
28500:"ТО1500",
28550:"ТО50",
28600:"ТО50",
28650:"ТО50",
28700:"ТО50",
28750:"ТО250",
28800:"ТО50",
28850:"ТО50",
28900:"ТО50",
28950:"ТО50",
29000:"ТО1000",
29050:"ТО50",
29100:"ТО50",
29150:"ТО50",
29200:"ТО50",
29250:"ТО250",
29300:"ТО50",
29350:"ТО50",
29400:"ТО50",
29450:"ТО50",
29500:"ТО500",
29550:"ТО50",
29600:"ТО50",
29650:"ТО50",
29700:"ТО50",
29750:"ТО250",
29800:"ТО50",
29850:"ТО50",
29900:"ТО50",
29950:"ТО50",
30000:"ТО5000/ТО6000",
30050:"ТО50",
30100:"ТО50",
30150:"ТО50",
30200:"ТО50",
30250:"ТО250",
30300:"ТО50",
30350:"ТО50",
30400:"ТО50",
30450:"ТО50",
30500:"ТО500",
30550:"ТО50",
30600:"ТО50",
30650:"ТО50",
30700:"ТО50",
30750:"ТО250",
30800:"ТО50",
30850:"ТО50",
30900:"ТО50",
30950:"ТО50",
31000:"ТО1000",
31050:"ТО50",
31100:"ТО50",
31150:"ТО50",
31200:"ТО50",
31250:"ТО250",
31300:"ТО50",
31350:"ТО50",
31400:"ТО50",
31450:"ТО50",
31500:"ТО1500",
31550:"ТО50",
31600:"ТО50",
31650:"ТО50",
31700:"ТО50",
31750:"ТО250",
31800:"ТО50",
31850:"ТО50",
31900:"ТО50",
31950:"ТО50",
32000:"ТО8000",
32050:"ТО50",
32100:"ТО50",
32150:"ТО50",
32200:"ТО50",
32250:"ТО250",
32300:"ТО50",
32350:"ТО50",
32400:"ТО50",
32450:"ТО50",
32500:"ТО500",
32550:"ТО50",
32600:"ТО50",
32650:"ТО50",
32700:"ТО50",
32750:"ТО250",
32800:"ТО50",
32850:"ТО50",
32900:"ТО50",
32950:"ТО50",
33000:"ТО3000",
33050:"ТО50",
33100:"ТО50",
33150:"ТО50",
33200:"ТО50",
33250:"ТО250",
33300:"ТО50",
33350:"ТО50",
33400:"ТО50",
33450:"ТО50",
33500:"ТО500",
33550:"ТО50",
33600:"ТО50",
33650:"ТО50",
33700:"ТО50",
33750:"ТО250",
33800:"ТО50",
33850:"ТО50",
33900:"ТО50",
33950:"ТО50",
34000:"ТО1000",
34050:"ТО50",
34100:"ТО50",
34150:"ТО50",
34200:"ТО50",
34250:"ТО250",
34300:"ТО50",
34350:"ТО50",
34400:"ТО50",
34450:"ТО50",
34500:"ТО1500",
34550:"ТО50",
34600:"ТО50",
34650:"ТО50",
34700:"ТО50",
34750:"ТО250",
34800:"ТО50",
34850:"ТО50",
34900:"ТО50",
34950:"ТО50",
35000:"ТО1000",
35050:"ТО50",
35100:"ТО50",
35150:"ТО50",
35200:"ТО50",
35250:"ТО250",
35300:"ТО50",
35350:"ТО50",
35400:"ТО50",
35450:"ТО50",
35500:"ТО500",
35550:"ТО50",
35600:"ТО50",
35650:"ТО50",
35700:"ТО50",
35750:"ТО250",
35800:"ТО50",
35850:"ТО50",
35900:"ТО50",
35950:"ТО50",
36000:"ТО12000",
36050:"ТО50",
36100:"ТО50",
36150:"ТО50",
36200:"ТО50",
36250:"ТО250",
36300:"ТО50",
36350:"ТО50",
36400:"ТО50",
36450:"ТО50",
36500:"ТО500",
36550:"ТО50",
36600:"ТО50",
36650:"ТО50",
36700:"ТО50",
36750:"ТО250",
36800:"ТО50",
36850:"ТО50",
36900:"ТО50",
36950:"ТО50",
37000:"ТО1000",
37050:"ТО50",
37100:"ТО50",
37150:"ТО50",
37200:"ТО50",
37250:"ТО250",
37300:"ТО50",
37350:"ТО50",
37400:"ТО50",
37450:"ТО50",
37500:"ТО1500",
37550:"ТО50",
37600:"ТО50",
37650:"ТО50",
37700:"ТО50",
37750:"ТО250",
37800:"ТО50",
37850:"ТО50",
37900:"ТО50",
37950:"ТО50",
38000:"ТО1000",
38050:"ТО50",
38100:"ТО50",
38150:"ТО50",
38200:"ТО50",
38250:"ТО250",
38300:"ТО50",
38350:"ТО50",
38400:"ТО50",
38450:"ТО50",
38500:"ТО500",
38550:"ТО50",
38600:"ТО50",
38650:"ТО50",
38700:"ТО50",
38750:"ТО250",
38800:"ТО50",
38850:"ТО50",
38900:"ТО50",
38950:"ТО50",
39000:"ТО3000",
39050:"ТО50",
39100:"ТО50",
39150:"ТО50",
39200:"ТО50",
39250:"ТО250",
39300:"ТО50",
39350:"ТО50",
39400:"ТО50",
39450:"ТО50",
39500:"ТО500",
39550:"ТО50",
39600:"ТО50",
39650:"ТО50",
39700:"ТО50",
39750:"ТО250",
39800:"ТО50",
39850:"ТО50",
39900:"ТО50",
39950:"ТО50",
40000:"ТО5000/8000",
40050:"ТО50",
40100:"ТО50",
40150:"ТО50",
40200:"ТО50",
40250:"ТО250",
40300:"ТО50",
40350:"ТО50",
40400:"ТО50",
40450:"ТО50",
40500:"ТО1500",
40550:"ТО50",
40600:"ТО50",
40650:"ТО50",
40700:"ТО50",
40750:"ТО250",
40800:"ТО50",
40850:"ТО50",
40900:"ТО50",
40950:"ТО50",
41000:"ТО1000",
41050:"ТО50",
41100:"ТО50",
41150:"ТО50",
41200:"ТО50",
41250:"ТО250",
41300:"ТО50",
41350:"ТО50",
41400:"ТО50",
41450:"ТО50",
41500:"ТО500",
41550:"ТО50",
41600:"ТО50",
41650:"ТО50",
41700:"ТО50",
41750:"ТО250",
41800:"ТО50",
41850:"ТО50",
41900:"ТО50",
41950:"ТО50",
42000:"ТО6000",
42050:"ТО50",
42100:"ТО50",
42150:"ТО50",
42200:"ТО50",
42250:"ТО250",
42300:"ТО50",
42350:"ТО50",
42400:"ТО50",
42450:"ТО50",
42500:"ТО500",
42550:"ТО50",
42600:"ТО50",
42650:"ТО50",
42700:"ТО50",
42750:"ТО250",
42800:"ТО50",
42850:"ТО50",
42900:"ТО50",
42950:"ТО50",
43000:"ТО1000",
43050:"ТО50",
43100:"ТО50",
43150:"ТО50",
43200:"ТО50",
43250:"ТО250",
43300:"ТО50",
43350:"ТО50",
43400:"ТО50",
43450:"ТО50",
43500:"ТО1500",
43550:"ТО50",
43600:"ТО50",
43650:"ТО50",
43700:"ТО50",
43750:"ТО250",
43800:"ТО50",
43850:"ТО50",
43900:"ТО50",
43950:"ТО50",
44000:"ТО1000",
44050:"ТО50",
44100:"ТО50",
44150:"ТО50",
44200:"ТО50",
44250:"ТО250",
44300:"ТО50",
44350:"ТО50",
44400:"ТО50",
44450:"ТО50",
44500:"ТО500",
44550:"ТО50",
44600:"ТО50",
44650:"ТО50",
44700:"ТО50",
44750:"ТО250",
44800:"ТО50",
44850:"ТО50",
44900:"ТО50",
44950:"ТО50",
45000:"ТО3000",
45050:"ТО50",
45100:"ТО50",
45150:"ТО50",
45200:"ТО50",
45250:"ТО250",
45300:"ТО50",
45350:"ТО50",
45400:"ТО50",
45450:"ТО50",
45500:"ТО500",
45550:"ТО50",
45600:"ТО50",
45650:"ТО50",
45700:"ТО50",
45750:"ТО250",
45800:"ТО50",
45850:"ТО50",
45900:"ТО50",
45950:"ТО50",
46000:"ТО1000",
46050:"ТО50",
46100:"ТО50",
46150:"ТО50",
46200:"ТО50",
46250:"ТО250",
46300:"ТО50",
46350:"ТО50",
46400:"ТО50",
46450:"ТО50",
46500:"ТО1500",
46550:"ТО50",
46600:"ТО50",
46650:"ТО50",
46700:"ТО50",
46750:"ТО250",
46800:"ТО50",
46850:"ТО50",
46900:"ТО50",
46950:"ТО50",
47000:"ТО1000",
47050:"ТО50",
47100:"ТО50",
47150:"ТО50",
47200:"ТО50",
47250:"ТО250",
47300:"ТО50",
47350:"ТО50",
47400:"ТО50",
47450:"ТО50",
47500:"ТО500",
47550:"ТО50",
47600:"ТО50",
47650:"ТО50",
47700:"ТО50",
47750:"ТО250",
47800:"ТО50",
47850:"ТО50",
47900:"ТО50",
47950:"ТО50",
48000:"ТО8000/12000"

}

In [67]:
to_dict_SD22={
    50:"",
100:"",
150:"",
200:"",
250:"ТО250",
300:"",
350:"",
400:"",
450:"",
500:"ТО500",
550:"",
600:"",
650:"",
700:"",
750:"ТО250",
800:"",
850:"",
900:"",
950:"",
1000:"ТО1000",
1050:"",
1100:"",
1150:"",
1200:"",
1250:"ТО250",
1300:"",
1350:"",
1400:"",
1450:"",
1500:"ТО500",
1550:"",
1600:"",
1650:"",
1700:"",
1750:"ТО250",
1800:"",
1850:"",
1900:"",
1950:"",
2000:"ТО2000",
2050:"",
2100:"",
2150:"",
2200:"",
2250:"ТО250",
2300:"",
2350:"",
2400:"",
2450:"",
2500:"ТО500",
2550:"",
2600:"",
2650:"",
2700:"",
2750:"ТО250",
2800:"",
2850:"",
2900:"",
2950:"",
3000:"ТО1000",
3050:"",
3100:"",
3150:"",
3200:"",
3250:"ТО250",
3300:"",
3350:"",
3400:"",
3450:"",
3500:"ТО500",
3550:"",
3600:"",
3650:"",
3700:"",
3750:"ТО250",
3800:"",
3850:"",
3900:"",
3950:"",
4000:"ТО4000",
4050:"",
4100:"",
4150:"",
4200:"",
4250:"ТО250",
4300:"",
4350:"",
4400:"",
4450:"",
4500:"ТО500",
4550:"",
4600:"",
4650:"",
4700:"",
4750:"ТО250",
4800:"",
4850:"",
4900:"",
4950:"",
5000:"ТО1000",
5050:"",
5100:"",
5150:"",
5200:"",
5250:"ТО250",
5300:"",
5350:"",
5400:"",
5450:"",
5500:"ТО500",
5550:"",
5600:"",
5650:"",
5700:"",
5750:"ТО250",
5800:"",
5850:"",
5900:"",
5950:"",
6000:"ТО2000",
6050:"",
6100:"",
6150:"",
6200:"",
6250:"ТО250",
6300:"",
6350:"",
6400:"",
6450:"",
6500:"ТО500",
6550:"",
6600:"",
6650:"",
6700:"",
6750:"ТО250",
6800:"",
6850:"",
6900:"",
6950:"",
7000:"ТО1000",
7050:"",
7100:"",
7150:"",
7200:"",
7250:"ТО250",
7300:"",
7350:"",
7400:"",
7450:"",
7500:"ТО500",
7550:"",
7600:"",
7650:"",
7700:"",
7750:"ТО250",
7800:"",
7850:"",
7900:"",
7950:"",
8000:"ТО4000",
8050:"",
8100:"",
8150:"",
8200:"",
8250:"ТО250",
8300:"",
8350:"",
8400:"",
8450:"",
8500:"ТО500",
8550:"",
8600:"",
8650:"",
8700:"",
8750:"ТО250",
8800:"",
8850:"",
8900:"",
8950:"",
9000:"ТО1000",
9050:"",
9100:"",
9150:"",
9200:"",
9250:"ТО250",
9300:"",
9350:"",
9400:"",
9450:"",
9500:"ТО500",
9550:"",
9600:"",
9650:"",
9700:"",
9750:"ТО250",
9800:"",
9850:"",
9900:"",
9950:"",
10000:"ТО2000",
10050:"",
10100:"",
10150:"",
10200:"",
10250:"ТО250",
10300:"",
10350:"",
10400:"",
10450:"",
10500:"ТО500",
10550:"",
10600:"",
10650:"",
10700:"",
10750:"ТО250",
10800:"",
10850:"",
10900:"",
10950:"",
11000:"ТО1000",
11050:"",
11100:"",
11150:"",
11200:"",
11250:"ТО250",
11300:"",
11350:"",
11400:"",
11450:"",
11500:"ТО500",
11550:"",
11600:"",
11650:"",
11700:"",
11750:"ТО250",
11800:"",
11850:"",
11900:"",
11950:"",
12000:"ТО4000",
12050:"",
12100:"",
12150:"",
12200:"",
12250:"ТО250",
12300:"",
12350:"",
12400:"",
12450:"",
12500:"ТО500",
12550:"",
12600:"",
12650:"",
12700:"",
12750:"ТО250",
12800:"",
12850:"",
12900:"",
12950:"",
13000:"ТО1000",
13050:"",
13100:"",
13150:"",
13200:"",
13250:"ТО250",
13300:"",
13350:"",
13400:"",
13450:"",
13500:"ТО500",
13550:"",
13600:"",
13650:"",
13700:"",
13750:"ТО250",
13800:"",
13850:"",
13900:"",
13950:"",
14000:"ТО2000",
14050:"",
14100:"",
14150:"",
14200:"",
14250:"ТО250",
14300:"",
14350:"",
14400:"",
14450:"",
14500:"ТО500",
14550:"",
14600:"",
14650:"",
14700:"",
14750:"ТО250",
14800:"",
14850:"",
14900:"",
14950:"",
15000:"ТО1000",
15050:"",
15100:"",
15150:"",
15200:"",
15250:"ТО250",
15300:"",
15350:"",
15400:"",
15450:"",
15500:"ТО500",
15550:"",
15600:"",
15650:"",
15700:"",
15750:"ТО250",
15800:"",
15850:"",
15900:"",
15950:"",
16000:"ТО4000",
16050:"",
16100:"",
16150:"",
16200:"",
16250:"ТО250",
16300:"",
16350:"",
16400:"",
16450:"",
16500:"ТО500",
16550:"",
16600:"",
16650:"",
16700:"",
16750:"ТО250",
16800:"",
16850:"",
16900:"",
16950:"",
17000:"ТО1000",
17050:"",
17100:"",
17150:"",
17200:"",
17250:"ТО250",
17300:"",
17350:"",
17400:"",
17450:"",
17500:"ТО500",
17550:"",
17600:"",
17650:"",
17700:"",
17750:"ТО250",
17800:"",
17850:"",
17900:"",
17950:"",
18000:"ТО2000",
18050:"",
18100:"",
18150:"",
18200:"",
18250:"ТО250",
18300:"",
18350:"",
18400:"",
18450:"",
18500:"ТО500",
18550:"",
18600:"",
18650:"",
18700:"",
18750:"ТО250",
18800:"",
18850:"",
18900:"",
18950:"",
19000:"ТО1000",
19050:"",
19100:"",
19150:"",
19200:"",
19250:"ТО250",
19300:"",
19350:"",
19400:"",
19450:"",
19500:"ТО500",
19550:"",
19600:"",
19650:"",
19700:"",
19750:"ТО250",
19800:"",
19850:"",
19900:"",
19950:"",
20000:"ТО4000",
20050:"",
20100:"",
20150:"",
20200:"",
20250:"ТО250",
20300:"",
20350:"",
20400:"",
20450:"",
20500:"ТО500",
20550:"",
20600:"",
20650:"",
20700:"",
20750:"ТО250",
20800:"",
20850:"",
20900:"",
20950:"",
21000:"ТО1000",
21050:"",
21100:"",
21150:"",
21200:"",
21250:"ТО250",
21300:"",
21350:"",
21400:"",
21450:"",
21500:"ТО500",
21550:"",
21600:"",
21650:"",
21700:"",
21750:"ТО250",
21800:"",
21850:"",
21900:"",
21950:"",
22000:"ТО2000",
22050:"",
22100:"",
22150:"",
22200:"",
22250:"ТО250",
22300:"",
22350:"",
22400:"",
22450:"",
22500:"ТО500",
22550:"",
22600:"",
22650:"",
22700:"",
22750:"ТО250",
22800:"",
22850:"",
22900:"",
22950:"",
23000:"ТО1000",
23050:"",
23100:"",
23150:"",
23200:"",
23250:"ТО250",
23300:"",
23350:"",
23400:"",
23450:"",
23500:"ТО500",
23550:"",
23600:"",
23650:"",
23700:"",
23750:"ТО250",
23800:"",
23850:"",
23900:"",
23950:"",
24000:"ТО4000",
24050:"",
24100:"",
24150:"",
24200:"",
24250:"ТО250",
24300:"",
24350:"",
24400:"",
24450:"",
24500:"ТО500",
24550:"",
24600:"",
24650:"",
24700:"",
24750:"ТО250",
24800:"",
24850:"",
24900:"",
24950:"",
25000:"ТО1000",
25050:"",
25100:"",
25150:"",
25200:"",
25250:"ТО250",
25300:"",
25350:"",
25400:"",
25450:"",
25500:"ТО500",
25550:"",
25600:"",
25650:"",
25700:"",
25750:"ТО250",
25800:"",
25850:"",
25900:"",
25950:"",
26000:"ТО2000",
26050:"",
26100:"",
26150:"",
26200:"",
26250:"ТО250",
26300:"",
26350:"",
26400:"",
26450:"",
26500:"ТО500",
26550:"",
26600:"",
26650:"",
26700:"",
26750:"ТО250",
26800:"",
26850:"",
26900:"",
26950:"",
27000:"ТО1000",
27050:"",
27100:"",
27150:"",
27200:"",
27250:"ТО250",
27300:"",
27350:"",
27400:"",
27450:"",
27500:"ТО500",
27550:"",
27600:"",
27650:"",
27700:"",
27750:"ТО250",
27800:"",
27850:"",
27900:"",
27950:"",
28000:"ТО4000",
28050:"",
28100:"",
28150:"",
28200:"",
28250:"ТО250",
28300:"",
28350:"",
28400:"",
28450:"",
28500:"ТО500",
28550:"",
28600:"",
28650:"",
28700:"",
28750:"ТО250",
28800:"",
28850:"",
28900:"",
28950:"",
29000:"ТО1000",
29050:"",
29100:"",
29150:"",
29200:"",
29250:"ТО250",
29300:"",
29350:"",
29400:"",
29450:"",
29500:"ТО500",
29550:"",
29600:"",
29650:"",
29700:"",
29750:"ТО250",
29800:"",
29850:"",
29900:"",
29950:"",
30000:"ТО2000",
30050:"",
30100:"",
30150:"",
30200:"",
30250:"ТО250",
30300:"",
30350:"",
30400:"",
30450:"",
30500:"ТО500",
30550:"",
30600:"",
30650:"",
30700:"",
30750:"ТО250",
30800:"",
30850:"",
30900:"",
30950:"",
31000:"ТО1000",
31050:"",
31100:"",
31150:"",
31200:"",
31250:"ТО250",
31300:"",
31350:"",
31400:"",
31450:"",
31500:"ТО500",
31550:"",
31600:"",
31650:"",
31700:"",
31750:"ТО250",
31800:"",
31850:"",
31900:"",
31950:"",
32000:"ТО4000",
32050:"",
32100:"",
32150:"",
32200:"",
32250:"ТО250",
32300:"",
32350:"",
32400:"",
32450:"",
32500:"ТО500",
32550:"",
32600:"",
32650:"",
32700:"",
32750:"ТО250",
32800:"",
32850:"",
32900:"",
32950:"",
33000:"ТО1000",
33050:"",
33100:"",
33150:"",
33200:"",
33250:"ТО250",
33300:"",
33350:"",
33400:"",
33450:"",
33500:"ТО500",
33550:"",
33600:"",
33650:"",
33700:"",
33750:"ТО250",
33800:"",
33850:"",
33900:"",
33950:"",
34000:"ТО2000",
34050:"",
34100:"",
34150:"",
34200:"",
34250:"ТО250",
34300:"",
34350:"",
34400:"",
34450:"",
34500:"ТО500",
34550:"",
34600:"",
34650:"",
34700:"",
34750:"ТО250",
34800:"",
34850:"",
34900:"",
34950:"",
35000:"ТО1000",
35050:"",
35100:"",
35150:"",
35200:"",
35250:"ТО250",
35300:"",
35350:"",
35400:"",
35450:"",
35500:"ТО500",
35550:"",
35600:"",
35650:"",
35700:"",
35750:"ТО250",
35800:"",
35850:"",
35900:"",
35950:"",
36000:"ТО4000",
36050:"",
36100:"",
36150:"",
36200:"",
36250:"ТО250",
36300:"",
36350:"",
36400:"",
36450:"",
36500:"ТО500",
36550:"",
36600:"",
36650:"",
36700:"",
36750:"ТО250",
36800:"",
36850:"",
36900:"",
36950:"",
37000:"ТО1000",
37050:"",
37100:"",
37150:"",
37200:"",
37250:"ТО250",
37300:"",
37350:"",
37400:"",
37450:"",
37500:"ТО500",
37550:"",
37600:"",
37650:"",
37700:"",
37750:"ТО250",
37800:"",
37850:"",
37900:"",
37950:"",
38000:"ТО2000",
38050:"",
38100:"",
38150:"",
38200:"",
38250:"ТО250",
38300:"",
38350:"",
38400:"",
38450:"",
38500:"ТО500",
38550:"",
38600:"",
38650:"",
38700:"",
38750:"ТО250",
38800:"",
38850:"",
38900:"",
38950:"",
39000:"ТО1000",
39050:"",
39100:"",
39150:"",
39200:"",
39250:"ТО250",
39300:"",
39350:"",
39400:"",
39450:"",
39500:"ТО500",
39550:"",
39600:"",
39650:"",
39700:"",
39750:"ТО250",
39800:"",
39850:"",
39900:"",
39950:"",
40000:"ТО4000",
40050:"",
40100:"",
40150:"",
40200:"",
40250:"ТО250",
40300:"",
40350:"",
40400:"",
40450:"",
40500:"ТО500",
40550:"",
40600:"",
40650:"",
40700:"",
40750:"ТО250",
40800:"",
40850:"",
40900:"",
40950:"",
41000:"ТО1000",
41050:"",
41100:"",
41150:"",
41200:"",
41250:"ТО250",
41300:"",
41350:"",
41400:"",
41450:"",
41500:"ТО500",
41550:"",
41600:"",
41650:"",
41700:"",
41750:"ТО250",
41800:"",
41850:"",
41900:"",
41950:"",
42000:"ТО2000",
42050:"",
42100:"",
42150:"",
42200:"",
42250:"ТО250",
42300:"",
42350:"",
42400:"",
42450:"",
42500:"ТО500",
42550:"",
42600:"",
42650:"",
42700:"",
42750:"ТО250",
42800:"",
42850:"",
42900:"",
42950:"",
43000:"ТО1000",
43050:"",
43100:"",
43150:"",
43200:"",
43250:"ТО250",
43300:"",
43350:"",
43400:"",
43450:"",
43500:"ТО500",
43550:"",
43600:"",
43650:"",
43700:"",
43750:"ТО250",
43800:"",
43850:"",
43900:"",
43950:"",
44000:"ТО4000",
44050:"",
44100:"",
44150:"",
44200:"",
44250:"ТО250",
44300:"",
44350:"",
44400:"",
44450:"",
44500:"ТО500",
44550:"",
44600:"",
44650:"",
44700:"",
44750:"ТО250",
44800:"",
44850:"",
44900:"",
44950:"",
45000:"ТО1000",
45050:"",
45100:"",
45150:"",
45200:"",
45250:"ТО250",
45300:"",
45350:"",
45400:"",
45450:"",
45500:"ТО500",
45550:"",
45600:"",
45650:"",
45700:"",
45750:"ТО250",
45800:"",
45850:"",
45900:"",
45950:"",
46000:"ТО2000",
46050:"",
46100:"",
46150:"",
46200:"",
46250:"ТО250",
46300:"",
46350:"",
46400:"",
46450:"",
46500:"ТО500",
46550:"",
46600:"",
46650:"",
46700:"",
46750:"ТО250",
46800:"",
46850:"",
46900:"",
46950:"",
47000:"ТО1000",
47050:"",
47100:"",
47150:"",
47200:"",
47250:"ТО250",
47300:"",
47350:"",
47400:"",
47450:"",
47500:"ТО500",
47550:"",
47600:"",
47650:"",
47700:"",
47750:"ТО250",
47800:"",
47850:"",
47900:"",
47950:"",
48000:"ТО4000"

    
}

In [68]:
to_dict_SG21A_3={
   50:"ТО50",
100:"ТО50",
150:"ТО50",
200:"ТО50",
250:"ТО250",
300:"ТО50",
350:"ТО50",
400:"ТО50",
450:"ТО50",
500:"ТО500",
550:"ТО50",
600:"ТО50",
650:"ТО50",
700:"ТО50",
750:"ТО250",
800:"ТО50",
850:"ТО50",
900:"ТО50",
950:"ТО50",
1000:"ТО1000",
1050:"ТО50",
1100:"ТО50",
1150:"ТО50",
1200:"ТО50",
1250:"ТО250",
1300:"ТО50",
1350:"ТО50",
1400:"ТО50",
1450:"ТО50",
1500:"ТО500",
1550:"ТО50",
1600:"ТО50",
1650:"ТО50",
1700:"ТО50",
1750:"ТО250",
1800:"ТО50",
1850:"ТО50",
1900:"ТО50",
1950:"ТО50",
2000:"ТО2000",
2050:"ТО50",
2100:"ТО50",
2150:"ТО50",
2200:"ТО50",
2250:"ТО250",
2300:"ТО50",
2350:"ТО50",
2400:"ТО50",
2450:"ТО50",
2500:"ТО500",
2550:"ТО50",
2600:"ТО50",
2650:"ТО50",
2700:"ТО50",
2750:"ТО250",
2800:"ТО50",
2850:"ТО50",
2900:"ТО50",
2950:"ТО50",
3000:"ТО3000",
3050:"ТО50",
3100:"ТО50",
3150:"ТО50",
3200:"ТО50",
3250:"ТО250",
3300:"ТО50",
3350:"ТО50",
3400:"ТО50",
3450:"ТО50",
3500:"ТО500",
3550:"ТО50",
3600:"ТО50",
3650:"ТО50",
3700:"ТО50",
3750:"ТО250",
3800:"ТО50",
3850:"ТО50",
3900:"ТО50",
3950:"ТО50",
4000:"ТО4000",
4050:"ТО50",
4100:"ТО50",
4150:"ТО50",
4200:"ТО50",
4250:"ТО250",
4300:"ТО50",
4350:"ТО50",
4400:"ТО50",
4450:"ТО50",
4500:"ТО500",
4550:"ТО50",
4600:"ТО50",
4650:"ТО50",
4700:"ТО50",
4750:"ТО250",
4800:"ТО50",
4850:"ТО50",
4900:"ТО50",
4950:"ТО50",
5000:"ТО1000",
5050:"ТО50",
5100:"ТО50",
5150:"ТО50",
5200:"ТО50",
5250:"ТО250",
5300:"ТО50",
5350:"ТО50",
5400:"ТО50",
5450:"ТО50",
5500:"ТО500",
5550:"ТО50",
5600:"ТО50",
5650:"ТО50",
5700:"ТО50",
5750:"ТО250",
5800:"ТО50",
5850:"ТО50",
5900:"ТО50",
5950:"ТО50",
6000:"ТО2000/3000",
6050:"ТО50",
6100:"ТО50",
6150:"ТО50",
6200:"ТО50",
6250:"ТО250",
6300:"ТО50",
6350:"ТО50",
6400:"ТО50",
6450:"ТО50",
6500:"ТО500",
6550:"ТО50",
6600:"ТО50",
6650:"ТО50",
6700:"ТО50",
6750:"ТО250",
6800:"ТО50",
6850:"ТО50",
6900:"ТО50",
6950:"ТО50",
7000:"ТО1000",
7050:"ТО50",
7100:"ТО50",
7150:"ТО50",
7200:"ТО50",
7250:"ТО250",
7300:"ТО50",
7350:"ТО50",
7400:"ТО50",
7450:"ТО50",
7500:"ТО500",
7550:"ТО50",
7600:"ТО50",
7650:"ТО50",
7700:"ТО50",
7750:"ТО250",
7800:"ТО50",
7850:"ТО50",
7900:"ТО50",
7950:"ТО50",
8000:"ТО4000",
8050:"ТО50",
8100:"ТО50",
8150:"ТО50",
8200:"ТО50",
8250:"ТО250",
8300:"ТО50",
8350:"ТО50",
8400:"ТО50",
8450:"ТО50",
8500:"ТО500",
8550:"ТО50",
8600:"ТО50",
8650:"ТО50",
8700:"ТО50",
8750:"ТО250",
8800:"ТО50",
8850:"ТО50",
8900:"ТО50",
8950:"ТО50",
9000:"ТО3000",
9050:"ТО50",
9100:"ТО50",
9150:"ТО50",
9200:"ТО50",
9250:"ТО250",
9300:"ТО50",
9350:"ТО50",
9400:"ТО50",
9450:"ТО50",
9500:"ТО500",
9550:"ТО50",
9600:"ТО50",
9650:"ТО50",
9700:"ТО50",
9750:"ТО250",
9800:"ТО50",
9850:"ТО50",
9900:"ТО50",
9950:"ТО50",
10000:"ТО2000",
10050:"ТО50",
10100:"ТО50",
10150:"ТО50",
10200:"ТО50",
10250:"ТО250",
10300:"ТО50",
10350:"ТО50",
10400:"ТО50",
10450:"ТО50",
10500:"ТО500",
10550:"ТО50",
10600:"ТО50",
10650:"ТО50",
10700:"ТО50",
10750:"ТО250",
10800:"ТО50",
10850:"ТО50",
10900:"ТО50",
10950:"ТО50",
11000:"ТО1000",
11050:"ТО50",
11100:"ТО50",
11150:"ТО50",
11200:"ТО50",
11250:"ТО250",
11300:"ТО50",
11350:"ТО50",
11400:"ТО50",
11450:"ТО50",
11500:"ТО500",
11550:"ТО50",
11600:"ТО50",
11650:"ТО50",
11700:"ТО50",
11750:"ТО250",
11800:"ТО50",
11850:"ТО50",
11900:"ТО50",
11950:"ТО50",
12000:"ТО3000/4000",
12050:"ТО50",
12100:"ТО50",
12150:"ТО50",
12200:"ТО50",
12250:"ТО250",
12300:"ТО50",
12350:"ТО50",
12400:"ТО50",
12450:"ТО50",
12500:"ТО500",
12550:"ТО50",
12600:"ТО50",
12650:"ТО50",
12700:"ТО50",
12750:"ТО250",
12800:"ТО50",
12850:"ТО50",
12900:"ТО50",
12950:"ТО50",
13000:"ТО1000",
13050:"ТО50",
13100:"ТО50",
13150:"ТО50",
13200:"ТО50",
13250:"ТО250",
13300:"ТО50",
13350:"ТО50",
13400:"ТО50",
13450:"ТО50",
13500:"ТО500",
13550:"ТО50",
13600:"ТО50",
13650:"ТО50",
13700:"ТО50",
13750:"ТО250",
13800:"ТО50",
13850:"ТО50",
13900:"ТО50",
13950:"ТО50",
14000:"ТО2000",
14050:"ТО50",
14100:"ТО50",
14150:"ТО50",
14200:"ТО50",
14250:"ТО250",
14300:"ТО50",
14350:"ТО50",
14400:"ТО50",
14450:"ТО50",
14500:"ТО500",
14550:"ТО50",
14600:"ТО50",
14650:"ТО50",
14700:"ТО50",
14750:"ТО250",
14800:"ТО50",
14850:"ТО50",
14900:"ТО50",
14950:"ТО50",
15000:"ТО3000",
15050:"ТО50",
15100:"ТО50",
15150:"ТО50",
15200:"ТО50",
15250:"ТО250",
15300:"ТО50",
15350:"ТО50",
15400:"ТО50",
15450:"ТО50",
15500:"ТО500",
15550:"ТО50",
15600:"ТО50",
15650:"ТО50",
15700:"ТО50",
15750:"ТО250",
15800:"ТО50",
15850:"ТО50",
15900:"ТО50",
15950:"ТО50",
16000:"ТО4000",
16050:"ТО50",
16100:"ТО50",
16150:"ТО50",
16200:"ТО50",
16250:"ТО250",
16300:"ТО50",
16350:"ТО50",
16400:"ТО50",
16450:"ТО50",
16500:"ТО500",
16550:"ТО50",
16600:"ТО50",
16650:"ТО50",
16700:"ТО50",
16750:"ТО250",
16800:"ТО50",
16850:"ТО50",
16900:"ТО50",
16950:"ТО50",
17000:"ТО1000",
17050:"ТО50",
17100:"ТО50",
17150:"ТО50",
17200:"ТО50",
17250:"ТО250",
17300:"ТО50",
17350:"ТО50",
17400:"ТО50",
17450:"ТО50",
17500:"ТО500",
17550:"ТО50",
17600:"ТО50",
17650:"ТО50",
17700:"ТО50",
17750:"ТО250",
17800:"ТО50",
17850:"ТО50",
17900:"ТО50",
17950:"ТО50",
18000:"ТО2000/3000",
18050:"ТО50",
18100:"ТО50",
18150:"ТО50",
18200:"ТО50",
18250:"ТО250",
18300:"ТО50",
18350:"ТО50",
18400:"ТО50",
18450:"ТО50",
18500:"ТО500",
18550:"ТО50",
18600:"ТО50",
18650:"ТО50",
18700:"ТО50",
18750:"ТО250",
18800:"ТО50",
18850:"ТО50",
18900:"ТО50",
18950:"ТО50",
19000:"ТО1000",
19050:"ТО50",
19100:"ТО50",
19150:"ТО50",
19200:"ТО50",
19250:"ТО250",
19300:"ТО50",
19350:"ТО50",
19400:"ТО50",
19450:"ТО50",
19500:"ТО500",
19550:"ТО50",
19600:"ТО50",
19650:"ТО50",
19700:"ТО50",
19750:"ТО250",
19800:"ТО50",
19850:"ТО50",
19900:"ТО50",
19950:"ТО50",
20000:"ТО4000",
20050:"ТО50",
20100:"ТО50",
20150:"ТО50",
20200:"ТО50",
20250:"ТО250",
20300:"ТО50",
20350:"ТО50",
20400:"ТО50",
20450:"ТО50",
20500:"ТО500",
20550:"ТО50",
20600:"ТО50",
20650:"ТО50",
20700:"ТО50",
20750:"ТО250",
20800:"ТО50",
20850:"ТО50",
20900:"ТО50",
20950:"ТО50",
21000:"ТО3000",
21050:"ТО50",
21100:"ТО50",
21150:"ТО50",
21200:"ТО50",
21250:"ТО250",
21300:"ТО50",
21350:"ТО50",
21400:"ТО50",
21450:"ТО50",
21500:"ТО500",
21550:"ТО50",
21600:"ТО50",
21650:"ТО50",
21700:"ТО50",
21750:"ТО250",
21800:"ТО50",
21850:"ТО50",
21900:"ТО50",
21950:"ТО50",
22000:"ТО2000",
22050:"ТО50",
22100:"ТО50",
22150:"ТО50",
22200:"ТО50",
22250:"ТО250",
22300:"ТО50",
22350:"ТО50",
22400:"ТО50",
22450:"ТО50",
22500:"ТО500",
22550:"ТО50",
22600:"ТО50",
22650:"ТО50",
22700:"ТО50",
22750:"ТО250",
22800:"ТО50",
22850:"ТО50",
22900:"ТО50",
22950:"ТО50",
23000:"ТО1000",
23050:"ТО50",
23100:"ТО50",
23150:"ТО50",
23200:"ТО50",
23250:"ТО250",
23300:"ТО50",
23350:"ТО50",
23400:"ТО50",
23450:"ТО50",
23500:"ТО500",
23550:"ТО50",
23600:"ТО50",
23650:"ТО50",
23700:"ТО50",
23750:"ТО250",
23800:"ТО50",
23850:"ТО50",
23900:"ТО50",
23950:"ТО50",
24000:"ТО3000/4000",
24050:"ТО50",
24100:"ТО50",
24150:"ТО50",
24200:"ТО50",
24250:"ТО250",
24300:"ТО50",
24350:"ТО50",
24400:"ТО50",
24450:"ТО50",
24500:"ТО500",
24550:"ТО50",
24600:"ТО50",
24650:"ТО50",
24700:"ТО50",
24750:"ТО250",
24800:"ТО50",
24850:"ТО50",
24900:"ТО50",
24950:"ТО50",
25000:"ТО1000",
25050:"ТО50",
25100:"ТО50",
25150:"ТО50",
25200:"ТО50",
25250:"ТО250",
25300:"ТО50",
25350:"ТО50",
25400:"ТО50",
25450:"ТО50",
25500:"ТО500",
25550:"ТО50",
25600:"ТО50",
25650:"ТО50",
25700:"ТО50",
25750:"ТО250",
25800:"ТО50",
25850:"ТО50",
25900:"ТО50",
25950:"ТО50",
26000:"ТО2000",
26050:"ТО50",
26100:"ТО50",
26150:"ТО50",
26200:"ТО50",
26250:"ТО250",
26300:"ТО50",
26350:"ТО50",
26400:"ТО50",
26450:"ТО50",
26500:"ТО500",
26550:"ТО50",
26600:"ТО50",
26650:"ТО50",
26700:"ТО50",
26750:"ТО250",
26800:"ТО50",
26850:"ТО50",
26900:"ТО50",
26950:"ТО50",
27000:"ТО3000",
27050:"ТО50",
27100:"ТО50",
27150:"ТО50",
27200:"ТО50",
27250:"ТО250",
27300:"ТО50",
27350:"ТО50",
27400:"ТО50",
27450:"ТО50",
27500:"ТО500",
27550:"ТО50",
27600:"ТО50",
27650:"ТО50",
27700:"ТО50",
27750:"ТО250",
27800:"ТО50",
27850:"ТО50",
27900:"ТО50",
27950:"ТО50",
28000:"ТО4000",
28050:"ТО50",
28100:"ТО50",
28150:"ТО50",
28200:"ТО50",
28250:"ТО250",
28300:"ТО50",
28350:"ТО50",
28400:"ТО50",
28450:"ТО50",
28500:"ТО500",
28550:"ТО50",
28600:"ТО50",
28650:"ТО50",
28700:"ТО50",
28750:"ТО250",
28800:"ТО50",
28850:"ТО50",
28900:"ТО50",
28950:"ТО50",
29000:"ТО500",
29050:"ТО50",
29100:"ТО50",
29150:"ТО50",
29200:"ТО50",
29250:"ТО250",
29300:"ТО50",
29350:"ТО50",
29400:"ТО50",
29450:"ТО50",
29500:"ТО500",
29550:"ТО50",
29600:"ТО50",
29650:"ТО50",
29700:"ТО50",
29750:"ТО250",
29800:"ТО50",
29850:"ТО50",
29900:"ТО50",
29950:"ТО50",
30000:"ТО2000/3000",
30050:"ТО50",
30100:"ТО50",
30150:"ТО50",
30200:"ТО50",
30250:"ТО250",
30300:"ТО50",
30350:"ТО50",
30400:"ТО50",
30450:"ТО50",
30500:"ТО500",
30550:"ТО50",
30600:"ТО50",
30650:"ТО50",
30700:"ТО50",
30750:"ТО250",
30800:"ТО50",
30850:"ТО50",
30900:"ТО50",
30950:"ТО50",
31000:"ТО1000",
31050:"ТО50",
31100:"ТО50",
31150:"ТО50",
31200:"ТО50",
31250:"ТО250",
31300:"ТО50",
31350:"ТО50",
31400:"ТО50",
31450:"ТО50",
31500:"ТО500",
31550:"ТО50",
31600:"ТО50",
31650:"ТО50",
31700:"ТО50",
31750:"ТО250",
31800:"ТО50",
31850:"ТО50",
31900:"ТО50",
31950:"ТО50",
32000:"ТО4000",
32050:"ТО50",
32100:"ТО50",
32150:"ТО50",
32200:"ТО50",
32250:"ТО250",
32300:"ТО50",
32350:"ТО50",
32400:"ТО50",
32450:"ТО50",
32500:"ТО500",
32550:"ТО50",
32600:"ТО50",
32650:"ТО50",
32700:"ТО50",
32750:"ТО250",
32800:"ТО50",
32850:"ТО50",
32900:"ТО50",
32950:"ТО50",
33000:"ТО3000",
33050:"ТО50",
33100:"ТО50",
33150:"ТО50",
33200:"ТО50",
33250:"ТО250",
33300:"ТО50",
33350:"ТО50",
33400:"ТО50",
33450:"ТО50",
33500:"ТО500",
33550:"ТО50",
33600:"ТО50",
33650:"ТО50",
33700:"ТО50",
33750:"ТО250",
33800:"ТО50",
33850:"ТО50",
33900:"ТО50",
33950:"ТО50",
34000:"ТО2000",
34050:"ТО50",
34100:"ТО50",
34150:"ТО50",
34200:"ТО50",
34250:"ТО250",
34300:"ТО50",
34350:"ТО50",
34400:"ТО50",
34450:"ТО50",
34500:"ТО500",
34550:"ТО50",
34600:"ТО50",
34650:"ТО50",
34700:"ТО50",
34750:"ТО250",
34800:"ТО50",
34850:"ТО50",
34900:"ТО50",
34950:"ТО50",
35000:"ТО1000",
35050:"ТО50",
35100:"ТО50",
35150:"ТО50",
35200:"ТО50",
35250:"ТО250",
35300:"ТО50",
35350:"ТО50",
35400:"ТО50",
35450:"ТО50",
35500:"ТО500",
35550:"ТО50",
35600:"ТО50",
35650:"ТО50",
35700:"ТО50",
35750:"ТО250",
35800:"ТО50",
35850:"ТО50",
35900:"ТО50",
35950:"ТО50",
36000:"ТО3000/4000",
36050:"ТО50",
36100:"ТО50",
36150:"ТО50",
36200:"ТО50",
36250:"ТО250",
36300:"ТО50",
36350:"ТО50",
36400:"ТО50",
36450:"ТО50",
36500:"ТО500",
36550:"ТО50",
36600:"ТО50",
36650:"ТО50",
36700:"ТО50",
36750:"ТО250",
36800:"ТО50",
36850:"ТО50",
36900:"ТО50",
36950:"ТО50",
37000:"ТО1000",
37050:"ТО50",
37100:"ТО50",
37150:"ТО50",
37200:"ТО50",
37250:"ТО250",
37300:"ТО50",
37350:"ТО50",
37400:"ТО50",
37450:"ТО50",
37500:"ТО500",
37550:"ТО50",
37600:"ТО50",
37650:"ТО50",
37700:"ТО50",
37750:"ТО250",
37800:"ТО50",
37850:"ТО50",
37900:"ТО50",
37950:"ТО50",
38000:"ТО2000",
38050:"ТО50",
38100:"ТО50",
38150:"ТО50",
38200:"ТО50",
38250:"ТО250",
38300:"ТО50",
38350:"ТО50",
38400:"ТО50",
38450:"ТО50",
38500:"ТО500",
38550:"ТО50",
38600:"ТО50",
38650:"ТО50",
38700:"ТО50",
38750:"ТО250",
38800:"ТО50",
38850:"ТО50",
38900:"ТО50",
38950:"ТО50",
39000:"ТО3000",
39050:"ТО50",
39100:"ТО50",
39150:"ТО50",
39200:"ТО50",
39250:"ТО250",
39300:"ТО50",
39350:"ТО50",
39400:"ТО50",
39450:"ТО50",
39500:"ТО500",
39550:"ТО50",
39600:"ТО50",
39650:"ТО50",
39700:"ТО50",
39750:"ТО250",
39800:"ТО50",
39850:"ТО50",
39900:"ТО50",
39950:"ТО50",
40000:"ТО4000",
40050:"ТО50",
40100:"ТО50",
40150:"ТО50",
40200:"ТО50",
40250:"ТО250",
40300:"ТО50",
40350:"ТО50",
40400:"ТО50",
40450:"ТО50",
40500:"ТО500",
40550:"ТО50",
40600:"ТО50",
40650:"ТО50",
40700:"ТО50",
40750:"ТО250",
40800:"ТО50",
40850:"ТО50",
40900:"ТО50",
40950:"ТО50",
41000:"ТО1000",
41050:"ТО50",
41100:"ТО50",
41150:"ТО50",
41200:"ТО50",
41250:"ТО250",
41300:"ТО50",
41350:"ТО50",
41400:"ТО50",
41450:"ТО50",
41500:"ТО500",
41550:"ТО50",
41600:"ТО50",
41650:"ТО50",
41700:"ТО50",
41750:"ТО250",
41800:"ТО50",
41850:"ТО50",
41900:"ТО50",
41950:"ТО50",
42000:"ТО2000/3000",
42050:"ТО50",
42100:"ТО50",
42150:"ТО50",
42200:"ТО50",
42250:"ТО250",
42300:"ТО50",
42350:"ТО50",
42400:"ТО50",
42450:"ТО50",
42500:"ТО500",
42550:"ТО50",
42600:"ТО50",
42650:"ТО50",
42700:"ТО50",
42750:"ТО250",
42800:"ТО50",
42850:"ТО50",
42900:"ТО50",
42950:"ТО50",
43000:"ТО1000",
43050:"ТО50",
43100:"ТО50",
43150:"ТО50",
43200:"ТО50",
43250:"ТО250",
43300:"ТО50",
43350:"ТО50",
43400:"ТО50",
43450:"ТО50",
43500:"ТО500",
43550:"ТО50",
43600:"ТО50",
43650:"ТО50",
43700:"ТО50",
43750:"ТО250",
43800:"ТО50",
43850:"ТО50",
43900:"ТО50",
43950:"ТО50",
44000:"ТО4000",
44050:"ТО50",
44100:"ТО50",
44150:"ТО50",
44200:"ТО50",
44250:"ТО250",
44300:"ТО50",
44350:"ТО50",
44400:"ТО50",
44450:"ТО50",
44500:"ТО500",
44550:"ТО50",
44600:"ТО50",
44650:"ТО50",
44700:"ТО50",
44750:"ТО250",
44800:"ТО50",
44850:"ТО50",
44900:"ТО50",
44950:"ТО50",
45000:"ТО3000",
45050:"ТО50",
45100:"ТО50",
45150:"ТО50",
45200:"ТО50",
45250:"ТО250",
45300:"ТО50",
45350:"ТО50",
45400:"ТО50",
45450:"ТО50",
45500:"ТО500",
45550:"ТО50",
45600:"ТО50",
45650:"ТО50",
45700:"ТО50",
45750:"ТО250",
45800:"ТО50",
45850:"ТО50",
45900:"ТО50",
45950:"ТО50",
46000:"ТО2000",
46050:"ТО50",
46100:"ТО50",
46150:"ТО50",
46200:"ТО50",
46250:"ТО250",
46300:"ТО50",
46350:"ТО50",
46400:"ТО50",
46450:"ТО50",
46500:"ТО500",
46550:"ТО50",
46600:"ТО50",
46650:"ТО50",
46700:"ТО50",
46750:"ТО250",
46800:"ТО50",
46850:"ТО50",
46900:"ТО50",
46950:"ТО50",
47000:"ТО1000",
47050:"ТО50",
47100:"ТО50",
47150:"ТО50",
47200:"ТО50",
47250:"ТО250",
47300:"ТО50",
47350:"ТО50",
47400:"ТО50",
47450:"ТО50",
47500:"ТО500",
47550:"ТО50",
47600:"ТО50",
47650:"ТО50",
47700:"ТО50",
47750:"ТО250",
47800:"ТО50",
47850:"ТО50",
47900:"ТО50",
47950:"ТО50",
48000:"ТО3000/4000"

    
}

In [69]:
to_CLG975F={
   50:"",
100:"",
150:"",
200:" ",
250:" ",
300:" ",
350:" ",
400:" ",
450:" ",
500:"ТО500",
550:" ",
600:" ",
650:" ",
700:" ",
750:" ",
800:" ",
850:" ",
900:" ",
950:" ",
1000:"ТО1000",
1050:" ",
1100:" ",
1150:" ",
1200:" ",
1250:" ",
1300:" ",
1350:" ",
1400:" ",
1450:" ",
1500:"ТО500",
1550:" ",
1600:" ",
1650:" ",
1700:" ",
1750:" ",
1800:" ",
1850:" ",
1900:" ",
1950:" ",
2000:"ТО2000",
2050:" ",
2100:" ",
2150:" ",
2200:" ",
2250:" ",
2300:" ",
2350:" ",
2400:" ",
2450:" ",
2500:"ТО500",
2550:" ",
2600:" ",
2650:" ",
2700:" ",
2750:" ",
2800:" ",
2850:" ",
2900:" ",
2950:" ",
3000:"ТО3000",
3050:" ",
3100:" ",
3150:" ",
3200:" ",
3250:" ",
3300:" ",
3350:" ",
3400:" ",
3450:" ",
3500:"ТО500",
3550:" ",
3600:" ",
3650:" ",
3700:" ",
3750:" ",
3800:" ",
3850:" ",
3900:" ",
3950:" ",
4000:"ТО4000",
4050:" ",
4100:" ",
4150:" ",
4200:" ",
4250:" ",
4300:" ",
4350:" ",
4400:" ",
4450:" ",
4500:"ТО500",
4550:" ",
4600:" ",
4650:" ",
4700:" ",
4750:" ",
4800:" ",
4850:" ",
4900:" ",
4950:" ",
5000:"ТО5000",
5050:" ",
5100:" ",
5150:" ",
5200:" ",
5250:" ",
5300:" ",
5350:" ",
5400:" ",
5450:" ",
5500:"ТО500",
5550:" ",
5600:" ",
5650:" ",
5700:" ",
5750:" ",
5800:" ",
5850:" ",
5900:" ",
5950:" ",
6000:"ТО2000",
6050:" ",
6100:" ",
6150:" ",
6200:" ",
6250:" ",
6300:" ",
6350:" ",
6400:" ",
6450:" ",
6500:"ТО500",
6550:" ",
6600:" ",
6650:" ",
6700:" ",
6750:" ",
6800:" ",
6850:" ",
6900:" ",
6950:" ",
7000:"ТО1000",
7050:" ",
7100:" ",
7150:" ",
7200:" ",
7250:" ",
7300:" ",
7350:" ",
7400:" ",
7450:" ",
7500:"ТО500",
7550:" ",
7600:" ",
7650:" ",
7700:" ",
7750:" ",
7800:" ",
7850:" ",
7900:" ",
7950:" ",
8000:"ТО4000",
8050:" ",
8100:" ",
8150:" ",
8200:" ",
8250:" ",
8300:" ",
8350:" ",
8400:" ",
8450:" ",
8500:"ТО500",
8550:" ",
8600:" ",
8650:" ",
8700:" ",
8750:" ",
8800:" ",
8850:" ",
8900:" ",
8950:" ",
9000:"ТО3000",
9050:" ",
9100:" ",
9150:" ",
9200:" ",
9250:" ",
9300:" ",
9350:" ",
9400:" ",
9450:" ",
9500:"ТО500",
9550:" ",
9600:" ",
9650:" ",
9700:" ",
9750:" ",
9800:" ",
9850:" ",
9900:" ",
9950:" ",
10000:"ТО2000/ТО5000",
10050:" ",
10100:" ",
10150:" ",
10200:" ",
10250:" ",
10300:" ",
10350:" ",
10400:" ",
10450:" ",
10500:"ТО500",
10550:" ",
10600:" ",
10650:" ",
10700:" ",
10750:" ",
10800:" ",
10850:" ",
10900:" ",
10950:" ",
11000:"ТО1000",
11050:" ",
11100:" ",
11150:" ",
11200:" ",
11250:" ",
11300:" ",
11350:" ",
11400:" ",
11450:" ",
11500:"ТО500",
11550:" ",
11600:" ",
11650:" ",
11700:" ",
11750:" ",
11800:" ",
11850:" ",
11900:" ",
11950:" ",
12000:"ТО4000",
12050:" ",
12100:" ",
12150:" ",
12200:" ",
12250:" ",
12300:" ",
12350:" ",
12400:" ",
12450:" ",
12500:"ТО500",
12550:" ",
12600:" ",
12650:" ",
12700:" ",
12750:" ",
12800:" ",
12850:" ",
12900:" ",
12950:" ",
13000:"ТО1000",
13050:" ",
13100:" ",
13150:" ",
13200:" ",
13250:" ",
13300:" ",
13350:" ",
13400:" ",
13450:" ",
13500:"ТО500",
13550:" ",
13600:" ",
13650:" ",
13700:" ",
13750:" ",
13800:" ",
13850:" ",
13900:" ",
13950:" ",
14000:"ТО2000",
14050:" ",
14100:" ",
14150:" ",
14200:" ",
14250:" ",
14300:" ",
14350:" ",
14400:" ",
14450:" ",
14500:"ТО500",
14550:" ",
14600:" ",
14650:" ",
14700:" ",
14750:" ",
14800:" ",
14850:" ",
14900:" ",
14950:" ",
15000:"ТО3000/ТО5000",
15050:" ",
15100:" ",
15150:" ",
15200:" ",
15250:" ",
15300:" ",
15350:" ",
15400:" ",
15450:" ",
15500:"ТО500",
15550:" ",
15600:" ",
15650:" ",
15700:" ",
15750:" ",
15800:" ",
15850:" ",
15900:" ",
15950:" ",
16000:"ТО4000",
16050:" ",
16100:" ",
16150:" ",
16200:" ",
16250:" ",
16300:" ",
16350:" ",
16400:" ",
16450:" ",
16500:"ТО500",
16550:" ",
16600:" ",
16650:" ",
16700:" ",
16750:" ",
16800:" ",
16850:" ",
16900:" ",
16950:" ",
17000:"ТО1000",
17050:" ",
17100:" ",
17150:" ",
17200:" ",
17250:" ",
17300:" ",
17350:" ",
17400:" ",
17450:" ",
17500:"ТО500",
17550:" ",
17600:" ",
17650:" ",
17700:" ",
17750:" ",
17800:" ",
17850:" ",
17900:" ",
17950:" ",
18000:"ТО2000",
18050:" ",
18100:" ",
18150:" ",
18200:" ",
18250:" ",
18300:" ",
18350:" ",
18400:" ",
18450:" ",
18500:"ТО500",
18550:" ",
18600:" ",
18650:" ",
18700:" ",
18750:" ",
18800:" ",
18850:" ",
18900:" ",
18950:" ",
19000:"ТО1000",
19050:" ",
19100:" ",
19150:" ",
19200:" ",
19250:" ",
19300:" ",
19350:" ",
19400:" ",
19450:" ",
19500:"ТО500",
19550:" ",
19600:" ",
19650:" ",
19700:" ",
19750:" ",
19800:" ",
19850:" ",
19900:" ",
19950:" ",
20000:"ТО4000/ТО5000",
20050:" ",
20100:" ",
20150:" ",
20200:" ",
20250:" ",
20300:" ",
20350:" ",
20400:" ",
20450:" ",
20500:"ТО500",
20550:" ",
20600:" ",
20650:" ",
20700:" ",
20750:" ",
20800:" ",
20850:" ",
20900:" ",
20950:" ",
21000:"ТО3000",
21050:" ",
21100:" ",
21150:" ",
21200:" ",
21250:" ",
21300:" ",
21350:" ",
21400:" ",
21450:" ",
21500:"ТО500",
21550:" ",
21600:" ",
21650:" ",
21700:" ",
21750:" ",
21800:" ",
21850:" ",
21900:" ",
21950:" ",
22000:"ТО2000",
22050:" ",
22100:" ",
22150:" ",
22200:" ",
22250:" ",
22300:" ",
22350:" ",
22400:" ",
22450:" ",
22500:"ТО500",
22550:" ",
22600:" ",
22650:" ",
22700:" ",
22750:" ",
22800:" ",
22850:" ",
22900:" ",
22950:" ",
23000:"ТО1000",
23050:" ",
23100:" ",
23150:" ",
23200:" ",
23250:" ",
23300:" ",
23350:" ",
23400:" ",
23450:" ",
23500:"ТО500",
23550:" ",
23600:" ",
23650:" ",
23700:" ",
23750:" ",
23800:" ",
23850:" ",
23900:" ",
23950:" ",
24000:"ТО4000",
24050:" ",
24100:" ",
24150:" ",
24200:" ",
24250:" ",
24300:" ",
24350:" ",
24400:" ",
24450:" ",
24500:"ТО500",
24550:" ",
24600:" ",
24650:" ",
24700:" ",
24750:" ",
24800:" ",
24850:" ",
24900:" ",
24950:" ",
25000:"ТО5000",
25050:" ",
25100:" ",
25150:" ",
25200:" ",
25250:" ",
25300:" ",
25350:" ",
25400:" ",
25450:" ",
25500:"ТО500",
25550:" ",
25600:" ",
25650:" ",
25700:" ",
25750:" ",
25800:" ",
25850:" ",
25900:" ",
25950:" ",
26000:"ТО2000",
26050:" ",
26100:" ",
26150:" ",
26200:" ",
26250:" ",
26300:" ",
26350:" ",
26400:" ",
26450:" ",
26500:"ТО500",
26550:" ",
26600:" ",
26650:" ",
26700:" ",
26750:" ",
26800:" ",
26850:" ",
26900:" ",
26950:" ",
27000:"ТО3000",
27050:" ",
27100:" ",
27150:" ",
27200:" ",
27250:" ",
27300:" ",
27350:" ",
27400:" ",
27450:" ",
27500:"ТО500",
27550:" ",
27600:" ",
27650:" ",
27700:" ",
27750:" ",
27800:" ",
27850:" ",
27900:" ",
27950:" ",
28000:"ТО4000",
28050:" ",
28100:" ",
28150:" ",
28200:" ",
28250:" ",
28300:" ",
28350:" ",
28400:" ",
28450:" ",
28500:"ТО500",
28550:" ",
28600:" ",
28650:" ",
28700:" ",
28750:" ",
28800:" ",
28850:" ",
28900:" ",
28950:" ",
29000:"ТО500",
29050:" ",
29100:" ",
29150:" ",
29200:" ",
29250:" ",
29300:" ",
29350:" ",
29400:" ",
29450:" ",
29500:"ТО500",
29550:" ",
29600:" ",
29650:" ",
29700:" ",
29750:" ",
29800:" ",
29850:" ",
29900:" ",
29950:" ",
30000:"ТО2000/5000",
30050:" ",
30100:" ",
30150:" ",
30200:" ",
30250:" ",
30300:" ",
30350:" ",
30400:" ",
30450:" ",
30500:"ТО500",
30550:" ",
30600:" ",
30650:" ",
30700:" ",
30750:" ",
30800:" ",
30850:" ",
30900:" ",
30950:" ",
31000:"ТО1000",
31050:" ",
31100:" ",
31150:" ",
31200:" ",
31250:" ",
31300:" ",
31350:" ",
31400:" ",
31450:" ",
31500:"ТО500",
31550:" ",
31600:" ",
31650:" ",
31700:" ",
31750:" ",
31800:" ",
31850:" ",
31900:" ",
31950:" ",
32000:"ТО4000",
32050:" ",
32100:" ",
32150:" ",
32200:" ",
32250:" ",
32300:" ",
32350:" ",
32400:" ",
32450:" ",
32500:"ТО500",
32550:" ",
32600:" ",
32650:" ",
32700:" ",
32750:" ",
32800:" ",
32850:" ",
32900:" ",
32950:" ",
33000:"ТО3000",
33050:" ",
33100:" ",
33150:" ",
33200:" ",
33250:" ",
33300:" ",
33350:" ",
33400:" ",
33450:" ",
33500:"ТО500",
33550:" ",
33600:" ",
33650:" ",
33700:" ",
33750:" ",
33800:" ",
33850:" ",
33900:" ",
33950:" ",
34000:"ТО2000",
34050:" ",
34100:" ",
34150:" ",
34200:" ",
34250:" ",
34300:" ",
34350:" ",
34400:" ",
34450:" ",
34500:"ТО500",
34550:" ",
34600:" ",
34650:" ",
34700:" ",
34750:" ",
34800:" ",
34850:" ",
34900:" ",
34950:" ",
35000:"ТО5000",
35050:" ",
35100:" ",
35150:" ",
35200:" ",
35250:" ",
35300:" ",
35350:" ",
35400:" ",
35450:" ",
35500:"ТО500",
35550:" ",
35600:" ",
35650:" ",
35700:" ",
35750:" ",
35800:" ",
35850:" ",
35900:" ",
35950:" ",
36000:"ТО4000",
36050:" ",
36100:" ",
36150:" ",
36200:" ",
36250:" ",
36300:" ",
36350:" ",
36400:" ",
36450:" ",
36500:"ТО500",
36550:" ",
36600:" ",
36650:" ",
36700:" ",
36750:" ",
36800:" ",
36850:" ",
36900:" ",
36950:" ",
37000:"ТО1000",
37050:" ",
37100:" ",
37150:" ",
37200:" ",
37250:" ",
37300:" ",
37350:" ",
37400:" ",
37450:" ",
37500:"ТО500",
37550:" ",
37600:" ",
37650:" ",
37700:" ",
37750:" ",
37800:" ",
37850:" ",
37900:" ",
37950:" ",
38000:"ТО2000",
38050:" ",
38100:" ",
38150:" ",
38200:" ",
38250:" ",
38300:" ",
38350:" ",
38400:" ",
38450:" ",
38500:"ТО500",
38550:" ",
38600:" ",
38650:" ",
38700:" ",
38750:" ",
38800:" ",
38850:" ",
38900:" ",
38950:" ",
39000:"ТО3000",
39050:" ",
39100:" ",
39150:" ",
39200:" ",
39250:" ",
39300:" ",
39350:" ",
39400:" ",
39450:" ",
39500:"ТО500",
39550:" ",
39600:" ",
39650:" ",
39700:" ",
39750:" ",
39800:" ",
39850:" ",
39900:" ",
39950:" ",
40000:"ТО4000/5000",
40050:" ",
40100:" ",
40150:" ",
40200:" ",
40250:" ",
40300:" ",
40350:" ",
40400:" ",
40450:" ",
40500:"ТО500",
40550:" ",
40600:" ",
40650:" ",
40700:" ",
40750:" ",
40800:" ",
40850:" ",
40900:" ",
40950:" ",
41000:"ТО1000",
41050:" ",
41100:" ",
41150:" ",
41200:" ",
41250:" ",
41300:" ",
41350:" ",
41400:" ",
41450:" ",
41500:"ТО500",
41550:" ",
41600:" ",
41650:" ",
41700:" ",
41750:" ",
41800:" ",
41850:" ",
41900:" ",
41950:" ",
42000:"ТО2000",
42050:" ",
42100:" ",
42150:" ",
42200:" ",
42250:" ",
42300:" ",
42350:" ",
42400:" ",
42450:" ",
42500:"ТО500",
42550:" ",
42600:" ",
42650:" ",
42700:" ",
42750:" ",
42800:" ",
42850:" ",
42900:" ",
42950:" ",
43000:"ТО1000",
43050:" ",
43100:" ",
43150:" ",
43200:" ",
43250:" ",
43300:" ",
43350:" ",
43400:" ",
43450:" ",
43500:"ТО500",
43550:" ",
43600:" ",
43650:" ",
43700:" ",
43750:" ",
43800:" ",
43850:" ",
43900:" ",
43950:" ",
44000:"ТО4000",
44050:" ",
44100:" ",
44150:" ",
44200:" ",
44250:" ",
44300:" ",
44350:" ",
44400:" ",
44450:" ",
44500:"ТО500",
44550:" ",
44600:" ",
44650:" ",
44700:" ",
44750:" ",
44800:" ",
44850:" ",
44900:" ",
44950:" ",
45000:"ТО3000/5000",
45050:" ",
45100:" ",
45150:" ",
45200:" ",
45250:" ",
45300:" ",
45350:" ",
45400:" ",
45450:" ",
45500:"ТО500",
45550:" ",
45600:" ",
45650:" ",
45700:" ",
45750:" ",
45800:" ",
45850:" ",
45900:" ",
45950:" ",
46000:"ТО2000",
46050:" ",
46100:" ",
46150:" ",
46200:" ",
46250:" ",
46300:" ",
46350:" ",
46400:" ",
46450:" ",
46500:"ТО500",
46550:" ",
46600:" ",
46650:" ",
46700:" ",
46750:" ",
46800:" ",
46850:" ",
46900:" ",
46950:" ",
47000:"ТО1000",
47050:" ",
47100:" ",
47150:" ",
47200:" ",
47250:" ",
47300:" ",
47350:" ",
47400:" ",
47450:" ",
47500:"ТО500",
47550:" ",
47600:" ",
47650:" ",
47700:" ",
47750:" ",
47800:" ",
47850:" ",
47900:" ",
47950:" ",
48000:"ТО4000"

    
}

In [70]:
to_CLG942EHD={
   50:"",
100:"",
150:"",
200:" ",
250:"ТО250",
300:" ",
350:" ",
400:" ",
450:" ",
500:"ТО500",
550:" ",
600:" ",
650:" ",
700:" ",
750:"ТО250",
800:" ",
850:" ",
900:" ",
950:" ",
1000:"ТО1000",
1050:" ",
1100:" ",
1150:" ",
1200:" ",
1250:"ТО250",
1300:" ",
1350:" ",
1400:" ",
1450:" ",
1500:"ТО500",
1550:" ",
1600:" ",
1650:" ",
1700:" ",
1750:"ТО250",
1800:" ",
1850:" ",
1900:" ",
1950:" ",
2000:"ТО2000",
2050:" ",
2100:" ",
2150:" ",
2200:" ",
2250:"ТО250",
2300:" ",
2350:" ",
2400:" ",
2450:" ",
2500:"ТО500",
2550:" ",
2600:" ",
2650:" ",
2700:" ",
2750:"ТО250",
2800:" ",
2850:" ",
2900:" ",
2950:" ",
3000:"ТО3000",
3050:" ",
3100:" ",
3150:" ",
3200:" ",
3250:"ТО250",
3300:" ",
3350:" ",
3400:" ",
3450:" ",
3500:"ТО500",
3550:" ",
3600:" ",
3650:" ",
3700:" ",
3750:"ТО250",
3800:" ",
3850:" ",
3900:" ",
3950:" ",
4000:"ТО4000",
4050:" ",
4100:" ",
4150:" ",
4200:" ",
4250:"ТО250",
4300:" ",
4350:" ",
4400:" ",
4450:" ",
4500:"ТО500",
4550:" ",
4600:" ",
4650:" ",
4700:" ",
4750:"ТО250",
4800:" ",
4850:" ",
4900:" ",
4950:" ",
5000:"ТО5000",
5050:" ",
5100:" ",
5150:" ",
5200:" ",
5250:"ТО250",
5300:" ",
5350:" ",
5400:" ",
5450:" ",
5500:"ТО500",
5550:" ",
5600:" ",
5650:" ",
5700:" ",
5750:"ТО250",
5800:" ",
5850:" ",
5900:" ",
5950:" ",
6000:"ТО2000",
6050:" ",
6100:" ",
6150:" ",
6200:" ",
6250:"ТО250",
6300:" ",
6350:" ",
6400:" ",
6450:" ",
6500:"ТО500",
6550:" ",
6600:" ",
6650:" ",
6700:" ",
6750:"ТО250",
6800:" ",
6850:" ",
6900:" ",
6950:" ",
7000:"ТО1000",
7050:" ",
7100:" ",
7150:" ",
7200:" ",
7250:"ТО250",
7300:" ",
7350:" ",
7400:" ",
7450:" ",
7500:"ТО500",
7550:" ",
7600:" ",
7650:" ",
7700:" ",
7750:"ТО250",
7800:" ",
7850:" ",
7900:" ",
7950:" ",
8000:"ТО4000",
8050:" ",
8100:" ",
8150:" ",
8200:" ",
8250:"ТО250",
8300:" ",
8350:" ",
8400:" ",
8450:" ",
8500:"ТО500",
8550:" ",
8600:" ",
8650:" ",
8700:" ",
8750:"ТО250",
8800:" ",
8850:" ",
8900:" ",
8950:" ",
9000:"ТО3000",
9050:" ",
9100:" ",
9150:" ",
9200:" ",
9250:"ТО250",
9300:" ",
9350:" ",
9400:" ",
9450:" ",
9500:"ТО500",
9550:" ",
9600:" ",
9650:" ",
9700:" ",
9750:"ТО250",
9800:" ",
9850:" ",
9900:" ",
9950:" ",
10000:"ТО2000/ТО5000",
10050:" ",
10100:" ",
10150:" ",
10200:" ",
10250:"ТО250",
10300:" ",
10350:" ",
10400:" ",
10450:" ",
10500:"ТО500",
10550:" ",
10600:" ",
10650:" ",
10700:" ",
10750:"ТО250",
10800:" ",
10850:" ",
10900:" ",
10950:" ",
11000:"ТО1000",
11050:" ",
11100:" ",
11150:" ",
11200:" ",
11250:"ТО250",
11300:" ",
11350:" ",
11400:" ",
11450:" ",
11500:"ТО500",
11550:" ",
11600:" ",
11650:" ",
11700:" ",
11750:"ТО250",
11800:" ",
11850:" ",
11900:" ",
11950:" ",
12000:"ТО4000",
12050:" ",
12100:" ",
12150:" ",
12200:" ",
12250:"ТО250",
12300:" ",
12350:" ",
12400:" ",
12450:" ",
12500:"ТО500",
12550:" ",
12600:" ",
12650:" ",
12700:" ",
12750:"ТО250",
12800:" ",
12850:" ",
12900:" ",
12950:" ",
13000:"ТО1000",
13050:" ",
13100:" ",
13150:" ",
13200:" ",
13250:"ТО250",
13300:" ",
13350:" ",
13400:" ",
13450:" ",
13500:"ТО500",
13550:" ",
13600:" ",
13650:" ",
13700:" ",
13750:"ТО250",
13800:" ",
13850:" ",
13900:" ",
13950:" ",
14000:"ТО2000",
14050:" ",
14100:" ",
14150:" ",
14200:" ",
14250:"ТО250",
14300:" ",
14350:" ",
14400:" ",
14450:" ",
14500:"ТО500",
14550:" ",
14600:" ",
14650:" ",
14700:" ",
14750:"ТО250",
14800:" ",
14850:" ",
14900:" ",
14950:" ",
15000:"ТО3000/ТО5000",
15050:" ",
15100:" ",
15150:" ",
15200:" ",
15250:"ТО250",
15300:" ",
15350:" ",
15400:" ",
15450:" ",
15500:"ТО500",
15550:" ",
15600:" ",
15650:" ",
15700:" ",
15750:"ТО250",
15800:" ",
15850:" ",
15900:" ",
15950:" ",
16000:"ТО4000",
16050:" ",
16100:" ",
16150:" ",
16200:" ",
16250:"ТО250",
16300:" ",
16350:" ",
16400:" ",
16450:" ",
16500:"ТО500",
16550:" ",
16600:" ",
16650:" ",
16700:" ",
16750:"ТО250",
16800:" ",
16850:" ",
16900:" ",
16950:" ",
17000:"ТО1000",
17050:" ",
17100:" ",
17150:" ",
17200:" ",
17250:"ТО250",
17300:" ",
17350:" ",
17400:" ",
17450:" ",
17500:"ТО500",
17550:" ",
17600:" ",
17650:" ",
17700:" ",
17750:"ТО250",
17800:" ",
17850:" ",
17900:" ",
17950:" ",
18000:"ТО2000",
18050:" ",
18100:" ",
18150:" ",
18200:" ",
18250:"ТО250",
18300:" ",
18350:" ",
18400:" ",
18450:" ",
18500:"ТО500",
18550:" ",
18600:" ",
18650:" ",
18700:" ",
18750:"ТО250",
18800:" ",
18850:" ",
18900:" ",
18950:" ",
19000:"ТО1000",
19050:" ",
19100:" ",
19150:" ",
19200:" ",
19250:"ТО250",
19300:" ",
19350:" ",
19400:" ",
19450:" ",
19500:"ТО500",
19550:" ",
19600:" ",
19650:" ",
19700:" ",
19750:"ТО250",
19800:" ",
19850:" ",
19900:" ",
19950:" ",
20000:"ТО4000/ТО5000",
20050:" ",
20100:" ",
20150:" ",
20200:" ",
20250:"ТО250",
20300:" ",
20350:" ",
20400:" ",
20450:" ",
20500:"ТО500",
20550:" ",
20600:" ",
20650:" ",
20700:" ",
20750:"ТО250",
20800:" ",
20850:" ",
20900:" ",
20950:" ",
21000:"ТО3000",
21050:" ",
21100:" ",
21150:" ",
21200:" ",
21250:"ТО250",
21300:" ",
21350:" ",
21400:" ",
21450:" ",
21500:"ТО500",
21550:" ",
21600:" ",
21650:" ",
21700:" ",
21750:"ТО250",
21800:" ",
21850:" ",
21900:" ",
21950:" ",
22000:"ТО2000",
22050:" ",
22100:" ",
22150:" ",
22200:" ",
22250:"ТО250",
22300:" ",
22350:" ",
22400:" ",
22450:" ",
22500:"ТО500",
22550:" ",
22600:" ",
22650:" ",
22700:" ",
22750:"ТО250",
22800:" ",
22850:" ",
22900:" ",
22950:" ",
23000:"ТО1000",
23050:" ",
23100:" ",
23150:" ",
23200:" ",
23250:"ТО250",
23300:" ",
23350:" ",
23400:" ",
23450:" ",
23500:"ТО500",
23550:" ",
23600:" ",
23650:" ",
23700:" ",
23750:"ТО250",
23800:" ",
23850:" ",
23900:" ",
23950:" ",
24000:"ТО4000",
24050:" ",
24100:" ",
24150:" ",
24200:" ",
24250:"ТО250",
24300:" ",
24350:" ",
24400:" ",
24450:" ",
24500:"ТО500",
24550:" ",
24600:" ",
24650:" ",
24700:" ",
24750:"ТО250",
24800:" ",
24850:" ",
24900:" ",
24950:" ",
25000:"ТО5000",
25050:" ",
25100:" ",
25150:" ",
25200:" ",
25250:"ТО250",
25300:" ",
25350:" ",
25400:" ",
25450:" ",
25500:"ТО500",
25550:" ",
25600:" ",
25650:" ",
25700:" ",
25750:"ТО250",
25800:" ",
25850:" ",
25900:" ",
25950:" ",
26000:"ТО2000",
26050:" ",
26100:" ",
26150:" ",
26200:" ",
26250:"ТО250",
26300:" ",
26350:" ",
26400:" ",
26450:" ",
26500:"ТО500",
26550:" ",
26600:" ",
26650:" ",
26700:" ",
26750:"ТО250",
26800:" ",
26850:" ",
26900:" ",
26950:" ",
27000:"ТО3000",
27050:" ",
27100:" ",
27150:" ",
27200:" ",
27250:"ТО250",
27300:" ",
27350:" ",
27400:" ",
27450:" ",
27500:"ТО500",
27550:" ",
27600:" ",
27650:" ",
27700:" ",
27750:"ТО250",
27800:" ",
27850:" ",
27900:" ",
27950:" ",
28000:"ТО4000",
28050:" ",
28100:" ",
28150:" ",
28200:" ",
28250:"ТО250",
28300:" ",
28350:" ",
28400:" ",
28450:" ",
28500:"ТО500",
28550:" ",
28600:" ",
28650:" ",
28700:" ",
28750:"ТО250",
28800:" ",
28850:" ",
28900:" ",
28950:" ",
29000:"ТО500",
29050:" ",
29100:" ",
29150:" ",
29200:" ",
29250:"ТО250",
29300:" ",
29350:" ",
29400:" ",
29450:" ",
29500:"ТО500",
29550:" ",
29600:" ",
29650:" ",
29700:" ",
29750:"ТО250",
29800:" ",
29850:" ",
29900:" ",
29950:" ",
30000:"ТО2000/5000",
30050:" ",
30100:" ",
30150:" ",
30200:" ",
30250:"ТО250",
30300:" ",
30350:" ",
30400:" ",
30450:" ",
30500:"ТО500",
30550:" ",
30600:" ",
30650:" ",
30700:" ",
30750:"ТО250",
30800:" ",
30850:" ",
30900:" ",
30950:" ",
31000:"ТО1000",
31050:" ",
31100:" ",
31150:" ",
31200:" ",
31250:"ТО250",
31300:" ",
31350:" ",
31400:" ",
31450:" ",
31500:"ТО500",
31550:" ",
31600:" ",
31650:" ",
31700:" ",
31750:"ТО250",
31800:" ",
31850:" ",
31900:" ",
31950:" ",
32000:"ТО4000",
32050:" ",
32100:" ",
32150:" ",
32200:" ",
32250:"ТО250",
32300:" ",
32350:" ",
32400:" ",
32450:" ",
32500:"ТО500",
32550:" ",
32600:" ",
32650:" ",
32700:" ",
32750:"ТО250",
32800:" ",
32850:" ",
32900:" ",
32950:" ",
33000:"ТО3000",
33050:" ",
33100:" ",
33150:" ",
33200:" ",
33250:"ТО250",
33300:" ",
33350:" ",
33400:" ",
33450:" ",
33500:"ТО500",
33550:" ",
33600:" ",
33650:" ",
33700:" ",
33750:"ТО250",
33800:" ",
33850:" ",
33900:" ",
33950:" ",
34000:"ТО2000",
34050:" ",
34100:" ",
34150:" ",
34200:" ",
34250:"ТО250",
34300:" ",
34350:" ",
34400:" ",
34450:" ",
34500:"ТО500",
34550:" ",
34600:" ",
34650:" ",
34700:" ",
34750:"ТО250",
34800:" ",
34850:" ",
34900:" ",
34950:" ",
35000:"ТО5000",
35050:" ",
35100:" ",
35150:" ",
35200:" ",
35250:"ТО250",
35300:" ",
35350:" ",
35400:" ",
35450:" ",
35500:"ТО500",
35550:" ",
35600:" ",
35650:" ",
35700:" ",
35750:"ТО250",
35800:" ",
35850:" ",
35900:" ",
35950:" ",
36000:"ТО4000",
36050:" ",
36100:" ",
36150:" ",
36200:" ",
36250:"ТО250",
36300:" ",
36350:" ",
36400:" ",
36450:" ",
36500:"ТО500",
36550:" ",
36600:" ",
36650:" ",
36700:" ",
36750:"ТО250",
36800:" ",
36850:" ",
36900:" ",
36950:" ",
37000:"ТО1000",
37050:" ",
37100:" ",
37150:" ",
37200:" ",
37250:"ТО250",
37300:" ",
37350:" ",
37400:" ",
37450:" ",
37500:"ТО500",
37550:" ",
37600:" ",
37650:" ",
37700:" ",
37750:"ТО250",
37800:" ",
37850:" ",
37900:" ",
37950:" ",
38000:"ТО2000",
38050:" ",
38100:" ",
38150:" ",
38200:" ",
38250:"ТО250",
38300:" ",
38350:" ",
38400:" ",
38450:" ",
38500:"ТО500",
38550:" ",
38600:" ",
38650:" ",
38700:" ",
38750:"ТО250",
38800:" ",
38850:" ",
38900:" ",
38950:" ",
39000:"ТО3000",
39050:" ",
39100:" ",
39150:" ",
39200:" ",
39250:"ТО250",
39300:" ",
39350:" ",
39400:" ",
39450:" ",
39500:"ТО500",
39550:" ",
39600:" ",
39650:" ",
39700:" ",
39750:"ТО250",
39800:" ",
39850:" ",
39900:" ",
39950:" ",
40000:"ТО4000/5000",
40050:" ",
40100:" ",
40150:" ",
40200:" ",
40250:"ТО250",
40300:" ",
40350:" ",
40400:" ",
40450:" ",
40500:"ТО500",
40550:" ",
40600:" ",
40650:" ",
40700:" ",
40750:"ТО250",
40800:" ",
40850:" ",
40900:" ",
40950:" ",
41000:"ТО1000",
41050:" ",
41100:" ",
41150:" ",
41200:" ",
41250:"ТО250",
41300:" ",
41350:" ",
41400:" ",
41450:" ",
41500:"ТО500",
41550:" ",
41600:" ",
41650:" ",
41700:" ",
41750:"ТО250",
41800:" ",
41850:" ",
41900:" ",
41950:" ",
42000:"ТО2000",
42050:" ",
42100:" ",
42150:" ",
42200:" ",
42250:"ТО250",
42300:" ",
42350:" ",
42400:" ",
42450:" ",
42500:"ТО500",
42550:" ",
42600:" ",
42650:" ",
42700:" ",
42750:"ТО250",
42800:" ",
42850:" ",
42900:" ",
42950:" ",
43000:"ТО1000",
43050:" ",
43100:" ",
43150:" ",
43200:" ",
43250:"ТО250",
43300:" ",
43350:" ",
43400:" ",
43450:" ",
43500:"ТО500",
43550:" ",
43600:" ",
43650:" ",
43700:" ",
43750:"ТО250",
43800:" ",
43850:" ",
43900:" ",
43950:" ",
44000:"ТО4000",
44050:" ",
44100:" ",
44150:" ",
44200:" ",
44250:"ТО250",
44300:" ",
44350:" ",
44400:" ",
44450:" ",
44500:"ТО500",
44550:" ",
44600:" ",
44650:" ",
44700:" ",
44750:"ТО250",
44800:" ",
44850:" ",
44900:" ",
44950:" ",
45000:"ТО3000/5000",
45050:" ",
45100:" ",
45150:" ",
45200:" ",
45250:"ТО250",
45300:" ",
45350:" ",
45400:" ",
45450:" ",
45500:"ТО500",
45550:" ",
45600:" ",
45650:" ",
45700:" ",
45750:"ТО250",
45800:" ",
45850:" ",
45900:" ",
45950:" ",
46000:"ТО2000",
46050:" ",
46100:" ",
46150:" ",
46200:" ",
46250:"ТО250",
46300:" ",
46350:" ",
46400:" ",
46450:" ",
46500:"ТО500",
46550:" ",
46600:" ",
46650:" ",
46700:" ",
46750:"ТО250",
46800:" ",
46850:" ",
46900:" ",
46950:" ",
47000:"ТО1000",
47050:" ",
47100:" ",
47150:" ",
47200:" ",
47250:"ТО250",
47300:" ",
47350:" ",
47400:" ",
47450:" ",
47500:"ТО500",
47550:" ",
47600:" ",
47650:" ",
47700:" ",
47750:"ТО250",
47800:" ",
47850:" ",
47900:" ",
47950:" ",
48000:"ТО4000"

    
}

In [71]:
to_CLG877H={
   50:"",
100:"",
150:"",
200:" ",
250:"ТО250",
300:" ",
350:" ",
400:" ",
450:" ",
500:"ТО500",
550:" ",
600:" ",
650:" ",
700:" ",
750:"ТО250",
800:" ",
850:" ",
900:" ",
950:" ",
1000:"ТО1000",
1050:" ",
1100:" ",
1150:" ",
1200:" ",
1250:"ТО250",
1300:" ",
1350:" ",
1400:" ",
1450:" ",
1500:"ТО1500",
1550:" ",
1600:" ",
1650:" ",
1700:" ",
1750:"ТО250",
1800:" ",
1850:" ",
1900:" ",
1950:" ",
2000:"ТО2000",
2050:" ",
2100:" ",
2150:" ",
2200:" ",
2250:"ТО250",
2300:" ",
2350:" ",
2400:" ",
2450:" ",
2500:"ТО500",
2550:" ",
2600:" ",
2650:" ",
2700:" ",
2750:"ТО250",
2800:" ",
2850:" ",
2900:" ",
2950:" ",
3000:"ТО1500",
3050:" ",
3100:" ",
3150:" ",
3200:" ",
3250:"ТО250",
3300:" ",
3350:" ",
3400:" ",
3450:" ",
3500:"ТО500",
3550:" ",
3600:" ",
3650:" ",
3700:" ",
3750:"ТО250",
3800:" ",
3850:" ",
3900:" ",
3950:" ",
4000:"ТО4000",
4050:" ",
4100:" ",
4150:" ",
4200:" ",
4250:"ТО250",
4300:" ",
4350:" ",
4400:" ",
4450:" ",
4500:"ТО500",
4550:" ",
4600:" ",
4650:" ",
4700:" ",
4750:"ТО250",
4800:" ",
4850:" ",
4900:" ",
4950:" ",
5000:"ТО1000",
5050:" ",
5100:" ",
5150:" ",
5200:" ",
5250:"ТО250",
5300:" ",
5350:" ",
5400:" ",
5450:" ",
5500:"ТО500",
5550:" ",
5600:" ",
5650:" ",
5700:" ",
5750:"ТО250",
5800:" ",
5850:" ",
5900:" ",
5950:" ",
6000:"ТО6000",
6050:" ",
6100:" ",
6150:" ",
6200:" ",
6250:"ТО250",
6300:" ",
6350:" ",
6400:" ",
6450:" ",
6500:"ТО500",
6550:" ",
6600:" ",
6650:" ",
6700:" ",
6750:"ТО250",
6800:" ",
6850:" ",
6900:" ",
6950:" ",
7000:"ТО1000",
7050:" ",
7100:" ",
7150:" ",
7200:" ",
7250:"ТО250",
7300:" ",
7350:" ",
7400:" ",
7450:" ",
7500:"ТО500",
7550:" ",
7600:" ",
7650:" ",
7700:" ",
7750:"ТО250",
7800:" ",
7850:" ",
7900:" ",
7950:" ",
8000:"ТО4000",
8050:" ",
8100:" ",
8150:" ",
8200:" ",
8250:"ТО250",
8300:" ",
8350:" ",
8400:" ",
8450:" ",
8500:"ТО500",
8550:" ",
8600:" ",
8650:" ",
8700:" ",
8750:"ТО250",
8800:" ",
8850:" ",
8900:" ",
8950:" ",
9000:"ТО1500",
9050:" ",
9100:" ",
9150:" ",
9200:" ",
9250:"ТО250",
9300:" ",
9350:" ",
9400:" ",
9450:" ",
9500:"ТО500",
9550:" ",
9600:" ",
9650:" ",
9700:" ",
9750:"ТО250",
9800:" ",
9850:" ",
9900:" ",
9950:" ",
10000:"ТО2000",
10050:" ",
10100:" ",
10150:" ",
10200:" ",
10250:"ТО250",
10300:" ",
10350:" ",
10400:" ",
10450:" ",
10500:"ТО500",
10550:" ",
10600:" ",
10650:" ",
10700:" ",
10750:"ТО250",
10800:" ",
10850:" ",
10900:" ",
10950:" ",
11000:"ТО1000",
11050:" ",
11100:" ",
11150:" ",
11200:" ",
11250:"ТО250",
11300:" ",
11350:" ",
11400:" ",
11450:" ",
11500:"ТО500",
11550:" ",
11600:" ",
11650:" ",
11700:" ",
11750:"ТО250",
11800:" ",
11850:" ",
11900:" ",
11950:" ",
12000:"ТО4000/6000",
12050:" ",
12100:" ",
12150:" ",
12200:" ",
12250:"ТО250",
12300:" ",
12350:" ",
12400:" ",
12450:" ",
12500:"ТО500",
12550:" ",
12600:" ",
12650:" ",
12700:" ",
12750:"ТО250",
12800:" ",
12850:" ",
12900:" ",
12950:" ",
13000:"ТО1000",
13050:" ",
13100:" ",
13150:" ",
13200:" ",
13250:"ТО250",
13300:" ",
13350:" ",
13400:" ",
13450:" ",
13500:"ТО500",
13550:" ",
13600:" ",
13650:" ",
13700:" ",
13750:"ТО250",
13800:" ",
13850:" ",
13900:" ",
13950:" ",
14000:"ТО2000",
14050:" ",
14100:" ",
14150:" ",
14200:" ",
14250:"ТО250",
14300:" ",
14350:" ",
14400:" ",
14450:" ",
14500:"ТО500",
14550:" ",
14600:" ",
14650:" ",
14700:" ",
14750:"ТО250",
14800:" ",
14850:" ",
14900:" ",
14950:" ",
15000:"ТО1000/1500",
15050:" ",
15100:" ",
15150:" ",
15200:" ",
15250:"ТО250",
15300:" ",
15350:" ",
15400:" ",
15450:" ",
15500:"ТО500",
15550:" ",
15600:" ",
15650:" ",
15700:" ",
15750:"ТО250",
15800:" ",
15850:" ",
15900:" ",
15950:" ",
16000:"ТО4000",
16050:" ",
16100:" ",
16150:" ",
16200:" ",
16250:"ТО250",
16300:" ",
16350:" ",
16400:" ",
16450:" ",
16500:"ТО500",
16550:" ",
16600:" ",
16650:" ",
16700:" ",
16750:"ТО250",
16800:" ",
16850:" ",
16900:" ",
16950:" ",
17000:"ТО1000",
17050:" ",
17100:" ",
17150:" ",
17200:" ",
17250:"ТО250",
17300:" ",
17350:" ",
17400:" ",
17450:" ",
17500:"ТО500",
17550:" ",
17600:" ",
17650:" ",
17700:" ",
17750:"ТО250",
17800:" ",
17850:" ",
17900:" ",
17950:" ",
18000:"ТО6000",
18050:" ",
18100:" ",
18150:" ",
18200:" ",
18250:"ТО250",
18300:" ",
18350:" ",
18400:" ",
18450:" ",
18500:"ТО500",
18550:" ",
18600:" ",
18650:" ",
18700:" ",
18750:"ТО250",
18800:" ",
18850:" ",
18900:" ",
18950:" ",
19000:"ТО1000",
19050:" ",
19100:" ",
19150:" ",
19200:" ",
19250:"ТО250",
19300:" ",
19350:" ",
19400:" ",
19450:" ",
19500:"ТО500",
19550:" ",
19600:" ",
19650:" ",
19700:" ",
19750:"ТО250",
19800:" ",
19850:" ",
19900:" ",
19950:" ",
20000:"ТО4000",
20050:" ",
20100:" ",
20150:" ",
20200:" ",
20250:"ТО250",
20300:" ",
20350:" ",
20400:" ",
20450:" ",
20500:"ТО500",
20550:" ",
20600:" ",
20650:" ",
20700:" ",
20750:"ТО250",
20800:" ",
20850:" ",
20900:" ",
20950:" ",
21000:"ТО1000/1500",
21050:" ",
21100:" ",
21150:" ",
21200:" ",
21250:"ТО250",
21300:" ",
21350:" ",
21400:" ",
21450:" ",
21500:"ТО500",
21550:" ",
21600:" ",
21650:" ",
21700:" ",
21750:"ТО250",
21800:" ",
21850:" ",
21900:" ",
21950:" ",
22000:"ТО2000",
22050:" ",
22100:" ",
22150:" ",
22200:" ",
22250:"ТО250",
22300:" ",
22350:" ",
22400:" ",
22450:" ",
22500:"ТО500",
22550:" ",
22600:" ",
22650:" ",
22700:" ",
22750:"ТО250",
22800:" ",
22850:" ",
22900:" ",
22950:" ",
23000:"ТО1000",
23050:" ",
23100:" ",
23150:" ",
23200:" ",
23250:"ТО250",
23300:" ",
23350:" ",
23400:" ",
23450:" ",
23500:"ТО500",
23550:" ",
23600:" ",
23650:" ",
23700:" ",
23750:"ТО250",
23800:" ",
23850:" ",
23900:" ",
23950:" ",
24000:"ТО4000/6000",
24050:" ",
24100:" ",
24150:" ",
24200:" ",
24250:"ТО250",
24300:" ",
24350:" ",
24400:" ",
24450:" ",
24500:"ТО500",
24550:" ",
24600:" ",
24650:" ",
24700:" ",
24750:"ТО250",
24800:" ",
24850:" ",
24900:" ",
24950:" ",
25000:"ТО1000",
25050:" ",
25100:" ",
25150:" ",
25200:" ",
25250:"ТО250",
25300:" ",
25350:" ",
25400:" ",
25450:" ",
25500:"ТО500",
25550:" ",
25600:" ",
25650:" ",
25700:" ",
25750:"ТО250",
25800:" ",
25850:" ",
25900:" ",
25950:" ",
26000:"ТО2000",
26050:" ",
26100:" ",
26150:" ",
26200:" ",
26250:"ТО250",
26300:" ",
26350:" ",
26400:" ",
26450:" ",
26500:"ТО500",
26550:" ",
26600:" ",
26650:" ",
26700:" ",
26750:"ТО250",
26800:" ",
26850:" ",
26900:" ",
26950:" ",
27000:"ТО1000/1500",
27050:" ",
27100:" ",
27150:" ",
27200:" ",
27250:"ТО250",
27300:" ",
27350:" ",
27400:" ",
27450:" ",
27500:"ТО500",
27550:" ",
27600:" ",
27650:" ",
27700:" ",
27750:"ТО250",
27800:" ",
27850:" ",
27900:" ",
27950:" ",
28000:"ТО4000",
28050:" ",
28100:" ",
28150:" ",
28200:" ",
28250:"ТО250",
28300:" ",
28350:" ",
28400:" ",
28450:" ",
28500:"ТО500",
28550:" ",
28600:" ",
28650:" ",
28700:" ",
28750:"ТО250",
28800:" ",
28850:" ",
28900:" ",
28950:" ",
29000:"ТО500",
29050:" ",
29100:" ",
29150:" ",
29200:" ",
29250:"ТО250",
29300:" ",
29350:" ",
29400:" ",
29450:" ",
29500:"ТО500",
29550:" ",
29600:" ",
29650:" ",
29700:" ",
29750:"ТО250",
29800:" ",
29850:" ",
29900:" ",
29950:" ",
30000:"ТО6000",
30050:" ",
30100:" ",
30150:" ",
30200:" ",
30250:"ТО250",
30300:" ",
30350:" ",
30400:" ",
30450:" ",
30500:"ТО500",
30550:" ",
30600:" ",
30650:" ",
30700:" ",
30750:"ТО250",
30800:" ",
30850:" ",
30900:" ",
30950:" ",
31000:"ТО1000",
31050:" ",
31100:" ",
31150:" ",
31200:" ",
31250:"ТО250",
31300:" ",
31350:" ",
31400:" ",
31450:" ",
31500:"ТО500",
31550:" ",
31600:" ",
31650:" ",
31700:" ",
31750:"ТО250",
31800:" ",
31850:" ",
31900:" ",
31950:" ",
32000:"ТО4000",
32050:" ",
32100:" ",
32150:" ",
32200:" ",
32250:"ТО250",
32300:" ",
32350:" ",
32400:" ",
32450:" ",
32500:"ТО500",
32550:" ",
32600:" ",
32650:" ",
32700:" ",
32750:"ТО250",
32800:" ",
32850:" ",
32900:" ",
32950:" ",
33000:"ТО1000/1500",
33050:" ",
33100:" ",
33150:" ",
33200:" ",
33250:"ТО250",
33300:" ",
33350:" ",
33400:" ",
33450:" ",
33500:"ТО500",
33550:" ",
33600:" ",
33650:" ",
33700:" ",
33750:"ТО250",
33800:" ",
33850:" ",
33900:" ",
33950:" ",
34000:"ТО2000",
34050:" ",
34100:" ",
34150:" ",
34200:" ",
34250:"ТО250",
34300:" ",
34350:" ",
34400:" ",
34450:" ",
34500:"ТО500",
34550:" ",
34600:" ",
34650:" ",
34700:" ",
34750:"ТО250",
34800:" ",
34850:" ",
34900:" ",
34950:" ",
35000:"ТО5000",
35050:" ",
35100:" ",
35150:" ",
35200:" ",
35250:"ТО250",
35300:" ",
35350:" ",
35400:" ",
35450:" ",
35500:"ТО500",
35550:" ",
35600:" ",
35650:" ",
35700:" ",
35750:"ТО250",
35800:" ",
35850:" ",
35900:" ",
35950:" ",
36000:"ТО4000",
36050:" ",
36100:" ",
36150:" ",
36200:" ",
36250:"ТО250",
36300:" ",
36350:" ",
36400:" ",
36450:" ",
36500:"ТО500",
36550:" ",
36600:" ",
36650:" ",
36700:" ",
36750:"ТО250",
36800:" ",
36850:" ",
36900:" ",
36950:" ",
37000:"ТО1000",
37050:" ",
37100:" ",
37150:" ",
37200:" ",
37250:"ТО250",
37300:" ",
37350:" ",
37400:" ",
37450:" ",
37500:"ТО500",
37550:" ",
37600:" ",
37650:" ",
37700:" ",
37750:"ТО250",
37800:" ",
37850:" ",
37900:" ",
37950:" ",
38000:"ТО2000",
38050:" ",
38100:" ",
38150:" ",
38200:" ",
38250:"ТО250",
38300:" ",
38350:" ",
38400:" ",
38450:" ",
38500:"ТО500",
38550:" ",
38600:" ",
38650:" ",
38700:" ",
38750:"ТО250",
38800:" ",
38850:" ",
38900:" ",
38950:" ",
39000:"ТО1000/1500",
39050:" ",
39100:" ",
39150:" ",
39200:" ",
39250:"ТО250",
39300:" ",
39350:" ",
39400:" ",
39450:" ",
39500:"ТО500",
39550:" ",
39600:" ",
39650:" ",
39700:" ",
39750:"ТО250",
39800:" ",
39850:" ",
39900:" ",
39950:" ",
40000:"ТО4000",
40050:" ",
40100:" ",
40150:" ",
40200:" ",
40250:"ТО250",
40300:" ",
40350:" ",
40400:" ",
40450:" ",
40500:"ТО500",
40550:" ",
40600:" ",
40650:" ",
40700:" ",
40750:"ТО250",
40800:" ",
40850:" ",
40900:" ",
40950:" ",
41000:"ТО1000",
41050:" ",
41100:" ",
41150:" ",
41200:" ",
41250:"ТО250",
41300:" ",
41350:" ",
41400:" ",
41450:" ",
41500:"ТО500",
41550:" ",
41600:" ",
41650:" ",
41700:" ",
41750:"ТО250",
41800:" ",
41850:" ",
41900:" ",
41950:" ",
42000:"ТО6000",
42050:" ",
42100:" ",
42150:" ",
42200:" ",
42250:"ТО250",
42300:" ",
42350:" ",
42400:" ",
42450:" ",
42500:"ТО500",
42550:" ",
42600:" ",
42650:" ",
42700:" ",
42750:"ТО250",
42800:" ",
42850:" ",
42900:" ",
42950:" ",
43000:"ТО1000",
43050:" ",
43100:" ",
43150:" ",
43200:" ",
43250:"ТО250",
43300:" ",
43350:" ",
43400:" ",
43450:" ",
43500:"ТО500",
43550:" ",
43600:" ",
43650:" ",
43700:" ",
43750:"ТО250",
43800:" ",
43850:" ",
43900:" ",
43950:" ",
44000:"ТО4000",
44050:" ",
44100:" ",
44150:" ",
44200:" ",
44250:"ТО250",
44300:" ",
44350:" ",
44400:" ",
44450:" ",
44500:"ТО500",
44550:" ",
44600:" ",
44650:" ",
44700:" ",
44750:"ТО250",
44800:" ",
44850:" ",
44900:" ",
44950:" ",
45000:"ТО1000/1500",
45050:" ",
45100:" ",
45150:" ",
45200:" ",
45250:"ТО250",
45300:" ",
45350:" ",
45400:" ",
45450:" ",
45500:"ТО500",
45550:" ",
45600:" ",
45650:" ",
45700:" ",
45750:"ТО250",
45800:" ",
45850:" ",
45900:" ",
45950:" ",
46000:"ТО2000",
46050:" ",
46100:" ",
46150:" ",
46200:" ",
46250:"ТО250",
46300:" ",
46350:" ",
46400:" ",
46450:" ",
46500:"ТО500",
46550:" ",
46600:" ",
46650:" ",
46700:" ",
46750:"ТО250",
46800:" ",
46850:" ",
46900:" ",
46950:" ",
47000:"ТО1000",
47050:" ",
47100:" ",
47150:" ",
47200:" ",
47250:"ТО250",
47300:" ",
47350:" ",
47400:" ",
47450:" ",
47500:"ТО500",
47550:" ",
47600:" ",
47650:" ",
47700:" ",
47750:"ТО250",
47800:" ",
47850:" ",
47900:" ",
47950:" ",
48000:"ТО4000/6000"

    
}

In [72]:
to_12HDC={
   50:"",
100:"",
150:"",
200:" ",
250:"",
300:" ",
350:" ",
400:" ",
450:" ",
500:"ТО500",
550:" ",
600:" ",
650:" ",
700:" ",
750:"",
800:" ",
850:" ",
900:" ",
950:" ",
1000:"ТО1000",
1050:" ",
1100:" ",
1150:" ",
1200:" ",
1250:"",
1300:" ",
1350:" ",
1400:" ",
1450:" ",
1500:"ТО500",
1550:" ",
1600:" ",
1650:" ",
1700:" ",
1750:"",
1800:" ",
1850:" ",
1900:" ",
1950:" ",
2000:"ТО1000",
2050:" ",
2100:" ",
2150:" ",
2200:" ",
2250:"",
2300:" ",
2350:" ",
2400:" ",
2450:" ",
2500:"ТО500",
2550:" ",
2600:" ",
2650:" ",
2700:" ",
2750:"",
2800:" ",
2850:" ",
2900:" ",
2950:" ",
3000:"ТО1000",
3050:" ",
3100:" ",
3150:" ",
3200:" ",
3250:"",
3300:" ",
3350:" ",
3400:" ",
3450:" ",
3500:"ТО500",
3550:" ",
3600:" ",
3650:" ",
3700:" ",
3750:"",
3800:" ",
3850:" ",
3900:" ",
3950:" ",
4000:"ТО4000",
4050:" ",
4100:" ",
4150:" ",
4200:" ",
4250:"",
4300:" ",
4350:" ",
4400:" ",
4450:" ",
4500:"ТО500",
4550:" ",
4600:" ",
4650:" ",
4700:" ",
4750:"",
4800:" ",
4850:" ",
4900:" ",
4950:" ",
5000:"ТО1000",
5050:" ",
5100:" ",
5150:" ",
5200:" ",
5250:"",
5300:" ",
5350:" ",
5400:" ",
5450:" ",
5500:"ТО500",
5550:" ",
5600:" ",
5650:" ",
5700:" ",
5750:"",
5800:" ",
5850:" ",
5900:" ",
5950:" ",
6000:"ТО1000",
6050:" ",
6100:" ",
6150:" ",
6200:" ",
6250:"",
6300:" ",
6350:" ",
6400:" ",
6450:" ",
6500:"ТО500",
6550:" ",
6600:" ",
6650:" ",
6700:" ",
6750:"",
6800:" ",
6850:" ",
6900:" ",
6950:" ",
7000:"ТО1000",
7050:" ",
7100:" ",
7150:" ",
7200:" ",
7250:"",
7300:" ",
7350:" ",
7400:" ",
7450:" ",
7500:"ТО500",
7550:" ",
7600:" ",
7650:" ",
7700:" ",
7750:"",
7800:" ",
7850:" ",
7900:" ",
7950:" ",
8000:"ТО4000",
8050:" ",
8100:" ",
8150:" ",
8200:" ",
8250:"",
8300:" ",
8350:" ",
8400:" ",
8450:" ",
8500:"ТО500",
8550:" ",
8600:" ",
8650:" ",
8700:" ",
8750:"",
8800:" ",
8850:" ",
8900:" ",
8950:" ",
9000:"ТО1000",
9050:" ",
9100:" ",
9150:" ",
9200:" ",
9250:"",
9300:" ",
9350:" ",
9400:" ",
9450:" ",
9500:"ТО500",
9550:" ",
9600:" ",
9650:" ",
9700:" ",
9750:"",
9800:" ",
9850:" ",
9900:" ",
9950:" ",
10000:"ТО1000",
10050:" ",
10100:" ",
10150:" ",
10200:" ",
10250:"",
10300:" ",
10350:" ",
10400:" ",
10450:" ",
10500:"ТО500",
10550:" ",
10600:" ",
10650:" ",
10700:" ",
10750:"",
10800:" ",
10850:" ",
10900:" ",
10950:" ",
11000:"ТО1000",
11050:" ",
11100:" ",
11150:" ",
11200:" ",
11250:"",
11300:" ",
11350:" ",
11400:" ",
11450:" ",
11500:"ТО500",
11550:" ",
11600:" ",
11650:" ",
11700:" ",
11750:"",
11800:" ",
11850:" ",
11900:" ",
11950:" ",
12000:"ТО4000",
12050:" ",
12100:" ",
12150:" ",
12200:" ",
12250:"",
12300:" ",
12350:" ",
12400:" ",
12450:" ",
12500:"ТО500",
12550:" ",
12600:" ",
12650:" ",
12700:" ",
12750:"",
12800:" ",
12850:" ",
12900:" ",
12950:" ",
13000:"ТО1000",
13050:" ",
13100:" ",
13150:" ",
13200:" ",
13250:"",
13300:" ",
13350:" ",
13400:" ",
13450:" ",
13500:"ТО500",
13550:" ",
13600:" ",
13650:" ",
13700:" ",
13750:"",
13800:" ",
13850:" ",
13900:" ",
13950:" ",
14000:"ТО1000",
14050:" ",
14100:" ",
14150:" ",
14200:" ",
14250:"",
14300:" ",
14350:" ",
14400:" ",
14450:" ",
14500:"ТО500",
14550:" ",
14600:" ",
14650:" ",
14700:" ",
14750:"",
14800:" ",
14850:" ",
14900:" ",
14950:" ",
15000:"ТО1000",
15050:" ",
15100:" ",
15150:" ",
15200:" ",
15250:"",
15300:" ",
15350:" ",
15400:" ",
15450:" ",
15500:"ТО500",
15550:" ",
15600:" ",
15650:" ",
15700:" ",
15750:"",
15800:" ",
15850:" ",
15900:" ",
15950:" ",
16000:"ТО4000",
16050:" ",
16100:" ",
16150:" ",
16200:" ",
16250:"",
16300:" ",
16350:" ",
16400:" ",
16450:" ",
16500:"ТО500",
16550:" ",
16600:" ",
16650:" ",
16700:" ",
16750:"",
16800:" ",
16850:" ",
16900:" ",
16950:" ",
17000:"ТО1000",
17050:" ",
17100:" ",
17150:" ",
17200:" ",
17250:"",
17300:" ",
17350:" ",
17400:" ",
17450:" ",
17500:"ТО500",
17550:" ",
17600:" ",
17650:" ",
17700:" ",
17750:"",
17800:" ",
17850:" ",
17900:" ",
17950:" ",
18000:"ТО1000",
18050:" ",
18100:" ",
18150:" ",
18200:" ",
18250:"",
18300:" ",
18350:" ",
18400:" ",
18450:" ",
18500:"ТО500",
18550:" ",
18600:" ",
18650:" ",
18700:" ",
18750:"",
18800:" ",
18850:" ",
18900:" ",
18950:" ",
19000:"ТО1000",
19050:" ",
19100:" ",
19150:" ",
19200:" ",
19250:"",
19300:" ",
19350:" ",
19400:" ",
19450:" ",
19500:"ТО500",
19550:" ",
19600:" ",
19650:" ",
19700:" ",
19750:"",
19800:" ",
19850:" ",
19900:" ",
19950:" ",
20000:"ТО4000",
20050:" ",
20100:" ",
20150:" ",
20200:" ",
20250:"",
20300:" ",
20350:" ",
20400:" ",
20450:" ",
20500:"ТО500",
20550:" ",
20600:" ",
20650:" ",
20700:" ",
20750:"",
20800:" ",
20850:" ",
20900:" ",
20950:" ",
21000:"ТО1000",
21050:" ",
21100:" ",
21150:" ",
21200:" ",
21250:"",
21300:" ",
21350:" ",
21400:" ",
21450:" ",
21500:"ТО500",
21550:" ",
21600:" ",
21650:" ",
21700:" ",
21750:"",
21800:" ",
21850:" ",
21900:" ",
21950:" ",
22000:"ТО2000",
22050:" ",
22100:" ",
22150:" ",
22200:" ",
22250:"",
22300:" ",
22350:" ",
22400:" ",
22450:" ",
22500:"ТО500",
22550:" ",
22600:" ",
22650:" ",
22700:" ",
22750:"",
22800:" ",
22850:" ",
22900:" ",
22950:" ",
23000:"ТО1000",
23050:" ",
23100:" ",
23150:" ",
23200:" ",
23250:"",
23300:" ",
23350:" ",
23400:" ",
23450:" ",
23500:"ТО500",
23550:" ",
23600:" ",
23650:" ",
23700:" ",
23750:"",
23800:" ",
23850:" ",
23900:" ",
23950:" ",
24000:"ТО4000",
24050:" ",
24100:" ",
24150:" ",
24200:" ",
24250:"",
24300:" ",
24350:" ",
24400:" ",
24450:" ",
24500:"ТО500",
24550:" ",
24600:" ",
24650:" ",
24700:" ",
24750:"",
24800:" ",
24850:" ",
24900:" ",
24950:" ",
25000:"ТО1000",
25050:" ",
25100:" ",
25150:" ",
25200:" ",
25250:"",
25300:" ",
25350:" ",
25400:" ",
25450:" ",
25500:"ТО500",
25550:" ",
25600:" ",
25650:" ",
25700:" ",
25750:"",
25800:" ",
25850:" ",
25900:" ",
25950:" ",
26000:"ТО2000",
26050:" ",
26100:" ",
26150:" ",
26200:" ",
26250:"",
26300:" ",
26350:" ",
26400:" ",
26450:" ",
26500:"ТО500",
26550:" ",
26600:" ",
26650:" ",
26700:" ",
26750:"",
26800:" ",
26850:" ",
26900:" ",
26950:" ",
27000:"ТО1000",
27050:" ",
27100:" ",
27150:" ",
27200:" ",
27250:"",
27300:" ",
27350:" ",
27400:" ",
27450:" ",
27500:"ТО500",
27550:" ",
27600:" ",
27650:" ",
27700:" ",
27750:"",
27800:" ",
27850:" ",
27900:" ",
27950:" ",
28000:"ТО4000",
28050:" ",
28100:" ",
28150:" ",
28200:" ",
28250:"",
28300:" ",
28350:" ",
28400:" ",
28450:" ",
28500:"ТО500",
28550:" ",
28600:" ",
28650:" ",
28700:" ",
28750:"",
28800:" ",
28850:" ",
28900:" ",
28950:" ",
29000:"ТО500",
29050:" ",
29100:" ",
29150:" ",
29200:" ",
29250:"",
29300:" ",
29350:" ",
29400:" ",
29450:" ",
29500:"ТО500",
29550:" ",
29600:" ",
29650:" ",
29700:" ",
29750:"",
29800:" ",
29850:" ",
29900:" ",
29950:" ",
30000:"ТО1000",
30050:" ",
30100:" ",
30150:" ",
30200:" ",
30250:"",
30300:" ",
30350:" ",
30400:" ",
30450:" ",
30500:"ТО500",
30550:" ",
30600:" ",
30650:" ",
30700:" ",
30750:"",
30800:" ",
30850:" ",
30900:" ",
30950:" ",
31000:"ТО1000",
31050:" ",
31100:" ",
31150:" ",
31200:" ",
31250:"",
31300:" ",
31350:" ",
31400:" ",
31450:" ",
31500:"ТО500",
31550:" ",
31600:" ",
31650:" ",
31700:" ",
31750:"",
31800:" ",
31850:" ",
31900:" ",
31950:" ",
32000:"ТО4000",
32050:" ",
32100:" ",
32150:" ",
32200:" ",
32250:"",
32300:" ",
32350:" ",
32400:" ",
32450:" ",
32500:"ТО500",
32550:" ",
32600:" ",
32650:" ",
32700:" ",
32750:"",
32800:" ",
32850:" ",
32900:" ",
32950:" ",
33000:"ТО1000",
33050:" ",
33100:" ",
33150:" ",
33200:" ",
33250:"",
33300:" ",
33350:" ",
33400:" ",
33450:" ",
33500:"ТО500",
33550:" ",
33600:" ",
33650:" ",
33700:" ",
33750:"",
33800:" ",
33850:" ",
33900:" ",
33950:" ",
34000:"ТО2000",
34050:" ",
34100:" ",
34150:" ",
34200:" ",
34250:"",
34300:" ",
34350:" ",
34400:" ",
34450:" ",
34500:"ТО500",
34550:" ",
34600:" ",
34650:" ",
34700:" ",
34750:"",
34800:" ",
34850:" ",
34900:" ",
34950:" ",
35000:"ТО1000",
35050:" ",
35100:" ",
35150:" ",
35200:" ",
35250:"",
35300:" ",
35350:" ",
35400:" ",
35450:" ",
35500:"ТО500",
35550:" ",
35600:" ",
35650:" ",
35700:" ",
35750:"",
35800:" ",
35850:" ",
35900:" ",
35950:" ",
36000:"ТО4000",
36050:" ",
36100:" ",
36150:" ",
36200:" ",
36250:"",
36300:" ",
36350:" ",
36400:" ",
36450:" ",
36500:"ТО500",
36550:" ",
36600:" ",
36650:" ",
36700:" ",
36750:"",
36800:" ",
36850:" ",
36900:" ",
36950:" ",
37000:"ТО1000",
37050:" ",
37100:" ",
37150:" ",
37200:" ",
37250:"",
37300:" ",
37350:" ",
37400:" ",
37450:" ",
37500:"ТО500",
37550:" ",
37600:" ",
37650:" ",
37700:" ",
37750:"",
37800:" ",
37850:" ",
37900:" ",
37950:" ",
38000:"ТО2000",
38050:" ",
38100:" ",
38150:" ",
38200:" ",
38250:"",
38300:" ",
38350:" ",
38400:" ",
38450:" ",
38500:"ТО500",
38550:" ",
38600:" ",
38650:" ",
38700:" ",
38750:"",
38800:" ",
38850:" ",
38900:" ",
38950:" ",
39000:"ТО1000",
39050:" ",
39100:" ",
39150:" ",
39200:" ",
39250:"",
39300:" ",
39350:" ",
39400:" ",
39450:" ",
39500:"ТО500",
39550:" ",
39600:" ",
39650:" ",
39700:" ",
39750:"",
39800:" ",
39850:" ",
39900:" ",
39950:" ",
40000:"ТО4000",
40050:" ",
40100:" ",
40150:" ",
40200:" ",
40250:"",
40300:" ",
40350:" ",
40400:" ",
40450:" ",
40500:"ТО500",
40550:" ",
40600:" ",
40650:" ",
40700:" ",
40750:"",
40800:" ",
40850:" ",
40900:" ",
40950:" ",
41000:"ТО1000",
41050:" ",
41100:" ",
41150:" ",
41200:" ",
41250:"",
41300:" ",
41350:" ",
41400:" ",
41450:" ",
41500:"ТО500",
41550:" ",
41600:" ",
41650:" ",
41700:" ",
41750:"",
41800:" ",
41850:" ",
41900:" ",
41950:" ",
42000:"ТО1000",
42050:" ",
42100:" ",
42150:" ",
42200:" ",
42250:"",
42300:" ",
42350:" ",
42400:" ",
42450:" ",
42500:"ТО500",
42550:" ",
42600:" ",
42650:" ",
42700:" ",
42750:"",
42800:" ",
42850:" ",
42900:" ",
42950:" ",
43000:"ТО1000",
43050:" ",
43100:" ",
43150:" ",
43200:" ",
43250:"",
43300:" ",
43350:" ",
43400:" ",
43450:" ",
43500:"ТО500",
43550:" ",
43600:" ",
43650:" ",
43700:" ",
43750:"",
43800:" ",
43850:" ",
43900:" ",
43950:" ",
44000:"ТО4000",
44050:" ",
44100:" ",
44150:" ",
44200:" ",
44250:"",
44300:" ",
44350:" ",
44400:" ",
44450:" ",
44500:"ТО500",
44550:" ",
44600:" ",
44650:" ",
44700:" ",
44750:"",
44800:" ",
44850:" ",
44900:" ",
44950:" ",
45000:"ТО1000",
45050:" ",
45100:" ",
45150:" ",
45200:" ",
45250:"",
45300:" ",
45350:" ",
45400:" ",
45450:" ",
45500:"ТО500",
45550:" ",
45600:" ",
45650:" ",
45700:" ",
45750:"",
45800:" ",
45850:" ",
45900:" ",
45950:" ",
46000:"ТО2000",
46050:" ",
46100:" ",
46150:" ",
46200:" ",
46250:"",
46300:" ",
46350:" ",
46400:" ",
46450:" ",
46500:"ТО500",
46550:" ",
46600:" ",
46650:" ",
46700:" ",
46750:"",
46800:" ",
46850:" ",
46900:" ",
46950:" ",
47000:"ТО1000",
47050:" ",
47100:" ",
47150:" ",
47200:" ",
47250:"",
47300:" ",
47350:" ",
47400:" ",
47450:" ",
47500:"ТО500",
47550:" ",
47600:" ",
47650:" ",
47700:" ",
47750:"",
47800:" ",
47850:" ",
47900:" ",
47950:" ",
48000:"ТО4000"

    
}

In [73]:
to_DNUDo_1600={
   50:"",
100:"",
150:"",
200:"ТО200",
250:"",
300:" ",
350:" ",
400:"ТО400",
450:" ",
500:"",
550:" ",
600:"ТО200",
650:" ",
700:" ",
750:"",
800:"ТО400",
850:" ",
900:" ",
950:" ",
1000:"ТО200",
1050:" ",
1100:" ",
1150:" ",
1200:"ТО400",
1250:"",
1300:" ",
1350:" ",
1400:" ",
1450:"ТО200",
1500:"",
1550:" ",
1600:"ТО1600 ",
1650:" ",
1700:" ",
1750:"",
1800:"ТО200",
1850:" ",
1900:" ",
1950:" ",
2000:"ТО400",
2050:" ",
2100:" ",
2150:" ",
2200:"ТО200",
2250:"",
2300:" ",
2350:" ",
2400:"ТО400",
2450:" ",
2500:"",
2550:" ",
2600:"ТО200",
2650:" ",
2700:" ",
2750:"",
2800:"ТО400",
2850:" ",
2900:" ",
2950:" ",
3000:"ТО200",
3050:" ",
3100:" ",
3150:" ",
3200:"ТО3200",
3250:"",
3300:" ",
3350:" ",
3400:"ТО200",
3450:" ",
3500:"",
3550:" ",
3600:"ТО400",
3650:" ",
3700:" ",
3750:"",
3800:"ТО200",
3850:" ",
3900:" ",
3950:" ",
4000:"ТО4000",
4050:" ",
4100:" ",
4150:" ",
4200:"ТО200",
4250:"",
4300:" ",
4350:" ",
4400:"ТО400",
4450:" ",
4500:"",
4550:" ",
4600:"ТО200",
4650:" ",
4700:" ",
4750:"",
4800:"ТО400",
4850:" ",
4900:" ",
4950:" ",
5000:"",
5050:" ",
5100:" ",
5150:" ",
5200:" ",
5250:"",
5300:" ",
5350:" ",
5400:" ",
5450:" ",
5500:" ",
5550:" ",
5600:" ",
5650:" ",
5700:" ",
5750:"",
5800:" ",
5850:" ",
5900:" ",
5950:" ",
6000:" ",
6050:" ",
6100:" ",
6150:" ",
6200:" ",
6250:"",
6300:" ",
6350:" ",
6400:" ",
6450:" ",
6500:" ",
6550:" ",
6600:" ",
6650:" ",
6700:" ",
6750:"",
6800:" ",
6850:" ",
6900:" ",
6950:" ",
7000:" ",
7050:" ",
7100:" ",
7150:" ",
7200:" ",
7250:"",
7300:" ",
7350:" ",
7400:" ",
7450:" ",
7500:" ",
7550:" ",
7600:" ",
7650:" ",
7700:" ",
7750:"",
7800:" ",
7850:" ",
7900:" ",
7950:" ",
8000:" ",
8050:" ",
8100:" ",
8150:" ",
8200:" ",
8250:"",
8300:" ",
8350:" ",
8400:" ",
8450:" ",
8500:" ",
8550:" ",
8600:" ",
8650:" ",
8700:" ",
8750:"",
8800:" ",
8850:" ",
8900:" ",
8950:" ",
9000:" ",
9050:" ",
9100:" ",
9150:" ",
9200:" ",
9250:"",
9300:" ",
9350:" ",
9400:" ",
9450:" ",
9500:" ",
9550:" ",
9600:" ",
9650:" ",
9700:" ",
9750:"",
9800:" ",
9850:" ",
9900:" ",
9950:" ",
10000:" ",
10050:" ",
10100:" ",
10150:" ",
10200:" ",
10250:"",
10300:" ",
10350:" ",
10400:" ",
10450:" ",
10500:" ",
10550:" ",
10600:" ",
10650:" ",
10700:" ",
10750:"",
10800:" ",
10850:" ",
10900:" ",
10950:" ",
11000:" ",
11050:" ",
11100:" ",
11150:" ",
11200:" ",
11250:"",
11300:" ",
11350:" ",
11400:" ",
11450:" ",
11500:" ",
11550:" ",
11600:" ",
11650:" ",
11700:" ",
11750:"",
11800:" ",
11850:" ",
11900:" ",
11950:" ",
12000:" ",
12050:" ",
12100:" ",
12150:" ",
12200:" ",
12250:"",
12300:" ",
12350:" ",
12400:" ",
12450:" ",
12500:" ",
12550:" ",
12600:" ",
12650:" ",
12700:" ",
12750:"",
12800:" ",
12850:" ",
12900:" ",
12950:" ",
13000:" ",
13050:" ",
13100:" ",
13150:" ",
13200:" ",
13250:"",
13300:" ",
13350:" ",
13400:" ",
13450:" ",
13500:" ",
13550:" ",
13600:" ",
13650:" ",
13700:" ",
13750:"",
13800:" ",
13850:" ",
13900:" ",
13950:" ",
14000:" ",
14050:" ",
14100:" ",
14150:" ",
14200:" ",
14250:"",
14300:" ",
14350:" ",
14400:" ",
14450:" ",
14500:" ",
14550:" ",
14600:" ",
14650:" ",
14700:" ",
14750:"",
14800:" ",
14850:" ",
14900:" ",
14950:" ",
15000:" ",
15050:" ",
15100:" ",
15150:" ",
15200:" ",
15250:"",
15300:" ",
15350:" ",
15400:" ",
15450:" ",
15500:" ",
15550:" ",
15600:" ",
15650:" ",
15700:" ",
15750:"",
15800:" ",
15850:" ",
15900:" ",
15950:" ",
16000:" ",
16050:" ",
16100:" ",
16150:" ",
16200:" ",
16250:"",
16300:" ",
16350:" ",
16400:" ",
16450:" ",
16500:" ",
16550:" ",
16600:" ",
16650:" ",
16700:" ",
16750:"",
16800:" ",
16850:" ",
16900:" ",
16950:" ",
17000:" ",
17050:" ",
17100:" ",
17150:" ",
17200:" ",
17250:"",
17300:" ",
17350:" ",
17400:" ",
17450:" ",
17500:" ",
17550:" ",
17600:" ",
17650:" ",
17700:" ",
17750:"",
17800:" ",
17850:" ",
17900:" ",
17950:" ",
18000:" ",
18050:" ",
18100:" ",
18150:" ",
18200:" ",
18250:"",
18300:" ",
18350:" ",
18400:" ",
18450:" ",
18500:" ",
18550:" ",
18600:" ",
18650:" ",
18700:" ",
18750:"",
18800:" ",
18850:" ",
18900:" ",
18950:" ",
19000:" ",
19050:" ",
19100:" ",
19150:" ",
19200:" ",
19250:"",
19300:" ",
19350:" ",
19400:" ",
19450:" ",
19500:" ",
19550:" ",
19600:" ",
19650:" ",
19700:" ",
19750:"",
19800:" ",
19850:" ",
19900:" ",
19950:" ",
20000:" ",
20050:" ",
20100:" ",
20150:" ",
20200:" ",
20250:"",
20300:" ",
20350:" ",
20400:" ",
20450:" ",
20500:" ",
20550:" ",
20600:" ",
20650:" ",
20700:" ",
20750:"",
20800:" ",
20850:" ",
20900:" ",
20950:" ",
21000:" ",
21050:" ",
21100:" ",
21150:" ",
21200:" ",
21250:"",
21300:" ",
21350:" ",
21400:" ",
21450:" ",
21500:" ",
21550:" ",
21600:" ",
21650:" ",
21700:" ",
21750:"",
21800:" ",
21850:" ",
21900:" ",
21950:" ",
22000:" ",
22050:" ",
22100:" ",
22150:" ",
22200:" ",
22250:"",
22300:" ",
22350:" ",
22400:" ",
22450:" ",
22500:" ",
22550:" ",
22600:" ",
22650:" ",
22700:" ",
22750:"",
22800:" ",
22850:" ",
22900:" ",
22950:" ",
23000:" ",
23050:" ",
23100:" ",
23150:" ",
23200:" ",
23250:"",
23300:" ",
23350:" ",
23400:" ",
23450:" ",
23500:" ",
23550:" ",
23600:" ",
23650:" ",
23700:" ",
23750:"",
23800:" ",
23850:" ",
23900:" ",
23950:" ",
24000:" ",
24050:" ",
24100:" ",
24150:" ",
24200:" ",
24250:"",
24300:" ",
24350:" ",
24400:" ",
24450:" ",
24500:" ",
24550:" ",
24600:" ",
24650:" ",
24700:" ",
24750:"",
24800:" ",
24850:" ",
24900:" ",
24950:" ",
25000:" ",
25050:" ",
25100:" ",
25150:" ",
25200:" ",
25250:"",
25300:" ",
25350:" ",
25400:" ",
25450:" ",
25500:" ",
25550:" ",
25600:" ",
25650:" ",
25700:" ",
25750:"",
25800:" ",
25850:" ",
25900:" ",
25950:" ",
26000:" ",
26050:" ",
26100:" ",
26150:" ",
26200:" ",
26250:"",
26300:" ",
26350:" ",
26400:" ",
26450:" ",
26500:" ",
26550:" ",
26600:" ",
26650:" ",
26700:" ",
26750:"",
26800:" ",
26850:" ",
26900:" ",
26950:" ",
27000:" ",
27050:" ",
27100:" ",
27150:" ",
27200:" ",
27250:"",
27300:" ",
27350:" ",
27400:" ",
27450:" ",
27500:" ",
27550:" ",
27600:" ",
27650:" ",
27700:" ",
27750:"",
27800:" ",
27850:" ",
27900:" ",
27950:" ",
28000:" ",
28050:" ",
28100:" ",
28150:" ",
28200:" ",
28250:"",
28300:" ",
28350:" ",
28400:" ",
28450:" ",
28500:" ",
28550:" ",
28600:" ",
28650:" ",
28700:" ",
28750:"",
28800:" ",
28850:" ",
28900:" ",
28950:" ",
29000:" ",
29050:" ",
29100:" ",
29150:" ",
29200:" ",
29250:"",
29300:" ",
29350:" ",
29400:" ",
29450:" ",
29500:" ",
29550:" ",
29600:" ",
29650:" ",
29700:" ",
29750:"",
29800:" ",
29850:" ",
29900:" ",
29950:" ",
30000:" ",
30050:" ",
30100:" ",
30150:" ",
30200:" ",
30250:"",
30300:" ",
30350:" ",
30400:" ",
30450:" ",
30500:" ",
30550:" ",
30600:" ",
30650:" ",
30700:" ",
30750:"",
30800:" ",
30850:" ",
30900:" ",
30950:" ",
31000:" ",
31050:" ",
31100:" ",
31150:" ",
31200:" ",
31250:"",
31300:" ",
31350:" ",
31400:" ",
31450:" ",
31500:" ",
31550:" ",
31600:" ",
31650:" ",
31700:" ",
31750:"",
31800:" ",
31850:" ",
31900:" ",
31950:" ",
32000:" ",
32050:" ",
32100:" ",
32150:" ",
32200:" ",
32250:"",
32300:" ",
32350:" ",
32400:" ",
32450:" ",
32500:" ",
32550:" ",
32600:" ",
32650:" ",
32700:" ",
32750:"",
32800:" ",
32850:" ",
32900:" ",
32950:" ",
33000:" ",
33050:" ",
33100:" ",
33150:" ",
33200:" ",
33250:"",
33300:" ",
33350:" ",
33400:" ",
33450:" ",
33500:" ",
33550:" ",
33600:" ",
33650:" ",
33700:" ",
33750:"",
33800:" ",
33850:" ",
33900:" ",
33950:" ",
34000:" ",
34050:" ",
34100:" ",
34150:" ",
34200:" ",
34250:"",
34300:" ",
34350:" ",
34400:" ",
34450:" ",
34500:" ",
34550:" ",
34600:" ",
34650:" ",
34700:" ",
34750:"",
34800:" ",
34850:" ",
34900:" ",
34950:" ",
35000:" ",
35050:" ",
35100:" ",
35150:" ",
35200:" ",
35250:"",
35300:" ",
35350:" ",
35400:" ",
35450:" ",
35500:" ",
35550:" ",
35600:" ",
35650:" ",
35700:" ",
35750:"",
35800:" ",
35850:" ",
35900:" ",
35950:" ",
36000:" ",
36050:" ",
36100:" ",
36150:" ",
36200:" ",
36250:"",
36300:" ",
36350:" ",
36400:" ",
36450:" ",
36500:" ",
36550:" ",
36600:" ",
36650:" ",
36700:" ",
36750:"",
36800:" ",
36850:" ",
36900:" ",
36950:" ",
37000:" ",
37050:" ",
37100:" ",
37150:" ",
37200:" ",
37250:"",
37300:" ",
37350:" ",
37400:" ",
37450:" ",
37500:" ",
37550:" ",
37600:" ",
37650:" ",
37700:" ",
37750:"",
37800:" ",
37850:" ",
37900:" ",
37950:" ",
38000:" ",
38050:" ",
38100:" ",
38150:" ",
38200:" ",
38250:"",
38300:" ",
38350:" ",
38400:" ",
38450:" ",
38500:" ",
38550:" ",
38600:" ",
38650:" ",
38700:" ",
38750:"",
38800:" ",
38850:" ",
38900:" ",
38950:" ",
39000:" ",
39050:" ",
39100:" ",
39150:" ",
39200:" ",
39250:"",
39300:" ",
39350:" ",
39400:" ",
39450:" ",
39500:" ",
39550:" ",
39600:" ",
39650:" ",
39700:" ",
39750:"",
39800:" ",
39850:" ",
39900:" ",
39950:" ",
40000:" ",
40050:" ",
40100:" ",
40150:" ",
40200:" ",
40250:"",
40300:" ",
40350:" ",
40400:" ",
40450:" ",
40500:" ",
40550:" ",
40600:" ",
40650:" ",
40700:" ",
40750:"",
40800:" ",
40850:" ",
40900:" ",
40950:" ",
41000:" ",
41050:" ",
41100:" ",
41150:" ",
41200:" ",
41250:"",
41300:" ",
41350:" ",
41400:" ",
41450:" ",
41500:" ",
41550:" ",
41600:" ",
41650:" ",
41700:" ",
41750:"",
41800:" ",
41850:" ",
41900:" ",
41950:" ",
42000:" ",
42050:" ",
42100:" ",
42150:" ",
42200:" ",
42250:"",
42300:" ",
42350:" ",
42400:" ",
42450:" ",
42500:" ",
42550:" ",
42600:" ",
42650:" ",
42700:" ",
42750:"",
42800:" ",
42850:" ",
42900:" ",
42950:" ",
43000:" ",
43050:" ",
43100:" ",
43150:" ",
43200:" ",
43250:"",
43300:" ",
43350:" ",
43400:" ",
43450:" ",
43500:" ",
43550:" ",
43600:" ",
43650:" ",
43700:" ",
43750:"",
43800:" ",
43850:" ",
43900:" ",
43950:" ",
44000:" ",
44050:" ",
44100:" ",
44150:" ",
44200:" ",
44250:"",
44300:" ",
44350:" ",
44400:" ",
44450:" ",
44500:" ",
44550:" ",
44600:" ",
44650:" ",
44700:" ",
44750:"",
44800:" ",
44850:" ",
44900:" ",
44950:" ",
45000:" ",
45050:" ",
45100:" ",
45150:" ",
45200:" ",
45250:"",
45300:" ",
45350:" ",
45400:" ",
45450:" ",
45500:" ",
45550:" ",
45600:" ",
45650:" ",
45700:" ",
45750:"",
45800:" ",
45850:" ",
45900:" ",
45950:" ",
46000:" ",
46050:" ",
46100:" ",
46150:" ",
46200:" ",
46250:"",
46300:" ",
46350:" ",
46400:" ",
46450:" ",
46500:" ",
46550:" ",
46600:" ",
46650:" ",
46700:" ",
46750:"",
46800:" ",
46850:" ",
46900:" ",
46950:" ",
47000:" ",
47050:" ",
47100:" ",
47150:" ",
47200:" ",
47250:"",
47300:" ",
47350:" ",
47400:" ",
47450:" ",
47500:" ",
47550:" ",
47600:" ",
47650:" ",
47700:" ",
47750:"",
47800:" ",
47850:" ",
47900:" ",
47950:" ",
48000:" ",

    
}

In [74]:
to_DHC_CB_320_22={
   50:"",
100:"",
150:"",
200:"",
250:"ТО250",
300:" ",
350:" ",
400:"",
450:" ",
500:"ТО500",
550:" ",
600:"",
650:" ",
700:" ",
750:"ТО250",
800:"",
850:" ",
900:" ",
950:" ",
1000:"ТО1000",
1050:" ",
1100:" ",
1150:" ",
1200:"",
1250:"ТО250",
1300:" ",
1350:" ",
1400:" ",
1450:"",
1500:"ТО500",
1550:" ",
1600:"",
1650:" ",
1700:" ",
1750:"ТО250",
1800:"",
1850:" ",
1900:" ",
1950:" ",
2000:"ТО2000",
2050:" ",
2100:" ",
2150:" ",
2200:"",
2250:"ТО250",
2300:" ",
2350:" ",
2400:"",
2450:" ",
2500:"ТО500",
2550:" ",
2600:"",
2650:" ",
2700:" ",
2750:"ТО250",
2800:"",
2850:" ",
2900:" ",
2950:" ",
3000:"ТО3000",
3050:" ",
3100:" ",
3150:" ",
3200:"",
3250:"ТО250",
3300:" ",
3350:" ",
3400:"",
3450:" ",
3500:"ТО500",
3550:" ",
3600:"",
3650:" ",
3700:" ",
3750:"ТО250",
3800:"",
3850:" ",
3900:" ",
3950:" ",
4000:"ТО2000",
4050:" ",
4100:" ",
4150:" ",
4200:"",
4250:"ТО250",
4300:" ",
4350:" ",
4400:"",
4450:" ",
4500:"ТО500",
4550:" ",
4600:"",
4650:" ",
4700:" ",
4750:"ТО250",
4800:"",
4850:" ",
4900:" ",
4950:" ",
5000:"ТО1000",
5050:" ",
5100:" ",
5150:" ",
5200:" ",
5250:"ТО250",
5300:" ",
5350:" ",
5400:" ",
5450:" ",
5500:"ТО500",
5550:" ",
5600:" ",
5650:" ",
5700:" ",
5750:"ТО250",
5800:" ",
5850:" ",
5900:" ",
5950:" ",
6000:"ТО3000",
6050:" ",
6100:" ",
6150:" ",
6200:" ",
6250:"ТО250",
6300:" ",
6350:" ",
6400:" ",
6450:" ",
6500:"ТО500",
6550:" ",
6600:" ",
6650:" ",
6700:" ",
6750:"ТО250",
6800:" ",
6850:" ",
6900:" ",
6950:" ",
7000:"ТО1000",
7050:" ",
7100:" ",
7150:" ",
7200:" ",
7250:"ТО250",
7300:" ",
7350:" ",
7400:" ",
7450:" ",
7500:"ТО500",
7550:" ",
7600:" ",
7650:" ",
7700:" ",
7750:"ТО250",
7800:" ",
7850:" ",
7900:" ",
7950:" ",
8000:"ТО1000",
8050:" ",
8100:" ",
8150:" ",
8200:" ",
8250:"",
8300:" ",
8350:" ",
8400:" ",
8450:" ",
8500:" ",
8550:" ",
8600:" ",
8650:" ",
8700:" ",
8750:"",
8800:" ",
8850:" ",
8900:" ",
8950:" ",
9000:" ",
9050:" ",
9100:" ",
9150:" ",
9200:" ",
9250:"",
9300:" ",
9350:" ",
9400:" ",
9450:" ",
9500:" ",
9550:" ",
9600:" ",
9650:" ",
9700:" ",
9750:"",
9800:" ",
9850:" ",
9900:" ",
9950:" ",
10000:" ",
10050:" ",
10100:" ",
10150:" ",
10200:" ",
10250:"",
10300:" ",
10350:" ",
10400:" ",
10450:" ",
10500:" ",
10550:" ",
10600:" ",
10650:" ",
10700:" ",
10750:"",
10800:" ",
10850:" ",
10900:" ",
10950:" ",
11000:" ",
11050:" ",
11100:" ",
11150:" ",
11200:" ",
11250:"",
11300:" ",
11350:" ",
11400:" ",
11450:" ",
11500:" ",
11550:" ",
11600:" ",
11650:" ",
11700:" ",
11750:"",
11800:" ",
11850:" ",
11900:" ",
11950:" ",
12000:" ",
12050:" ",
12100:" ",
12150:" ",
12200:" ",
12250:"",
12300:" ",
12350:" ",
12400:" ",
12450:" ",
12500:" ",
12550:" ",
12600:" ",
12650:" ",
12700:" ",
12750:"",
12800:" ",
12850:" ",
12900:" ",
12950:" ",
13000:" ",
13050:" ",
13100:" ",
13150:" ",
13200:" ",
13250:"",
13300:" ",
13350:" ",
13400:" ",
13450:" ",
13500:" ",
13550:" ",
13600:" ",
13650:" ",
13700:" ",
13750:"",
13800:" ",
13850:" ",
13900:" ",
13950:" ",
14000:" ",
14050:" ",
14100:" ",
14150:" ",
14200:" ",
14250:"",
14300:" ",
14350:" ",
14400:" ",
14450:" ",
14500:" ",
14550:" ",
14600:" ",
14650:" ",
14700:" ",
14750:"",
14800:" ",
14850:" ",
14900:" ",
14950:" ",
15000:" ",
15050:" ",
15100:" ",
15150:" ",
15200:" ",
15250:"",
15300:" ",
15350:" ",
15400:" ",
15450:" ",
15500:" ",
15550:" ",
15600:" ",
15650:" ",
15700:" ",
15750:"",
15800:" ",
15850:" ",
15900:" ",
15950:" ",
16000:" ",
16050:" ",
16100:" ",
16150:" ",
16200:" ",
16250:"",
16300:" ",
16350:" ",
16400:" ",
16450:" ",
16500:" ",
16550:" ",
16600:" ",
16650:" ",
16700:" ",
16750:"",
16800:" ",
16850:" ",
16900:" ",
16950:" ",
17000:" ",
17050:" ",
17100:" ",
17150:" ",
17200:" ",
17250:"",
17300:" ",
17350:" ",
17400:" ",
17450:" ",
17500:" ",
17550:" ",
17600:" ",
17650:" ",
17700:" ",
17750:"",
17800:" ",
17850:" ",
17900:" ",
17950:" ",
18000:" ",
18050:" ",
18100:" ",
18150:" ",
18200:" ",
18250:"",
18300:" ",
18350:" ",
18400:" ",
18450:" ",
18500:" ",
18550:" ",
18600:" ",
18650:" ",
18700:" ",
18750:"",
18800:" ",
18850:" ",
18900:" ",
18950:" ",
19000:" ",
19050:" ",
19100:" ",
19150:" ",
19200:" ",
19250:"",
19300:" ",
19350:" ",
19400:" ",
19450:" ",
19500:" ",
19550:" ",
19600:" ",
19650:" ",
19700:" ",
19750:"",
19800:" ",
19850:" ",
19900:" ",
19950:" ",
20000:" ",
20050:" ",
20100:" ",
20150:" ",
20200:" ",
20250:"",
20300:" ",
20350:" ",
20400:" ",
20450:" ",
20500:" ",
20550:" ",
20600:" ",
20650:" ",
20700:" ",
20750:"",
20800:" ",
20850:" ",
20900:" ",
20950:" ",
21000:" ",
21050:" ",
21100:" ",
21150:" ",
21200:" ",
21250:"",
21300:" ",
21350:" ",
21400:" ",
21450:" ",
21500:" ",
21550:" ",
21600:" ",
21650:" ",
21700:" ",
21750:"",
21800:" ",
21850:" ",
21900:" ",
21950:" ",
22000:" ",
22050:" ",
22100:" ",
22150:" ",
22200:" ",
22250:"",
22300:" ",
22350:" ",
22400:" ",
22450:" ",
22500:" ",
22550:" ",
22600:" ",
22650:" ",
22700:" ",
22750:"",
22800:" ",
22850:" ",
22900:" ",
22950:" ",
23000:" ",
23050:" ",
23100:" ",
23150:" ",
23200:" ",
23250:"",
23300:" ",
23350:" ",
23400:" ",
23450:" ",
23500:" ",
23550:" ",
23600:" ",
23650:" ",
23700:" ",
23750:"",
23800:" ",
23850:" ",
23900:" ",
23950:" ",
24000:" ",
24050:" ",
24100:" ",
24150:" ",
24200:" ",
24250:"",
24300:" ",
24350:" ",
24400:" ",
24450:" ",
24500:" ",
24550:" ",
24600:" ",
24650:" ",
24700:" ",
24750:"",
24800:" ",
24850:" ",
24900:" ",
24950:" ",
25000:" ",
25050:" ",
25100:" ",
25150:" ",
25200:" ",
25250:"",
25300:" ",
25350:" ",
25400:" ",
25450:" ",
25500:" ",
25550:" ",
25600:" ",
25650:" ",
25700:" ",
25750:"",
25800:" ",
25850:" ",
25900:" ",
25950:" ",
26000:" ",
26050:" ",
26100:" ",
26150:" ",
26200:" ",
26250:"",
26300:" ",
26350:" ",
26400:" ",
26450:" ",
26500:" ",
26550:" ",
26600:" ",
26650:" ",
26700:" ",
26750:"",
26800:" ",
26850:" ",
26900:" ",
26950:" ",
27000:" ",
27050:" ",
27100:" ",
27150:" ",
27200:" ",
27250:"",
27300:" ",
27350:" ",
27400:" ",
27450:" ",
27500:" ",
27550:" ",
27600:" ",
27650:" ",
27700:" ",
27750:"",
27800:" ",
27850:" ",
27900:" ",
27950:" ",
28000:" ",
28050:" ",
28100:" ",
28150:" ",
28200:" ",
28250:"",
28300:" ",
28350:" ",
28400:" ",
28450:" ",
28500:" ",
28550:" ",
28600:" ",
28650:" ",
28700:" ",
28750:"",
28800:" ",
28850:" ",
28900:" ",
28950:" ",
29000:" ",
29050:" ",
29100:" ",
29150:" ",
29200:" ",
29250:"",
29300:" ",
29350:" ",
29400:" ",
29450:" ",
29500:" ",
29550:" ",
29600:" ",
29650:" ",
29700:" ",
29750:"",
29800:" ",
29850:" ",
29900:" ",
29950:" ",
30000:" ",
30050:" ",
30100:" ",
30150:" ",
30200:" ",
30250:"",
30300:" ",
30350:" ",
30400:" ",
30450:" ",
30500:" ",
30550:" ",
30600:" ",
30650:" ",
30700:" ",
30750:"",
30800:" ",
30850:" ",
30900:" ",
30950:" ",
31000:" ",
31050:" ",
31100:" ",
31150:" ",
31200:" ",
31250:"",
31300:" ",
31350:" ",
31400:" ",
31450:" ",
31500:" ",
31550:" ",
31600:" ",
31650:" ",
31700:" ",
31750:"",
31800:" ",
31850:" ",
31900:" ",
31950:" ",
32000:" ",
32050:" ",
32100:" ",
32150:" ",
32200:" ",
32250:"",
32300:" ",
32350:" ",
32400:" ",
32450:" ",
32500:" ",
32550:" ",
32600:" ",
32650:" ",
32700:" ",
32750:"",
32800:" ",
32850:" ",
32900:" ",
32950:" ",
33000:" ",
33050:" ",
33100:" ",
33150:" ",
33200:" ",
33250:"",
33300:" ",
33350:" ",
33400:" ",
33450:" ",
33500:" ",
33550:" ",
33600:" ",
33650:" ",
33700:" ",
33750:"",
33800:" ",
33850:" ",
33900:" ",
33950:" ",
34000:" ",
34050:" ",
34100:" ",
34150:" ",
34200:" ",
34250:"",
34300:" ",
34350:" ",
34400:" ",
34450:" ",
34500:" ",
34550:" ",
34600:" ",
34650:" ",
34700:" ",
34750:"",
34800:" ",
34850:" ",
34900:" ",
34950:" ",
35000:" ",
35050:" ",
35100:" ",
35150:" ",
35200:" ",
35250:"",
35300:" ",
35350:" ",
35400:" ",
35450:" ",
35500:" ",
35550:" ",
35600:" ",
35650:" ",
35700:" ",
35750:"",
35800:" ",
35850:" ",
35900:" ",
35950:" ",
36000:" ",
36050:" ",
36100:" ",
36150:" ",
36200:" ",
36250:"",
36300:" ",
36350:" ",
36400:" ",
36450:" ",
36500:" ",
36550:" ",
36600:" ",
36650:" ",
36700:" ",
36750:"",
36800:" ",
36850:" ",
36900:" ",
36950:" ",
37000:" ",
37050:" ",
37100:" ",
37150:" ",
37200:" ",
37250:"",
37300:" ",
37350:" ",
37400:" ",
37450:" ",
37500:" ",
37550:" ",
37600:" ",
37650:" ",
37700:" ",
37750:"",
37800:" ",
37850:" ",
37900:" ",
37950:" ",
38000:" ",
38050:" ",
38100:" ",
38150:" ",
38200:" ",
38250:"",
38300:" ",
38350:" ",
38400:" ",
38450:" ",
38500:" ",
38550:" ",
38600:" ",
38650:" ",
38700:" ",
38750:"",
38800:" ",
38850:" ",
38900:" ",
38950:" ",
39000:" ",
39050:" ",
39100:" ",
39150:" ",
39200:" ",
39250:"",
39300:" ",
39350:" ",
39400:" ",
39450:" ",
39500:" ",
39550:" ",
39600:" ",
39650:" ",
39700:" ",
39750:"",
39800:" ",
39850:" ",
39900:" ",
39950:" ",
40000:" ",
40050:" ",
40100:" ",
40150:" ",
40200:" ",
40250:"",
40300:" ",
40350:" ",
40400:" ",
40450:" ",
40500:" ",
40550:" ",
40600:" ",
40650:" ",
40700:" ",
40750:"",
40800:" ",
40850:" ",
40900:" ",
40950:" ",
41000:" ",
41050:" ",
41100:" ",
41150:" ",
41200:" ",
41250:"",
41300:" ",
41350:" ",
41400:" ",
41450:" ",
41500:" ",
41550:" ",
41600:" ",
41650:" ",
41700:" ",
41750:"",
41800:" ",
41850:" ",
41900:" ",
41950:" ",
42000:" ",
42050:" ",
42100:" ",
42150:" ",
42200:" ",
42250:"",
42300:" ",
42350:" ",
42400:" ",
42450:" ",
42500:" ",
42550:" ",
42600:" ",
42650:" ",
42700:" ",
42750:"",
42800:" ",
42850:" ",
42900:" ",
42950:" ",
43000:" ",
43050:" ",
43100:" ",
43150:" ",
43200:" ",
43250:"",
43300:" ",
43350:" ",
43400:" ",
43450:" ",
43500:" ",
43550:" ",
43600:" ",
43650:" ",
43700:" ",
43750:"",
43800:" ",
43850:" ",
43900:" ",
43950:" ",
44000:" ",
44050:" ",
44100:" ",
44150:" ",
44200:" ",
44250:"",
44300:" ",
44350:" ",
44400:" ",
44450:" ",
44500:" ",
44550:" ",
44600:" ",
44650:" ",
44700:" ",
44750:"",
44800:" ",
44850:" ",
44900:" ",
44950:" ",
45000:" ",
45050:" ",
45100:" ",
45150:" ",
45200:" ",
45250:"",
45300:" ",
45350:" ",
45400:" ",
45450:" ",
45500:" ",
45550:" ",
45600:" ",
45650:" ",
45700:" ",
45750:"",
45800:" ",
45850:" ",
45900:" ",
45950:" ",
46000:" ",
46050:" ",
46100:" ",
46150:" ",
46200:" ",
46250:"",
46300:" ",
46350:" ",
46400:" ",
46450:" ",
46500:" ",
46550:" ",
46600:" ",
46650:" ",
46700:" ",
46750:"",
46800:" ",
46850:" ",
46900:" ",
46950:" ",
47000:" ",
47050:" ",
47100:" ",
47150:" ",
47200:" ",
47250:"",
47300:" ",
47350:" ",
47400:" ",
47450:" ",
47500:" ",
47550:" ",
47600:" ",
47650:" ",
47700:" ",
47750:"",
47800:" ",
47850:" ",
47900:" ",
47950:" ",
48000:" ",

    
}

In [75]:
to_DHC_CB_300_20={
   50:"",
100:"",
150:"",
200:"",
250:"ТО250",
300:" ",
350:" ",
400:"",
450:" ",
500:"ТО500",
550:" ",
600:"",
650:" ",
700:" ",
750:"ТО250",
800:"",
850:" ",
900:" ",
950:" ",
1000:"ТО1000",
1050:" ",
1100:" ",
1150:" ",
1200:"",
1250:"ТО250",
1300:" ",
1350:" ",
1400:" ",
1450:"",
1500:"ТО500",
1550:" ",
1600:"",
1650:" ",
1700:" ",
1750:"ТО250",
1800:"",
1850:" ",
1900:" ",
1950:" ",
2000:"ТО2000",
2050:" ",
2100:" ",
2150:" ",
2200:"",
2250:"ТО250",
2300:" ",
2350:" ",
2400:"",
2450:" ",
2500:"ТО500",
2550:" ",
2600:"",
2650:" ",
2700:" ",
2750:"ТО250",
2800:"",
2850:" ",
2900:" ",
2950:" ",
3000:"ТО3000",
3050:" ",
3100:" ",
3150:" ",
3200:"",
3250:"ТО250",
3300:" ",
3350:" ",
3400:"",
3450:" ",
3500:"ТО500",
3550:" ",
3600:"",
3650:" ",
3700:" ",
3750:"ТО250",
3800:"",
3850:" ",
3900:" ",
3950:" ",
4000:"ТО2000",
4050:" ",
4100:" ",
4150:" ",
4200:"",
4250:"ТО250",
4300:" ",
4350:" ",
4400:"",
4450:" ",
4500:"ТО500",
4550:" ",
4600:"",
4650:" ",
4700:" ",
4750:"ТО250",
4800:"",
4850:" ",
4900:" ",
4950:" ",
5000:"ТО1000",
5050:" ",
5100:" ",
5150:" ",
5200:" ",
5250:"ТО250",
5300:" ",
5350:" ",
5400:" ",
5450:" ",
5500:"ТО500",
5550:" ",
5600:" ",
5650:" ",
5700:" ",
5750:"ТО250",
5800:" ",
5850:" ",
5900:" ",
5950:" ",
6000:"ТО3000",
6050:" ",
6100:" ",
6150:" ",
6200:" ",
6250:"ТО250",
6300:" ",
6350:" ",
6400:" ",
6450:" ",
6500:"ТО500",
6550:" ",
6600:" ",
6650:" ",
6700:" ",
6750:"ТО250",
6800:" ",
6850:" ",
6900:" ",
6950:" ",
7000:"ТО1000",
7050:" ",
7100:" ",
7150:" ",
7200:" ",
7250:"ТО250",
7300:" ",
7350:" ",
7400:" ",
7450:" ",
7500:"ТО500",
7550:" ",
7600:" ",
7650:" ",
7700:" ",
7750:"ТО250",
7800:" ",
7850:" ",
7900:" ",
7950:" ",
8000:"ТО1000",
8050:" ",
8100:" ",
8150:" ",
8200:" ",
8250:"",
8300:" ",
8350:" ",
8400:" ",
8450:" ",
8500:" ",
8550:" ",
8600:" ",
8650:" ",
8700:" ",
8750:"",
8800:" ",
8850:" ",
8900:" ",
8950:" ",
9000:" ",
9050:" ",
9100:" ",
9150:" ",
9200:" ",
9250:"",
9300:" ",
9350:" ",
9400:" ",
9450:" ",
9500:" ",
9550:" ",
9600:" ",
9650:" ",
9700:" ",
9750:"",
9800:" ",
9850:" ",
9900:" ",
9950:" ",
10000:" ",
10050:" ",
10100:" ",
10150:" ",
10200:" ",
10250:"",
10300:" ",
10350:" ",
10400:" ",
10450:" ",
10500:" ",
10550:" ",
10600:" ",
10650:" ",
10700:" ",
10750:"",
10800:" ",
10850:" ",
10900:" ",
10950:" ",
11000:" ",
11050:" ",
11100:" ",
11150:" ",
11200:" ",
11250:"",
11300:" ",
11350:" ",
11400:" ",
11450:" ",
11500:" ",
11550:" ",
11600:" ",
11650:" ",
11700:" ",
11750:"",
11800:" ",
11850:" ",
11900:" ",
11950:" ",
12000:" ",
12050:" ",
12100:" ",
12150:" ",
12200:" ",
12250:"",
12300:" ",
12350:" ",
12400:" ",
12450:" ",
12500:" ",
12550:" ",
12600:" ",
12650:" ",
12700:" ",
12750:"",
12800:" ",
12850:" ",
12900:" ",
12950:" ",
13000:" ",
13050:" ",
13100:" ",
13150:" ",
13200:" ",
13250:"",
13300:" ",
13350:" ",
13400:" ",
13450:" ",
13500:" ",
13550:" ",
13600:" ",
13650:" ",
13700:" ",
13750:"",
13800:" ",
13850:" ",
13900:" ",
13950:" ",
14000:" ",
14050:" ",
14100:" ",
14150:" ",
14200:" ",
14250:"",
14300:" ",
14350:" ",
14400:" ",
14450:" ",
14500:" ",
14550:" ",
14600:" ",
14650:" ",
14700:" ",
14750:"",
14800:" ",
14850:" ",
14900:" ",
14950:" ",
15000:" ",
15050:" ",
15100:" ",
15150:" ",
15200:" ",
15250:"",
15300:" ",
15350:" ",
15400:" ",
15450:" ",
15500:" ",
15550:" ",
15600:" ",
15650:" ",
15700:" ",
15750:"",
15800:" ",
15850:" ",
15900:" ",
15950:" ",
16000:" ",
16050:" ",
16100:" ",
16150:" ",
16200:" ",
16250:"",
16300:" ",
16350:" ",
16400:" ",
16450:" ",
16500:" ",
16550:" ",
16600:" ",
16650:" ",
16700:" ",
16750:"",
16800:" ",
16850:" ",
16900:" ",
16950:" ",
17000:" ",
17050:" ",
17100:" ",
17150:" ",
17200:" ",
17250:"",
17300:" ",
17350:" ",
17400:" ",
17450:" ",
17500:" ",
17550:" ",
17600:" ",
17650:" ",
17700:" ",
17750:"",
17800:" ",
17850:" ",
17900:" ",
17950:" ",
18000:" ",
18050:" ",
18100:" ",
18150:" ",
18200:" ",
18250:"",
18300:" ",
18350:" ",
18400:" ",
18450:" ",
18500:" ",
18550:" ",
18600:" ",
18650:" ",
18700:" ",
18750:"",
18800:" ",
18850:" ",
18900:" ",
18950:" ",
19000:" ",
19050:" ",
19100:" ",
19150:" ",
19200:" ",
19250:"",
19300:" ",
19350:" ",
19400:" ",
19450:" ",
19500:" ",
19550:" ",
19600:" ",
19650:" ",
19700:" ",
19750:"",
19800:" ",
19850:" ",
19900:" ",
19950:" ",
20000:" ",
20050:" ",
20100:" ",
20150:" ",
20200:" ",
20250:"",
20300:" ",
20350:" ",
20400:" ",
20450:" ",
20500:" ",
20550:" ",
20600:" ",
20650:" ",
20700:" ",
20750:"",
20800:" ",
20850:" ",
20900:" ",
20950:" ",
21000:" ",
21050:" ",
21100:" ",
21150:" ",
21200:" ",
21250:"",
21300:" ",
21350:" ",
21400:" ",
21450:" ",
21500:" ",
21550:" ",
21600:" ",
21650:" ",
21700:" ",
21750:"",
21800:" ",
21850:" ",
21900:" ",
21950:" ",
22000:" ",
22050:" ",
22100:" ",
22150:" ",
22200:" ",
22250:"",
22300:" ",
22350:" ",
22400:" ",
22450:" ",
22500:" ",
22550:" ",
22600:" ",
22650:" ",
22700:" ",
22750:"",
22800:" ",
22850:" ",
22900:" ",
22950:" ",
23000:" ",
23050:" ",
23100:" ",
23150:" ",
23200:" ",
23250:"",
23300:" ",
23350:" ",
23400:" ",
23450:" ",
23500:" ",
23550:" ",
23600:" ",
23650:" ",
23700:" ",
23750:"",
23800:" ",
23850:" ",
23900:" ",
23950:" ",
24000:" ",
24050:" ",
24100:" ",
24150:" ",
24200:" ",
24250:"",
24300:" ",
24350:" ",
24400:" ",
24450:" ",
24500:" ",
24550:" ",
24600:" ",
24650:" ",
24700:" ",
24750:"",
24800:" ",
24850:" ",
24900:" ",
24950:" ",
25000:" ",
25050:" ",
25100:" ",
25150:" ",
25200:" ",
25250:"",
25300:" ",
25350:" ",
25400:" ",
25450:" ",
25500:" ",
25550:" ",
25600:" ",
25650:" ",
25700:" ",
25750:"",
25800:" ",
25850:" ",
25900:" ",
25950:" ",
26000:" ",
26050:" ",
26100:" ",
26150:" ",
26200:" ",
26250:"",
26300:" ",
26350:" ",
26400:" ",
26450:" ",
26500:" ",
26550:" ",
26600:" ",
26650:" ",
26700:" ",
26750:"",
26800:" ",
26850:" ",
26900:" ",
26950:" ",
27000:" ",
27050:" ",
27100:" ",
27150:" ",
27200:" ",
27250:"",
27300:" ",
27350:" ",
27400:" ",
27450:" ",
27500:" ",
27550:" ",
27600:" ",
27650:" ",
27700:" ",
27750:"",
27800:" ",
27850:" ",
27900:" ",
27950:" ",
28000:" ",
28050:" ",
28100:" ",
28150:" ",
28200:" ",
28250:"",
28300:" ",
28350:" ",
28400:" ",
28450:" ",
28500:" ",
28550:" ",
28600:" ",
28650:" ",
28700:" ",
28750:"",
28800:" ",
28850:" ",
28900:" ",
28950:" ",
29000:" ",
29050:" ",
29100:" ",
29150:" ",
29200:" ",
29250:"",
29300:" ",
29350:" ",
29400:" ",
29450:" ",
29500:" ",
29550:" ",
29600:" ",
29650:" ",
29700:" ",
29750:"",
29800:" ",
29850:" ",
29900:" ",
29950:" ",
30000:" ",
30050:" ",
30100:" ",
30150:" ",
30200:" ",
30250:"",
30300:" ",
30350:" ",
30400:" ",
30450:" ",
30500:" ",
30550:" ",
30600:" ",
30650:" ",
30700:" ",
30750:"",
30800:" ",
30850:" ",
30900:" ",
30950:" ",
31000:" ",
31050:" ",
31100:" ",
31150:" ",
31200:" ",
31250:"",
31300:" ",
31350:" ",
31400:" ",
31450:" ",
31500:" ",
31550:" ",
31600:" ",
31650:" ",
31700:" ",
31750:"",
31800:" ",
31850:" ",
31900:" ",
31950:" ",
32000:" ",
32050:" ",
32100:" ",
32150:" ",
32200:" ",
32250:"",
32300:" ",
32350:" ",
32400:" ",
32450:" ",
32500:" ",
32550:" ",
32600:" ",
32650:" ",
32700:" ",
32750:"",
32800:" ",
32850:" ",
32900:" ",
32950:" ",
33000:" ",
33050:" ",
33100:" ",
33150:" ",
33200:" ",
33250:"",
33300:" ",
33350:" ",
33400:" ",
33450:" ",
33500:" ",
33550:" ",
33600:" ",
33650:" ",
33700:" ",
33750:"",
33800:" ",
33850:" ",
33900:" ",
33950:" ",
34000:" ",
34050:" ",
34100:" ",
34150:" ",
34200:" ",
34250:"",
34300:" ",
34350:" ",
34400:" ",
34450:" ",
34500:" ",
34550:" ",
34600:" ",
34650:" ",
34700:" ",
34750:"",
34800:" ",
34850:" ",
34900:" ",
34950:" ",
35000:" ",
35050:" ",
35100:" ",
35150:" ",
35200:" ",
35250:"",
35300:" ",
35350:" ",
35400:" ",
35450:" ",
35500:" ",
35550:" ",
35600:" ",
35650:" ",
35700:" ",
35750:"",
35800:" ",
35850:" ",
35900:" ",
35950:" ",
36000:" ",
36050:" ",
36100:" ",
36150:" ",
36200:" ",
36250:"",
36300:" ",
36350:" ",
36400:" ",
36450:" ",
36500:" ",
36550:" ",
36600:" ",
36650:" ",
36700:" ",
36750:"",
36800:" ",
36850:" ",
36900:" ",
36950:" ",
37000:" ",
37050:" ",
37100:" ",
37150:" ",
37200:" ",
37250:"",
37300:" ",
37350:" ",
37400:" ",
37450:" ",
37500:" ",
37550:" ",
37600:" ",
37650:" ",
37700:" ",
37750:"",
37800:" ",
37850:" ",
37900:" ",
37950:" ",
38000:" ",
38050:" ",
38100:" ",
38150:" ",
38200:" ",
38250:"",
38300:" ",
38350:" ",
38400:" ",
38450:" ",
38500:" ",
38550:" ",
38600:" ",
38650:" ",
38700:" ",
38750:"",
38800:" ",
38850:" ",
38900:" ",
38950:" ",
39000:" ",
39050:" ",
39100:" ",
39150:" ",
39200:" ",
39250:"",
39300:" ",
39350:" ",
39400:" ",
39450:" ",
39500:" ",
39550:" ",
39600:" ",
39650:" ",
39700:" ",
39750:"",
39800:" ",
39850:" ",
39900:" ",
39950:" ",
40000:" ",
40050:" ",
40100:" ",
40150:" ",
40200:" ",
40250:"",
40300:" ",
40350:" ",
40400:" ",
40450:" ",
40500:" ",
40550:" ",
40600:" ",
40650:" ",
40700:" ",
40750:"",
40800:" ",
40850:" ",
40900:" ",
40950:" ",
41000:" ",
41050:" ",
41100:" ",
41150:" ",
41200:" ",
41250:"",
41300:" ",
41350:" ",
41400:" ",
41450:" ",
41500:" ",
41550:" ",
41600:" ",
41650:" ",
41700:" ",
41750:"",
41800:" ",
41850:" ",
41900:" ",
41950:" ",
42000:" ",
42050:" ",
42100:" ",
42150:" ",
42200:" ",
42250:"",
42300:" ",
42350:" ",
42400:" ",
42450:" ",
42500:" ",
42550:" ",
42600:" ",
42650:" ",
42700:" ",
42750:"",
42800:" ",
42850:" ",
42900:" ",
42950:" ",
43000:" ",
43050:" ",
43100:" ",
43150:" ",
43200:" ",
43250:"",
43300:" ",
43350:" ",
43400:" ",
43450:" ",
43500:" ",
43550:" ",
43600:" ",
43650:" ",
43700:" ",
43750:"",
43800:" ",
43850:" ",
43900:" ",
43950:" ",
44000:" ",
44050:" ",
44100:" ",
44150:" ",
44200:" ",
44250:"",
44300:" ",
44350:" ",
44400:" ",
44450:" ",
44500:" ",
44550:" ",
44600:" ",
44650:" ",
44700:" ",
44750:"",
44800:" ",
44850:" ",
44900:" ",
44950:" ",
45000:" ",
45050:" ",
45100:" ",
45150:" ",
45200:" ",
45250:"",
45300:" ",
45350:" ",
45400:" ",
45450:" ",
45500:" ",
45550:" ",
45600:" ",
45650:" ",
45700:" ",
45750:"",
45800:" ",
45850:" ",
45900:" ",
45950:" ",
46000:" ",
46050:" ",
46100:" ",
46150:" ",
46200:" ",
46250:"",
46300:" ",
46350:" ",
46400:" ",
46450:" ",
46500:" ",
46550:" ",
46600:" ",
46650:" ",
46700:" ",
46750:"",
46800:" ",
46850:" ",
46900:" ",
46950:" ",
47000:" ",
47050:" ",
47100:" ",
47150:" ",
47200:" ",
47250:"",
47300:" ",
47350:" ",
47400:" ",
47450:" ",
47500:" ",
47550:" ",
47600:" ",
47650:" ",
47700:" ",
47750:"",
47800:" ",
47850:" ",
47900:" ",
47950:" ",
48000:" ",

    
}

In [76]:
to_DHU_1250_63={
   50:"",
100:"",
150:"",
200:"",
250:"",
300:" ",
350:" ",
400:"",
450:" ",
500:"ТО500",
550:" ",
600:"",
650:" ",
700:" ",
750:"",
800:"",
850:" ",
900:" ",
950:" ",
1000:"ТО1000",
1050:" ",
1100:" ",
1150:" ",
1200:"",
1250:"",
1300:" ",
1350:" ",
1400:" ",
1450:"",
1500:"ТО500",
1550:" ",
1600:"",
1650:" ",
1700:" ",
1750:"",
1800:"",
1850:" ",
1900:" ",
1950:" ",
2000:"ТО1000",
2050:" ",
2100:" ",
2150:" ",
2200:"",
2250:"",
2300:" ",
2350:" ",
2400:"",
2450:" ",
2500:"ТО500",
2550:" ",
2600:"",
2650:" ",
2700:" ",
2750:"",
2800:"",
2850:" ",
2900:" ",
2950:" ",
3000:"ТО1000",
3050:" ",
3100:" ",
3150:" ",
3200:"",
3250:"",
3300:" ",
3350:" ",
3400:"",
3450:" ",
3500:"ТО500",
3550:" ",
3600:"",
3650:" ",
3700:" ",
3750:"",
3800:"",
3850:" ",
3900:" ",
3950:" ",
4000:"ТО4000",
4050:" ",
4100:" ",
4150:" ",
4200:"",
4250:"",
4300:" ",
4350:" ",
4400:"",
4450:" ",
4500:"ТО500",
4550:" ",
4600:"",
4650:" ",
4700:" ",
4750:"",
4800:"",
4850:" ",
4900:" ",
4950:" ",
5000:"ТО1000",
5050:" ",
5100:" ",
5150:" ",
5200:" ",
5250:"",
5300:" ",
5350:" ",
5400:" ",
5450:" ",
5500:"ТО500",
5550:" ",
5600:" ",
5650:" ",
5700:" ",
5750:"",
5800:" ",
5850:" ",
5900:" ",
5950:" ",
6000:"ТО1000",
6050:" ",
6100:" ",
6150:" ",
6200:" ",
6250:"",
6300:" ",
6350:" ",
6400:" ",
6450:" ",
6500:"ТО500",
6550:" ",
6600:" ",
6650:" ",
6700:" ",
6750:"",
6800:" ",
6850:" ",
6900:" ",
6950:" ",
7000:"ТО1000",
7050:" ",
7100:" ",
7150:" ",
7200:" ",
7250:"",
7300:" ",
7350:" ",
7400:" ",
7450:" ",
7500:"ТО500",
7550:" ",
7600:" ",
7650:" ",
7700:" ",
7750:"",
7800:" ",
7850:" ",
7900:" ",
7950:" ",
8000:"ТО1000",
8050:" ",
8100:" ",
8150:" ",
8200:" ",
8250:"",
8300:" ",
8350:" ",
8400:" ",
8450:" ",
8500:" ",
8550:" ",
8600:" ",
8650:" ",
8700:" ",
8750:"",
8800:" ",
8850:" ",
8900:" ",
8950:" ",
9000:" ",
9050:" ",
9100:" ",
9150:" ",
9200:" ",
9250:"",
9300:" ",
9350:" ",
9400:" ",
9450:" ",
9500:" ",
9550:" ",
9600:" ",
9650:" ",
9700:" ",
9750:"",
9800:" ",
9850:" ",
9900:" ",
9950:" ",
10000:" ",
10050:" ",
10100:" ",
10150:" ",
10200:" ",
10250:"",
10300:" ",
10350:" ",
10400:" ",
10450:" ",
10500:" ",
10550:" ",
10600:" ",
10650:" ",
10700:" ",
10750:"",
10800:" ",
10850:" ",
10900:" ",
10950:" ",
11000:" ",
11050:" ",
11100:" ",
11150:" ",
11200:" ",
11250:"",
11300:" ",
11350:" ",
11400:" ",
11450:" ",
11500:" ",
11550:" ",
11600:" ",
11650:" ",
11700:" ",
11750:"",
11800:" ",
11850:" ",
11900:" ",
11950:" ",
12000:" ",
12050:" ",
12100:" ",
12150:" ",
12200:" ",
12250:"",
12300:" ",
12350:" ",
12400:" ",
12450:" ",
12500:" ",
12550:" ",
12600:" ",
12650:" ",
12700:" ",
12750:"",
12800:" ",
12850:" ",
12900:" ",
12950:" ",
13000:" ",
13050:" ",
13100:" ",
13150:" ",
13200:" ",
13250:"",
13300:" ",
13350:" ",
13400:" ",
13450:" ",
13500:" ",
13550:" ",
13600:" ",
13650:" ",
13700:" ",
13750:"",
13800:" ",
13850:" ",
13900:" ",
13950:" ",
14000:" ",
14050:" ",
14100:" ",
14150:" ",
14200:" ",
14250:"",
14300:" ",
14350:" ",
14400:" ",
14450:" ",
14500:" ",
14550:" ",
14600:" ",
14650:" ",
14700:" ",
14750:"",
14800:" ",
14850:" ",
14900:" ",
14950:" ",
15000:" ",
15050:" ",
15100:" ",
15150:" ",
15200:" ",
15250:"",
15300:" ",
15350:" ",
15400:" ",
15450:" ",
15500:" ",
15550:" ",
15600:" ",
15650:" ",
15700:" ",
15750:"",
15800:" ",
15850:" ",
15900:" ",
15950:" ",
16000:" ",
16050:" ",
16100:" ",
16150:" ",
16200:" ",
16250:"",
16300:" ",
16350:" ",
16400:" ",
16450:" ",
16500:" ",
16550:" ",
16600:" ",
16650:" ",
16700:" ",
16750:"",
16800:" ",
16850:" ",
16900:" ",
16950:" ",
17000:" ",
17050:" ",
17100:" ",
17150:" ",
17200:" ",
17250:"",
17300:" ",
17350:" ",
17400:" ",
17450:" ",
17500:" ",
17550:" ",
17600:" ",
17650:" ",
17700:" ",
17750:"",
17800:" ",
17850:" ",
17900:" ",
17950:" ",
18000:" ",
18050:" ",
18100:" ",
18150:" ",
18200:" ",
18250:"",
18300:" ",
18350:" ",
18400:" ",
18450:" ",
18500:" ",
18550:" ",
18600:" ",
18650:" ",
18700:" ",
18750:"",
18800:" ",
18850:" ",
18900:" ",
18950:" ",
19000:" ",
19050:" ",
19100:" ",
19150:" ",
19200:" ",
19250:"",
19300:" ",
19350:" ",
19400:" ",
19450:" ",
19500:" ",
19550:" ",
19600:" ",
19650:" ",
19700:" ",
19750:"",
19800:" ",
19850:" ",
19900:" ",
19950:" ",
20000:" ",
20050:" ",
20100:" ",
20150:" ",
20200:" ",
20250:"",
20300:" ",
20350:" ",
20400:" ",
20450:" ",
20500:" ",
20550:" ",
20600:" ",
20650:" ",
20700:" ",
20750:"",
20800:" ",
20850:" ",
20900:" ",
20950:" ",
21000:" ",
21050:" ",
21100:" ",
21150:" ",
21200:" ",
21250:"",
21300:" ",
21350:" ",
21400:" ",
21450:" ",
21500:" ",
21550:" ",
21600:" ",
21650:" ",
21700:" ",
21750:"",
21800:" ",
21850:" ",
21900:" ",
21950:" ",
22000:" ",
22050:" ",
22100:" ",
22150:" ",
22200:" ",
22250:"",
22300:" ",
22350:" ",
22400:" ",
22450:" ",
22500:" ",
22550:" ",
22600:" ",
22650:" ",
22700:" ",
22750:"",
22800:" ",
22850:" ",
22900:" ",
22950:" ",
23000:" ",
23050:" ",
23100:" ",
23150:" ",
23200:" ",
23250:"",
23300:" ",
23350:" ",
23400:" ",
23450:" ",
23500:" ",
23550:" ",
23600:" ",
23650:" ",
23700:" ",
23750:"",
23800:" ",
23850:" ",
23900:" ",
23950:" ",
24000:" ",
24050:" ",
24100:" ",
24150:" ",
24200:" ",
24250:"",
24300:" ",
24350:" ",
24400:" ",
24450:" ",
24500:" ",
24550:" ",
24600:" ",
24650:" ",
24700:" ",
24750:"",
24800:" ",
24850:" ",
24900:" ",
24950:" ",
25000:" ",
25050:" ",
25100:" ",
25150:" ",
25200:" ",
25250:"",
25300:" ",
25350:" ",
25400:" ",
25450:" ",
25500:" ",
25550:" ",
25600:" ",
25650:" ",
25700:" ",
25750:"",
25800:" ",
25850:" ",
25900:" ",
25950:" ",
26000:" ",
26050:" ",
26100:" ",
26150:" ",
26200:" ",
26250:"",
26300:" ",
26350:" ",
26400:" ",
26450:" ",
26500:" ",
26550:" ",
26600:" ",
26650:" ",
26700:" ",
26750:"",
26800:" ",
26850:" ",
26900:" ",
26950:" ",
27000:" ",
27050:" ",
27100:" ",
27150:" ",
27200:" ",
27250:"",
27300:" ",
27350:" ",
27400:" ",
27450:" ",
27500:" ",
27550:" ",
27600:" ",
27650:" ",
27700:" ",
27750:"",
27800:" ",
27850:" ",
27900:" ",
27950:" ",
28000:" ",
28050:" ",
28100:" ",
28150:" ",
28200:" ",
28250:"",
28300:" ",
28350:" ",
28400:" ",
28450:" ",
28500:" ",
28550:" ",
28600:" ",
28650:" ",
28700:" ",
28750:"",
28800:" ",
28850:" ",
28900:" ",
28950:" ",
29000:" ",
29050:" ",
29100:" ",
29150:" ",
29200:" ",
29250:"",
29300:" ",
29350:" ",
29400:" ",
29450:" ",
29500:" ",
29550:" ",
29600:" ",
29650:" ",
29700:" ",
29750:"",
29800:" ",
29850:" ",
29900:" ",
29950:" ",
30000:" ",
30050:" ",
30100:" ",
30150:" ",
30200:" ",
30250:"",
30300:" ",
30350:" ",
30400:" ",
30450:" ",
30500:" ",
30550:" ",
30600:" ",
30650:" ",
30700:" ",
30750:"",
30800:" ",
30850:" ",
30900:" ",
30950:" ",
31000:" ",
31050:" ",
31100:" ",
31150:" ",
31200:" ",
31250:"",
31300:" ",
31350:" ",
31400:" ",
31450:" ",
31500:" ",
31550:" ",
31600:" ",
31650:" ",
31700:" ",
31750:"",
31800:" ",
31850:" ",
31900:" ",
31950:" ",
32000:" ",
32050:" ",
32100:" ",
32150:" ",
32200:" ",
32250:"",
32300:" ",
32350:" ",
32400:" ",
32450:" ",
32500:" ",
32550:" ",
32600:" ",
32650:" ",
32700:" ",
32750:"",
32800:" ",
32850:" ",
32900:" ",
32950:" ",
33000:" ",
33050:" ",
33100:" ",
33150:" ",
33200:" ",
33250:"",
33300:" ",
33350:" ",
33400:" ",
33450:" ",
33500:" ",
33550:" ",
33600:" ",
33650:" ",
33700:" ",
33750:"",
33800:" ",
33850:" ",
33900:" ",
33950:" ",
34000:" ",
34050:" ",
34100:" ",
34150:" ",
34200:" ",
34250:"",
34300:" ",
34350:" ",
34400:" ",
34450:" ",
34500:" ",
34550:" ",
34600:" ",
34650:" ",
34700:" ",
34750:"",
34800:" ",
34850:" ",
34900:" ",
34950:" ",
35000:" ",
35050:" ",
35100:" ",
35150:" ",
35200:" ",
35250:"",
35300:" ",
35350:" ",
35400:" ",
35450:" ",
35500:" ",
35550:" ",
35600:" ",
35650:" ",
35700:" ",
35750:"",
35800:" ",
35850:" ",
35900:" ",
35950:" ",
36000:" ",
36050:" ",
36100:" ",
36150:" ",
36200:" ",
36250:"",
36300:" ",
36350:" ",
36400:" ",
36450:" ",
36500:" ",
36550:" ",
36600:" ",
36650:" ",
36700:" ",
36750:"",
36800:" ",
36850:" ",
36900:" ",
36950:" ",
37000:" ",
37050:" ",
37100:" ",
37150:" ",
37200:" ",
37250:"",
37300:" ",
37350:" ",
37400:" ",
37450:" ",
37500:" ",
37550:" ",
37600:" ",
37650:" ",
37700:" ",
37750:"",
37800:" ",
37850:" ",
37900:" ",
37950:" ",
38000:" ",
38050:" ",
38100:" ",
38150:" ",
38200:" ",
38250:"",
38300:" ",
38350:" ",
38400:" ",
38450:" ",
38500:" ",
38550:" ",
38600:" ",
38650:" ",
38700:" ",
38750:"",
38800:" ",
38850:" ",
38900:" ",
38950:" ",
39000:" ",
39050:" ",
39100:" ",
39150:" ",
39200:" ",
39250:"",
39300:" ",
39350:" ",
39400:" ",
39450:" ",
39500:" ",
39550:" ",
39600:" ",
39650:" ",
39700:" ",
39750:"",
39800:" ",
39850:" ",
39900:" ",
39950:" ",
40000:" ",
40050:" ",
40100:" ",
40150:" ",
40200:" ",
40250:"",
40300:" ",
40350:" ",
40400:" ",
40450:" ",
40500:" ",
40550:" ",
40600:" ",
40650:" ",
40700:" ",
40750:"",
40800:" ",
40850:" ",
40900:" ",
40950:" ",
41000:" ",
41050:" ",
41100:" ",
41150:" ",
41200:" ",
41250:"",
41300:" ",
41350:" ",
41400:" ",
41450:" ",
41500:" ",
41550:" ",
41600:" ",
41650:" ",
41700:" ",
41750:"",
41800:" ",
41850:" ",
41900:" ",
41950:" ",
42000:" ",
42050:" ",
42100:" ",
42150:" ",
42200:" ",
42250:"",
42300:" ",
42350:" ",
42400:" ",
42450:" ",
42500:" ",
42550:" ",
42600:" ",
42650:" ",
42700:" ",
42750:"",
42800:" ",
42850:" ",
42900:" ",
42950:" ",
43000:" ",
43050:" ",
43100:" ",
43150:" ",
43200:" ",
43250:"",
43300:" ",
43350:" ",
43400:" ",
43450:" ",
43500:" ",
43550:" ",
43600:" ",
43650:" ",
43700:" ",
43750:"",
43800:" ",
43850:" ",
43900:" ",
43950:" ",
44000:" ",
44050:" ",
44100:" ",
44150:" ",
44200:" ",
44250:"",
44300:" ",
44350:" ",
44400:" ",
44450:" ",
44500:" ",
44550:" ",
44600:" ",
44650:" ",
44700:" ",
44750:"",
44800:" ",
44850:" ",
44900:" ",
44950:" ",
45000:" ",
45050:" ",
45100:" ",
45150:" ",
45200:" ",
45250:"",
45300:" ",
45350:" ",
45400:" ",
45450:" ",
45500:" ",
45550:" ",
45600:" ",
45650:" ",
45700:" ",
45750:"",
45800:" ",
45850:" ",
45900:" ",
45950:" ",
46000:" ",
46050:" ",
46100:" ",
46150:" ",
46200:" ",
46250:"",
46300:" ",
46350:" ",
46400:" ",
46450:" ",
46500:" ",
46550:" ",
46600:" ",
46650:" ",
46700:" ",
46750:"",
46800:" ",
46850:" ",
46900:" ",
46950:" ",
47000:" ",
47050:" ",
47100:" ",
47150:" ",
47200:" ",
47250:"",
47300:" ",
47350:" ",
47400:" ",
47450:" ",
47500:" ",
47550:" ",
47600:" ",
47650:" ",
47700:" ",
47750:"",
47800:" ",
47850:" ",
47900:" ",
47950:" ",
48000:" ",

    
}

In [77]:
to_DHU_1250_63_GCP={
   50:"",
100:"",
150:"",
200:"",
250:"",
300:" ",
350:" ",
400:"",
450:" ",
500:"ТО500",
550:" ",
600:"",
650:" ",
700:" ",
750:"",
800:"",
850:" ",
900:" ",
950:" ",
1000:"ТО1000",
1050:" ",
1100:" ",
1150:" ",
1200:"",
1250:"",
1300:" ",
1350:" ",
1400:" ",
1450:"",
1500:"ТО500",
1550:" ",
1600:"",
1650:" ",
1700:" ",
1750:"",
1800:"",
1850:" ",
1900:" ",
1950:" ",
2000:"ТО1000",
2050:" ",
2100:" ",
2150:" ",
2200:"",
2250:"",
2300:" ",
2350:" ",
2400:"",
2450:" ",
2500:"ТО500",
2550:" ",
2600:"",
2650:" ",
2700:" ",
2750:"",
2800:"",
2850:" ",
2900:" ",
2950:" ",
3000:"ТО1000",
3050:" ",
3100:" ",
3150:" ",
3200:"",
3250:"",
3300:" ",
3350:" ",
3400:"",
3450:" ",
3500:"ТО500",
3550:" ",
3600:"",
3650:" ",
3700:" ",
3750:"",
3800:"",
3850:" ",
3900:" ",
3950:" ",
4000:"ТО4000",
4050:" ",
4100:" ",
4150:" ",
4200:"",
4250:"",
4300:" ",
4350:" ",
4400:"",
4450:" ",
4500:"ТО500",
4550:" ",
4600:"",
4650:" ",
4700:" ",
4750:"",
4800:"",
4850:" ",
4900:" ",
4950:" ",
5000:"ТО1000",
5050:" ",
5100:" ",
5150:" ",
5200:" ",
5250:"",
5300:" ",
5350:" ",
5400:" ",
5450:" ",
5500:"ТО500",
5550:" ",
5600:" ",
5650:" ",
5700:" ",
5750:"",
5800:" ",
5850:" ",
5900:" ",
5950:" ",
6000:"ТО1000",
6050:" ",
6100:" ",
6150:" ",
6200:" ",
6250:"",
6300:" ",
6350:" ",
6400:" ",
6450:" ",
6500:"ТО500",
6550:" ",
6600:" ",
6650:" ",
6700:" ",
6750:"",
6800:" ",
6850:" ",
6900:" ",
6950:" ",
7000:"ТО1000",
7050:" ",
7100:" ",
7150:" ",
7200:" ",
7250:"",
7300:" ",
7350:" ",
7400:" ",
7450:" ",
7500:"ТО500",
7550:" ",
7600:" ",
7650:" ",
7700:" ",
7750:"",
7800:" ",
7850:" ",
7900:" ",
7950:" ",
8000:"ТО1000",
8050:" ",
8100:" ",
8150:" ",
8200:" ",
8250:"",
8300:" ",
8350:" ",
8400:" ",
8450:" ",
8500:" ",
8550:" ",
8600:" ",
8650:" ",
8700:" ",
8750:"",
8800:" ",
8850:" ",
8900:" ",
8950:" ",
9000:" ",
9050:" ",
9100:" ",
9150:" ",
9200:" ",
9250:"",
9300:" ",
9350:" ",
9400:" ",
9450:" ",
9500:" ",
9550:" ",
9600:" ",
9650:" ",
9700:" ",
9750:"",
9800:" ",
9850:" ",
9900:" ",
9950:" ",
10000:" ",
10050:" ",
10100:" ",
10150:" ",
10200:" ",
10250:"",
10300:" ",
10350:" ",
10400:" ",
10450:" ",
10500:" ",
10550:" ",
10600:" ",
10650:" ",
10700:" ",
10750:"",
10800:" ",
10850:" ",
10900:" ",
10950:" ",
11000:" ",
11050:" ",
11100:" ",
11150:" ",
11200:" ",
11250:"",
11300:" ",
11350:" ",
11400:" ",
11450:" ",
11500:" ",
11550:" ",
11600:" ",
11650:" ",
11700:" ",
11750:"",
11800:" ",
11850:" ",
11900:" ",
11950:" ",
12000:" ",
12050:" ",
12100:" ",
12150:" ",
12200:" ",
12250:"",
12300:" ",
12350:" ",
12400:" ",
12450:" ",
12500:" ",
12550:" ",
12600:" ",
12650:" ",
12700:" ",
12750:"",
12800:" ",
12850:" ",
12900:" ",
12950:" ",
13000:" ",
13050:" ",
13100:" ",
13150:" ",
13200:" ",
13250:"",
13300:" ",
13350:" ",
13400:" ",
13450:" ",
13500:" ",
13550:" ",
13600:" ",
13650:" ",
13700:" ",
13750:"",
13800:" ",
13850:" ",
13900:" ",
13950:" ",
14000:" ",
14050:" ",
14100:" ",
14150:" ",
14200:" ",
14250:"",
14300:" ",
14350:" ",
14400:" ",
14450:" ",
14500:" ",
14550:" ",
14600:" ",
14650:" ",
14700:" ",
14750:"",
14800:" ",
14850:" ",
14900:" ",
14950:" ",
15000:" ",
15050:" ",
15100:" ",
15150:" ",
15200:" ",
15250:"",
15300:" ",
15350:" ",
15400:" ",
15450:" ",
15500:" ",
15550:" ",
15600:" ",
15650:" ",
15700:" ",
15750:"",
15800:" ",
15850:" ",
15900:" ",
15950:" ",
16000:" ",
16050:" ",
16100:" ",
16150:" ",
16200:" ",
16250:"",
16300:" ",
16350:" ",
16400:" ",
16450:" ",
16500:" ",
16550:" ",
16600:" ",
16650:" ",
16700:" ",
16750:"",
16800:" ",
16850:" ",
16900:" ",
16950:" ",
17000:" ",
17050:" ",
17100:" ",
17150:" ",
17200:" ",
17250:"",
17300:" ",
17350:" ",
17400:" ",
17450:" ",
17500:" ",
17550:" ",
17600:" ",
17650:" ",
17700:" ",
17750:"",
17800:" ",
17850:" ",
17900:" ",
17950:" ",
18000:" ",
18050:" ",
18100:" ",
18150:" ",
18200:" ",
18250:"",
18300:" ",
18350:" ",
18400:" ",
18450:" ",
18500:" ",
18550:" ",
18600:" ",
18650:" ",
18700:" ",
18750:"",
18800:" ",
18850:" ",
18900:" ",
18950:" ",
19000:" ",
19050:" ",
19100:" ",
19150:" ",
19200:" ",
19250:"",
19300:" ",
19350:" ",
19400:" ",
19450:" ",
19500:" ",
19550:" ",
19600:" ",
19650:" ",
19700:" ",
19750:"",
19800:" ",
19850:" ",
19900:" ",
19950:" ",
20000:" ",
20050:" ",
20100:" ",
20150:" ",
20200:" ",
20250:"",
20300:" ",
20350:" ",
20400:" ",
20450:" ",
20500:" ",
20550:" ",
20600:" ",
20650:" ",
20700:" ",
20750:"",
20800:" ",
20850:" ",
20900:" ",
20950:" ",
21000:" ",
21050:" ",
21100:" ",
21150:" ",
21200:" ",
21250:"",
21300:" ",
21350:" ",
21400:" ",
21450:" ",
21500:" ",
21550:" ",
21600:" ",
21650:" ",
21700:" ",
21750:"",
21800:" ",
21850:" ",
21900:" ",
21950:" ",
22000:" ",
22050:" ",
22100:" ",
22150:" ",
22200:" ",
22250:"",
22300:" ",
22350:" ",
22400:" ",
22450:" ",
22500:" ",
22550:" ",
22600:" ",
22650:" ",
22700:" ",
22750:"",
22800:" ",
22850:" ",
22900:" ",
22950:" ",
23000:" ",
23050:" ",
23100:" ",
23150:" ",
23200:" ",
23250:"",
23300:" ",
23350:" ",
23400:" ",
23450:" ",
23500:" ",
23550:" ",
23600:" ",
23650:" ",
23700:" ",
23750:"",
23800:" ",
23850:" ",
23900:" ",
23950:" ",
24000:" ",
24050:" ",
24100:" ",
24150:" ",
24200:" ",
24250:"",
24300:" ",
24350:" ",
24400:" ",
24450:" ",
24500:" ",
24550:" ",
24600:" ",
24650:" ",
24700:" ",
24750:"",
24800:" ",
24850:" ",
24900:" ",
24950:" ",
25000:" ",
25050:" ",
25100:" ",
25150:" ",
25200:" ",
25250:"",
25300:" ",
25350:" ",
25400:" ",
25450:" ",
25500:" ",
25550:" ",
25600:" ",
25650:" ",
25700:" ",
25750:"",
25800:" ",
25850:" ",
25900:" ",
25950:" ",
26000:" ",
26050:" ",
26100:" ",
26150:" ",
26200:" ",
26250:"",
26300:" ",
26350:" ",
26400:" ",
26450:" ",
26500:" ",
26550:" ",
26600:" ",
26650:" ",
26700:" ",
26750:"",
26800:" ",
26850:" ",
26900:" ",
26950:" ",
27000:" ",
27050:" ",
27100:" ",
27150:" ",
27200:" ",
27250:"",
27300:" ",
27350:" ",
27400:" ",
27450:" ",
27500:" ",
27550:" ",
27600:" ",
27650:" ",
27700:" ",
27750:"",
27800:" ",
27850:" ",
27900:" ",
27950:" ",
28000:" ",
28050:" ",
28100:" ",
28150:" ",
28200:" ",
28250:"",
28300:" ",
28350:" ",
28400:" ",
28450:" ",
28500:" ",
28550:" ",
28600:" ",
28650:" ",
28700:" ",
28750:"",
28800:" ",
28850:" ",
28900:" ",
28950:" ",
29000:" ",
29050:" ",
29100:" ",
29150:" ",
29200:" ",
29250:"",
29300:" ",
29350:" ",
29400:" ",
29450:" ",
29500:" ",
29550:" ",
29600:" ",
29650:" ",
29700:" ",
29750:"",
29800:" ",
29850:" ",
29900:" ",
29950:" ",
30000:" ",
30050:" ",
30100:" ",
30150:" ",
30200:" ",
30250:"",
30300:" ",
30350:" ",
30400:" ",
30450:" ",
30500:" ",
30550:" ",
30600:" ",
30650:" ",
30700:" ",
30750:"",
30800:" ",
30850:" ",
30900:" ",
30950:" ",
31000:" ",
31050:" ",
31100:" ",
31150:" ",
31200:" ",
31250:"",
31300:" ",
31350:" ",
31400:" ",
31450:" ",
31500:" ",
31550:" ",
31600:" ",
31650:" ",
31700:" ",
31750:"",
31800:" ",
31850:" ",
31900:" ",
31950:" ",
32000:" ",
32050:" ",
32100:" ",
32150:" ",
32200:" ",
32250:"",
32300:" ",
32350:" ",
32400:" ",
32450:" ",
32500:" ",
32550:" ",
32600:" ",
32650:" ",
32700:" ",
32750:"",
32800:" ",
32850:" ",
32900:" ",
32950:" ",
33000:" ",
33050:" ",
33100:" ",
33150:" ",
33200:" ",
33250:"",
33300:" ",
33350:" ",
33400:" ",
33450:" ",
33500:" ",
33550:" ",
33600:" ",
33650:" ",
33700:" ",
33750:"",
33800:" ",
33850:" ",
33900:" ",
33950:" ",
34000:" ",
34050:" ",
34100:" ",
34150:" ",
34200:" ",
34250:"",
34300:" ",
34350:" ",
34400:" ",
34450:" ",
34500:" ",
34550:" ",
34600:" ",
34650:" ",
34700:" ",
34750:"",
34800:" ",
34850:" ",
34900:" ",
34950:" ",
35000:" ",
35050:" ",
35100:" ",
35150:" ",
35200:" ",
35250:"",
35300:" ",
35350:" ",
35400:" ",
35450:" ",
35500:" ",
35550:" ",
35600:" ",
35650:" ",
35700:" ",
35750:"",
35800:" ",
35850:" ",
35900:" ",
35950:" ",
36000:" ",
36050:" ",
36100:" ",
36150:" ",
36200:" ",
36250:"",
36300:" ",
36350:" ",
36400:" ",
36450:" ",
36500:" ",
36550:" ",
36600:" ",
36650:" ",
36700:" ",
36750:"",
36800:" ",
36850:" ",
36900:" ",
36950:" ",
37000:" ",
37050:" ",
37100:" ",
37150:" ",
37200:" ",
37250:"",
37300:" ",
37350:" ",
37400:" ",
37450:" ",
37500:" ",
37550:" ",
37600:" ",
37650:" ",
37700:" ",
37750:"",
37800:" ",
37850:" ",
37900:" ",
37950:" ",
38000:" ",
38050:" ",
38100:" ",
38150:" ",
38200:" ",
38250:"",
38300:" ",
38350:" ",
38400:" ",
38450:" ",
38500:" ",
38550:" ",
38600:" ",
38650:" ",
38700:" ",
38750:"",
38800:" ",
38850:" ",
38900:" ",
38950:" ",
39000:" ",
39050:" ",
39100:" ",
39150:" ",
39200:" ",
39250:"",
39300:" ",
39350:" ",
39400:" ",
39450:" ",
39500:" ",
39550:" ",
39600:" ",
39650:" ",
39700:" ",
39750:"",
39800:" ",
39850:" ",
39900:" ",
39950:" ",
40000:" ",
40050:" ",
40100:" ",
40150:" ",
40200:" ",
40250:"",
40300:" ",
40350:" ",
40400:" ",
40450:" ",
40500:" ",
40550:" ",
40600:" ",
40650:" ",
40700:" ",
40750:"",
40800:" ",
40850:" ",
40900:" ",
40950:" ",
41000:" ",
41050:" ",
41100:" ",
41150:" ",
41200:" ",
41250:"",
41300:" ",
41350:" ",
41400:" ",
41450:" ",
41500:" ",
41550:" ",
41600:" ",
41650:" ",
41700:" ",
41750:"",
41800:" ",
41850:" ",
41900:" ",
41950:" ",
42000:" ",
42050:" ",
42100:" ",
42150:" ",
42200:" ",
42250:"",
42300:" ",
42350:" ",
42400:" ",
42450:" ",
42500:" ",
42550:" ",
42600:" ",
42650:" ",
42700:" ",
42750:"",
42800:" ",
42850:" ",
42900:" ",
42950:" ",
43000:" ",
43050:" ",
43100:" ",
43150:" ",
43200:" ",
43250:"",
43300:" ",
43350:" ",
43400:" ",
43450:" ",
43500:" ",
43550:" ",
43600:" ",
43650:" ",
43700:" ",
43750:"",
43800:" ",
43850:" ",
43900:" ",
43950:" ",
44000:" ",
44050:" ",
44100:" ",
44150:" ",
44200:" ",
44250:"",
44300:" ",
44350:" ",
44400:" ",
44450:" ",
44500:" ",
44550:" ",
44600:" ",
44650:" ",
44700:" ",
44750:"",
44800:" ",
44850:" ",
44900:" ",
44950:" ",
45000:" ",
45050:" ",
45100:" ",
45150:" ",
45200:" ",
45250:"",
45300:" ",
45350:" ",
45400:" ",
45450:" ",
45500:" ",
45550:" ",
45600:" ",
45650:" ",
45700:" ",
45750:"",
45800:" ",
45850:" ",
45900:" ",
45950:" ",
46000:" ",
46050:" ",
46100:" ",
46150:" ",
46200:" ",
46250:"",
46300:" ",
46350:" ",
46400:" ",
46450:" ",
46500:" ",
46550:" ",
46600:" ",
46650:" ",
46700:" ",
46750:"",
46800:" ",
46850:" ",
46900:" ",
46950:" ",
47000:" ",
47050:" ",
47100:" ",
47150:" ",
47200:" ",
47250:"",
47300:" ",
47350:" ",
47400:" ",
47450:" ",
47500:" ",
47550:" ",
47600:" ",
47650:" ",
47700:" ",
47750:"",
47800:" ",
47850:" ",
47900:" ",
47950:" ",
48000:" ",

    
}

In [78]:
to_DHU_630_70_GCP={
   50:"",
100:"",
150:"",
200:"",
250:"",
300:" ",
350:" ",
400:"",
450:" ",
500:"ТО500",
550:" ",
600:"",
650:" ",
700:" ",
750:"",
800:"",
850:" ",
900:" ",
950:" ",
1000:"ТО1000",
1050:" ",
1100:" ",
1150:" ",
1200:"",
1250:"",
1300:" ",
1350:" ",
1400:" ",
1450:"",
1500:"ТО500",
1550:" ",
1600:"",
1650:" ",
1700:" ",
1750:"",
1800:"",
1850:" ",
1900:" ",
1950:" ",
2000:"ТО1000",
2050:" ",
2100:" ",
2150:" ",
2200:"",
2250:"",
2300:" ",
2350:" ",
2400:"",
2450:" ",
2500:"ТО500",
2550:" ",
2600:"",
2650:" ",
2700:" ",
2750:"",
2800:"",
2850:" ",
2900:" ",
2950:" ",
3000:"ТО1000",
3050:" ",
3100:" ",
3150:" ",
3200:"",
3250:"",
3300:" ",
3350:" ",
3400:"",
3450:" ",
3500:"ТО500",
3550:" ",
3600:"",
3650:" ",
3700:" ",
3750:"",
3800:"",
3850:" ",
3900:" ",
3950:" ",
4000:"ТО4000",
4050:" ",
4100:" ",
4150:" ",
4200:"",
4250:"",
4300:" ",
4350:" ",
4400:"",
4450:" ",
4500:"ТО500",
4550:" ",
4600:"",
4650:" ",
4700:" ",
4750:"",
4800:"",
4850:" ",
4900:" ",
4950:" ",
5000:"ТО1000",
5050:" ",
5100:" ",
5150:" ",
5200:" ",
5250:"",
5300:" ",
5350:" ",
5400:" ",
5450:" ",
5500:"ТО500",
5550:" ",
5600:" ",
5650:" ",
5700:" ",
5750:"",
5800:" ",
5850:" ",
5900:" ",
5950:" ",
6000:"ТО1000",
6050:" ",
6100:" ",
6150:" ",
6200:" ",
6250:"",
6300:" ",
6350:" ",
6400:" ",
6450:" ",
6500:"ТО500",
6550:" ",
6600:" ",
6650:" ",
6700:" ",
6750:"",
6800:" ",
6850:" ",
6900:" ",
6950:" ",
7000:"ТО1000",
7050:" ",
7100:" ",
7150:" ",
7200:" ",
7250:"",
7300:" ",
7350:" ",
7400:" ",
7450:" ",
7500:"ТО500",
7550:" ",
7600:" ",
7650:" ",
7700:" ",
7750:"",
7800:" ",
7850:" ",
7900:" ",
7950:" ",
8000:"ТО1000",
8050:" ",
8100:" ",
8150:" ",
8200:" ",
8250:"",
8300:" ",
8350:" ",
8400:" ",
8450:" ",
8500:" ",
8550:" ",
8600:" ",
8650:" ",
8700:" ",
8750:"",
8800:" ",
8850:" ",
8900:" ",
8950:" ",
9000:" ",
9050:" ",
9100:" ",
9150:" ",
9200:" ",
9250:"",
9300:" ",
9350:" ",
9400:" ",
9450:" ",
9500:" ",
9550:" ",
9600:" ",
9650:" ",
9700:" ",
9750:"",
9800:" ",
9850:" ",
9900:" ",
9950:" ",
10000:" ",
10050:" ",
10100:" ",
10150:" ",
10200:" ",
10250:"",
10300:" ",
10350:" ",
10400:" ",
10450:" ",
10500:" ",
10550:" ",
10600:" ",
10650:" ",
10700:" ",
10750:"",
10800:" ",
10850:" ",
10900:" ",
10950:" ",
11000:" ",
11050:" ",
11100:" ",
11150:" ",
11200:" ",
11250:"",
11300:" ",
11350:" ",
11400:" ",
11450:" ",
11500:" ",
11550:" ",
11600:" ",
11650:" ",
11700:" ",
11750:"",
11800:" ",
11850:" ",
11900:" ",
11950:" ",
12000:" ",
12050:" ",
12100:" ",
12150:" ",
12200:" ",
12250:"",
12300:" ",
12350:" ",
12400:" ",
12450:" ",
12500:" ",
12550:" ",
12600:" ",
12650:" ",
12700:" ",
12750:"",
12800:" ",
12850:" ",
12900:" ",
12950:" ",
13000:" ",
13050:" ",
13100:" ",
13150:" ",
13200:" ",
13250:"",
13300:" ",
13350:" ",
13400:" ",
13450:" ",
13500:" ",
13550:" ",
13600:" ",
13650:" ",
13700:" ",
13750:"",
13800:" ",
13850:" ",
13900:" ",
13950:" ",
14000:" ",
14050:" ",
14100:" ",
14150:" ",
14200:" ",
14250:"",
14300:" ",
14350:" ",
14400:" ",
14450:" ",
14500:" ",
14550:" ",
14600:" ",
14650:" ",
14700:" ",
14750:"",
14800:" ",
14850:" ",
14900:" ",
14950:" ",
15000:" ",
15050:" ",
15100:" ",
15150:" ",
15200:" ",
15250:"",
15300:" ",
15350:" ",
15400:" ",
15450:" ",
15500:" ",
15550:" ",
15600:" ",
15650:" ",
15700:" ",
15750:"",
15800:" ",
15850:" ",
15900:" ",
15950:" ",
16000:" ",
16050:" ",
16100:" ",
16150:" ",
16200:" ",
16250:"",
16300:" ",
16350:" ",
16400:" ",
16450:" ",
16500:" ",
16550:" ",
16600:" ",
16650:" ",
16700:" ",
16750:"",
16800:" ",
16850:" ",
16900:" ",
16950:" ",
17000:" ",
17050:" ",
17100:" ",
17150:" ",
17200:" ",
17250:"",
17300:" ",
17350:" ",
17400:" ",
17450:" ",
17500:" ",
17550:" ",
17600:" ",
17650:" ",
17700:" ",
17750:"",
17800:" ",
17850:" ",
17900:" ",
17950:" ",
18000:" ",
18050:" ",
18100:" ",
18150:" ",
18200:" ",
18250:"",
18300:" ",
18350:" ",
18400:" ",
18450:" ",
18500:" ",
18550:" ",
18600:" ",
18650:" ",
18700:" ",
18750:"",
18800:" ",
18850:" ",
18900:" ",
18950:" ",
19000:" ",
19050:" ",
19100:" ",
19150:" ",
19200:" ",
19250:"",
19300:" ",
19350:" ",
19400:" ",
19450:" ",
19500:" ",
19550:" ",
19600:" ",
19650:" ",
19700:" ",
19750:"",
19800:" ",
19850:" ",
19900:" ",
19950:" ",
20000:" ",
20050:" ",
20100:" ",
20150:" ",
20200:" ",
20250:"",
20300:" ",
20350:" ",
20400:" ",
20450:" ",
20500:" ",
20550:" ",
20600:" ",
20650:" ",
20700:" ",
20750:"",
20800:" ",
20850:" ",
20900:" ",
20950:" ",
21000:" ",
21050:" ",
21100:" ",
21150:" ",
21200:" ",
21250:"",
21300:" ",
21350:" ",
21400:" ",
21450:" ",
21500:" ",
21550:" ",
21600:" ",
21650:" ",
21700:" ",
21750:"",
21800:" ",
21850:" ",
21900:" ",
21950:" ",
22000:" ",
22050:" ",
22100:" ",
22150:" ",
22200:" ",
22250:"",
22300:" ",
22350:" ",
22400:" ",
22450:" ",
22500:" ",
22550:" ",
22600:" ",
22650:" ",
22700:" ",
22750:"",
22800:" ",
22850:" ",
22900:" ",
22950:" ",
23000:" ",
23050:" ",
23100:" ",
23150:" ",
23200:" ",
23250:"",
23300:" ",
23350:" ",
23400:" ",
23450:" ",
23500:" ",
23550:" ",
23600:" ",
23650:" ",
23700:" ",
23750:"",
23800:" ",
23850:" ",
23900:" ",
23950:" ",
24000:" ",
24050:" ",
24100:" ",
24150:" ",
24200:" ",
24250:"",
24300:" ",
24350:" ",
24400:" ",
24450:" ",
24500:" ",
24550:" ",
24600:" ",
24650:" ",
24700:" ",
24750:"",
24800:" ",
24850:" ",
24900:" ",
24950:" ",
25000:" ",
25050:" ",
25100:" ",
25150:" ",
25200:" ",
25250:"",
25300:" ",
25350:" ",
25400:" ",
25450:" ",
25500:" ",
25550:" ",
25600:" ",
25650:" ",
25700:" ",
25750:"",
25800:" ",
25850:" ",
25900:" ",
25950:" ",
26000:" ",
26050:" ",
26100:" ",
26150:" ",
26200:" ",
26250:"",
26300:" ",
26350:" ",
26400:" ",
26450:" ",
26500:" ",
26550:" ",
26600:" ",
26650:" ",
26700:" ",
26750:"",
26800:" ",
26850:" ",
26900:" ",
26950:" ",
27000:" ",
27050:" ",
27100:" ",
27150:" ",
27200:" ",
27250:"",
27300:" ",
27350:" ",
27400:" ",
27450:" ",
27500:" ",
27550:" ",
27600:" ",
27650:" ",
27700:" ",
27750:"",
27800:" ",
27850:" ",
27900:" ",
27950:" ",
28000:" ",
28050:" ",
28100:" ",
28150:" ",
28200:" ",
28250:"",
28300:" ",
28350:" ",
28400:" ",
28450:" ",
28500:" ",
28550:" ",
28600:" ",
28650:" ",
28700:" ",
28750:"",
28800:" ",
28850:" ",
28900:" ",
28950:" ",
29000:" ",
29050:" ",
29100:" ",
29150:" ",
29200:" ",
29250:"",
29300:" ",
29350:" ",
29400:" ",
29450:" ",
29500:" ",
29550:" ",
29600:" ",
29650:" ",
29700:" ",
29750:"",
29800:" ",
29850:" ",
29900:" ",
29950:" ",
30000:" ",
30050:" ",
30100:" ",
30150:" ",
30200:" ",
30250:"",
30300:" ",
30350:" ",
30400:" ",
30450:" ",
30500:" ",
30550:" ",
30600:" ",
30650:" ",
30700:" ",
30750:"",
30800:" ",
30850:" ",
30900:" ",
30950:" ",
31000:" ",
31050:" ",
31100:" ",
31150:" ",
31200:" ",
31250:"",
31300:" ",
31350:" ",
31400:" ",
31450:" ",
31500:" ",
31550:" ",
31600:" ",
31650:" ",
31700:" ",
31750:"",
31800:" ",
31850:" ",
31900:" ",
31950:" ",
32000:" ",
32050:" ",
32100:" ",
32150:" ",
32200:" ",
32250:"",
32300:" ",
32350:" ",
32400:" ",
32450:" ",
32500:" ",
32550:" ",
32600:" ",
32650:" ",
32700:" ",
32750:"",
32800:" ",
32850:" ",
32900:" ",
32950:" ",
33000:" ",
33050:" ",
33100:" ",
33150:" ",
33200:" ",
33250:"",
33300:" ",
33350:" ",
33400:" ",
33450:" ",
33500:" ",
33550:" ",
33600:" ",
33650:" ",
33700:" ",
33750:"",
33800:" ",
33850:" ",
33900:" ",
33950:" ",
34000:" ",
34050:" ",
34100:" ",
34150:" ",
34200:" ",
34250:"",
34300:" ",
34350:" ",
34400:" ",
34450:" ",
34500:" ",
34550:" ",
34600:" ",
34650:" ",
34700:" ",
34750:"",
34800:" ",
34850:" ",
34900:" ",
34950:" ",
35000:" ",
35050:" ",
35100:" ",
35150:" ",
35200:" ",
35250:"",
35300:" ",
35350:" ",
35400:" ",
35450:" ",
35500:" ",
35550:" ",
35600:" ",
35650:" ",
35700:" ",
35750:"",
35800:" ",
35850:" ",
35900:" ",
35950:" ",
36000:" ",
36050:" ",
36100:" ",
36150:" ",
36200:" ",
36250:"",
36300:" ",
36350:" ",
36400:" ",
36450:" ",
36500:" ",
36550:" ",
36600:" ",
36650:" ",
36700:" ",
36750:"",
36800:" ",
36850:" ",
36900:" ",
36950:" ",
37000:" ",
37050:" ",
37100:" ",
37150:" ",
37200:" ",
37250:"",
37300:" ",
37350:" ",
37400:" ",
37450:" ",
37500:" ",
37550:" ",
37600:" ",
37650:" ",
37700:" ",
37750:"",
37800:" ",
37850:" ",
37900:" ",
37950:" ",
38000:" ",
38050:" ",
38100:" ",
38150:" ",
38200:" ",
38250:"",
38300:" ",
38350:" ",
38400:" ",
38450:" ",
38500:" ",
38550:" ",
38600:" ",
38650:" ",
38700:" ",
38750:"",
38800:" ",
38850:" ",
38900:" ",
38950:" ",
39000:" ",
39050:" ",
39100:" ",
39150:" ",
39200:" ",
39250:"",
39300:" ",
39350:" ",
39400:" ",
39450:" ",
39500:" ",
39550:" ",
39600:" ",
39650:" ",
39700:" ",
39750:"",
39800:" ",
39850:" ",
39900:" ",
39950:" ",
40000:" ",
40050:" ",
40100:" ",
40150:" ",
40200:" ",
40250:"",
40300:" ",
40350:" ",
40400:" ",
40450:" ",
40500:" ",
40550:" ",
40600:" ",
40650:" ",
40700:" ",
40750:"",
40800:" ",
40850:" ",
40900:" ",
40950:" ",
41000:" ",
41050:" ",
41100:" ",
41150:" ",
41200:" ",
41250:"",
41300:" ",
41350:" ",
41400:" ",
41450:" ",
41500:" ",
41550:" ",
41600:" ",
41650:" ",
41700:" ",
41750:"",
41800:" ",
41850:" ",
41900:" ",
41950:" ",
42000:" ",
42050:" ",
42100:" ",
42150:" ",
42200:" ",
42250:"",
42300:" ",
42350:" ",
42400:" ",
42450:" ",
42500:" ",
42550:" ",
42600:" ",
42650:" ",
42700:" ",
42750:"",
42800:" ",
42850:" ",
42900:" ",
42950:" ",
43000:" ",
43050:" ",
43100:" ",
43150:" ",
43200:" ",
43250:"",
43300:" ",
43350:" ",
43400:" ",
43450:" ",
43500:" ",
43550:" ",
43600:" ",
43650:" ",
43700:" ",
43750:"",
43800:" ",
43850:" ",
43900:" ",
43950:" ",
44000:" ",
44050:" ",
44100:" ",
44150:" ",
44200:" ",
44250:"",
44300:" ",
44350:" ",
44400:" ",
44450:" ",
44500:" ",
44550:" ",
44600:" ",
44650:" ",
44700:" ",
44750:"",
44800:" ",
44850:" ",
44900:" ",
44950:" ",
45000:" ",
45050:" ",
45100:" ",
45150:" ",
45200:" ",
45250:"",
45300:" ",
45350:" ",
45400:" ",
45450:" ",
45500:" ",
45550:" ",
45600:" ",
45650:" ",
45700:" ",
45750:"",
45800:" ",
45850:" ",
45900:" ",
45950:" ",
46000:" ",
46050:" ",
46100:" ",
46150:" ",
46200:" ",
46250:"",
46300:" ",
46350:" ",
46400:" ",
46450:" ",
46500:" ",
46550:" ",
46600:" ",
46650:" ",
46700:" ",
46750:"",
46800:" ",
46850:" ",
46900:" ",
46950:" ",
47000:" ",
47050:" ",
47100:" ",
47150:" ",
47200:" ",
47250:"",
47300:" ",
47350:" ",
47400:" ",
47450:" ",
47500:" ",
47550:" ",
47600:" ",
47650:" ",
47700:" ",
47750:"",
47800:" ",
47850:" ",
47900:" ",
47950:" ",
48000:" ",

    
}

In [79]:
to_ADD_4004={
   50:"",
100:"",
150:"",
200:"",
250:"ТО250",
300:" ",
350:" ",
400:"",
450:" ",
500:"ТО500",
550:" ",
600:"",
650:" ",
700:" ",
750:"ТО250",
800:"",
850:" ",
900:" ",
950:" ",
1000:"ТО1000",
1050:" ",
1100:" ",
1150:" ",
1200:"",
1250:"ТО250",
1300:" ",
1350:" ",
1400:" ",
1450:"",
1500:"ТО500",
1550:" ",
1600:"",
1650:" ",
1700:" ",
1750:"ТО250",
1800:"",
1850:" ",
1900:" ",
1950:" ",
2000:"ТО2000",
2050:" ",
2100:" ",
2150:" ",
2200:"",
2250:"ТО250",
2300:" ",
2350:" ",
2400:"",
2450:" ",
2500:"ТО500",
2550:" ",
2600:"",
2650:" ",
2700:" ",
2750:"ТО250",
2800:"",
2850:" ",
2900:" ",
2950:" ",
3000:"ТО3000",
3050:" ",
3100:" ",
3150:" ",
3200:"",
3250:"ТО250",
3300:" ",
3350:" ",
3400:"",
3450:" ",
3500:"ТО500",
3550:" ",
3600:"",
3650:" ",
3700:" ",
3750:"ТО250",
3800:"",
3850:" ",
3900:" ",
3950:" ",
4000:"ТО2000",
4050:" ",
4100:" ",
4150:" ",
4200:"",
4250:"ТО250",
4300:" ",
4350:" ",
4400:"",
4450:" ",
4500:"ТО500",
4550:" ",
4600:"",
4650:" ",
4700:" ",
4750:"ТО250",
4800:"",
4850:" ",
4900:" ",
4950:" ",
5000:"ТО1000",
5050:" ",
5100:" ",
5150:" ",
5200:" ",
5250:"ТО250",
5300:" ",
5350:" ",
5400:" ",
5450:" ",
5500:"ТО500",
5550:" ",
5600:" ",
5650:" ",
5700:" ",
5750:"ТО250",
5800:" ",
5850:" ",
5900:" ",
5950:" ",
6000:"ТО1000",
6050:" ",
6100:" ",
6150:" ",
6200:" ",
6250:"ТО250",
6300:" ",
6350:" ",
6400:" ",
6450:" ",
6500:"ТО500",
6550:" ",
6600:" ",
6650:" ",
6700:" ",
6750:"ТО250",
6800:" ",
6850:" ",
6900:" ",
6950:" ",
7000:"ТО1000",
7050:" ",
7100:" ",
7150:" ",
7200:" ",
7250:"ТО250",
7300:" ",
7350:" ",
7400:" ",
7450:" ",
7500:"ТО500",
7550:" ",
7600:" ",
7650:" ",
7700:" ",
7750:"ТО250",
7800:" ",
7850:" ",
7900:" ",
7950:" ",
8000:"ТО1000",
8050:" ",
8100:" ",
8150:" ",
8200:" ",
8250:"ТО250",
8300:" ",
8350:" ",
8400:" ",
8450:" ",
8500:"ТО500",
8550:" ",
8600:" ",
8650:" ",
8700:" ",
8750:"ТО250",
8800:" ",
8850:" ",
8900:" ",
8950:" ",
9000:"ТО3000",
9050:" ",
9100:" ",
9150:" ",
9200:" ",
9250:"ТО250",
9300:" ",
9350:" ",
9400:" ",
9450:" ",
9500:"ТО500",
9550:" ",
9600:" ",
9650:" ",
9700:" ",
9750:"ТО250",
9800:" ",
9850:" ",
9900:" ",
9950:" ",
10000:"ТО2000",
10050:" ",
10100:" ",
10150:" ",
10200:" ",
10250:"",
10300:" ",
10350:" ",
10400:" ",
10450:" ",
10500:" ",
10550:" ",
10600:" ",
10650:" ",
10700:" ",
10750:"",
10800:" ",
10850:" ",
10900:" ",
10950:" ",
11000:" ",
11050:" ",
11100:" ",
11150:" ",
11200:" ",
11250:"",
11300:" ",
11350:" ",
11400:" ",
11450:" ",
11500:" ",
11550:" ",
11600:" ",
11650:" ",
11700:" ",
11750:"",
11800:" ",
11850:" ",
11900:" ",
11950:" ",
12000:" ",
12050:" ",
12100:" ",
12150:" ",
12200:" ",
12250:"",
12300:" ",
12350:" ",
12400:" ",
12450:" ",
12500:" ",
12550:" ",
12600:" ",
12650:" ",
12700:" ",
12750:"",
12800:" ",
12850:" ",
12900:" ",
12950:" ",
13000:" ",
13050:" ",
13100:" ",
13150:" ",
13200:" ",
13250:"",
13300:" ",
13350:" ",
13400:" ",
13450:" ",
13500:" ",
13550:" ",
13600:" ",
13650:" ",
13700:" ",
13750:"",
13800:" ",
13850:" ",
13900:" ",
13950:" ",
14000:" ",
14050:" ",
14100:" ",
14150:" ",
14200:" ",
14250:"",
14300:" ",
14350:" ",
14400:" ",
14450:" ",
14500:" ",
14550:" ",
14600:" ",
14650:" ",
14700:" ",
14750:"",
14800:" ",
14850:" ",
14900:" ",
14950:" ",
15000:" ",
15050:" ",
15100:" ",
15150:" ",
15200:" ",
15250:"",
15300:" ",
15350:" ",
15400:" ",
15450:" ",
15500:" ",
15550:" ",
15600:" ",
15650:" ",
15700:" ",
15750:"",
15800:" ",
15850:" ",
15900:" ",
15950:" ",
16000:" ",
16050:" ",
16100:" ",
16150:" ",
16200:" ",
16250:"",
16300:" ",
16350:" ",
16400:" ",
16450:" ",
16500:" ",
16550:" ",
16600:" ",
16650:" ",
16700:" ",
16750:"",
16800:" ",
16850:" ",
16900:" ",
16950:" ",
17000:" ",
17050:" ",
17100:" ",
17150:" ",
17200:" ",
17250:"",
17300:" ",
17350:" ",
17400:" ",
17450:" ",
17500:" ",
17550:" ",
17600:" ",
17650:" ",
17700:" ",
17750:"",
17800:" ",
17850:" ",
17900:" ",
17950:" ",
18000:" ",
18050:" ",
18100:" ",
18150:" ",
18200:" ",
18250:"",
18300:" ",
18350:" ",
18400:" ",
18450:" ",
18500:" ",
18550:" ",
18600:" ",
18650:" ",
18700:" ",
18750:"",
18800:" ",
18850:" ",
18900:" ",
18950:" ",
19000:" ",
19050:" ",
19100:" ",
19150:" ",
19200:" ",
19250:"",
19300:" ",
19350:" ",
19400:" ",
19450:" ",
19500:" ",
19550:" ",
19600:" ",
19650:" ",
19700:" ",
19750:"",
19800:" ",
19850:" ",
19900:" ",
19950:" ",
20000:" ",
20050:" ",
20100:" ",
20150:" ",
20200:" ",
20250:"",
20300:" ",
20350:" ",
20400:" ",
20450:" ",
20500:" ",
20550:" ",
20600:" ",
20650:" ",
20700:" ",
20750:"",
20800:" ",
20850:" ",
20900:" ",
20950:" ",
21000:" ",
21050:" ",
21100:" ",
21150:" ",
21200:" ",
21250:"",
21300:" ",
21350:" ",
21400:" ",
21450:" ",
21500:" ",
21550:" ",
21600:" ",
21650:" ",
21700:" ",
21750:"",
21800:" ",
21850:" ",
21900:" ",
21950:" ",
22000:" ",
22050:" ",
22100:" ",
22150:" ",
22200:" ",
22250:"",
22300:" ",
22350:" ",
22400:" ",
22450:" ",
22500:" ",
22550:" ",
22600:" ",
22650:" ",
22700:" ",
22750:"",
22800:" ",
22850:" ",
22900:" ",
22950:" ",
23000:" ",
23050:" ",
23100:" ",
23150:" ",
23200:" ",
23250:"",
23300:" ",
23350:" ",
23400:" ",
23450:" ",
23500:" ",
23550:" ",
23600:" ",
23650:" ",
23700:" ",
23750:"",
23800:" ",
23850:" ",
23900:" ",
23950:" ",
24000:" ",
24050:" ",
24100:" ",
24150:" ",
24200:" ",
24250:"",
24300:" ",
24350:" ",
24400:" ",
24450:" ",
24500:" ",
24550:" ",
24600:" ",
24650:" ",
24700:" ",
24750:"",
24800:" ",
24850:" ",
24900:" ",
24950:" ",
25000:" ",
25050:" ",
25100:" ",
25150:" ",
25200:" ",
25250:"",
25300:" ",
25350:" ",
25400:" ",
25450:" ",
25500:" ",
25550:" ",
25600:" ",
25650:" ",
25700:" ",
25750:"",
25800:" ",
25850:" ",
25900:" ",
25950:" ",
26000:" ",
26050:" ",
26100:" ",
26150:" ",
26200:" ",
26250:"",
26300:" ",
26350:" ",
26400:" ",
26450:" ",
26500:" ",
26550:" ",
26600:" ",
26650:" ",
26700:" ",
26750:"",
26800:" ",
26850:" ",
26900:" ",
26950:" ",
27000:" ",
27050:" ",
27100:" ",
27150:" ",
27200:" ",
27250:"",
27300:" ",
27350:" ",
27400:" ",
27450:" ",
27500:" ",
27550:" ",
27600:" ",
27650:" ",
27700:" ",
27750:"",
27800:" ",
27850:" ",
27900:" ",
27950:" ",
28000:" ",
28050:" ",
28100:" ",
28150:" ",
28200:" ",
28250:"",
28300:" ",
28350:" ",
28400:" ",
28450:" ",
28500:" ",
28550:" ",
28600:" ",
28650:" ",
28700:" ",
28750:"",
28800:" ",
28850:" ",
28900:" ",
28950:" ",
29000:" ",
29050:" ",
29100:" ",
29150:" ",
29200:" ",
29250:"",
29300:" ",
29350:" ",
29400:" ",
29450:" ",
29500:" ",
29550:" ",
29600:" ",
29650:" ",
29700:" ",
29750:"",
29800:" ",
29850:" ",
29900:" ",
29950:" ",
30000:" ",
30050:" ",
30100:" ",
30150:" ",
30200:" ",
30250:"",
30300:" ",
30350:" ",
30400:" ",
30450:" ",
30500:" ",
30550:" ",
30600:" ",
30650:" ",
30700:" ",
30750:"",
30800:" ",
30850:" ",
30900:" ",
30950:" ",
31000:" ",
31050:" ",
31100:" ",
31150:" ",
31200:" ",
31250:"",
31300:" ",
31350:" ",
31400:" ",
31450:" ",
31500:" ",
31550:" ",
31600:" ",
31650:" ",
31700:" ",
31750:"",
31800:" ",
31850:" ",
31900:" ",
31950:" ",
32000:" ",
32050:" ",
32100:" ",
32150:" ",
32200:" ",
32250:"",
32300:" ",
32350:" ",
32400:" ",
32450:" ",
32500:" ",
32550:" ",
32600:" ",
32650:" ",
32700:" ",
32750:"",
32800:" ",
32850:" ",
32900:" ",
32950:" ",
33000:" ",
33050:" ",
33100:" ",
33150:" ",
33200:" ",
33250:"",
33300:" ",
33350:" ",
33400:" ",
33450:" ",
33500:" ",
33550:" ",
33600:" ",
33650:" ",
33700:" ",
33750:"",
33800:" ",
33850:" ",
33900:" ",
33950:" ",
34000:" ",
34050:" ",
34100:" ",
34150:" ",
34200:" ",
34250:"",
34300:" ",
34350:" ",
34400:" ",
34450:" ",
34500:" ",
34550:" ",
34600:" ",
34650:" ",
34700:" ",
34750:"",
34800:" ",
34850:" ",
34900:" ",
34950:" ",
35000:" ",
35050:" ",
35100:" ",
35150:" ",
35200:" ",
35250:"",
35300:" ",
35350:" ",
35400:" ",
35450:" ",
35500:" ",
35550:" ",
35600:" ",
35650:" ",
35700:" ",
35750:"",
35800:" ",
35850:" ",
35900:" ",
35950:" ",
36000:" ",
36050:" ",
36100:" ",
36150:" ",
36200:" ",
36250:"",
36300:" ",
36350:" ",
36400:" ",
36450:" ",
36500:" ",
36550:" ",
36600:" ",
36650:" ",
36700:" ",
36750:"",
36800:" ",
36850:" ",
36900:" ",
36950:" ",
37000:" ",
37050:" ",
37100:" ",
37150:" ",
37200:" ",
37250:"",
37300:" ",
37350:" ",
37400:" ",
37450:" ",
37500:" ",
37550:" ",
37600:" ",
37650:" ",
37700:" ",
37750:"",
37800:" ",
37850:" ",
37900:" ",
37950:" ",
38000:" ",
38050:" ",
38100:" ",
38150:" ",
38200:" ",
38250:"",
38300:" ",
38350:" ",
38400:" ",
38450:" ",
38500:" ",
38550:" ",
38600:" ",
38650:" ",
38700:" ",
38750:"",
38800:" ",
38850:" ",
38900:" ",
38950:" ",
39000:" ",
39050:" ",
39100:" ",
39150:" ",
39200:" ",
39250:"",
39300:" ",
39350:" ",
39400:" ",
39450:" ",
39500:" ",
39550:" ",
39600:" ",
39650:" ",
39700:" ",
39750:"",
39800:" ",
39850:" ",
39900:" ",
39950:" ",
40000:" ",
40050:" ",
40100:" ",
40150:" ",
40200:" ",
40250:"",
40300:" ",
40350:" ",
40400:" ",
40450:" ",
40500:" ",
40550:" ",
40600:" ",
40650:" ",
40700:" ",
40750:"",
40800:" ",
40850:" ",
40900:" ",
40950:" ",
41000:" ",
41050:" ",
41100:" ",
41150:" ",
41200:" ",
41250:"",
41300:" ",
41350:" ",
41400:" ",
41450:" ",
41500:" ",
41550:" ",
41600:" ",
41650:" ",
41700:" ",
41750:"",
41800:" ",
41850:" ",
41900:" ",
41950:" ",
42000:" ",
42050:" ",
42100:" ",
42150:" ",
42200:" ",
42250:"",
42300:" ",
42350:" ",
42400:" ",
42450:" ",
42500:" ",
42550:" ",
42600:" ",
42650:" ",
42700:" ",
42750:"",
42800:" ",
42850:" ",
42900:" ",
42950:" ",
43000:" ",
43050:" ",
43100:" ",
43150:" ",
43200:" ",
43250:"",
43300:" ",
43350:" ",
43400:" ",
43450:" ",
43500:" ",
43550:" ",
43600:" ",
43650:" ",
43700:" ",
43750:"",
43800:" ",
43850:" ",
43900:" ",
43950:" ",
44000:" ",
44050:" ",
44100:" ",
44150:" ",
44200:" ",
44250:"",
44300:" ",
44350:" ",
44400:" ",
44450:" ",
44500:" ",
44550:" ",
44600:" ",
44650:" ",
44700:" ",
44750:"",
44800:" ",
44850:" ",
44900:" ",
44950:" ",
45000:" ",
45050:" ",
45100:" ",
45150:" ",
45200:" ",
45250:"",
45300:" ",
45350:" ",
45400:" ",
45450:" ",
45500:" ",
45550:" ",
45600:" ",
45650:" ",
45700:" ",
45750:"",
45800:" ",
45850:" ",
45900:" ",
45950:" ",
46000:" ",
46050:" ",
46100:" ",
46150:" ",
46200:" ",
46250:"",
46300:" ",
46350:" ",
46400:" ",
46450:" ",
46500:" ",
46550:" ",
46600:" ",
46650:" ",
46700:" ",
46750:"",
46800:" ",
46850:" ",
46900:" ",
46950:" ",
47000:" ",
47050:" ",
47100:" ",
47150:" ",
47200:" ",
47250:"",
47300:" ",
47350:" ",
47400:" ",
47450:" ",
47500:" ",
47550:" ",
47600:" ",
47650:" ",
47700:" ",
47750:"",
47800:" ",
47850:" ",
47900:" ",
47950:" ",
48000:" ",

    
}

In [80]:
to_DEC60={
   50:"",
100:"",
150:"",
200:"",
250:"",
300:" ",
350:" ",
400:"",
450:" ",
500:"",
550:" ",
600:"ТО600",
650:" ",
700:" ",
750:"",
800:"",
850:" ",
900:" ",
950:" ",
1000:"",
1050:" ",
1100:" ",
1150:" ",
1200:"ТО1200",
1250:"",
1300:" ",
1350:" ",
1400:" ",
1450:"",
1500:"",
1550:" ",
1600:"",
1650:" ",
1700:" ",
1750:"",
1800:"ТО1800",
1850:" ",
1900:" ",
1950:" ",
2000:"",
2050:" ",
2100:" ",
2150:" ",
2200:"",
2250:"",
2300:" ",
2350:" ",
2400:"ТО2400",
2450:" ",
2500:"",
2550:" ",
2600:"",
2650:" ",
2700:" ",
2750:"",
2800:"",
2850:" ",
2900:" ",
2950:" ",
3000:"ТО600",
3050:" ",
3100:" ",
3150:" ",
3200:"",
3250:"",
3300:" ",
3350:" ",
3400:"",
3450:" ",
3500:"",
3550:" ",
3600:"ТО1200",
3650:" ",
3700:" ",
3750:"",
3800:"",
3850:" ",
3900:" ",
3950:" ",
4000:"",
4050:" ",
4100:" ",
4150:" ",
4200:"ТО600",
4250:"",
4300:" ",
4350:" ",
4400:"",
4450:" ",
4500:"",
4550:" ",
4600:"",
4650:" ",
4700:" ",
4750:"",
4800:"ТО1200",
4850:" ",
4900:" ",
4950:" ",
5000:"",
5050:" ",
5100:" ",
5150:" ",
5200:" ",
5250:"",
5300:" ",
5350:" ",
5400:"ТО1800",
5450:" ",
5500:"",
5550:" ",
5600:" ",
5650:" ",
5700:" ",
5750:"",
5800:" ",
5850:" ",
5900:" ",
5950:" ",
6000:"ТО1200",
6050:" ",
6100:" ",
6150:" ",
6200:" ",
6250:"",
6300:" ",
6350:" ",
6400:" ",
6450:" ",
6500:"",
6550:" ",
6600:"ТО600",
6650:" ",
6700:" ",
6750:"",
6800:" ",
6850:" ",
6900:" ",
6950:" ",
7000:"",
7050:" ",
7100:" ",
7150:" ",
7200:"ТО2400",
7250:"",
7300:" ",
7350:" ",
7400:" ",
7450:" ",
7500:"",
7550:" ",
7600:" ",
7650:" ",
7700:" ",
7750:"",
7800:"ТО600",
7850:" ",
7900:" ",
7950:" ",
8000:"",
8050:" ",
8100:" ",
8150:" ",
8200:" ",
8250:"",
8300:" ",
8350:" ",
8400:"ТО1200",
8450:" ",
8500:"",
8550:" ",
8600:" ",
8650:" ",
8700:" ",
8750:"",
8800:" ",
8850:" ",
8900:" ",
8950:" ",
9000:"ТО1800",
9050:" ",
9100:" ",
9150:" ",
9200:" ",
9250:"",
9300:" ",
9350:" ",
9400:" ",
9450:" ",
9500:"",
9550:" ",
9600:" ",
9650:" ",
9700:" ",
9750:"",
9800:" ",
9850:" ",
9900:" ",
9950:" ",
10000:"",
10050:" ",
10100:" ",
10150:" ",
10200:" ",
10250:"",
10300:" ",
10350:" ",
10400:" ",
10450:" ",
10500:" ",
10550:" ",
10600:" ",
10650:" ",
10700:" ",
10750:"",
10800:" ",
10850:" ",
10900:" ",
10950:" ",
11000:" ",
11050:" ",
11100:" ",
11150:" ",
11200:" ",
11250:"",
11300:" ",
11350:" ",
11400:" ",
11450:" ",
11500:" ",
11550:" ",
11600:" ",
11650:" ",
11700:" ",
11750:"",
11800:" ",
11850:" ",
11900:" ",
11950:" ",
12000:" ",
12050:" ",
12100:" ",
12150:" ",
12200:" ",
12250:"",
12300:" ",
12350:" ",
12400:" ",
12450:" ",
12500:" ",
12550:" ",
12600:" ",
12650:" ",
12700:" ",
12750:"",
12800:" ",
12850:" ",
12900:" ",
12950:" ",
13000:" ",
13050:" ",
13100:" ",
13150:" ",
13200:" ",
13250:"",
13300:" ",
13350:" ",
13400:" ",
13450:" ",
13500:" ",
13550:" ",
13600:" ",
13650:" ",
13700:" ",
13750:"",
13800:" ",
13850:" ",
13900:" ",
13950:" ",
14000:" ",
14050:" ",
14100:" ",
14150:" ",
14200:" ",
14250:"",
14300:" ",
14350:" ",
14400:" ",
14450:" ",
14500:" ",
14550:" ",
14600:" ",
14650:" ",
14700:" ",
14750:"",
14800:" ",
14850:" ",
14900:" ",
14950:" ",
15000:" ",
15050:" ",
15100:" ",
15150:" ",
15200:" ",
15250:"",
15300:" ",
15350:" ",
15400:" ",
15450:" ",
15500:" ",
15550:" ",
15600:" ",
15650:" ",
15700:" ",
15750:"",
15800:" ",
15850:" ",
15900:" ",
15950:" ",
16000:" ",
16050:" ",
16100:" ",
16150:" ",
16200:" ",
16250:"",
16300:" ",
16350:" ",
16400:" ",
16450:" ",
16500:" ",
16550:" ",
16600:" ",
16650:" ",
16700:" ",
16750:"",
16800:" ",
16850:" ",
16900:" ",
16950:" ",
17000:" ",
17050:" ",
17100:" ",
17150:" ",
17200:" ",
17250:"",
17300:" ",
17350:" ",
17400:" ",
17450:" ",
17500:" ",
17550:" ",
17600:" ",
17650:" ",
17700:" ",
17750:"",
17800:" ",
17850:" ",
17900:" ",
17950:" ",
18000:" ",
18050:" ",
18100:" ",
18150:" ",
18200:" ",
18250:"",
18300:" ",
18350:" ",
18400:" ",
18450:" ",
18500:" ",
18550:" ",
18600:" ",
18650:" ",
18700:" ",
18750:"",
18800:" ",
18850:" ",
18900:" ",
18950:" ",
19000:" ",
19050:" ",
19100:" ",
19150:" ",
19200:" ",
19250:"",
19300:" ",
19350:" ",
19400:" ",
19450:" ",
19500:" ",
19550:" ",
19600:" ",
19650:" ",
19700:" ",
19750:"",
19800:" ",
19850:" ",
19900:" ",
19950:" ",
20000:" ",
20050:" ",
20100:" ",
20150:" ",
20200:" ",
20250:"",
20300:" ",
20350:" ",
20400:" ",
20450:" ",
20500:" ",
20550:" ",
20600:" ",
20650:" ",
20700:" ",
20750:"",
20800:" ",
20850:" ",
20900:" ",
20950:" ",
21000:" ",
21050:" ",
21100:" ",
21150:" ",
21200:" ",
21250:"",
21300:" ",
21350:" ",
21400:" ",
21450:" ",
21500:" ",
21550:" ",
21600:" ",
21650:" ",
21700:" ",
21750:"",
21800:" ",
21850:" ",
21900:" ",
21950:" ",
22000:" ",
22050:" ",
22100:" ",
22150:" ",
22200:" ",
22250:"",
22300:" ",
22350:" ",
22400:" ",
22450:" ",
22500:" ",
22550:" ",
22600:" ",
22650:" ",
22700:" ",
22750:"",
22800:" ",
22850:" ",
22900:" ",
22950:" ",
23000:" ",
23050:" ",
23100:" ",
23150:" ",
23200:" ",
23250:"",
23300:" ",
23350:" ",
23400:" ",
23450:" ",
23500:" ",
23550:" ",
23600:" ",
23650:" ",
23700:" ",
23750:"",
23800:" ",
23850:" ",
23900:" ",
23950:" ",
24000:" ",
24050:" ",
24100:" ",
24150:" ",
24200:" ",
24250:"",
24300:" ",
24350:" ",
24400:" ",
24450:" ",
24500:" ",
24550:" ",
24600:" ",
24650:" ",
24700:" ",
24750:"",
24800:" ",
24850:" ",
24900:" ",
24950:" ",
25000:" ",
25050:" ",
25100:" ",
25150:" ",
25200:" ",
25250:"",
25300:" ",
25350:" ",
25400:" ",
25450:" ",
25500:" ",
25550:" ",
25600:" ",
25650:" ",
25700:" ",
25750:"",
25800:" ",
25850:" ",
25900:" ",
25950:" ",
26000:" ",
26050:" ",
26100:" ",
26150:" ",
26200:" ",
26250:"",
26300:" ",
26350:" ",
26400:" ",
26450:" ",
26500:" ",
26550:" ",
26600:" ",
26650:" ",
26700:" ",
26750:"",
26800:" ",
26850:" ",
26900:" ",
26950:" ",
27000:" ",
27050:" ",
27100:" ",
27150:" ",
27200:" ",
27250:"",
27300:" ",
27350:" ",
27400:" ",
27450:" ",
27500:" ",
27550:" ",
27600:" ",
27650:" ",
27700:" ",
27750:"",
27800:" ",
27850:" ",
27900:" ",
27950:" ",
28000:" ",
28050:" ",
28100:" ",
28150:" ",
28200:" ",
28250:"",
28300:" ",
28350:" ",
28400:" ",
28450:" ",
28500:" ",
28550:" ",
28600:" ",
28650:" ",
28700:" ",
28750:"",
28800:" ",
28850:" ",
28900:" ",
28950:" ",
29000:" ",
29050:" ",
29100:" ",
29150:" ",
29200:" ",
29250:"",
29300:" ",
29350:" ",
29400:" ",
29450:" ",
29500:" ",
29550:" ",
29600:" ",
29650:" ",
29700:" ",
29750:"",
29800:" ",
29850:" ",
29900:" ",
29950:" ",
30000:" ",
30050:" ",
30100:" ",
30150:" ",
30200:" ",
30250:"",
30300:" ",
30350:" ",
30400:" ",
30450:" ",
30500:" ",
30550:" ",
30600:" ",
30650:" ",
30700:" ",
30750:"",
30800:" ",
30850:" ",
30900:" ",
30950:" ",
31000:" ",
31050:" ",
31100:" ",
31150:" ",
31200:" ",
31250:"",
31300:" ",
31350:" ",
31400:" ",
31450:" ",
31500:" ",
31550:" ",
31600:" ",
31650:" ",
31700:" ",
31750:"",
31800:" ",
31850:" ",
31900:" ",
31950:" ",
32000:" ",
32050:" ",
32100:" ",
32150:" ",
32200:" ",
32250:"",
32300:" ",
32350:" ",
32400:" ",
32450:" ",
32500:" ",
32550:" ",
32600:" ",
32650:" ",
32700:" ",
32750:"",
32800:" ",
32850:" ",
32900:" ",
32950:" ",
33000:" ",
33050:" ",
33100:" ",
33150:" ",
33200:" ",
33250:"",
33300:" ",
33350:" ",
33400:" ",
33450:" ",
33500:" ",
33550:" ",
33600:" ",
33650:" ",
33700:" ",
33750:"",
33800:" ",
33850:" ",
33900:" ",
33950:" ",
34000:" ",
34050:" ",
34100:" ",
34150:" ",
34200:" ",
34250:"",
34300:" ",
34350:" ",
34400:" ",
34450:" ",
34500:" ",
34550:" ",
34600:" ",
34650:" ",
34700:" ",
34750:"",
34800:" ",
34850:" ",
34900:" ",
34950:" ",
35000:" ",
35050:" ",
35100:" ",
35150:" ",
35200:" ",
35250:"",
35300:" ",
35350:" ",
35400:" ",
35450:" ",
35500:" ",
35550:" ",
35600:" ",
35650:" ",
35700:" ",
35750:"",
35800:" ",
35850:" ",
35900:" ",
35950:" ",
36000:" ",
36050:" ",
36100:" ",
36150:" ",
36200:" ",
36250:"",
36300:" ",
36350:" ",
36400:" ",
36450:" ",
36500:" ",
36550:" ",
36600:" ",
36650:" ",
36700:" ",
36750:"",
36800:" ",
36850:" ",
36900:" ",
36950:" ",
37000:" ",
37050:" ",
37100:" ",
37150:" ",
37200:" ",
37250:"",
37300:" ",
37350:" ",
37400:" ",
37450:" ",
37500:" ",
37550:" ",
37600:" ",
37650:" ",
37700:" ",
37750:"",
37800:" ",
37850:" ",
37900:" ",
37950:" ",
38000:" ",
38050:" ",
38100:" ",
38150:" ",
38200:" ",
38250:"",
38300:" ",
38350:" ",
38400:" ",
38450:" ",
38500:" ",
38550:" ",
38600:" ",
38650:" ",
38700:" ",
38750:"",
38800:" ",
38850:" ",
38900:" ",
38950:" ",
39000:" ",
39050:" ",
39100:" ",
39150:" ",
39200:" ",
39250:"",
39300:" ",
39350:" ",
39400:" ",
39450:" ",
39500:" ",
39550:" ",
39600:" ",
39650:" ",
39700:" ",
39750:"",
39800:" ",
39850:" ",
39900:" ",
39950:" ",
40000:" ",
40050:" ",
40100:" ",
40150:" ",
40200:" ",
40250:"",
40300:" ",
40350:" ",
40400:" ",
40450:" ",
40500:" ",
40550:" ",
40600:" ",
40650:" ",
40700:" ",
40750:"",
40800:" ",
40850:" ",
40900:" ",
40950:" ",
41000:" ",
41050:" ",
41100:" ",
41150:" ",
41200:" ",
41250:"",
41300:" ",
41350:" ",
41400:" ",
41450:" ",
41500:" ",
41550:" ",
41600:" ",
41650:" ",
41700:" ",
41750:"",
41800:" ",
41850:" ",
41900:" ",
41950:" ",
42000:" ",
42050:" ",
42100:" ",
42150:" ",
42200:" ",
42250:"",
42300:" ",
42350:" ",
42400:" ",
42450:" ",
42500:" ",
42550:" ",
42600:" ",
42650:" ",
42700:" ",
42750:"",
42800:" ",
42850:" ",
42900:" ",
42950:" ",
43000:" ",
43050:" ",
43100:" ",
43150:" ",
43200:" ",
43250:"",
43300:" ",
43350:" ",
43400:" ",
43450:" ",
43500:" ",
43550:" ",
43600:" ",
43650:" ",
43700:" ",
43750:"",
43800:" ",
43850:" ",
43900:" ",
43950:" ",
44000:" ",
44050:" ",
44100:" ",
44150:" ",
44200:" ",
44250:"",
44300:" ",
44350:" ",
44400:" ",
44450:" ",
44500:" ",
44550:" ",
44600:" ",
44650:" ",
44700:" ",
44750:"",
44800:" ",
44850:" ",
44900:" ",
44950:" ",
45000:" ",
45050:" ",
45100:" ",
45150:" ",
45200:" ",
45250:"",
45300:" ",
45350:" ",
45400:" ",
45450:" ",
45500:" ",
45550:" ",
45600:" ",
45650:" ",
45700:" ",
45750:"",
45800:" ",
45850:" ",
45900:" ",
45950:" ",
46000:" ",
46050:" ",
46100:" ",
46150:" ",
46200:" ",
46250:"",
46300:" ",
46350:" ",
46400:" ",
46450:" ",
46500:" ",
46550:" ",
46600:" ",
46650:" ",
46700:" ",
46750:"",
46800:" ",
46850:" ",
46900:" ",
46950:" ",
47000:" ",
47050:" ",
47100:" ",
47150:" ",
47200:" ",
47250:"",
47300:" ",
47350:" ",
47400:" ",
47450:" ",
47500:" ",
47550:" ",
47600:" ",
47650:" ",
47700:" ",
47750:"",
47800:" ",
47850:" ",
47900:" ",
47950:" ",
48000:" ",

    
}

In [81]:
values=new_df['Планируемая наработка в момент проведения ТО']

In [82]:
values=list(range(50, 48000, 50))

In [83]:
new_df[['Марка','Модификация']].drop_duplicates()

                     Марка     Модификация
0                  CLG877H        LG G877H
206              CLG942EHD        LG-G942E
412                CLG975F        LG-G975F
824                  D-375              5D
618                  D-375               6
...                    ...             ...
57062                  ПСМ  ДНУ-1250/63-ЛП
57268                  ПСМ         ДНУ-630
57474  Платформа грузовая            ПГ-26
58092                  УАЗ          Хантер
58298                   ЭД             400

[145 rows x 2 columns]

In [84]:
new_df['Планируемая наработка в момент проведения ТО'] = new_df['Планируемая наработка в момент проведения ТО'].astype(str)
new_df['Планируемая наработка в момент проведения ТО'] = new_df['Планируемая наработка в момент проведения ТО'].str.replace(',', '.').astype(float)

In [85]:
#values = new_df['Планируемая наработка в момент проведения ТО']

for i in range(50, 48000, 50):
    if i in values:
       

        new_df.loc[new_df['Марка'].isin(['ДЭС-320','DCA-500SPK' ]) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict[i]
        new_df.loc[new_df['Марка'].isin(['ДЭС-320', 'DCA-500SPK']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_dict[i]
        
        new_df.loc[new_df['Модификация'].isin(['320','200','220']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict[i]
        new_df.loc[new_df['Модификация'].isin(['320','200','220']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_dict[i]

        new_df.loc[new_df['Модификация'].isin(['60']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_DEC60[i]
        new_df.loc[new_df['Модификация'].isin(['60']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_DEC60[i]

        new_df.loc[new_df['Модификация'].isin(['400']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict[i]
        new_df.loc[new_df['Модификация'].isin(['400']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_dict[i]
        
        new_df.loc[new_df['Марка'].isin(['АДД-4004']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_ADD_4004[i]
        new_df.loc[new_df['Марка'].isin(['АДД-4004']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_ADD_4004[i]
        
        new_df.loc[new_df['Модификация'].isin(['ДНУ-630']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_DHU_630_70_GCP[i]
        new_df.loc[new_df['Модификация'].isin(['ДНУ-630']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_DHU_630_70_GCP[i]
        
        new_df.loc[new_df['Модификация'].isin(['ДНУ-1250/63-ГСП']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_DHU_1250_63_GCP[i]
        new_df.loc[new_df['Модификация'].isin(['ДНУ-1250/63-ГСП']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_DHU_1250_63_GCP[i]

        new_df.loc[new_df['Модификация'].isin(['ДНУ-1250/63-ЛП']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_DHU_1250_63[i]
        new_df.loc[new_df['Модификация'].isin(['ДНУ-1250/63-ЛП']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_DHU_1250_63[i]
        
        new_df.loc[new_df['Марка'].isin(['ДНС-СВ-300-20']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_DHC_CB_300_20[i]
        new_df.loc[new_df['Марка'].isin(['ДНС-СВ-300-20']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_DHC_CB_300_20[i]
        
        new_df.loc[new_df['Модификация'].isin(['ДНС-СВ-32-22']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_DHC_CB_320_22[i]
        new_df.loc[new_df['Модификация'].isin(['ДНС-СВ-32-22']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_DHC_CB_320_22[i]

        new_df.loc[new_df['Модификация'].isin(['DNUDo-1600-75 ГСП (Doosan DP158LD) ','DNUDo-1600-75 ГСП (Doosan DP158LD)','DNUDO -1600/75']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_DNUDo_1600[i]
        new_df.loc[new_df['Модификация'].isin(['DNUDo-1600-75 ГСП (Doosan DP158LD) ','DNUDo-1600-75 ГСП (Doosan DP158LD)','DNUDO -1600/75']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_DNUDo_1600[i]

        new_df.loc[new_df['Модификация'].isin(['12НДС 1500ГК-01']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_12HDC[i]
        new_df.loc[new_df['Модификация'].isin(['12НДС 1500ГК-01']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_12HDC[i]

        new_df.loc[new_df['Марка'].isin(['D-375','D-375A','Компрессор']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i+20)), 'Планируемое техобслуживание'] = to_dict[i]
        new_df.loc[new_df['Марка'].isin(['D-375','D-375A','Компрессор']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_dict[i]

        new_df.loc[new_df['Марка'].isin(['D-475']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i+20)), 'Планируемое техобслуживание'] = to_dict475[i]
        new_df.loc[new_df['Марка'].isin(['D-475']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_dict475[i]

               
        new_df.loc[new_df['Марка'].isin(['PC-800','PC-1250','PC-750']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_PC[i]
        new_df.loc[new_df['Марка'].isin(['PC-800','PC-1250','PC-750']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_dict_PC[i]
        
        new_df.loc[new_df['Марка'].isin(['ZX-870']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_ZX[i]
        new_df.loc[new_df['Марка'].isin(['ZX-870']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] =  to_dict_ZX[i]

        new_df.loc[new_df['Марка'].isin(['HD-465']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_HD[i]
        new_df.loc[new_df['Марка'].isin(['HD-465']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] =   to_dict_HD[i]

        
                
        new_df.loc[new_df['Марка'].isin(['DM-45']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_DM[i]
        new_df.loc[new_df['Марка'].isin(['DM-45']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] =   to_dict_DM[i]
        
        new_df.loc[new_df['Марка'].isin(['JD-2000']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_JD[i]
        new_df.loc[new_df['Марка'].isin(['JD-2000']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] =   to_dict_JD[i]

        new_df.loc[new_df['Марка'].isin(['WA-470']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_WA470[i]
        new_df.loc[new_df['Марка'].isin(['WA-470']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] =   to_dict_WA470[i]

        new_df.loc[new_df['Марка'].isin(['WD-600', 'WA-600']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_WD[i]
        new_df.loc[new_df['Марка'].isin(['WD-600', 'WA-600']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] =   to_dict_WD[i]

        new_df.loc[new_df['Марка'].isin(['TM10.11 ГСТ10','TM10.11 ГСТ12']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_TM[i]
        new_df.loc[new_df['Марка'].isin(['TM10.11 ГСТ10','TM10.11 ГСТ12']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] =   to_dict_TM[i]

        new_df.loc[new_df['Марка'].isin(['ECD50E']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_ECD50E[i]
        new_df.loc[new_df['Марка'].isin(['ECD50E']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] =   to_dict_ECD50E[i]

        new_df.loc[new_df['Марка'].isin(['БелАЗ']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_7547[i]
        new_df.loc[new_df['Марка'].isin(['БелАЗ']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] =   to_dict_7547[i]

        new_df.loc[new_df['Модификация'].isin(['7555B']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_7555[i]
        new_df.loc[new_df['Модификация'].isin(['7555B']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] =   to_dict_7555[i]

        new_df.loc[new_df['Марка'].isin(['TD-16']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_TD16[i]
        new_df.loc[new_df['Марка'].isin(['TD-16']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] =   to_dict_TD16[i]

        new_df.loc[new_df['Марка'].isin(['D-65']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_D65[i]
        new_df.loc[new_df['Марка'].isin(['D-65']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] =   to_dict_D65[i]

        new_df.loc[new_df['Марка'].isin(['PC-400']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_PC400[i]
        new_df.loc[new_df['Марка'].isin(['PC-400']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_dict_PC400[i]

        new_df.loc[new_df['Марка'].isin(['CASE']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_case[i]
        new_df.loc[new_df['Марка'].isin(['CASE']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_dict_case[i]

        new_df.loc[new_df['Марка'].isin(['SL50W', ]) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_sl[i]
        new_df.loc[new_df['Марка'].isin(['SL50W',]) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_dict_sl[i]

        new_df.loc[new_df['Марка'].isin(['Б-11']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_b11[i]
        new_df.loc[new_df['Марка'].isin(['Б-11']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_dict_b11[i]

        new_df.loc[new_df['Марка'].isin(['СБШ-250']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_sbh[i]
        new_df.loc[new_df['Марка'].isin(['СБШ-250']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_dict_sbh[i]

        new_df.loc[new_df['Марка'].isin(['ДНУ-1250/63-ГСП', 'ДНУ-630/70-ГСП']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_DNU[i]
        new_df.loc[new_df['Марка'].isin(['ДНУ-1250/63-ГСП','ДНУ-630/70-ГСП']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_dict_DNU[i]

        new_df.loc[new_df['Марка'].isin(['DNUDo-1600/75-ГСП']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_DNU_1600[i]
        new_df.loc[new_df['Марка'].isin(['DNUDo-1600/75-ГСП']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_dict_DNU_1600[i]
        
        new_df.loc[new_df['Марка'].isin(['DCA-220SPK3','DCA-500SPK']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_DCA[i]
        new_df.loc[new_df['Марка'].isin(['DCA-220SPK3','DCA-500SPK']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_dict_DCA[i]
        
        new_df.loc[new_df['Марка'].isin(['АД200С']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_DCA_AD200[i]
        new_df.loc[new_df['Марка'].isin(['АД200С']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_dict_DCA_AD200[i]

        new_df.loc[new_df['Марка'].isin(['ЭД30Е']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_DCA_ED30[i]
        new_df.loc[new_df['Марка'].isin(['ЭД30Е']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_dict_DCA_ED30[i]

        new_df.loc[new_df['Марка'].isin(['ЭД200С']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_DCA_AD200[i]
        new_df.loc[new_df['Марка'].isin(['ЭД200С']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_dict_DCA_AD200[i]

        new_df.loc[new_df['Марка'].isin(['D55']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_D55[i]
        new_df.loc[new_df['Марка'].isin(['D55']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_dict_D55[i]

        new_df.loc[new_df['Марка'].isin(['SD22']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_SD22[i]
        new_df.loc[new_df['Марка'].isin(['SD22']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_dict_SD22[i]

        new_df.loc[new_df['Марка'].isin(['SG21A_3']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_dict_SG21A_3[i]
        new_df.loc[new_df['Марка'].isin(['SG21A_3']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_dict_SG21A_3[i]

        new_df.loc[new_df['Марка'].isin(['CLG975F']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_CLG975F[i]
        new_df.loc[new_df['Марка'].isin(['CLG975F']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_CLG975F[i]

        new_df.loc[new_df['Марка'].isin(['CLG877H']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_CLG877H[i]
        new_df.loc[new_df['Марка'].isin(['CLG877H']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_CLG877H[i]

        new_df.loc[new_df['Марка'].isin(['CLG942EHD']) & ((new_df['Планируемая наработка в момент проведения ТО'] > i) & (new_df['Планируемая наработка в момент проведения ТО'] < i + 20)), 'Планируемое техобслуживание'] = to_CLG942EHD[i]
        new_df.loc[new_df['Марка'].isin(['CLG942EHD']) & ((new_df['Планируемая наработка в момент проведения ТО'] == i)), 'Планируемое техобслуживание'] = to_CLG942EHD[i]

In [184]:
mask=new_df["Марка"]=='Shantui '
new_df.loc[mask]

Empty DataFrame
Columns: [index, Подразделение, Марка, Модификация, Инвентарный номер, Дата начала обслуживания, Наработка машины, Фактическая наработка в момент проведения ТО, Дата планирования, Дата, Планируемая наработка в момент проведения ТО, Планируемое техобслуживание]
Index: []

[0 rows x 12 columns]

In [185]:
new_df.head(10)

,index,Подразделение,Марка,Модификация,Инвентарный номер,...,Фактическая наработка в момент проведения ТО,Дата планирования,Дата,Планируемая наработка в момент проведения ТО,Планируемое техобслуживание
0,0,Дражный,CLG877H,LG G877H,1249,...,"1,700",2026-12-23,2026-06-01,"1,700",
1,0,Дражный,CLG877H,LG G877H,1249,...,"1,700",2026-12-23,2026-06-02,"1,720",NaN
2,0,Дражный,CLG877H,LG G877H,1249,...,"1,700",2026-12-23,2026-06-03,"1,740",NaN
3,0,Дражный,CLG877H,LG G877H,1249,...,"1,700",2026-12-23,2026-06-04,"1,760",ТО250
4,0,Дражный,CLG877H,LG G877H,1249,...,"1,700",2026-12-23,2026-06-05,"1,780",NaN
5,0,Дражный,CLG877H,LG G877H,1249,...,"1,700",2026-12-23,2026-06-06,"1,800",
6,0,Дражный,CLG877H,LG G877H,1249,...,"1,700",2026-12-23,2026-06-07,"1,820",NaN
7,0,Дражный,CLG877H,LG G877H,1249,...,"1,700",2026-12-23,2026-06-08,"1,840",NaN
8,0,Дражный,CLG877H,LG G877H,1249,...,"1,700",2026-12-23,2026-06-09,"1,860",
9,0,Дражный,CLG877H,LG G877H,1249,...,"1,700",2026-12-23,2026-06-10,"1,880",NaN

In [186]:
# p=new_df.loc[
#            new_df['Марка']
#            .astype(str)
#            .str.contains('375', case=False, na=False),
#               ['Марка', 'Модификация','Инвентарный номер']
#            ].drop_duplicates()

p=new_df[['Марка', 'Модификация']].drop_duplicates()
p

                     Марка      Модификация
0                  CLG877H         LG G877H
206              CLG942EHD         LG-G942E
412                CLG975F         LG-G975F
618                  D-375               5D
824                  D-375               6R
...                    ...              ...
52324     Насосная станция     ДНС-СВ-32-22
52530     Насосная станция  ДНУ-1250/63-ГСП
52736     Насосная станция   ДНУ-1250/63-ЛП
52942     Насосная станция          ДНУ-630
53148  Платформа грузовая             ПГ-26

[134 rows x 2 columns]

In [187]:
mask=(new_df['Марка']=='Насосная станция')&(new_df['Модификация']=='ДНС-СВ-32-22')
new_df.loc[mask,'Модификация']='320-22'
new_df.loc[mask,'Марка']='ДНС-СВ'

mask=(new_df['Марка']=='TM10.11 ГСТ12')&(new_df['Модификация']=='1')
new_df.loc[mask,'Модификация']='ГСТ12'
new_df.loc[mask,'Марка']='ТМ10.11'

mask=(new_df['Марка']=='АДД-4004')
new_df.loc[mask,'Модификация']='Д-243'
new_df.loc[mask,'Марка']='АДД-4004'

mask=(new_df['Марка']=='PC-750')
new_df.loc[mask,'Модификация']='8'
new_df.loc[mask,'Марка']='РС 800 8E0'

mask=(new_df['Марка']=='ДЭС')&(new_df['Модификация']=='320')
new_df.loc[mask,'Модификация']='2306CE14TAG3'
new_df.loc[mask,'Марка']='Wilson 320'

mask=(new_df['Марка']=='ДЭС')&(new_df['Модификация']=='400')
new_df.loc[mask,'Модификация']='DC13 072A'
new_df.loc[mask,'Марка']='ЭД400'

mask=(new_df['Марка']=='Компрессор')&(new_df['Модификация']=='LUY100-12')
new_df.loc[mask,'Модификация']='12'
new_df.loc[mask,'Марка']='LUY100-12'

mask=(new_df['Марка']=='ДЭС')&(new_df['Модификация']=='60')
new_df.loc[mask,'Модификация']='NEF45SM3.S500'
new_df.loc[mask,'Марка']='ДЭС-60'


mask=(new_df['Марка']=='Насосная станция')&(new_df['Модификация']=='ДНУ-630')
new_df.loc[mask,'Модификация']='ЯМЗ-238ДИ'
new_df.loc[mask,'Марка']='ДНУ-630/70-ГСП'

mask=(new_df['Марка']=='Насосная станция')&(new_df['Модификация']=='ДНУ-1250/63-ЛП')
new_df.loc[mask,'Модификация']='ЛП ЯМЗ-7514'
new_df.loc[mask,'Марка']='ДНУ-1250/63'

mask=(new_df['Марка']=='Насосная станция')&(new_df['Модификация']=='ДНУ-1250/63-ГСП')
new_df.loc[mask,'Модификация']='ГСП ЯМЗ-7514'
new_df.loc[mask,'Марка']='ДНУ-1250/63-ГСП'

mask=(new_df['Марка']=='WA-600')
new_df.loc[mask,'Модификация']='6'
new_df.loc[mask,'Марка']='WA 600-6'

mask=(new_df['Марка']=='WD-600')
new_df.loc[mask,'Модификация']='6'
new_df.loc[mask,'Марка']='WD 600 6'

mask=(new_df['Марка']=='TM10.11 ГСТ10')
new_df.loc[mask,'Модификация']='ГСТ10'
new_df.loc[mask,'Марка']='ТМ10.11'

mask=(new_df['Марка']=='ТМ10.10')&(new_df['Модификация']=='ГСТ9')
new_df.loc[mask,'Модификация']='ГСТ9'
new_df.loc[mask,'Марка']='ТМ10.10'

mask=(new_df['Марка']=='CASE')
new_df.loc[mask,'Модификация']='CX-800B'
new_df.loc[mask,'Марка']='CASE CX-800B'

mask=(new_df['Марка']=='D-475')
new_df.loc[mask,'Модификация']='A-5'
new_df.loc[mask,'Марка']='D 475 A-5'

mask=(new_df['Марка']=='Насосная станция')&(new_df['Модификация']=='DNUDo-1600-75 ГСП (Doosan DP158LD)')
new_df.loc[mask,'Модификация']='DP158LD'
new_df.loc[mask,'Марка']='DNUDo-1600/75-ГСП'

mask=(new_df['Марка']=='Насосная станция')&(new_df['Модификация']=='DNUDO -1600/75')
new_df.loc[mask,'Модификация']='DP158LD'
new_df.loc[mask,'Марка']='DNUDo-1600/75-ГСП'

mask=(new_df['Марка']=='Насосная станция')&(new_df['Модификация']=='DNUDo-1600-75 ГСП (Doosan DP158LD) ')
new_df.loc[mask,'Модификация']='DP158LD'
new_df.loc[mask,'Марка']='DNUDo-1600/75-ГСП'

mask=(new_df['Марка']=='HD-465')
new_df.loc[mask,'Модификация']='7R'
new_df.loc[mask,'Марка']='HD 465-7R'

mask=new_df['Марка']=='DM-45'
new_df.loc[mask,'Марка']='DM45 HP'

keys=[791,917,967]
values=[791,917,967]

for keys, values in zip(keys, values):
    new_df.loc[new_df['Инвентарный номер'].eq(keys), 'Модификация']=values

mask=new_df['Марка']=='CLG877H'
new_df.loc[mask,'Модификация']='H'

mask=new_df['Марка']=='CLG942EHD'
new_df.loc[mask,'Модификация']='EHD'

mask=new_df['Марка']=='CLG975F'
new_df.loc[mask,'Модификация']='F'

mask=new_df['Инвентарный номер'].isin([697,721,720,677,719,717,675,678,716])
new_df.loc[mask,'Модификация']='5D'
new_df.loc[mask,'Марка']='D 375 А-5D'

mask=new_df['Инвентарный номер'].isin([688,818,916,915,902,603,679,1161,602])
new_df.loc[mask,'Модификация']='6'
new_df.loc[mask,'Марка']='D 375 A-6'

mask=new_df['Инвентарный номер'].isin([1148,1145,1160])
new_df.loc[mask,'Модификация']='6R'
new_df.loc[mask,'Марка']='D 375 А-6R'

mask=new_df['Инвентарный номер'].isin([1371])
new_df.loc[mask,'Модификация']='8'
new_df.loc[mask,'Марка']='D 375 А-8'

mask=new_df['Марка']=='PC-400'
new_df.loc[mask,'Модификация']='7'
new_df.loc[mask,'Марка']='РС 400-7'

mask=new_df['Марка'].isin(['PC-800','PC-800'])
new_df.loc[mask,'Модификация']='8'
new_df.loc[mask,'Марка']='РС 800 8E0'

mask=new_df['Марка']=='WA-470'
new_df.loc[mask,'Модификация']='3'
new_df.loc[mask,'Марка']='WA 470-3'

mask=new_df['Инвентарный номер'].isin([661,1080,1081,1083,1084,1156,1186,330,1152,658,1151,660,1187,573,659,1150,1153,1154,1155,333,574,575,600,601,1157,1158,1159])
new_df.loc[mask,'Модификация']='7547'
new_df.loc[mask,'Марка']='БелАЗ 7547'

mask=new_df['Инвентарный номер'].isin([1204,1238,1311,1312,789,790])
new_df.loc[mask,'Модификация']='7555В'
new_df.loc[mask,'Марка']='БелАЗ 7555В'

mask=(new_df['Марка']=='ДЭС')&(new_df['Модификация']=='220')
new_df.loc[mask,'Модификация']='S6D125E-2'
new_df.loc[mask,'Марка']='DCA-220SPK3'

mask=(new_df['Марка']=='ДЭС')&(new_df['Модификация'].isin(['200', '1']))
new_df.loc[mask,'Модификация']='DC09 072A'
new_df.loc[mask,'Марка']='ДЭС-200'

mask=(new_df['Марка']=='ДЭС')&(new_df['Модификация']=='201')
new_df.loc[mask,'Модификация']='DC09 072A'
new_df.loc[mask,'Марка']='ДЭС-200'

mask=(new_df['Марка']=='ДЭС')&(new_df['Модификация']=='378')
new_df.loc[mask,'Модификация']='378'
new_df.loc[mask,'Марка']='DPK-DC-378'

mask=(new_df['Марка']=='ECD50E')&(new_df['Модификация']=='0')
new_df.loc[mask,'Модификация']='1'
new_df.loc[mask,'Марка']='ECD50E'

mask=(new_df['Марка']=='FG Wilson P150-1')&(new_df['Модификация']=='150')
new_df.loc[mask,'Модификация']='P150-1'
new_df.loc[mask,'Марка']='FG Wilson P150-1'

mask=(new_df['Марка']=='D-65')
new_df.loc[mask,'Модификация']='EX-16'
new_df.loc[mask,'Марка']='D 65EX-16'

mask=(new_df['Марка']=='Насосная станция')&(new_df['Модификация']=='ДНС-СВ-300-20')
new_df.loc[mask,'Модификация']='300-20'
new_df.loc[mask,'Марка']='ДНС-СВ'

mask=(new_df['Марка']=='Насосная станция')&(new_df['Модификация']=='12НДС 1500ГК-01')
new_df.loc[mask,'Модификация']='12НДС'
new_df.loc[mask,'Марка']='1500ГК-01'

mask=(new_df['Марка']=='ДНУ ПМС')&(new_df['Модификация']=='ДНУ-1250/63-ЛП')
new_df.loc[mask,'Модификация']='ЛП ЯМЗ-7514'
new_df.loc[mask,'Марка']='ДНУ-1250/63'

mask=(new_df['Марка']=='ДЭС')&(new_df['Модификация']=='100')
new_df.loc[mask,'Модификация']='6BTAA5,9-G2'
new_df.loc[mask,'Марка']='АД100С'

mask=(new_df['Марка']=='ДЭС')&(new_df['Модификация']=='30')
new_df.loc[mask,'Модификация']='Д-243'
new_df.loc[mask,'Марка']='АД-30С'

mask=(new_df['Марка']=='D55')
new_df.loc[mask,'Модификация']='1'
new_df.loc[mask,'Марка']='PRD55'

mask=(new_df['Марка']=='JD-2000')
new_df.loc[mask,'Модификация']='1'
new_df.loc[mask,'Марка']='JD-2000'

mask=(new_df['Марка']=='PC-1250')
new_df.loc[mask,'Модификация']='8'
new_df.loc[mask,'Марка']='PC 1250-8'

In [188]:
p=new_df[['Марка', 'Модификация']].drop_duplicates()
p

                     Марка   Модификация
0                  CLG877H             H
206              CLG942EHD           EHD
412                CLG975F             F
618             D 375 А-5D            5D
824             D 375 А-6R            6R
...                    ...           ...
51912            LUY100-12            12
52324               ДНС-СВ        320-22
52530      ДНУ-1250/63-ГСП  ГСП ЯМЗ-7514
52942       ДНУ-630/70-ГСП     ЯМЗ-238ДИ
53148  Платформа грузовая          ПГ-26

[123 rows x 2 columns]

##### === ставим первоначальную наработку ===

In [189]:
df_narabotka

,Подразделение,Тип машины,Марка,Модификация,Инвентарный номер,...,Замечания проверяющего,Отметка об утверждении акта (ФИО утвердившего),Дата утверждения,Месяц_ном,Год
21,Дымный,Бульдозер,TD-16,NaN,902,...,NaN,NaN,NaN,3,"2,025"
22,Дымный,Бульдозер,TD-16,NaN,902,...,NaN,NaN,NaN,3,"2,025"
23,Дымный,Бульдозер,TD-16,NaN,902,...,NaN,NaN,NaN,3,"2,025"
24,Дымный,Бульдозер,TD-16,NaN,902,...,NaN,NaN,NaN,3,"2,025"
25,Дымный,Экскаватор,PC-800,8,913,...,NaN,NaN,NaN,3,"2,025"
...,...,...,...,...,...,...,...,...,...,...,...
2234,Обман,Автозаправщик,КАМАЗ АТЗ,43118,1092,...,NaN,NaN,NaN,10,"2,025"
2235,Обман,Водовозка,КАМАЗ,43118,956,...,NaN,NaN,NaN,10,"2,025"
2236,Обман,Автокран,УРАЛ автокран,4320-5557,297,...,NaN,NaN,NaN,10,"2,025"
2237,Обман,Автокран,УРАЛ автокран,4320-5557,297,...,NaN,NaN,NaN,10,"2,025"
2238,Обман,Грузовой бортовой,ГАЗ САДКО,3897G1,1336,...,NaN,NaN,NaN,10,"2,025"

In [190]:
df = df_narabotka.copy()

df['Дата начала обслуживания'] = pd.to_datetime(df['Дата начала обслуживания'], errors='coerce')
df['Наработка машины'] = pd.to_numeric(df['Наработка машины'], errors='coerce')
df['Фактическая наработка в момент проведения ТО'] = pd.to_numeric(df['Фактическая наработка в момент проведения ТО'], errors='coerce')

cols_keep = ['Марка','Модификация','Инвентарный номер',
             'Фактическая наработка в момент проведения ТО','Наработка машины','Дата начала обслуживания']

pivot_table = (
    df.sort_values(['Инвентарный номер','Дата начала обслуживания',
                    'Фактическая наработка в момент проведения ТО','Наработка машины'])
      .drop_duplicates(subset=['Инвентарный номер'], keep='first')   # <-- по каждому инв. номеру одна строка
      [cols_keep]
      .reset_index(drop=True)
)

In [191]:
pivot_table

,Марка,Модификация,Инвентарный номер,Фактическая наработка в момент проведения ТО,Наработка машины,Дата начала обслуживания
0,Hiace,NaN,43,NaN,NaN,2025-05-07
1,КАМАЗ,43114,47,NaN,NaN,2025-03-06
2,КАМАЗ автобус,43114,51,NaN,NaN,2025-04-02
3,Сварочный агрегат,NaN,101,NaN,NaN,2025-07-06
4,ДЭС,30,126,"5,098","5,098",2025-04-02
...,...,...,...,...,...,...
254,Насосная станция,12НДС 1500ГК-01,1357,50,50,2025-07-09
255,SHACMAN с КМУ,NaN,1365,308,308,2025-07-27
256,ТАНКЕР -Л-330,0,1370,100,100,2025-09-13
257,D-375,8-А,1371,500,500,2025-08-01
258,ТАНКЕР-Л-330,NaN,<NA>,NaN,NaN,2025-03-01

In [192]:
svod_narabotka=new_df.copy()

In [193]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 53766 entries, 0 to 53765
Data columns (total 12 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   index                                         53766 non-null  int64
 1   Подразделение                                 53766 non-null  object
 2   Марка                                         53766 non-null  object
 3   Модификация                                   53766 non-null  object
 4   Инвентарный номер                             53766 non-null  Int64
 5   Дата начала обслуживания                      53766 non-null  datetime64[ns]
 6   Наработка машины                              53766 non-null  object
 7   Фактическая наработка в момент проведения ТО  53766 non-null  object
 8   Дата планирования                             53766 non-null  datetime64[ns]
 9   Дата                                          53766 non-null  datetime64[ns]
 10  Планируемая наработка в момент проведения ТО  53766 non-null  float64
 11  Планируемое техобслуживание                   13282 non-null  object
dtypes: Int64(1), datetime64[ns](3), float64(1), int64(1), object(6)
memory usage: 5.4+ MB

In [194]:
pivot_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 259 entries, 0 to 258
Data columns (total 6 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Марка                                         259 non-null    object
 1   Модификация                                   210 non-null    object
 2   Инвентарный номер                             258 non-null    Int64
 3   Фактическая наработка в момент проведения ТО  208 non-null    float64
 4   Наработка машины                              208 non-null    float64
 5   Дата начала обслуживания                      259 non-null    datetime64[ns]
dtypes: Int64(1), datetime64[ns](1), float64(2), object(2)
memory usage: 12.5+ KB

In [195]:
to_join = (pivot_table[['Инвентарный номер','Дата начала обслуживания','Наработка машины']]
           .drop_duplicates('Инвентарный номер', keep='first')
           .rename(columns={'Дата начала обслуживания': 'Дата ТО (мин)', 'Наработка машины':'Первоначальная наработка'}))

# убедимся, что типы совпадают
new_df['Инвентарный номер'] = pd.to_numeric(new_df['Инвентарный номер'], errors='coerce')
to_join['Инвентарный номер'] = pd.to_numeric(to_join['Инвентарный номер'], errors='coerce')

result = new_df.merge(to_join, how='left', on='Инвентарный номер')

In [196]:
to_join

     Инвентарный номер Дата ТО (мин)  Первоначальная наработка
0                   43    2025-05-07                       NaN
1                   47    2025-03-06                       NaN
2                   51    2025-04-02                       NaN
3                  101    2025-07-06                       NaN
4                  126    2025-04-02                     5,098
..                 ...           ...                       ...
254               1357    2025-07-09                        50
255               1365    2025-07-27                       308
256               1370    2025-09-13                       100
257               1371    2025-08-01                       500
258               <NA>    2025-03-01                       NaN

[259 rows x 3 columns]

In [197]:
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53766 entries, 0 to 53765
Data columns (total 14 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   index                                         53766 non-null  int64
 1   Подразделение                                 53766 non-null  object
 2   Марка                                         53766 non-null  object
 3   Модификация                                   53766 non-null  object
 4   Инвентарный номер                             53766 non-null  Int64
 5   Дата начала обслуживания                      53766 non-null  datetime64[ns]
 6   Наработка машины                              53766 non-null  object
 7   Фактическая наработка в момент проведения ТО  53766 non-null  object
 8   Дата планирования                             53766 non-null  datetime64[ns]
 9   Дата                                          53766 non-null  datetime64[ns]
 10  Планируемая наработка в момент проведения ТО  53766 non-null  float64
 11  Планируемое техобслуживание                   13282 non-null  object
 12  Дата ТО (мин)                                 53766 non-null  datetime64[ns]
 13  Первоначальная наработка                      46144 non-null  float64
dtypes: Int64(1), datetime64[ns](4), float64(2), int64(1), object(6)
memory usage: 5.8+ MB

In [198]:
result=result.loc[result['Дата']<=pd.Timestamp('2026-10-01')]

In [199]:
cols = ['Планируемая наработка в момент проведения ТО', 'Наработка машины']

def to_float(s: pd.Series) -> pd.Series:
    s = s.astype(str).str.strip()
    # Если ячейка — только тире/длинное тире -> NaN
    s = s.replace({r'^\s*[–—−-]+\s*$': np.nan}, regex=True)
    # Разные минусы к обычному
    s = s.str.replace('\u2212', '-', regex=False).str.replace('\u2013', '-', regex=False).str.replace('\u2014', '-', regex=False)
    # Убираем пробелы/неразрывные, меняем запятую на точку
    s = s.str.replace('\xa0', '', regex=False).str.replace(' ', '', regex=False).str.replace(',', '.', regex=False)
    # Оставляем только цифры, точку и минус (уберёт 'ч', 'м/ч' и т.п.)
    s = s.str.replace(r'[^0-9\.\-]', '', regex=True)
    return pd.to_numeric(s, errors='coerce')

for c in cols:
    result[c + '_num'] = to_float(result[c])

result['Наработка 2026'] = result[cols[0] + '_num'] - result[cols[1] + '_num']

In [200]:
#2500
work = pd.to_numeric(result['Наработка 2026'], errors='coerce')
fit = result['Инвентарный номер'].isin([1249, 967, 1024,1199, 1202,1094,719, 791, 917,1304,1091])
result = result.loc[~fit | (work < 2500)].copy()

#3600
work = pd.to_numeric(result['Наработка 2026'], errors='coerce')
fit = result['Инвентарный номер'].isin([1251,697, 1148,  ])
result = result.loc[~fit | (work < 3600)].copy()

#3000
work = pd.to_numeric(result['Наработка 2026'], errors='coerce')
fit = result['Инвентарный номер'].isin([574,575,600,601,1157,1158,1159,1204,1238,792,793,1086,1087,1088,1089,1090,900,903,1160,805,901 ])
result = result.loc[~fit | (work < 3000)].copy()

#2000
work = pd.to_numeric(result['Наработка 2026'], errors='coerce')
fit = result['Инвентарный номер'].isin([1006,1228,680,804,1185,1183,711,912,1250,1184,1253,476,596])
result = result.loc[~fit | (work < 2000)].copy()

#1000
work = pd.to_numeric(result['Наработка 2026'], errors='coerce')
fit = result['Инвентарный номер'].isin([963,1357,919,1127,681,126,1005,811,1115,1203,595,1067,498,810,400,652,653,819,1007,684,918,830])
result = result.loc[~fit | (work < 1000)].copy()

In [201]:
result.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44563 entries, 0 to 53765
Data columns (total 17 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   index                                             44563 non-null  int64
 1   Подразделение                                     44563 non-null  object
 2   Марка                                             44563 non-null  object
 3   Модификация                                       44563 non-null  object
 4   Инвентарный номер                                 44563 non-null  Int64
 5   Дата начала обслуживания                          44563 non-null  datetime64[ns]
 6   Наработка машины                                  44563 non-null  object
 7   Фактическая наработка в момент проведения ТО      44563 non-null  object
 8   Дата планирования                                 44563 non-null  datetime64[ns]
 9   Дата                                              44563 non-null  datetime64[ns]
 10  Планируемая наработка в момент проведения ТО      44563 non-null  float64
 11  Планируемое техобслуживание                       10130 non-null  object
 12  Дата ТО (мин)                                     44563 non-null  datetime64[ns]
 13  Первоначальная наработка                          37255 non-null  float64
 14  Планируемая наработка в момент проведения ТО_num  44563 non-null  float64
 15  Наработка машины_num                              44563 non-null  int64
 16  Наработка 2026                                    44563 non-null  float64
dtypes: Int64(1), datetime64[ns](4), float64(4), int64(2), object(6)
memory usage: 6.2+ MB

# === план по проведению ТО закончен ===

In [203]:
result.to_excel('result.xlsx',sheet_name='Расфасовка', index=False)

In [ ]:
control=new_df.copy()

In [ ]:
new_df=control.copy()

In [ ]:
new_df = new_df.reset_index(drop=True)

In [ ]:
for i, row in new_df.iterrows():
    
    if i>=1:     
        if  ((new_df.loc[i,"Инвентарный номер"]==new_df.loc[i-1,"Инвентарный номер"])& \
            (new_df.loc[i,"Марка"]==new_df.loc[i-1,"Марка"])& \
            (new_df.loc[i,"Планируемое техобслуживание"]!=new_df.loc[i-1,"Планируемое техобслуживание"])
            ):
                new_df.loc[i,"Планируемое техобслуживание++"]=new_df.loc[i,"Планируемое техобслуживание"]

In [ ]:
new_df

In [ ]:
def concat(*args):
    strs = [str(arg) for arg in args if not pd.isnull(arg)]
    return ','.join(strs) if strs else np.nan
np_concat = np.vectorize(concat)

In [ ]:
np_concat(new_df['Планируемое техобслуживание++'], new_df['Наработка совпала'].astype(str))

In [ ]:
new_df['Наработка совпала'].unique()

In [ ]:
new_df['Планируемое техобслуживание+++'] = np_concat(new_df['Планируемое техобслуживание++'], new_df['Наработка совпала'].astype(str))

In [ ]:
new_df

In [ ]:
new_df["Дата"]=new_df['Дата планирования']

In [ ]:
new_df=new_df.drop(['Дата начала обслуживания','Дата планирования','Планируемое техобслуживание','Наработка совпала','Планируемое техобслуживание++'], axis=1)

In [ ]:
new_df.rename(columns={'Планируемое техобслуживание+++': 'Планируемое техобслуживание'}, inplace=True)

In [ ]:
new_df=new_df.fillna('')

In [ ]:
new_df

In [ ]:
new_df['Планируемое техобслуживание']=new_df['Планируемое техобслуживание'].fillna('пусто')

In [ ]:
new_df=new_df.loc[new_df['Планируемое техобслуживание']!='nan']

In [ ]:
# Преобразование столбца 'Дата' в тип данных datetime
new_df['Дата'] = pd.to_datetime(new_df['Дата'])

In [ ]:
new_df['Номер месяца'] = new_df['Дата'].dt.month.astype(int)

In [ ]:
new_df['Планируемое техобслуживание'] = new_df['Планируемое техобслуживание'].fillna('').str.replace(',nan', '')

In [ ]:
df.columns

Здесь происходит сравнение, с какой точки анчинать отсчет t. Мы его задавали в первых ячейках

In [ ]:
new_df = new_df.loc[(new_df['Дата'] >= t) & (new_df['Планируемое техобслуживание'] != '')]

In [ ]:
new_df.columns

In [ ]:
new_df.rename(columns={'Наработка машины': 'Текущая наработка'}, inplace=True)

In [ ]:
print(new_df['Дата'].apply(type).unique())

In [ ]:
control2=new_df.copy()

In [ ]:
control2

In [ ]:
new_df

In [ ]:
smurf=(
    (new_df['Инвентарный номер']==new_df['Инвентарный номер'].shift(1))&
    ((new_df['Планируемая наработка в момент проведения ТО']-new_df['Планируемая наработка в момент проведения ТО'].shift(1))<20)&
    (new_df['Планируемое техобслуживание']==new_df['Планируемое техобслуживание'].shift(1)))
new_df['Планируемое техобслуживание']=np.where(smurf, "", new_df["Планируемое техобслуживание"])

In [ ]:
pivot_table = pd.pivot_table(new_df, values={'Планируемое техобслуживание' }, 
                             index=['Подразделение', 'Марка', 'Инвентарный номер','Текущая наработка' ], 
                             columns=['Дата'],
                             aggfunc={'Планируемое техобслуживание': 'first'}).reset_index()

pivot_table = pivot_table.round(2)
pivot_table = pivot_table.fillna("")
# pivot_table=pivot_table.reset_index()
# Вывод обновленной сводной таблицы
pivot_table

In [ ]:
pivot_table.info()

In [ ]:
pivot_table_mod = pd.pivot_table(pivot_table, values=['Текущая наработка' ], 
                             index=['Дата','Подразделение', 'Марка', 'Инвентарный номер','Планируемое техобслуживание' ], 
                             
                             aggfunc={'Текущая наработка':'last'})

pivot_table_mod = pivot_table_mod.round(2)
pivot_table_mod = pivot_table_mod.fillna("")
pivot_table_mod=pivot_table_mod.reset_index()
# Вывод обновленной сводной таблицы
pivot_table_mod

In [ ]:
import openpyxl 
import xlwings as xw

In [ ]:
app = xw.App(visible=False)

In [ ]:
wb = xw.Book(r'c:\Users\poisk-12\Documents\$Механики\Агрегатный журнал сводный(Power Query).xlsx')
#wb = xw.Book(r'C:/Users/poisk-12/YandexDisk-shirobokov@pskgold.ru/Контроль ТО/Агрегатный журнал сводный(Power Query).xlsx')

In [ ]:
sheet_name = "Планируемое_ТО"
ws = None

In [ ]:
# Проверка наличия листа "Планируемое ТО"
for sheet in wb.sheets:
    if sheet.name == sheet_name:
        ws = sheet
        break

In [ ]:

# Если лист "Планируемое ТО" не существует, создаем новый лист
if ws is None:
    ws = wb.sheets.add(sheet_name)

# Очищаем содержимое листа
ws.clear()

# Вставка формулы =сегодня() в ячейку A1
ws["A1"].value = "=сегодня()"
ws["A1"].api.Font.Color = -16776961  # Красный цвет
ws["A1"].api.NumberFormat = "dd-mm-yyyy"

In [ ]:
ws["A4"].options(pd.DataFrame, header=1, index=True, expand='table').value = pivot_table

In [ ]:
ws["A4"].expand("right").api.Font.Bold = True
ws["A4"].expand("down").api.Font.Bold = True
ws["A4"].expand("right").api.Borders.Weight = 2
ws["A4"].expand("down").api.Borders.Weight = 2

# Удаление 4-й строки
ws.range("4:4").delete(shift="up")

In [ ]:

# Выравнивание столбцов с 5 по 10 по центру
ws.range("E:X").api.HorizontalAlignment = -4108  # Выравнивание по центру

# Заливка данных чередованием оранжевого и белого цвета
#data_range = ws.range("A2").expand("table")  # Диапазон данных (без заголовков)
#rows_count = data_range.rows.count


current_dir = os.getcwd()

wb.save(r'c:\Users\poisk-12\Documents\$Механики\Агрегатный журнал сводный(Power Query).xlsx')
#wb.save(r'C:/Users/poisk-12/YandexDisk-shirobokov@pskgold.ru/Контроль ТО/Агрегатный журнал сводный(Power Query).xlsx')
app.quit()

сгруппировать. Добавить файл Игоря Николаевича

In [ ]:
df_=pd.read_excel(r'C:\Users\poisk-12\YandexDisk-shirobokov@pskgold.ru\$2025\прогноз наработки на 24-25 (в2) (4).xlsx', "Расчет наработки")

In [ ]:
df_.columns=df_.loc[0]

In [ ]:
df_=df_.drop(df_.index[0])

In [ ]:
df_['модель 1 вар'].unique()

In [ ]:
df_['модель 1 вар']=df_['модель 1 вар'].replace({'CX-800B':'CASE','ECD-50E':'ECD50E', 'HD465-7':'HD-465','SD-22':'Shantui SD22','SHANTUI SL50W':'SL50W','TD16':'TD-16','ЭКГ-5А':'ЭКГ','ZX-870-5G':'ZX-870','D65EX':'D-65','CGET-PRD55':'D-55'})
df_agr=pivot_table_reset.copy()
df_agr['Марка']=df_agr['Марка'].replace({'SD22':'Shantui SD22'})
df_agr['Марка'].unique()
# Условие для выбора строк с указанными инвентарными номерами
condition = (new_df['Инвентарный номер'] == '789')|(new_df['Инвентарный номер'] == '790')

# Использование np.where для замены значений в столбце 'Марка' при выполнении условия
new_df.loc[condition, 'Марка'] = 'БелАЗ 7555В'
df_=df_.rename(columns={'инв номер':'Инвентарный номер',
                       'модель 1 вар':'Марка'
                       
                       
                       })
df_=df_[['Марка','Инвентарный номер','Прогноз наработки часов на 30.09.24']]

3. Смерджим наработку агрегатного журнала

In [ ]:
new_df['Марка'] = new_df['Марка'].astype(str)
df_['Марка'] = df_['Марка'].astype(str)
new_df['Инвентарный номер'] = new_df['Инвентарный номер'].astype(str)
df_['Инвентарный номер'] = df_['Инвентарный номер'].astype(str)

In [ ]:
matches = new_df.merge(df_, on=['Марка', 'Инвентарный номер'], how='inner')
print(f'Число совпадений: {len(matches)}')

In [ ]:
result=new_df.merge(df_, on=['Марка', 'Инвентарный номер'], how='left')

In [ ]:
condition=pd.isna(result['Прогноз наработки часов на 30.09.24'])
result['Наработка машины_2']=np.where(condition, result['Наработка машины'],result['Прогноз наработки часов на 30.09.24'])

In [ ]:
result['Наработка машины']=result['Наработка машины_2']
result=result.drop(columns='Наработка машины_2')